### ISSUE TITLE
Create lobid-resources repo fo API 2.0 and show example of new json ld transformation

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1]
The API 2.0 hbz catalog transformation will be considerably different than the old one used in 'https://github.com/lobid/lodmill'.
For a start:

- show how to transform N-Triples to compacted and framed JSON-LD
- the outcome should be indexed into elasticsearch
- write a short documentation

**Comment by acka47** [comment]
See also https://github.com/hbz/lobid/issues/172.

**Comment by acka47** [comment]
This may overlap with https://github.com/lobid/lodmill/issues/449.

**Comment by acka47** [comment]
Can't we close this one?

**Comment by acka47** [comment]
Forget my last comment. Just saw that #2 isn't merged. The repo already exists though...

**Comment by dr0i** [comment]
Yeah, no we can't close as the presumptions of the issue were quite bold (see above) and are not fullfilled yet.

**Comment by acka47** [comment]
Thanks for adjusting the title accordingly.

**Comment by acka47** [comment]
For a documentation of test usage of JSON-LD framing see https://github.com/lobid/lodmill/issues/433.

**Comment by acka47** [comment]
The JSON-LD frame is quite easy. This suffices:

```javascript
{
  "@context": "http://lobid.org/context/lobid-resources.json",
  "@type": "http://purl.org/dc/terms/BibliographicResource"
}
```

Unfortunately, the arrays for creators/contributors and subjects aren't sorted according to the source data as we would like them to. For this, we will need to 
1. add the order in N-Triples as RDF list or
2. discard this approach and move on like we intended to first, i.e. directly creating JSON-LD from source data with Metafacture.

**Comment by jschnasse** [comment]
For Api 2.0 , I´d suggest another trick. It would be nice to always get a prefLabel as a side car to all occurrences of @id (in document AND in context) . The usage of prefLabel would give clients a simple, unified and intuitive way to access the index and to mock views on lobid data. It can also be useful for configuring the index (e.g. boosting prefLabel). 
Some examples:
- in case of gnd-ids the preferredName should be provided as prefLabel, same for gnd-subjects
- for skos vocabs, a prefLabel comes together with the uris
- for the @ids in the context you can use tools like [etikett](https://github.com/hbz/etikett)

**Comment by acka47** [comment]
Adding to my last comment. The result of the framing has to be post-processed:

1. the `@graph` array must be removed
2. the blank node `@id`s for the multiVolumeWork/series relation have to be removed.

**Comment by acka47** [comment]
I created a simplified example.

# JSON-LD file

```javascript
{
  "@graph" : [ {
    "@id" : "http://d-nb.info/gnd/1060772442",
    "preferredName" : "Pfarrei St. Joseph und St. Antonius Bergisch Gladbach",
    "preferredNameForTheCorporateBody" : "Pfarrei St. Joseph und St. Antonius Bergisch Gladbach",
    "preferredNameForThePerson" : "Pfarrei St. Joseph und St. Antonius Bergisch Gladbach"
  }, {
    "@id" : "http://d-nb.info/gnd/172845785",
    "preferredName" : "Clemens-Schierbaum, Ursula, 1963-",
    "preferredNameForThePerson" : "Clemens-Schierbaum, Ursula, 1963-"
  }, {
    "@id" : "http://d-nb.info/gnd/2175350-7",
    "preferredName" : "Pfarrei Sankt Antonius Abbas Herkenrath",
    "preferredNameForTheCorporateBody" : "Pfarrei Sankt Antonius Abbas Herkenrath",
    "preferredNameForThePerson" : "Pfarrei Sankt Antonius Abbas Herkenrath"
  }, {
    "@id" : "http://lobid.org/resource/HT018454638",
    "@type" : [ "http://purl.org/dc/terms/BibliographicResource", "http://purl.org/ontology/bibo/Book" ],
    "contributor" : [ "http://d-nb.info/gnd/1060772442", "http://d-nb.info/gnd/2175350-7", "http://d-nb.info/gnd/172845785" ],
    "language" : "http://id.loc.gov/vocabulary/iso639-2/deu",
    "medium" : "http://rdvocab.info/termList/RDAproductionMethod/1010",
    "subject" : [ "http://d-nb.info/gnd/2175350-7", "http://d-nb.info/gnd/1060772442" ],
    "exemplar" : [ "http://lobid.org/item/HT018454638:DE-Kn28:Fc%206601", "http://lobid.org/item/HT018454638:DE-5-39:Gb%207470%2F201" ],
        "describedBy" : "http://lobid.org/resource/HT018454638/about"
  } ],
  "@id" : "http://lobid.org/resource/HT018454638/about",
  "dateCreated" : "20141111",
  "dateModified" : "20150303",
  "@context" : "http://lobid.org/context/lobid-resources.json"
}
```

# Frame

:exclamation: Note that I am using `@list` as well as `@set in the example.

```javascript
{
	"@type": "http://purl.org/dc/terms/BibliographicResource",
	"@context": {
		"preferredName": "http://d-nb.info/standards/elementset/gnd#preferredName",
		"preferredNameForTheCorporateBody": "http://d-nb.info/standards/elementset/gnd#preferredNameForTheCorporateBody",
		"preferredNameForThePerson": "http://d-nb.info/standards/elementset/gnd#preferredNameForThePerson",
		"contributor": {
			"@type": "@id",
			"@id": "http://purl.org/dc/terms/contributor",
			"@container": "@list"
			},
		"language": {
			"@id": "http://purl.org/dc/terms/language",
			"@type": "@id",
			"@container": "@set"
			},
		"medium": {
			"@type": "@id",
			"@id": "http://purl.org/dc/terms/medium",
			"@container": "@set"
			},
	"subject": {
		"@id": "http://purl.org/dc/terms/subject",
		"@type": "@id",
		"@container": "@list"
		},
	"exemplar": {
		"@type": "@id",
		"@id": "http://purl.org/vocab/frbr/core#exemplar",
		"@container": "@set"
		},
	"dateCreated": "http://purl.org/dc/terms/created",
	"dateModified": "http://purl.org/dc/terms/modified",
	"describedBy": {
		"@type": "@id",
		"@id": "http://www.w3.org/2007/05/powder-s#describedby"
		}
	}
}
```

# Playground

Using both in the playground doesn't give an error but strangely the keys for a `@list` that is an array of objects become URIs again. See http://tinyurl.com/qzfp588.

**Comment by acka47** [comment]
I noticed another problem with the fram from https://github.com/hbz/lobid-resources/issues/1#issuecomment-143729040:

If one GND resource is both creator/contributor and subject it is only expanded under one property, see http://tinyurl.com/oa85e39. We will have to keep this in mind.

**Comment by acka47** [comment]
Please see https://github.com/hbz/lobid-resources/issues/4#issuecomment-144653116 for an example of an expected outcome.

**Comment by dr0i** [comment]
@acka47 Please have a look if  #11 fullfills this issue's demands. I found [HT015891797](https://github.com/hbz/lobid-resources/blob/master/src/test/resources/jsonld/HT015891797) a good example.

If this issue is closed we can go on to implement the other needs (HashBang URIS etc.).

**Comment by acka47** [comment]
+1 I guess we should close this one at last. There is still a lot of stuff in the records that won't be part of API 2.0 (e.g. `contributorLabel`, `subjectLabel`, `subjectChain`) and we will definitely do some more changes (see e.g. #10 ). But this is very good for the start.
