### ISSUE TITLE
Some geo points are too broad 

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1001]
From https://github.com/hbz/lobid-resources/issues/998#issuecomment-498146504:

> As discussed offline, we will have to think about the broader regions (e.g. Eifel, Weserbergland, or Nordrhein-Westfalen itself) that have one geo point attached. it does not make sense to use those geo coordinates for the "result map". So we have to think about a way to handle this (ignoring these coordinates or not storing them to begin with).

**Comment by acka47** [comment]
We opened another issue for this, see https://github.com/hbz/nwbib/issues/494. As the discussion there is already more detailed, I am closing this one.
