### ISSUE TITLE
ISBN10 and ISBN13

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1002]
Working on #201 I recognize that we don't generate both forms of the ISBN even if this would be possible. As verbundgruppe asked about this feature we should provide it.

**Comment by TobiasNx** [comment]
In lobid-resources for ALMA we have a solution for this:

```XML
  <data source="020  .a" name="@cleanIsbn">
    <isbn to="clean"/>
    <unique />
  </data>

  <entity name="isbn[]" flushWith="record">
    <data name="" source="@cleanIsbn">
      <isbn to="isbn10"/>
      <unique />
    </data>
    <data name="" source="@cleanIsbn">
      <isbn to="isbn13"/>
      <unique />
    </data>
  </entity>
```
This should work in ALEPH with little adaption.

**Comment by TobiasNx** [comment]
ALMA-FIX can do this. @acka47 : We won't fix this for ALEPH right?
