### ISSUE TITLE
Missing data in note field

### ISSUE THREAD

**Issue by hagbeck** [hbz/lobid-resources#1009]
In the record HT020008571 the value "Seite 76-80" in the note field is not complete. 
The value in the original footnote field starts with "Literaturverzeichnis: ". 
So I expect "Literaturverzeichnis: Seite 76-80".

**Comment by acka47** [comment]
Thanks for the report. We will deal with it as soon as vacation time is over. From the source:

```xml
<datafield tag="501" ind1="-" ind2="1">
  <subfield code="p">Literaturverzeichnis</subfield>
  <subfield code="a">Seite 76-80</subfield>
</datafield>
```

Currently, we only use subfield `a` for the `note` field. See the morph:

https://github.com/hbz/lobid-resources/blob/397c648375ea444fdef1885f7d6e061e3865f1b5/src/main/resources/morph-hbz01-to-lobid.xml#L7555-L7559

**Comment by dr0i** [comment]
@hagbeck please have a look, data should be there now.

**Comment by fsteeg** [comment]
Closing, see: http://lobid.org/resources/HT020008571.json
