### ISSUE TITLE
Don't entrich maps with subject from superordinated resources

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1011]
Reported by NWbib editor I.N. via email on 2019-08-02:

Am 02.08.19 um 16:08 schrieb I.N.:
...
> uns ist aufgefallen, dass bei Karten durch die automatische Anreicherung 
> der Bandsätze mit der Schlagwortfolge der Überordnung (z.B. ÜO 
> HT015332726 SW: Nordrhein-Westfalen ; Landkreis ; Karte) eine thematisch 
> nicht passende Schlagwortfolge bei den Bandsätzen erzeugt wird.
> 
> Die Bandsätze verzeichnen die Einzelkarten zu einem bestimmtem Kreis 
> oder Ort und müssten nach RSWK thematisch enger d.h. mit dem 
> entsprechenden geographischen Namen beschlagwortet werden.
> 
> Können Sie die Anreicherung der Bandsätze *bei *den *Karten* 
> unterdrücken bzw. auch wieder rückgängig machen?
> 
> Die Information, dass es sich um eine Karte handelt, steht bei 
> RAK-Aufnahmen im Feld 050 = Datenträger (Position 10 Landkarten „a“) und 
> bei RDA-Aufnahmen im Feld 064a „Karte“. Im Json-Format gibt es am Anfang 
> des Datensatzes den Eintrag „type: [… „Map“…].

**Examples**

http://lobid.org/resources/HT016642623

NWBib-Screenshot:

![image](https://user-images.githubusercontent.com/160292/63267576-b0477e80-c292-11e9-9695-b9b3eb0c2b7f.png)

http://lobid.org/resources/HT015373288

NWBib-Screenshot:

![image](https://user-images.githubusercontent.com/160292/63267655-d53bf180-c292-11e9-8474-5b31a8418780.png)

**Comment by acka47** [comment]
Source snippet for the first example:

```xml
<datafield tag="902" ind1="-" ind2="2">
  <subfield code="g">Nordrhein-Westfalen</subfield>
  <subfield code="9">(DE-588)4042570-8</subfield>
</datafield>
<datafield tag="902" ind1="-" ind2="2">
  <subfield code="s">Landkreis</subfield>
  <subfield code="9">(DE-588)4073976-4</subfield>
</datafield>
<datafield tag="902" ind1="-" ind2="2">
  <subfield code="f">Karte</subfield>
</datafield>
<datafield tag="903" ind1="-" ind2="2">
  <subfield code="a">213</subfield>
</datafield>
<datafield tag="907" ind1="-" ind2="1">
  <subfield code="g">Kreis Coesfeld</subfield>
  <subfield code="9">(DE-588)4010356-0</subfield>
</datafield>
<datafield tag="907" ind1="-" ind2="1">
  <subfield code="f">Karte</subfield>
</datafield>
```

For maps, we only want those 9-- fiels transformed  with `in2="1"`. What is typed as `biboMap` is defined like this:

https://github.com/hbz/lobid-resources/blob/0e890caf74fee8ae51db0aedb9ba89eb3f35ff64/src/main/resources/morph-hbz01-to-lobid.xml#L1701-L1709

**Comment by dr0i** [comment]
Seems ridiculous hard to achieve this.
So my question is:
it would be easy to just get rid of the superordinated subject chain in whole, for every resource.
Would this be a solution?

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
Fixed with #1024. Closing.
