### ISSUE TITLE
Remove redundant occurence of NWBib notations 35, 36, 37 from data

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1012]
Most NWBib records with the spatial notations 35, 36, 37 in `700n.a` also have an entry in `700n.b`. Examples:

HT017536715 ([source](http://lobid.org/hbz01/HT017536715), [JSON](http://lobid.org/resources/HT017536715.json)):

```xml
<datafield tag="700" ind1="n" ind2="1">
  <subfield code="a">35</subfield>
  <subfield code="b">Kirchenkreis An der Ruhr</subfield>
</datafield>
```

HT020082521 ([source](http://lobid.org/hbz01/HT020082521), [JSON](http://lobid.org/resources/HT020082521.json)):

```xml
<datafield tag="700" ind1="n" ind2="1">
  <subfield code="a">36</subfield>
  <subfield code="b">Diözese Münster (Westf)</subfield>
</datafield>
```

HT017206874 ([source](http://lobid.org/hbz01/HT017206874), [JSON](http://lobid.org/resources/HT017206874.json)):

```xml
<datafield tag="700" ind1="n" ind2="1">
  <subfield code="a">37</subfield>
  <subfield code="b">Dekanat Ahlen</subfield>
</datafield>
```

This information in 700n is currently transformed into two objects in the `spatial` array (in the JSON-LD). For example [HT017536715](http://lobid.org/resources/HT017536715.json):

```json
{
   "spatial":[
      {
         "id":"https://nwbib.de/spatial#N35",
         "type":[
            "Concept"
         ],
         "source":{
            "id":"https://nwbib.de/spatial",
            "label":"Raumsystematik der Nordrhein-Westfälischen Bibliographie"
         },
         "notation":"35",
         "label":"Evangelische Kirche. Kirchenkreise"
      },
      {
         "focus":{
            "id":"http://www.wikidata.org/entity/Q63078887",
            "type":[
               "http://www.wikidata.org/entity/Q897303"
            ]
         },
         "id":"https://nwbib.de/spatial#Q63078887",
         "type":[
            "Concept"
         ],
         "label":"Kirchenkreis An der Ruhr",
         "source":{
            "id":"https://nwbib.de/spatial",
            "label":"Raumsystematik der Nordrhein-Westfälischen Bibliographie"
         }
      }
   ]
}
```

**To Do**:

The spatial object that is generated from `700n.a` (the 1st one in the above example) has to be removed from the data, for the notations 35, 36, 37. 

:exclamation:  **Note**

There are also some entries with only information in `700n.a.`. Those records have to retain the `spatial` object generated from this subfield. Example BT000071273 ([source](http://lobid.org/hbz01/BT000071273), [JSON](http://lobid.org/resources/BT000071273.json)):

```xml
<datafield tag="700" ind1="n" ind2="1">
  <subfield code="a">36</subfield>
</datafield>
```

**Comment by acka47** [comment]
This is basically the same as we already do with notation 99. The relevant part of the morph must be: https://github.com/hbz/lobid-resources/blob/00416a031d0b166cae1054a8c2d0d3f52f463c0e/src/main/resources/morph-hbz01-to-lobid.xml#L7326-L7336

**Comment by acka47** [comment]
@dr0i, bitte übernehmen Sie.

**Comment by acka47** [comment]
As this is deployed on staging, I made a functional review. Everything looks as requested. Thanks. +1

**Comment by dr0i** [comment]
Deployed to production, closing.

**Comment by acka47** [comment]
Reopening: To Do: Write email to NWBib editors.

**Comment by acka47** [comment]
Mail is out. Closing
