### ISSUE TITLE
Adjust notations for Westfalen & Euregio

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1018]
To be implemented together with #1017.

We have to replace the URI and notation for Westfalen and Euregio:

1. Westfalen: `05` -> `04` (respectively `https://nwbib.de/spatial#N05` -> `https://nwbib.de/spatial#N04`)
2. Euregio: `91` -> `07` (respectively `https://nwbib.de/spatial#N91` -> `https://nwbib.de/spatial#N07`)

I think, this means adding two exceptions to these lines in the morph: 
https://github.com/hbz/lobid-resources/blob/0e890caf74fee8ae51db0aedb9ba89eb3f35ff64/src/main/resources/morph-hbz01-to-lobid.xml#L7340-L7344

**Comment by dr0i** [comment]
I assume these URIs should be changed for all the possible statements, not only for subjects?

**Comment by dr0i** [comment]
Thinking about it - wouldn't be the _data_ the right place to change this?
I mean, if we feed #N05 and transform it to #N04, this makes the whole process overly complicated and intransparent and just mindbogglingcrazy, doesn't it? So why not turn underlying data  #N05 into #N04 before doing crazy stuff?

**Comment by dr0i** [comment]
@fsteeg as agreed with @acka47 it would be nicer to do this workaround in the UI - would that be ok for you?

**Comment by dr0i** [comment]
Agreed offline to wait for the data to be corrected. An email is sent to stakeholders asking for confirmation.

**Comment by acka47** [comment]
Euregios are already updated the rest is in progress. With the updates for hbz01, all 05 entries will be updated to `Westfalen$$0https://nwbib.de/spatial#N04`. We will have to check in January whether everything worked fine

**Comment by acka47** [comment]
Everything workd fine. Closing.
