### ISSUE TITLE
Link to the MAB XML open data dumps

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1023]
As E.S. from Digib asked where to find the open data MAB XML Clob data dumps:
we should link to the [download page](https://lobid.org/download/dumps/DE-605/mabxml/) at the [description site](https://lobid.org/resources) so it's easier to find.

**Comment by acka47** [comment]
There is a link to the datahub entry at https://lobid.org/resources/dataset.

**Comment by dr0i** [comment]
Aha, but this site seems to be somehow a bit hidden for people not looking into the rdf data. To improve this we could:
1. link to the _dataset_ site at https://lobid.org/resources
2. as described above direct link to the fulldump location

What do you think?

**Comment by acka47** [comment]
My suggestion: 

1. Link to the dataset description from https://lobid.org/resources
2. Directl link to https://lobid.org/download/dumps/DE-605/mabxml/ instead of datahub from dataset description.

**Comment by dr0i** [comment]
Re 1 and 3 : What do you think about to substitue https://lobid.org/resources with https://lobid.org/resources/dataset?

**Comment by dr0i** [comment]
Did as you proposed @acka47 . Please have a look.

**Comment by dr0i** [comment]
Deployed to staging, see https://stage.lobid.org/resources and https://stage.lobid.org/resources/dataset.

**Comment by acka47** [comment]
I adjusted the dataset description a bit. Please redeploy to staging.

**Comment by dr0i** [comment]
I deployed it to production because I think it's fine now. Just a minor update - there was a "http" link in the description. @acka47 please close after a last look.

**Comment by acka47** [comment]
Closing.
