### ISSUE TITLE
Use rdfs:label instead of gnd:preferredName

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#103]
[edit @dr0i:] Also, update the [context](http://lobid.org/download/contextTmp.json) accordingly.

**Comment by acka47** [comment]
Perhaps better use http://schema.org/name and http://schema.org/alternateName?

**Comment by acka47** [comment]
> Perhaps better use http://schema.org/name and http://schema.org/alternateName?

We won't.

**Comment by acka47** [comment]
This should be done together with https://github.com/hbz/lobid-rdf-to-json/issues/24.Moving back to ready".

**Comment by acka47** [comment]
Also, the property currently used for the pref label (gnd:preferredName) can then be removed from the context.

**Comment by dr0i** [comment]
With https://github.com/hbz/lobid-rdf-to-json/issues/24 the `altLabel` is deployed in context. I will change the topic of this issue to `Use skos:label instead of gnd:preferredName`.

**Comment by acka47** [comment]
It's `rdfs:label`! Adjusting the title accordingly

**Comment by dr0i** [comment]
Deployed small test, see e.g. http://test.lobid.org/resources/HT018612706#!.

**Comment by acka47** [comment]
+1 for http://lobid.org/download/contextTmp.json, -1 for http://lobid.org/download/contextTmp-staging.json

**Comment by dr0i** [comment]
done

**Comment by acka47** [comment]
Now also +1 for http://lobid.org/download/contextTmp-staging.json

**Comment by acka47** [comment]
(BTW, we should move http://lobid.org/download/contextTmp.json to http://lobid.org/download/context.json at some point.)

**Comment by dr0i** [comment]
Renamed the `context` and deployed small set , deliberately not with the  the `context-staging`-paramter to test the use of the production.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
