### ISSUE TITLE
NullPointer Exception using more Threads than documents

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1030]
Experienced this when shrinking the hbz01XmlClobs.tar.bz2 test set to one, while there are two threads to compute the data. When calling `closeStream()`, a NullPointer Exception appears. This stops the ETL process finishing correctly, and thus no resource (aka document) is serialized to the disk.
A workaround is to catch the Exception.
However, as this is a problem can occur everywhere, it would be nicer to somehow control this at the modules in metafacture-core, probably at the [ObjectPipeDecoupler](https://github.com/metafacture/metafacture-core/blob/cb43933ec8eb01a4ddce4019c14b2415cc441918/metafacture-flowcontrol/src/main/java/org/metafacture/flowcontrol/ObjectPipeDecoupler.java). Also, to say the least, it's rather unexpected to use more threads than documents, it _may_ happen.

**Comment by acka47** [comment]
@dr0i Does this problem still exist? Shouldn't we open issue over at metafacture-core then and close this one?

**Comment by dr0i** [comment]
Problem still exists. Opened https://github.com/metafacture/metafacture-core/issues/466. Closing this one.
