### ISSUE TITLE
Some missing spatial.focus objects

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1034]
From https://github.com/hbz/lobid-resources/issues/1029#issuecomment-539456142 :

http://lobid.org/resources/search?q=_exists_%3Aspatial+AND+NOT+_exists_%3Aspatial.focus

shows 818 resources missing the spatial.focus objects. These are not in the generated nwbib-spatial.csv, which is generated using the skos.ttl, while indeed they exist in the skos file.

**Comment by acka47** [comment]
I don't think this is an issue. There are some entries without a `foaf:focus` in the SKOS vocab and as far as I can see the 818 entries have exactly those in `spatial`. Where did you see anything contrary, @dr0i ?

**Comment by dr0i** [comment]
Ah, ok, that's the problem! So all programs work as they should, and this is no bug.
Thx for the hint - closing.
