### ISSUE TITLE
ISBN for parallel manifestations not included

### ISSUE THREAD

**Issue by hagbeck** [hbz/lobid-resources#1039]
Is it possible to include the ISBNs for parallel manifestations (e-book if print and vice versa)?

Example:
For https://lobid.org/resources/HT020114939 (e-book) the MAB record contains the ISBN for the printed version in field 776.

**Comment by acka47** [comment]
Thanks for the request, Hans-Georg. I am not sure we will be able to approach this before January but maybe we will find some time in December.

Here is the content of `776`:

```xml
<datafield tag="776" ind1="-" ind2="1">
  <subfield code="i">Printed edition</subfield>
  <subfield code="z">9783662581711</subfield>
</datafield>
```

**Comment by acka47** [comment]
I suggest to add it as a bnode in the `similar` array with content from subfield `i` as `note`:

```json
{
    "similar":[
        {
            "id":"http://dx.doi.org/10.1007/978-3-662-58172-8",
            "label":"978-3-662-58172-8"
        },
        {
            "isbn":"9783662581711",
            "note":"Printed edition"
        }
    ]
}
```

**Comment by acka47** [comment]
Reviewing this on production, I noticed that the ISBNs are not normalized as we usually do, this means sometime the might contain hyphens or spaces in `similar.isbn`. For example https://lobid.org/resources/HT019474284.json:

```json
{
   "similar":[
      {
         "note":"Erscheint auch als",
         "isbn":[
            "978-3-319-32415-9"
         ]
      }
   ]
}
```

I guess, we should also normalize them in this field, shouldn't we?

**Comment by acka47** [comment]
> I guess, we should also normalize them in this field

However, it is ok to merge this now and do the normalization in the next step.

**Comment by dr0i** [comment]
Normalized `similar.isbn`.Review whole data from Wednesday on.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, see e.g. https://lobid.org/resources/HT019474284.json. Closing
