### ISSUE TITLE
Fill "fulltextOnline" if 655...x=Verlag && 655...z=kostenfrei

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1044]
From an email thread with subject `Anzeige Titelaufnahme Website "Euregio-history.net" u.a.`:

> "damit auch bei Einträgen mit Unterfeld x "Verlag" und Unterfeld z "kostenfrei" der Link 
ergänzt wird."

This sounds reasonable.

**Comment by dr0i** [comment]
Will be deployed to staging at wednesday. Check then http://lobid.org/resources/HT020282074.

**Comment by dr0i** [comment]
Looks good http://stage.lobid.org/resources/HT020282074 .
Coverage increased from 0.84M to 1.15, though the quality of these links is often enough bad (unresolvable; TOCs instead of fulltexts; redundant...).

**Comment by acka47** [comment]
Obviously, this also added fulltext links for resources that only have subfield `x` with "Verlag" but not "kostenfrei" in `z`, e.g. HT019969981 ([source](http://lobid.org/hbz01/HT019969981)):

```xml
<datafield tag="655" ind1="e" ind2="1">
  <subfield code="u">https://www.degruyter.com/...</subfield>
  <subfield code="x">Verlag</subfield>
  <subfield code="A">0</subfield>
</datafield>
```

From the JSON:

```json
{
    "fulltextOnline":[
        {
            "id":"https://www.degruyter.com/...",
            "label":"..."
        }
    ]
}
```

**Comment by dr0i** [comment]
This was triggered by the existence of field `334`. It is now reverted and thus no more `fulltextOnline` for HT019969981.
Now there are not 300k but 25k more links to fulltexts. As they are presumably of higher quality, we shall be delightful altogether.
