### ISSUE TITLE
Provide regular fulldumps as jsonl

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1048]
As bulk download can cause problems like the one reported by @hagbeck :

> > curl "http://lobid.org/resources/search?q=*&format=bulk" -o
> 2019-12-21_lobid.gz
>    % Total    % Received % Xferd  Average Speed   Time    Time     Time
> Current
>                                   Dload  Upload   Total   Spent    Left
> Speed
> 100 7688M    0 7688M    0     0  2139k      0 --:--:--  1:01:19 --:--:--
>      0
> curl: (18) transfer closed with outstanding read data remaining

it would be good to provide regularly fulldumps of json at http://lobid.org/download/dumps/DE-605/lod/ which then can be complemented by bulk-downloading using e.g. `http://lobid.org/resources/search?q=describedBy.dateCreated:[20200101%20TO%2020200110]&format=json`.

Not clear if this is related to https://github.com/hbz/lobid/issues/335 or https://github.com/hbz/lobid/issues/188 or an issue of its own. Providing regulary fulldumps, however, would be a workaround for at least the latter.

**Comment by dr0i** [comment]
As @hagbeck asks for it again #1070 provides a script to get the data in smaller packages.·
A [new dump (8.4 GB)](http://lobid.org/download/dumps/DE-605/lod/resources.tar) was created using the script. Experienced the `transfer closed` issue several times doing the dump myself. As the dump is parted in smaller packages (one per year starting from `describedBy.dateCreated:1980`) an errored dump could be retried until it's working.
·
If you want to update the provided dump yourself,  use this as template:
`curl --header "Accept-Encoding: gzip" "http://lobid.org/resources/search?q=describedBy.dateCreated:[$FROM_INITIAL%20TO%20$TO_INITIAL]&format=bulk`

*Note*: starting with the initially provided dump (done at 2020-06-15) deletions are naturally not considered. The deleted resources can be lookuped too, see the [API decription](http://www.lobid.org/resources/api), e.g.:
https://www.lobid.org/resources/deletions/search?q=describedBy.deleted%3A[20200615+TO+20200617]&size=9999
(to not get too much data step through it by doing several API calls (e.g. by getting 10 days consecutively). Check that `totalItems` are smaller than the value of `size` and note that `size` cannot be >9999.)

This issue is kept open for there is nothing scheduled to provide regular dumps. If the need arises again, we may be punched to adapt the script to do so.

Note also that you can always get the [weekly created fulldump of the mabxml original data](http://lobid.org/download/dumps/DE-605/mabxml/) and ETL it with the code of this repository.

**Comment by hagbeck** [comment]
Unpacking the "new dump" I'm getting an error for 20200101-20210101.jsonl.gz: 

gzip: 20200101-20210101.jsonl.gz: unexpected end of file

The other part are ok.

**Comment by dr0i** [comment]
Uh, you are right.
Updated `resources.tar`.
You can download the one package here: http://lobid.org/download/dumps/DE-605/lod/resources/20190101-20200101.jsonl.gz

**Comment by dr0i** [comment]
Moving to backlog for @hagbeck gave thumbs up.

**Comment by TobiasNx** [comment]
@dr0i Backend or Frontend?
