### ISSUE TITLE
Wrong label for subject

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1049]
NWBib customer S K-L reported a component list object having a wrong label assoiated with the correct id. Interestingly, the composed label for the whole component-list is ok. E.g. `HT018260267`:
>  "componentList": [
{
"id": "https://d-nb.info/gnd/4035322-9",
"type": [
"PlaceOrGeographicName"
],
"source": {
"id": "https://d-nb.info/gnd/7749153-1",
"label": "Gemeinsame Normdatei (GND)"
},
"label": "Sachsen. Landesvermessungsamt",
"gndIdentifier": "4035322-9"
}, 
...
"label": "Lengerich, Kreis Steinfurt | Topografie | Karte "

where `Lengerich, Kreis Steinfurt` would be the correct label for `https://d-nb.info/gnd/7749153-1`.

**Comment by dr0i** [comment]
Issue should be resolved. @acka47  do you inform customers?

**Comment by acka47** [comment]
Done, closing.
