### ISSUE TITLE
Pretty print JSON-LD

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#105]
It's already implemented for lobid-organisations, see https://github.com/hbz/lobid-organisations/issues/85

**Comment by dr0i** [comment]
Done, see e.g. `curl http://lobid.org/resources/HT018786244#!`.
(Just had to append `pretty=1` at the ULR in apache rewriteRule proxying to elasticsearch daemon).

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
Closing.
