### ISSUE TITLE
Subfields c sometimes not transformed to RDF

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1051]
Reported via email today by I.N.:

On 30.01.20 13:00, I.N. wrote:
> ...
> Uns ist aufgefallen, dass bei einigen Schlagwörtern die Unterfelder 
> nicht angezeigt werden. Hier einige Beispiele:
> 

- [x]  Veranstaltungsfolge (Entität = vif):  Karussell der Jugend |c Soest und 
> Allerheiligenkirmes |c Soest ->  [Unterfeld c = Ort wird nicht angezeigt]
> 
> https://nwbib.de/HT020297152
> 
- [x] Einzel-Veranstaltung (Entität = vie) : Regionale |h Nordrhein-Westfalen 
> |n 8. |d 2016 |c Münsterland, West -> [Unterfeld h = Zusatz wird nicht 
> angezeigt]
> 
> https://nwbib.de/HT019965834
> 
> Anmerkung: Die Unterfeldkategorie „h“ scheint nicht die Ursache zu sein, 
> denn bei anderen Schlagwort-Entitäten (gib, giw, snz, saz, szz) wird das 
> Unterfeld h angezeigt:
> Wasserschloss Nordkirchen |h Nordkirchen https://nwbib.de/HT019807646 
> <https://nwbib.de/HT019807646>
>   Alte Dorfstraße |h Münster (Westf) https://nwbib.de/HT020018562 
> <https://nwbib.de/HT020018562>
>  Bienen |h Familie https://nwbib.de/HT017839863 
> <https://nwbib.de/HT017839863>
> Religion |h Motiv https://nwbib.de/HT020073161 
> <https://nwbib.de/HT020073161>
> Alter |h 70-90Jahre https://nwbib.de/HT019983503 
> <https://nwbib.de/HT019983503>

From the first example (http://lobid.org/resources/HT020297152.json):

```json
"subject": [
        {
        "type": [
            "ComplexSubject"
        ],
        "componentList": [
            {
                "id": "https://d-nb.info/gnd/1200563662",
                "type": [
                    "ConferenceOrEvent"
                ],
                "source": {
                    "id": "https://d-nb.info/gnd/7749153-1",
                    "label": "Gemeinsame Normdatei (GND)"
                },
                "label": "Karussell der Jugend",
                "gndIdentifier": "1200563662"
            },
            {
                "type": [
                    "SubjectHeading"
                ],
                "label": "Geschichte 1959-1971"
            }
        ],
        "label": "Karussell der Jugend, Soest | Geschichte 1959-1971"
    },
    {
        "type": [
            "ComplexSubject"
        ],
        "componentList": [
            {
                "id": "https://d-nb.info/gnd/7677592-6",
                "type": [
                    "ConferenceOrEvent"
                ],
                "source": {
                    "id": "https://d-nb.info/gnd/7749153-1",
                    "label": "Gemeinsame Normdatei (GND)"
                },
                "label": "Allerheiligenkirmes",
                "gndIdentifier": "7677592-6"
            },
            ...
        ],
        "label": "Allerheiligenkirmes, Soest | Jugend | Tanzveranstaltung | Geschichte 1959-1971"
    }
]
```

For both subjects, there is the "Soest" missing in `subject.ComponentList.label` although it is there in `subject.label`. From the [source](http://lobid.org/hbz01/HT020297152):

```xml
<datafield tag="902" ind1="-" ind2="1">
    <subfield code="e">Karussell der Jugend</subfield>
    <subfield code="c">Soest</subfield>
    <subfield code="9">(DE-588)1200563662</subfield>
</datafield>
<datafield tag="907" ind1="-" ind2="1">
    <subfield code="e">Allerheiligenkirmes</subfield>
    <subfield code="c">Soest</subfield>
    <subfield code="9">(DE-588)7677592-6</subfield>
</datafield>
```

**Comment by dr0i** [comment]
Deployed to production, closed.
