### ISSUE TITLE
Single hits errored because github has problems

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1067]
Rendering the single hit detail page results in a `gateway error` caused by a timeout when lookup `/isil2opac_hbzid.json`:

> 2020-04-23 16:01:15 +0200 [ERROR] from application in application-akka.actor.default-dispatcher-78 - Could not create OPAC URL
java.io.IOException: Server returned HTTP response code: 500 for URL: https://raw.githubusercontent.com/hbz/link-templates/master/isil2opac_hbzid.json

Today 1.2k views were affected.

It's better to load the isil2opac_hbzid.json as file, not via github web server, or/and to cache it.

**Comment by TobiasNx** [comment]
@fsteeg is this a backend or a frontend issue?

**Comment by fsteeg** [comment]
It's not a transformation issue, but a web app issue (there, it's a backend issue).

**Comment by dr0i** [comment]
This is resolved by #1915.
Closing.
