### ISSUE TITLE
Type in `subject`-array missing

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#107]
In http://lobid.org/resources/HT019035373 the type for the corporate body `http://d-nb.info/gnd/2047974-8` is missing.
See also hbz/lobid-rdf-to-json/issues/25.

**Comment by dr0i** [comment]
Most likely this is a result of https://github.com/hbz/lobid-rdf-to-json/issues/40.
Postponed until that issue is solved.

**Comment by dr0i** [comment]
Deployed small set, see e.g. http://test.lobid.org/resources/HT018771475 (look at "http://d-nb.info/gnd/1074109953").

**Comment by acka47** [comment]
+1
