### ISSUE TITLE
Add relation information to "related" objects

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1071]
This originates in a thread on the NWBib mailing list starting 2020-06-15 and named "Fwd: Feedback zu NWBib...". NWBib editors want the links to related resources from fields `527`, `775` und `776` shown in NWBib with the label from subfield `n` (at least for `776`). I.N. writes today (2020-06-22):

> wenn es für Sie leicht umzusetzen ist, die URL aus dem Feld "related" in die Nutzeroberfläche einzubinden, würden wir das Angebot gerne annehmen. Als Hinweistext sollte man die üblichen Bemerkungen aus dem Unterfeld "n" des Feldes 776 verwenden:  "Online-Ausgabe" bzw. "Druck-Ausgabe".

I.N. was responding to my email from 2020-06-17:

> wir haben die Links momentan bereits schon in den JSON-Daten unter 
> "related", siehe z.B. http://lobid.org/resources/HT020163348.json:
> 
> "related": [
>    {
>      "id": "http://lobid.org/resources/HT020163372#!",
>      "label": "Der Prozess der Berufsorientierung aus der Perspektive 
> der Schülerschaft mit sonderpädagogischem Unterstützungsbedarf im 
> Bereich Lernen an Förderschulen im Land Nordrhein-Westfalen"
>    }
> ]
> 
> Allerdings sind unter "related" auch Verweise aus den Feldern 527, 775 
> und 776 zu finden. Wir holen dafür die ID der verlinkte Ressource aus 
> Unterfeld 9 und das Label aus Unterfeld t bzw. bei 527 Unterfeld a. Die 
> Unterfelder i, n und a werden also bisher bei der Datentransformation 
> nicht berücksichtigt.

For reference, the links were added with #367 .

**Comment by acka47** [comment]
To Do: Find out whether there is a common way to get the information like `776.n` into the `related` node or whether the respective subfield may contain inconsistent data.

**Comment by acka47** [comment]
The [source data](http://lobid.org/hbz01/HT020163348) looks like this for the example HT020163348:

```xml
<datafield tag="776" ind1="-" ind2="1">
  <subfield code="i">Erscheint auch als</subfield>
  <subfield code="n">Online-Ausgabe, PDF</subfield>
  <subfield code="a">Hübner, Carina</subfield>
  <subfield code="t">
    Der Prozess der Berufsorientierung aus der Perspektive der Schülerschaft mit sonderpädagogischem Unterstützungsbedarf im Bereich Lernen an Förderschulen im Land Nordrhein-Westfalen
  </subfield>
  <subfield code="9">HT020163372</subfield>
</datafield>
```

If I understand it correctly, NWBib editors want to display something like this:

[Online-Ausgabe, PDF](https://nwbib.de/HT020163372)

For this, we need the content of subfield `n`. I suggest adding it as `note` in the `related` object like this and furthermore add the content of subfield `a` at the start of `label`:

```json
{
  "related":[
    {
      "id":"http://lobid.org/resources/HT020163372#!",
      "label":"Hübner, Carina: Der Prozess der Berufsorientierung aus der Perspektive der Schülerschaft mit sonderpädagogischem Unterstützungsbedarf im Bereich Lernen an Förderschulen im Land Nordrhein-Westfalen",
      "note":"Online-Ausgabe, PDF"
    }
  ]
}
```

**Comment by TobiasNx** [comment]
It seems that field 776 is similar in the alma transformation. I rearranged this here:

https://github.com/hbz/lobid-resources/commit/18976f6e5f05e0eeea781e7956ed2397e6a41266

There also existed a (similar) ticket for your task here: https://github.com/hbz/lobid-resources/issues/1090

**Comment by acka47** [comment]
> There also existed a (similar) ticket for your task here: #1090

Thanks for the hint. I prefer the approach in #1090 using `medium` instead of `note`. I suggest us three (@TobiasNx, @dr0i, @acka47) discuss how to proceed and then close one issue as duplicate. Would  tomorrow at 10 am be ok?
