### ISSUE TITLE
Document bulk (aka "scroll" or "dump") download 

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1073]
[API documentation](https://lobid.org/resources/api) is missing how to bulk-donwload bigger chunks of data.
Should be equivalent to https://lobid.org/gnd/api#bulk_downloads.

Complements https://github.com/hbz/lobid-resources/pull/372.

**Comment by acka47** [comment]
Actually, it is already documented but not in a separate paragraph. You can find it under [Inhaltstypen](https://lobid.org/resources/api#content_types):

> Er unterstützt Content-Negotiation für JSON (application/json), JSON lines (application/x-jsonlines), RSS (application/rss+xml) und HTML (text/html):
>
> `curl --header "Accept: application/json" https://lobid.org/resources/search?q=kunst`
>
> `curl --header "Accept: application/rss+xml" https://lobid.org/resources/search?q=kunst`
>
> `curl --header "Accept: application/x-jsonlines" https://lobid.org/resources/search?q=kunst > kunst.jsonl
>
> ...
> Für größere Anfragen kann die Antwort als gzip komprimiert werden:
>
> `curl --header "Accept-Encoding: gzip" "https://lobid.org/resources/search?q=ehrenfeld&format=jsonl" > ehrenfeld.gz`

I agree that it is inconsistent with the lobid-gnd API documentation and at some point we already discussed about this. So, +1 for aligning the documentations.

**Comment by dr0i** [comment]
Deployed on production.
Closing.
