### ISSUE TITLE
BEACON file broken: wrong gnd-URI, bnodes

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1075]
The '#TARGET' in the beacon still uses http-URIs instead of https. These don't resolve anymore.

See https://github.com/hbz/lobid-gnd/issues/243 announcing no longer supporting http lookups for gnd ids.

**Comment by acka47** [comment]
About which BEACON file are you talking? Can you provide a link?

**Comment by dr0i** [comment]
https://github.com/hbz/lobid-resources/issues/685

**Comment by acka47** [comment]
This probably is also a problem in the NWBib BEACON file. Please also take a look at that, @dr0i .

**Comment by dr0i** [comment]
Deployed, see https://lobid.org/download/beacons/hbzlod-pndbeacon.txt.

**Comment by acka47** [comment]
+1
