### ISSUE TITLE
Aleph Sources not accessible

### ISSUE THREAD

**Issue by schmitzd** [hbz/lobid-resources#1085]
Similar to #436 we have problems accessing MAB data for the following items:

* HT020616342
* HT020616386
* HT020616079
* HT020616677
* HT020617657
* HT020616296
* HT020616303
* HT020616258

This is http://lobid.org/hbz01/HT020616258 returns an error while http://lobid.org/resources/HT020616258 works.

**Comment by dr0i** [comment]
Thx for the report! The cause is network trouble as reported in https://github.com/hbz/lobid-resources/issues/1078.
Switched to use an elasticsearch node which is still accessible and triggered the hbz01 updates again.
@schmitzd please check.

**Comment by dr0i** [comment]
@fsteeg pushed a hot fix. Had to remove the `master` as protected branch to do this.

**Comment by schmitzd** [comment]
Thank you. I can confirm that there are no issues with these items anymore.
