### ISSUE TITLE
Take into accout all semicolon-separated notations from 700l.a in transformation 

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1086]
Requested by Edoweb customers in [EDOZWO-1032](https://jira.hbz-nrw.de/browse/EDOZWO-1032):

> Momentan werden bei Zeitschriften keine LBZ-Notationen (die 3stelligen Zahlen in der HBZ-Kategorie 700l) angezeigt, zB bei [HT019885947](https://lobid.org/resources/HT019885947), obwohl sie im Datensatz stehen \[siehe [Quelldaten](), 700l.a, A.P.\]. Das liegt daran, daß in der ZDB die Notationen nicht wie bei Mongraphien in jeweils eine eigene Kategorie geschrieben werden, sondern alle in 1 Kategorie ("600 ; 610 ; 130 ..."). 
>
> Unsere Frage nun: kann man es so hinkriegen, daß die Notationen auch bei Zeitschriften so angezeigt werden wie bei Monographien 

This is how the field in question looks like:

```xml
<datafield tag="700" ind1="l" ind2="1">
   <subfield code="a">600 ; 610 ; 130 ; 131 ; 106 ; 139</subfield>
</datafield>
```

**Comment by acka47** [comment]
The notations are from the [rpb2 classification](https://w3id.org/lobid/rpb2), and the corresponding morph part is here (I think):

https://github.com/hbz/lobid-resources/blob/f93201bec043cc732b27814a6ab4aea390d1aa9e/src/main/resources/morph-hbz01-to-lobid.xml#L7448-L7450

**Comment by acka47** [comment]
We will first have to see whether the ZDB resources can be corrected. For ZDB resources in NWBib, the 700n field is repeated when there are several enttries, see e.g. http://lobid.org/hbz01/HT015941018.

**Comment by dr0i** [comment]
Exactly - and we really shouldn't introduce a second semantic to a field. As HT019885947 is not correctly catalogueg, this should be fixed at catalogization level.
Closing.
