### ISSUE TITLE
Document usage of "regexp" at the api website 

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1088]
It's already possible to use [regexp when using the api](thttps://www.elastic.co/guide/en/elasticsearch/reference/6.8/query-dsl-regexp-query.html ):

~~https://lobid.org/resources/search?q=title:(regexp%20%22hu*%22)~~
[title:/hu[s]ten.*/](https://lobid.org/resources/search?q=title%3A%2Fhu%5Bs%5Dten.*%2F) => 32 hits
[title:/hu[as]ten.*/](https://lobid.org/resources/search?q=title%3A%2Fhu%5Bas%5Dten.*%2F) => 33 hits

but some things are strange, e.g. while [title:husten](https://lobid.org/resources/search?q=title:husten) has some 294 hits the equivalent [title:/husten/](https://lobid.org/resources/search?q=title%3A%2Fhusten%2F) has 0  and [title:/.\*husten.*/](https://lobid.org/resources/search?q=title%3A%2F.*husten.*%2F) has 64
and [title:/husten.*/](https://lobid.org/resources/search?q=title%3A%2Fhusten.*%2F) has 32 and [title:/keuchhusten.*/](https://lobid.org/resources/search?q=title%3A%2Fkeuchhusten.*%2F) has 32 but the equivalent [title:/.*husten/](https://lobid.org/resources/search?q=title%3A%2F.*husten%2F) has 0.
And if the slashes '/' are escaped it works well for [title:\/husten\/](https://lobid.org/resources/search?q=title%3A%5C%2Fhusten%5C%2F) but not for [title:\/hu\[sa\]ten\/](https://lobid.org/resources/search?q=+title%3A%5C%2Fhu%5C%5Bsa%5C%5Dten%5C%2F) .

It may have something to do with the [reserved characters](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_reserved_characters) or how these are treated in the api while making the query against ES.

As a customer Daniel K. asked about "how to get all resources starting with foo" this could help (a bit) and may be useful for others, too.

**Comment by acka47** [comment]
Won't engage. Will be reopened if anybody asks.
