### ISSUE TITLE
lobid-resources down again: it returns 502 Bad Gateway

### ISSUE THREAD

**Issue by hagbeck** [hbz/lobid-resources#1091]
... examples:

http://lobid.org/resources/HT003388516

http://lobid.org/resources/search?q=describedBy.dateModified:%3E20201208+OR+describedBy.dateCreated:%3E20201208&owner=DE-290&format=bulk

**Comment by acka47** [comment]
Thanks for the report. @dr0i restarted the app and now it's running again. Closing.

**Comment by dr0i** [comment]
Note #1092 where we are going to add a further `monit` check to automagically restart the play web app.
