### ISSUE TITLE
Move some metamorph functions into metafacture-core

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1097]
Thse three metamorph functions in lobid-resource may become part of metafacture-core:
`urlescape` , `sanitizeUrl` ,`dateformat`

This may be enough to get rid of lobid-resources' own `metamorph.xsd`.

**Comment by TobiasNx** [comment]
Does this make seens to migrate them to fix? @dr0i

**Comment by dr0i** [comment]
As we will switch to fix, I would say so. Question is: are these functions ok to be integrated in fix (thinking of catmandu API etc.)?

**Comment by TobiasNx** [comment]
@dr0i should we close this ticket, we are not using morph anymore in lobid and the fix we are using is no specific lobid fix

**Comment by dr0i** [comment]
ACK. Also some functions are now available in `fix`, e.g. [uri_encode](https://github.com/metafacture/metafacture-fix/tree/331cd6f808170bbaf8b6572e53038f7d8bb7be8f?tab=readme-ov-file#uri_encode) and [timestamp](https://github.com/metafacture/metafacture-fix/tree/331cd6f808170bbaf8b6572e53038f7d8bb7be8f?tab=readme-ov-file#timestamp).
Closing.
