### ISSUE TITLE
Enforce array for publication.location & publication.publishedBy

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1098]
As we sometimes have more than one value in `publication.location` & `publication.publishedBy` (see e.g. [HT018612706](https://github.com/hbz/lobid-resources/blob/12209c36c77889a44fb8a95596632960d5b6edd5/src/test/resources/jsonld/HT018612706.json#L206-L211) and [HT017411546](https://github.com/hbz/lobid-resources/blob/12209c36c77889a44fb8a95596632960d5b6edd5/src/test/resources/jsonld/HT017411546.json#L205-L209))  we should always have an array for those keys. Currently, we don't have an array if there is only one value. Examples:

https://github.com/hbz/lobid-resources/blob/12209c36c77889a44fb8a95596632960d5b6edd5/src/test/resources/jsonld/TT003060418.json#L159-L164

(There obviously is another error in this example tith the `publication.location` value but we'll ignore this here.)

https://github.com/hbz/lobid-resources/blob/12209c36c77889a44fb8a95596632960d5b6edd5/src/test/resources/jsonld/HT019996406.json#L85-L90

**Comment by acka47** [comment]
I think this could easily be solved by adjusting the context (same as #1084 #1083). Will make a PR.

**Comment by acka47** [comment]
This was accidentally closed. Reopening, as the problem persists.

**Comment by TobiasNx** [comment]
This should be solved in ALMA-Fix
