### ISSUE TITLE
Add sameAs-Element to Alma-Transformation

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1113]
Array that contains objects with:

- [x]  "sameAs.[].id"
- [x] "sameAs.[].label"
- [x] "zdbId"
- [x] "oclcNumber"

SameAs should recognize OCLC-, ZDB-ID and  Culturegraph Representation of record.

**Comment by TobiasNx** [comment]
1) Also added ALEPHCCHBZ. But perhaps this should not be stated as sameAs but as standalone identifier similar to 
`"almaIdMMS"`. What do you think @acka47 

2) I use the the id that is also used for creating the lobid-URI for CultureGraph. But sometimes there is also ALMA added to the `@id` (https://github.com/hbz/lobid-resources/blob/8a13996b01b6bd9922e882d09b74f69fa2afe650/src/main/resources/alma/common/fields.xml#L11). Those do not resolve as CultureGraph links. Which records are used in CultureGraph, should i use `"hbzId"` instead?

3) I found that there is a `"identifierZDB"`-Array with the value (https://github.com/hbz/lobid-resources/blob/8a13996b01b6bd9922e882d09b74f69fa2afe650/src/main/resources/alma/common/fields.xml#L91). I use for the zdbIdentifier `"zdbId"-Element that is also used in lobid resources for aleph (e.g. http://www.lobid.org/resources/HT012734833.json) Do we need identifierZDB or is zdbId enough? @dr0i

**Comment by blackwinter** [comment]
> 1. Also added ALEPHCCHBZ.

@TobiasNx, please note that those legacy IDs are going to be [removed](https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=573866037) before Go-Live.

**Comment by TobiasNx** [comment]
> > 1. Also added ALEPHCCHBZ.
> 
> @TobiasNx, please note that those legacy IDs are going to be [removed](https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=573866037) before Go-Live.

@blackwinter 

  ```xml
<datafield tag="035" ind1=" " ind2=" ">
      <subfield code="a">HT012734833</subfield>
    </datafield>
    <datafield tag="035" ind1=" " ind2=" ">
      <subfield code="a">(DE-605)HT012734833</subfield>
    </datafield>
    <datafield tag="035" ind1=" " ind2=" ">
      <subfield code="a">(ALEPHCCHBZ)010887386HBZ01</subfield>
    </datafield>
    <datafield tag="035" ind1=" " ind2=" ">
      <subfield code="a">(OCoLC)863021596</subfield>
      <subfield code="0">(uri) http://www.worldcat.org/oclc/863021596</subfield>
    </datafield>
    <datafield tag="035" ind1=" " ind2=" ">
      <subfield code="a">(DE-600)1500025-4</subfield>
    </datafield>
    <datafield tag="035" ind1=" " ind2=" ">
      <subfield code="a">(DE-599)ZDB1500025-4</subfield>
    </datafield>
```

It says there that "Feld 009 (hbz-ID ohne Präfix), Feld 035a (hbz-ID ohne Präfix), Feld 035a (Aleph-SYS)" will be deleted. But there is no example which this would be. Since I am new to the Aleph-Alma-Migration, could you tell me if any of the above will be deleted too, or for what i should look to know that this entry will be deleted. What prefix does this refer to?

**Comment by blackwinter** [comment]
I don't know for sure what the final normalization rule will look like. But you can see that after test load 1 `(ALEPHCCHBZ)` was going to be removed, and after test load 2 it was changed to `(HBZ01)`. Your example (`HT012734833`/`990108873860206441`) doesn't include the Aleph SYS number anymore in the current publishing result. So I think it's safe to assume that the Aleph SYS number will be removed regardless of whichever prefix it might have after the production load.

> could you tell me if any of the above will be deleted too

This particular normalization refers to Aleph legacy IDs only. Other external identifiers are not affected.

**Comment by TobiasNx** [comment]
Perhaps we leave the Aleph-Sys in for testing, when we want to filter out entries that are from ALEPH and not from Alma for now. So we delete the transfrmation rule, when it is deleted.

**Comment by dr0i** [comment]
@blackwinter hm,  I had took NZ_Central_Pub_PE_Bib_GND_All_2021020411_19081964230006441_new.tar.gz into account and was mislead in beliving that I updated our test data (HT012734833 i.a.) with that - I _just_ recognized that these are not even part of that particular dump. Good thing in bad thing is: this explains why the source test data didn't change a bit ;)
Did you accomplish something with BGZF re #1102  ? This would come in handy to update ones test files.

**Comment by blackwinter** [comment]
> Did you accomplish something with BGZF re #1102 ?

Almost done (I hope). Should be finished by the end of the week. I'll let you know.

**Comment by dr0i** [comment]
Re 1 (ALEPHCCHBZ) : better remove it - as @blackwinter  said, it will (_is_) not be part of the XML anymore. We may forget to remove it later.
Re 2 (CultureGraph): +1, use better `hbzId`, if it exists. If it doesn't exist, don't build a CultureGraph link.
Re 3: +1 , zdbId is enough.
