### ISSUE TITLE
Add  edoweb, rpb, publisso to inCollection (Alma)

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1123]
The inclusion of `inCollection` in #1114 did not add  edoweb, rpb, publisso
due to missing testdata. Should be added, when testdata is found.

- [x] edoweb
- [x] rpb
- [x] publisso

**Comment by TobiasNx** [comment]
This is done for ALMA-FIX

**Comment by TobiasNx** [comment]
# publisso

https://github.com/hbz/lobid-resources/blob/2ae7b86259115ee3fa8693e3ba16ebda2739ca54/src/main/resources/alma/fix/relatedRessourcesAndLinks.fix#L365-L375

@dr0i could you check if the number of publisso ressources are the same or if I need to improve the transformation.

**Comment by TobiasNx** [comment]
https://github.com/hbz/lobid-resources/blob/2ae7b86259115ee3fa8693e3ba16ebda2739ca54/src/main/resources/alma/fix/relatedRessourcesAndLinks.fix#L349-L358

@acka47: Is src/test/resources/alma-fix/(CKB)5280000000199164.xml also an EZB record?

**Comment by acka47** [comment]
> s src/test/resources/alma-fix/(CKB)5280000000199164.xml also an EZB record?

I can not find it at https://github.com/hbz/lobid-resources/tree/master/src/test/resources/alma-fix. Anyway, I doubt that I could help much with this question as I don't have any experiences with EZB records.

**Comment by dr0i** [comment]
> could you check if the number of publisso ressources are the same or if I need to improve the transformation.

we have to wait for the completed Alma Fix index , see https://github.com/hbz/lobid-resources/issues/1435.

**Comment by dr0i** [comment]
> check if the number of publisso ressources are the same or if I need to improve the transformation.

| alma-fix: hits |  lobid-resources: hits |
| ------------- |:-------------:| 
| [edoweb](http://test.lobid.org/resources/search?q=inCollection.id:%22http://repository.publisso.de%22&format=json): 8436 | [edoweb](http://lobid.org/resources/search?q=inCollection.id:%22http://repository.publisso.de%22&format=json):8623
| [rbp](http://test.lobid.org/resources/search?q=inCollection.id:%22http://lobid.org/resources/HT013494180%23!%22&format=json): 557946 | [rpb](http://lobid.org/resources/search?q=inCollection.id:%22http://lobid.org/resources/HT013494180%23!%22&format=json):6629
| [publisso](http://test.lobid.org/resources/search?q=inCollection.id:%22http://lobid.org/resources/HT016925914%23!%22&format=json) : 10227| [publisso](http://lobid.org/resources/search?q=inCollection.id:%22http://lobid.org/resources/HT016925914%23!%22&format=json):10223

**Comment by dr0i** [comment]
Note that the `rpb` data is missing now because of a newly build Alma Fix index. I am gonna automate this and let you know when this is done.

**Comment by dr0i** [comment]
After reindexing of RPB data the [rbp `inColleection`](http://test.lobid.org/resources/search?q=inCollection.id:%22http://lobid.org/resources/HT013494180%23!%22&format=json) is good again. Expect the RPB data to be there anytime besides Sunday late evening up to Monday around 6:20 (see https://github.com/hbz/lobid-resources/issues/1469#issuecomment-1274691392 for background).
Closing.
