### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1124]
a) Atm the `GENERATE_TESTDATA` is hard coded to `true`. The default should be `false`.
The effect is that no real test is done, i.e. no comparison (aka diff) between the generated resources and the commited test resources is done => All build will always be successful.
b) the diffing in test seems to fail when the order of keys is not the expected one. The order should not matter:
> [ERROR]   AlmaMarc21XmlToLobidJsonTest.transformFiles:137->lambda$transformFiles$1:174 expected:<...  "publishedBy" : "S[emiconductor Media Ltd. Trans World House",
    "startDate" : "20092011]",
    "type" : [ "P...> but was:<...  "publishedBy" : "S[olar Media Ltd., Trans-World House",
    "startDate" : "20092011",
    "type" : [ "PublicationEvent" ],
    "location" : "London",
    "publishedBy" : "Semiconductor Media Ltd. Trans World House]",
    "type" : [ "P...>

**Comment by TobiasNx** [comment]
@dr0i still an issue?

**Comment by dr0i** [comment]
No, can be closed. Closing.
