### ISSUE TITLE
Fix ISBN Mapping (ALMA)

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1130]
At the moment the ISBN mapping results in:

```
      "isbn": [
        "9783161546303",
        "e-book",
        "9783161546303",
        "e-book"
      ],

```

http://alma.lobid.org/resources/search?q=hbzId:HT020202475&format=json

**Comment by TobiasNx** [comment]
it should exclude eBook and entries should be unique.

**Comment by TobiasNx** [comment]
New Testfile needed for ebook-sample:
https://indexes.devel.digibib.net/export/990363946050206441

**Comment by dr0i** [comment]
Not deployed yet, reopened.

**Comment by TobiasNx** [comment]
okay, next time i leave it open

**Comment by dr0i** [comment]
Deployed , see e.g. http://alma.lobid.org/resources/search?q=hbzId:HT020202475&format=json.
Closing.
