### ISSUE TITLE
Missing GND-Identifier Person (ALMA)

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1134]
With the updated test data we can't map GND-identifiers anymore. We should checkout why.

The gnd-mapping works with macros which i do not completly understand yet. What was matched for the gnd-identifier of a person?

**Comment by dr0i** [comment]
What do you mean by "gnd-mapping"?

I can see that "Allan G" lacks the GND-ID in the Alma Marc Xml sources, see https://github.com/hbz/lobid-resources/blob/master/src/test/resources/alma/HT005207972.xml#L80.

But _some_ GND-IDs (still) exists, like "(DE-588)127022538" (https://github.com/hbz/lobid-resources/blob/master/src/test/resources/alma/HT005207972.xml#L73), and they are good transformed.
So this is not a principal issue of the ETL proces but rather of the data provider (aka "upstream").
Don't know, it may be deliberately missing. We should ignore this and go on. If it's an misconfiguration on the upstreams' side they will likely fix it resp. it will pop up again.

**Comment by TobiasNx** [comment]
Yes you are right I think. But there are new GND-refrence-links in `  <datafield tag="GSI" ind1="7" ind2=" ">`,   `<datafield tag="GKT" ind1="2" ind2=" ">`, `  <datafield tag="GST" ind1="7" ind2=" "> ` , `  <datafield tag="GGN" ind1=" " ind2=" ">`, `  <datafield tag="GPN" ind1="1" ind2=" ">`.

The last one is person. The other ones i need to have another look

**Comment by blackwinter** [comment]
See "Authority Enrichment" in the [wiki](https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=581533808#AnpassungenabDezember2020ff.-AuthorityEnrichment2020-12-09) or in the publishing profile (tab "Data Enrichment").

**Comment by TobiasNx** [comment]
> See "Authority Enrichment" in the [wiki](https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=581533808#AnpassungenabDezember2020ff.-AuthorityEnrichment2020-12-09) or in the publishing profile (tab "Data Enrichment").

Thanks a lot. Since most of this details are only represented in pictures I find it really difficult to search for them in the wiki. Thankfully you usually know where to look.

**Comment by dr0i** [comment]
This seems a duplicate or at least related to https://github.com/hbz/lobid-resources/issues/1176 .

**Comment by dr0i** [comment]
Closing as duplicate of #1176.

**Comment by TobiasNx** [comment]
I think we should keep this open, it is another it is relating to 100 110 and 700 710. Creator and contributor fields that should have an connection to the GND.

**Comment by TobiasNx** [comment]
can be closed 100 an 700 have GND Identifier, if provided in marc record
