### ISSUE TITLE
POR and other Holding information are missing with new data (AMLA)

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1135]
With the updated test files it seems that that there are less  POR and other holding information than before. We should investigate that if we need to change our mappings since some identifiers changed too. But this can be a shift due to reduction of holding information.

**Comment by dr0i** [comment]
After a fresh update some new POR popped up, see https://github.com/hbz/lobid-resources/pull/1142.
But these reveal other problems (all mapped to DE-605, which seems a problem at data provider level ?).

**Comment by TobiasNx** [comment]
![image](https://user-images.githubusercontent.com/61879957/109463675-b6acde00-7a65-11eb-8add-96ebdb5aeb1b.png)

This are the POR-fields.

**Comment by TobiasNx** [comment]
This is not relevant anymore.
