### ISSUE TITLE
Duplicate Values for type (ALMA)

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1136]
https://github.com/hbz/lobid-resources/blob/e0131bc29f780c434bea5d633404003b40fd54bf/src/test/resources/alma/HT012734884.json#L23

Can find the mapping in the morph for further investiogation, perhapse you can help @dr0i

**Comment by dr0i** [comment]
There are two occurences in  `common/facets.xml`.

**Comment by TobiasNx** [comment]
I see
Anyway to simplify    in common/facets.xml
Are the if-conditionals necessary? Wouldn 't i be useful to utilize a lookup, instead of all the if-conditionals?

**Comment by dr0i** [comment]
I don't know. Open a PR and I will review.
