### ISSUE TITLE
Duplicate Keys in publication-Element (ALMA)

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1138]
example: HT017131400

```
  "publication" : [ {
    "location" : "London",
    "publishedBy" : "Solar Media Ltd., Trans-World House",
    "startDate" : "20092011",
    "type" : [ "PublicationEvent" ],
    "location" : "London",
    "publishedBy" : "Semiconductor Media Ltd. Trans World House",
    "type" : [ "PublicationEvent", "PublicationEvent" ]
  } ]
```

source xml shows:

```
  <datafield tag="264" ind1="3" ind2="1">
    <subfield code="a">London</subfield>
    <subfield code="b">Solar Media Ltd., Trans-World House</subfield>
    <subfield code="c">2009-2011</subfield>
  </datafield>
  <datafield tag="264" ind1="2" ind2="1">
    <subfield code="a">London</subfield>
    <subfield code="b">Semiconductor Media Ltd. Trans World House</subfield>
    <subfield code="c">anfangs</subfield>
  </datafield>
```

Morph should seperate between different publication entries. This is perhaps easily solved with adding `reset` and `sameEntity`-attributes to publication object keys.

**Comment by TobiasNx** [comment]
here it seems that there are some problems with the date information:

https://www.loc.gov/marc/bibliographic/bd264.html
The subfield $c does not need a structured date information. How should we work with that. Perhapse this date-problem is no only specific for this subfield.

**Comment by dr0i** [comment]
Note the indicator_1 in `264[23]1`. What's the semantic of it - is it ok (may well be) to use it as `publication`?

To cope with the unstructured data (well, very much improvement here ( "...wir schreiben das Jahr 2021")):
you could regexp the first  digits and claim it to be the start date. If it has an '-' in it : capture the last 4 digits and assume it's the end date. Everything else (as e.g. "anfang") - dump it. Or, if you like, add that to `publicationHistory` (it's a subfield of `publication` and used in lobid-resources) - lookup https://lobid.org/resources/context.jsonld to see it pointing to http://www.rdaregistry.info/Elements/u/#P60491 (which allows everything , i.e. unstructured notes in all languages, including dump).

**Comment by dr0i** [comment]
This was somehow partly fixed, at least there are no more two `publishedBy`, but tere are two times `types: PublicationEvent`:
http://alma.lobid.org/resources/search?q=HT017131400&format=json

**Comment by dr0i** [comment]
Deployed, see e.g. http://alma.lobid.org/resources/search?q=HT017131400&format=json. Closing.
