### ISSUE TITLE
hbzId matching (ALMA)

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1140]
(DE-605)HT020391499 is missing `<controlfield tag="009">` for hbzId, but has 

```
  <datafield tag="035" ind1=" " ind2=" ">
    <subfield code="a">(DE-605)HT020391499</subfield>
  </datafield>
```

We perhaps should take up this ID as `hbzId` and ignore the controlfield

**Comment by blackwinter** [comment]
`009` will be deleted before Go Live, you must use `035$$a` with prefix `(DE-605)`.

**Comment by dr0i** [comment]
@TobiasNx go on  , use `035$$a` with prefix `(DE-605)` instead of `009` for `hbzId`.
