### ISSUE TITLE
decribedBy>modifiedBy -> no duplicate keys

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1143]
https://github.com/hbz/lobid-resources/blob/3d1c62b36c362c79fd8e0c5190a2945e64bf313a/src/test/resources/alma/HT016709661.json#L149-L163

There are duplicated keys as well as values as well as keys in `"describedBy"`>`"modifiedBy"`.

https://www.loc.gov/marc/bibliographic/bd040.html says : 

> $d - Modifying agency (R)

I would propose an array instead of a single string value.

**Comment by dr0i** [comment]
Hm, but it uses the term "agency" as singular. Also, the test data shows only one organisations, but erroneously multiple times. As there is only one "dateModified" it is implied that there is a singular event - which also hints to stick to a singular entity creating this event. So atm I don't see why we want to switch to an array.
What we need is a single 'modifiedBy'.

**Comment by TobiasNx** [comment]
I think you are right, that we should stick only one entity for now. Concerning a possibility of real subfield repetition, we can come back.

I would say we exclude 9999 as modifier. But I see that the other URL is wrong and has "DE-DE-".
Will fix that too then.

**Comment by dr0i** [comment]
Ready.
