### ISSUE TITLE
Add content-media-carrier (CMC) information to RDF

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#115]
Sub-issue of https://github.com/hbz/lobid/issues/161.
- content: in MAB field 060, controlled values at [LoC](https://www.loc.gov/standards/valuelist/rdacontent.html) & [RDA registry](http://www.rdaregistry.info/termList/RDAContentType)
- media: in MAB field 061, controlled values at [LoC](http://id.loc.gov/vocabulary/mediaTypes) & [RDA registry](http://www.rdaregistry.info/termList/RDAMediaType/)
- carrier: in MAB field 062, controlled values at [LoC](https://www.loc.gov/standards/valuelist/rdacarrier.html) & [RDA  registry](http://www.rdaregistry.info/termList/RDACarrierType)

Example:

``` xml
<datafield tag="060" ind1="-" ind2="1">
  <subfield code="b">txt</subfield>
  <subfield code="a">Text</subfield>
</datafield>
<datafield tag="061" ind1="-" ind2="1">
  <subfield code="b">n</subfield>
  <subfield code="a">ohne Hilfsmittel zu benutzen</subfield>
</datafield>
<datafield tag="062" ind1="-" ind2="1">
  <subfield code="b">nb</subfield>
  <subfield code="a">Blatt</subfield>
</datafield>
```

**Comment by acka47** [comment]
Here are some helpful examples for assigning CMC information: http://mediawiki.middlebury.edu/wikis/LIS/images/d/d5/RDA_3xx_fields.pdf

**Comment by TobiasNx** [comment]
This could be introduced in ALMA FIX, or @acka47

**Comment by TobiasNx** [comment]
https://wiki.dnb.de/display/RDAINFO/Arbeitshilfen?preview=/106042227/108631389/AH-013.pdf

**Comment by acka47** [comment]
> we are already using some information from 061 -> 337 and 062 -> 338 for the selection of medium and type, do you intend to add the information differently?

This is an old issue. I think we can close this now as we have added information from these fields.
