### ISSUE TITLE
Enable query to get only resources which are part of Alma and not of Aleph

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1153]
Provided by @blackwinter :
> (Pseudo-)Filterbedingung: (MBD$$M=memberID OR POR$$M=memberID OR POR$$A=memberID) AND NOT (MBD$$M=49HBZ_NETWORK AND EXISTS(ITM)) AND NOT leader@05=d

We have to make sure to have all this data in our index before possibly make a query to get the data which is part of Alma and not of Aleph. This is fundamental to avoid doublets to query both indices (see #1152).

**Comment by dr0i** [comment]
Just a note - this issue has high priority - it is essential for the migration.

**Comment by TobiasNx** [comment]
@dr0i can you have a look at src/main/resources/alma/filterMorph.xml
I think this could work as filter-morph.

**Comment by dr0i** [comment]
As @hagbeck is fine with using the API that only uses _one_ index (the Alma one: alma.lobid.org/resources) we don't need this.
When phase 2 is finished, we don't need the old Aleh-API.
So, this issue has lost its relevance.
Closing.
