### ISSUE TITLE
Add IZ mmsID

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1154]
Map `MBD$$i` to identify the IZ mmsID.
We have to check if this is not already done. E.g. `MBD$$i` is already mapped to `hasItem.id` e.g.

`"id" : "https://lobid.org/item/991003545629706445"` (see http://alma.lobid.org/resources/search?q=990021367710206441&format=json).

Would be good to know if _all_ `hasItem.id` are of kind IZ mmsID, resp. how to discriminate them from the `NZ` origination. If our data lacks the possibility to discover that we would have to add some data, e.g. `type: [Item, IZItem]` or something better (to be discussed).

**Comment by TobiasNx** [comment]
At the moment we label portfolio as Portfolio, shouldn't we label the MDB-ID differently as we did with "POR"?

**Comment by dr0i** [comment]
Closed unintentionally. Reopened.

**Comment by TobiasNx** [comment]
This is also relevant to issue #1160

**Comment by TobiasNx** [comment]
@dr0i This seems to be solved by #1160, right?
MBD is not relevant for hasItem anymore but the ITM  .a or the HOL which has to be implemented (as discussed of board) (Should create new ticket for that.)
There is no NZ Id connected to ITM.

**Comment by dr0i** [comment]
Hm, is missing `HOL` the cause of the missing heldBy mentioned in https://github.com/hbz/lobid-resources/issues/1168?

**Comment by dr0i** [comment]
Gonna close this issue as the the almaIdMMs is added to the index profile. We should rather open a new issue if there is something about the questions raised here.
