### ISSUE TITLE
hasItem.electronicLocator and hasItem.sublocation not resolving

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1157]
Reported by @hagbeck.

E.g. `"electronicLocator": "https://eu04.alma.exlibrisgroup.com/view/uresolver/49HBZ_NETWORK/openurl?u.ignore_date_coverage=true&portfolio_pid=53451922210006441&Force_direct=true` (from
http://alma.lobid.org/resources/search?q=990191843330206441&format=json )

To make it work, the  `49HBZ_NETWORK` in the URL must be substituted with the proper "alma-iz-code" of the institution, here: `49HBZ_UBD`. The mappings for these can be extracted from the  field 'hasItem.heldBy.id` (the last part of this URL consits of the ISIL of the holding institution) and then mapped using https://github.com/hbz/lobid-resources/blob/master/src/main/resources/alma/maps/alma-iz-code-to-isil.xml.

**Comment by blackwinter** [comment]
Problem is, it's specific to each IZ. So you'd have to generate individual `hasItem`s per `POR$$A`, which doesn't seem to be the case yet: [99368090810506441](http://alma.lobid.org/resources/search?q=99368090810506441&format=json).

BTW: The new (single) ISIL for `49HBZ_UDE` (6446) is `DE-465`, not `DE-464`.

**Comment by dr0i** [comment]
Re: generate individual `hasItem`s per `POR$$A: yes, you are right! Filed it as a new issue #1158.
Re: ISIL : hotfixed with 43ad491.

**Comment by dr0i** [comment]
As @hagbeck is using Daia/Paia Api we don't need resolvable URIs atm.
Postponed this by moving to backlog.

**Comment by hagbeck** [comment]
Hint:

Your current URLs are like 

https://hbz-network.userservices.exlibrisgroup.com/view/uresolver/49HBZ_NETWORK/openurl?u.ignore_date_coverage=true&rft.mms_id=991009524939706445

This is not working, because the 49HBZ_NETWORK. If you use 49HBZ_UBD in this case it will work. So you have to use the institutional MMS-IS **and** the institutions ExLibris-ID.

**Comment by dr0i** [comment]
@hagbeck I don't understand how your note differs from what I initially wrote (i.e. substituting the 49HBZ_NETWORK).
More important: I postponed this issue as not important for you since you would do the substitution when consuming lobid's data. has that changed?

**Comment by hagbeck** [comment]
You're right in both points. 
I should had read all comments. And more important: it is currently not important for us :-)

**Comment by hagbeck** [comment]
@TobiasNx 

For POR without $A:

You have to build an electronicLocator based on subfield code="D" by replacing "49HBZ_NETWORK" with the value from subfield code="M".

For POR with $A:

You have to build an electronicLocator for each member of subfield code="A" based on subfield code="D" by replacing "49HBZ_NETWORK" with the value from subfield code="A".
The result is a list of count(subfield code="A") electronic locations or rather PORs.

**Comment by TobiasNx** [comment]
Like this: https://github.com/hbz/lobid-resources/commit/916502aaa30df79bdd7863f1138226057fc0a716 ?

**Comment by hagbeck** [comment]
In the file src/test/resources/alma-fix/990133067580206441.json not all sublocations are valid. But its the right way :-)

**Comment by TobiasNx** [comment]
Okay should be fixed then. Thanks!

**Comment by TobiasNx** [comment]
Resolved with: https://github.com/hbz/lobid-resources/pull/1525
