### ISSUE TITLE
Generate individual hasItem`s per POR$$A

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1158]
Reported by @blackwinter in https://github.com/hbz/lobid-resources/issues/1157#issuecomment-796829848:

Generating individual `hasItem`s per `POR$$A` is not the case yet: [99368090810506441](http://alma.lobid.org/resources/search?q=99368090810506441&format=json), as the processing is "flushed with POR$$w" `(<choose flushWith="POR  .w"` )and thus done only once.

**Comment by TobiasNx** [comment]
I think I found the problem see #1164 .

**Comment by TobiasNx** [comment]
It seems that the feature branch was old and behind master. I opened a new feature branch https://github.com/hbz/lobid-resources/tree/1158-takeAllPorAintoAccount_

I think I have a solution for our problem. I used a variation of: https://swissbib.gitlab.io/metamorph-doku/kochbuch/literale-in-entitaeten-wiederverwenden/

**Comment by TobiasNx** [comment]
I did link to the branch but github did not recognize the "_", so check [https://github.com/hbz/lobid-resources/tree/1158-takeAllPorAintoAccount_](https://github.com/hbz/lobid-resources/tree/1158-takeAllPorAintoAccount_) for my proposed solution

**Comment by dr0i** [comment]
Deployed, see e.g. http://alma.lobid.org/resources/search?q=99368090810506441&format=json, closing.
