### ISSUE TITLE
Evaluate possible methods to query for authority labels

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#116]
As mentioned in https://github.com/hbz/lobid-rdf-to-json/issues/24#issuecomment-251962557 we need to discuss other ways to enrich GND links with alternate labels. This is the place to discuss different possible methods.

**Comment by acka47** [comment]
In the context of this issue and also with regard to #140 we re discussing putting authority data and title data into different elasticsearch indexes (e.g. titles, authorities and items) and embedding information on the API-side if needed. We will have to discuss how to move on to get to a sensible solution.

**Comment by fsteeg** [comment]
Result of our offline discussion: we will keep getting the GND data from the title data for the API 2.0 launch, but remove the general `altLabel` in the responses we serve to keep support for querying the altLabels, but avoid leaking a workaround into the 2.0 API. When we switch to getting the GND data from the actual GND (not from the titles), we can add specific `altLabels` to each GND entity and stay compatible with the launched 2.0 API.

**Comment by acka47** [comment]
I just realized that we already have `altLabel`s associated with a subject if it is a single person, see e.g. http://lobid.org/resources/HT002721371 . If there are two persons as subject, the alt labels are put into subjectAltLabel, though, see e.g. http://lobid.org/resources/HT009513254. This is inconsistent and confusing and could rightly be called a bug.

**Comment by acka47** [comment]
This might be seen as prerequisite for #532. We will have to discuss this.

**Comment by TobiasNx** [comment]
@acka47 do we still need this, due to the GND enrichment of ALMA, we have the data containing in the records, or can we close the issue?

**Comment by acka47** [comment]
Generally, we are set here. However, as it is relevant in this context: I recently noticed that lots of records have a `subjectsLabels` property: http://lobid.org/resources/search?q=_exists_%3Asubjectslabels I can not remember why this exists in the data.

**Comment by blackwinter** [comment]
It's used in DigiBib (union catalogue); see #1617.

**Comment by acka47** [comment]
> It's used in DigiBib (union catalogue); see https://github.com/hbz/lobid-resources/issues/1617.

Ah, thanks for the pointer. I guess, everything is ok then. Closing.
