### ISSUE TITLE
shelfmarks lost

### ISSUE THREAD

**Issue by hagbeck** [hbz/lobid-resources#1160]
Currently there are no shelfmarks in records for print holdings. We expect them in hasItem/callNumber.

Example: http://alma.lobid.org/resources/990193094010206441.json -> expected: A 12726

**Comment by TobiasNx** [comment]
A couple of questions:
At the moment MBD is transformed for heldBy:
   ```JSON
 "type": [
        "Item"
      ],
      "label": "lobid Bestandsressource",
      "heldBy": {
        "id": "http://lobid.org/organisations/DE-605#!",
        "label": "lobid Organisation"
      },
      "id": "https://lobid.org/item/990193094010206441"
    },
    {
      "type": [
        "Item"
      ],
      "label": "lobid Bestandsressource",
      "heldBy": {
        "id": "http://lobid.org/organisations/DE-290#!",
        "label": "lobid Organisation"
      },
      "id": "https://lobid.org/item/991005272979706445"
    }
  ],

```
The callNumber is found in H52 and ITM:

```XML
<datafield tag="MBD" ind1=" " ind2=" ">
    <subfield code="M">49HBZ_NETWORK</subfield>
    <subfield code="i">990193094010206441</subfield>
    <subfield code="n">HBZ Network</subfield>
  </datafield>
  <datafield tag="MBD" ind1=" " ind2=" ">
    <subfield code="M">49HBZ_UBD</subfield>
    <subfield code="i">991005272979706445</subfield>
    <subfield code="n">Technische Universit&#228;t Dortmund</subfield>
  </datafield>
...
 <datafield tag="H52" ind1=" " ind2=" ">
    <subfield code="b">ZB</subfield>
    <subfield code="c">Freihand</subfield>
    <subfield code="h">A 12726</subfield>
    <subfield code="8">2286063530006445</subfield>
  </datafield>
....  
<datafield tag="ITM" ind1=" " ind2=" ">
    <subfield code="H">2286063530006445</subfield>
    <subfield code="x">Freihand</subfield>
    <subfield code="f">BOOK</subfield>
    <subfield code="v">Freihand</subfield>
    <subfield code="X">System</subfield>
    <subfield code="U">2020-11-25 10:59:00</subfield>
    <subfield code="Y">2021-02-11 21:21:09</subfield>
    <subfield code="h">false</subfield>
    <subfield code="G">1</subfield>
    <subfield code="M">49HBZ_UBD</subfield>
    <subfield code="s">1</subfield>
    <subfield code="d">#</subfield>
    <subfield code="V">import</subfield>
    <subfield code="L">ClassificationNo: 100 | SISIS-Magazindrucker: 0 | HBZ01: HT017398609 | Keine Beilagen: 1</subfield>
    <subfield code="b">20129967</subfield>
    <subfield code="O">SISIS-Ausleihz&#228;hler vorletztes Migrationsjahr: 3 | SISIS-Vormerkz&#228;hler Migrationsjahr: 0 | SISIS-vorletztes R&#252;ckgabedatum: 2018-07-13 | SISIS-Buchdaten-Aufnahmedatum: 2013-10-14</subfield>
    <subfield code="N">Fernleihkonditionen: 0 | Sigel: 290 | Klassifikation: 100 | Altersbegrenzung: 0 | SISIS-Ausleihz&#228;hler Migrationsjahr: 0 | SISIS-Ausleihz&#228;hler Vor-Migrationsjahr: 0</subfield>
    <subfield code="a">2386063520006445</subfield>
    <subfield code="c">A 12726</subfield>
    <subfield code="B">ZB-77849</subfield>
    <subfield code="W">2020-11-26 20:09:57</subfield>
    <subfield code="u">ZB</subfield>
    <subfield code="w">ZB</subfield>
  </datafield>
```


So the questions:
1) Is it necessary that the NZ is listed as "holder": http://lobid.org/organisations/DE-605#!, it is present in MDB.
2) Is MBD at all necessary for the hasItem information, or should we prefer ITM? MBD has no callNumber information
3) I assume that ITM is more relevant than H52. Am i right?

**Comment by hagbeck** [comment]
I think the relevant part is ITM and its subfields a = id and c = shelfmark. For library/location there are two options u/v or w/x. Here the question is, which pair represents the "current location" in Alma. The pair for that should be the choice.

So:
1. No, it's not necessary.
2. ITM
3. Yes.

:-)

**Comment by TobiasNx** [comment]
At the moment we create hasItem, if there is any MBD information additionally to POR. 

```
    <!-- MBD -->
    <entity name="" reset="true" sameEntity="true">
      <combine name="id" value="https://lobid.org/item/${i}">
        <data name="i" source="MBD  .i"/>
      </combine>
      <entity name="type[]" sameEntity="true">
        <data name="" source="@isiliz">
          <constant value="Item"/>
        </data>
      </entity>
      <data name="label" source="@isiliz">
          <constant value="lobid Bestandsressource"/>
      </data>
      <entity name="heldBy" sameEntity="true">
        <combine name="id" value="http://lobid.org/organisations/${a}#!">
          <data name="a" source="@isiliz"/>
        </combine>
        <data name="label" source="@isiliz">
          <constant value="lobid Organisation"/>
        </data>
      </entity>
    </entity>
```
The variable "@isiliz" is created from MBD
https://github.com/hbz/lobid-resources/blob/7baf6853e4c602aabe8f40017cbcda97255e7413/src/main/resources/alma/alma.xml#L9

_Sitenote: "@isiliz" is also needed to create "@uid" but "@uid" is not needed anywhere else as source just as target field. Perhaps we should delete that_

Following @hagbeck comments i would suggest:

1. Rework `"hasItem"` that it is sensible to ITM and not to MBD.
- This will allow us to drop NZ-MBD info as holder and add the callNumber-field
2. Add the needed fields for callNumber
3. CleanUp the "@isiliz" variable that was a pillar for the old work flow.

**Comment by TobiasNx** [comment]
The internal docu says that w/x is representing the current location.

**Comment by TobiasNx** [comment]
@hagbeck your example would now return like this:
your example HT017398609
```JSON
"hasItem" : [ {
    "id" : "https://lobid.org/item/2386063520006445",
    "type" : [ "Item" ],
    "label" : "lobid Bestandsressource",
    "heldBy" : {
      "id" : "http://lobid.org/organisations/DE-290#!",
      "label" : "lobid Organisation"
    },
    "callNumber" : "A 12726",
    "currentLocation" : "ZB Freihand"
  } ]
```
Since every ITM is a separate entry there can be multiple `hasItem`-entries for a single UB:

e.g.:
HT005207972

```JSON
 "hasItem" : [ {
    "id" : "https://lobid.org/item/23104064560006445",
    "type" : [ "Item" ],
    "label" : "lobid Bestandsressource",
    "heldBy" : {
      "id" : "http://lobid.org/organisations/DE-290#!",
      "label" : "lobid Organisation"
    },
    "callNumber" : "5200/Mars",
    "currentLocation" : "ZB SFS"
  }, {
    "currentLocation" : "ZB Freihand",
    "id" : "https://lobid.org/item/23104064580006445",
    "type" : [ "Item" ],
    "label" : "lobid Bestandsressource",
    "heldBy" : {
      "id" : "http://lobid.org/organisations/DE-290#!",
      "label" : "lobid Organisation"
    },
    "callNumber" : "F 29772"
  }, {
    "currentLocation" : "ZB 13W_Mono",
    "id" : "https://lobid.org/item/23103185950006442",
    "type" : [ "Item" ],
    "label" : "lobid Bestandsressource",
    "heldBy" : {
      "id" : "http://lobid.org/organisations/DE-361#!",
      "label" : "lobid Organisation"
    },
    "callNumber" : "SL800 M367(3)"
  } ]
```

**Comment by TobiasNx** [comment]
@dr0i @acka47 
hasItem used to have also following elements:
 "hasItem.[].label" -> was just a repetition of the callNumber
"hasItem.[].note" and "hasItem.[].note.[]" -> cryptic information inconsistent if array or string

**Comment by dr0i** [comment]
Re fields: both are not really important to be solved just yet. You may just leave them as they are, or make another ticket. However, _if_ you want to resolve it:
We have the convention to always provide a `label` for every entry having an `id`. So we shall not drop `hasItem.[].label`, but rather use a more "meaningful" value  for it, i.e. e.g. "DE-832:BBV1390" for `"id": "http://lobid.org/items/HT017398609:DE-832:BBV1390#!"`.
Re hasItem.[].note : yeah we should enforce an array I think (more flexibility). Regarding the "cryptic" nature, that should be analyzed (see underlying MarcXml) what it means, respectively wait if someone asks for this data. Or again, just leave it as it is (besides the inconsitency of the nature of the field (array or value). Maybe drop it as this is easiest.

**Comment by hagbeck** [comment]
> @hagbeck your example would now return like this:
> your example HT017398609
> 
> ```json
> "hasItem" : [ {
>     "id" : "https://lobid.org/item/2386063520006445",
>     "type" : [ "Item" ],
>     "label" : "lobid Bestandsressource",
>     "heldBy" : {
>       "id" : "http://lobid.org/organisations/DE-290#!",
>       "label" : "lobid Organisation"
>     },
>     "callNumber" : "A 12726",
>     "currentLocation" : "ZB Freihand"
>   } ]
> ```
> 
> Since every ITM is a separate entry there can be multiple `hasItem`-entries for a single UB:
> 
> e.g.:
> HT005207972
> 
> ```json
>  "hasItem" : [ {
>     "id" : "https://lobid.org/item/23104064560006445",
>     "type" : [ "Item" ],
>     "label" : "lobid Bestandsressource",
>     "heldBy" : {
>       "id" : "http://lobid.org/organisations/DE-290#!",
>       "label" : "lobid Organisation"
>     },
>     "callNumber" : "5200/Mars",
>     "currentLocation" : "ZB SFS"
>   }, {
>     "currentLocation" : "ZB Freihand",
>     "id" : "https://lobid.org/item/23104064580006445",
>     "type" : [ "Item" ],
>     "label" : "lobid Bestandsressource",
>     "heldBy" : {
>       "id" : "http://lobid.org/organisations/DE-290#!",
>       "label" : "lobid Organisation"
>     },
>     "callNumber" : "F 29772"
>   }, {
>     "currentLocation" : "ZB 13W_Mono",
>     "id" : "https://lobid.org/item/23103185950006442",
>     "type" : [ "Item" ],
>     "label" : "lobid Bestandsressource",
>     "heldBy" : {
>       "id" : "http://lobid.org/organisations/DE-361#!",
>       "label" : "lobid Organisation"
>     },
>     "callNumber" : "SL800 M367(3)"
>   } ]
> ```
> 
> Can you work with this?

Nice! Is ist possible to add a separator between w and x -> e.g. ZB / 13W_Mono or ZB / Freihand?

**Comment by TobiasNx** [comment]
> Re fields: both are not really important to be solved just yet. You may just leave them as they are, or make another ticket. However, _if_ you want to resolve it:
> We have the convention to always provide a `label` for every entry having an `id`. So we shall not drop `hasItem.[].label`, but rather use a more "meaningful" value for it, i.e. e.g. "DE-832:BBV1390" for `"id": "http://lobid.org/items/HT017398609:DE-832:BBV1390#!"`.
> Re hasItem.[].note : yeah we should enforce an array I think (more flexibility). Regarding the "cryptic" nature, that should be analyzed (see underlying MarcXml) what it means, respectively wait if someone asks for this data. Or again, just leave it as it is (besides the inconsitency of the nature of the field (array or value). Maybe drop it as this is easiest.

just to clarify this is from the hasItem>label and hasItem>note is not included in the ALMA-Transformation but in the ALEPH-MORPH, so there is no underlying MarcXML but only the MAB from ALEPH.

Concerning the label there is     "label" : "lobid Bestandsressource" at the same level as the callNumber. We already have a label then.

So in the mean time, i would just leave callNumber specific "label" and "note" beside.

**Comment by TobiasNx** [comment]
> > @hagbeck your example would now return like this:
> > your example HT017398609
> > ```json
> > "hasItem" : [ {
> >     "id" : "https://lobid.org/item/2386063520006445",
> >     "type" : [ "Item" ],
> >     "label" : "lobid Bestandsressource",
> >     "heldBy" : {
> >       "id" : "http://lobid.org/organisations/DE-290#!",
> >       "label" : "lobid Organisation"
> >     },
> >     "callNumber" : "A 12726",
> >     "currentLocation" : "ZB Freihand"
> >   } ]
> > ```
> > 
> > 
> > Since every ITM is a separate entry there can be multiple `hasItem`-entries for a single UB:
> > e.g.:
> > HT005207972
> > ```json
> >  "hasItem" : [ {
> >     "id" : "https://lobid.org/item/23104064560006445",
> >     "type" : [ "Item" ],
> >     "label" : "lobid Bestandsressource",
> >     "heldBy" : {
> >       "id" : "http://lobid.org/organisations/DE-290#!",
> >       "label" : "lobid Organisation"
> >     },
> >     "callNumber" : "5200/Mars",
> >     "currentLocation" : "ZB SFS"
> >   }, {
> >     "currentLocation" : "ZB Freihand",
> >     "id" : "https://lobid.org/item/23104064580006445",
> >     "type" : [ "Item" ],
> >     "label" : "lobid Bestandsressource",
> >     "heldBy" : {
> >       "id" : "http://lobid.org/organisations/DE-290#!",
> >       "label" : "lobid Organisation"
> >     },
> >     "callNumber" : "F 29772"
> >   }, {
> >     "currentLocation" : "ZB 13W_Mono",
> >     "id" : "https://lobid.org/item/23103185950006442",
> >     "type" : [ "Item" ],
> >     "label" : "lobid Bestandsressource",
> >     "heldBy" : {
> >       "id" : "http://lobid.org/organisations/DE-361#!",
> >       "label" : "lobid Organisation"
> >     },
> >     "callNumber" : "SL800 M367(3)"
> >   } ]
> > ```
> > 
> > 
> > Can you work with this?
> 
> Nice! Is it possible to add a separator between w and x -> e.g. ZB / 13W_Mono or ZB / Freihand?

+1 and done!

**Comment by dr0i** [comment]
Deployed to staging, see example:
> http://alma.lobid.org/resources/990193094010206441.json -> expected: A 12726

**Comment by dr0i** [comment]
Please have a look again and close this issue if all is ok.

**Comment by TobiasNx** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.

**Comment by hagbeck** [comment]
http://alma.lobid.org/resources/990190491150206441.json contains no callNumber. We expect A 12605.

**Comment by dr0i** [comment]
MARC xml source:

```
<datafield tag="ITM" ind1=" " ind2=" ">
<subfield code="H">22200208770006445</subfield>
...
<subfield code="n">A 12605</subfield>
<subfield code="M">49HBZ_UBD</subfield>
```

**Comment by dr0i** [comment]
Let's stay with the already known resource as described here at the beginning: http://alma.lobid.org/resources/search?q=HT017398609&format=json. Now there the callnumber is again missing.
It's because the fields changed:
we took `ITM  .c` as `callnumber`, but now it resides in `ITM  .n`, see Alma MARC sources:
```
<datafield tag="ITM" ind1=" " ind2=" ">
<subfield code="H">22195293920006445</subfield>
...
<subfield code="h">false</subfield>
<subfield code="n">A 12726</subfield>
<subfield code="M">49HBZ_UBD</subfield>
```
I don't know why this change was done. Is it expected @blackwinter ?

**Comment by blackwinter** [comment]
I guess so. UBD indicated they would change their call number structure in support of their DAIA efforts. @hagbeck should be able to confirm (`c` = Call number subfield, `n` = Item call number subfield).

**Comment by hagbeck** [comment]
Yes, we have changed our call numbers to item level only. It seems `c` is holding level and `n` is item level.

**Comment by TobiasNx** [comment]
is only UBD doing this or is the ITM structure changed for every library?

**Comment by blackwinter** [comment]
It's specific to each IZ. Different libraries handle their call numbers differently.

**Comment by TobiasNx** [comment]
> It's specific to each IZ. Different libraries handle their call numbers differently.


but it is not completely arbitrary, right.  different subfields can be used for the same purpose but the same subfield cannot for different purposes:


d, c, t, n for call numbers as stated here: https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=612532300

**Comment by blackwinter** [comment]
Correct.

**Comment by TobiasNx** [comment]
I added only `ITM  .n`, since subfield `d` and `t` refer to callNumber type

**Comment by dr0i** [comment]
Deployed fix, please have a look @hagbeck .
