### ISSUE TITLE
total items in Alma index for DE-290

### ISSUE THREAD

**Issue by hagbeck** [hbz/lobid-resources#1168]
Currently we're getting 1.024.975 records for DE-290 from the Alma index. [1]
From the Aleph based index we're getting 1.334.514 records [2] 

This gap seems a little bit to big, to be reasoned on not up-to-date sources.

[1] http://alma.lobid.org/resources/search?owner=http%3A%2F%2Flobid.org%2Forganisations%2FDE-290%23!&format=json
[2] http://lobid.org/resources/search?owner=http%3A%2F%2Flobid.org%2Forganisations%2FDE-290%23%21&aggregations=owner

**Comment by dr0i** [comment]
This _could_ be because of https://github.com/hbz/lobid-resources/issues/1158 (some heldbys are ignored).

Just a note: querying the older index created at 2021-03-15 brings up `1.133.219` ( curl  'http://weywot4.hbz-nrw.de:9200/almaresources-20210315-1419/resource/_search?q=hasItem.heldBy.id%3A%22http%3A%2F%2Flobid.org%2Forganisations%2FDE-290%23!%22&format=json').

**Comment by hagbeck** [comment]
A search in Alma currently results in 1.386.535 records from combined NZ and IZ.

**Comment by dr0i** [comment]
We should identitfy one of these missing resources to be able to see what's going on.
@hagbeck or @TobiasNx can you find one example?

**Comment by hagbeck** [comment]
I think #1173 is a case.

**Comment by dr0i** [comment]
@hagbeck great, thx! We will use this do identify the problem.

**Comment by dr0i** [comment]
Good news here: https://github.com/hbz/lobid-resources/pull/1183 got us more than 200k new resources. Now total hits is 1.283.773.

**Comment by dr0i** [comment]
Accidentally closed. Reopened.

**Comment by dr0i** [comment]
Meanwhile it increased to 1.298.616 which seems good, but not good enough. Task: find a resource that's part of alma but not in alma.lobid.org. (see one mentioned in https://github.com/hbz/lobid-resources/issues/1168#issuecomment-806481597 is meanwhile a part of alma.lobid).

**Comment by dr0i** [comment]
(hm , strange, cannot assign @UBmakla).

**Comment by blackwinter** [comment]
You can only assign ["anyone who has commented on the issue or pull request, anyone with write permissions to the repository, and organization members with read permissions to the repository"](https://docs.github.com/en/github/managing-your-work-on-github/assigning-issues-and-pull-requests-to-other-github-users#about-issue-and-pull-request-assignees).

**Comment by hagbeck** [comment]
I've found a record which is still missing: 990053976760206441 / HT000312236.

http://alma.lobid.org/resources/990053976760206441.json

**Comment by dr0i** [comment]
> You can only assign 
You are right, that explains why I can assign @hagbeck but not @UBmakla: both are not part of the lobid team but @hagbeck has commented (resp. created) the issue, so I can assign him but not @UBmakla.

**Comment by dr0i** [comment]
@hagbeck the resource http://alma.lobid.org/resources/990053976760206441.json exists. Can you find another one?

**Comment by dr0i** [comment]
@hagbeck forgot my comment: yes it is in the index but it is not part of DE-290. So, this is in fact a good example!

**Comment by TobiasNx** [comment]
@hagbeck is is possible to identify **Überordnungen/Bindeeinheiten** in a Marc Record?

**Comment by hagbeck** [comment]
HT014382984 (old MMS-ID: 990135991740206441) should be an example. I don't know how the MARC data looks like. Can you share it?

**Comment by TobiasNx** [comment]
> HT014382984 (old MMS-ID: 990135991740206441) should be an example. I don't know how the MARC data looks like. Can you share it?

https://github.com/hbz/lobid-resources/blob/81d8a80b9f10d29bcdf77bf3daac371aff23843b/src/test/resources/alma/(DE-605)HT014382984.xml

**Comment by dr0i** [comment]
Deployed to production. Total hits now 1.391.336. @hagbeck @UBMakla: don't forget to adjust your treating the changed `hasItem.type`.
(note: it is not yet possible to [query the `hasItem.type`](http://alma.lobid.org/resources/search?q=hasItem.type%3APOR&format=json). As you don't do these queries, we use this index nonetheless. Will provide a fix soon).

**Comment by dr0i** [comment]
There was a bug in naming of the index when triggering ETL, see https://github.com/hbz/lobid-resources/issues/1159#issuecomment-826792981. Will recreate index. For the moment the index is without the "#1168 recreate all holdings" fix.

**Comment by dr0i** [comment]
Index ready now. Total results is slightly less (1.384.350). Could be because the incremental daily update( at least the bgzf) is not yet published.
> (note: it is not yet possible to [query the `hasItem.type`](http://alma.lobid.org/resources/search?q=hasItem.type%3APOR&format=json). 
It is now possible.
Closing.
