### ISSUE TITLE
facet value "Bestand in Bibliotheken" differs from factual results

### ISSUE THREAD

**Issue by hagbeck** [hbz/lobid-resources#1169]
From the Aleph based index we're getting 1.334.514 records [1]
The facet "Bestand in Bibliotheken" in the Aleph based index shows 1.471.170 records.

[1] http://lobid.org/resources/search?owner=http%3A%2F%2Flobid.org%2Forganisations%2FDE-290%23%21&aggregations=owner

**Comment by dr0i** [comment]
This is an lobid-resources UI issue, I think.
Don't know if @fsteeg can work this out?

**Comment by acka47** [comment]
This is a duplicate of #207. Let's further discuss it there. Closing.
