### ISSUE TITLE
Ignore every hasItem.heldBy that's not DE-290

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1172]
We should try to focus on  hasItem.heldBy to DE-290.
This would also help to identify the problem in https://github.com/hbz/lobid-resources/issues/1168.

@TobiasNx can you do that? Prio high.

**Comment by dr0i** [comment]
As we are moving closer to the correct amount of resources (aka "total hits") this issue may be obsolete. Moved to backlog.

**Comment by TobiasNx** [comment]
I think this can be closed.
