### ISSUE TITLE
Alma Index: holdings for DE-290 not available

### ISSUE THREAD

**Issue by hagbeck** [hbz/lobid-resources#1173]
The following resource contains no holding for us:

http://alma.lobid.org/resources/990055946050206441.json

DE-290 is the only owner for this resource.

**Comment by dr0i** [comment]
@TobiasNx can you use this example to figure out why it lacks the `heldBy`?

**Comment by TobiasNx** [comment]
I checked the MARC-XML.
This is due to the missing integration of only `"HOL"`-Holdings.
There is already an issue for that, see #1174

**Comment by dr0i** [comment]
As mentioned, this is a duplicate. Closing.

**Comment by dr0i** [comment]
(as this issue precedes the mentioned #1174 the latter is rather a duplicate. Just a note - we leave it as it is).

**Comment by dr0i** [comment]
This is solved by #1174, see http://alma.lobid.org/resources/990055946050206441.json.
