### ISSUE TITLE
Include HOL without ITM as information for hasItem

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1174]
HOL without ITM are used for multivolume works. We need to include them to in our hasItem information:

e.g.:
HT006855611

This should help to reduce the difference discussed in #1168

**Comment by TobiasNx** [comment]
I tried to filter in multiple ways none seems to work:

- if-Conditional in the entity:
```
      <if>
          <none>
            <data source="ITM  .a">
            </data>
          </none>
      </if>
```

works only without flushWith and without sameEntity="true" at the level of entity, but fills all information in one single object and creates duplicate keys

- variable outside the entity for ITM  .A which is used in if-Conditional in the entity
```
      <if>
          <none>
            <data source="@ITMexists">
            </data>
          </none>
      </if>
```

 same result as above


- if-Conditional outside the entity for creating a variable for HOL  .8 to be used in the entity 

only puts out the last version

- choose-Collector outside the entity (first ITM  .1 then HOL  .8) like this https://swissbib.gitlab.io/metamorph-doku/kochbuch/literale-in-entitaeten-wiederverwenden/ to create a variable for HOL  .8 to be used in the entity

only puts out the last version


it is very difficult or impossible (?) to only put out only HOL if ITM does not exist, because:
- when if-conditionals are referring to other entities it is not compatible with sameEntity="true"
- when if-condition is referring to a varibale is is only used once a later iteration seems not possible.
- we need to find a way to conditionally relate different entites of the source data.

**Comment by dr0i** [comment]
Cannot see the problem:
_if_ there is a HOL *and* a corresponding ITM (both having the same id, see e.g. HT005207972) your morph creates only _one_ item (fine!).
If there is only a HOL but no ITM the item is created nonetheless (e.g. HT006855611). Fine!

So you are all set.
Or have I missed something?

**Comment by TobiasNx** [comment]
Unfortunately HOL's and ITM's always have different IDs:

e.g. HT005207972
HOL$$8 -> HOL-ID:  2**2**1040645**7**0006445
ITM$$a -> ITM-ID:    2**3**1040645**6**0006445

The HOL-ID is also stated in ITM as subfield H but that is not used.

Therefore we have for HT005207972 objects in hasItem since there are 3 ITM and 3 HOL entries in this record. If it would be like you say it would have been only 3 entries.

We could separate between HOL and ITM entries if we would give HOL also a different type. But that awould not reduce the number of entries.

**Comment by TobiasNx** [comment]
@hagbeck would it be a problem if we provide all HOL entries as well regardless if there is an ITM or not?

**Comment by hagbeck** [comment]
I don't know. We have to try it.

**Comment by dr0i** [comment]
> you say it would have been only 3 entries.
but it _has_ only 3 items, see http://alma.lobid.org/resources/search?q=HT005207972&format=json.

**Comment by TobiasNx** [comment]
But this is change is not implemented yet or is it? https://github.com/hbz/lobid-resources/blob/master/src/main/resources/alma/common/item.xml

Result concerning testfile see:
https://github.com/hbz/lobid-resources/blob/2af03ca2914cf4aae8b483e016432eeac767d045/src/test/resources/alma/(DE-605)HT005207972.json#L7-L61

**Comment by dr0i** [comment]
Do a `git pull` and check again.

**Comment by dr0i** [comment]
If the `git pull origin master` is not working, in some rare moments do `git pull; git reset --hard origin/master` to ensure to be in sync.

**Comment by TobiasNx** [comment]
I will open an PR to clarify the differences between master and branch

**Comment by TobiasNx** [comment]
> I don't know. We have to try it.

@dr0i, If we are not able to filter them out, we could try to keep all HOL but add a different type lable to the HOL entry.

**Comment by TobiasNx** [comment]
@hagbeck I think we have solved this issue BUT one further question: Can records with `POR` have `HOL`? Then we have to filter out this possibility, too.

**Comment by dr0i** [comment]
It's not deployed yet. Reopend.

**Comment by dr0i** [comment]
Deployed, see e.g. http://alma.lobid.org/resources/search?q=HT006855611&format=json. Closing.

**Comment by hagbeck** [comment]
> @hagbeck I think we have solved this issue BUT one further question: Can records with `POR` have `HOL`? Then we have to filter out this possibility, too.

Hm, I don't know. But I don't think so, because POR and HOL/ITM should belong to different bibliographic records.

**Comment by blackwinter** [comment]
> Hm, I don't know. But I don't think so, because POR and HOL/ITM should belong to different bibliographic records.

These are known as so-called "hybrid" records (see [NZ-Publishing - Fragen an Verbundgruppe (Discovery W1): #1](https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=613646369); ex.: [99368110050706441](http://alma.lobid.org/resources/99368110050706441.json)).

**Comment by TobiasNx** [comment]
I reopen this Issue since it is relevant for ALMA-Fix and states an example of records with "HOL" but without "ITM" and "POR" for an institution.

The example here HT006855611 Holdings with ITM and some without.

**Comment by TobiasNx** [comment]
Found an example for a HOL without ITM and without other HOL/ITM combinations;  https://alma.lobid.org/marcxml/990055946050206441

**Comment by TobiasNx** [comment]
@UBmakla : 99370782520706441, http://test.lobid.org/resources/search?q=HT020936481&format=json , https://alma.lobid.org/marcxml/99370782520706441

Thanks I will have a look.

**Comment by TobiasNx** [comment]
Since this problem needs to be solved: I have a conceptual questions:

- HOL (Holdings) without ITMs are always records for superordinate objects as series, multivolume books, right?
- Do they have physicial respresentations, are they items?
- Dortmund seems to vary from other libraries since @UBmakla example has holdings with items (e.g. UDE) as well as holdings without items ( Dortmund ). What is the reason for that.
- Do the holdings without items have callnumbers or other local infos that we need?

**Comment by blackwinter** [comment]
Some quick remarks:

- Records with holdings but no items aren't "items" in the `hasItem` sense.
- In your example 990050000600206441, TU Dortmund (UBD) only has a few local fields, but neither holdings/items nor portfolios.
- `ITM` has subfield `$$H` that references `HOL$$8`. Portfolios (`POR`) don't relate to holdings (`HOL`) in any way.

**Comment by TobiasNx** [comment]
@blackwinter you are right my example was wrong but in my draft PR we see two examples where HOL with ITM and HOL without ITM are given: https://github.com/hbz/lobid-resources/pull/1546/files

**Comment by hagbeck** [comment]
Hi,
as @blackwinter said, those holdings don't have items in the sense of ITM or POR.

Let us understand all MARC records as instances of works. Some of them are itemized by physical objects (ITM) and some others by digital objects (POR). But some instances are not manifested directly and are therefore not itemized.
But all instances are contained in a libraries collection.
So we should insert holding collections like this for NWbib for each of the libraries of the union catalog to bind all relevant instances via `inCollection`.

**Comment by TobiasNx** [comment]
@hagbeck : 
@dr0i @acka47 and I had a look at it again:

1. We had a look at the way we did it in ALMA lobid. We constructed the info from MAB 088. Regardless of real items or not since this info was not given. Only the ALMA Transformation introduced "Typen von Lokaldatensätzen". This by the way broke the ALEPH-Transformation of the holdings since no institution was listed as holding which had Suffix `/RT` , `/NT`. `/ET`.

2. We had a look that there is no consistent way if a ressource has only HOL or an additional ITM: https://alma.lobid.org/marcxml/990050000600206441

3.Some Holdings without ITMs have additional infos in `HXX` - Elements that need to be listed somewhere.

4. `inCollection`-entries for every `HOL` creates duplicate info.

5. Main goal is for Users to find if an library holds an item or not.

On this basis we decided to go with the creation of items if a HOL has no item in `hasItem` even if this is semantically a little off. But it ensures contiuity to our old ALEPH transformation. Allows to add additional info if necessary.

We would introduce an additional type statement. If you have some suggestion we would be happy if you help.

**Comment by TobiasNx** [comment]
This should be implemented by tomorrow: https://github.com/hbz/lobid-resources/pull/1546

We now have as workaround Schrödingers Item: "type" : [ "Item", "NoItem" ], until we have an better type. Also I added callNumber and currentLocation if H52 is provided.

**Comment by dr0i** [comment]
I this implementes with https://github.com/hbz/lobid-resources/pull/1546 ?

**Comment by TobiasNx** [comment]
Besides our decision here: https://github.com/hbz/lobid-resources/issues/1174#issuecomment-1362978569

To be able to differentiate "NurTitel"  from "PhysikalischerTitel" I replaced "NoItem" with the two workaround types "NurTitel" and "PhysikalischerTitel" until we have better type names for them: https://github.com/hbz/lobid-resources/commit/210b1581ec499899b383251f5700eaf8fe30f820

I will close this ticket and and open a new ticket for better naming of item types.
