### ISSUE TITLE
Add local subjects with provinence 982$$.a/b (ALMA) 

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1175]
In Alma local subject keywords are provided in subfield 982. These are e.g. keywords given by the authors of a dissertation. They can help if somebody is searching for something.

MARC fiels **982** subfield **a** provides unseparated keywords, subfield **b** offers seperated keywords subfield **M** states the provinence

e.g. 991012024039706445 / HT015011399

```xml
<datafield tag="982" ind1=" " ind2=" ">
<subfield code="a">FB 03; RabGTPase; Guaninnukleotidaustauschfaktor; Vesikulärer Transport; MSS4; Sec2</subfield>
<subfield code="9">LOCAL</subfield>
<subfield code="M">49HBZ_UBD</subfield>
</datafield>
```

Difficulties will be that the separation sign is not always the same in subfield a

Where should we store them? I think we should store them as separate keyword array to not provoke API-break and allways add the provinence.

**Comment by TobiasNx** [comment]
@acka47 What do you think is a good way to provide these local keywords which are also usable for external users?

**Comment by acka47** [comment]
This sounds very similar to #536 where we added free subjects to the `subject` array like this ([example](https://lobid.org/resources/TT002234459.json)):

```json
{
  "source":{
    "id":"http://www.wikidata.org/entity/Q47524318",
    "label":"Freie Verschlagwortung"
  },
  "label":"Wandern, Diez, Lahnstein, Rhein-Lahn-Info, Rhein, Lahn, Wirtschaftsförderung"
}
```
Accordingly, the example from this issue could look like this:

```json
{
  "source":{
    "id":"http://www.wikidata.org/entity/Q47524318",
    "label":"Freie Verschlagwortung"
  },
  "label":"FB 03; RabGTPase; Guaninnukleotidaustauschfaktor; Vesikulärer Transport; MSS4; Sec2"
}
```

Will we have to keep the provenance? I am not sure how to best represent this. The most pragmatic approach might be to use the `source` field like this:

```json
{
  "source":{
    "id":"http://lobid.org/organisations/DE-290#!",
    "label":"Freie Verschlagwortung durch DE-290"
  },
  "label":"FB 03; RabGTPase; Guaninnukleotidaustauschfaktor; Vesikulärer Transport; MSS4; Sec2"
}
```

**Comment by dr0i** [comment]
@acka47 +1 for the most pragmatic approach!
Assigning @TobiasNx for takeover.

**Comment by TobiasNx** [comment]
@acka47 In  https://github.com/hbz/lobid-resources/issues/536 you wrote the free subjects should now be stored in `subject`. Has `subjectAltLabel` become obsolete? It is still in use.

**Comment by acka47** [comment]
> Has `subjectAltLabel` become obsolete?

The field `subjectAltLabel` is a transitional workaround, because alternative labels in the Aleph data are not clearly associated  with a specific subject. Our solution was to put them all in one field to at least enable search by altLabels (see https://github.com/hbz/lobid-resources/issues/197#issuecomment-287703813) . AFAIK, we don't have this problem with the Alma data and will be able to attach the altLabels to the respective subject so that `subjectAltLabel` can finally be removed when switching from Aleph.

> Also what is the convention now for "Freie Verschlagwortung" in general? Do we use only one subject per label and object, or all?

Until now, we handled this like thte field would only be used for seaching and not for display. Thus, putting it all in one string should suffice.

> It seems that the "Freie Verschlagwortungs-Convention" is not represented in the schema yet.

Please add it if you see that it's necessary.

**Comment by TobiasNx** [comment]
> > Has `subjectAltLabel` become obsolete?
> 
> The field `subjectAltLabel` is a transitional workaround, because alternative labels in the Aleph data are not clearly associated with a specific subject. Our solution was to put them all in one field to at least enable search by altLabels (see [#197 (comment)](https://github.com/hbz/lobid-resources/issues/197#issuecomment-287703813)) . AFAIK, we don't have this problem with the Alma data and will be able to attach the altLabels to the respective subject so that `subjectAltLabel` can finally be removed when switching from Aleph.

Unfortunately at least for GND-Terms altLabels are added at the end of an record - all fields starting with "GXX". At least for now Metafacture is not able to sort them to the subject we have because the source data is in different entities. It seems that we have to stick to the altLabel workaround.

> 
> > Also what is the convention now for "Freie Verschlagwortung" in general? Do we use only one subject per label and object, or all?
> 
> Until now, we handled this like thte field would only be used for seaching and not for display. Thus, putting it all in one string should suffice.

Okay, will do for now. But for consistency purposes I think it should not be that difficult to create a single object for each single subject. 

> 
> > It seems that the "Freie Verschlagwortungs-Convention" is not represented in the schema yet.
> 
> Please add it if you see that it's necessary.

**Comment by dr0i** [comment]
Just a note:
> Metafacture is not able to sort them to the subject we have because the source data is in different entities

this is true in conjunction with the JsonEncoder. Working with triples, this is doable (I know we don't want to switch to use triples->json as we did in the Aleph-lobid-resources).

**Comment by TobiasNx** [comment]
@hagbeck
It seems that "982" is repeatable AND that is hase multiple keywords (unaufgegliedert) as in you example but also single keywords as in this example:

https://github.com/hbz/lobid-resources/blob/814baaf810f11bcd782eb89f9d2a81a33eb939b2/src/test/resources/alma/(DE-605)HT020202475.xml#L130-L149

Can you work with multiple keyword entries for UB Dortmund?

**Comment by hagbeck** [comment]
Yes, it's ok. We will only index them and will not use them for display.

I hope, that this sometimes strange keywords are cleaned up by the current migration.
