### ISSUE TITLE
Add 689 as subject>compelexSubject (ALMA)

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1176]
At the moment keywords and subjects are missing.
We need to add them.

See https://www.loc.gov/marc/bibliographic/bd6xx.html for keywords and subjects

@dr0i could you add http://alma.lobid.org/resources/990171142550206441.json as testfile since it was mentioned at our last meeting with @blackwinter and @hagbeck
It should have at least have keywords FFBR, Conceptual Model ...

I will start with 689, other keywords / subjects should get their own tickets.

**Comment by TobiasNx** [comment]
```
  <datafield tag="689" ind1="1" ind2="0">
    <subfield code="a">Ingenieurwissenschaften</subfield>
    <subfield code="D">s</subfield>
    <subfield code="0">(DE-588)4137304-2</subfield>
    <subfield code="0">(uri) https://portal.dnb.de/opac.htm?method=simpleSearch&amp;cqlMode=true&amp;query=idn=041373049</subfield>
    <subfield code="0">(uri) http://viaf.org/viaf/sourceID/DNB|041373049</subfield>
    <subfield code="B">GND-041373049</subfield>
  </datafield>
```

Field 689 is not documented https://www.loc.gov/marc/bibliographic/bd6xx.html

**Comment by dr0i** [comment]
Added 990171142550206441 in https://github.com/hbz/lobid-resources/pull/1182.
Reassigning @TobiasNx .

**Comment by dr0i** [comment]
Re undocumented field `689`:
It's "RSWK Schlagwortketten", see https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=581533808#AnpassungenabDezember2020ff.-AuthorityEnrichment2020-12-09.

**Comment by dr0i** [comment]
Re missing field `650`: just asked about it at https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=562135157#NZ-Publishing-fachlich-technischerAustausch(DiscoveryW1)-GNDSubjects,re:Feld650,fehlen.

**Comment by blackwinter** [comment]
`650` is present:

```xml
<datafield tag="650" ind1=" " ind2="0">
  <subfield code="a">FRBR (Conceptual model)</subfield>
</datafield>
```

GND enrichments are published as `Gxx` (see [Test "Authority Enrichment" (Discovery W1)](https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=554041781) and [NZ-Publishing für Discovery-Anbindung (DISC): Authority Enrichment](https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=612532300#NZ-Publishingf%C3%BCrDiscovery-Anbindung(DISC)-AuthorityEnrichment)).

**Comment by dr0i** [comment]
@blackwinter re 650: oh, thx for the clarifying ... must have had tomatoes upon my eyes ... 
re `Gxx`: thx for the pointer!

**Comment by TobiasNx** [comment]
@blackwinter: Do you know why the GND-Nr / URI or Links is are not always the correct GND-Nr in ALMA?
e.g.: HT015671602 // 990171142550206441
```
  <datafield tag="689" ind1="0" ind2="0">
    <subfield code="a">Functional Requirements for Bibliographic Records</subfield>
    <subfield code="D">s</subfield>
    <subfield code="0">**(DE-588)7615733-7**</subfield>
    <subfield code="0">(uri) **https://portal.dnb.de/opac.htm?method=simpleSearch&amp;cqlMode=true&amp;query=idn=989254461**</subfield>
    <subfield code="0">(uri) **http://viaf.org/viaf/sourceID/DNB|989254461**</subfield>
    <subfield code="B">**GND-989254461**</subfield>
  </datafield>
...
  <datafield tag="GST" ind1=" " ind2=" ">
    <subfield code="a">FRBR</subfield>
    <subfield code="A">GND</subfield>
    <subfield code="B">**GND-989254461**</subfield>
    <subfield code="C">450</subfield>
  </datafield>
  <datafield tag="GSI" ind1="7" ind2=" ">
    <subfield code="a">**http://d-nb.info/gnd/7615733-7**</subfield>
    <subfield code="2">uri</subfield>
    <subfield code="A">GND</subfield>
    <subfield code="B">**GND-989254461**</subfield>
    <subfield code="C">024</subfield>
  </datafield>
```
There are two numbers: **GND-989254461** and **7615733-7**.

**7615733-7**: is the real one and it is used in on instance of _689 00.0_ and _GSI   .a_ as part of the URI. 

**GND-989254461**: is used in the other links in _689 00.0_ but the links are broken and also in _689 00.B_, _GST  .B_, _GSI  .B_ 

The second number is more present but only seems to be an internal number? Or is the data still not correct?

**Comment by blackwinter** [comment]
They are both [GND IDs](https://www.dnb.de/DE/Service/Hilfe/Katalog/kataloghilfeExpertensuche.html#sprg264690): `7615733-7` = `nid`, `989254461` = `idn`. Both can be used in [links](https://www.dnb.de/DE/Service/Hilfe/Katalog/kataloghilfe.html#link): http://d-nb.info/gnd/7615733-7, http://d-nb.info/989254461. The `portal.dnb.de` link is working, only the `viaf.org` link is broken.

**Comment by TobiasNx** [comment]
Thanks a lot. That helps to understand this issue better.

One thing though:
The GND-Link in 689 00.0 https://portal.dnb.de/opac.htm?method=simpleSearch&amp;cqlMode=true&amp;query=idn=989254461 is also broken. I receive "Fehler".

**Comment by blackwinter** [comment]
Did you replace the XML entities? ;)

https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=idn=989254461

**Comment by TobiasNx** [comment]
I am still confused:

> idn
> 
> Mit idn wird ausschließlich die Identifikationsnummer eines **Titeldatensatzes der Deutschen Nationalbibliothek oder eines Personen-Normdatensatzes (GND**) gefunden. Die Identifikationsnummern stehen am Ende der URL des Link zu diesem Datensatz über den Metadaten.
> 
> nid
> 
> Mit nid wird ausschließlich die **Identifikationsnummer eines Normdatensatzes der GND oder der Deutschen Nationalbibliothek** gefunden. Die Identifikationsnummern stehen am Ende der URL im Link zu diesem Datensatz über den Metadaten.

and


> 1.12 Link zu diesem Datensatz
> 
> Jeder Datensatz im Katalog hat einen eindeutigen Link. Diese URL mit der Basisadresse http://d-nb.info/ zeigt immer auf die aktuelle Fassung des Datensatzes und kann als Favorit gespeichert oder in andere Systeme eingebunden werden.
> 
> Beispiel: http://d-nb.info/990064271
> Ergebnis: Dieser Link führt zu dem Titeldatensatz „Erläuterungen zu Bertolt Brecht, Der gute Mensch von Sezuan / von Horst Grobe“.
> 
> Beispiel: http://d-nb.info/gnd/118514768
> Ergebnis: Dieser Link führt zu dem GND-Datensatz von „Brecht, Bertolt“.
> 
> 

(Quelle: https://www.dnb.de/DE/Service/Hilfe/Katalog/kataloghilfe.html?nn=260400#link)

Which is the URI? Also I am confused since in the documentation it says **idn** is for person GND records. Also the links http://d-nb.info/989254461 resolves as query and at the site then states http://d-nb.info/gnd/4322126-9 as the URI.

Anyyway:
I probably should use `689` instead of `GSI` or `GST`

**Comment by TobiasNx** [comment]
> Did you replace the XML entities? ;)
> 
> https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=idn=989254461

Hmm, I don't think so, perhaps perhaps our testfiles are old.

**Comment by blackwinter** [comment]
> Which is the URI? Also I am confused since in the documentation it says **idn** is for person GND records. Also the links http://d-nb.info/989254461 resolves as query and at the site then states http://d-nb.info/gnd/4322126-9 as the URI.

I'm not sure what you're trying to achieve exactly. What do you mean by _the_ URI?

> Hmm, I don't think so, perhaps perhaps our testfiles are old.

What do you mean? Which link did you try? The link in the quoted XML fragment above - necessarily - contains XML entities, so it's not clickable, if that's what you mean.

**Comment by TobiasNx** [comment]
> > Which is the URI? Also I am confused since in the documentation it says **idn** is for person GND records. Also the links http://d-nb.info/989254461 resolves as query and at the site then states http://d-nb.info/gnd/4322126-9 as the URI.
> 
> I'm not sure what you're trying to achieve exactly. What do you mean by _the_ URI?
> 
> > Hmm, I don't think so, perhaps perhaps our testfiles are old.
> 
> What do you mean? Which link did you try? The link in the quoted XML fragment above - necessarily - contains XML entities, so it's not clickable, if that's what you mean.

Okay, you are right, I did not know that. That's explains why the link seems not to work.

Concerning "the" URI: What is the usual/main identifier that is used for GND. Seems to me that http://d-nb.info/gnd/4322126-9 is it.

But since I will approach the subject transformation via `689` and use http://d-nb.info/gnd/4322126-9 as id.

**Comment by TobiasNx** [comment]
I leave this here for me, it displays the indicator and subfield structure in marc for 689 as suggested by the DNB. Also it should be highlighted that Schlagwortkette is not used anymore concept but Schlagwortfolge a lot of hbz internal documentation still uses the old concept Schlagwortkette which has been substituted by Schlagwortfolge in 2010 in RWSK.

https://wiki.dnb.de/display/MARC21AE/Anwenderebene+Titeldaten+Feld+689

**Comment by TobiasNx** [comment]
I will open another ticket for the different types of keywords and subjects. Here only "Schlagwortfolgen/Schlagwortketten" relating to 689 should be discussed.

**Comment by TobiasNx** [comment]
We have subject components that do not relate to GND but that are given a type character in ALMA/MARC.
These have type specifications in subfield A and not in subfield D.

e.g.:
```XML
  <datafield tag="689" ind1="0" ind2="2">
    <subfield code="a">Online-Ressource</subfield>
    <subfield code="A">f</subfield>
  </datafield>
  <datafield tag="689" ind1="0" ind2="3">
    <subfield code="a">Zeitschrift</subfield>
    <subfield code="A">f</subfield>
  </datafield>
```

Subfield "A" refers to values-list:
    f - Formschlagwort
    g - Zeitschlagwort
    z - Veranstaltungsort (und -zeit)

Our type-vocabulary (almost identical to the vocab list in Subfield D) allows for 
https://github.com/hbz/lobid-resources/blob/352d5f628046f05eb7b191202163bcd29dc13708/src/test/resources/schemas/complexSubject.json#L35-L43

@acka47 How should I type Formatschlagwort, Zeitschlagwort and Veranstaltungsort? Should I only add them to the enum-List? If so, do you have suggestions what kind of type I should use or where I could look for possible concepts?

**Comment by dr0i** [comment]
Closed inadvertently, reopening.

**Comment by dr0i** [comment]
All related PRs are merged, and field 689 seems to be dealt with already #1192. So closing this.
