### ISSUE TITLE
No data for related records (Alma)

### ISSUE THREAD

**Issue by hagbeck** [hbz/lobid-resources#1179]
Currently there are no IDs to related records such as multi volume works.

Example: 990225056670206441 (TT003907920) is part of 990050000600206441 (HT006855611). In Alma this relation seems to be documented via field 773

`773	08 |w (DE-605)HT006855611 |q 3`

and only via hbz-ID and not via MMS-ID. But the representation in the publishing results might be different.

Btw.: 990225056670206441 (TT003907920) is an example without DE-290 as owner

**Comment by blackwinter** [comment]
The planned, but not yet enabled, [related records enrichment](https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=525926523) might be helpful here. The existing linking entries (based on the hbz-ID) originate from Aleph CC.

**Comment by hagbeck** [comment]
Today I've learned that we don't get MMS-IDs for related records for the time being. So we have to use the hbz-/Aleph-ID in MARC field 773 subfield w. Subfield q seems to be the volume number.

**Comment by dr0i** [comment]
Moving this up to "ready", since we should care about this because at 26th April we have to deal with it. As I understand the field is not yet in the source MARC but we can treat it in the morph as if it were already present.

**Comment by blackwinter** [comment]
Linking fields - based on the hbz-ID - are already present. This doesn't change with the initial publishing after Go Live.

The question is, AFAIUI, if/when MMS IDs become available for linking.

**Comment by dr0i** [comment]
Deployed to production, see e.g. http://alma.lobid.org/resources/990225056670206441.json.

**Comment by UBmakla** [comment]
no data for related records in 990225980070206441

**Comment by dr0i** [comment]
990225980070206441 seems to have it's `hasPart` information in MARC `830$0.w` - at least there is no `773` in the MARC sources (and that's the field that was treated in  https://github.com/hbz/lobid-resources/pull/1217 ):
```
<datafield tag="830" ind1=" " ind2="0">
<subfield code="a">Kunst & Kohle</subfield>
<subfield code="w">(DE-605)HT019688715</subfield>http://lobid.org/resources/HT019688715
```

So it seems we have to take MARC `830$0.w` into account, too?

**Comment by TobiasNx** [comment]
`830` is refering to _Series Added Entry-Uniform Title_


> Series added entry consisting of a series title alone.
> 
> An 830 field is usually justified by a series statement (field 490) or a general note (field 500) relating to the series. For reproductions, it may be justified by a series statement in subfield $f of field 533 (Reproduction Note)

 ([Source](https://www.loc.gov/marc/bibliographic/bd830.html))

Subfield `$w `:


> $w - Bibliographic record control number   [830]
> 
> See description of this subfield in [Appendix A: Control Subfields.](https://www.loc.gov/marc/bibliographic/ecbdcntf.html)
>
([Source](https://www.loc.gov/marc/bibliographic/bdx30.html))

**Comment by TobiasNx** [comment]
I added 830 to isPartOf and filtered duplicates out with an if conditional.

**Comment by TobiasNx** [comment]
we should leave the ticket open and add "labels" in the "hasSuperordinate"

**Comment by dr0i** [comment]
Deployed, see e.g. https://alma.lobid.org/resources/search?q=HT017015300&format=json. Closed.

**Comment by dr0i** [comment]
Reported in https://github.com/hbz/lobid-resources/issues/1258:
The title is missing in http://alma.lobid.org/resources/search?q=990225980070206441&format=json although it's in the  Alma Marc Source (as noted here https://github.com/hbz/lobid-resources/issues/1179#issuecomment-827591591).
Also, the id should be a valid lod URI like: "http://lobid.org/resources/$HT-NR#!" .
