### ISSUE TITLE
Add GND Enrichment as altLabels (ALMA)

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1190]
GND Enrichment (`GXX`) provides the altLabels for GND used on other locations in a record. It should be included as `"altLabels"`

**Comment by TobiasNx** [comment]
https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=612532300

I added as subjectAltLabels:
GPN
GST
GGN


GKT seems very complex since part of the name can be in subfield a, b and g.
GKS and GEL were not represented in the test files.

**Comment by dr0i** [comment]
Deployed, see e.g. http://alma.lobid.org/resources/990153086040206441.json.
