### ISSUE TITLE
Add DDC (ALMA)

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1191]
DDC Metadata is located in Marc field `082`, which is not repeatable.
See: https://www.loc.gov/marc/bibliographic/bd082.html

Also additional DDC Metadata can be found `083`
See: https://www.loc.gov/marc/bibliographic/bd083.html

**Comment by dr0i** [comment]
Deployed, see e.g. http://alma.lobid.org/resources/99368090810506441.json.
