### ISSUE TITLE
Add responsibilityStatement (field 245??.c)

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1194]
Like in http://lobid.org/resources/HT000068434.json we need `responsibilityStatement` in http://alma.lobid.org/resources/990000597810206441.json.

**Comment by dr0i** [comment]
There is already a test resource reflecting this field: `(DE-605)HT020202475.xml`.

**Comment by TobiasNx** [comment]
Subfield .c is prrovided with every 245 field, which appearse once in a record.

**Comment by TobiasNx** [comment]
@acka47: responsibilityStatement is an array. The source of it is a non repeatable field. Should this be changed to a string value, or is this a too strong api break?

**Comment by acka47** [comment]
>  `responsibilityStatement` is an array. The source of it is a non repeatable field `245??c` (MAB `359# $$a`). Should this be changed to a string value, or is this a too strong api break?

This would be an API break, yes. As discussed in the meeting today, we will leave it like this.

**Comment by dr0i** [comment]
Deployed, see e.g. http://alma.lobid.org/resources/990001412590206441.json and http://alma.lobid.org/resources/990000597810206441.json.
