### ISSUE TITLE
Consistently use 2-space identation in ALMA Morph and Maps

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1200]
as discussed off board, we should have a consistent identation in all morph/map files for ALMA.
This we will do after @dr0i merged the open PR connected to ALMA.

**Comment by dr0i** [comment]
Reassigning @TobiasNx .
Go on to reformat the morphs - I don't have any open PRs and thus I will be free of conflicts :)

**Comment by dr0i** [comment]
Also note that I added this formatting issue to our [maintainer guidelines](https://github.com/hbz/lobid-resources/wiki/Maintainer-Guidelines#formatting) for future reference.

**Comment by dr0i** [comment]
If you are on it, maybe this is a good time to also update re https://github.com/hbz/lobid-resources/issues/1224#event-4654810460 (in a commit on it's own to have SOC).

**Comment by dr0i** [comment]
Merged and closing.
