### ISSUE TITLE
Multiple title keys

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1209]
See: HT003176544

https://github.com/hbz/lobid-resources/blob/d986f75654e26989e9d3abb77d63b86ce29ff9d5/src/test/resources/alma/(DE-605)HT003176544.json

**Comment by TobiasNx** [comment]
http://lobid.org/resources/HT003176544.json

In comparison to our old transformation we have multiple differences. Title information should be rebuild.

Marc provides this:

```XML
  <datafield tag="245" ind1="0" ind2="0">
    <subfield code="a">Reisen in Deutschland</subfield>
    <subfield code="b">deutsches Handbuch f&#252;r Fremdenverkehr</subfield>
    <subfield code="n">Band 2</subfield>
    <subfield code="p">Reisegebiete in Berlin (West), Bremen, Hamburg, Nordrhein-Westfalen, Niedersachsen, Rheinland-Pfalz, Saarland, Schleswig-Holstein</subfield>
    <subfield code="c">hrsg. im Auftrag des Deutschen Fremdenverkehrsverbandes e.V. Frankfurt/Main und in Zusammenarbeit mit dem Deutschen B&#228;derverband e.V</subfield>
  </datafield>
```
At the moment _$a_ and _$p_ are used as `"title"`-source. _$b_ as `"otherTitleInformation"`. _$n_ is not morphed yet. (only as comment)
 _$c_ is responsibilityStatement that can be excluded here and was solved in #1197. 

$p should not end in `"title"` but in `titleOfSubseries` as used in lobid aleph. But perhapse we should use another key since it refers to volumes and not series.

**Comment by TobiasNx** [comment]
I morphed 245 $p to `"titleOfSubSeries"`.

Conceptually `"titleOfSubSeries"` does not completely reflect "_245 $$p Haupttitel das Bandes oder der Unterreihe_" (https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=483000321) We should think about changing the key in the future perhaps. @acka47

**Comment by acka47** [comment]
> Conceptually `"titleOfSubSeries"` does not completely reflect "_245 $$p Haupttitel das Bandes oder der Unterreihe_" (https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=483000321) We should think about changing the key in the future perhaps. 

Yes, this is not the right property and, additonally, the property used is now deprecated, see http://rdaregistry.info/Elements/u/P60517. So, we should think about a better one although this would mean an API break. We should probably better create a separate issue for this. I already looked at Bibframe and the RDA unconstrained properties but could not find anything that might fit.
