### ISSUE TITLE
Use bibo:Periodical (or similar) instead of bibo:Journal

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#121]
Realized this [tweeting](https://twitter.com/acka47/status/793066162246606848) about ZDB data in lobid. Many ZDB resources are not Journals in the strict sense but periodicals. That's why we should map MAB `<controlfield tag="052">p||||||||||||||</controlfield>` to `bibo:Periodical` or – as we want to get away from bibo – something equivalent class like `schema:Periodical`.

**Comment by ChristophEwertowski** [comment]
@acka47 
1. What's the reason for leaving bibo? 

2. Definition of periodicals of bibo and schema.org

[bibo](http://bibliographic-ontology.org/bibo/bibo.php#Periodical)
> A group of related documents issued at regular intervals.

 [schema.org](https://schema.org/Periodical)
> A publication in any medium issued in successive parts bearing numerical or chronological designations and intended, such as a magazine, scholarly journal, or newspaper to continue indefinitely.

Periodical is the only publication type which has got an issn, so if we take schema.org we have to take it. 
In the case of bibo series isn't a subclass of periodical but standing besides periodical. 

3. Periodika ≠ periodicals?
Moreover it seems to me that there is no 100 percent translation of "Periodika" in English. While my understanding of "Periodika" is that all periodically published works are covered, in English it seems to be the case that "periodical" concentrates more on smaller issues (as a clue see [Periodical (Wikipedia, en)](https://en.wikipedia.org/wiki/Periodical_literature) and the media section of [Series (Wikipedia, en)](https://en.wikipedia.org/wiki/Series). But if there is no perfect translation we have to take "Periodical".

**Comment by acka47** [comment]
> 1. What's the reason for leaving bibo? 

We were thinking about this when I opened the issue but since then decided to keep it. For more information see #108. Thus, I don't mind using `bibo:Periodical`.

**Comment by ChristophEwertowski** [comment]
The DNB differentiates between periodical and series [page 6](http://www.dnb.de/SharedDocs/Downloads/DE/DNB/service/linkedDataModellierungTiteldaten.pdf?__blob=publicationFile) (September 2016). But in their norm data file http://d-nb.info/gnd/4155074-2 they combine "Monografische Reihe", "Zeitschrift" and "Reihe" under the term "Fortlaufendes Sammelwerk"/"Periodikum <Fortlaufendes Sammelwerk>".
Also [wikidata](https://www.wikidata.org/wiki/Q1002697) has a definition and examples in German which describe both journals and similar publication types and book series under the term "periodical literature". 

Finally I didn't found a bibo:Periodical or bibo:Journal or bibo:Series at the [RDF version of Bibframe](http://id.loc.gov/ontologies/bibframe.rdf). In a nutshell: I would stick with periodical in whatever vocabulary we use.
