### ISSUE TITLE
Rename TitleOther.title to alternativeTitle

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1212]
While working at #1209: having a look at the diff of all `tilte` related fields  between aleph.lobid and alma.lobid:
Alma:
```
"title" : "Reisen in Deutschland",
"otherTitleInformation" : [ "deutsches Handbuch für Fremdenverkehr" ],
 "titleOfSubSeries" : "Reisegebiete in Berlin (West), Bremen, Hamburg, Nordrhein-Westfalen, Niedersachsen, Rheinland-Pfalz, Saarland, Schleswig-Holstein",
 "TitleOther" : {
              "title" : [ "Reisen in Deutschland / 2" ]},
```
Aleph:
```
"title": "Reisen in Deutschland",
otherTitleInformation": ["deutsches Handbuch für Fremdenverkehr"],
"titleOfSubSeries": "Band 2, Reisegebiete in Berlin (West), Bremen, Hamburg, Nordrhein-Westfalen, Niedersachsen, Rheinland-Pfalz, Saarland, Schleswig-Holstein",
"alternativeTitle": ["Bayern","Reisen in Deutschland / 2"],
```

1. `TitleOther.title` should be named to `alternativeTitle`
2. is `"titleOfSubSeries": "Band 2` really a title of the subseries? If so, add it in alma also.

**Comment by TobiasNx** [comment]
$n - Number of part/section of a work (R) 

so it is not the name of the subvolume but it's number. It should be represented somehow!

**Comment by dr0i** [comment]
Deployed, see e.g. https://alma.lobid.org/resources/search?q=HT003176544&format=json. Closing.
