### ISSUE TITLE
Title of subvolume and subseries (245?? $p)

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1215]
> Conceptually `"titleOfSubSeries"` does not completely reflect "_245 $$p Haupttitel das Bandes oder der Unterreihe_" (https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=483000321) We should think about changing the key in the future perhaps. 

Yes, this is not the right property and, additonally, the property used is now deprecated, see http://rdaregistry.info/Elements/u/P60517. So, we should think about a better one although this would mean an API break. We should probably better create a separate issue for this. I already looked at Bibframe and the RDA unconstrained properties but could not find anything that might fit.

_Originally posted by @acka47 in https://github.com/hbz/lobid-resources/issues/1209#issuecomment-824654993_

**Comment by TobiasNx** [comment]
Official RDA -> Marc Mapping (http://www.rdaregistry.info/Maps/mapRDA2M21B.html) says:

http://www.rdaregistry.info/Elements/w/#P10088 

"has title of work"
but this is the most general one.

**Comment by TobiasNx** [comment]
[Since the numbering and the name of a subvolume is now included in the title,](https://github.com/hbz/lobid-resources/issues/1320) due to the demand of EDU web and Dortmund should we get rid of `titleOfSubseries` since it only provides duplicated info.
http://test.lobid.org/resources/990054301770206441


It would be an API-Break which would be documented.

@dr0i suggested it already here: https://github.com/hbz/lobid-resources/issues/1320#issuecomment-989827626
@acka47 what do you think?

**Comment by acka47** [comment]
Taking a look at the test files, it seems to make much sense to remove `titleOfSubseries` from the data. I assume there won't be any cases where `titleOfSubseries` won't be part of `title`? If there are, we should keep the field in those cases. (This was triggered by reading [this comment](https://github.com/hbz/lobid-resources/issues/672#issuecomment-359828865) about `otherTitleInformation`.)

**Comment by TobiasNx** [comment]
I deleted `titleOfSubseries` with https://github.com/hbz/lobid-resources/pull/1593 it only has info that is also appended to the main title.
