### ISSUE TITLE
655 Format/Genre Subject (ALMA)

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1219]
e.g. HT000161712

```XML
  <datafield tag="655" ind1=" " ind2="7">
    <subfield code="a">W&#246;rterbuch</subfield>
    <subfield code="0">(DE-588)4066724-8</subfield>
    <subfield code="2">gnd-content</subfield>
  </datafield>
```

655 - Indexierungsterm - Genre/Formschlagwort (W)

Here again we would need a subject type for format? Is there any @acka47

**Comment by TobiasNx** [comment]
In the old morph this is transformed as "natureOfContent". Will transform this as this, too.

**Comment by dr0i** [comment]
Deployed, see e.g. http://alma.lobid.org/resources/search?q=hbzId:HT003176544&format=json.
