### ISSUE TITLE
610 Corporate Body  subject (ALMA)

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1221]
610 - Nebeneintragung unter einem Schlagwort - Körperschaftsname (W)

e.g.HT003176544

  ```XML
<datafield tag="610" ind1="2" ind2="4">
    <subfield code="a">Berlin</subfield>
  </datafield>
  <datafield tag="610" ind1="2" ind2="4">
    <subfield code="a">Bremen</subfield>
  </datafield>
  <datafield tag="610" ind1="2" ind2="4">
    <subfield code="a">Hamburg</subfield>
  </datafield>
  <datafield tag="610" ind1="2" ind2="4">
    <subfield code="a">Nordrhein-Westfalen</subfield>
  </datafield>
  <datafield tag="610" ind1="2" ind2="4">
    <subfield code="a">Niedersachsen</subfield>
  </datafield>
  <datafield tag="610" ind1="2" ind2="4">
    <subfield code="a">Rheinland-Pfalz</subfield>
  </datafield>
  <datafield tag="610" ind1="2" ind2="4">
    <subfield code="a">Saarland</subfield>
  </datafield>
  <datafield tag="610" ind1="2" ind2="4">
    <subfield code="a">Schleswig-Holstein</subfield>
  </datafield>
```

**Comment by dr0i** [comment]
Just wondering if `Corporate Body subject` should be typed as [Concept](https://www.w3.org/TR/2009/NOTE-skos-primer-20090818/#secconcept). We use already `Concept` e.g. `spatial.id:"https://nwbib.de/spatial#N20"` which denote a SKOSified URI. But this is not the case for the `Corporate Body subject` which lacks any URIs to begin with and thus lacks any SKOSification.

**Comment by TobiasNx** [comment]
Since we have a subjects that do not count as `"type": "complexSubject"` or `"type": "concept"` we introduced `"type": "keyword"` as type for those subjects that do not have controlled vocabs. `"type": "concept"` will be used for SKOS and also for other concepts from controlled vocabularies even if they do not have an id.

**Comment by dr0i** [comment]
Will be deployed at Monday.

**Comment by dr0i** [comment]
Deployed, se e.g. http://alma.lobid.org/resources/search?q=HT020202475&format=json. Closed.
