### ISSUE TITLE
Alma: corporatebody incomplete

### ISSUE THREAD

**Issue by hagbeck** [hbz/lobid-resources#1224]
In http://alma.lobid.org/resources/990206897010206441.json the CorporateBody in contribution is incomplete. We expect 
"Technische Universität Dortmund. Fakultät Architektur und Bauingenieurwesen" like in the GND record: https://d-nb.info/gnd/16178353-3

**Comment by dr0i** [comment]
Deployed, see e.g. http://alma.lobid.org/resources/990206897010206441.json.
@hagbeck please close this issue if you think it's solved.

**Comment by TobiasNx** [comment]
@dr0i: short reminder, we wanted to use fieldnumbers that are not shortend, so that you can search the morph.

**Comment by dr0i** [comment]
In this case that would mean to denote 6 fieldnumbers. I don't thinkf this is handy. Maybe we shall add all permutations as comments in the morph, like:
> 1100 .b ; 1101 .b ; 1102 .b ; 7100 .b ; 7101. b ; 7102 .b
Would that be ok? Or is it even sufficient to denote just the main fields (entities), like:
> 110; 710
I like the latter more. One could search then these fields and dig deeper looking at the morph.
What do you think @TobiasNx ?

**Comment by TobiasNx** [comment]
They only need to be two variants 110??. .b and 710??.b.
https://www.loc.gov/marc/bibliographic/bd110.html
The mapping is suitable for all indicators https://www.loc.gov/marc/bibliographic/bd110.html and https://www.loc.gov/marc/bibliographic/bd710.html.

But yes a comment would be good too.

**Comment by dr0i** [comment]
Added this to https://github.com/hbz/lobid-resources/wiki/Maintainer-Guidelines#field-numbers-in-morph.
We might someday refactor the morphs to reflect that or do it step by step.
Closing this issue and apologizing for being a bit offtopic here.
