### ISSUE TITLE
double author in 990181275760206441

### ISSUE THREAD

**Issue by UBmakla** [hbz/lobid-resources#1226]
Two times Contribution.gndIdentifier:"1049517296", see  http://alma.lobid.org/resources/search?q=990181275760206441&format=json .

**Comment by dr0i** [comment]
Hm, it is also two times present in the Alma Marc Xml : 

```
<datafield tag="100" ind1="1" ind2=" ">
<subfield code="a">Furlan, Peter</subfield>
<subfield code="d">1953-</subfield>
<subfield code="0">(DE-588)1049517296</subfield>
<subfield code="4">aut</subfield>
<subfield code="9">O:H</subfield>
<subfield code="0">
(uri) https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=idn=1049517296
</subfield>
<subfield code="0">(uri) http://viaf.org/viaf/sourceID/DNB|1049517296</subfield>
</datafield>
...
<datafield tag="100" ind1="1" ind2=" ">
<subfield code="a">Furlan, Peter</subfield>
<subfield code="d">1953-</subfield>
<subfield code="0">(DE-588)1049517296</subfield>
<subfield code="4">aut</subfield>
<subfield code="9">O:H</subfield>
<subfield code="M">49HBZ_UBD</subfield>
</datafield>```

I am not sure what to do. Is this wrongly cataloged, or has it something to do with the "Lokalsystem" and we should  avoid ETL if '100.1$M'="49HBZ_UBD" ? Maybe you have an idea @blackwinter ?

**Comment by blackwinter** [comment]
Exactly, the second one is a local field. It should supersede the NZ field, but i'm not certain that's the case for all fields.

Besides, it's quite possibly a serious problem for your "global" index - having both "global" and local fields side by side. Not to mention the difficulty of transforming such a structure with Metamorph.

**Comment by TobiasNx** [comment]
Can all marc-fields exist as global and local? Do local fields always have subfield `M`?

**Comment by blackwinter** [comment]
> Can all marc-fields exist as global and local?

I guess so, more or less. Would have to ask a cataloguing expert.

> Do local fields always have subfield `M`?

Yes.

**Comment by blackwinter** [comment]
On the other hand, did you previously include these "overridden" fields? I assume not, as you didn't have access to them via Aleph CC. So maybe it would indeed be a legitimate "solution" to ignore those fields? That's what we're contemplating for IntrOX as well.

**Comment by TobiasNx** [comment]
> On the other hand, did you previously include these "overridden" fields? I assume not, as you didn't have access to them via Aleph CC. So maybe it would indeed be a legitimate "solution" to ignore those fields? That's what we're contemplating for IntrOX as well.

I don't think that we included those fields before. At least, I was not aware of them before. But it would have created lots of duplicate information. @blackwinter is the information normally included, or did something change with the provided Marc-Data?
 @dr0i has something changed with our import?

**Comment by blackwinter** [comment]
No, there was no change. These fields were always included in the Alma data.  But they weren't included in the Aleph data, that's what I meant.

**Comment by TobiasNx** [comment]
> > Can all marc-fields exist as global and local?
> 
> I guess so, more or less. Would have to ask a cataloguing expert.
> 
> > Do local fields always have subfield `M`?
> 
> Yes.

Okay, I had a look at our test data. Local fields are used for 020, 340, 500, 505, 830,  856, 980, 981, 982, 983, 996, 997. And now 100.
It seems that especially Dortmund is using local variants of these fields. But this can be due to the test data is connected to issues of UDB.
@UBmakla and @hagbeck is UBD using the local fields more than other libraries?And is this a deliberate local usage for this 100 field as it just repeats the global entry.

**Comment by hagbeck** [comment]
I've no idea, why we have so many local variants. This is strange ... I will ask our catalogers.

**Comment by blackwinter** [comment]
> > Can all marc-fields exist as global and local?
> 
> I guess so, more or less. Would have to ask a cataloguing expert.

"Beispiel: Im Extension Pack der NZ können Felder vorhanden sein:
009, 090, 100, 110, 111, 240, 249, 250, 264, 290, 300, 336, 337, 338, 340, 344, 345, 346, 347, 382, 385, 500, 502, 655, 689, 700, 710, 711, 751, 770, 772, 773, 775, 776, 777, 780,785, 787, 900, 910, 912, 924, 925, 929, 930, 931, 932, 960, 961, 962, 963, 964 (?)." (see "Zentrale und lokale MARC 21-Felder im hbz")

**Comment by TobiasNx** [comment]
> > > Can all marc-fields exist as global and local?
> > 
> > 
> > I guess so, more or less. Would have to ask a cataloguing expert.
> 
> "Beispiel: Im Extension Pack der NZ können Felder vorhanden sein:
> 009, 090, 100, 110, 111, 240, 249, 250, 264, 290, 300, 336, 337, 338, 340, 344, 345, 346, 347, 382, 385, 500, 502, 655, 689, 700, 710, 711, 751, 770, 772, 773, 775, 776, 777, 780,785, 787, 900, 910, 912, 924, 925, 929, 930, 931, 932, 960, 961, 962, 963, 964 (?)." (see "Zentrale und lokale MARC 21-Felder im hbz")

with `830` we have something that*s not in the list.

**Comment by TobiasNx** [comment]
Took this up again and solved it. Unfortunately we can't work with makros here since they are not allowed in if-conditionals also if-conditionals are not allowed in makros.

**Comment by dr0i** [comment]
Deployed, see e.g. https://alma.lobid.org/resources/search?q=990181275760206441&format=json.
Closed.
