### ISSUE TITLE
Missing hbz01 resources

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1227]
Reported by Edoweb customers, see https://jira.hbz-nrw.de/browse/EDOZWO-1059:

> Katalogisiert am 19.04.
> HT020901818: Wir geht nur gemeinsam
> HT020901400: EFi- Praxishandbuch
> HT020901566: Junge Menschen mit Fluchtgeschichte
> HT020901723: Möglichkeiten der Gestaltung migrationsbedingter Vielfalt
>
> Katalogisiert am 21.04.
> HT020904022: Migration und Kinderschutz
> HT020903759: Stand und Entwicklung der Integrationshilfen 

The resources are in hbz01, see e.g. [HT020901818](http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DHT020901818) or [HT020901400](http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DHT020901400).

**Comment by dr0i** [comment]
There was a classical race condition:
as of the Alma Migration at the weekend, there was a bigger incremental update (3GB) at Sunday 25th of April with a timestamp of Apr 26 04:47. The ETL of incremental updates was triggered as usual at 04:15, i.e. half an hour earlier. This resulted in missing that update at whole.
Just going to reindex it manually. Note that it would have "healed itself" (by reindexing everything) next Thursday.

**Comment by dr0i** [comment]
Updated manually, seems to work:
http://lobid.org/resources/HT020901818
http://lobid.org/resources/
http://lobid.org/resources/

**Comment by dr0i** [comment]
Ping @inkuss.

**Comment by inkuss** [comment]
Danke, funktioniert wieder.

**Comment by acka47** [comment]
Closing
