### ISSUE TITLE
Update test data and check for changes and possible new issues

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1228]
The Marc records changed therefore we need to update our test data.
With updating we need to check if our ETL is still working properly.

**Comment by TobiasNx** [comment]
Missing:
- 99368090810506441
- 99368090810506441/
- 990193229450206441/ HT017411546

-Some callNumbers and current locations
-some local keywords from UBD

**Comment by dr0i** [comment]
Updated the test resources. Please have a look @TobiasNx .
