### ISSUE TITLE
Wrong type for testfile HT015082724

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#123]
Originally reported at https://github.com/lobid/lodmill/issues/273:

> The resource is typed as `bibo:Book` and `bibo:Collection` although `bibo:Issue` would be the correct class.

**Comment by acka47** [comment]
The record is about issue 119 from 2006 of the journal 	Tijdschrift voor geschiedenis. Thus, `bibo:Issue` would indeed be the correct type. As far as I can see, until now we don't have any mapping to `bibo:Issue` at all as the  [morph file](https://github.com/hbz/lobid-resources/blob/6bc5bc49865189af55d77280edb45dd336a026b7/src/main/resources/morph-hbz01-to-lobid.xml) doesn't mention it.

The source looks like this (snippet):

```xml
<datafield tag="001" ind1="-" ind2="2">
  <subfield code="a">HT001373475</subfield>
</datafield>
<datafield tag="010" ind1="-" ind2="1">
  <subfield code="a">HT001373475</subfield>
</datafield>
<controlfield tag="050">a|||||||||||||</controlfield>
```

We only have a medium information (print) in `050`, it doesn't say anywhere in the MAB of what type the resource is. Actually, it seems that there is no possibility in MAB to say that something is a journal issue. Thus, the type information can only be concluded from the fact that this is a sub-resource of Journal (HT001373475). I don't know whether we should go this way. We should first inspect some similar issues and/or talk to a cataloger.

**Comment by ChristophEwertowski** [comment]
Another way would be ```596``` (BANDZAEHLUNG, JAHRESZAEHLUNG, HEFTZAEHLUNG, UMFANGS-
 UND ILLUSTRATIONSANGABE DER QUELLE). If a resource has got ```596a``` (zusaetzlich mit Band- und/oder Heftbezeichnung) and no ```596b``` (zusaetzlich mit Tagesdatum bei Zeitungen), it is an issue.

As for the type I can't help. The field ```025``` with the zdb-id has got the right indicator so it shouldn't be a book.

**Comment by ChristophEwertowski** [comment]
Will be resolved in https://github.com/hbz/lobid-resources/pull/700.

**Comment by ChristophEwertowski** [comment]
Deployed to test, see [TT002881480 (test, json)](http://test.lobid.org/resources/TT002881480.json). At the moment many resources typed as `PublicationIssue` aren't part of a journal or even a series ([query](http://lobid.org/resources/search?t=PublicationIssue)). Many are song books or learning material. I expanded the definition so that the resources not only have to be a "Heft" but also have a superordinated resource which is part of the ZDB.
(I don't know why I didn't take the example from the headline. Works also for that resource.)

**Comment by ChristophEwertowski** [comment]
Assigning myself as on test resources are typed as `PublicationIssue`s which don't have MAB 025z2.a.

**Comment by ChristophEwertowski** [comment]
@droi and myself: The `combine` element doesn't work.
```
<combine name="@rdftype" value="${a}">
   <data source="025z2.a"/>
   <data source="089|090-1.a" name="a">
      <regexp match="Heft" format="http://schema.org/PublicationIssue"/>
   </data>
</combine>
```
[HT009706034 (test)](http://test.lobid.org/resources/HT009706034) is typed as a `PublicationIssue` although it doesn't have the MAB field 025z2.a. I already tried flushing and using the `<if>` element. It would be good to have a look at it tomorrow.

**Comment by ChristophEwertowski** [comment]
`PublicationIssue` was defined two times. Now only resources which have a superordinated resource which is in the ZDB is defined as a `PublicationIssue`: [TT002881480 (test, json)](http://test.lobid.org/resources/TT002881480.json).
[HT009706034 (test, json)](http://test.lobid.org/resources/HT009706034.json) is an example which was formerly typed as a `PublicationIssue` but isn't anymore as it doesn't have MAB 025z2. The same should be true for song books, many educational resources (for example "Schülermaterialheft") and other works which aren't part of a periodical.

**Comment by acka47** [comment]
+1 (Maybe we can type the other resources that don't have a ZDB resource as superordinated resource as http://schema.org/PublicationVolume? If you think it makes sense, please open an issue for this, @ChristophEwertowski .

**Comment by dr0i** [comment]
From #784:

> Deployed to staging. This does not what it was supposed to do, see e.g. http://stage.lobid.org/resources/HT015082724.json which is still typed as Book. Reassigning @ChristophEwertowski to have a look.

**Comment by ChristophEwertowski** [comment]
@acka47 : I updated the regular expression so that all resources which have a superordinated resource which is in the ZDB are typed `PublicationIssue`. See [HT015082724 (test, json)](http://test.lobid.org/resources/HT015082724.json).

**Comment by ChristophEwertowski** [comment]
All resources in test which are both `PublicationIssue`s and `Book`s are either issues bound together or part of a `Series`. Both fit the [description of schema.org](http://schema.org/PublicationIssue):
> A part of a successively published publication such as a periodical or publication volume, often numbered, usually containing a grouping of works such as articles.

**Comment by acka47** [comment]
+1
