### ISSUE TITLE
Deduplicate subjectAltLabels

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1232]
https://github.com/hbz/lobid-resources/commit/a3e091162cd179113209a78680179cc9a5e6c340#r50172856

subjectAltLabels have a lot of duplicates:
e.g.: HT000312236
`"subjectAltLabel" : [ "Physik", "Physik", "Physikdidaktik", "Periodikum", "Zeitschriften", "Physik", "Physik", "Physikdidaktik", "Physik", "Physik", "Physikdidaktik" ]`

**Comment by dr0i** [comment]
See https://alma.lobid.org/resources/search?q=HT000312236%20AND%20subjectAltLabel:*&format=json. Closed.
