### ISSUE TITLE
wrong values in `hasVersion` and `related`

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1242]
e.g. HT000161712

```JSON
  "hasVersion" : [ {
    "id" : "http://digitale-objekte.hbz-nrw.de/storage2/2019/04/06/file_4/8295425.pdf"
  } ],
  "related" : [ {
    "id" : "Inhaltsverzeichnis"
  } ],
```

**Comment by TobiasNx** [comment]
as discussed off-board woth @dr0i : I split this issue in two steps:
1) I will out-comment `hasVersion` and `related`-transformation. So that I can work on #1237 since they encompass tableOfContent information.
2) After solving #1237 I will rearrange `hasVersion` and `related`

**Comment by dr0i** [comment]
Deployed, see e.g. See e.g. https://alma.lobid.org/resources/search?q=HT000161712&format=json. Closed.

**Comment by TobiasNx** [comment]
Reopen for remodelling `"hasVersion"` and `"related"`

**Comment by TobiasNx** [comment]
@acka47 

I am irritated by the definition of "hasVersion" as lobid is using it: https://github.com/hbz/lobid-resources/pull/453/commits/e26a3189d3c516b99399e4d8c4394e7da690b302

> hasVersion contains andything from 655, subfields x or 3 if not a description, fulltext or tableOfContents. Improve definition of fulltextOnline by adding and deleting.

655 is only refering to electronic links in the metadata.

In contrast https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/hasVersion gives a much broader definition:

> 
>Definition | A related resource that is a version, edition, or adaptation of the described resource.
>-- | --
>Comment | Changes in version imply substantive changes in content rather  than differences in format. This property is intended to be used with  non-literal values. This property is an inverse property of Is Version  Of.

I think this does not fit conceptually. Do we need this very narrow link list at all? Or should we even remodel the hasVersion?

**Comment by acka47** [comment]
The issue where the current status regarding `seeAlso`, `hasVersion` and `fulltextOnline` have been discussed is #441. Maybe this helps for your understanding, @TobiasNx ?

**Comment by TobiasNx** [comment]
The values in 856## $3 which used to be 655 $3 and specifiy the content of the link are:

> 655 #  L 3 Abstract
655 #  L 3 Ausführliche Beschreibung
655 #  L 3 Auszug
655 #  L 3 Autorenbiografie
655 #  L 3 Autorenkommentar
655 #  L 3 Begleitmaterial
655 #  L 3 Beschreibung für Bibliotheken
655 #  L 3 Beschreibung für Buchhändler
655 #  L 3 Beschreibung für die Lizenzabteilung
655 #  L 3 Beschreibung für Lehrer/Erzieher
655 #  L 3 Beschreibung für Lesegruppen
655 #  L 3 Beschreibung für Leser
655 #  L 3 Beschreibung für Marketing
655 #  L 3 Cover
655 #  L 3 Einführung/Vorwort
655 #  L 3 Errata
655 #  L 3 Erstes Kapitel
655 #  L 3 Fragen für Lesegruppen
655 #  L 3 Illustration
655 #  L 3 Inhaltstext
655 #  L 3 Inhaltsverzeichnis
655 #  L 3 Kapitel
655 #  L 3 Klappentext
655 #  L 3 Konkurrierende Titel
655 #  L 3 Kurzbeschreibung
655 #  L 3 Literaturverzeichnis
655 #  L 3 Pressetext
655 #  L 3 Register
655 #  L 3 Rezension
655 #  L 3 Rezension (Auszug)
655 #  L 3 Titelblatt
655 #  L 3 Umschlagtext
655 #  L 3 Unveröffentlichter Kommentar
655 #  L 3 Volltext
655 #  L 3 Werbliche Überschrift
655 #  L 3 Zitat aus einer vorhergehenden Besprechung
655 #  L 3 Zusätzliche Angaben

None of those has a specific refrence to versions of the publication. As discussed with @acka47 off-board I will leave out hasVersion for now.

**Comment by dr0i** [comment]
Reopened for I am unsure if it is completely solved [re](https://github.com/hbz/lobid-resources/issues/1242#issuecomment-833305273):

> As discussed with @acka47 off-board I will leave out hasVersion for now.

while the title demands the fix of "hasVersion".

**Comment by TobiasNx** [comment]
> Reopened for I am unsure if it is completely solved [re](https://github.com/hbz/lobid-resources/issues/1242#issuecomment-833305273):
> 
> > As discussed with @acka47 off-board I will leave out hasVersion for now.
> 
> while the title demands the fix of "hasVersion".

yes the ticket can be closed, while working on this ticket we decided to drop "hasVersion" for now.
