### ISSUE TITLE
110 & 710 are missing GND-identifier-fields

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1246]

**Comment by TobiasNx** [comment]
While the GND as`"id"` is created, the field gndIdentifier is not created for 110 an 710. But there seems to be a macro for that we could use.

**Comment by TobiasNx** [comment]
https://github.com/hbz/lobid-resources/blob/2d136786157b1a3f4b6837f980a4a5b33d9cc576/src/main/resources/alma/common/contribution.xml#L17

https://github.com/hbz/lobid-resources/blob/2d136786157b1a3f4b6837f980a4a5b33d9cc576/src/main/resources/alma/common/contribution.xml#L85-L121

**Comment by dr0i** [comment]
Merged but not deployed yet. Will be deployed at Monday.

**Comment by dr0i** [comment]
Deployed, see e.g. http://alma.lobid.org/resources/search?q=HT017411546&format=json .
Note, though, that you cannot query `contribution.agent.gndIdentifier`: http://alma.lobid.org/resources/search?q=contribution.agent.gndIdentifier:*&format=json
