### ISSUE TITLE
Add EtikettMaker to Alma ETL

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1257]
Add the EtikettMaker to Alma's ETL workflow and see what happens.
Might resolve (or help to resolve) #1248 in conjunction with its PR (##1255).

**Comment by TobiasNx** [comment]
When I locally test run etiketts are not added https://github.com/hbz/lobid-resources/commit/ed34b40c4db773b70c053ff9b7702cf4afa1873b

Also somehow it seems, that the testdata changed, since the order changed and the new data was introduced.

**Comment by dr0i** [comment]
Problem was fixed, "mvn clean install" was missing. Closing.
