### ISSUE TITLE
Different sequence in hasItem

### ISSUE THREAD

**Issue by UBmakla** [hbz/lobid-resources#1261]
Is it possible to keep the same sequence in hasItem? In general currentLocation is under heldBy, but sometimes above, e.g. 990054016950206441. This is a problem for our work with Metafacture. thx

**Comment by dr0i** [comment]
Hm, no this cannot be guaranteed. JSON is agnostic to the sequence of fields. From [rfc 7159](https://datatracker.ietf.org/doc/html/rfc7159):
>    An object is an unordered collection of zero or more name/value pairs,

If you could provide an example and morph we may help to figure out how to make it work. We could also use a [sandbox](https://github.com/hagbeck/metafacture-sandbox/) for this, if you like.

**Comment by UBmakla** [comment]
Hm, thx, I try another way in Metafacture. Otherwise I call again ;-). But first a week holiday :-)

**Comment by dr0i** [comment]
Good holiday then :)
I just stumbled upon a documentation of a new metafacture feature (since 5.2.0 ) ["restrict-firing-to-only-when-the-collector-iscomplete"](https://github.com/metafacture/metafacture-core/wiki/Metamorph-Cookbook#restrict-firing-to-only-when-the-collector-iscomplete), maybe this helps you fixing the morph.

**Comment by TobiasNx** [comment]
Another idea would be to use flushWith at the entity level: `flushWith="hasItem[].*` (something like that?) @blackwinter gave me the hint, that it is possible to flush at entity level. I did not know that before.

**Comment by UBmakla** [comment]
Relaxing vacation helps ;-). I find another way for the problem. But the flushWith idea may be helpfull for another problem, thx!

**Comment by dr0i** [comment]
Good to hear :)
Closing this issue.
