### ISSUE TITLE
Add format subject from 689 to natureOfContent

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1268]
@hagbeck wished to add the format subjects from the Schlagwortfolgen `"689"` those have 

These have type specifications in subfield A and not in subfield D.

e.g.:

```
  <datafield tag="689" ind1="0" ind2="2">
    <subfield code="a">Online-Ressource</subfield>
    <subfield code="A">f</subfield>
  </datafield>
  <datafield tag="689" ind1="0" ind2="3">
    <subfield code="a">Zeitschrift</subfield>
    <subfield code="A">f</subfield>
  </datafield>
```

Subfield "A" refers to values-list:
f - Formschlagwort

**Comment by dr0i** [comment]
Merged, will be deployed after weekend.

**Comment by dr0i** [comment]
Note that the field can occur multiple times but should be unique. Opened issue #1271 for that.
