### ISSUE TITLE
Problems with label for corporate body as contributor and subfield "e"

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#128]
Reported by @fsteeg in https://github.com/hbz/nwbib/pull/355#issuecomment-264499102:

> the two contributors have the same label. This seems to be an error in the Lobid data 2.0 conversion. Compare `200` and `204` in http://lobid.org/hbz01/HT019093814 and `contributor` in http://lobid.org/resources/HT019093814.

[Source](http://lobid.org/hbz01/HT019093814) snippet:

```xml
<datafield tag="200" ind1="b" ind2="1">
  <subfield code="k">Kultur Ruhr GmbH</subfield>
  <subfield code="9">(DE-588)7741856-6</subfield>
</datafield>
<datafield tag="204" ind1="b" ind2="1">
  <subfield code="e">Ruhrtriennale</subfield>
  <subfield code="9">(DE-588)5555595-0</subfield>
</datafield>
```

Usually, there are no problems with labels of double contributors, see e.g. http://lobid.org/resources/HT006947678. The problem here obviously is the label being recorded in subfield `e`. I guess we should probably just pull subfield `e` into the label field as we do with subfield `k`.

**Comment by acka47** [comment]
I don't get the [relevant parts of the morph](https://github.com/hbz/lobid-resources/blob/785bdf8f5ea74b1482e97b01800c2104c7d5373e/src/main/resources/morph-hbz01-to-lobid.xml#L1005-L1036). We might have to add another variable `@nameOfContributingCorporateBodyE`. Assigning @dr0i .

**Comment by dr0i** [comment]
Deployed to staging and production, @acka47 please have a look.

**Comment by acka47** [comment]
+1. Closing.
