### ISSUE TITLE
Add default codes for contributors without marcRel codes

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1282]
e.g. 99370756332806441

```
  <datafield tag="100" ind1="1" ind2=" ">
    <subfield code="a">Osha, Sanya.</subfield>
  </datafield>
...
  <datafield tag="710" ind1="2" ind2=" ">
    <subfield code="a">African Books Collective.</subfield>
  </datafield>
```

I would suggest 100 and 110 since they are the main contributor if type book or other textual publication then "aut" otherwise "cre".
For 700 and 710 "ctb" (contribution) since they are additional contributors.

We have ~300.000 records without contributor roles.

**Comment by TobiasNx** [comment]
for creators that are 100 or 110 (Main Entry-Personal Name)

                "BibliographicResource",
                "ArchivalResource",
                "ArchivedWebPage", -> cre
                "Book", -> aut
                "Collection", -> aut
                "Periodical", -> edt or cre
                "Series", -> edt or cre
                "Newspaper", -> edt or cre
                "Journal", -> edt or cre
                "MultiVolumeBook", -> aut
                "PublicationIssue", -> edt or cre
                "Article", -> aut
                "Miscellaneous", -> cre
                "Thesis", -> aut
                "EditedVolume", -> edt or cre
                "Proceedings", -> cre
                "Festschrift", -> edt or cre (why german?)
                "Bibliography", -> cre
                "OfficialPublication", -> aut
                "ReferenceSource", ?
                "Statistics", -> cre
                "Legislation", -> cre
                "PublishedScore", -> cre
                "Schoolbook", -> aut
                "Game", -> cre
                "Biography", -> aut 
                "Report", -> aut
                "Image", -> cre
                "Map", -> cre
                "Standard", -> cre
                "SubjectHeading" -> cre (why subjectHeading?)

default for: 700/710 ( Added Entry-Personal Name) always ctb (Contributor).

**Comment by TobiasNx** [comment]
This list should also be used for ALEPH #1248

**Comment by acka47** [comment]
Looks good two things have to be changed:

- [`Collection` in lobid](http://lobid.org/resources/search?q=type:Collection) refers to collections of bibliographic data (NWBib, ZDB). Thus, we should use `cre` there.
- `Proceedings` should also use `cre` or `edt`
- 
Regarding "Festschrift", the German term is actually used in English as well, see https://en.wikipedia.org/wiki/Festschrift.

**Comment by acka47** [comment]
> 700/710 ( Added Entry-Personal Name) always ctb (Contributor).

I am not sure about this but my MARC21 knowledge is too small to assess this. If you are sure about this, @TobiasNx, I am ok with it.

**Comment by TobiasNx** [comment]
@acka47: a first version is included in the ALMA-Fix Transformation:

https://github.com/hbz/lobid-resources/blob/a438beafa5b2e42c657e22f8e4c40ed729cb70e5/src/main/resources/alma/fix/contribution.fix#L179-L187

Could you have a look if that is okay for you?

**Comment by acka47** [comment]
+1 Looks good for me. We'll also be able to tweak it later when users notice strange roles.

**Comment by TobiasNx** [comment]
ALMA-FIX add default roles.
