### ISSUE TITLE
Change "lv:almaIdMMS" to "lv:almaMmsId"

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1289]
Originates in https://github.com/hbz/lobid-vocabs/pull/134.

We have to adjust the morph and also the code.

**Comment by dr0i** [comment]
Don't forget, from https://github.com/hbz/lobid-vocabs/pull/134#issuecomment-849572082:

> ... Please just let us know which name you choose and from when the change is active.

**Comment by dr0i** [comment]
This is ETLed atm and should be ready in an hour or so - @TobiasNx  should get an email when this is ready.
This new index should not be made productive, i.e., the alias should have the `-staging` suffix.
It can be tested at http://test.alma.lobid.org. 
The index `almaresources-20210607-1507` should be still the productive one.

**Comment by TobiasNx** [comment]
http://test.alma.lobid.org/resources/search?q=990181275760206441&format=json seems to work

**Comment by TobiasNx** [comment]
@UBmakla and @hagbeck we would change the the `AlmaIdMMS` to `almaMmsId` then. Is that okay with you?

**Comment by hagbeck** [comment]
Yes, it is. We're currently able to work with both.

**Comment by dr0i** [comment]
Deployed. Closed.
