### ISSUE TITLE
Label with multiple entries (instead of just one)

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#129]
Reported by @fsteeg in https://github.com/hbz/nwbib/pull/355#issuecomment-264499102.

Snippet from http://lobid.org/resources/HT017324477:

```json
  "contributor" : [ {
    "altLabel" : "Westfälisches Heilpädagogisches Kinderheim",
    "id" : "http://d-nb.info/gnd/5183585-X",
    "label" : [ "Westfälisches Heilpädagogisches Kinderheim, Hamm (Westf)", "Westfälisches Heilpädagogisches Kinderheim (Hamm (Westf))" ],
    "type" : [ "CorporateBody" ]
  } ]
```

[Source](http://lobid.org/hbz01/HT017324477) snippet:

```xml
<datafield tag="200" ind1="b" ind2="2">
  <subfield code="k">Westfälisches Heilpädagogisches Kinderheim</subfield>
  <subfield code="h">Hamm (Westf)</subfield>
  <subfield code="9">(DE-588)5183585-X</subfield>
</datafield>
<datafield tag="902" ind1="-" ind2="2">
  <subfield code="k">Westfälisches Heilpädagogisches Kinderheim</subfield>
  <subfield code="h">Hamm (Westf)</subfield>
  <subfield code="9">(DE-588)5183585-X</subfield>
</datafield>
```
The problem seems to be that the resource is both contributor and subject as problems do not occur in similar entries (see e.g. http://lobid.org/resources/HT012319980).  I guess, the label is created in a different way for contributors (with content from `h` in parentheses) and subjects (with content from `h` after comma). We should align these, using parentheses for both.

**Comment by dr0i** [comment]
Deployed to staging and production, @acka47 please have a look.

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
Closing.
