### ISSUE TITLE
lobidAlma doesn´t work

### ISSUE THREAD

**Issue by UBmakla** [hbz/lobid-resources#1302]
"Not found" e.g. for http://alma.lobid.org/resources/990369982720206441.json 
thx

**Comment by dr0i** [comment]
Uh - sorry! That was a silly misconfiguration that prevented the testing ... Should work now.

**Comment by UBmakla** [comment]
perfect, works, thx!

**Comment by dr0i** [comment]
Also added to monit-config to test if alma.lobid.org/resources/search?q= yields the field `almaMmsId` (instead of `hbzId`). So we will shall be warned next time that crucial field is missing.
