### ISSUE TITLE
Alma: non-official collections are missing

### ISSUE THREAD

**Issue by hagbeck** [hbz/lobid-resources#1305]
s.a. #1052 for the same problem in Aleph version

The relevant value in the Alma record 990213367870206441 comes from the MARC field `962 e`. 
I knew that collections could be in 912 and 960. And now obviously in 962, too.

**Comment by TobiasNx** [comment]
@hagbeck can you have a look at the PR.

**Comment by TobiasNx** [comment]
@hagbeck wrote:
"Die Testausgabe passt auf jeden Fall so. Labels wären natürlich aus Open Data-Sicht schön, aber wir benötigen "nur" die ID, damit wir die im Index als Anker zum Aufruf der Collection-Inhalte nutzen können.

Für diese "Nicht-ZDB-Sigel-Kollektionen" müsste es doch eigentlich im Verbund eine Dokumention geben, die auch ordentliche Label oder Bezeichnungen enthält. Fraglich ist natürlich, ob die auch Maschinen lesen können. Also das übliche Problem

Viele Grüße
Hans-Georg"

=> so he can work with the data
=> labels would be a cherry on the top. there should be some dokumentation about labels.

**Comment by dr0i** [comment]
Was closed unintentionally by closing PR #1306. Reopening.
Will be automatically deployed at Sunday.

**Comment by dr0i** [comment]
> Will be automatically deployed at Sunday.

Nope. Note to self: look at https://github.com/hbz/lobid-resources/wiki/Maintaining-Alma.lobid-API#deploy.
I had deployed aleph-lobid, not alma-lobid.

**Comment by dr0i** [comment]
Deployed to production, see e.g. http://alma.lobid.org/resources/search?q=HT000161712&format=json.
Closing.
