### ISSUE TITLE
Add ORCID

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1307]
@UBmakla asks for ORCID integration.

In GND exists sometimes a sameAs to ORCID, e.g. https://lobid.org/gnd/121546985 .

These ORCIDs exists also in Alma, see e.g. in https://indexes.devel.digibib.net/export/990181637940206441 (accessible only in hbz internal network):
```
<datafield tag="GSI" ind1="7" ind2=" ">
<subfield code="a">0000-0003-3071-9772</subfield>
<subfield code="2">orcid</subfield>
<subfield code="A">GND</subfield>
<subfield code="B">GND-121546985</subfield>
<subfield code="C">024</subfield>
</datafield>
```

If it would be integrated it would appear in https://alma.lobid.org/resources/search?q=121546985&format=json .

**Comment by TobiasNx** [comment]
Okay, that seems to be tricky since the author information resides in 100/110 and 700/710. In there is a GND refrence to the GSI element, which also exist twice:

```
<datafield tag="700" ind1="1" ind2=" ">
<subfield code="a">Tinnemann, Peter</subfield>
<subfield code="d">1967-</subfield>
<subfield code="0">(DE-588)121546985</subfield>
<subfield code="4">oth</subfield>
<subfield code="0">
(uri) https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=idn=121546985
</subfield>
<subfield code="0">(uri) http://viaf.org/viaf/sourceID/DNB|121546985</subfield>
<subfield code="B">GND-121546985</subfield>
</datafield>
...
<datafield tag="GSI" ind1="7" ind2=" ">
<subfield code="a">121546985</subfield>
<subfield code="0">http://d-nb.info/gnd/121546985</subfield>
<subfield code="2">gnd</subfield>
<subfield code="A">GND</subfield>
<subfield code="B">GND-121546985</subfield>
<subfield code="C">024</subfield>
</datafield>
<datafield tag="GSI" ind1="7" ind2=" ">
<subfield code="a">0000-0003-3071-9772</subfield>
<subfield code="2">orcid</subfield>
<subfield code="A">GND</subfield>
<subfield code="B">GND-121546985</subfield>
<subfield code="C">024</subfield>
</datafield>
</record>
```

**Comment by dr0i** [comment]
AFAIK we use `sameAs` only at top level. So it may be easier for both, producer (us!) and consumer to enrich agents by simply adding `orcid` like this:

    agent : { 
      label : Cartter, Allan Murray,
      type : [ Person ],
      gndIdentifier : 127022538,
      orcid: $theOrcid,
      id : https://d-nb.info/gnd/127022538
    },

(btw.: isn't it a shame that that is not done already in Alma's MarcXml? Also, prefixing a GND-ID sometimes with `(DE-588)` and sometimes with `GND-` seems also to be more creative than necessary)

**Comment by dr0i** [comment]
With stream-based morph cannot merge two entities `A` and `B` if the one who should be merged (`B`)  comes _after_ the "main" entity (`A`)_and_ if there can be more _main_ entities having the same field names (the `flushWith="$entityName"` cannot work then properly). Unfortunately both is the case here, so https://github.com/metafacture/metafacture-core/wiki/Metamorph-Cookbook#restrict-firing-to-only-when-the-collector-iscomplete doesn't help.

With morph we could try to :
a) preprocess the incoming sources ensuring `B` always comes ahead of `A`
b) build  a lookup table (or use lobid-gnd as lookup index) to be used in the morph
c) build a lookup database and merge that in postprocessing

We do c) for geo enrichment in NWBib (see `WikidataGeodata2Es.java` and `ElasticsearchIndexer.java`) and could build on that. The idea I had in mind back then was to have an "enrichment" database (which could be build and updated independently of the ETL of the catalog's data to encompass also data which is not part of the catalog's data) and then be merged into the json coming out of the metafcature's pipeline and index this enriched json.
The con of that is to have a handtailored java class for enrichment of json (see "enrich" in `ElasticsearchIndexer.java`).
Maybe worthwhile looking at https://github.com/jprante/elasticsearch-analysis-reference where we could do this enrichment by using Elasticsearch (also the plugin seems to not enrich the output of the data  (`_source`) but just references for making queries working. Also it may break if another Elasticsearch version is used. )

**Comment by acka47** [comment]
We had a meeting today where we – amongst other use cases – discussed this issue. See the pad athttps://etherpad.lobid.org/p/lobid-datenanreicherung

**Comment by TobiasNx** [comment]
This might be solvable with ALMA-Fix.

**Comment by dr0i** [comment]
Assigning @TobiasNx . Was reminded of this because of the [GND enrichment](https://github.com/hbz/lobid-resources/pull/1536). We could go on here?

**Comment by dr0i** [comment]
Some orcids are now in the data, e.g. https://test.lobid.org/resources/990109506170206441.json.
Some are missing because of an FIX error.
