### ISSUE TITLE
Labels for Collections e.g. ZDB and those from 912?

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1312]
At the moment we just list "eResource package"" as label for ZDB-Collections.
https://github.com/hbz/lobid-resources/blob/2ae7b86259115ee3fa8693e3ba16ebda2739ca54/src/main/resources/alma/fix/relatedRessourcesAndLinks.fix#L391-L401

We could use the labels from here: https://service-wiki.hbz-nrw.de/display/VDBE/Produktsigel+und+interne+Selektionskennzeichen

And we have no labels for 
https://github.com/hbz/lobid-resources/blob/2ae7b86259115ee3fa8693e3ba16ebda2739ca54/src/main/resources/alma/fix/relatedRessourcesAndLinks.fix#L404-L417

Do we need the labels for every collection?

**Comment by acka47** [comment]
Is this about the same collections as #1052? I had added labels for those in the labels.json, see https://github.com/hbz/lobid-resources/blob/2ae7b86259115ee3fa8693e3ba16ebda2739ca54/src/main/resources/labels/labels.json#L14494-L14910

Or is this about something else?

**Comment by TobiasNx** [comment]
I realized that the formating of the collection URL is wrong and needs to be fixed. Perhaps this will create better labels and then I should check again.

**Comment by TobiasNx** [comment]
> At the moment we just list "eResource package"" as label for ZDB-Collections.
> 
> https://github.com/hbz/lobid-resources/blob/2ae7b86259115ee3fa8693e3ba16ebda2739ca54/src/main/resources/alma/fix/relatedRessourcesAndLinks.fix#L391-L401
> 
> We could use the labels from here: https://service-wiki.hbz-nrw.de/display/VDBE/Produktsigel+und+interne+Selektionskennzeichen
> 
> And we have no labels for
> 
> https://github.com/hbz/lobid-resources/blob/2ae7b86259115ee3fa8693e3ba16ebda2739ca54/src/main/resources/alma/fix/relatedRessourcesAndLinks.fix#L404-L417
> 
> Do we need the labels for every collection?

This seem that there is an bug docu says element 912 und 962. Should be fixed if fixed.

**Comment by TobiasNx** [comment]
seems to be no bug. closing
