### ISSUE TITLE
Use same Alma-resources as test resources that are used in Aleph

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1313]
To compare and monitor progress of the Alma2lobid ETL it would be nice to easily compare the same test resources (i.e. resource with the same hbz ID) coming from Aleph and Alma.

**Comment by TobiasNx** [comment]
I added the Aleph-Testfiles in the branch https://github.com/hbz/lobid-resources/tree/1313-copyAlephTestfilesToAlma

Then I compared the ALMA and Aleph-Transforamtion-Results of the test:

ALMA is missing:

- [ ] contribution[].*.agent.altLabel[].*
- [ ] hasItem[].*.note[].*
- [ ] contribution[].*.agent.dateOfBirth
- [ ] spatial[].*.focus.type[].*
- [ ] isPartOf[].*.type[].*
- [ ] contribution[].*.agent.dateOfDeath
- [ ] fulltextOnline[].*.id
- [ ] fulltextOnline[].*.label
- [ ] contribution[].*.agent.altLabel
- [ ] subject[].*.componentList[].*.altLabel[].*
- [ ] spatial[].*.id
- [ ] spatial[].*.label
- [ ] spatial[].*.source.id
- [ ] spatial[].*.source.label
- [ ] spatial[].*.type[].*
- [ ] spatial[].*.notation
- [ ] coverage[].*
- [ ] spatial[].*.focus.id
- [ ] hasVersion[].*.id
- [ ] hasVersion[].*.label
- [ ] similar[].*.id
- [ ] similar[].*.label
- [ ] spatial[].*.focus.geo.lat
- [ ] spatial[].*.focus.geo.lon
- [ ] bibliographicCitation
- [ ] spatial[].*.focus.label
- [ ] containedIn[].*.id
- [ ] containedIn[].*.label
- [ ] urn[].*
- [ ] exampleOfWork.label
- [ ] exampleOfWork.type[].*
- [ ] publication[].*.note[].*
- [ ] publication[].*.publishedBy[].*
- [ ] subject[].*.componentList[].*.dateOfBirth
- [ ] contribution[].*.agent.source.id
- [ ] contribution[].*.agent.source.label
- [ ] containsExampleOfWork[].*.label
- [ ] containsExampleOfWork[].*.type[].*
- [ ] oclcNumber[].*
- [ ] subject[].*.componentList[].*.dateOfDeath
- [ ] containsExampleOfWork[].*.creatorOfWork
- [ ] containsExampleOfWork[].*.id
- [ ] publication[].*.frequency[].*.id
- [ ] publication[].*.frequency[].*.label
- [ ] publication[].*.location[].*
- [ ] supplement[].*.id
- [ ] supplement[].*.label
- [ ] description[].*.id
- [ ] description[].*.label
- [ ] predecessor[].*.label
- [ ] publication[].*.description[].*
- [ ] successor[].*.label
- [ ] contribution[].*.agent.label[].*
- [ ] primaryForm[].*.id
- [ ] primaryForm[].*.label
- [ ] containsExampleOfWork[].*.instrumentation[].*
- [ ] contribution[].*.agent.dateOfBirthAndDeath
- [ ] corporateBodyForTitle[].*
- [ ] exampleOfWork.creatorOfWork
- [ ] seeAlso[].*.id
- [ ] seeAlso[].*.label
- [ ] successor[].*.id
- [ ] titleKeyword[].*
- [ ] predecessor[].*.id
- [ ] webPageArchived[].*.id
- [ ] webPageArchived[].*.label
- [ ] exampleOfWork.id
- [ ] exampleOfWork.instrumentation[].*
- [ ] longitudeAndLatitude[].*
- [ ] related[].*.note[].*
- [ ] shortTitle[].*
- [ ] containsExampleOfWork[].*.musicalKey
- [ ] containsExampleOfWork[].*.workNumbering
- [ ] license[].*.id
- [ ] license[].*.label
- [ ] license[].*.note[].*
- [ ] similar[].*.isbn[].*
- [ ] similar[].*.note[].*
- [ ] subject[].*.componentList[].*.altLabel
- [ ] subject[].*.componentList[].*.dateOfBirthAndDeath

ALEPH fehlen:

- [ ] contribution[].*.conferenceDate
- [ ] contribution[].*.conferenceIdentifier[].*
- [ ] contribution[].*.conferenceName
- [ ] contribution[].*.conferencePlace
- [ ] contribution[].*.corporateBodyNameNumber
- [ ] hasItem[].*.currentLocation
- [ ] hasItem[].*.electronicLocator
- [ ] hasItem[].*.sublocation
- [ ] isPartOf[].*.type
- [ ] oclcNumber
- [ ] related[].*.isbn[].*
- [ ] related[].*.issn
- [ ] related[].*.note
- [ ] subject[].*.source.version

**Comment by TobiasNx** [comment]
@acka47 which of those should we prioritize concerning nwbib?

**Comment by acka47** [comment]
I've added some exclamation marks for fields I think or am ceratin about that they are important for NWBib. Might have added some that aren't and missed others, though but it should give you some hints where to start, @TobiasNx .

**Comment by acka47** [comment]
There exists #1107 as overview ticket with the fields listed in https://github.com/hbz/lobid-resources/issues/1313#issuecomment-914107555.

**Comment by TobiasNx** [comment]
@dr0i could we discuss remodelling the testing for ALMA-FIX.

1) Get rid of ALMA-Morph testing or at least do not stop the dependency from ALMA-FIX testing to ALMA-Morph testing.
2) Introduce a lobid-ressources testing, that also loads the ALEPH-Lobid-Ressource Results for the HT numbers of the ALMA-FIX results?

**Comment by dr0i** [comment]
1) You mean introducing _two_ test files as basis for the tests instead of a shared one (the latter being `almaMarcXmlTestFiles.xml.tar.bz2`)?
2) You mean comparing the ALEPH json results with the ALMA Fix json results?

**Comment by TobiasNx** [comment]
1. Since we stop changing stuff with ALMA-Morph, either decouple ALMA-Morph and ALMA-Fix (your suggestion), or new testfiles are at first added to ALMA-FIX and if needed processed in ALMA-Morph. At the moment the script builds ALMA-Morph first and you have to run additionally ALMA-FIX.
2. Exactly, but only by adding the data of lobid-resources.

The script `test/alma/updateAlmaTestFiles.sh` could do something like:

1. Add new files to almaMarcXmlTestFiles.xml.tar.bz2 and execute them for ALMA-FIX. (Instead of ALMA-Morph)
2. Look for the element `hbzId` and `curl` from lobid-ressources the records of the ALEPH-Transformation. Name the record with the ALMAMMSid_aleph.json and the ALMAMMSid_aleph.xml

**Comment by dr0i** [comment]
1) copied `alma/updateAlmaTestFiles.sh` to `alma-fix/updateAlmaTestFiles.sh` and adapted the script so that you now can choose which test you want to update and execute
2) got to the directory `lobid-resources/src/test/resources/alma-fix/almaFilesFromIdsOfAlephTestFiles` and do `bash grepAlephTestIdsAndLookupAlmaJsonAndXml.sh`. The script gets the hbzId from the Aleph test files and lookups Alma Fix resources via API. Gets also the Alma sources. Writes those files into the directory.

**Comment by TobiasNx** [comment]
+1 You can now load the aleph files locally with the script. @dr0i would it be a good idea to put the content of the script folder to gitingore?

**Comment by TobiasNx** [comment]
> +1 You can now load the aleph files locally with the script. @dr0i would it be a good idea to put the content of the script folder to gitingore? so one does not track the changes?

https://github.com/hbz/lobid-resources/pull/1502

**Comment by dr0i** [comment]
Yes, you may add it to the .gitignore.

**Comment by dr0i** [comment]
I assigned this to you @TobiasNx as there are many unchecked items in the list in https://github.com/hbz/lobid-resources/issues/1313#issuecomment-914107555 and I don't know if here remain things to do.

**Comment by TobiasNx** [comment]
> I assigned this to you @TobiasNx as there are many unchecked items in the list in [#1313 (comment)](https://github.com/hbz/lobid-resources/issues/1313#issuecomment-914107555) and I don't know if here remain things to do.

This list is replaced by #1475  Ticket can be closed.
