### ISSUE TITLE
Articles not typed as such

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1314]
I compared [HT020925306 in lobid-Aleph](http://lobid.org/resources/HT020925306.json) with [HT020925306 in lobid-Alma](https://alma.lobid.org/resources/search?q=HT020925306&format=json) and noticed:

- in Alma this is not typed as `Article` (but it should be)
- `isPartOf` is used to link to the journal the article is contained in instead of `containedIn`

**Comment by acka47** [comment]
Related request by U.P. via NWBib mailing list on 2021-07-27:

> seit einiger Zeit arbeiten wir in Düsseldorf ja jetzt in Alma. Das hat 
> im NWBib-Portal für Aufsätze eine negative Änderung zur Folge:
> 
> Beispiel
> 
> https://nwbib.de/HT020998310 <https://nwbib.de/HT020998310>
> 
> Bei Publikationstyp wird jetzt anstelle von „Aufsatz“ leider nur noch 
> „Sonstige“ angezeigt.
> 
> Das liegt wohl daran, dass es in Alma keine Möglichkeit gibt, wie in 
> Aleph in Feld 051 zusätzlich zu Pos. 0 mit a für unselbst. Publ. noch 
> Pos.1 mit t für Aufsatz zu belegen. Unsere TA aus Alma weisen daher in 
> Aleph in Feld 051 nur eine Belegung für Pos. 0 auf. Das ist nicht sehr 
> schön. Ich habe auch nachgefragt. Frau Block hat aber im hbz-Wiki 
> zurückgemeldet, dass eine weitere Spezifizierung unselbständiger Werke 
> für Aufsätze in Alma nicht vorgesehen sei.
> 
> In der entsprechenden Alma-TA ist im LDR-Feld Pos. 7 mit a belegt für 
> „monogr. Komponententeil“, was Aufsatz entspricht.

So we probably will have to type a resource as `Article` when there is an `a` in the MARC leader position 7.

**Comment by acka47** [comment]
To Do: Read ensuing NWBib mailing list thread and post summary/actions here.

**Comment by TobiasNx** [comment]
Is an article only an article if it is part of an monograph, or also of a series book and an issue of an continues ressource?

**Comment by TobiasNx** [comment]
There seems to be one issue with "Monographic component part". While all articles in Books are "Monographic component part". Neither are all "Monographic component part" articles. They can be other types too, e.g. a map. How do we handle this.

Also still to be determined if Articles are only "Monographic component part" or also Journal Articles and how do we identify these?

**Comment by TobiasNx** [comment]
We now have Aufsatz (1124938) in ALMA-Fix, when mapping monographic component part. In contrast we have only Aufsatz (516130) in lobid ALEPH.

**Comment by TobiasNx** [comment]
Since we cannot differentiate between article and other monographic component parts it seems that the isPartOf-Relation is also messed up: https://alma.lobid.org/marcxml/990123613330206441

Also this makes it more difficult to select an article. This might be a faulty cataloguing issue but an Tonkassette is not an Article...

**Comment by TobiasNx** [comment]
https://github.com/hbz/lobid-resources/issues/703

@ChristophEwertowski added possible criteria a long time ago for MAB that could be added

> [HT013925945 (MAB)](http://lobid.org/hbz01/HT013925945): Article which isn't typed as such (missing t in MAB 051). We could use MAB 525 (Herkunftsangabe) and MAB 590-599 (Segment Herkunft (Quelle) unselbstständig erschienener Werke) for it.

We could add these conditionals
```
    elsif exists("77308")
      add_field("type[].$append","Article")
      replace_all("type[].*","Miscellaneous","")
    else
      do list(path: "500??", "var":"$i")
        if any_contain("$i.a","In:")
          add_field("type[].$append","Article")
          replace_all("type[].*","Miscellaneous","")
        end
      end
```

to the existing:

```
if any_match ("type[]", "Miscellaneous|Biography|Bibliography")
  unless any_match ("medium[].*.label", ".*(Audio|Video).*")
    if any_match("@leaderPos06-07",".a")
      add_field("type[].$append","Article")
      replace_all("type[].*","Miscellaneous","")
    end
  end
end
```

Tested these but they seem not to bring any changes at least with our testfiles

**Comment by TobiasNx** [comment]
http://lobid.org/resources/99370776442406441
Closing this ticket, since we improved the mapping for article even if we have no clear article statement as in ALEPH.
If we find another case for missing article mappings we could reopen this ticket.
