### ISSUE TITLE
Remove unnecessary JSON objects or add additional information

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#132]
There are some properties that have an array of one or more JSON objects with only the `id` field as information. One such property is `exemplar`. As many title have a lot of items connected (see e.g. http://lobid.org/resources/HT000786420#!) the already long array gets even more bloated by the object parentheses.

Properties where this is the case: 

- `exemplar`
- `fulltextOnline`
- `hasSupplement`
- `hasVersion`
- `isFormatOf`
- `isPartOf`
- `isPrimaryTopicOf`
- `language`
- `owner`
- `sameAs`
- `seeAlso`
- `similar`
- `source`
- `tableOfContents`
- `webPageArchived`
- `description`

There are two options for dealing with these:

1. Adding additional informato the object, e.g. `type` (for exemplars this would be `Item`) or `label` if available.
2. Removing the object and directly list the URIs in the array.

Add least for `language` we should add the labels. But I doubt that we could add useful information to all of these...

**Comment by fsteeg** [comment]
Another issue we should look into is universal usage of arrays. I don't think it makes sense to use arrays for everything (except `id` and `label`, which is our current plan). For instance here:

http://test.lobid.org/resources/HT018776640

The `agent` and `role` fields contain arrays, but that makes no sense at this point, since multiple contributions are in the `contribution` array, and each contribution has only a single agent and role. The arrays at this point make processing more cumbersome than required.

Our motivation for the always-array approach is to simplify processing of the data (e.g. to avoid checks in clients like 'if it's an array do this else that'). To achieve that, I think it would suffice to have arrays in all fields that multiple values actually occur. So if a field can have 1 or many values, it's always an array. If it never has multiple values in our data, it's a single non array value.

In our daily call today we decided to discuss this on Thursday, and see what @jschnasse thinks.

**Comment by acka47** [comment]
We discussed both topics today. With regard to the original issue (objects that only have the `id` field) we decided the following:

- Keep all objects
- Add labels to all objects, using the domain of the URL if no other label is used.

Regarding the question of arrays we decided to identify those properties that are intended to only hold one value and to remove the array from them. Here is a first list of possible candidates:

- `agent`
- `bibliographicCitation` :question: (morph](https://github.com/hbz/lobid-resources/blob/d920dc32d988bf16d846b318a111d66c5bdc88a9/src/main/resources/morph-hbz01-to-lobid.xml#L1618-L1627))
- `callNumber`
- `describedby`
- `description` :question: 
- `exemplarOf`
- `extent` ([morph](https://github.com/hbz/lobid-resources/blob/d920dc32d988bf16d846b318a111d66c5bdc88a9/src/main/resources/morph-hbz01-to-lobid.xml#L765))
- `hbzId`
- `isFormatOf` ([morph](https://github.com/hbz/lobid-resources/blob/d920dc32d988bf16d846b318a111d66c5bdc88a9/src/main/resources/morph-hbz01-to-lobid.xml#L186-L189))
- `isPrimaryTopicOf`([morph](https://github.com/hbz/lobid-resources/blob/d920dc32d988bf16d846b318a111d66c5bdc88a9/src/main/resources/morph-hbz01-to-lobid.xml#L213-L217))
- `issued` (We will have to fix https://github.com/lobid/lodmill/issues/730 and won't have multiple dates afterwards.)
- `isSupplementTo`
- `owner`
- `statementOfResponsibility` 
- `title`
- `zdbId`


Here are some that already are without array:
- `dateCreated`
- `dateModified`
- `dateOfBirth`
- `dateOfDeath`
- `numbering`

**Comment by dr0i** [comment]
Re "labels for every object": 
Now it is guaranteed to have a label as sidecar for every URI. If a URI's label isn't given via `labels.json` the fallback is: the domainname (and a possible first part of the path) will be extracted from the URI. This string is then itself re-lookuped in the labels. E.g.  `http://hub.culturegraph.org/resource/HBZ-HT013099804` would become `http://hub.culturegraph.org/resource/` which is configured in labels.json having the label `Culturegraph Ressource`.
Last fallback: If there is nothing found, the domainname itself will be the label.

**Comment by acka47** [comment]
I just noticed that we currently don't use `isSupplementTo`, see https://github.com/hbz/nwbib/issues/98#issuecomment-148733915. So we should add it to the data or remove the property from the context.

**Comment by fsteeg** [comment]
`agent` is now a single object, but `role` is still an array (`role` was missing in the list above).

See: http://lobid.org/resources/HT017158450

**Comment by acka47** [comment]
I left this out intentionally. While agent can only be one person, it would be ok to add two URIs for the same role, see https://github.com/hbz/lobid-resources/issues/139#issue-197196303. If we are sure that we won't do this in the future we could remove the array...

**Comment by dr0i** [comment]
https://github.com/hbz/lobid-resources/issues/139#issue-197196303 says:

> Two or more role statements within the same Contribution resource should occur only because you want to provide two different representations (e.g. two different URIs) for the same role.

I think we definitely don't want to begin with such redundancy. Why would we possibly ever would want this? Where to start and where to end :no_good:.

**Comment by ChristophEwertowski** [comment]
I concur with drOi. If the roles of the LoC would become deprecated, which doesn't seem likely, we would have to update the data. But since then I would stick with one URI for one role.

**Comment by fsteeg** [comment]
Another point, which we recently mentiond offline: we will have to check the item JSON and answer the same questions about objects and arrays.

See e.g.: http://alpha.lobid.org/items/HT019116616:DE-38:XK4375?format=json

I think none of the fields (callNumber, describedby, exemplarOf, id, owner, type) should be arrays, and we should keep the objects for describedby, exemplarOf, and owner.

(and btw, @dr0i: callNumber was a string last week, did you change that anywhere, on purpose?)

Also, for consistency, `describedby` (for /items and /resources) should probably be `describedBy` (as in exemplarOf). We should handle that in a separate issue though.

**Comment by acka47** [comment]
> I think none of the fields (callNumber, describedby, exemplarOf, id, owner, type) should be arrays, and we should keep the objects for describedby, exemplarOf, and owner.

+1 with the exception of `type`. This should remain an array because it is like this for the linked manifestations.

**Comment by fsteeg** [comment]
@dr0i Same thing as `callNumber` in items seems to have happened for `title` in resources: was string, now array, see: http://alpha.lobid.org/resources/HT015438076?format=json

**Comment by fsteeg** [comment]
@dr0i And `hbzId`. I guess everything turned into an array :-)

**Comment by fsteeg** [comment]
@dr0i Reviewing the list above, `hbzId` and `title` actually were arrays before. I was confused (was using an API 1.x response where they are strings, now using API 2 there). Pretty sure `callNumber` was a string on Friday though.

**Comment by dr0i** [comment]
I added the desired changes for `role` to the list at the top.
Re items: 
This is already fine now. All entries non-arrays, except for `type`, see http://alpha.lobid.org/items/HT019116616:DE-38:XK4375?format=json
