### ISSUE TITLE
Number of multipart monograph is missing in title

### ISSUE THREAD

**Issue by UBmakla** [hbz/lobid-resources#1320]
e.g. 99370782520706441, should be „BKI-Baukosten ... Neubau, Teil 2: Statistische Kostenkennwerte für Bauelemente“
e.g. 990101630530206441, should be „Materialien-Handbuch Geographie, 5“
Is possible to realize this? THX

**Comment by dr0i** [comment]
Hi @UBmakla !
The resource your mention is : http://alma.lobid.org/resources/search?q=HT020936481&format=json.
I take it you would want to have it analog to http://lobid.org/resources/HT020936481.json where the `title` is composed of `title` and `titleOfSubSeries` ?
The ALMA source:
```xml
<datafield tag="245" ind1="1" ind2="0">
<subfield code="a">BKI-Baukosten ... Neubau</subfield>
<subfield code="n">2021</subfield>
<subfield code="n">Teil 2</subfield>
<subfield code="p">Statistische Kostenkennwerte für Bauelemente</subfield>
<subfield code="c">BKI, Baukosteninformationszentrum (Hrsg.)</subfield>
</datafield>
```
We already parse `245_10_p` as `titleOfSubSeries` so we just would have to also parse `245_10_n` and and concat that to `title`.

Should we get rid of `titleOfSubSeries` at whole (it's missing in the Aleph MAB) or should we keep it?

**Comment by UBmakla** [comment]
Yes, that´s exactly what I mean.

**Comment by TobiasNx** [comment]
I do not know it this is not problematic from a library perspectiv.'

The title of a multivolume monograph stays the same and to include the changing volume names / years in the title would corrupt the title data.

**Comment by dr0i** [comment]
> The title of a multivolume monograph stays the same and to include the changing volume names / years in the title would corrupt the title data.

But this out of the scope of this issue since this is also in our lobid-resources (as mentioned here https://github.com/hbz/lobid-resources/issues/1320#issuecomment-989827626) and we agreed to use lobid-resources as master template for alma-lobid. We could, of course, open a new issue to tackle this?

**Comment by dr0i** [comment]
@TobiasNx made me aware of two issues which discuss this:
https://github.com/hbz/lobid-resources/issues/672
https://github.com/hbz/lobid-resources/issues/1215
Maybe this would be a good time for introducing such an API-break for we are building a new API (the alma-lobid-API)?
I invite also @acka47 to give 2 cents.
Most important may be the opinion of @UBmakla and @hagbeck for being the VIP users of alma.lobid .

In the meantime I propose: we _could_  deploy the changes of #1323 and _later_ change things based on our discussion here?

**Comment by acka47** [comment]
> we could deploy the changes of #1323 and later change things based on our discussion here?

+1 as far as I can see in http://alma.lobid.org/resources/search?q=HT020936481&format=json, the changes are already deployed.

**Comment by dr0i** [comment]
Yes, already deployed. Now merged into master. Closing.
