### ISSUE TITLE
Series without numbers are missing

### ISSUE THREAD

**Issue by UBmakla** [hbz/lobid-resources#1321]
e.g. 990223521400206441 missing series: „Programmierung/JavaScript“ and „Rheinwerk computing“
THX

**Comment by dr0i** [comment]
Mab Aleph: http://lobid.org/resources/HT020391499.json
Marc Alma:  http://alma.lobid.org/resources/search?q=HT020391499&format=json

You mean this is missing:
```json
"isPartOf": [

    {
        "type": [
            "IsPartOfRelation"
        ],
        "hasSuperordinate": [
            {
                "label": "Rheinwerk computing"
            }
        ]
    },
    {
        "type": [
            "IsPartOfRelation"
        ],
        "hasSuperordinate": [
            {
                "label": "Programmierung/JavaScript"
            }
        ]
    }
]
```

The relevant Alma Marc-XML looks like:
```xml
<datafield tag="490" ind1="0" ind2=" ">
<subfield code="a">Rheinwerk computing</subfield>
</datafield>
<datafield tag="490" ind1="0" ind2=" ">
<subfield code="a">Programmierung/JavaScript</subfield>
</datafield>
```

**Comment by dr0i** [comment]
Deployed to test , see e.g. http://test.alma.lobid.org/resources/search?q=HT019631849&format=json.

**Comment by UBmakla** [comment]
Great, thanks for the quick implementation!

**Comment by TobiasNx** [comment]
Do understand this issue right that not the missing volume number but the missing id of an series was the issue?

The example here linked here: https://github.com/hbz/lobid-resources/issues/1321#issuecomment-989910106 suggest that. It has a volume number but no id.

> Mab Aleph: http://lobid.org/resources/HT020391499.json Marc Alma: http://alma.lobid.org/resources/search?q=HT020391499&format=json
> 

In my opinion this seems to work now but in the example of @dr0i the volume number is missing.
See: http://test.alma.lobid.org/resources/search?q=HT020391499&format=json

**Comment by dr0i** [comment]
I haven't dug up in what you mean by "missing volume number". 
It was just that Aleph (http://lobid.org/resources/HT019631849.json) has `isPartOfRelation` while ALMA missed that formerly (http://alma.lobid.org/resources/search?q=990223521400206441&format=json).

**Comment by TobiasNx** [comment]
Aleph:

```
 "isPartOf": [
    {
      "type": [
        "IsPartOfRelation"
      ],
      "hasSuperordinate": [
        {
          "label": "Les indicateurs de l'éducation à la loupe"
        }
      ],
      "numbering": "no.67"
    }
  ]
```

I was referring to the numbering in your example. @UBmakla opened the issue as series without numbers. It is not the `numbering` but the missing `id` that was the reason that the `ìsPartOf`-Realtion has not been added.

In your example the `isPartOfRelation` is now added. But the `numbering` as subfield is missing.

ALMA:

```
     "isPartOf": [
        {
          "hasSuperordinate": [
            {
              "label": "Les indicateurs de l'éducation à la loupe"
            }
          ],
          "type": "IsPartOfRelation"
        }
      ],
```

**Comment by dr0i** [comment]
Thx for clarification!
Seems to be a new issue.
