### ISSUE TITLE
Alma: Missing ISSN

### ISSUE THREAD

**Issue by hagbeck** [hbz/lobid-resources#1331]
Hi,
I'm missing the ISSN 2471-5506 for the record 99371107766906441. The ISSN is in the MARC field 776 x. 
Please support this field for ISSN in lobid resources.

**Comment by dr0i** [comment]
We already take `776??x` into account, but as a `related.issn`, see e.g. http://alma.lobid.org/resources/search?q=990108873860206441&format=json.  We demand more fields than just the existence of `776??.x`, however. For the 990108873860206441 it's:

```
<datafield tag="776" ind1="0" ind2="8">
<subfield code="i">Druckausg.</subfield>
<subfield code="t">Behavioural pharmacology</subfield>
<subfield code="d">Hagerstown : Lippincott Williams & Wilkins, 1989-</subfield>
<subfield code="x">0955-8810</subfield>
<subfield code="w">(DE-605)HT004230139</subfield>
<subfield code="0">(uri) http://worldcat.org/issn/0955-8810</subfield>
</datafield>```

while your example just has:

```
<datafield tag="776" ind1=" " ind2=" ">
<subfield code="x">2471-5506</subfield>
<subfield code="0">(uri) http://worldcat.org/issn/2471-5506</subfield>
</datafield>```

A plain `issn` is also treated, but it has to reside in `022`.

So, how should we go on?

a) treat `776??.x` as `issn` (if no other `776??.?` exists)
b ) treat `776??.x` as `related.issn` (even if no other `776??.?` exists)
c) fix the resource' source (given that it's insufficiently/incorrectly catalogued)

**Comment by hagbeck** [comment]
Hm, good question. 
I think I prefer b)
a) is semantically incorrect, because 776 is for related resources (if I understand it correctly)
c) could be a problem as in this case, because the record comes from the Alma CZ

**Comment by dr0i** [comment]
Updated the index, see:
http://alma.lobid.org/resources/search?q=99371107766906441&format=json
You can also (as before) query the related issn: 
http://alma.lobid.org/resources/search?q=related.issn=%222471-5506%22&format=json

**Comment by dr0i** [comment]
You may check this @hagbeck and give a +1 if it's fine now.

**Comment by hagbeck** [comment]
Hi,
the ISSNs are missing again.

**Comment by dr0i** [comment]
ACK. Going to examine.
