### ISSUE TITLE
Broken links to Duisburg-Essen catalogue

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1335]
Sported by Sebastian Masse via Mastodon, https://digitalcourage.social/@sl007/108058896666664835:

> tl;dr Uni Du-Essen Katalog-Link funzt nicht. 
>
> Fragte jemand, ob ich ein Buch verleihen könnte (verrückte Idee).
> Guck ich lobid. 
> [https://lobid.org/resources/HT012820317​](https://lobid.org/resources/HT012820317)
> Ausnahmsweise ist mal was bei der Uni Duisburg Essen verfügbar ;) also hier in Essen aber Jedenfalls sehen die Links in Essen jetzt so aus 
https://primo.uni-due.de/discovery/search?query=any,contains,Robert%20Frank%20The%20Americans&tab=Everything&search_scope=MyInst_and_CI_custom&vid=49HBZ_UDE:UDE&offset=0​

**Comment by TobiasNx** [comment]
https://lobid.org/resources/HT012820317

It is the Link for:

[Lokalen Katalog abfragen](http://primo.ub.uni-due.de/primo_library/libweb/action/search.do?fn=search&vl%281UI0%29=exact&vl%28freeText0%29=HT012820317)

It also seems not to work with the Bielefeld-Link

**Comment by acka47** [comment]
OPAC link templates for lobid-resources are maintained in https://github.com/hbz/link-templates. The idea was to maintain them together with other hbz groups and other people from the Verbund. Apparently, lobid-resources is the only service to directly use them and people (e.g. DigiBib) use their own solutions for maintaining these link templates.

I opened a PR at https://github.com/hbz/link-templates/pull/18 for these two catalogues. Duisburg-Essen (DE-465) can be fixed as it provides means to search for hbz ID. FH Bielefeld (DE-Bi10) can not be fixed imo as there is no possibility to search for hbz ID in the EDS service they use.

I am afraid that other link templates will also be broken by now...

**Comment by acka47** [comment]
Reopening, for @dr0i to deploy the changes from https://github.com/hbz/link-templates/pull/18

**Comment by dr0i** [comment]
By merging the `link-template` the content at https://raw.githubusercontent.com/hbz/link-templates/master/isil2opac_hbzid.json has been updated. As this URL is used on-the-fly to get the OPAC link (when using the [html-view of the Item-URI](http://lobid.org/items/HT012820317:DE-465:JZIH2941(4)#!)) no further deployment is necessary.
Closing.
