### ISSUE TITLE
Serve contexts with CORS header and application/ld+json type

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#134]
Our remote context for API 2.0 is currently not working in the JSON-LD playground. For implementation in 1.0, see also https://github.com/hbz/lobid/pull/92.

**Comment by dr0i** [comment]
As discussed with @fsteeg this will be implemented  together with a first `play` deployment for API 2.0. Assigning.

**Comment by fsteeg** [comment]
Moved to https://github.com/hbz/lobid-resources-web/issues/2, closing.
