### ISSUE TITLE
Move Alma transformation to Metafix

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1341]
- [x] Provide area for the fix transformation. A copy of the ALMA-Morph transformation. (@dr0i)
- [x] Start turning the morph transformation into fix.
- [x] alma.fix #1345 
- [x] titleRelatedFields.fix #1345 
- [x] contribution.fix #1351
- [x] item.fix
- [x] facets.fix
- [x] fields.fix
- [x] describedBy.fix
- [x] subjects.fix

Take in mind:
- #1340 there is a list of invalidations that need to be addressed in the new transformation
- #1339 hints missing elements that are important for NWBIB and are not in the ALMA morph transformation

Before we can start:
- #1345 must be closed

**Comment by TobiasNx** [comment]
I reopen this ticket, since only the first part is done. The move of the alma transformation to fix will be done in steps over the next weeks.

**Comment by TobiasNx** [comment]
One thing I noticed working with MARC in FIX is that the index-nr and the possible subfields can both have numeric path names. This should be taken in mind.

**Comment by TobiasNx** [comment]
This can be closed since only details and frontend and backend implementations are needed to be done. Next steps are https://github.com/hbz/lobid-resources/issues/1435  #1342  #1434
