### ISSUE TITLE
Make GUI for ALMA run?

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1342]
At the moment we have no running GUI of the ALMA Transformation. We decided to create this with the ALMA-Fix lobid Transformation and not with the ALMA-Morph.

**Comment by fsteeg** [comment]
Will implement for https://test.lobid.org/resources when that is switched to the Fix-transformed Alma index.

**Comment by dr0i** [comment]
Done switching. https://test.lobid.org/resources was build on 2022-10-04, updates yet to be done.

**Comment by fsteeg** [comment]
Things currently erroring in the (Alma-Fix-based) test resources UI:

http://test.lobid.org/resources/search
http://test.lobid.org/resources/99370966568606441

The actual data is there:

http://test.lobid.org/resources/search?format=json
http://test.lobid.org/resources/99370966568606441.json

Access via hbzId does not seem possible (no error, not found):

http://test.lobid.org/resources/HT019042995
http://test.lobid.org/resources/HT019042995.json

Might require similar tweaks as NWBib: https://github.com/hbz/nwbib/commit/ba9327aaceb118678c53465f3a38c91b7adc444c, where access by hbzId works: https://test.nwbib.de/HT020968842 but not via almaMmsId: https://test.nwbib.de/99370849894106441.

**Comment by fsteeg** [comment]
The basic UI now works, now using `almaMmsIds` instead of `hbzIds`. See:

http://test.lobid.org/resources/search
http://test.lobid.org/resources/99370966568606441

The difference to NWBib is that there, it seems to work to stick with the `hbzIds`. Is that because all NWBib records do have an `hbzId`, while not all in lobid-resources do? Will it remain like that? I guess here we'll have to discuss what we want regarding canonical URLs and redirects. See also #1433.

One remaining UI issue are items, which are currently not displayed because the UI expects item URIs that contain their owner's ISILs (like `http://lobid.org/items/HT014991220:DE-38:34A6062#!`). Should (can?) the UI get the ISIL from the `heldBy.id`? (Or) can the ISILs be added in the transformation to create item URIs as before?

**Comment by blackwinter** [comment]
> Rephrasing @blackwinter: "`hbzId`s are discontinued. Everything that is catalogued newly into ALMA only gets an ALMAMMS id. But the `hbzid` if already existing are kept."

Not sure where you got that from, but it's wrong. AFAIK, hbz IDs will continue to be assigned to new resources.

**Comment by blackwinter** [comment]
> @blackwinter : I thought I asked you if the `hbzId`s are kept since new ressources exist already without "hbzId" (HT-...), e.g.: https://github.com/hbz/lobid-resources/blob/0f96587365ff00e5542b797ac0615ad767a6baa7/src/test/resources/alma-fix/990015048200206447.json

Only NZ resources get an hbz ID, this is an IZ resource.

**Comment by TobiasNx** [comment]
> > Is that because all NWBib records do have an hbzId, while not all in lobid-resources do?
> 
> Some NWBib resources lack already an hbzId: http://test.lobid.org/resources/search?q=+inCollection.id%3A%22http%3A%2F%2Flobid.org%2Fresources%2FHT014176012%23%21%22++AND+%28+NOT+_exists_%3AhbzId%29 Maybe that causes the error for https://test.nwbib.de/search?&q=Ein+Mann+zieht+durch ?
> 
> Re Items: asking @TobiasNx

https://alma.lobid.org/marcxml/99370682885406441
```
<datafield tag="035" ind1=" " ind2=" ">
<subfield code="a">(CKB)5280000000197576</subfield>
</datafield>
<datafield tag="035" ind1=" " ind2=" ">
<subfield code="a">(DE-599)ZDB2616496-6</subfield>
</datafield>
```

=> has no hbzId but nwbib classifications:
```
<datafield tag="084" ind1=" " ind2=" ">
<subfield code="a">01</subfield>
<subfield code="a">444050</subfield>
<subfield code="2">nwbib</subfield>
</datafield>
```

 => [which makes them a nwbib collection ressource.](https://github.com/hbz/lobid-resources/blob/0f96587365ff00e5542b797ac0615ad767a6baa7/src/main/resources/alma/fix/relatedRessourcesAndLinks.fix#L382-L391)

**Comment by acka47** [comment]
> Is this an ZDB-Ressource specific issue?

If it was, we could use hbz IDs plus ZDB IDs fpr NWBib.

**Comment by acka47** [comment]
As just discussed in the meeting, there is one last thing missing: the link to the source MARC/XML. Currently, the data is at `https://alma.lobid.org/marcxml/{alma-mmsid}`, e.g. https://alma.lobid.org/marcxml/990108873860206441. We decided that @dr0i will move it to `https://lobid.org/marcxml/{alma-mmsid}`.

**Comment by acka47** [comment]
We decided to remove the `<M>` link to the source from the UI for now.

**Comment by acka47** [comment]
> One remaining UI issue are items, which are currently not displayed because the UI expects item URIs that contain their owner's ISILs (like `http://lobid.org/items/HT014991220:DE-38:34A6062#!`). Should (can?) the UI get the ISIL from the `heldBy.id`? (Or) can the ISILs be added in the transformation to create item URIs as before?

As discussed just now in the team meeting, we will postpone the implementation of item information until we have finished the holding modeling in #1373 .

**Comment by fsteeg** [comment]
The source data link is now only visible when hovering, and points to the MARC-XML when deployed with Alma data (and will point to the MAB-XML data when deployed on production with Aleph data), see: http://test.lobid.org/resources/99370966568606441

Like this, it should be possible to always get to the actual source data (MAB or MARC) with a click.

For consistency with the existing code for the source links, I did not set up a `.mrcx` route, but use links to `https://alma.lobid.org/marcxml/{alma-mmsid}`, configured in resources.conf, like the MAB URL.

**Comment by blackwinter** [comment]
Assignment of hbz IDs in NZ phase 2 is documented in the [wiki](https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=754516217#Publishingf%C3%BCrhbzKatalog,IntrOX,lobid,Fernleiheintern/externZusammenfassung-MARC21035,hbz-Identifikationsnummer).
