### ISSUE TITLE
URI to lobid are always http instead of https in transformation

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1343]
I suggest to change that.

e.g.:
https://github.com/hbz/lobid-resources/blob/4b14daf9302cc8cea455be7d7a9a6f98e53e1cf3/src/main/resources/alma/common/describedBy.xml#L62-L63

**Comment by dr0i** [comment]
Done your suggestion.

**Comment by dr0i** [comment]
Wait, there are a lot more.

**Comment by TobiasNx** [comment]
Yes my example was only one of many.

**Comment by dr0i** [comment]
Should be completed now.
@TobiasNx please check.

**Comment by TobiasNx** [comment]
We need to update the schema too:
https://github.com/hbz/lobid-resources/pull/1346

**Comment by dr0i** [comment]
As discussed in standup:
We can't just simply switch to https for RDF data.
We _can_ do this like in [4b6abb0](https://github.com/hbz/lobid-resources/commit/4b6abb06053b9b77a29580ac43408881db1dfbbf).
Other commits should be reverted.
Note to self: don't do code review and functional review in one person.

**Comment by dr0i** [comment]
Reverted [bd88d02](https://github.com/hbz/lobid-resources/commit/bd88d0220b7cef473bdce8319bb1669703c01cf7).

**Comment by TobiasNx** [comment]
This looks good now. +1
