### ISSUE TITLE
Add `fix` support to lobid ressources

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1345]
At the moment it seems that only morph is supported. To move ALMA transformation to Metafix #1341. We need support for Metafix in lobid-ressources.

**Comment by dr0i** [comment]
#1347 should enable metafix.  A first example of ETL with alma-fix is provided there, also how to use it. the `fix` are taken from https://github.com/hbz/limetrans/tree/wip/src/main/resources/transformation.
There will be many things not correct yet, e.g. fix variables set in `AlmaMarc21XmlToLobidJsonMetafixTest.java` - we will work that out.
