### ISSUE TITLE
ALMA test xmls are not valid MARCXML

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1348]
[See here](https://metafacture.org/playground/?flux=PG_DATA%0A%7C+decode-xml%0A%7C+handle-marcxml%0A%7C+encode-json%0A%7C+print%0A%3B&data=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22utf-8%22%3F%3E%0A++%3Crecord%3E%0A++++%3Cleader%3E01187cam%23a2200397%23c%234500%3C/leader%3E%0A++++%3Ccontrolfield+tag%3D%22005%22%3E20210409180628.0%3C/controlfield%3E%0A++++%3Ccontrolfield+tag%3D%22007%22%3Ecr%23%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%3C/controlfield%3E%0A++++%3Ccontrolfield+tag%3D%22008%22%3E190918%7C2016%23%23%23%23gw%23%23%23%23%23%23o%23%23%23%23%23%7C%7C%7C%23%7C%23ger%23c%3C/controlfield%3E%0A++++%3Ccontrolfield+tag%3D%22003%22%3EDE-605%3C/controlfield%3E%0A++++%3Ccontrolfield+tag%3D%22001%22%3E990363946050206441%3C/controlfield%3E%0A++++%3Cdatafield+tag%3D%22020%22+ind1%3D%22+%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22a%22%3E9783161546303%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22c%22%3Ee-book%3C/subfield%3E%0A++++++%3Csubfield+code%3D%229%22%3E978-3-16-154630-3%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22035%22+ind1%3D%22+%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22a%22%3E%28DE-605%29HT020202475%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22040%22+ind1%3D%22+%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22a%22%3E290%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22b%22%3Eger%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22d%22%3E290%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22e%22%3Erda%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22041%22+ind1%3D%22+%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22a%22%3Eger%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22044%22+ind1%3D%22+%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22c%22%3EXA-DE%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22100%22+ind1%3D%221%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22a%22%3EBreuer%2C+Stefan%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22d%22%3E1948-%3C/subfield%3E%0A++++++%3Csubfield+code%3D%220%22%3E%28DE-588%29120195364%3C/subfield%3E%0A++++++%3Csubfield+code%3D%224%22%3Eaut%3C/subfield%3E%0A++++++%3Csubfield+code%3D%220%22%3E%28uri%29+https%3A//portal.dnb.de/opac.htm%3Fmethod%3DsimpleSearch%26amp%3BcqlMode%3Dtrue%26amp%3Bquery%3Didn%3D120195364%3C/subfield%3E%0A++++++%3Csubfield+code%3D%220%22%3E%28uri%29+http%3A//viaf.org/viaf/sourceID/DNB%7C120195364%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22B%22%3EGND-120195364%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22245%22+ind1%3D%221%22+ind2%3D%220%22%3E%0A++++++%3Csubfield+code%3D%22a%22%3EKritische+Theorie%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22b%22%3ESchl%26%23252%3Bsselbegriffe%2C+Kontroversen%2C+Grenzen%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22c%22%3EStefan+Breuer%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22264%22+ind1%3D%22+%22+ind2%3D%221%22%3E%0A++++++%3Csubfield+code%3D%22a%22%3ET%26%23252%3Bbingen%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22b%22%3EMohr+Siebeck%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22c%22%3E%5B2016%5D%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22264%22+ind1%3D%22+%22+ind2%3D%224%22%3E%0A++++++%3Csubfield+code%3D%22c%22%3E%26%23169%3B+2016%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22300%22+ind1%3D%22+%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22a%22%3E1+Online-Ressource+%28271+Seiten%29%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22336%22+ind1%3D%22+%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22b%22%3Etxt%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22337%22+ind1%3D%22+%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22b%22%3Ec%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22338%22+ind1%3D%22+%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22b%22%3Ecr%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22650%22+ind1%3D%22+%22+ind2%3D%224%22%3E%0A++++++%3Csubfield+code%3D%22a%22%3ECritical+theory%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22650%22+ind1%3D%22+%22+ind2%3D%224%22%3E%0A++++++%3Csubfield+code%3D%22a%22%3EElectronic+books%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22776%22+ind1%3D%220%22+ind2%3D%228%22%3E%0A++++++%3Csubfield+code%3D%22i%22%3EErscheint+auch+als%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22n%22%3EDruck-Ausgabe%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22z%22%3E9783161546105%3C/subfield%3E%0A++++++%3Csubfield+code%3D%220%22%3E%28uri%29+http%3A//www.isbnsearch.org/isbn/9783161546105%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22856%22+ind1%3D%224%22+ind2%3D%220%22%3E%0A++++++%3Csubfield+code%3D%22u%22%3Ehttps%3A//doi.org/10.1628/978-3-16-154630-3%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22x%22%3EResolving-System%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22912%22+ind1%3D%22+%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22a%22%3EZDB-197-MSE%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22960%22+ind1%3D%221%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22i%22%3Eiall%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22962%22+ind1%3D%22+%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22e%22%3EZDB-197-MSE%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22964%22+ind1%3D%220%22+ind2%3D%22s%22%3E%0A++++++%3Csubfield+code%3D%22F%22%3E030%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22A%22%3Ea%7C%7Cur%7C%7C%7C%7C%7C%7C17%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22964%22+ind1%3D%220%22+ind2%3D%22s%22%3E%0A++++++%3Csubfield+code%3D%22F%22%3E050%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22A%22%3E%7C%7C%7C%7C%7C%7C%7C%7Cg%7C%7C%7C%7C%7C%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22964%22+ind1%3D%220%22+ind2%3D%22s%22%3E%0A++++++%3Csubfield+code%3D%22F%22%3E051%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22A%22%3Em%7C%7C%7C%7C%7C%7C%7C%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22035%22+ind1%3D%22+%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22a%22%3E%28DE-627%2901281704X%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22035%22+ind1%3D%22+%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22a%22%3E%28XX-XxUND%29KEP01281704X%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22035%22+ind1%3D%22+%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22a%22%3E%28EDP%2901281704X%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22MBD%22+ind1%3D%22+%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22M%22%3E49HBZ_NETWORK%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22i%22%3E990363946050206441%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22n%22%3EHBZ+Network%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22MBD%22+ind1%3D%22+%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22M%22%3E49HBZ_UBD%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22i%22%3E991009604019706445%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22n%22%3EUB+Dortmund%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22020%22+ind1%3D%22+%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22a%22%3E9783161546303%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22c%22%3Ee-book%3C/subfield%3E%0A++++++%3Csubfield+code%3D%229%22%3E978-3-16-154630-3%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22M%22%3E49HBZ_UBD%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22980%22+ind1%3D%221%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22e%22%3EHBZ%3C/subfield%3E%0A++++++%3Csubfield+code%3D%229%22%3ELOCAL%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22M%22%3E49HBZ_UBD%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22981%22+ind1%3D%22+%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22a%22%3E%28DE-290%291732340%3C/subfield%3E%0A++++++%3Csubfield+code%3D%229%22%3ELOCAL%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22M%22%3E49HBZ_UBD%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22982%22+ind1%3D%22+%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%222%22%3Eunaufgegliedert%3C/subfield%3E%0A++++++%3Csubfield+code%3D%229%22%3ELOCAL%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22M%22%3E49HBZ_UBD%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22982%22+ind1%3D%22+%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%222%22%3Eunaufgegliedert%3C/subfield%3E%0A++++++%3Csubfield+code%3D%229%22%3ELOCAL%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22M%22%3E49HBZ_UBD%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22997%22+ind1%3D%22+%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22a%22%3E20190918%3C/subfield%3E%0A++++++%3Csubfield+code%3D%229%22%3ELOCAL%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22M%22%3E49HBZ_UBD%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22998%22+ind1%3D%224%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22z%22%3EZugriff+nur+im+Hochschulnetz+der+Technischen+Universit%26%23228%3Bt+Dortmund+bzw.+f%26%23252%3Br+autorisierte+Benutzer%3C/subfield%3E%0A++++++%3Csubfield+code%3D%229%22%3ELOCAL%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22M%22%3E49HBZ_UBD%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22MNG%22+ind1%3D%22+%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22c%22%3ESystem%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22f%22%3EILS%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22i%22%3Emarc21%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22k%22%3E01%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22e%22%3Efalse%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22d%22%3E2021-04-09+18%3A06%3A28+Europe/Berlin%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22g%22%3E036394605-HBZ01%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22j%22%3E60%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22a%22%3Eimport%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22b%22%3E2021-04-05+12%3A19%3A05+Europe/Berlin%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22POR%22+ind1%3D%22+%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22x%22%3ESystem%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22a%22%3E53209365020006445%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22M%22%3E49HBZ_UBD%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22c%22%3Estatic%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22l%22%3EZugriff+nur+im+Hochschulnetz+der+Technischen+Universit%26%23228%3Bt+Dortmund+bzw.+f%26%23252%3Br+autorisierte+Benutzer%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22y%22%3E2021-04-20+21%3A35%3A24+Europe/Berlin%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22w%22%3E2021-04-20+21%3A35%3A19+Europe/Berlin%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22D%22%3Ehttps%3A//eu04.alma.exlibrisgroup.com/view/uresolver/49HBZ_NETWORK/openurl%3Fu.ignore_date_coverage%3Dtrue%26amp%3Bportfolio_pid%3D53209365020006445%26amp%3BForce_direct%3Dtrue%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22v%22%3EP2E_JOB%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22z%22%3E2021-04-20+19%3A35%3A19%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22i%22%3Efalse%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22S%22%3E52209365030006445%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22d%22%3Ehttps%3A//hbz-network.userservices.exlibrisgroup.com/view/uresolver/49HBZ_NETWORK/openurl%3Fu.ignore_date_coverage%3Dtrue%26amp%3Brft.mms_id%3D991009604019706445%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22b%22%3EAvailable%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22f%22%3EBOOK%3C/subfield%3E%0A++++++%3Csubfield+code%3D%228%22%3E53209365020006445%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22GPN%22+ind1%3D%221%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22a%22%3EBrojer%2C+%26%23352%3Btefan%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22d%22%3E1948-%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22A%22%3EGND%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22B%22%3EGND-120195364%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22C%22%3E400%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22GPN%22+ind1%3D%221%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22a%22%3EBreuer%2C+S.%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22d%22%3E1948-%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22A%22%3EGND%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22B%22%3EGND-120195364%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22C%22%3E400%3C/subfield%3E%0A++++%3C/datafield%3E%0A++++%3Cdatafield+tag%3D%22GSI%22+ind1%3D%227%22+ind2%3D%22+%22%3E%0A++++++%3Csubfield+code%3D%22a%22%3E120195364%3C/subfield%3E%0A++++++%3Csubfield+code%3D%220%22%3Ehttp%3A//d-nb.info/gnd/120195364%3C/subfield%3E%0A++++++%3Csubfield+code%3D%222%22%3Egnd%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22A%22%3EGND%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22B%22%3EGND-120195364%3C/subfield%3E%0A++++++%3Csubfield+code%3D%22C%22%3E024%3C/subfield%3E%0A++++%3C/datafield%3E%0A++%3C/record%3E&active-editor=fix)

The problem is, that the namespace is not provided in the marc xml files:
https://github.com/hbz/lobid-resources/blob/b1b8a24d6958026a2adebf1ff607a6ec9dd664aa/src/test/resources/alma

It s:  `<record>`

Should be: `<record xmlns="http://www.loc.gov/MARC21/slim">`

If there is a` <collection> `element as in https://github.com/hbz/lobid-resources/blob/4fbc7cfa76792bc5730f19a17f2292d24ab515ac/src/test/resources/alma/almaMarcXmlTestFiles.xml.tar.bz2 then the namespace should include the namespace refrence not the `<record>` element.
It s:  `<collection><record>`

Should be: `<collection xmlns="http://www.loc.gov/MARC21/slim"><record>`

Because of this the playground as well as other Flux-Scripts do not recognize the files without the namespace as marc-xml.

**Comment by dr0i** [comment]
But our [ETL](https://github.com/hbz/lobid-resources/blob/c21685ce23fe223712953f920b33a2228686a24a/src/test/java/org/lobid/resources/AlmaMarc21XmlToLobidJsonTest.java#L161) is working with it.
What looks your flux like?
In java its: `FileOpener->XmlDecoder->MarcXmlHandler` ...

**Comment by dr0i** [comment]
ah, uh - and use 'marcXmlHandler.setNamespace(null);` - this prevents a ns-check. In flux, use `| handle-marcxml(namespace=null)`. 
Try that. May be it's not working because the `null` must be a `null` and not a string `null`, so that this workaround doesn't work with flux.

**Comment by blackwinter** [comment]
> But the option behaviour [...] is not documented

Of course it's documented:

```
options: namespace (String), attributemarker (String)
```

You can either set it to `null` as @dr0i suggested (if that works in Flux) in order to disable the namespace check or set it to the required namespace value (`"http://www.loc.gov/MARC21/slim"`) in order make the check pass (see metafacture/metafacture-core#331).

> normally this would be "tru[e]"/"false"

This only applies to `boolean` options.

**Comment by blackwinter** [comment]
> But the option behaviour [...] is not documented

Oh, did you mean the part about disabling the namespace check? Then you're right, that's currently not documented. Sorry if I misunderstood.

**Comment by dr0i** [comment]
@TobiasNx can you document it?

**Comment by TobiasNx** [comment]
https://github.com/metafacture/metafacture-core/pull/504

**Comment by dr0i** [comment]
This issue is related to https://github.com/metafacture/metafacture-core/issues/569.
Btw: is it solved? What is missing here?

**Comment by TobiasNx** [comment]
While we can work with the marc data from lobid with metafacture now, due to the adjustemts made in https://github.com/metafacture/metafacture-core/issues/569 . The marc data is still not valid.

But since the alma publishing data is part of our records one could argue the data is no "pure" marc xml. 

So we could still add the namespace to the marc xml records OR just put this on wont fix until somebody asks for it.

**Comment by dr0i** [comment]
Won't fix atm as discussed in our meeting. Closing.
