### ISSUE TITLE
ALMA-FIX: "POR"-Transformation?

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1356]
What was the problem we had transforming "POR" information with Morph. There are something with an repeated field,
`POR## $$A` and `POR## $$a`

Do you remember what the issue was?

**Comment by blackwinter** [comment]
AFAIR, you needed to create a `hasItem` per `POR$$A` (with data from `POR`). Morph can't do that (reliably), with Fix it's easy :)

**Comment by TobiasNx** [comment]
@dr0i  could you have a look if this can be closed?

**Comment by dr0i** [comment]
Commits are already in master. So yeah, closing.
