### ISSUE TITLE
Missing Alma updates 

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1358]
@hagbeck writes today:

> offenbar kommen seit letzten Mittwoch oder Donnerstag keine Updates aus Alma mehr in lobid an

I started investigating whether this is a problem on our side or on the provision side.

**Comment by dr0i** [comment]
I had to restart and update manually. Should be fine now. Can you confrm @hagbeck ?

**Comment by hagbeck** [comment]
I can confirm. Thanks!

**Comment by acka47** [comment]
Closing

**Comment by TobiasNx** [comment]
Is still a problem? http://lobid.org/hbz01/HT021429811 The MAB file is not accessable? @fsteeg suggested to ask here.
