### ISSUE TITLE
Alma: NZ resources from CZ

### ISSUE THREAD

**Issue by hagbeck** [hbz/lobid-resources#1359]
Hi,

in NZ exists resources from CZ which are not directly linked to the IZ. These resources are in the IZ from CZ, too. The NZ resources are marked as "held by institution" in Alma. Examples: 99370703206706441, 99370703864506441, 99370706268806441\
The problem is, that our discovery service is unable to link these NZ resources to the "real" holdings from our IZ.

From a discussion with hbz colleagues there is now the following proposal:\
the lobid-resources should ignore the NZ resources containing a field 035 $$a starting/containing the substring (CKB).

My problem with that approach is, that I don't know, how many records this affects, because there is no search option in Alma to get this info. Could you query this number of records from you data?

**Comment by blackwinter** [comment]
I'm not sure I totally follow your scenario, but you can search for `All Titles where (Other System Number (035a) Exact starts with "(CKB)")` in the relevant zone (institution/network/community).

**Comment by hagbeck** [comment]
@blackwinter you are right. This are ca. 1,3 records. but it is not possible to limit this results to "held by 290".

**Comment by blackwinter** [comment]
I'm sorry, I don't think I understand what you're trying to achieve here. Maybe the lobid team can be of assistance.

**Comment by TobiasNx** [comment]
Hi @hagbeck, I am back from vacation. Where and with whom did you discuss this? I try to get some context concerning the problem.
Where is "held by 290" stated to narrow down CBK?
Perhaps we could revive our videocall on friday with @dr0i and get more details.

**Comment by hagbeck** [comment]
@TobiasNx I discussed that with Natascha Dahmenfrom from the Alma NZ view. But I think, a revive of our videocall makes sense in this complex case.

**Comment by TobiasNx** [comment]
Still could you give an example where held by is stated?

**Comment by hagbeck** [comment]
The examples 99370703206706441, 99370703864506441, 99370706268806441 are in the NZ from CZ with prefix (CKB) in 035$a. In the Alma NZ WebUI is shown "held by". This results by the publishing processes in a lobid resource with a holding for 290.\
But this NZ-MMS-IDs have no direct links to the IZ and are therefore useless for us.

... But wait: The missed IZ-MMS-ID is contained in the lobid-resource in the "hasItem/held by" and therefore the NZ and IZ are linked!? Sorry, I've to look at it again...

**Comment by hagbeck** [comment]
Hi,
this issue isn't relevant any more, because lobid-resource has already solved my problem :-) Sorry for the confusion!

The link between the resources is in lobid by the `label` or `id` in case of `type=MBD` in:

```json
{
    "heldBy": {
        "id": "http://lobid.org/organisations/DE-290#!",
        "label": "lobid Organisation"
    },
    "id": "https://lobid.org/item/991013480109306445",
    "type": [
        "MBD"
    ],
    "label": "991013480109306445"
}
```
The NZs 99370703206706441 is therefore linked with the IZs 991013480109306445 and everything is fine :-)
