### ISSUE TITLE
FixProcessException:  Can't find: $last in: null

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1360]
Following up #1341 following error for resource `990063549080206441` occurs:
```
[WARNING] 
org.metafacture.metafix.FixProcessException: Error while executing Fix expression (at file:/home/sol/git/lobid-resources-alma-fix/src/main/resources/alma/fix/fields.fix, line 451): copy_field("$i.t", "isPartOf[].$last.hasSuperordinate[].$last.label")
[...]
Caused by: java.lang.IllegalArgumentException: Can't find: $last in: null
```

**Comment by TobiasNx** [comment]
Should be fixed with https://github.com/hbz/lobid-resources/pull/1354/commits/7a185e3fbd607ba48bae96577074aad78ce220e6

**Comment by dr0i** [comment]
It's not fixed.
Added the resource in question and improved logging. Also, `AlmaMarc21XmlToLobidJsonMetafixTest` was not part of the automatically executed UnitTest.

To test reasonable fast:
```
mvn clean install -DskipTests=true
mvn failsafe:integration-test -Dit.test=AlmaMarc21XmlToLobidJsonMetafixTest.java failsafe:verify
```

You will see the failing of the test. Look at the 'ERROR' outputs, there is also the name of the failing XML logged.

**Comment by TobiasNx** [comment]
Okay you are right
should be fixed now.

**Comment by dr0i** [comment]
Merged, closing.
