### ISSUE TITLE
Find documentation for ALMA-Marc specific elements

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1363]
Is there a documentation for:
"POR", "ITM", "MNG" etc.

I do not find any online?

**Comment by dr0i** [comment]
No idea - unassigning myself.

**Comment by blackwinter** [comment]
These are defined in the publishing profile which is documented [here](https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=612532300).

**Comment by blackwinter** [comment]
Can this issue be closed?

**Comment by TobiasNx** [comment]
Yes thanks
