### ISSUE TITLE
ALMA-Fix: Add `hasVersion`

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1367]
This not yet added.

https://github.com/hbz/lobid-resources/blob/e4d172608a1a58b84c8684092fb8cdab2b001aaf/src/main/resources/alma/fix/fields.fix#L538-L539

**Comment by TobiasNx** [comment]
https://github.com/hbz/lobid-resources/issues/1242

we outcommented `hasVersion` for a reason, since the mapping is not matching suitable for the concept https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/hasVersion

See also:
https://github.com/hbz/lobid-resources/issues/1242#issuecomment-832483535
https://github.com/hbz/lobid-resources/issues/1242#issuecomment-833305273

We planed to remodel `hasVersion`.

**Comment by acka47** [comment]
> we outcommented `hasVersion` for a reason, since the mapping is not matching suitable for the concept https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/hasVersion

In https://github.com/hbz/lobid-resources/issues/1242#issuecomment-832483535 @TobiasNx quotes this from https://github.com/hbz/lobid-resources/issues/441#issuecomment-305173534 to show problems with `hasVersion`:

> `hasVersion`: Contains everything from 655 which isn't labeled as a fulltext, table of contents or description.

However, if I understand correctly, this statement was updated in https://github.com/hbz/lobid-resources/issues/441#issuecomment-306433314:

> Before the changes it contained all but archived resources if it was an online resource. So it also contained `tableOfContents` etc. Since almost all urls of `hasVersion` in the test set lead to fulltexts they are not exactly *about* a resource but a version of it and should stay there.

However, this refers to some test set. I'd need some up-to-date information to have am opinion on this. Generally, I'd be happy with a pragmatic approach that puts everything where you can find the resource or another version of it under `sdo:sameAs`, see also https://github.com/hbz/lobid-resources/issues/1400#issuecomment-1225492131.

**Comment by TobiasNx** [comment]
https://wiki.dnb.de/pages/viewpage.action?pageId=68061169

here is a definition of `hasVersion` that I find plausible: "

Parallele Ausgabe (zum Beispiel andere Sprache)
	

[dct:hasVersion](http://purl.org/dc/terms/hasVersion)
	

URI"

the refrence all 655 but toC etc. was based on the ALEPH-Morph not just the test set.

**Comment by TobiasNx** [comment]
We decided to discontiune `hasVersion` for now.
