### ISSUE TITLE
Separate Contribution objects for person with two roles

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#139]
From https://github.com/hbz/lobid-resources/issues/79#issuecomment-268818628:

> But I don't think it is ok to list two roles in one `contribution` object. If a person has two roles in a work (e.g. "Sprecher" and "Darsteller") these are actually two contributions with different roles but not one contribution covering two roles.

I posted this question to the Bibframe list and Ray Denenberg just confirmed what I said. Quoting Ray:

> If you want to list two roles, e.g. “illustrator” and “author” for the
> same person, the rule is, declare two separate Contribution resources.  
> Two or more role statements within the same Contribution resource should
> occur only because you want to provide two different representations
> (e.g. two different URIs) for the same role. 

Thus, we should have two separate Contribution objects if the same person has two roles regarding a resource.

**Comment by dr0i** [comment]
A nice example is given in lobid/lodmill#715 : http://lobid.org/resource/HT014525099 (which will be present when 715 is solved).

**Comment by acka47** [comment]
> A nice example is given in lobid/lodmill#715 :  http://lobid.org/resources/HT014525099 with 118867539 (which will be present when 715 is solved).

I am afraid that lobid/lodmill#715 has some problems and doubt that http://lobid.org/resources/HT014525099 is a good example. Will comment further at the original issue.
