### ISSUE TITLE
Embed item information in resource description

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#140]
As I argued in today's meeting, I would like to embed item information (owner, call number, possibly geo coordinates of the owner) in the resource description. I also think we can leave out the item URIs altogether and embed them as blank nodes.

**Comment by fsteeg** [comment]
Moving to `ready`.

If we want to do this, we should prioritize it, to reach a stable data structure for the UI as soon as possible.

**Comment by fsteeg** [comment]
Result of our offline discussion: we will keep the current general items approach for the API 2.0 launch. We will create routes and pages for the items in lobid-organisations-web. If we want to embed the item details, we can add them to each item object (which currently contain the URI only) and stay compatible with the launched 2.0 API. Unlike #116 there is no specific issue with this approach, so we can close this (and reopen if we do want to pick it up at some point).

**Comment by acka47** [comment]
Reopening as this was requested by @hagbeck via email:

> - hasItem: Hier wäre es toll, wenn die Signatur und das Sigel nicht nur
> im URI enthalten wären. Optimal wären hier sogar noch die Geo-Daten der
> Bib :-)

I suggest we add `callNumber` and `heldBy` but leave out geo information on the owner as this add two more levels of hierarchy (`hasItem.heldBy.location.geo`).

**Comment by acka47** [comment]
Here is an example. [An item of resource HT017435917 held by the UB Dortmund](http://lobid.org/items/HT017435917:DE-290:L%2024710?format=json) currently has the following item information:

```json
{
   "@context":"http://lobid.org/resources/context.jsonld",
   "callNumber":"L 24710",
   "describedby":{
      "id":"http://lobid.org/items/HT017435917:DE-290:L%2024710",
      "label":"lobid Bestandsressource"
   },
   "heldBy":{
      "id":"http://lobid.org/organisations/DE-290",
      "label":"lobid Organisation"
   },
   "id":"http://lobid.org/items/HT017435917:DE-290:L%2024710#!",
   "itemOf":{
      "id":"http://lobid.org/resources/HT017435917#!",
      "label":"lobid Ressource"
   },
   "note":[
      "00000001"
   ],
   "type":[
      "Item"
   ]
}
```

As noted, we should add `callNumber` and `heldBy` to the manifestation/instance level and I think, `type` information also makes sense. This would mean that [HT017435917](http://lobid.org/resources/HT017435917?format=json) should look like this:

```json
{
   "@context":"http://lobid.org/resources/context.jsonld",
   "id":"http://lobid.org/resources/HT017435917#!",
   "hasItem":[
      {
         "id":"http://lobid.org/items/HT017435917:DE-290:L%2024710#!",
         "type: "Item",
         "label":"lobid Bestandsressource",
         "callNumber": L 24710",
         "heldBy":{
            "id":"http://lobid.org/organisations/DE-290",
            "label":"lobid Organisation"
         }
      }
   ]
}
```

I think, we should also work on the labels "lobid Bestandsressource" and "lobid Organisation". Either we should use better generic labels or – if this is easy to implement – use the name of the library for `hasItem.heldBy.label` and a combination of call number and library name for `hasItem.label`

**Comment by ChristophEwertowski** [comment]
After some working on it, it became clear that I need some guideline how to use rdf:subject, see #389 . If the callNumber should be added to the main resource and not to the instances of this resource then probably some work at the ntriples files is needed. Now the callNumber only exists at the instances and the resources don't have the field. A point for discussion with @dr0i in the next week.
