### ISSUE TITLE
Add data about collections 

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1411]
Some resources are linked to e.g. https://lobid.org/collections#vl-ulbd . The URL should resolve.

- [ ] identifiy and add data to all ` https://lobid.org/collections` 
- [ ] make the URL resolvable

Came up in https://github.com/hbz/lobid-resources/pull/1403#pullrequestreview-1085027482.

**Comment by acka47** [comment]
Won't fix. We are using the URIs as IDs only and said in the past that we would add RDF only if needed, see https://github.com/hbz/lobid-resources/issues/1052#issuecomment-598137600. Closing
