### ISSUE TITLE
publication.publicationHistory is recorded for too many resources

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1419]
E.g. all monographs currently have this information although it should only be found in descriptions of series and periodicals: `$ curl "https://alma.lobid.org/resources/search?q=type:Book&format=json" | jq .member[].publication[].publicationHistory`

The question is how to filter for resources that might contain this field. One way might be to only add this for ZDB resources.

**Comment by TobiasNx** [comment]
@acka47 hinted to problems with publicationHistory:

> I just took a short look at it. At least the `publicationHistory` needs some improvement. Currently it only reads "anfangs" for two resource. I guess, we will have to include more (all?) subfields from Marc 264 when building `publicationHistory` and currently wea re only seem to be using subfield `a`.
> 
> See both test files with 264:
> 
> https://github.com/hbz/lobid-resources/blob/c3425a1dd047fd44403e15a643c299e507797781/src/test/resources/alma-fix/990108740950206441.xml#L54-L66
> 
> https://github.com/hbz/lobid-resources/blob/c3425a1dd047fd44403e15a643c299e507797781/src/test/resources/alma-fix/990053976760206441.xml#L86-L95
> 
> It is always good to also check how the ZDB RDF looks (here e.g. http://ld.zdb-services.de/data/123550-3.ttl) but in the case of MARC 26, they are not transforming it to RDF. Looking at the HTML view, though, one sees that they just show the contents of 362a for Publication History/Erscheinungsverlauf, see https://ld.zdb-services.de/resource/123550-3 (Click on "More title information") and https://ld.zdb-services.de/resource/1484300-6.
> 
> https://github.com/hbz/lobid-resources/blob/c3425a1dd047fd44403e15a643c299e507797781/src/test/resources/alma-fix/990053976760206441.xml#L96-L98
> 
> https://github.com/hbz/lobid-resources/blob/c3425a1dd047fd44403e15a643c299e507797781/src/test/resources/alma-fix/990108740950206441.xml#L67-L69
> 
> So we should do the same and skip 264.

https://github.com/hbz/lobid-resources/pull/1488#issuecomment-1290593062

I should fix this within this ticket.

**Comment by TobiasNx** [comment]
This should be fixed with #1631

**Comment by dr0i** [comment]
This can be checked beginning with 20.2.2023.

**Comment by TobiasNx** [comment]
> E.g. all monographs currently have this information although it should only be found in descriptions of series and periodicals: `$ curl "https://alma.lobid.org/resources/search?q=type:Book&format=json" | jq .member[].publication[].publicationHistory`
> 
> The question is how to filter for resources that might contain this field. One way might be to only add this for ZDB resources.

`curl` result now is zero
