### ISSUE TITLE
ALMA-Fix: Lookup DDC-Labels

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1425]
Since the real lookup is hidden at the server, i did not set this up yet.

**Comment by TobiasNx** [comment]
Is this working now? @dr0i ? Could you have a look at the index?

**Comment by TobiasNx** [comment]
@dr0i did you have a look if this works now? Can we close it?

**Comment by dr0i** [comment]
For this we need to build an Alma-FIX index. I am going to use the webhook-induced ETL which depends on https://github.com/hbz/lobid-resources/issues/1435.

**Comment by TobiasNx** [comment]
Seems to work.

```
{
      "notation" : "004",
      "source" : {
        "label" : "Dewey-Dezimalklassifikation",
        "id" : "http://d-nb.info/gnd/4149423-4"
      },
      "label" : "Informatik",
      "type" : [ "Concept" ],
      "version" : "23sdnb"
    }
```
Version comes from the ALMA-Morph: https://github.com/hbz/lobid-resources/blob/bd88d0220b7cef473bdce8319bb1669703c01cf7/src/main/resources/alma/common/subjects.xml#L69


I found that there is a bug in the old lobid with a combination of dewey and Schlagwortfolgen:
http://lobid.org/resources/search?q=hbzId:HT019631849&format=json

**Comment by dr0i** [comment]
With #1435 resolved this seems to work, see [http://test.lobid.org/resources/search?q=HT019631849&format=json. ](http://test.lobid.org/resources/search?q=subject.source.id:%22http://d-nb.info/gnd/4149423-4%22&format=json).

re "Bug old lobid resources": please open a new issue (or just ignore it, I don't think we will fix this).

**Comment by dr0i** [comment]
@acka47 can we close this?

**Comment by TobiasNx** [comment]
```
{
          "notation": "823.92",
          "source": {
            "label": "Dewey-Dezimalklassifikation",
            "id": ["http://d-nb.info/gnd/4149423-4"](http://d-nb.info/gnd/4149423-4)
          },
          "label": "Englische Erzählprosa--2000–",
          "type": [
            "Concept"
          ],
          "version": "23"
        }
 ```

seems to work:        http://test.lobid.org/resources/search?q=subject.source.id:%22http://d-nb.info/gnd/4149423-4%22&format=json
