### ISSUE TITLE
Trigger Webhook after ETL - timing issue?

### ISSUE THREAD

**Issue by hagbeck** [hbz/lobid-resources#1430]
Hi,
since last week we observed some problems with the webhook. It seems that at the time we get the trigger and start our ETL the data in lobid is not stable. If we wait for a few minutes starting our ETL the data is fine. Is there a timing problem in your process?

**Comment by dr0i** [comment]
Do you experience this behaviour only after *basedump* indexing (this month's weeks always at Saturdays) or everytime, i.e. also when *updating* the index (every other day of the week)? I just discovered that the webhook is triggered _before_  the newly created index is switched (done only when doing full basedump ETL). There is a time gap of **10s to 20s**. Fixing that is easy. 

If you experience this unstable behaviour _every time_ or if it's greater than the 20s than it could be possible that ES is doing something in the background and the index is not full "stable" to be queried, despite the [usrb.execute().actionGet()](https://github.com/hbz/lobid-resources/blob/master/src/main/java/org/lobid/resources/ElasticsearchIndexer.java#L151). I would just add 5m safety sleep before informing your webhook listener (this is a rather arbitrary value but "should be safe").

Concerns #1380.

**Comment by hagbeck** [comment]
Last Tuesday and Wednesday there were no results at request time (ca. 3 minutes after the trigger) and on the other days the data was not fully updated.
In the first case restarting our process solves the problem.
In the last case we missed data in our system, which was a few minutes later available.

Today I added a delay of a few minutes in our process to prevent empty lobid results.

**Comment by dr0i** [comment]
Thx @hagbeck for the infos.
I will just add the 5 minute safety distance.

**Comment by dr0i** [comment]
Deployed hot fix https://github.com/hbz/lobid-resources/pull/1431.

> Today I added a delay of a few minutes in our process to prevent empty lobid results.

You may test this, if you wish. Comes now with 5 minutes safety distance.
Thx for reporting in any case!

**Comment by dr0i** [comment]
Checked again, also fulldump is using the safety distance. Should all be good here. If the problem shows up again simply reopen this issue.
Closing for now.
