### ISSUE TITLE
ALMA-Fix: Replace ALMA-Morph with ALMA-Fix

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1434]
Since Dortmund is happy with the number of their resources we can replace ALMA-Fix later this week.

FYI: @hagbeck and @UBmakla

**Comment by dr0i** [comment]
- [ ] configure routes (delete alma, use alma-fix)
- [ ] configure webhook notification (emails)
- [ ] make `lobid-resources-alma` the new `lobid-resources-test`. Also port!
- [ ] remove alma-morph code and git-tag repo `remove alma-morph`
- [ ] configure monit / remove alma-morph on all servers
- [ ] inform customers
- [ ] blog ?
- [ ] switch nwbib ?

**Comment by dr0i** [comment]
I close this beast.
Open issue is to write blog post.
