### ISSUE TITLE
`doi`-Element always URI or just the code?

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1439]
https://github.com/hbz/lobid-resources/blob/2ae7b86259115ee3fa8693e3ba16ebda2739ca54/src/main/resources/alma/fix/identifiers.fix#L70-L78

**Comment by acka47** [comment]
We use the [bido:doi](http://purl.org/ontology/bibo/doi) property for this which has rdf:Literal as range. This means, URIs on this property would be interpreted as strings by RDF libraries/reasoners. Thus, I suggest to use only the code. Applications can resolve these easily as should we add links to the URI in HTML interfaces.

**Comment by TobiasNx** [comment]
Since we have no example for a urls in elements in `024`. We would not need to filter them out.
But we could pick up missing dois from `856` if they have:

```
    <datafield tag="856" ind1="4" ind2="0">
      <subfield code="u">https://doi.org/10.1628/978-3-16-154630-3</subfield>
      <subfield code="x">Resolving-System</subfield>
    </datafield>
```

but no `024`
