### ISSUE TITLE
Miscellaneous is the only english medium label

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1441]
https://github.com/hbz/lobid-resources/blob/2ae7b86259115ee3fa8693e3ba16ebda2739ca54/src/main/resources/alma/fix/maps.fix#L31-L45

Should we change this to "Sonstige"? Has this consequences for the GUI?

**Comment by acka47** [comment]
This makes sense, although it is only seen in the data, lobid.org already shows "Sonstige" in the HTML (filter section, detail view). So please go ahead and change it.

**Comment by acka47** [comment]
> Has this consequences for the GUI?

Now as the GUI is configured based on the URI:

https://github.com/hbz/lobid-resources/blob/3ac007f560d62370f054055762e7d92904484790/web/conf/resources.conf#L85

Your proposed change would lead towards more consistency between UI and data.

**Comment by TobiasNx** [comment]
I see that this should be "Sonstige", not "Sonstiges". Damn.

**Comment by TobiasNx** [comment]
But we use "Sonstiges" also in HCRT: https://skohub.io/dini-ag-kim/hcrt/heads/master/w3id.org/kim/hcrt/other.de.html Perhaps this is something to be fixed in the Front-End.

**Comment by TobiasNx** [comment]
@acka47 should we use Sonstiges as in lobid resources GUI or Sonstige as in HCRT.
I would vote for the second but the frontend label would have to be changed.

**Comment by acka47** [comment]
>  should we use Sonstiges as in lobid resources GUI or Sonstige as in HCRT.

I don't care evry much. So I suggest we just stick with "Sonstiges".

**Comment by dr0i** [comment]
This wasn't autoclosed. Closable?

**Comment by acka47** [comment]
Closing

**Comment by gregorbg** [comment]
Not sure if this is related, but http://lobid.org/resources/HT018678515.json yields `Sonstiges` directly under `type` where I believe it should be `Miscellanous`.

Completely wild guess: You had a transformation somewhere that turned "Sonstiges" into "Miscellanous" but overlooked it when changing "Sonstiges" to "Sonstige"??

**Comment by gregorbg** [comment]
Here's a grep over our entire "Bestand" in case you need more samples for debugging :)
https://pastebin.com/LrbfZ4mM

**Comment by gregorbg** [comment]
Ah, I wasn't aware that you will be making a hard switch by that time already. Thanks for the reply! Of course I can live with the interim state for this short amount of time. In that case: Yippie and nevermind 😃

**Comment by acka47** [comment]
> I wasn't aware that you will be making a hard switch by that time already.

Yes, we haven't made a good job communicating this. We will have to blog it and send it around Mastodon, the mailing list etc. @TobiasNx can you create an issue for this?
