### ISSUE TITLE
Exlude Reviews as Abstracts

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1442]
https://github.com/hbz/lobid-resources/blob/2ae7b86259115ee3fa8693e3ba16ebda2739ca54/src/main/resources/alma/fix/otherFields.fix#L97-L103

We include Reviews as abstracts, shouldn't we exclude them from `abstract[]`
For further MARC info see: https://www.loc.gov/marc/bibliographic/bd520.html

**Comment by acka47** [comment]
It is probably better to exclude them. It would be interesting to know how many resources have a review so that we could think about whether we should include reviews in another way.

**Comment by TobiasNx** [comment]
Resolved with https://github.com/hbz/lobid-resources/pull/1593
