### ISSUE TITLE
Use extent from limetrans

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1443]
https://github.com/hbz/lobid-resources/blob/2ae7b86259115ee3fa8693e3ba16ebda2739ca54/src/main/resources/alma/fix/otherFields.fix#L21-L86

Our old transformation for extent was very basic, only copied a string. Limetrans has a more advanced version that also normalizes the info. We adapted the limetrans transformation, should we keep it?

**Comment by acka47** [comment]
Without understanding the details, this looks good to me. If people complain, we can still change it. Closing.
