### ISSUE TITLE
Distinguish PublicationEvent and SecondaryPublicationEvent?

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1446]
https://github.com/hbz/lobid-resources/blob/67b55015a380e68bf1d15dbb4374f0e32a40929d/src/main/resources/alma/fix/titleRelatedFields.fix#L58-L122

TODO is there a way to distinguish PublicationEvent and SecondaryPublicationEvent?

**Comment by acka47** [comment]
The issue descritpion is very sparse and the link leads to a 404. Please provide examples, @TobiasNx,  so that I can comment.

**Comment by TobiasNx** [comment]
Old morph:
https://github.com/hbz/lobid-resources/blob/412a8b4f142958199afc410ef380b2e45ab2755e/src/main/resources/morph-hbz01-to-lobid.xml#L2716-L2758

Fix:
https://github.com/hbz/lobid-resources/blob/412a8b4f142958199afc410ef380b2e45ab2755e/src/main/resources/alma/fix/titleRelatedFields.fix#L48-L94

**Comment by TobiasNx** [comment]
Replaced by: #1485
