### ISSUE TITLE
Exclude Slide/Dia and Transparency from Medium Video

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1448]
https://github.com/hbz/lobid-resources/blob/2ae7b86259115ee3fa8693e3ba16ebda2739ca54/src/main/resources/alma/fix/mediumAndType.fix#L97-L131

Slide/Dia and Transparency are transformed to Medium Video/Audio-Visuell.
I would suggest to exclude these. But how do we include them?

**Comment by acka47** [comment]
I don't know. As this is a more detailed question about a very small part of lobid-resources, we should not use much time for a discussion. As nobody has objected yet we can also just leave it as is.

**Comment by TobiasNx** [comment]
Closing since noone complained.
