### ISSUE TITLE
Should Kit and MixedMaterial always be sorted as medium Print?

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1449]
https://github.com/hbz/lobid-resources/blob/2ae7b86259115ee3fa8693e3ba16ebda2739ca54/src/main/resources/alma/fix/mediumAndType.fix#L157-L186

For Marc-Info see: https://www.loc.gov/marc/bibliographic/bdleader.html

**Comment by acka47** [comment]
Short answer to the question in the issue title: No. (And I can not recall why this was configured like so in the first place.)

**Comment by TobiasNx** [comment]
Deleted the comments with https://github.com/hbz/lobid-resources/pull/1579 . We do not map Kit or MixedMaterial to Print by default.
