### ISSUE TITLE
Should we include more microformats?

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1451]
https://github.com/hbz/lobid-resources/blob/ac8c976fa7f19b32adc2261d9623b0dc3a3190c7/src/main/resources/alma/fix/mediumAndType.fix#L226-L253

338  .b has more versions than only Microfich

**Comment by acka47** [comment]
As this is a quite detailed question about a very small part of lobid-resources, we should not use much time for a discussion. As nobody has objected yet, I suggest we just leave it as is.

**Comment by acka47** [comment]
Closing
