### ISSUE TITLE
Remote Access as online ressource?

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1453]
TODO: Old Morph also sets remote access as online ressource (050/8/1=g=Computerdatei(en) im Fernzugriff and 058.) Our ALMA-Transformation does not, how should we proceed.

https://github.com/hbz/lobid-resources/blob/ac8c976fa7f19b32adc2261d9623b0dc3a3190c7/src/main/resources/alma/fix/mediumAndType.fix#L274-L294

**Comment by acka47** [comment]
As nobody complained, I'd say we should implement it as for Aleph.
