### ISSUE TITLE
No transformation for "MultiVolumeBook"

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1456]
https://github.com/hbz/lobid-resources/blob/ac8c976fa7f19b32adc2261d9623b0dc3a3190c7/src/main/resources/alma/fix/mediumAndType.fix#L551-L556

**Comment by TobiasNx** [comment]
It seems that leader 07 m and 19 a could be a marker for a MultiVolumeBook (https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=483000321  -mapping for 051/0)

**Comment by dr0i** [comment]
Closed with #1573.
