### ISSUE TITLE
MapperParsingException: URI instead of String for publication.location

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1464]
We got new data where the place of publication is a URI, e.g.
https://lobid.org/hbz01/HT021519082 (419 1.a), which is nice but breaks our definition of this type of field (must be String, is a URI).
ES complains with a  `MapperParsingException` and the document is not indexed, see [/HT021519082](http://lobid.org/resources/HT021519082).

This also may affect ALMA data.

**Comment by dr0i** [comment]
@TobiasNx this would also be a problem if such data appears in ALMA (-> `titleRelatedFields.fix`). You may want to provide a fix for the Fix.

**Comment by dr0i** [comment]
Checked ALMA (Morph and Fix), no probs here.

**Comment by dr0i** [comment]
To be checked at Thursday.

**Comment by TobiasNx** [comment]
@dr0i did you check?

**Comment by dr0i** [comment]
Strange - there is no more a `MapperParsingException`in the logs  but the data is still missing in all indices:
http://lobid.org/resources/search?q=HT021519082 and http://alma.lobid.org/resources/search?q=HT021519082&format=json and http://test.lobid.org/resources/search?q=HT021519082&format=json.
Only the MabXML source was indexed: https://lobid.org/hbz01/HT021519082

**Comment by dr0i** [comment]
Ah [HT021519082 was deleted on 2022-10-15](https://lobid.org/resources/deletions/search?q=HT021519082%20AND%20describedBy.deleted%3A[20221001+TO+20221025]) - praise the deletion API !

So I think we are on the safe side anyway (no more MPE). Closing.
