### ISSUE TITLE
Alma Fix: URIs falsely in lat/lon field

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1471]
Results from https://github.com/hbz/lobid-resources/pull/1458:

>    [602]: index [resourcestest-alma-fix-20221010-1552], type [resource], id [990364455390206441], message [MapperParsingException[failed to parse]; nested: ElasticsearchParseException[[lat] and [lon] must be valid double values]; nested: NumberFormatException[For input string: "https://nwbib.de/spatial#Q2112"];]

So it seems that for lat or lon _often_ the URI is inserted, and ES denies indexing of this.

**Comment by dr0i** [comment]
Wait, this may well be because `nwbib-spatial.tsv` couldn't be found at the server. Assigning myself.

**Comment by dr0i** [comment]
After fixing the path (#1472), so that `nwbib-spatila.tsv` can be resolved, there are still some errors, like:

> [136]: index [resourcestest-alma-fix-20221010-1552], type [resource], id [99370768456106441], message [MapperParsingException[failed to parse]; nested: ElasticsearchParseException[[lat] and [lon] must be valid double values]; nested: NumberFormatException[For input string: "https://nwbib.de/spatial#N43"];]
[1650]: index [resourcestest-alma-fix-20221010-1552], type [resource], id [990110714900206441], message [MapperParsingException[failed to parse]; nested: ElasticsearchParseException[[lat] and [lon] must be valid double values]; nested: NumberFormatException[For input string: "http://www.wikidata.org/entity/Q1374337"];]

Do you have a clue @TobiasNx ?

**Comment by TobiasNx** [comment]
This seems to be a problem since the values that should be looked up are not part of https://github.com/hbz/lobid-resources/blob/317e36a4e8cb4ba251c91673c9aa2e9558baf50d/src/main/resources/wd_itemLabelTypesCoordinates.tsv

**Comment by TobiasNx** [comment]
Had a talk with @dr0i. We assumed that this is also broken in ALEPH-ALMA:
https://lobid.org/resources/BT000024700.json

It seems that https://github.com/hbz/lobid-resources/blob/317e36a4e8cb4ba251c91673c9aa2e9558baf50d/src/main/resources/wd_itemLabelTypesCoordinates.tsv has not been updated in a longer time.

**Comment by dr0i** [comment]
See https://github.com/hbz/nwbib/issues/570#issuecomment-889746463 on how this file is build.

**Comment by dr0i** [comment]
The question "how is the `[wd_itemLabelTypesCoordinates.tsv](https://github.com/hbz/lobid-resources/blob/317e36a4e8cb4ba251c91673c9aa2e9558baf50d/src/main/resources/wd_itemLabelTypesCoordinates.tsv)` build still remains unanswered for running `getTypeAndCoordinatesFromWikidata.sparql` only reveals `164` as opposed to the `9k` atm.
However, adjusting the sparql to get every Wikidata entry typed as `NWBid` we get `4.5k` entries, i.a. the missing one:
> http://www.wikidata.org/entity/Q1374337,Euregio,http://www.wikidata.org/entity/Q153026

would this be ok?

**Comment by TobiasNx** [comment]
Would be solved by https://github.com/hbz/lobid-resources/issues/1473

**Comment by dr0i** [comment]
made some checks:
- all 164 entries of getTypeAndCoordinatesFromWikidata.sparql are also present in the new SPARQL result besides these four: Q645030, Q14551680, Q316174 and Q993449 (all rather edge case lacking a NWBid)
- these have two times lat/lon : Q109773,Q2011523,Q109773,Q152356,Q2011523,Q152356

Lots of old WD resource, while  part of `wd_itemLabelTypesCoordinates.tsv`, are missing in the newly generated  4539 (i.e. 8997 - 4539). But that's ok, for as they are not part of nwbib following https://nwbib.de/spatial they are not needed.

**Comment by dr0i** [comment]
Note that https://github.com/hbz/lobid-resources/issues/1471#issuecomment-1277555645:
> We assumed that this is also broken in ALEPH-ALMA. In fact it is broken or better it is missing lon/lat-Elements in spatial: https://lobid.org/resources/BT000024700.json


is not true in that it is _not_ broken - the [coordinates are (still) not notated in wikidata](https://www.wikidata.org/wiki/Q1374337), maybe because it's a too broad of a region. So these coordinates will be missing even after using the new mechanisam of getting the data.

**Comment by dr0i** [comment]
https://test.lobid.org/resources/search?q=990364455390206441&format=json works now, but >9k are still failing with MPE, e.g. https://test.lobid.org/resources/search?q=990112086220206441&format=json (compare with https://alma.lobid.org/resources/search?q=990112086220206441&format=json).

**Comment by TobiasNx** [comment]
> https://test.lobid.org/resources/search?q=990364455390206441&format=json works now, but >9k are still failing with MPE, e.g. https://test.lobid.org/resources/search?q=990112086220206441&format=json (compare with https://alma.lobid.org/resources/search?q=990112086220206441&format=json, where it's also missing - while `geo` exists in https://lobid.org/resources/search?q=BT000162603&format=json).

This seems not a problem by the geo-data but by `type`:
```
"spatial" : [ {
    "id" : "https://nwbib.de/spatial#Q2112",
    "label" : "Bielefeld",
    "type" : [ "Concept" ],
    "source" : {
      "id" : "https://nwbib.de/spatial",
      "label" : "Raumsystematik der Nordrhein-Westfälischen Bibliographie"
    }
  }, {
    "focus" : {
      "id" : "http://www.wikidata.org/entity/Q2112",
      "label" : "Bielefeld",
      "type" : [ "Bielefeld,\"http://www.wikidata.org/entity/Q1187811, http://www.wikidata.org/entity/Q262166, http://www.wikidata.org/entity/Q22865, http://www.wikidata.org/entity/Q1549591, http://www.wikidata.org/entity/Q42744322, http://www.wikidata.org/entity/Q1964689, http://www.wikidata.org/entity/Q707813\",Point(8.533333333 52.016666666)" ],
      "geo" : {
        "lat" : "8.533333333",
        "lon" : "52.016666666"
      }
    }
  } ],
```

**Comment by TobiasNx** [comment]
This is the source of the error:
https://github.com/hbz/lobid-resources/blob/15c79a23997206502ce8d165c1658e25bcc12dad/src/main/resources/wd_itemLabelTypesCoordinates.tsv#L5033-L5034

**Comment by TobiasNx** [comment]
> I think there is an error in the current `spatial` data structure: the `focus` object currently is a direct member of the `spatial` array, but it should be inside each of the other members of the `spatial` array. See e.g. http://test.lobid.org/resources/99371527702306441.json where the `focus` for Köln should be a field in the first `spatial` object, not an object of its own.

@acka47  hinted to that too. It should be fixed with #1496 and #1497

**Comment by TobiasNx** [comment]
> https://test.lobid.org/resources/search?q=990364455390206441&format=json works now, but >9k are still failing with MPE, e.g. https://test.lobid.org/resources/search?q=990112086220206441&format=json (compare with https://alma.lobid.org/resources/search?q=990112086220206441&format=json, where it's also missing - while `geo` exists in https://lobid.org/resources/search?q=BT000162603&format=json).

Is this still a problem?

**Comment by dr0i** [comment]
No MPE anymore - all other observatiosn are still true. What to make of this?

**Comment by dr0i** [comment]
Many MPE's here, e.g.:
> 2022-11-08 10:20:41 WARN [org.lobid.resources.ElasticsearchIndexer.process(ElasticsearchIndexer.java:242)] - Bulk insert failed: failure in bulk execution:
[45]: index [resources-alma-fix-20221106-1200], type [resource], id [990197085920206441], message [MapperParsingException[failed to parse]; nested: ElasticsearchParseException[[lat] and [lon] must be valid double values]; nested: NumberFormatException[For input string: "Wittgensteiner Land,http://www.wikidata.org/entity/Q82794,"];]

**Comment by TobiasNx** [comment]
NWBIB changed 41 entries of ZDB yesterday by hand. Could this changes be the source of the error?

**Comment by dr0i** [comment]
Hm, probably, as the mentioned resource was updated yesterday AND is part of NWbib (http://alma.lobid.org/resources/search?q=990197085920206441&format=json). Going to investigate further.

**Comment by acka47** [comment]
> NWBIB changed 41 entries of ZDB yesterday by hand. Could this change be the source of the error?

Looks like it to me. Here ist the list of those 41 resources: https://gist.github.com/acka47/ca834888e08669c58a8ab94571849b3c

**Comment by dr0i** [comment]
Geo data is missing in `wd_itemLabelTypesCoordinates.tsv` because it's missing in http://www.wikidata.org/entity/Q881875.
Tracing:
```xml
<datafield tag="084" ind1=" " ind2=" ">
<subfield code="a">Wittgensteiner Land</subfield>
<subfield code="0">https://nwbib.de/spatial#N18</subfield>
```
invokes a lookup in `nwbib-spatial.tsv` where it maps to:
> :https://nwbib.de/spatial#N18  Wittgensteiner Land|18|http://www.wikidata.org/entity/Q881875

which incokes a lookup of `http://www.wikidata.org/entity/Q881875`  in `wd_itemLabelTypesCoordinates.tsv`:
> wd_itemLabelTypesCoordinates.tsv:http://www.wikidata.org/entity/Q881875 Wittgensteiner Land,http://www.wikidata.org/entity/Q82794,

and there the geo data is missing. That's because in the Wikidata it's missing for http://www.wikidata.org/entity/Q881875.

We _could_ try to build the `wd_itemLabelTypesCoordinates.tsv` correctly (i.e. not adding entries which lack  geo data) _or_ (my favourite) treat it in Fix when there is no geo data (e.g. missing prefix of "Point(" when parsing geo data ). I favour this  because:
a) it's easier to do (supposedly)
b) it's more robust (all kind of data errors can occur)
c) we have a `wd_itemLabelTypesCoordinates.tsv` where we can find easily Wikidata entries laking geo data (so maybe to add them in Wikidata)

I looks like there is already a proper parsing of "Point" (see https://github.com/hbz/lobid-resources/blob/c7680d39e88d4ea5d92245465d9284910e8f9e27/src/main/resources/alma/fix/subjects.fix#L235  ) but maybe there is something wrong?
Could you do that @TobiasNx ?

**Comment by TobiasNx** [comment]
Seems to be fixed! http://test.lobid.org/resources/99371527702306441.json
