### ISSUE TITLE
Add RPB Vocabs to ALMA-Fix

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1478]
@acka47 noticed [here](https://github.com/hbz/lobid-resources/pull/1461) that RPB should already be included in FIX:

>The classification called "Rheinland-Pfälzische Bibliographie" we do have a SKOS version at https://w3id.org/lobid/rpb2.
>However, this actually is not related to RPB, see https://jira.hbz-nrw.de/browse/RPB-7 where it reads:
> >Bei der Systematik https://w3id.org/lobid/rpb2, die derzeit "RPB-Sachgruppen und Zusätze" heißt, handelt es sich um LBZ-Fachnotation, die mit der RPB eigentlich gar nichts zu tun haben.

>There obviously went something wrong in the past that this is associated with RPB at different places. However, we can add those URIs in the `id` field in lobid.

**Comment by TobiasNx** [comment]
When the SKOS Look Up in metafacture fix works, we could use this here.

**Comment by TobiasNx** [comment]
Blocked by https://github.com/hbz/lobid-resources/issues/1622

**Comment by acka47** [comment]
Edoweb customers noticed missing notations in their metadatan, see https://jira.hbz-nrw.de/browse/EDOZWO-1133.

This is the example resource they mention: https://lobid.org/resources/99372423567906441

The [MARC source]() contains this:

```xml
<datafield tag="084" ind1=" " ind2=" ">
  <subfield code="a">rpbr_01_</subfield>
  <subfield code="2">rpb</subfield>
</datafield>
<datafield tag="084" ind1=" " ind2=" ">
  <subfield code="a">rpb547600</subfield>
  <subfield code="2">rpb</subfield>
</datafield>
<datafield tag="084" ind1=" " ind2=" ">
  <subfield code="a">147</subfield>
  <subfield code="2">rpb</subfield>
</datafield>
<datafield tag="084" ind1=" " ind2=" ">
  <subfield code="a">131</subfield>
  <subfield code="2">rpb</subfield>
</datafield>
<datafield tag="084" ind1=" " ind2=" ">
  <subfield code="a">106</subfield>
  <subfield code="2">rpb</subfield>
</datafield>
<datafield tag="084" ind1=" " ind2=" ">
  <subfield code="a">139</subfield>
  <subfield code="2">rpb</subfield>
</datafield>
<datafield tag="084" ind1=" " ind2=" ">
  <subfield code="a">650</subfield>
  <subfield code="2">rpb</subfield>
</datafield>
```

There are three classifications provided by LBZ (the "RPB2" one being incorrectly labeled as it is not used for RPB):

- RPB-Sachsystematik: https://github.com/hbz/lobid-vocabs/blob/master/rpb/rpb.ttl
- RPB-Raumsystematik: https://github.com/hbz/lobid-vocabs/blob/master/rpb/rpb-spatial.ttl
- RPB2 (which is not a RPB classification and should  be renamed): https://github.com/hbz/lobid-vocabs/blob/master/rpb/rpb2.ttl

Here is the mapping:

- notations with prefix `rpb` followed by six digits are mapped to the Sachsystematik (rpb.ttl) (e.g. `rpb547600` -> `http://purl.org/lobid/rpb#n54760`)
- notations with `rpbr` prefix are mapped to the Raumsystematik (e.g. `rpbr_01_` -> `https://rpb.lobid.org/spatial#n01`)
- notations with three digits are mapped to `rpb.ttl` (`106` -> `https://w3id.org/lobid/rpb2#n106`)

I am not sure that the labels are needed. as we can get them easily via a SKOS lookup we can just add them.

**Comment by acka47** [comment]
We should use these IDs amd labels in the source object:

- RPB-Sachsystematik: http://purl.org/lobid/rpb, RPB-Sachsystematik
- RPB-Raumsystematik: https://rpb.lobid.org/spatial, RPBRaumsystematik
- RPB2: https://w3id.org/lobid/rpb2 (I will ask in JIRA about the correct label)

**Comment by acka47** [comment]
To not introduce a breaking change I took a look at an old test file to see the ETL output we had with Aleph data. Looks exactly as we would do it now (except for the updated labels):

```json
"subject" : [ {
    "id" : "http://purl.org/lobid/rpb#n574040",
    "source" : {
      "id" : "https://w3id.org/lobid/rpb",
      "label" : "Systematik der Rheinland-Pfälzischen Bibliographie"
    },
    "notation" : "574040",
    "label" : "Straßenbau"
  }, {
    "id" : "https://w3id.org/lobid/rpb2#n940",
    "source" : {
      "id" : "https://w3id.org/lobid/rpb2",
      "label" : "RPB-Sachgruppen und Zusätze"
    }
```
