### ISSUE TITLE
ALMA-Fix: `webPageArchived`

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1486]
Derivative of #1475  

https://github.com/hbz/lobid-resources/blob/5f3195e6916d13b43eae03f684a41ea6d31f381b/src/main/resources/morph-hbz01-to-lobid.xml#L6886-L6903

@dr0i it seems that you wrote this code and comment, could you help where I find the info if a ressource is of type "webPageArchived"?

**Comment by dr0i** [comment]
From the [morph](https://github.com/hbz/lobid-resources/blob/master/src/main/resources/morph-hbz01-to-lobid.xml#L1693):
``` 		
<data source="051." name="@archived">
  <regexp match="^.w" format="$[ns-lobid-vocab]ArchivedWebPage"/>
</data>
```

There are some test files covering this, e.g. http://lobid.org/resources/HT019248596.json . Maybe you can trace it from there.

**Comment by TobiasNx** [comment]
Mapping ALEPH MAB to ALMA MARC does not seem to support this element anymore:
https://service-wiki.hbz-nrw.de/display/VDBE/ALT+-+Mapping+MAB2+-+MARC+21+-++Segmente+0---%2C+001+-+088+-+Kurzform

51/1-3/3=w Website has no corresponding value.

Need to find another indicator here.
