### ISSUE TITLE
MapperParsingException: lat/lon

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1506]
From the lobid morph logs:

>log/20221102-041501.log.startHbz00ToLobidResources.sh:[1507]: index [resources-20221030-0030], type [resource], id [HT019377994], message [MapperParsingException[failed to parse]; nested: ElasticsearchParseException[field must be either [lat], [lon] or [geohash]];]
log/20221102-0030-stage.startHbz02ToLobidResources.sh:[1930]: index [resources-20221102-0030], type [resource], id [HT019061477], message [MapperParsingException[failed to parse]; nested: ElasticsearchParseException[field must be either [lat], [lon] or [geohash]];]

Don't know exactly where this lat/lon error comes from - is it the `700n10https://nwbib.de/subjects#N530100` where the problem is #N530100? Where is this looked up?

**Comment by TobiasNx** [comment]
The data is not migrated correctly, the info should be noted in Element `084`: https://www.loc.gov/marc/bibliographic/bd084.html
700 is for contributors https://www.loc.gov/marc/bibliographic/bd700.html

**Comment by dr0i** [comment]
> the info should be noted in Element 084

no, I think the `700` is especially designed for nwbib krimskrams.
Hm,  I fear the need of a deeper look ... going to debug.

**Comment by dr0i** [comment]
Also, there are _two_ (redundant) geo coordinates, while https://www.wikidata.org/wiki/Q152243 only shows _one_.

**Comment by acka47** [comment]
AFAICS, only two resources are affected, the one above (HT019377994) and HT019061477.

From [HT019061477 XML](http://lobid.org/hbz01/HT019061477):

```xml
<datafield tag="700" ind1="n" ind2="1">
<subfield code="a">Rheinland</subfield>
<subfield code="0">https://nwbib.de/spatial#N03</subfield>
</datafield>
<datafield tag="700" ind1="n" ind2="1">
<subfield code="a">Rheinland</subfield>
<subfield code="0">https://nwbib.de/spatial#Q152243</subfield>
</datafield>
```

**Comment by dr0i** [comment]
And this is roughly the way how this issue was introduced:
After the [import of the new ZDB data](https://github.com/hbz/nwbib/issues/465#issuecomment-1286778489) there is:
> 2865203-4	"Rheinland$$0https://nwbib.de/spatial#N03", "Rheinland$$0https://nwbib.de/spatial#Q152243"

These strange (and superflous if not false) entries , denoting the same entity (after dereferencing of `#N03`), come from the old morph ETLed index (where the geo object was not broken but rather had two (one of them superflous) independent geo objects.  This happened because there were multiple ways of creating geo data (by using [wd_itemLabelTypesCoordinates.tsv](https://github.com/hbz/lobid-resources/blob/master/src/main/resources/wd_itemLabelTypesCoordinates.tsv) if a QID is present and by using the geo_nwbib cache if only coverage data existed to _gain_ the QID).) 

Now, enriching of the catalog with the ZDB import  (by querying the old morph based aleph index) we got the QID ( besides that the nwbib spatial ID) in the catalog.
A new ETL  lookups `https://nwbib.de/spatial#Q152243` in [wd_itemLabelTypesCoordinates.tsv](https://github.com/hbz/lobid-resources/blob/master/src/main/resources/wd_itemLabelTypesCoordinates.tsv) => geo data,  _and_ it looks up `https://nwbib.de/spatial#N03` in [nwbib-spatial.tsv](https://github.com/hbz/lobid-resources/blob/master/src/main/resources/nwbib-spatial.tsv) where `https://nwbib.de/spatial#N03` is substituted by `http://www.wikidata.org/entity/Q152243`. Now there are _two_ geo objects with the same ID, resulting in the strange _bnodes_ ("objects").
As only two IDs are affected theses could be manually fixed in the catalog.

**Comment by dr0i** [comment]
Thx - looks good now:
https://test.lobid.org/resources/search?q=HT019377994&format=json.
Closing.
