### ISSUE TITLE
Institution Lookup for ITM is broken.

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1526]
Uh, doesnot work on server:
>  Error while executing Fix expression (at file:/home/sol/git/lobid-resources-test/web/target/universal/stage/conf/alma/fix/item.fix, line 58): lookup("hasItem[].$last.heldBy.id", "alma-institution-code-to-isil")
org.metafacture.metamorph.api.MorphExecutionException: File not found: conf/alma/./maps/institutions.tsv

_Originally posted by @dr0i in https://github.com/hbz/lobid-resources/issues/1520#issuecomment-1326142143_
      

Diskussed this, for now we should use a variable. Next time we should have a look why our FIX does not work with the dot-notation for the path.

**Comment by TobiasNx** [comment]
Seems to be live: http://test.lobid.org/resources/990112775700206441.json

**Comment by dr0i** [comment]
Great, the let's close this.
