### ISSUE TITLE
Special character # in field language

### ISSUE THREAD

**Issue by UBmakla** [hbz/lobid-resources#1530]
Hi,

in some cases (e.g. 990057975940206441 and 990063455990206441) there are ### instead of the language specification. It may be because in MARC field 008 it looks the same. The correct language specification is contained in field 040.b. Can you do something about it?
Thanks a lot!

**Comment by TobiasNx** [comment]
Hi thanks for the hint. One thing: `040 $$b` https://www.loc.gov/marc/bibliographic/bd040.html is the language for the cataloguing record not the resource. That should be `041` https://www.loc.gov/marc/bibliographic/bd041.html we use `$$a`, `$$d` and `$$j` and also the language code in `008`.

It seems that the lookup needs the option: `delete:"true"`:
https://github.com/hbz/lobid-resources/blob/f05606ed30f88ad9ac16045525818d403560e529/src/main/resources/alma/fix/otherFields.fix#L17-L18

**Comment by TobiasNx** [comment]
Hi Manuela,
it seems that the Bug does not exist in ALMA-Fix. Also both entries do not provide language info.

Since we do not plan to change ALMA-Morph anymore, would it be okay for you to wait for this until you switch to ALMA-Fix too?

**Comment by TobiasNx** [comment]
@UBmakla can this be closed?

**Comment by UBmakla** [comment]
Hi,
thanks for your answer and yes, it is okay for us to wait until Fix.
