### ISSUE TITLE
Add deprecatedUri statements for hbzIds

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#1535]
Originates from https://github.com/hbz/lobid-resources/issues/1433.

@acka47 [wrote](https://github.com/hbz/lobid-resources/issues/1433#issuecomment-1326562109):
> we should add a [dnb:deprecatedUri](https://d-nb.info/standards/elementset/dnb#deprecatedUri) statement to each resource that indicates the old URI e.g. for the example resource (in N-Triples): <http://lobid.org/resources/99370849894106441#!> <https://d-nb.info/standards/elementset/dnb#deprecatedUri> "https://test.lobid.org/resources/HT020968842#!" .

@TobiasNx [wrote](https://github.com/hbz/lobid-resources/issues/1433#issuecomment-1327280320):
>Should we add deprecatedUri to all ressources that have HT-Numbers? In my opinion It would be difficult to differentiate between records prior and after the switch to ALMA-Fix. And this would be the easier way.

**Comment by acka47** [comment]
See https://github.com/hbz/lobid-resources/issues/1433#issuecomment-1337529289
