### ISSUE TITLE
ALMA-Fix: nwbib without explicit URI

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1542]
https://test.lobid.org/resources/search?q=subject.source.id%3A%22nwbib%22

When introducing new classifications I found a 800+ entries with faulty nwbib subject entries in `084`. Reason for that seems to be that they have no nwbib-URI just the classification OR the some mixture. Even some old spatial entries.

https://test.lobid.org/resources/990205221730206441.json

```
    {
      "notation": "582000",
      "type": [
        "Concept"
      ],
      "source": {
        "label": "nwbib",
        "id": "nwbib"
      }
    },
```   

https://test.lobid.org/resources/990227427410206441.json

```
    {
      "notation": "Mundartenhttps://nwbib.de/subjects#N744000",
      "type": [
        "Concept"
      ],
      "source": {
        "label": "nwbib",
        "id": "nwbib"
      }
    }
 ```

https://test.lobid.org/resources/990364878140206441.json

```
   {
      "notation": "Heilige. Heiligenverehrung ; https://nwbib.de/subjects#N611090",
      "type": [
        "Concept"
      ],
      "source": {
        "label": "nwbib",
        "id": "nwbib"
      }
    }
```

https://test.lobid.org/resources/99370684055406441.json

```
   {
      "notation": "99 ; Bonn",
      "type": [
        "Concept"
      ],
      "source": {
        "label": "nwbib",
        "id": "nwbib"
      }
    },
    {
      "notation": "794010",
      "type": [
        "Concept"
      ],
      "source": {
        "label": "nwbib",
        "id": "nwbib"
      }
    }
```

**Comment by acka47** [comment]
For the record, only one of thee examples is a ZDB resource: https://test.lobid.org/resources/990205221730206441.json

Generally, [all of the 872 resources are part of NWBib](inCollection.id:("http://lobid.org/resources/HT014846970#!" AND "http://lobid.org/resources/HT014176012#!") but only [258 are also in ZDB](https://test.lobid.org/resources/search?q=subject.source.id%3A%22nwbib%22+AND+inCollection.id%3A%28%22http%3A%2F%2Flobid.org%2Fresources%2FHT014846970%23%21%22+AND+%22http%3A%2F%2Flobid.org%2Fresources%2FHT014176012%23%21%22%29) 

So, the recent ZDB update (https://github.com/hbz/nwbib/issues/465) does not seem the (main) root of this problem.

**Comment by acka47** [comment]
I think all these entries use notations/URIs that do not exist in the classifications, see also https://github.com/hbz/nwbib/issues/595. Will discuss with NWBib editors how to proceed.

**Comment by TobiasNx** [comment]
@acka47 can we close this ticket? since it will be resolved in https://github.com/hbz/nwbib/issues/595

**Comment by acka47** [comment]
Ok. Closing.
