### ISSUE TITLE
Missing Aleph resources

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1551]
Reported today by @aquast via email:

On 16.12.22 09:19, A. Q. wrote:
> ZB MED berichtet, dass das Aleph-Publishing anscheinend wieder steht. 
> Verschiedenen neue Titeldaten sind nicht in lobid angekommen.
> 
> Beispiele:
> 
> HT021659083
> HT021659084
> HT021659085
> HT021659086
> HT021661423

**Comment by dr0i** [comment]
Mail von S.Sch. :
> aufgrund des Ex libris-Fehlers bezüglich "GND" mussten wir das 
Publishing der Bestände aus Alma nach Aleph abschalten

**Comment by dr0i** [comment]
ping @aquast

**Comment by dr0i** [comment]
Da können wir nichts machen. Closing.

**Comment by dr0i** [comment]
Die Daten sind wohl prinzipiell in Aleph, aber nicht über die Update-Schnittstelle exportiert worden.
Spätestens am Sonntag sollte dann alle Daten im Index sein, da am Samstag ein Vollabzug gemacht wird.

**Comment by blackwinter** [comment]
> Spätestens am Sonntag sollte dann alle Daten im Index sein, da am Samstag ein Vollabzug gemacht wird.

Only if the publishing process has caught up by then. Do you have any new information? I haven't received an answer to my e-mail yet.

**Comment by dr0i** [comment]
As S.Sch told just told us in an Email the data publishing will be completed at the Weekend.
Will check this at Monday.

**Comment by dr0i** [comment]
Data now available, see e.g. https://lobid.org/resources/HT021659085.
Wrote an email to inform stakeholders.
Closing.
