### ISSUE TITLE
ALMA-Fix: Only use content not carrier subjects for `natureOfContent`

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1553]
`natureOfContent` describes the content and not the carrier. But `655` also provides info for `carrier`. Also some old Formschlagwörter are carrier instead of content describing e.g. Film 16mm.

We should get a list of all values and filter out, what carriers we want to exclude.

**Comment by TobiasNx** [comment]
I could introduce this  conditional but I have no example:      `unless any_match("$i.a",".*(Audiovisuelles Material|Bildplatte|CD|CD-ROM|Dia|Diskette|DVD-Audio|DVD-ROM|DVD-Video|Elektronische Publikation|Film|Medienkombination|Mikroform|Musikdruck|Online-Publikation|Schallplatte|Text|Tonbildreihe|Tonkassette|Tonträger|Videokassette).*")`

**Comment by TobiasNx** [comment]
therefore would close if #1663 is deployes

**Comment by dr0i** [comment]
Unassigning me. If https://github.com/hbz/lobid-resources/pull/1663 is deployed and everything is fine @TobiasNx will close this issue.

**Comment by TobiasNx** [comment]
Yes done. Will open another ticket to reuse gnd carrier and old carrirer Formschlagwörter for medium
