### ISSUE TITLE
GND Altlabels from multiple subfields

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1556]
"almaMmsId" : "990206060640206441",
  "hbzId" : "HT018468645"

https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=nid%3D4219952-9

**Comment by dr0i** [comment]
Is this resolved with #1570 ?

**Comment by TobiasNx** [comment]
Resolved with #1588
