### ISSUE TITLE
Couple of issues from old Article PR

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1562]
Sorry, but this review led me down a rabbit hole. I think we have to take a step back and discuss the implementation also with regard to the `containedIn` property . Originally, we had created the property `containedIn` to be used only on resources of type `Article`. We created the `containedIn` property by ourselves to cover these use cases. From the property description (see http://purl.org/lobid/lv#containedIn):

> This property is used to link an article to a journal or an edited volume it is contained in.

Let's take a look at how `containedIn` is actually used.

## Problems in production lobid (Aleph, not to be fixed)

We apparently already got it wrong in the Aleph transformation as there are [354,375  resources with `containedIn` and without `"type": [ "Article" ]`](https://lobid.org/resources/search?q=_exists_%3AcontainedIn+AND+NOT+type%3AArticle&size=100). Skimming the results, I notice that `containedIn` is also used for musical scores in a collection of scores which also makes sense, I guess. 

So we take look at the [267,641 resources with `containedIn` and without type `Article` or `PublishedScore`](https://lobid.org/resources/search?q=_exists_%3AcontainedIn+AND+NOT+type%3A%28Article+OR+PublishedScore%29).  There are lots of resources in this list without an explicit type (i.e. [247,233 are of type `Miscellaneous`](https://lobid.org/resources/search?q=_exists_%3AcontainedIn+AND+NOT+type%3A%28Article+OR+PublishedScore%29+AND+type%3AMiscellaneous)). Looking at some examples, it seems like one could add type `Article` to them which would improve the data significantly. However, as we won't touch the old API, let's move on to the test API.

## The status in test.lobid.org/resources

Now, let's take a look at the status in the Alma-Fix transformation:

1. [639,455 resources with `containedIn` and without type `Article` or `PublishedScore`](https://test.lobid.org/resources/search?q=_exists_%3AcontainedIn+AND+NOT+type%3A(Article+OR+PublishedScore))
2. Many of the resources in 1.) are incorrectly typed as Book, see the list at [_exists_:containedIn AND NOT type:(Article OR PublishedScore)](https://test.lobid.org/resources/search?q=_exists_%3AcontainedIn+AND+NOT+type%3A%28Article+OR+PublishedScore%29+AND+type%3ABook)

There are some other types where `containedIn` also seems to make sense: `Map` ([example](https://test.lobid.org/resources/990197160910206441)), `Image` ([example](https://test.lobid.org/resources/990364910310206441)), `Report` ([example](https://test.lobid.org/resources/990110770560206441)). Filtering these out together with `Article` and `PublishedScore`, we get a list of [625,366 resources](https://test.lobid.org/resources/search?q=_exists_%3AcontainedIn+AND+NOT+type%3A%28Article+OR+PublishedScore+OR+Image+OR+PublishedScore+OR+Report%29) we should take a deeper look at.

## To Do

If I haven't overlooked anything, we should adjust the transformation so that it checks that **all resources with a `containedIn` statement are either of type `Article`, `PublishedScore`, `Map`, `Image` or `Report`**. (I might have missed a type here.)

## Some other strange things I noticed and we will probably need extra tickets for

* This resource is typed `EditedVolume` though it looks like an aticle to me: https://test.lobid.org/resources/990194221820206441 Actually, there are [38,834 resources of type `EditedVolume` with a `containedIn` statement](https://test.lobid.org/resources/search?q=_exists_%3AcontainedIn+AND+type%3AEditedVolume+AND+NOT+type%3A%28Article+OR+PublishedScore%29+) where we should take a look at.
* This volume used `containedIn` where `isPartOf` would be the correct relation: https://test.lobid.org/resources/99371066229606441
* There are  [ resources of type `Standard`]() where a larger amount should rather have another type, for example there are lots of Dictionaries in there, see [`type:Standard AND title:Wörterbuch`](https://test.lobid.org/resources/search?q=type%3AStandard+AND+title%3AW%C3%B6rterbuch)
*

_Originally posted by @acka47 in https://github.com/hbz/lobid-resources/issues/1476#issuecomment-1290177259_

**Comment by TobiasNx** [comment]
> ## The status in test.lobid.org/resources
> 
> Now, let's take a look at the status in the Alma-Fix transformation:
> 
>     1. [639,455 resources with `containedIn` and without type `Article` or `PublishedScore`](https://test.lobid.org/resources/search?q=_exists_%3AcontainedIn+AND+NOT+type%3A(Article+OR+PublishedScore))

https://test.lobid.org/resources/search?q=_exists_%3AcontainedIn+AND+NOT+type%3A(Article+OR+PublishedScore)
After the last changes this results only in 85,621 resources with `containedIn` and without type `Article` or `PublishedScore`

> 
>     2. Many of the resources in 1.) are incorrectly typed as Book, see the list at [_exists_:containedIn AND NOT type:(Article OR PublishedScore)](https://test.lobid.org/resources/search?q=_exists_%3AcontainedIn+AND+NOT+type%3A%28Article+OR+PublishedScore%29+AND+type%3ABook)

https://test.lobid.org/resources/search?q=_exists_%3AcontainedIn+AND+NOT+type%3A%28Article+OR+PublishedScore%29+AND+type%3ABook
After the last changes this results only in 895  resources with `containedIn` and without type `Article` or `PublishedScore` that have type Book.

> 
> 
> There are some other types where `containedIn` also seems to make sense: `Map` ([example](https://test.lobid.org/resources/990197160910206441)), `Image` ([example](https://test.lobid.org/resources/990364910310206441)), `Report` ([example](https://test.lobid.org/resources/990110770560206441)). Filtering these out together with `Article` and `PublishedScore`, we get a list of [625,366 resources](https://test.lobid.org/resources/search?q=_exists_%3AcontainedIn+AND+NOT+type%3A%28Article+OR+PublishedScore+OR+Image+OR+PublishedScore+OR+Report%29) we should take a deeper look at.

https://test.lobid.org/resources/search?q=_exists_%3AcontainedIn+AND+NOT+type%3A%28Article+OR+PublishedScore+OR+Image+OR+PublishedScore+OR+Report%29
After the last changes this results only in  68478 

> ## To Do
> 
> If I haven't overlooked anything, we should adjust the transformation so that it checks that **all resources with a `containedIn` statement are either of type `Article`, `PublishedScore`, `Map`, `Image` or `Report`**. (I might have missed a type here.)
> ## Some other strange things I noticed and we will probably need extra tickets for
> 
>     * This resource is typed `EditedVolume` though it looks like an aticle to me: https://test.lobid.org/resources/990194221820206441 Actually, there are [38,834 resources of type `EditedVolume` with a `containedIn` statement](https://test.lobid.org/resources/search?q=_exists_%3AcontainedIn+AND+type%3AEditedVolume+AND+NOT+type%3A%28Article+OR+PublishedScore%29+) where we should take a look at.

https://test.lobid.org/resources/search?q=_exists_%3AcontainedIn+AND+type%3AEditedVolume+AND+NOT+type%3A%28Article+OR+PublishedScore%29+
After the last changes this results only in  367  and example is not EditedVolume anymore. 


> 
>     * This volume used `containedIn` where `isPartOf` would be the correct relation: https://test.lobid.org/resources/99371066229606441

This example is for a part of a `Multivolumebook`. How do we differentiate between these and others?

> 
>     * There are   resources of type `Standard` where a larger amount should rather have another type, for example there are lots of Dictionaries in there, see [`type:Standard AND title:Wörterbuch`](https://test.lobid.org/resources/search?q=type%3AStandard+AND+title%3AW%C3%B6rterbuch)

@acka47 do you have an example for this. There seems to be only one hit for this.


> 
> 
> _Originally posted by @acka47 in [#1476 (comment)](https://github.com/hbz/lobid-resources/pull/1476#issuecomment-1290177259)_

**Comment by TobiasNx** [comment]
@acka47 can you have a look at my answers and lets discuss how to proceed here.

**Comment by acka47** [comment]
>  After the last changes this results only in 85,621 resources with containedIn and without type Article or PublishedScore

[55,445 of these are of type AudioDocument](https://test.lobid.org/resources/search?q=_exists_%3AcontainedIn+AND+NOT+type%3A%28Article+OR+PublishedScore%29+AND+medium.id%3A%22http%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2FAudioDocument%22), lots of them single tracks.

Generally, this looks good to me now. 

> https://test.lobid.org/resources/search?q=_exists_%3AcontainedIn+AND+NOT+type%3A%28Article+OR+PublishedScore%29+AND+type%3ABook
After the last changes this results only in 895  resources with `containedIn` and without type `Article` or `PublishedScore` that have type Book.

There are still [933 resources  with `containedIn` and type `Book`](https://test.lobid.org/resources/search?q=_exists_%3AcontainedIn+AND+type%3ABook) which is definitely incorrect. But I guess we can not get rid of those easily.

A general thought: We might think about adding some checks in the ETL to avoid conflicting `type` combinations, `medium` combinations and `type`-`medium` combinations...

> https://test.lobid.org/resources/search?q=_exists_%3AcontainedIn+AND+NOT+type%3A%28Article+OR+PublishedScore+OR+Image+OR+PublishedScore+OR+Report%29
After the last changes this results only in  68478 

Also excluding medium:AudioDocument, there are only around 13k left: https://test.lobid.org/resources/search?q=_exists_%3AcontainedIn+AND+NOT+type%3A%28Article+OR+PublishedScore+OR+Image+OR+PublishedScore+OR+Report%29+AND+NOT+medium.id%3A%22http%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2FAudioDocument%22

I assume most of these audio Documents are single audio tracks. Can we somehow identify those and add a specific type for them?

> https://test.lobid.org/resources/search?q=_exists_%3AcontainedIn+AND+type%3AEditedVolume+AND+NOT+type%3A%28Article+OR+PublishedScore%29+
> After the last changes this results only in  367  and example is not EditedVolume anymore. 

Great, that is a number we can tolerate.

> This example is for a part of a `Multivolumebook`. How do we differentiate between these and others?

I am not sure whether you can see it in the MARC record of the subordinated resource whether it is a volume or not. And I don't have the time now to dive into the MARC documentation. We could check the type of the superordinated resource and choose `isPartOf` if it is a `MultiVolumeBook`. Or isn't this feasible in the ETL if we want to have a performant workflow?

> @acka47 do you have an example for this. There seems to be only one hit for this.

Apparently, the data has already improved since I wrote this so no need to go deeper into this. Nice.

**Comment by TobiasNx** [comment]
I have an idea for isPartOf / containedIn, at least if 245 $n or $p exist because they state the subvolume name and number. I will introduce this.

**Comment by TobiasNx** [comment]
Closing issue that is still open will be solved in #1635
