### ISSUE TITLE
Facette mapping with `300` should exclude types and medium behind `:`

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1567]
Type Mapping with 300 should exclude those that are behind a `:` e.g.:

```
    <datafield tag="300" ind1=" " ind2=" ">
      <subfield code="a">S. [129] - 524 : Ill., graph. Darst, Kt.</subfield>
    </datafield>
```

This has a map as a part of the book but it is no map in it self: http://test.lobid.org/resources/HT004764408#!

**Comment by dr0i** [comment]
Not sure why I am assigned here. If it's about checking wether your commit works it seems not (http://alma.lobid.org/resources/990065341720206441) but then I don't know if I understand the issue coorectly.

**Comment by TobiasNx** [comment]
Seems to work now.
