### ISSUE TITLE
Introduce type for "Teil eines Werkes"

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1574]
Limetrans has a mapping for Teil eines Werkes, which translates to the component parts of a publication:

https://github.com/hbz/limetrans/blob/433b0eeffa59dcf31e49ebd662e0826db9d0c02f/src/main/resources/transformation/alma.fix#L727

While we have this for Articles we should introduce this as a general type in my opinion:
Map if `leader` 07 is `a` and/or if `245` has subfield "n" or "p"

**Comment by acka47** [comment]
Today's discussion:

- @TobiasNx and @acka47 have reservations of putting information into `type` that is already expressed by a relation (`isPartOf`)
- Another approach would be to display a facet for `bibliographicLevel`. @blackwinter will investiugate whether this could be an alternative route.
