### ISSUE TITLE
Make entries in  altLabels unique

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1582]
Sometimes in `altLabels` there is redundant data like in [src/test/resources/alma-fix/990141342350206441.json](https://github.com/hbz/lobid-resources/blob/master/src/test/resources/alma-fix/990141342350206441.json#L106) . Would be good if we could make these unique to not overblow the index.

**Comment by TobiasNx** [comment]
It seems that these are no duplicates but are different variations which differ from the info in the subfields. Question would be if we should keep them since some info is not just the variation of the name.

**Comment by dr0i** [comment]
I count 14 times `Federico` in the `altLabels` field.

**Comment by TobiasNx** [comment]
This is related to: https://github.com/hbz/lobid-resources/pull/1584/commits/733286d2e1f6841f795650c57c18c166c453ce06

The subfields $a $b $c and $x have additional info that should be comined to the name, then the duplicates would resolve.

**Comment by TobiasNx** [comment]
Solved with #1558
