### ISSUE TITLE
ALMA: only 4 subject facettes?

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1586]
![grafik](https://user-images.githubusercontent.com/61879957/211279822-ed4888b9-53f3-464d-b61d-2c4655137742.png)

https://test.lobid.org/resources/search?q=

I don't know where to fix this?

**Comment by dr0i** [comment]
I don't know. There is:
```  <div class="row facet"><div class="col-md-12">@facets("Schlagwörter", Application.SUBJECT_FIELD, if(!urisOnly(subject).isEmpty) urisOnly(subject) else "", "dropup")</div></div>```
in `bin/views/tags/facets.scala.html` , but don't know why this is not working.
Structural difference to production lobid-resources seems to be the addendum of `altLabels` in almafix - could this possibly break teh creation of `Schlagwörter` facet? 
Looking at the logs I don't see anything.
Assigning @fsteeg .

**Comment by fsteeg** [comment]
Currently, on https://test.lobid.org/resources/search?q=, I don't see the subject facet at all.

**Comment by fsteeg** [comment]
The underlying problem seems to be that in the Alma data, `subject.componentList.id` has `http` URIs instead of `https`, see:

http://test.lobid.org/resources/search?q=subject.componentList.id:*&format=json
http://lobid.org/resources/search?q=subject.componentList.id:*&format=json

I've opened https://github.com/hbz/lobid-resources/pull/1589 to make it work both with `http` and `https` URIs since the UI should not break due to that. But it should probably also be changed in the transformation.

**Comment by fsteeg** [comment]
Assigning @TobiasNx for functional review of the subject facet. Deployed to test:

https://test.lobid.org/resources/search

(Not sure if you want to continue with the http->https transformation change here or in a new issue.)

**Comment by TobiasNx** [comment]
which one is right? http or https?

**Comment by dr0i** [comment]
The `https` one is the better one, not only because we used that in old lobid-resources -  it's also the preferred URL:
` curl -vvv 'http://d-nb.info/gnd/7749153-1'`
=>
```    [...] <h1>Moved Permanently</h1>
    <p>The document has moved <a href="https://d-nb.info/gnd/7749153-1">here</a>.</p>  [...]
```

**Comment by TobiasNx** [comment]
+1 seems to work on test.

**Comment by fsteeg** [comment]
As discussed in our meeting today, I've closed https://github.com/hbz/lobid-resources/pull/1589 and undeployed the workaround:

https://test.lobid.org/resources/search

Assigning @TobiasNx for functional review of the actual fix (when https://github.com/hbz/lobid-resources/pull/1594 is deployed).

**Comment by TobiasNx** [comment]
Seems to work now closing
