### ISSUE TITLE
ALMA-Fix: Titles with ... and [...]

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1591]
https://test.lobid.org/resources/990212668130206441 ( Bericht der Schulinspektion .., [...]: Schule An der Burgweide )
https://test.lobid.org/resources/990370599930206441 ( Ren-min wang, [...]. [...]: Uyġurčä )
https://test.lobid.org/resources/990370268580206441 ( Zensus .., [...]. [...]: Bevölkerung und Haushalte )

@acka47 how do we deal with this?

**Comment by acka47** [comment]
I guest, it is probably best to follow the approach from current productive lobid-resources: 

https://lobid.org/resources/HT019037589
https://lobid.org/resources/HT020866768
 https://lobid.org/resources/HT020833573

**Comment by TobiasNx** [comment]
Trailing dot is cut off: https://test.lobid.org/resources/990212668130206441 This should be fixed.

**Comment by TobiasNx** [comment]
@dr0i is this not working on test.lobid? https://test.lobid.org/resources/990212668130206441
The master seems to work.
https://github.com/hbz/lobid-resources/pull/1632

**Comment by dr0i** [comment]
Data on spare server couldn't be accessed, so there was no updated index. Switched to other server , which can access the data. Started ETL so that the index should be there tomorow.

**Comment by dr0i** [comment]
Deployed. Closing.
