### ISSUE TITLE
Different aggregated results in Bestände-Facette and Results

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1601]
When selecting an institution in the facette the results and the aggregated result differ:

![grafik](https://user-images.githubusercontent.com/61879957/212650365-759d6905-a3bf-4be8-bb95-1eb1e901454e.png)

![grafik](https://user-images.githubusercontent.com/61879957/212650565-53e3b1dd-1092-4735-9127-df6ca268f173.png)

**Comment by dr0i** [comment]
Do you have links? Images don't help me this much to reproduce.

**Comment by TobiasNx** [comment]
No links: Go to lobid-resources select "Bestand in Bibliotheken" -> Münster ULB and then have a look at the results at the top and the number besides Münster.

**Comment by dr0i** [comment]
Ah now I see e.g. http://lobid.org/resources/search?q=linux&owner=http%3A%2F%2Flobid.org%2Forganisations%2FDE-467%23%21&aggregations=owner. But that's the old lobid-resources. Do we need to fix that?

**Comment by dr0i** [comment]
relates to https://github.com/hbz/lobid-resources/issues/1602

**Comment by acka47** [comment]
I think this is a duplicate of #207 and thus can be closed.
