### ISSUE TITLE
ALMA-Fix: Bestände in GUI is missing as facette

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1602]
In the old system we have
"Bestand in Bibliotheken"  as facet, e.g. https://lobid.org/resources/search?q=linux.
In the new one these are missing: https://test.lobid.org/resources/search?q=linux

Must have something to do how the `item`s are modelled now.

**Comment by fsteeg** [comment]
Quoting the latest state on this from https://github.com/hbz/lobid-resources/issues/1342#issuecomment-1288996284:

> One remaining UI issue are items, which are currently not displayed because the UI expects item URIs that contain their owner's ISILs (like `http://lobid.org/items/HT014991220:DE-38:34A6062#!`). Should (can?) the UI get the ISIL from the heldBy.id? (Or) can the ISILs be added in the transformation to create item URIs as before?

**Comment by dr0i** [comment]
In Alma-Fix these look like e.g. `"http://lobid.org/items/990053976760206441:DE-465:67 P 23#!"`. The ISIL is`DE-465` and structurally at the same "slot" like in the old system. Difference is: formerly after `/items/` there was `$hbzID` now `$almaMMSID`. Also the URI is no more resolvable - but I think we agreed that this is ok.

**Comment by dr0i** [comment]
There is even an own isil field now: `hasItem.heldBy.isil`( http://test.lobid.org/resources/990053976760206441.json) which was formerly not there.

**Comment by TobiasNx** [comment]
> 

It is only not resolvable because we do not have a function to encode it as URL: https://github.com/hbz/lobid-resources/issues/1521

**Comment by TobiasNx** [comment]
The missing URL encoding in metafacture fix is not blocking this ticket any more: https://github.com/hbz/lobid-resources/issues/1521#issuecomment-1463708641

**Comment by dr0i** [comment]
I think this is resolved. Can you close then @TobiasNx ?

**Comment by TobiasNx** [comment]
It seems as it is solved yes.
Not sure if there is anything to still open, but we could reopen the ticket if needed.
