### ISSUE TITLE
ALMA-Fix: Document API-Breaks in Tickets and in Blog

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1603]
https://github.com/hbz/lobid-blog/pull/85

**Comment by dr0i** [comment]
Ah, sorry if I've intervened with https://github.com/hbz/lobid-blog/issues/87. You may close the issues and PRs.

**Comment by TobiasNx** [comment]
Closing since published: https://blog.lobid.org/2023/04/11/lobid-alma.html
