### ISSUE TITLE
ALMA-Fix: Variation for holding of DE-6 to ALMA-Morph

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1605]
[ALMA-Fix: 6256635](http://test.lobid.org/resources/search?q=hasItem.heldBy.id%3A%22http%3A%2F%2Flobid.org%2Forganisations%2FDE-6%23!%22)
[ALEPH-Morph: 2938332](http://lobid.org/resources/search?q=hasItem.heldBy.id%3A%22http%3A%2F%2Flobid.org%2Forganisations%2FDE-6%23%21%22)

**Comment by TobiasNx** [comment]
It seems that ALMA counts institutional library holdings of DE-6 (e.g. [DE-6-164](http://lobid.org/organisations/DE-6-164)) as holdings of DE-6:

```
<datafield tag="MBD" ind1=" " ind2=" ">
<subfield code="M">49HBZ_ULM</subfield>
<subfield code="i">991032169219706449</subfield>
<subfield code="n">Universität Münster</subfield>
</datafield>
...
<datafield tag="HOL" ind1=" " ind2=" ">
<subfield code="b">2022-07-11 10:44:34</subfield>
<subfield code="8">22545591710006449</subfield>
<subfield code="M">49HBZ_ULM</subfield>
<subfield code="g">false</subfield>
<subfield code="a">import</subfield>
</datafield>
...
<datafield tag="ITM" ind1=" " ind2=" ">
<subfield code="H">22545591710006449</subfield>
<subfield code="x">MEGT_BIBEG</subfield>
<subfield code="f">BOOK</subfield>
<subfield code="v">MEGT_BIBEG</subfield>
<subfield code="X">AMO_TL2_FIX</subfield>
<subfield code="U">2022-07-10 12:59:00 Europe/Berlin</subfield>
<subfield code="Y">2022-07-12 13:10:54 Europe/Berlin</subfield>
<subfield code="h">false</subfield>
<subfield code="Q">
SISIS-Ausleihzähler Migrationsjahr: 0 | SISIS-Ausleihzähler Vor-Migrationsjahr: 0 | SISIS-Ausleihzähler vorletztes Migrationsjahr: 0
</subfield>
<subfield code="M">49HBZ_ULM</subfield>
<subfield code="s">1</subfield>
<subfield code="d">8</subfield>
<subfield code="V">import</subfield>
<subfield code="b">Z75-040987</subfield>
<subfield code="O">Fernleihkonditionen: 3</subfield>
<subfield code="a">23545591700006449</subfield>
<subfield code="R">DBS-Systematik: 0</subfield>
<subfield code="c">31 u S 1698</subfield>
<subfield code="W">2022-07-11 12:44:34 Europe/Berlin</subfield>
<subfield code="u">MEGT</subfield>
<subfield code="w">MEGT</subfield>
</datafield>
```

was: 

```
<datafield tag="088" ind1=" " ind2=" ">
<subfield code="a">6/164</subfield>
<subfield code="c">31 u S 1698</subfield>
<subfield code="e">keine Angabe</subfield>
</datafield>
```

@dr0i and @acka47  might this be the problem? 
Could you help to count all holdings in ALEPH with `DE-6*` not just `DE-6`

**Comment by TobiasNx** [comment]
Another example: http://lobid.org/resources/HT001191377 (DE-6-011) vs. http://test.lobid.org/resources/HT001191377 (DE-6)

**Comment by TobiasNx** [comment]
Thanks to the hint by @blackwinter institional libraries are now part of their parent institution IZ

In `H52`

[H52](https://www.loc.gov/marc/holdings/hd852.html): library = `$b`, location = `$c`

 And in `ITM` 

[ITM](https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=612532300#NZPublishingf%C3%BCrDiscoveryAnbindung(DISC)-ItemsInformation(ITM)): library = `$w`, location = `$x`

We find a refrence to the sublocation

**Comment by acka47** [comment]
> Could you help to count all holdings in ALEPH with DE-6* not just DE-6

This query should be the way to go:

[`(hasItem.heldBy.id:http\:\/\/lobid.org\/organisations\/DE\-6\-* OR hasItem.heldBy.id:http\:\/\/lobid.org\/organisations\/DE\-6#\!)`](https://lobid.org/resources/search?q=%28hasItem.heldBy.id%3Ahttp%5C%3A%5C%2F%5C%2Flobid.org%5C%2Forganisations%5C%2FDE%5C-6%5C-*+OR+hasItem.heldBy.id%3Ahttp%5C%3A%5C%2F%5C%2Flobid.org%5C%2Forganisations%5C%2FDE%5C-6%23%5C%21%29)

**Comment by acka47** [comment]
How do we identify the electronic resources that only exist in Alma? By `medium.id: "http://rdaregistry.info/termList/RDAMediaType/1003"`. These are 1,689,631 resources:

[`hasItem.heldBy.id:"http://lobid.org/organisations/DE-6#!" AND medium.id:"http://rdaregistry.info/termList/RDAMediaType/1003"`](http://test.lobid.org/resources/search?q=hasItem.heldBy.id%3A%22http%3A%2F%2Flobid.org%2Forganisations%2FDE-6%23%21%22+AND+medium.id%3A%22http%3A%2F%2Frdaregistry.info%2FtermList%2FRDAMediaType%2F1003%22)

4,712,726 + 1,689,631 = 6,402,357

**Comment by TobiasNx** [comment]
When I exclude hasItem.type:DigitalDocument is 4452233
[`(hasItem.heldBy.id:http\:\/\/lobid.org\/organisations\/DE\-6\-* OR hasItem.heldBy.id:http\:\/\/lobid.org\/organisations\/DE\-6#\!) AND NOT  hasItem.type:DigitalDocument`](https://test.lobid.org/resources/search?q=%28hasItem.heldBy.id%3Ahttp%5C%3A%5C%2F%5C%2Flobid.org%5C%2Forganisations%5C%2FDE%5C-6%5C-*+OR+hasItem.heldBy.id%3Ahttp%5C%3A%5C%2F%5C%2Flobid.org%5C%2Forganisations%5C%2FDE%5C-6%23%5C%21%29+AND+NOT++hasItem.type%3ADigitalDocument)

**Comment by TobiasNx** [comment]
> Können lokale Titeldatensätze durch lobid ausgefiltert werden (Titel ohne IDNs mit (DE-605) Präfix HT-, CT, TT oder BT, oder nur ZDB-IDN)?

[(hasItem.heldBy.id:http\:\/\/lobid.org\/organisations\/DE\-6\-* OR hasItem.heldBy.id:http\:\/\/lobid.org\/organisations\/DE\-6#\!) AND NOT _exists_:hbzId
](https://test.lobid.org/resources/search?q=%28hasItem.heldBy.id%3Ahttp%5C%3A%5C%2F%5C%2Flobid.org%5C%2Forganisations%5C%2FDE%5C-6%5C-*+OR+hasItem.heldBy.id%3Ahttp%5C%3A%5C%2F%5C%2Flobid.org%5C%2Forganisations%5C%2FDE%5C-6%23%5C%21%29+AND+NOT+_exists_%3AhbzId)

**Comment by TobiasNx** [comment]
> > Können lokale Titeldatensätze durch lobid ausgefiltert werden (Titel ohne IDNs mit (DE-605) Präfix HT-, CT, TT oder BT, oder nur ZDB-IDN)?
> 
> [(hasItem.heldBy.id:http://lobid.org/organisations/DE-6-* OR hasItem.heldBy.id:http://lobid.org/organisations/DE-6#!) AND NOT _exists_:hbzId ](https://test.lobid.org/resources/search?q=%28hasItem.heldBy.id%3Ahttp%5C%3A%5C%2F%5C%2Flobid.org%5C%2Forganisations%5C%2FDE%5C-6%5C-*+OR+hasItem.heldBy.id%3Ahttp%5C%3A%5C%2F%5C%2Flobid.org%5C%2Forganisations%5C%2FDE%5C-6%23%5C%21%29+AND+NOT+_exists_%3AhbzId)
> 
> = 1,054,042 without hbzId = local resources
> 
> Or did I miss something

Thanks to @blackwinter again:

> nein, cz-ressourcen wären dann auch ausgefiltert (sie haben keine hbz-id). aber es würden die zdb-titel fehlen (bekommen keine hbz-id mehr).
> 
> außerdem meine ich mich zu erinnern, dass es nach der migration vereinzelt lokale titel mit hbz-id gab. ich weiß nicht, ob diese inzwischen bereinigt sind.

Resources without `hbzId` are CZ and local resources, but also contain ZDB resources that do not get `hbzId`s anymore.
Also due to some migration error some local resources had a `hbzId`. (maybe fixed)

[(hasItem.heldBy.id:http\:\/\/lobid.org\/organisations\/DE\-6#\!) AND (NOT _exists_:hbzId AND NOT _exists_:zdbId)](https://test.lobid.org/resources/search?q=%28hasItem.heldBy.id%3Ahttp%5C%3A%5C%2F%5C%2Flobid.org%5C%2Forganisations%5C%2FDE%5C-6%23%5C%21%29+AND+%28NOT+_exists_%3AhbzId+AND+NOT+_exists_%3AzdbId%29)

same result
= 1,054,042 without hbzId = local resources + CZ resources

**Comment by TobiasNx** [comment]
Combined:
ALMA:
[6,256,930](https://test.lobid.org/resources/search?q=%28hasItem.heldBy.id%3Ahttp%5C%3A%5C%2F%5C%2Flobid.org%5C%2Forganisations%5C%2FDE%5C-6%23%5C%21%29) all holdings by `DE-6`

[5,202,888](https://test.lobid.org/resources/search?q=%28hasItem.heldBy.id%3Ahttp%5C%3A%5C%2F%5C%2Flobid.org%5C%2Forganisations%5C%2FDE%5C-6%23%5C%21%29+AND+%28+_exists_%3AhbzId+OR+_exists_%3AzdbId%29) all holdings by `DE-6` without local resources and CZ resources

[4,022,883 ](https://test.lobid.org/resources/search?q=%28hasItem.heldBy.id%3Ahttp%5C%3A%5C%2F%5C%2Flobid.org%5C%2Forganisations%5C%2FDE%5C-6%23%5C%21%29+AND+%28+_exists_%3AhbzId+OR+_exists_%3AzdbId%29+AND+NOT+hasItem.type%3ADigitalDocument) all holdings by `DE-6` without local resources and CZ resources and no electronic portfolios

ALEPH:
[2,938,588](https://lobid.org/resources/search?q=hasItem.heldBy.id%3Ahttp%5C%3A%5C%2F%5C%2Flobid.org%5C%2Forganisations%5C%2FDE%5C-6%23%5C%21)  all holdings by `DE-6` 



[4,712,726](https://lobid.org/resources/search?q=%28hasItem.heldBy.id%3Ahttp%5C%3A%5C%2F%5C%2Flobid.org%5C%2Forganisations%5C%2FDE%5C-6%5C-*+OR+hasItem.heldBy.id%3Ahttp%5C%3A%5C%2F%5C%2Flobid.org%5C%2Forganisations%5C%2FDE%5C-6%23%5C%21%29) all holdings of institutions with ISIL `DE-6` or `DE-6-*`

**Comment by acka47** [comment]
To do: Write email to Verbundgruppe requiring

1. use of ISILs instead of new identifiers for insitute libraries/sublocations in Alma
2. if 1.) is not possible, provide a mapping of Alma sublocation IDs to ISIL.

**Comment by acka47** [comment]
> if 1.) is not possible, provide a mapping of Alma sublocation IDs to ISIL.

The mapping can be found at https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=763035742 (via @TobiasNx in chat).

**Comment by acka47** [comment]
I just talked to S.S. on the phone. There is no chance to switch the Alma-internal lirbary codes to ISIL. I also learned that these IDs are set by the libraries themselves and they provide the mapping.

I suggested to maintain the mapping in git, e.g. by using the https://github.com/hbz/lookup-tables repo. We scheduled a meeting for January 27th to discuss the concrete approach that will then be communicated to the libraries on February 8th.

**Comment by acka47** [comment]
@TobiasNx for now, you can proceed using the mappings in the [wiki](https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=763035742). Maybe you best start by putting the mapping information from the wiki and the attached xslx files as csv into the [lookup-tables](https://github.com/hbz/lookup-tables) repo.

**Comment by TobiasNx** [comment]
If we want to map the sublocation ISIL we need one of the following solutions:

either a long mapping list where `[Main owner ISIL or ALMA Code]+[library code]` is mapped to sublibrary ISIL

or

mapping files for each library where library code is mapped to sublibrary ISIL. The second solution also needs new features in FIX since `lookup("Sublibrary-ISIL", "$[HO-ISIL].tsv","sep_char":"\t", delete:"true")` does not work yet. Fix can't create a variable from a element value at the moment.

**Comment by acka47** [comment]
We found the underlying problem. Steps to solve this, well get their own issues. Closing
