### ISSUE TITLE
"New" fields coming in Aleph export from February on

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#161]
Quoting an email by colleage S. Scholz from 2017-01-11:

> Gerne möchte ich nochmals auf die Änderungen ab 22. Februar 2017 in der hbz-Verbunddatenbank hinweisen: Einführung von acht neuen ASEQ-Feldern, die den MARC21-Feldern 770, 772, 775, 776, 777, 780, 785 und 787 nachgebildet sind. Sie sollen künftig die Inhalte aufnehmen, die bisher in den ASEQ-Feldern 527 bis 534 gehalten werden.

| Neu?|MARC |     Inhalte        | ASEQ alt | ASEQ neu |
|-----|-----|--------------------|----------|----------|
|NEU|770 08| Beilage |529 |770 |
|NEU|772 08 |Übergeordnete Einheit der Beilage| 530 |772 |
|-|773 08 |Übergeordnete Einheit des unselbständigen Werks| 010, 090, 59X |010, 090, 59X |
|-|774 |Teileinheit |- |- |
|-|775 08| Angaben/Link zum Original bei identischer physischer Form |649a| 649a|
|-|775 08 |Angaben/Link zur Reproduktion bei identischer physischer Form |649b |649b|
|NEU|775 08 |Angaben/Link zu anderen Ausgaben bei identischer physischer Form |527 |775 |
|-|776 08 |Angaben/Link zum Original bei unterschiedlicher physischer Form |649c| 649c|
|-|776 08 |Angaben/Link zur Reproduktion bei unterschiedlicher physischer Form |649d |649d|
|NEU|776 08 |Angaben/Link zu anderen Ausgaben bei unterschiedlicher physischer Form| 527| 776 |
|NEU|777 | Erschienen mit |- |777 |
|NEU|780| Vorgänger| 531| 780| 
|NEU|785| Nachfolger| 533| 785| 
|-|786| Datenquelle| -| -| 
|NEU|787 08| Angaben/Link zu in sonstiger Beziehung stehenden Ressourcen| 534| 787|

**Comment by acka47** [comment]
@jprante answered in the mail thread:

> die MARC-Felder 770, 772, 775, 776, 777, 780, 785 und 787 gibt es auch in den ZDB-MARC-Lieferungen.

So maybe we also have them already covered.

**Comment by acka47** [comment]
As far as I can see we currently only transform `529`, see [morph, line193](https://github.com/hbz/lobid-resources/blob/7523c206b124e8ae9370fe1e88ea80fa42ecb13a/src/main/resources/morph-hbz01-to-lobid.xml#L193). Other fields that are mentioned in the table I couldn't find in the morph. (Which doesn't mean that we shouldn't add them.)

**Comment by acka47** [comment]
To be clear: **These changes only hold for records created or modified after 2017-02-22.**

**Comment by ChristophEwertowski** [comment]
090 is used for lobid/lv#volumeIn but not as a discrete field. 594 is transformed to placeOfPublication ([morph, line 661](https://github.com/hbz/lobid-resources/blob/master/src/main/resources/morph-hbz01-to-lobid.xml#L661)). 595 to schema.org/startDate ([line 676](https://github.com/hbz/lobid-resources/blob/master/src/main/resources/morph-hbz01-to-lobid.xml#L676)) and 59[0123568] for dc/terms/bibliographicCitation ([line 1569](https://github.com/hbz/lobid-resources/blob/master/src/main/resources/morph-hbz01-to-lobid.xml#L1569)).

**Comment by ChristophEwertowski** [comment]
Simply added the new fields were the old fields were already used. A grep on the baseline didn't show resources.

**Comment by ChristophEwertowski** [comment]
We agreed on putting it back until some resources with the MAB fields exist. For now I'm closing this issue.

**Comment by ChristophEwertowski** [comment]
| Neu?|     Inhalte        | ASEQ alt | ASEQ neu |Covered?
|-----|-----|--------------------|----------|----------|
|NEU| Beilage |529 |770 |Only 529z1
|NEU|Übergeordnete Einheit der Beilage| 530 |772 |No
|-|Übergeordnete Einheit des unselbständigen Werks| 010, 090, 59X |010, 090, 59X |10: Yes; 90: Yes; 59X: All but 597 covered
|-| Angaben/Link zum Original bei identischer physischer Form |649a| 649a|No, see #526
|-|Angaben/Link zur Reproduktion bei identischer physischer Form |649b |649b|No, see #526
|NEU|Angaben/Link zu anderen Ausgaben bei identischer physischer Form |527 |775 |Yes
|-|Angaben/Link zum Original bei unterschiedlicher physischer Form |649c| 649c|No, see #526
|-|Angaben/Link zur Reproduktion bei unterschiedlicher physischer Form |649d |649d|No, see #526
|NEU|Angaben/Link zu anderen Ausgaben bei unterschiedlicher physischer Form| 527| 776 |Yes
|NEU| Erschienen mit |- |777 |No
|NEU| Vorgänger| 531| 780|Yes
|NEU| Nachfolger| 533| 785|Yes
|NEU| Angaben/Link zu in sonstiger Beziehung stehenden Ressourcen| 534| 787|No

Also grep doesn't work on binary files...

**Comment by ChristophEwertowski** [comment]
I ran the statistics tool by dr0i on aleph-baseline from 09th of March.

|MAB field|Comment|
|--|--|
|529| 529z1: ~34.000 resources. 529-1: ~2500 resources. 529y1: 80 resources. 529x1: 12 resources.|
|534|No results.|
|597|~46.000 resources. "Gesamttitel der Quelle". Contains titles and volumes, if part of the whole title. E.g. "Meisterweisen ; 5".|
|649|649a: ~1500 resources. 649b: 201 resources. 649c: ~15.000 resources. 649d: ~18.000 resources.|
|777|Only 276 resources. Example: http://lobid.org/hbz01/HT019017781.|
|787|~74.000 resources. |
