### ISSUE TITLE
NWBib data used to have to have supertypes like e.g. Q106658 (Landkreis) 

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1611]
From https://github.com/hbz/lobid-resources/pull/1610#issuecomment-1404786561:

> The only difference I see, is with regard to the type infromation from Wikidata. Aleph lobid uses a supertype ([Q106658 (Landkreis)](http://www.wikidata.org/entity/Q106658)) while Alma lobid uses the actual types from the entry ([Q20738811 (Kreis in Nordrhein-Westfalen)](http://www.wikidata.org/entity/Q20738811) & [Q106517174 (Optionskommune)](http://www.wikidata.org/entity/Q106517174)). I am not sure but it can well be that we defined a list of types to be used here for Aleph lobid.
However, for now this looks good and we might as well fix the type thing later.

We can find that `Q106658`  was formerly used in the now discarded  https://github.com/hbz/lobid-resources/blob/3ac035d3500b0b8c6e2c5709630b1661537084f1/src/main/java/org/lobid/resources/run/WikidataGeodata2Es.java#L87 . There we used the "coverage" entry "97" to determine the type, see https://github.com/hbz/lobid-resources/pull/1610/files#diff-1a1962f114b3feace52d433108ac495205769ff84218ff41b7611c04b0356b21L16 .

**Comment by TobiasNx** [comment]
@acka47 can this be closed? Since the types are now discarded?

**Comment by acka47** [comment]
Generally, I liked the old approach  with the supertypes as it kept the number of Wikidata classes used small and we intentionally opened this issue to revisit it. However, although the current solution might be the cleanest as a multitude of types is used it makes sense as it 1:1 mirrors the practice in Wikidata.. It also conforms to what we have written in https://blog.lobid.org/2019/10/08/nwbib-at-cdv.html#nwbib-ortssystematik-und-wikidata: 

> Mit spatial.focus.id wird der entsprechende Wikidata-Eintrag zu dem Ort angegeben... Zudem finden sich im spatial.focus-Objekt Geokoordinaten aus Wikidata und die Klassen, denen das Wikidata-Objekt zugeordnet wurde. 

Thus, closing.
