### ISSUE TITLE
Add correct labels for RPB classifications via SKOS lookup

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1612]
In [meeting on 2023-01-27](https://service-wiki.hbz-nrw.de/display/SEM/2023-01-27+Kleine+Runde) with LBZ they reported that Aleph-based resources have wrong labels, example [HT021604735](https://lobid.org/resources/HT021604735). This is, because we did not update the labels.json after changes in the RPP turtle files, e.g. https://github.com/hbz/lobid-vocabs/commit/2f74dc0190c0db39e0370554c4dcd03530f6f3f1

However, we do not need to change the Aleph-lobid so let's take a look at the Alma-based data: https://lobid.org/resources/HT021604735

There are no labels at all for the RPB classification concepts. We will have to add them with the Metafacture SKOS lookup we still need to introduce. Thus, depends on https://github.com/metafacture/metafacture-core/issues/415

**Comment by TobiasNx** [comment]
Seems to be a duplicate: https://github.com/hbz/lobid-resources/issues/1478

**Comment by acka47** [comment]
> Seems to be a duplicate: https://github.com/hbz/lobid-resources/issues/1478

Yes, closing.
