### ISSUE TITLE
Solve differences in analyzing search fields

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1614]
There are differences in analyzing search fields. DigiBib uses stopwords and in part different analyzers.
We gather some examples and try to find a compromise/solution for both worlds.

**Comment by blackwinter** [comment]
Here are some differences between DigiBib and Lobid index settings:

| Setting | DigiBib | Lobid |
|-|-|-|
| Analyzer | [Custom](https://github.com/hbz/limetrans/blob/a1566c5e257d942e9c9b3f4b710e16b800f26592/src/main/resources/elasticsearch/hbztitle-settings.json#L98)¹ | [Custom](https://github.com/hbz/lobid-resources/blob/4e3cb45c2d5ff36b0f9bbf31011945e9fa3c1fb4/src/main/resources/index-config.json#L7) & [Standard](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/analysis-standard-analyzer.html) |
| Tokenizer | [Hyphen](https://github.com/jprante/elasticsearch-plugin-bundle/blob/master/src/docs/asciidoc/hyphen.adoc) | [Standard](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/analysis-standard-tokenizer.html) |
| Search analyzer | [w/o Hyphen](https://github.com/hbz/limetrans/blob/a1566c5e257d942e9c9b3f4b710e16b800f26592/src/main/resources/elasticsearch/hbztitle-settings.json#L114) | n/a |
| "All fields" search | [`cql.allIndexes`](https://github.com/hbz/limetrans/blob/a1566c5e257d942e9c9b3f4b710e16b800f26592/src/main/resources/elasticsearch/hbztitle-mapping.json#L68) (via [`copy_to`](https://www.elastic.co/guide/en/elasticsearch/reference/2.2/copy-to.html)) | [`_all`](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/mapping-all-field.html)² |

¹ Additional filters in DigiBib analyzer:

- [german_stop_words](https://github.com/hbz/limetrans/blob/a1566c5e257d942e9c9b3f4b710e16b800f26592/src/main/resources/elasticsearch/hbztitle-settings.json#L39)
- [keyword_repeat](https://www.elastic.co/guide/en/elasticsearch/reference/2.2/analysis-keyword-repeat-tokenfilter.html)
- [icu_normalizer](https://github.com/jprante/elasticsearch-plugin-bundle/blob/master/src/docs/asciidoc/icu.adoc#2-normalization)
- [icu_folding](https://github.com/jprante/elasticsearch-plugin-bundle/blob/master/src/docs/asciidoc/icu.adoc#3-character-folding)
- [hyphen](https://github.com/jprante/elasticsearch-plugin-bundle/blob/master/src/docs/asciidoc/hyphen.adoc)
- [string_normalizer](https://github.com/hbz/limetrans/blob/a1566c5e257d942e9c9b3f4b710e16b800f26592/src/main/resources/elasticsearch/hbztitle-settings.json#L19)
- [standardnumber](https://github.com/jprante/elasticsearch-plugin-bundle/blob/master/src/docs/asciidoc/standardnumbers.adoc) (ISBN)
- [unique](https://www.elastic.co/guide/en/elasticsearch/reference/2.2/analysis-unique-tokenfilter.html)

² May be configured with [`include_in_all`](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/include-in-all.html).

**Comment by blackwinter** [comment]
We're using the [elasticsearch-analysis-reference](https://github.com/jprante/elasticsearch-analysis-reference) plugin for GND enrichment (corporate bodies, geographic names, person names, subject headings). This may be replaced with `altLabel`s from Alma's Authority Enrichment (`Gxx` fields in the publishing).

**Comment by blackwinter** [comment]
I'm contemplating the idea of introducing new search fields (_virtual_ fields via `copy_to`) in order to satisfy DigiBib's analysis and searchability requirements without impacting existing use cases. Would you be open to such a change? I'm thinking of grouping them under new top-level properties (something like `q`/`query` for query fields, `f`/`facet` for facet fields, `s`/`sort` for sort fields).

**Comment by dr0i** [comment]
How could we have any objections against things which don't affect the status quo of the API? Just go on.

**Comment by blackwinter** [comment]
The proposed changes affect you/the API in that they preclude these index-only fields from being used for metadata fields; that's why I suggested short names that are unlikely to occur in practice (or we could even introduce a single new top-level field that's reserved for this purpose).

Another aspect might be that these changes affect indexing time and index size, which you called out in other occasions.

But I'll open a pull request and then we can discuss specifics if necessary.

**Comment by dr0i** [comment]
I consider these effects to be OK.

**Comment by blackwinter** [comment]
Depends on #1615 being resolved:

- [ ] Plugin available for tests (before pull request)
- [ ] Plugin available for production (before deploy)

**Comment by dr0i** [comment]
@blackwinter is something missing or can you go on here? We received feedback from E.S. that the ISBN/ISSN search should work with and without semantic sugar.

**Comment by blackwinter** [comment]
I'll get to it as time allows.
