### ISSUE TITLE
Install plugin for treatment of  Bindestrich-Komposita and ISBNs 

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1615]
DigiBib uses  https://github.com/jprante/elasticsearch-plugin-bundle . It's not available in our version of ES 5.6 , but we should try them out. Maybe they are just working - or we get them to work with some adaptions.

**Comment by blackwinter** [comment]
In order for #1614 to proceed, `elasticsearch-plugin-bundle` needs to be installed:

- [ ] into the local test cluster (for tests)
- [ ] into the production cluster (for production use)

---

Hints for making the plugin available for index tests:

1. Specify test implementation dependency on `org.xbib.elasticsearch:elasticsearch-plugin-bundle:5.4.1.0`.
2. Import `org.xbib.elasticsearch.plugin.bundle.BundlePlugin` in `controllers.resources.LocalIndex`.
3. Inject `BundlePlugin.class` into `new Node(settings)`, possibly via `LocalNode` class.

```java
private static class LocalNode extends Node {
    private LocalNode(final Settings settings) {
        super(InternalSettingsPreparer.prepareEnvironment(settings, null),
                Version.CURRENT,
                Collections.singleton(BundlePlugin.class));
    }
}
```

**Comment by blackwinter** [comment]
Dependency declaration for [elasticsearch-plugin-bundle](https://central.sonatype.com/artifact/org.xbib.elasticsearch.plugin/elasticsearch-plugin-bundle/5.4.1.0) in `web/build.sbt`:

```sbt
"org.xbib.elasticsearch.plugin" % "elasticsearch-plugin-bundle" % "5.4.1.0" % "test"
```

**Comment by dr0i** [comment]
@blackwinter thx a lot for your code hints! I got it working by changing `"org.xbib.elasticsearch.plugin" % "elasticsearch-plugin-bundle" % "5.4.1.0" % "test"` to not restrict to `test`: as the class `LocalIndex` is not part of the `test` directory but trying to use the `BundlePlugin` it cannot find.

**Comment by blackwinter** [comment]
Ah, yes, that was my mistake. Thank you!

**Comment by dr0i** [comment]
Installed plugin into ES prduction cluster following in https://github.com/hbz/lobid-resources/issues/1615#issuecomment-1516331254.

Tested https://github.com/jprante/elasticsearch-plugin-bundle#icu_numberformat and seems to work.

_Note_: the [official documentation](https://www.elastic.co/guide/en/elasticsearch/plugins/5.6/installation.html#_core_elasticsearch_plugins) doesn't mention the need of a restart of the node, but I discovered that this is crucial. Although a `bin/elasticsearch-plugin list` shows the `bundle` as installed a node restart was necessary.

**Comment by dr0i** [comment]
I close this issue and @blackwinter can go on in https://github.com/hbz/lobid-resources/issues/1614.
