### ISSUE TITLE
Document how a contribution search works

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1616]
Document how a corporation-search is done (like e.g. https://nwbib.de/search?name=&corporation=k%C3%B6ln , accessible in https://nwbib.de/advanced ->Person ->choose "Körperschaft").

@blackwinter needs this for implementation in DigiBib.

**Comment by fsteeg** [comment]
I had written that to @blackwinter in the chat. Here's a translation for the record:

It's implemented with a nested query, which is available in lobid via the 'nested' query parameter. It's implemented here: https://github.com/hbz/lobid-resources/blob/master/web/app/controllers/resources/Queries.java#L496. There's a sample call in the 'nested' example here: http://lobid.org/resources/api#query-syntax.

**Comment by dr0i** [comment]
\o/ Ok then, I close this issue.
