### ISSUE TITLE
Make more `labels` working as aggregations to provide facets

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1617]
Lobid facets use IDs. DigiBib uses labels. Thus we need labels to be typed as `keyword` to  enable ES' aggregations.

We should start with:
- [x]  `language` and`medium`
and later also:
- [x] `subject`

@blackwinter noted that it woul be nice to have ISIL as a field on its own.

@dr0i expects not a huge decline in overall ETL processing time. ES-cluster should be fine doing the extra work.

**Comment by TobiasNx** [comment]
@blackwinter two additional questions:

Do you need the ISIL only of the mainowner or of the sublibrary?
Should the subject facette exclude the concatinated label of the Schlagwortfolgen (if that is possible)?

**Comment by blackwinter** [comment]
> Do you need the ISIL only of the mainowner or of the sublibrary?

We would need the ISIL of the sublibrary. But shouldn't this be discussed in a separate issue?

> Should the subject facette exclude the concatinated label of the Schlagwortfolgen (if that is possible)?

I'm not sure I follow. Do you have an example? Do you intend to add it via data (transformation) instead of via schema (`copy_to`)?

**Comment by blackwinter** [comment]
I see, thanks. That is indeed more complex.

Initially, I was thinking of simply combining `subject.label` and `subject.componentList.label` into a new facet (via `copy_to`). But with `subject.componentList.label` basically containing duplicates of `subject.label`, I'm not so sure anymore.

Ideally, we'd want `subject.label WHERE subject.type = "concept"` plus `subject.componentList.label`, but that would require changing the data transformation (and adding a new field to the API).

Let me think about possible options. If you have any ideas, please don't hesitate to share.

**Comment by blackwinter** [comment]
It's not possible within the Elasticsearch mapping. There's no way to create a "virtual" field based on some condition. So it would have to be an actual source field. But please, I'd love to be proven wrong ;)

**Comment by blackwinter** [comment]
Summary: `subject.componentList.label` plus `subject.label WHERE subject.type = "Concept" AND NOT EXISTS("subject.notation")`

**Comment by blackwinter** [comment]
Decision: Add a new field matching the aforementioned criteria; the field will initially be public.

@TobiasNx will propose a specification for the new field.

**Comment by dr0i** [comment]
I reopen this issue for reviewing the deployed version at 17.4. Assigning @blackwinter  to review on coming Monday.
