### ISSUE TITLE
Missing details for journals

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#1627]
Came up in [RPB-50](https://jira.hbz-nrw.de/browse/RPB-50?focusedId=303146&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-303146) (where we're using Alma data, it seems this is an issue both with Aleph and Alma data):

> Bei den Lobid-Datensätzen ist mir aufgefallen, dass bei Zeitschriften die wichtigste Information fehlt: der Zählung der Zeitschrift, also die erschienenen Jahrgänge/Bände, diese Information steht in Aleph Kat. 405. Die in Lobid angezeigte Information "Erschienen = "publicationHistory" zeigt nur an, in welchen Jahren die Jahrgänge/Bände erschienen sind. Diese Angaben können (teils sehr) voneinander abweichen, z.B. der Kalender von 2023 erscheint in 2022, das Jahrbuch 2020/21 erscheint erst 2023

**Comment by TobiasNx** [comment]
@fsteeg could you provide an example?

**Comment by TobiasNx** [comment]
ALEPH MORPH used 405 as statement in publicationHistory:

			`<data source="405-1.a" name="http://rdaregistry.info/Elements/u/P60491"/>`

=>
 ```
 {
    "name": "publicationHistory",
    "uri": "http://rdaregistry.info/Elements/u/P60491",
    "label": "Erscheinungsverlauf",
    "referenceType": "String"
  }
```

**Comment by TobiasNx** [comment]
405# $a | 362 0# $a | Angaben zur Zählung (fR)
-- | -- | --

It seems that `publicationHistory` was mapped false in ALMA-Fix. 

```
do list(path:"260[ 23] |264[ 23][ 1]", "var":"$i")
  add_field("publication[].$append.test","")
  paste("publication[].$last.publicationHistory", "$i.c")
```

**Comment by TobiasNx** [comment]
@fsteeg could you check if this problem is fixed now?
I adjusted the mapping: https://github.com/hbz/lobid-resources/commit/5de0e32cb56bd0498afd2e66c0e8c3fe6f7b0d93

**Comment by fsteeg** [comment]
Sorry, I did not get an examples with the report. But looking at the original report and your change I don't think it is correct (also in the diff there seem to be weird values introduced): `publicationHistory` should contain actual publication dates, as it did before, but the info from `405` should be available somewhere, at least that's how I understand it.

**Comment by TobiasNx** [comment]
I updated the mapping to the matching element here:  https://github.com/hbz/lobid-resources/commit/5de0e32cb56bd0498afd2e66c0e8c3fe6f7b0d93:


405# $a | 362 0# $a | Angaben zur Zählung (fR)
-- | -- | --

Source: https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=483000321

When did this element have actual publication dates? If you compare lobid and alma.lobid `publicationHistory` should be the same:

http://lobid.org/resources/HT016604323?format=json
http://alma.lobid.org/resources/HT016604323?format=json


http://alma.lobid.org/resources/990193229450206441?format=json
http://lobid.org/resources/990193229450206441?format=json

**Comment by TobiasNx** [comment]
Talked to @fsteeg off board, we decided the changes are good. So we close.
