### ISSUE TITLE
Wrong publication.startDate

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1638]
The publication dates of these resources are too far in the future:
https://test.lobid.org/resources/search?q=publication.startDate:%3E2024&from=1&sort=newest

Should be investigated if it's a wrong transformation rule or a catalog error.

**Comment by TobiasNx** [comment]
There are around 250 records with publication dates above 2023. This is due to multiple reasons; Publication dates in the future. Indian publication dates. Wrong publication dates.
Since this is a very small number of publications I would say that we close this issue.

@dr0i  what do you think?

**Comment by dr0i** [comment]
Agreed. Closing.
