### ISSUE TITLE
Map the sublocation ISIL as holdings

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1639]
If we want to map the sublocation ISIL we need the following:

- [x] Create Repo for institutional specific tsv/csv named `[Main owner ISIL or ALMA Code].tsv` with 1. column:`[library code]` 2. column: sublibrary ISIL See: https://github.com/hbz/lookup-tables/pull/10
- [x] create script to combine the multiple tsv to one long mapping list where `[Main owner ISIL or ALMA Code]+[library code]` is mapped to `sublibrary ISIL`
- [x] add lookup to alma-fix to map holdings to `sublibrary ISIL` instead of `Main owner ISIL` See: https://github.com/hbz/lobid-resources/pull/1640
- [x]  add automated workflow that `curl`s the file https://raw.githubusercontent.com/hbz/lookup-tables/master/data/almaSublibraryCode2Isil/generated/generatedAlmaSublibraryCode2Isil.tsv and overwrites the file: https://github.com/hbz/lobid-resources/pull/1641/files#diff-e940def23987ac6073fab5e9de4f7267210480487bf1072f2e289cbaa6b7af25

Also see: https://github.com/hbz/lobid-resources/issues/1605#issuecomment-1386856215_

**Comment by TobiasNx** [comment]
@dr0i the script should create this file: https://github.com/hbz/lobid-resources/pull/1640/files#diff-683e8d999fc884f218ed1a3522144dc59dfa19d9efce01237256d16b0c23ba3c

**Comment by TobiasNx** [comment]
Source of this should be: https://github.com/hbz/almaSublibraryCodeMapping

**Comment by TobiasNx** [comment]
@acka47 and @dr0i please have a look at this solution

**Comment by dr0i** [comment]
> Source of this should be: https://github.com/hbz/almaSublibraryCodeMapping

We discussed in the meeting at 20230127 to use "das bestehende Repo benutzen: https://github.com/hbz/lookup-tables ". It's not decided yet, but I would vote to do that.

**Comment by TobiasNx** [comment]
> > Source of this should be: https://github.com/hbz/almaSublibraryCodeMapping
> 
> We discussed in the meeting at 20230127 to use "das bestehende Repo benutzen: https://github.com/hbz/lookup-tables ". It's not decided yet, but I would vote to do that.

If the mapping should be done by the libraries. This could cause issues concerning the rights, how can we limit the authority of contributors to only certain folders?

**Comment by dr0i** [comment]
@TobiasNx I thought of : we review and merge.

**Comment by TobiasNx** [comment]
@dr0i and @acka47 I changed the repo to https://github.com/hbz/lookup-tables and prepared everything for developing the short script.

**Comment by dr0i** [comment]
Script is ready, see PR. Unassigning me here.

**Comment by TobiasNx** [comment]
@dr0i the pullrequest #1641 can be reviewed and you can add the cron job that curls the file.

**Comment by dr0i** [comment]
Added to cron : every day at 8:00 pm the lookup table is pulled and copied to servers.

**Comment by dr0i** [comment]
@acka47 moved this to Done in [oi-Knirps](https://github.com/orgs/hbz/projects/8) but didn't close it. Assuming that that was not intended:
closing.
