### ISSUE TITLE
Alma: case "Angebunden an"

### ISSUE THREAD

**Issue by hagbeck** [hbz/lobid-resources#1643]
Hi,
we observed a case which isn't currently supported by lobid. "Angebunden an" are titles which are contained in the physical object of another title. Those "parts" have its own holdings or items.

An example is 990057340660206441. The data for the host object is in field 773:

```xml
<datafield tag="773" ind1="1" ind2="8">
  <subfield code="9">LOCAL</subfield>
  <subfield code="g">no:413443</subfield>
  <subfield code="p">AngebundenAn</subfield>
  <subfield code="t">¬Die gesellschaftliche Schichtung im Kapitalismus</subfield>
  <subfield code="w">991000882289706445</subfield>
  <subfield code="M">49HBZ_UBD</subfield>
</datafield>```

Could you please add a `relation` for this situation?

**Comment by hagbeck** [comment]
991000882289706445 is an identifier (MMS-ID) from our IZ. I don't know why this is here and not the corresponding from the NZ (990057345430206441).

The sign at the beginning of the title is equivalent to the notation <<Die>>.

The idea behind this structure is to reduce the costs for the "Buchbinder". Therefore this title has not its own holding or item. 

The "only" thing we need is a link to the parent 990057345430206441. But I can't see how to get this ID ...

**Comment by acka47** [comment]
> The "only" thing we need is a link to the parent 990057345430206441. But I can't see how to get this ID ...

@hagbeck So should we close this then?

**Comment by hagbeck** [comment]
If there is no way to add the ID, then we can close this.

**Comment by acka47** [comment]
> If there is no way to add the ID, then we can close this.

Currently, there isn't. We could communicate the problem to Verbundgruppe and ask to use NZ IDs instead of (or in addition to) IZ IDs for this relation.

**Comment by TobiasNx** [comment]
@hagbeck I think we are the wrong contact to adress this. It seems that 773 $w holds [related Hosting objects ](https://www.loc.gov/marc/bibliographic/bd773.html)

Mostly the relation is expressed by hbz identifiern: 
e.g.: [990183092590206441](https://alma.lobid.org/resources/990183092590206441)

```
  <datafield tag="773" ind1="0" ind2="8">
    <subfield code="i">Enthalten in</subfield>
    <subfield code="t">Mélodies / Claude Debussy</subfield>
    <subfield code="d">[S.l.], 1980</subfield>
    <subfield code="w">(DE-605)HT016607985</subfield>
  </datafield>
```
or
[990190567380206441](https://alma.lobid.org/resources/990190567380206441)

```
  <datafield tag="773" ind1="0" ind2="8">
    <subfield code="i">Enthalten in</subfield>
    <subfield code="t">Westfalen</subfield>
    <subfield code="d">Münster</subfield>
    <subfield code="g">88. 2010 (2012), S. 175-179</subfield>
    <subfield code="w">(DE-605)HT001374559</subfield>
  </datafield>
```

But I found examples from UB Münster that have the same issue as you:

[990063549080206441](https://alma.lobid.org/resources/990063549080206441)

```
  <datafield tag="773" ind1="1" ind2="8">
    <subfield code="9">LOCAL</subfield>
    <subfield code="g">no:Z/2035-507/509</subfield>
    <subfield code="p">AngebundenAn</subfield>
    <subfield code="t">¬The annals of the American Academy of Political and Social Science</subfield>
    <subfield code="w">991012986519706449</subfield>
    <subfield code="M">49HBZ_ULM</subfield>
  </datafield>
```


[991000688209706449](https://alma.lobid.org/resources/991000688209706449)
```
  <datafield tag="773" ind1="0" ind2="8">
    <subfield code="w">991021220959706449</subfield>
  </datafield>
```


Both seem to link to IZ entries and not NZ entries with no corresponding entry in lobid. Perhaps you should talk about this to the Verbund-Gruppe?
If the links get fixed, you could get back to us.

**Comment by TobiasNx** [comment]
@hagbeck I have another question:
I kick out all local 773 linking with https://github.com/hbz/lobid-resources/pull/1657
Since they only use IZ linking as you identified.

 The question is, are the lokal 773 important for you? Should we keep them if they have more info than this or should we even keep the lokal IZ linkage even though they do not resolve?
