### ISSUE TITLE
URI-encoding needed?

### ISSUE THREAD

**Issue by hagbeck** [hbz/lobid-resources#1644]
If I want to convert the resource http://alma.lobid.org/resources/990226793240206441.json to turtle via e.g. https://issemantic.net/rdf-converter I'm getting the error

> Error: "http://lobid.org/items/990226793240206441:DE-290:EFB:A 358 GOUD#!" does not look like a valid URI, I cannot serialize this as N3/Turtle. Perhaps you wanted to urlencode it?

**Comment by TobiasNx** [comment]
Duplicate: https://github.com/hbz/lobid-resources/issues/1521

**Comment by dr0i** [comment]
Hi @hagbeck as @TobiasNx said, we are already of it. There is even a [PR](https://github.com/metafacture/metafacture-fix/pull/285) for it but that need some refactoring. I don't think that this will be resolved in the next month. Is that ok for you or is it urging?

**Comment by hagbeck** [comment]
It's ok. Today I've used the data as RDF the first time for a show case. For some examples it is possible for me to fix that manually.

**Comment by dr0i** [comment]
Ok, good then. I will close this issue. We will keep track on that issue in https://github.com/hbz/lobid-resources/issues/1521 .
