### ISSUE TITLE
Stats for 2017-01-01 missing

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#165]
I can't find web access statistics for December 2016, ie.e from 2017-01-01. @dr0i can you please take a look?

**Comment by dr0i** [comment]
That's an issue when executing the `logrotate` from the crontab.
In "/etc/logrotate.d/apache2":
    /var/log/apache2/access_log {
        monthly
        missingok
        rotate 2400
        compress
        compresscmd /usr/bin/bzip2
        delaycompress
        notifempty
        create 640 root root
        su nobody nogroup
        sharedscripts
        copytruncate
        dateext
        postrotate
                /usr/bin/systemctl reload apache2.service
                mv /var/log/apache2/access_log-20* /files/weywot4/logs_apache_emphytos/
        endscript
    }
I changed the formerly line "create 640 nobody nogroup" to "root".
To be tested.
Splitted the access.log manually and ran the [crontabMonthly.sh](https://github.com/hbz/lobid-webserver/blob/master/goaccess/crontabMonthly.sh) script.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Again: logrotate permission denied :(
Changed in "/etc/logrotate.d/apache2": 

    su wwwrun root
    create 644 wwwrun root

Tested this with:
`# logrotate -d  /etc/logrotate.d/apache2`
=> no error.
