### ISSUE TITLE
lobid-Alma GUI: Missing `Details zum Bestand als Liste anzeigen` info on the detail page of a resource

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1654]
Records have the info related to Details zum Bestand als Liste anzeigen, but GUI is missing the info. @fsteeg is this related to https://github.com/hbz/lobid-resources/issues/1602 and the error is caused due to the missing urls for items in ALMA (e.g. http://lobid.org/items/HT006327580:DE-38:95%2F1099)?

http://lobid.org/resources/HT006327580#

![grafik](https://user-images.githubusercontent.com/61879957/224739570-2f6818ec-fb41-43c1-bb43-e022dd92d305.png)

http://alma.lobid.org/resources/990023967740206441#

![grafik](https://user-images.githubusercontent.com/61879957/224739685-3a335e19-8699-4bc2-87ef-e22643d481d5.png)

**Comment by TobiasNx** [comment]
@fsteeg is this related to #1602

**Comment by dr0i** [comment]
I think this is resolved - can you close then @TobiasNx ?

**Comment by TobiasNx** [comment]
Fixed
