### ISSUE TITLE
RPB-Lookup for inCollection and rpbId

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1655]
I added the list from https://github.com/hbz/lookup-tables/pull/12#event-8732500659 and introduced a lookup for `rpbId` as well a inCollection for RPB if a record has a `rpbId`.

Should @dr0i add a cron job to update the list ?

**Comment by TobiasNx** [comment]
See #1656

**Comment by dr0i** [comment]
Will be deployed at early Monday.

**Comment by TobiasNx** [comment]
You were assigned if this method meets your demands. You can unassigne yourself for now.

**Comment by dr0i** [comment]
Checked cron , works.
