### ISSUE TITLE
Performance decline in ETL

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1666]
Since index `resources-alma-fix-20230318-0917` the ETL takes 25h.
ETL of the index before that (`resources-alma-fix-20230311-0835`) needed only 18h.

The cause is very likely Metafix as we experienced (and improved) before, e.g. https://github.com/metafacture/metafacture-fix/issues/207.
It  _could_ also have other causes (server load; network; etc.) so we first wait a week to see if  this is reproducible.

**Comment by dr0i** [comment]
Decline seems to be manifest - index from 2023-03-25 09:14 took 26h.

**Comment by dr0i** [comment]
Will increase RAM and see if this helps.

**Comment by TobiasNx** [comment]
[Beetween November 27 and December 5 the performance increased by 6,5h from  7h to 13,5h.](https://github.com/hbz/lobid-resources/pulls?q=is%3Apr+closed%3A2022-11-27..2022-12-05+)

[Between March 10 and March 17 the perfomance increased by 8h from 17h to 25h.](https://github.com/hbz/lobid-resources/pulls?q=is%3Apr+closed%3A2023-03-10..2023-03-17)


- [ ] Is `unless` or `unless`in `unless` a problem?
- [ ] Is `put_filemap` with multiple columns a problem?
- [ ] Is `expected_columns:"-1"` as option in `put_filemap` a problem?
- [ ] It introduced multiple lookups with +2 columns ("multi column"). For nwbib and rpb. Is that a problem?
- [ ] Is uniq a problem?
- [ ] Is the lookup using a external variable a problem?
- [ ] is do list on on array with an do list on another external array a problem?

**Comment by dr0i** [comment]
Maps were included every time a document was ETLed. Using `do once("maps")` around `include ("./fix/maps.fix")` ensures the loading of the map one time during running time.
Reduces the time of whole ETL from 26h to ~10h.
Thx @TobiasNx  for having the idea and @blackwinter for code snippet.
