### ISSUE TITLE
Incomplete data for three-level corporate body

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1667]
Reported today by D.C. via [RPB-50](https://jira.hbz-nrw.de/browse/RPB-50?focusedId=303567&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-303567):

> Bei der Bearbeitung der Liste ist mir noch ein Fehler in der Lobid-Anzeige aufgefallen:
Unvollständigkeit bei der lobid-Anzeige: bei einer dreistufigen Körperschaft werden nur die ersten beiden Stufen angezeigt.
http://test.lobid.org/resources/990214618190206441
in lobid: Sozialdemokratische Partei Deutschlands. Ortsverein
vollständig wäre: Sozialdemokratische Partei Deutschlands. Ortsverein (Mainz-Altstadt)

See also Aleph-based production where everything is fine: https://lobid.org/resources/HT019199421

Subfield `g` is not taken into account ([source](https://alma.lobid.org/marcxml/990214618190206441)):

```xml
<datafield tag="110" ind1="2" ind2=" ">
  <subfield code="a">Sozialdemokratische Partei Deutschlands</subfield>
  <subfield code="b">Ortsverein</subfield>
  <subfield code="g">Mainz-Altstadt</subfield>
  <subfield code="0">(DE-588)10091858-X</subfield>
  <subfield code="4">aut</subfield>
  <subfield code="0">
https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=idn=97377102X
  </subfield>
  <subfield code="0">http://viaf.org/viaf/sourceID/DNB|97377102X</subfield>
  <subfield code="B">GND-97377102X</subfield>
</datafield>
```

**Comment by TobiasNx** [comment]
In alma.lobid this fix is productive:
http://alma.lobid.org/resources/990214618190206441

**Comment by dr0i** [comment]
We defined the staging index to use for RPB. This is always one basedump ETL behind the production (one week behind). Shall we change this? Don't we have any data conflicts (doublettes) ?

**Comment by TobiasNx** [comment]
The RPB Question can be discussed in a new ticket if neededd. CLosing
