### ISSUE TITLE
Enhance Alma type mapping

### ISSUE THREAD

**Issue by blackwinter** [hbz/lobid-resources#1669]
While comparing the new Alma records to our current Aleph representations, we identified the following differences:

- [x] [CT005001279](https://alma.lobid.org/resources/990188822530206441) has **type** `Miscellaneous`, should be `Book`.
- [x] [HT006482841](https://alma.lobid.org/resources/990024710810206441) has **type** `Miscellaneous`, should be `Book` and `PublishedScore` ("Musikalia").
- [x] [HT006482841](https://alma.lobid.org/resources/990024710810206441) has **medium** `Miscellaneous`, should be `Print`. (Implied by `type=Book`; see [transformation](https://github.com/hbz/lobid-resources/blob/4e3cb45c2d5ff36b0f9bbf31011945e9fa3c1fb4/src/main/resources/alma/fix/mediumAndType.fix#L667).)
- [ ] ~[HT016717410](https://alma.lobid.org/resources/990184214350206441) and [HT004908939](https://alma.lobid.org/resources/990081611770206441) have **type** `Book`, should be `PartOfWork` ("Teil eines Werkes").~ See #1574.

(Subject to the Alma metadata providing the required information to infer these mappings.)

**Comment by TobiasNx** [comment]
@blackwinter one side note PartOfWork ("Teil eines Werkes") is not yet part of lobid see #1574

**Comment by TobiasNx** [comment]
One hint concerning Monograph/Item, marc defines them not as book specific info:

```

**Comment by TobiasNx** [comment]
> `CT005001279` has `leader/06=m` ("Computer file"), but you are [only considering](https://github.com/hbz/lobid-resources/blob/4e3cb45c2d5ff36b0f9bbf31011945e9fa3c1fb4/src/main/resources/alma/fix/mediumAndType.fix#L12) `a` ("Language material") for `type`. This, in combination with `leader/07=m` ("Monograph/Item"), _might_ be sufficient to infer `Book`. Otherwise, a more suitable type may be chosen.

@blackwinter 
isn't this what should work?
https://github.com/hbz/lobid-resources/blob/4e3cb45c2d5ff36b0f9bbf31011945e9fa3c1fb4/src/main/resources/alma/fix/mediumAndType.fix#L17

**Comment by TobiasNx** [comment]
> While comparing the new Alma records to our current Aleph representations, we identified the following differences:
> 
>     * [x]  [CT005001279](https://alma.lobid.org/resources/990188822530206441) has **type** `Miscellaneous`, should be `Book`.
> 
>     * [x]  [HT006482841](https://alma.lobid.org/resources/990024710810206441) has **type** `Miscellaneous`, should be `Book` and `PublishedScore` ("Musikalia").
> 
>     * [x]  [HT006482841](https://alma.lobid.org/resources/990024710810206441) has **medium** `Miscellaneous`, should be `Print`. (Implied by `type=Book`; see [transformation](https://github.com/hbz/lobid-resources/blob/4e3cb45c2d5ff36b0f9bbf31011945e9fa3c1fb4/src/main/resources/alma/fix/mediumAndType.fix#L667).)
> 
>     * [ ]  ~[HT016717410](https://alma.lobid.org/resources/990184214350206441) and [HT004908939](https://alma.lobid.org/resources/990081611770206441) have **type** `Book`, should be `PartOfWork` ("Teil eines Werkes").~ See [Introduce type for "Teil eines Werkes" #1574](https://github.com/hbz/lobid-resources/issues/1574).
> 
> 
> (Subject to the Alma metadata providing the required information to infer these mappings.)

Updates are now productive and changed. Looks good.
