### ISSUE TITLE
Add "Notiz" to item data

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#167]
If possible, we should add "Notiz" details to our item data.

See https://github.com/hbz/lobid-resources-web/issues/15#issuecomment-271287198

**Comment by acka47** [comment]
This is 088, subfield b, e.g. http://lobid.org/hbz01/HT015061862:

```xml
<datafield tag="088" ind1=" " ind2=" ">
  <subfield code="a">461/1</subfield>
  <subfield code="b">204</subfield>
  <subfield code="c">TWP/BLU</subfield>
<subfield code="e">Keine Angabe</subfield>
</datafield>
```

("204" is not correct anymore, though, because we moved to another room...)

**Comment by acka47** [comment]
I suggest we use `http://id.loc.gov/ontologies/bibframe/note` as property.

**Comment by dr0i** [comment]
Unsure if `note` should be a string or a set. I found http://lobid.org/hbz01/HT012926727 where `PUM 16(2)` has two entries and comes with two different `note`s. Ideas @acka47 @ChristophEwertowski ?

**Comment by ChristophEwertowski** [comment]
To sum up talk between acka47 and dr0i: Using set for "note" is better because we don't know what else is hidden for this field. I agree to this.

**Comment by ChristophEwertowski** [comment]
+1s given in [pull request](https://github.com/hbz/lobid-resources/pull/183).

**Comment by fsteeg** [comment]
Reopening, the note should be displayed in the UI (item details on the map), e.g. for:

[http://lobid.org/items/HT002702618:DE-605:AASL%2FBLC(82%2F85)-14#!](http://lobid.org/items/HT002702618:DE-605:AASL%2FBLC(82%2F85)-14#!)

Background: original use case was to find things in our (increasingly distributed) hbz library.

See also https://github.com/hbz/lobid-resources-web/issues/15.

**Comment by acka47** [comment]
@dr0i @fsteeg Thanks for implementing this. Shouldn't we add a page to lobid.org that only searches hbz Dienstbibliothek's collection? This should be hidden, i.e. not linked anywhere in the nav bar...
