### ISSUE TITLE
Implement MARC `028$$a` (Publisher or Distributor Number)

### ISSUE THREAD

**Issue by blackwinter** [hbz/lobid-resources#1670]
[HT004044766](https://alma.lobid.org/resources/990015710520206441) should include the "Publisher or Distributor Number" ([MARC 028$$a](https://www.loc.gov/marc/bibliographic/bd028.html)).

```xml
<datafield tag="028" ind1="5" ind2="2">
  <subfield code="a">Best.-Nr. AM 70210</subfield>
</datafield>
```

**Comment by TobiasNx** [comment]
I would suggest: https://schema.org/sku

> The Stock Keeping Unit (SKU), i.e. a merchant-specific identifier for a product or service, or the product to which the offer refers.

From Wikipedia:

> These identifiers are not regulated or standardized. When a company receives items from a vendor, it has a choice of maintaining the vendor's SKU or creating its own.

Since they are repeatable I would suggest an array of strings.

**Comment by acka47** [comment]
> https://www.w3.org/community/schemabibex/wiki/Holdings_via_Offer

In the [Schema Bib Extend Community Group](https://www.w3.org/community/schemabibex/), `sdo:sku` was recommended for "call number", see https://www.w3.org/community/schemabibex/wiki/Holdings_via_Offer. So this might not be the best choice then.

**Comment by TobiasNx** [comment]
Bibframe has https://id.loc.gov/ontologies/bibframe/StockNumber.rdf as class. This seems to be a good starting point for naming the new property in lobid: `stockNumber`

**Comment by blackwinter** [comment]
Not implemented in most recent index. Still need to be deployed?

**Comment by TobiasNx** [comment]
I thought pascal introduced automatic deployment?

**Comment by blackwinter** [comment]
`stockNumber` is available now.
