### ISSUE TITLE
Implement MARC `546$$a,b` (Language Note)

### ISSUE THREAD

**Issue by blackwinter** [hbz/lobid-resources#1671]
[HT018856429](https://alma.lobid.org/resources/990210273970206441) and [HT019472708](https://alma.lobid.org/resources/990219775100206441) should include the "Language Note" ([MARC 546$$a,b](https://www.loc.gov/marc/bibliographic/bd546.html)).

"Language note":

```xml
<datafield tag="546" ind1=" " ind2=" ">
  <subfield code="a">Beiträge teilweise deutsch, teilweise englisch</subfield>
</datafield>
```

"Information code or alphabet":

```xml
<datafield tag="546" ind1=" " ind2=" ">
  <subfield code="b">In chinesischer Schrift</subfield>
</datafield>
```

**Comment by acka47** [comment]
From https://www.loc.gov/bibframe/mtbf/ it looks like Bibframe uses a general note field and adds a type information to the different notes. This apporach would mean an API break so we can not follow this path. Thus, we should either use this approach for newly added notes or just define a property `lv:langNote` or similar in lobid vocab.

**Comment by blackwinter** [comment]
`langNote` is available now.
