### ISSUE TITLE
Implement MARC `650$#7$2=MeSH` (Subject Added Entry-Topical Term: Medical Subject Headings)

### ISSUE THREAD

**Issue by blackwinter** [hbz/lobid-resources#1672]
[HT003184116](https://alma.lobid.org/resources/990075538650206441) should include "MeSH (Medical Subject Headings)" ([MARC 650$#7$2=MeSH](https://www.loc.gov/marc/bibliographic/bd650.html)) in addition to "FAST (Faceted Application of Subject Terminology)".

```xml
<datafield tag="650" ind1=" " ind2="7">
  <subfield code="a">Shoulder / injuries</subfield>
  <subfield code="2">MeSH</subfield>
</datafield>
```

**Comment by TobiasNx** [comment]
One sidenote: This seems to be incorrectly catalogued:
Medical Subject Headings have their own indicator:

2 - Medical Subject Headings 
See: https://www.loc.gov/marc/bibliographic/bd650.html

Here is 7.
We could map specific vocabularies that are also listed in 7 too. Do we have a list of these providers?

**Comment by blackwinter** [comment]
> This seems to be incorrectly catalogued:
> Medical Subject Headings have their own indicator:

Be that as it may, we'd still like to have it ;)



> We could map specific vocabularies that are also listed in 7 too. Do we have a list of these providers?

See [Subject Heading and Term Source Codes](https://www.loc.gov/standards/sourcelist/subject.html).

**Comment by TobiasNx** [comment]
Done. If we want to add additional vocabularies. We should have a look at: [Subject Heading and Term Source Codes](https://www.loc.gov/standards/sourcelist/subject.html).
