### ISSUE TITLE
Provide filtering ability for Alma Network Zone records

### ISSUE THREAD

**Issue by blackwinter** [hbz/lobid-resources#1677]
We need to be able to filter records belonging to the Alma Network Zone. The initial approach was to rely on the presence of the hbz ID (MARC `035$$a` with prefix `(DE-605)`, Lobid `hbzId`), but this is not sufficient:

1. Sometimes records in an Institution Zone erroneously include an hbz ID (e.g., `TT050389906`: [990178459700206446](https://alma.lobid.org/resources/990178459700206446) and [990010880170206447](https://alma.lobid.org/resources/990010880170206447)).
2. ZDB records won't receive an hbz ID anymore starting with NZ phase 2.

So we need a different filter condition that _excludes_ IZ records, but _includes_ ZDB records. Potential candidates:

1. MARC `003=DE-655` ([hbz Network Zone ISIL](https://lobid.org/organisations/DE-655)); this would require mapping the [Control Number Identifier](https://www.loc.gov/marc/bibliographic/bd003.html) field.
2. MARC `MBD$$M=49HBZ_NETWORK` (hbz Network Zone Member code); this would require mapping the Member code field.

(NOTE: It's still unclear - to me, anyway - how exactly the records will look like in NZ phase 2; we might have to wait for the first publishing in order to determine a suitable solution.)

Whatever field is chosen, we just need to be able to query its existence (`"exists": { "field": "isAlmaNz" }`) or a boolean value (`"term": { "isAlmaNz": "true" }`); although querying a specific value would work just as well (`"term": { "controlNumberIdentifier": "DE-655" }` or `"term": { "almaMemberCode": "49HBZ_NETWORK" }`).

**Comment by TobiasNx** [comment]
How about a collection for NZ?

**Comment by blackwinter** [comment]
Do you mean `inCollection`? Yeah, sure, that should work. (It can be [queried by](https://github.com/hbz/lobid-resources/blob/4e3cb45c2d5ff36b0f9bbf31011945e9fa3c1fb4/src/main/resources/index-config.json#L133) `id`.)

**Comment by TobiasNx** [comment]
What about ALMA-MMS-ID with trailing `6441` as filter condition?

**Comment by blackwinter** [comment]
> What about ALMA-MMS-ID with trailing `6441` as filter condition?

Yes, that should work as well. Should be equivalent to `MBD$$M=49HBZ_NETWORK`.

**Comment by TobiasNx** [comment]
This seems to work:
https://alma.lobid.org/resources/search?q=inCollection.id%3A%22http%3A%2F%2Flobid.org%2Forganisations%2FDE-655%23!%22

**Comment by blackwinter** [comment]
Thanks, works as intended.
