### ISSUE TITLE
Change `describedBy.modifiedBy` to `array`?

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1678]
In contrast to 
`describedBy.provider `(`040 $a`) and `describedBy.sourceOrganization` (`040 $c`)

the source element `040 $d` for `describedBy.modifiedBy` is repeatable,
I would suggest to change modifiedBy to an array instead of an object.

https://www.loc.gov/marc/bibliographic/bd040.html

```
  <datafield tag="040" ind1=" " ind2=" ">
    <subfield code="a">0001</subfield>
    <subfield code="b">ger</subfield>
    <subfield code="c">DNB</subfield>
    <subfield code="d">0001</subfield>
    <subfield code="d">DE-605</subfield>
  </datafield>
```
or
```
  <datafield tag="040" ind1=" " ind2=" ">
    <subfield code="a">9001</subfield>
    <subfield code="b">ger</subfield>
    <subfield code="c">DNB</subfield>
    <subfield code="d">0005</subfield>
    <subfield code="d">DE-605</subfield>
  </datafield>
```

This would be an API Break but it would be more accurate to the source data.

@acka47 what do you think?

**Comment by TobiasNx** [comment]
We (@acka47 and I) decided off board to change this to an array and document it as API break.

**Comment by dr0i** [comment]
As this introduces an API break : please @hagbeck @UBmakla can you check if this is ok for you?

**Comment by UBmakla** [comment]
Thanks for the information, that should be no problem for us cause we don´t use modifiedBy. BTW, is there any documentation of API breaks?

**Comment by TobiasNx** [comment]
> Thanks for the information, that should be no problem for us cause we don´t use modifiedBy. BTW, is there any documentation of API breaks?

@hagbeck @UBmakla we are about to publish a blog-post: https://github.com/hbz/lobid-blog/pull/90
