### ISSUE TITLE
containedIn holds non alma ids

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1693]
See e.g. http://alma.lobid.org/resources/990221359400206441.json

These old aleph ids are going to be obsolete. They are also problematic for https://github.com/hbz/lobid-resources/issues/1686 . Can they be substituded by `almaMmsId`?

**Comment by blackwinter** [comment]
> These old aleph ids are going to be obsolete.

What do you mean? hbz IDs are here to stay. Only ZDB titles are going to lose them.

```json
"containedIn" : [ {
  "id" : "http://lobid.org/resources/HT012034605#!",
  "label" : "lobid Ressource"
} ]
```

**Comment by dr0i** [comment]
Uh, gosh, wasn't (anymore?) aware of this. It means, in essential, that  it would even be more neccessarye to provide resolvables URIs like http://lobid.org/resources/HT012034605 in the future.

However - why can't we just link to http://alma.lobid.org/resources/990101871580206441 ? It is not only a duplicate of the old deprecatedUri but has even itself `hbzId: "HT012034605"` so the data should be there.
Ah - cheeze - is it true that this data is missing in [990221359400206441](http://alma.lobid.org/resources/990221359400206441.json) ? Looks like: https://alma.lobid.org/marcxml/990221359400206441

This doesn't make much sense.
We _could_ repair this by making a lookup. We could generate a lookup table.


> Only ZDB titles are going to lose them.

What does this mean? The referenced `containedIn` resource has a `zdbId`.

**Comment by TobiasNx** [comment]
> Uh, gosh, wasn't (anymore?) aware of this. It means, in essential, that it would even be more neccessarye to provide resolvables URIs like http://lobid.org/resources/HT012034605 in the future.
We also have to provide resolvables URL because the old URIs are out in the web. Because of that we introduced solutions for:
https://github.com/hbz/lobid-resources/issues/1433
https://github.com/hbz/lobid-resources/issues/1535

> However - why can't we just link to http://alma.lobid.org/resources/990101871580206441 ? It is not only a duplicate of the old deprecatedUri but has even itself `hbzId: "HT012034605"` so the data should be there. Ah - cheeze - is it true that this data is missing in [990221359400206441](http://alma.lobid.org/resources/990221359400206441.json) ? Looks like: https://alma.lobid.org/marcxml/990221359400206441
Nope linked resource data is not there.

> 
> This doesn't make much sense. We _could_ repair this by making a lookup. We could generate a lookup table.
You want to make a 20.000.000 + lines lookup file that is reused constantly?

> 
> > Only ZDB titles are going to lose them.
https://alma.lobid.org/resources/search?q=_exists_%3A%22zdbId%22+AND+NOT+_exists_%3A%22hbzId%22
New entries to the ZDB will not have a new hbzId.

> 
> What does this mean? The referenced `containedIn` resource has a `zdbId`.

One thing I am not sure about is, if **new** entries in the NZ generally receive links with `"hbzId"` or `ALMA-MMS-ID`?
Old entries will keep the links they already have.

**Comment by dr0i** [comment]
Thx all for clarification. I close this issue as "close as not planned".

**Comment by blackwinter** [comment]
> is it true that this data is missing in [990221359400206441](http://alma.lobid.org/resources/990221359400206441.json) ? Looks like: https://alma.lobid.org/marcxml/990221359400206441

Can you be more specific as to which data is missing?

> What does this mean? The referenced `containedIn` resource has a `zdbId`.

See [here](https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=754516217) for more information. Does this answer (all) your questions?

> New entries to the ZDB will not have a new hbzId.

Just to be clear: Not only _new_ records, but _all_ of them (retroactively).

> One thing I am not sure about is, if **new** entries in the NZ generally receive links with `"hbzId"` or `ALMA-MMS-ID`?

See wiki page above; records are linked by hbz ID or ZDB ID (where applicable).

> Old entries will keep the links they already have.

No, that's not the case for ZDB records: hbz ID links will change to ZDB ID.

**Comment by blackwinter** [comment]
> It's linked to [Aleph HT012034605](http://lobid.org/resources/HT012034605) instead to [Alma 990101871580206441](990101871580206441). In the future we will get new data for Alma, not for Aleph. Thus, _if_ the data would be updated, we will not have that reflected by the link, because this link references outdated data (if Aleph is no more updated that is).

No, it refers to an hbz ID, which is currently generated by Aleph and in the future by Alma. Every record that currently has an hbz ID ("HT-Nummer") will keep its ID in NZ phase 2 - except for ZDB records.

Maybe it helps to emphasize that the hbz IDs we're talking about here are "synthetic" IDs, i.e. they're not the internal database IDs (which will indeed change, of course, from Aleph SYS IDs to Alma MMS IDs).

> so all of old hbzId will be substituted in future? Good.

No, only for ZDB records.

> This I don't understand. Do you mean with "hbz IDs" what I mean with the field name `hbzId` ?

Yes.

> I thought these will be substituted in the future.

Again, only for ZDB records.

> Whatever, I don't have any stocks in this. I just thought we could directly link Alma resources to Alma resources. This is not the case, so we can keep this closed.

I'm only providing the facts here (AFAIK), it's totally up to you what you make of it ;)

**Comment by TobiasNx** [comment]
To document the answer of Verbund concerning the linking:

The linking by hbzId is the way it is done in ALEPH. And it will be continued until ALPEH is shut down. 
Exception: ZDB resources which will lose their hbzIds.  Also IZ resources that link between local resources use ALMA-MMS-IDs.

After ALEPH is shut down it is not decided yet how to proceed with the linking:
- replace all linking with hbzId with ALMA-MMS-ID, or,
- keep all hbzId linking until date x and afterwards all new links will use ALMA-MMS-IDs.

This decision will be done, when NZ-Phase II is done and Verbund-Team will aproach the next step of the ALMA-Migration. shutting down ALEPH.
