### ISSUE TITLE
Error on API doc page with Alma instance

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#1698]
See https://alma.lobid.org/resources/api

From the logs (thanks for reporting @TobiasNx):

```
Caused by: java.lang.NullPointerException: null
        at views.html.api_Scope0$api.sample_doc$1(api.template.scala:40)
        at views.html.api_Scope0$api.apply(api.template.scala:156)
```

**Comment by fsteeg** [comment]
Updated the resource IDs for Alma data and deployed to test:

http://test.lobid.org/resources/api

(I've switched from [HT018472857](http://lobid.org/resources/HT018472857) to [990150876610206441](https://test.lobid.org/resources/990150876610206441) to have an example with items.)

**Comment by fsteeg** [comment]
> (I've switched from [HT018472857](http://lobid.org/resources/HT018472857) to [990150876610206441](https://test.lobid.org/resources/990150876610206441) to have an example with items.)

Weird, now I get the item for [HT018472857](http://test.lobid.org/resources/HT018472857), but I think we can stay with the updated resource.

**Comment by acka47** [comment]
+1 (Wit the switch to Alma, we will have to update the documentation by annotation – or remove it completely.)
