### ISSUE TITLE
Link to the right Bibframe URL

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#170]
http://bibframe.org/vocab/contribution has to be replaced for http://id.loc.gov/ontologies/bibframe/contributor in line 5722 in the file labels.json to match the label "Mitwirkende" and point to the Bibframe 2.0 namespace (see #169 ). It also has to be adapted in the morph.

**Comment by acka47** [comment]
Note that the correct property to use ist `bf:contribution`, i.e. for Bibframe 2.0 `http://id.loc.gov/ontologies/bibframe/contribution`.

**Comment by ChristophEwertowski** [comment]
Shouldn't it be [http://id.loc.gov/ontologies/bibframe/**contributor**](http://id.loc.gov/ontologies/bibframe/contributor)? "Mitwirkende" shouldn't have the same URI as "Mitwirkung".

**Comment by acka47** [comment]
`bf:contributor` is for directly linking a contributor to a resource like so `<resource> bf:contributor <Contributor1>` and furthermore it will actually be eliminated (see http://listserv.loc.gov/cgi-bin/wa?A2=ind1612&L=bibframe&T=0&P=2864). lobid follows the approach that will be left being supported by Bibframe 2.0 where any kind of contribution is found in the "Contribution" object which specifies the agent of the contribution and their role (using [MARC relator codes](http://id.loc.gov/vocabulary/relators.html) and especially `http://id.loc.gov/vocabulary/relators/ctb` as general URI for a not further specified "Mitwirkung").  See also https://www.loc.gov/bibframe/docs/pdf/bf2-roles-apr2016.pdf for the different approaches (they oviously will update this as `bf:contributor` will be eliminated). Following, some examples from lobid. 

From http://lobid.org/resources/TT002664683:

```json
"contribution":{
   "agent":{
      "altLabel":[
         "Dölger, Franz Josef",
         "Doelger, Franz Joseph",
         "Dölger, Franz Jos.",
         "Dölger, Franz J."
      ],
      "id":"http://d-nb.info/gnd/118526227",
      "label":"Dölger, Franz Joseph",
      "type":[
         "Person"
      ]
   },
   "role":[
      {
         "id":"http://id.loc.gov/vocabulary/relators/ctb",
         "label":"Mitwirkende"
      }
   ],
   "type":[
      "Contribution"
   ]
}
```

From http://lobid.org/resources/TT003048562:

```json
"contribution":[
   {
      "agent":{
         "id":"http://d-nb.info/gnd/187197660",
         "label":"Engelkamp, Johannes",
         "type":[
            "Person"
         ]
      },
      "role":[
         {
            "id":"http://id.loc.gov/vocabulary/relators/cre",
            "label":"Autor/in"
         }
      ],
      "type":[
         "Contribution"
      ]
   }
]
```

From http://lobid.org/resources/TT002664695:

```json
"contribution":[
   {
      "agent":{
         "altLabel":[
            "Rijn, Rembrandt Harmensz van",
            "Rembrandt, Harmensz van Ryn",
            "Rijn, Rembrandt van",
            "Rembrandt, van Rijn",
            "Rembrandt, Harmens van Rijn",
            "Harmenszoon van Rijn, Rembrandt",
            "Rembrandt Hermens van Rijn",
            "Rembrant",
            "Rijn, Rembrandt Harmenszoon van",
            "Charmens van Rejn, Rembrandt",
            "Rembrandt, Harmensz van Rijn",
            "Harmensz van Ryn, Rembrandt",
            "Van Rijn, Rembrandt Harmenszoon",
            "Rhyn, Rembrandt van",
            "Rembrandt, Charmens van Rejn",
            "Rembrandt, van Rhyn",
            "Harmensz van Rijn, Rembrandt",
            "Rejn, Rembrandt Charmens van",
            "Ryn, Rembrandt Harmensz van",
            "Rembrandt, Harmens van Ryn",
            "Rembrandt, Harmenszoon van Rijn",
            "Rijn, Rembrandt H. van",
            "Rembrandt",
            "Rembrandt, ..."
         ],
         "id":"http://d-nb.info/gnd/11859964X",
         "label":"Rembrandt, Harmensz van Rijn",
         "type":[
            "Person"
         ]
      },
      "role":[
         {
            "id":"http://id.loc.gov/vocabulary/relators/ill",
            "label":"Illustration"
         }
      ],
      "type":[
         "Contribution"
      ]
   }
...
]
```

**Comment by ChristophEwertowski** [comment]
Since we use the approach of setting a person and it's role to a contribution my suggestion wasn't hitting the mark. Issue will be closed.
