### ISSUE TITLE
Add links for resource links that provide ALMA MMS ID links

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1702]
While at the moment all most all linking is via hbzId links (which could be changed after the complete shut down of ALEPH) for some links the ALMA-MMS-ID is provided.

If no hbzId link is provided we should use the ALMA-MMS-id as link.

**Comment by dr0i** [comment]
I think most of them are substituted by now with the `almaMmsId`.
Some remain however, like e.g. `related` (see e.g. http://lobid.org/resources/99370771475306441.json).

**Comment by TobiasNx** [comment]
Closing this because at the moment only local records link to other records with almaMmsId. We can reopen it when needed.
