### ISSUE TITLE
Some resources are missing inCollection NWBib

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#1705]
E.g. http://lobid.org/resources/HT002200739.json is inCollection NWBib (because some of its volumes are in NWBib?), but http://test.lobid.org/resources/990054165430206441.json is not. This would lead to non-resolving links in NWBib after switching to Alma data for entries like https://test.nwbib.de/99371104961506441 (where `In` links to `http://nwbib.de/HT002200739#!` which will resolve to `http://nwbib.de/990054165430206441`, which is not in NWBib: http://test.nwbib.de/990054165430206441).

**Comment by TobiasNx** [comment]
```
<datafield tag="960" ind1="1" ind2=" ">
<subfield code="n">NWBib-Zeitschrift</subfield>
</datafield>
```

We could add this on basis of this reference to nwbib.
Should be fixed with: https://github.com/hbz/lobid-resources/pull/1722

**Comment by acka47** [comment]
This is done and we can close it, can't we, @TobiasNx ?

**Comment by TobiasNx** [comment]
Yes, closing
