### ISSUE TITLE
Set up zdbId-URI to mmsId-URI redirect for ZDB resources

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1709]
E.g. `http://lobid.org/resources/1151093-6` should redirect (301) to `http://lobid.org/resources/990054441240206441`.

This is because internal links to ZDB resources (e.g. `predecessor`/`successor` or `containedIn`) are handled in Alma via ZDB-IDs (not MMS IDs). 

We should do this analogous to the `hbzId` -> `mmsId` redirect which functions like this:

```
$ curl -IL "http://alma.lobid.org/resources/HT004563509"
HTTP/1.1 301 Moved Permanently
Date: Fri, 21 Apr 2023 12:21:01 GMT
Server: Apache
Location: /resources/990054441240206441
Access-Control-Allow-Origin: *
Via: 1.1 alma.lobid.org
```

**Comment by acka47** [comment]
For context see https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=754516217:

> ### MARC 21 035, hbz-Identifikationsnummer
> 
> Alle Titeldatensätze enthalten eine hbz-Identifikationsnummer in MARC 21 035 $$a mit Präfix (DE-605). 
> 
> Ausnahmen:
> 
> **a) ZDB-Titeldatensätze**
> Bei  ZDB-Titeldatensätzen wird die ZDB-Identifikationsnummer in Alma in MARC 21 035 $$a mit Präfix (DE-600) angegeben. Es gibt keine **keine** hbz-IDN in den ZDB-Titeldatensätzen.
> 
> Beispiel:
> 035 __ $$a (DE-600)201077-X
>
> **NZ-Phase I:**
> 
> 035 | __ \|a (DE-605)HT002213027
> -- | --
> 035 | __ \|a (DE-600)201077-X
> 
> **NZ-Phase II:**
> 035 | ~~__ \|a (DE-605)HT002213027~~
> -- | --
> 035 | __ \|a (DE-600)201077-X
> 
> Verlinkungen zu ZDB-Titeldatensätzen (von ZDB- und Nicht-ZDB-Titeldatensätzen) werden nur über die ZDB-Identifikationsnummer durchgeführt.
> 
> Beispiel:
> 776 08 $$i Sonderdr. $$t Ausgewählte Bibliographien und Nachschlagewerke $$d Frankfurt, M.: $$w **(DE-600)1052303-0**
> 
> **NZ-Phase I:**
> 776 | 08 \|i Sonderdr. \|t Ausgewählte Bibliographien und Nachschlagewerke \|d Frankfurt, M. : Klostermann, 1974-1983 \|w **(DE-605)HT007039586**
> -- | --
> 
> **NZ-Phase II:**
> 776 | 08 \|i Sonderdr. \|t Ausgewählte Bibliographien und Nachschlagewerke \|d Frankfurt, M. : Klostermann, 1974-1983 \|w (DE-600)1052303-0
> -- | --

**Comment by fsteeg** [comment]
Deployed to test:

https://test.lobid.org/resources/1151093-6

```bash
$ curl -IL "https://test.lobid.org/resources/1151093-6"
HTTP/1.1 301 Moved Permanently
Date: Mon, 24 Apr 2023 10:55:58 GMT
Server: Apache
Location: /resources/990054441240206441
```
