### ISSUE TITLE
Redirect items to resources and use embedded details

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#1715]
Came up via https://github.com/hbz/lobid-resources/issues/1714, which seems to be caused by many unsuccessful calls to the `/items` route.

Originally, item details were only available via a separate `/items` route like:

http://lobid.org/items/HT019025795:DE-Kn3:KMB%2FYG%20BERLINW%2033%20%202016%20A#!

And not in the `/resource` itself, like it has been for a while now, see e.g.:

http://lobid.org/resources/HT019025795.json

So while these item routes were no longer required for a while, we never switched the UI to the embedded data, since we still had the separate routes. With the switch to Alma, we're now removing these individual item documents, and should:

- [x] Redirect item routes to the resources that contain them
- [x] Use the embedded item details in the UI (like for NWBib in https://github.com/hbz/nwbib/pull/609/commits/d1f50ab37a38581fcbcc83fc9bc2e478e853bddc)

**Comment by fsteeg** [comment]
Deployed to test:

> - [x] Redirect item routes to the resources that contain them

http://test.lobid.org/items/HT019025795:DE-Kn3:KMB%2FYG%20BERLINW%2033%20%202016%20A#!

```
$ curl -IL "http://test.lobid.org/items/HT019025795:DE-Kn3:KMB%2FYG%20BERLINW%2033%20%202016%20A#!"
HTTP/1.1 303 See Other
Date: Tue, 25 Apr 2023 11:21:47 GMT
Server: Apache
Location: /resources/HT019025795
[...]
```

>  - [x] Use the embedded item details in the UI 

See pins and items list, e.g.

http://test.lobid.org/resources/990212549810206441

**Comment by acka47** [comment]
+1
