### ISSUE TITLE
Problems with resources that are part of more than one series

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#172]
Working on https://github.com/hbz/lobid-resources/pull/171 I stumbled over http://lobid.org/resources/HT018290299#! which has an array with two values in a "numbering" field. (Usually, this field does not have an array.)

```json
"inSeries":[
   {
      "numbering":[
         "2",
         "19"
      ],
      "series":[
         {
            "id":"http://lobid.org/resources/HT006514951#!",
            "label":"lobid Ressource"
         },
         {
            "id":"http://lobid.org/resources/HT017500108#!",
            "label":"lobid Ressource"
         }
      ],
      "type":[
         "SeriesRelation"
      ]
   },
   {
      "numbering":"19",
      "series":[
         {
            "id":"http://lobid.org/resources/HT006514951#!",
            "label":"lobid Ressource"
         }
      ],
      "type":[
         "SeriesRelation"
      ]
   }
]
```

The underlying problem is that the resource is part of two series, and obviously both 451 and 461 are taken into account for the numbering of the first seriesRelation. From the [source data](http://lobid.org/hbz01/HT018290299#!):

```xml
<datafield tag="451" ind1="-" ind2="1">
  <subfield code="a">
Schriftenreihe des NS-Dokumentationszentrums der Stadt Köln ; 19
  </subfield>
</datafield>
<datafield tag="453" ind1="-" ind2="1">
  <subfield code="a">HT006514951</subfield>
</datafield>
<datafield tag="455" ind1="-" ind2="1">
  <subfield code="a">19</subfield>
</datafield>
<datafield tag="456" ind1="-" ind2="1">
  <subfield code="a">19</subfield>
</datafield>
<datafield tag="461" ind1="-" ind2="1">
  <subfield code="a">
Biografien & Materialien / NSDOK; NS-Dokumentationszentrum der Stadt Köln; 2
  </subfield>
</datafield>
<datafield tag="463" ind1="-" ind2="1">
  <subfield code="a">HT017500108</subfield>
</datafield>
<datafield tag="465" ind1="-" ind2="1">
  <subfield code="a">2</subfield>
</datafield>
<datafield tag="466" ind1="-" ind2="1">
  <subfield code="a">2</subfield>
</datafield>
```

The problem must be in [line 1632 of the current morph](https://github.com/hbz/lobid-resources/blob/701e0d4c13e1627af6ccff6bf3794aec733896cd/src/main/resources/morph-hbz01-to-lobid.xml#L1632). As I don't know how to fix this I am assigning @dr0i .

@fsteeg Note that this also affects NWBib, see http://nwbib.de/HT018290299

**Comment by fsteeg** [comment]
> @fsteeg Note that this also affects NWBib, see http://nwbib.de/HT018290299

Works fine with staged switch to API 1.x: http://test.nwbib.de/HT018290299

But an issue in lobid-resources-web: http://alpha.lobid.org/resources/HT018290299
