### ISSUE TITLE
Allow references to ZDB-ID for "related" and "predecessor"

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1723]
Reported by @blackwinter :
In fields `related` and `predecessor`  are only references to  `hbz-ID (DE-605)` accepted while there are recently also `ZDB-IDs (DE-600)`. See https://github.com/hbz/limetrans/commit/4993e6fc45ce51654f4b9d5fffad760ed62bb6e8

**Comment by TobiasNx** [comment]
This should be allowed for all linked resources.

**Comment by TobiasNx** [comment]
Should the link be like this: http://ld.zdb-services.de/resource/2581964-1 or http://lobid.org/resources/2581964-1 or http://lobid.org/resources/ZDB-2581964-1

Idea would be to link to the lobid-record of the zdb entry but they lose/lost their HT-Nr.

**Comment by blackwinter** [comment]
> Should the link be like this: http://ld.zdb-services.de/resource/2581964-1 or http://lobid.org/resources/2581964-1 or http://lobid.org/resources/ZDB-2581964-1

The first alternative would mean that we wouldn't have to adapt on our side (that's what's currently used for `supplement`), the third alternative would be possible for us because we can at least differentiate between hbz IDs and ZDB IDs. But the second alternative would not work (without resorting to analyzing the ID pattern).

**Comment by acka47** [comment]
With #1709 we have set up a redirect based on the second pattern, e.g.:

```
$ curl -LI "http://alma.lobid.org/resources/1151093-6"
HTTP/1.1 301 Moved Permanently
Date: Fri, 28 Apr 2023 09:36:57 GMT
Server: Apache
Location: /resources/990054441240206441
Access-Control-Allow-Origin: *
Via: 1.1 alma.lobid.org
```

The idea was to use these IDs in the data as this is the most convenient way with regard to the combination of ETL and UI. At a later stage we should probably also add those URIs to the JSON-LD decription of the ZDB resources in the `sameAs` array, à la:

```json
"sameAs": [

    {
        "id": "http://hub.culturegraph.org/resource/HBZ-HT004563509",
        "label": "Culturegraph Ressource"
    },
    {
        "id": "http://worldcat.org/oclc/260195177",
        "label": "OCLC Ressource"
    },
    {
        "id": "http://ld.zdb-services.de/resource/1151093-6",
        "label": "ZDB-Ressource"
    },
    {
        "id": "http://lobid.org/resource/1151093-6",
        "label": "lobid-Ressource"
    }
]
```

@jenswille Good to know that this approach is problematic for you. Maybe we then must revisit this...

**Comment by blackwinter** [comment]
> With #1709 we have set up a redirect based on the second pattern

Oh, sorry, I saw this only in the context of record IDs, not links.

> Good to know that this approach is problematic for you. Maybe we then must revisit this...

Well, we have to be able to distinguish between hbz IDs and ZDB IDs. That's why we modeled it after the current implementation for `supplement`.

Even better would be if you included the ISIL prefix ;) (I.e., `http://lobid.org/resource/(DE-605)HT004563509` and `http://lobid.org/resource/(DE-600)1151093-6`, resp.) But I guess that's too intrusive?

**Comment by acka47** [comment]
> Even better would be if you included the ISIL prefix ;) (I.e., http://lobid.org/resource/(DE-605)HT004563509 and http://lobid.org/resource/(DE-600)1151093-6, resp.) But I guess that's too intrusive?

Yes, I think so too.

To me it looks like we should choose the third approach @TobiasNx suggested, e.g. `http://lobid.org/resources/ZDB-2581964-1`. @fsteeg Is there any problem to adjust the solution form #1709 according so that the following would happen?

```
$ curl -LI "http://lobid.org/resources/ZDB-1151093-6"
HTTP/1.1 301 Moved Permanently
Date: Fri, 28 Apr 2023 09:36:57 GMT
Server: Apache
Location: /resources/990054441240206441
Access-Control-Allow-Origin: *
Via: 1.1 alma.lobid.org
```

**Comment by blackwinter** [comment]
> To me it looks like we should choose the third approach @TobiasNx suggested, e.g. `http://lobid.org/resources/ZDB-2581964-1`.

Okay. This will be changed globally then, right? (I.e., also for `supplement`.)

**Comment by fsteeg** [comment]
> @fsteeg Is there any problem to adjust the solution form https://github.com/hbz/lobid-resources/issues/1709 [to ZDB-2581964-1]

No, that should work.

**Comment by TobiasNx** [comment]
@blackwinter will be productive on monday

**Comment by blackwinter** [comment]
Great, thanks!

**Comment by TobiasNx** [comment]
we already run the fulldump index: http://lobid.org/resources/991005935279706485.json seems to work!

**Comment by dr0i** [comment]
Going to close this as completed with approved results.
