### ISSUE TITLE
API doc annotations: update the contents mentioning MAB fields, or remove it all

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#1725]
Came up in https://github.com/hbz/lobid-resources/issues/1698

See annotations starting at http://test.lobid.org/resources/api#buch

**Comment by TobiasNx** [comment]
@fsteeg or @acka47 could you have a look if the changes are sufficient? https://lobid.org/resources/api

**Comment by TobiasNx** [comment]
> I also adjusted this one but am not actually sure whether each entry has at least one type in addition to `BibliographicResource`: https://hypothes.is/a/vWAhliUDEeeonAPlpXnwqA Please correct it, if wrong.

There is at least `Miscellaneous` besides `BibliographicResource`

https://github.com/hbz/lobid-resources/blob/2c1d7fa315aee8cd37c0d76e1aa476006760ba42/src/main/resources/alma/fix/mediumAndType.fix#L712-L719
