### ISSUE TITLE
Provide organisation labels in `hasItem.heldBy.label`

### ISSUE THREAD

**Issue by blackwinter** [hbz/lobid-resources#1734]
In the context of the DigiBib union catalogue, we're getting requests to display organisation labels instead of (or in addition to) the arcane ISILs. One solution would be to include these labels in the index, alongside `isil` and `id`. They need not be searchable (for our use case), but we might want to be able to aggregate them (possibly as `label.raw` to keep in line with other `label` fields).

@acka47: Would you agree to adding such a field to the index/API?

@dr0i: Do you have any objections, e.g. regarding index size?

Clarification: The `label` field is already [present](https://lobid.org/resources/990124729640206441.json), but with a fixed value of "lobid Organisation".

```diff
--- before
+++ after
@@ -7,7 +7,7 @@
   "heldBy" : {
     "id" : "http://lobid.org/organisations/DE-468#!",
     "isil" : "DE-468",
-    "label" : "lobid Organisation"
+    "label" : "Universitätsbibliothek Wuppertal"
   },
   "id" : "http://lobid.org/items/990124729640206441:DE-468:23120393580006447#!"
 }
```

**Comment by dr0i** [comment]
I don't have any objections.

**Comment by acka47** [comment]
+1 for adding it, "lobid Organisation" always was a workaround. We could atuomatically create from lobid-organisations a map to be used in the transformation.

**Comment by TobiasNx** [comment]
Do we have a map for lobid organisations -> labels. That would be nice.

**Comment by blackwinter** [comment]
That's great news, thank you.

I'm not sure I'd be able to come up with an implementation, so I'm assigning @TobiasNx for now. If you can hook me up with a map from lobid-organisations (`isil` -> `name`), I can give it a try, though.

**Comment by TobiasNx** [comment]
See the MR https://github.com/hbz/lobid-resources/pull/1736

**Comment by dr0i** [comment]
To be reviewed next Monday.

**Comment by blackwinter** [comment]
Aggregation is fixed, thanks!
