### ISSUE TITLE
Missing closing "]" in publication.location

### ISSUE THREAD

**Issue by UBmakla** [hbz/lobid-resources#1735]
in some cases, e.g. 990049113390206441

**Comment by TobiasNx** [comment]
@UBmakla : Should I get rid of all bracket or keep them:
`Aachen [u.a.]` or `Aachen u.a.`

**Comment by UBmakla** [comment]
I think the hardcore catalogers want to keep the bracket because [u.a.] is a different statement than u.a.

**Comment by TobiasNx** [comment]
okay, I just wanted to check, since we kicked out some "Sonderzeichen" along the way, e.g. `[Aachen]` => `Aachen`

**Comment by dr0i** [comment]
Will be deployed next Monday.
