### ISSUE TITLE
Update index config for describedBy

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1746]
We have rearranged the location of `dateModified`, `dateCreated`, `sourceOrganization`, `modifiedBy` etc. but haven't updated the index config accordingly:

https://github.com/hbz/lobid-resources/blob/693ad01cd9260d82af472ef471c940070f9d06c8/src/main/resources/alma/index-config.json#L719-L747

NWBib editor U.P. asked us today via email to update these queries: https://github.com/hbz/nwbib/wiki/Titel-ohne-NWBib-Sortierzeichen-aber-mit-NWBib-Notationen

To make it work, for example this should give back results:

- [`describedBy.resultOf.object.modifiedBy.id:"http://lobid.org/organisations/DE-6#!"`](https://lobid.org/resources/search?q=describedBy.resultOf.object.modifiedBy.id%3A%22http%3A%2F%2Flobid.org%2Forganisations%2FDE-5%23!%22)
- [`describedBy.resultOf.object.sourceOrganization.id:"http://lobid.org/organisations/DE-5#!"`](https://lobid.org/resources/search?q=describedBy.resultOf.object.sourceOrganization.id%3A%22http%3A%2F%2Flobid.org%2Forganisations%2FDE-5%23%21%22)

**Comment by dr0i** [comment]
Please check @acka47 if this can be closed.
