### ISSUE TITLE
Improve fullTextOnline

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1757]
http://lobid.org/resources/99372423567906441

and other missing links.

**Comment by TobiasNx** [comment]
A lot of improvements were done but the example http://lobid.org/resources/99372423567906441 cannot get a proper fullTextOnline since the link is missing:

```
<datafield tag="856" ind1="4" ind2=" ">
<subfield code="x">Archivierte Online-Ressource</subfield>
<subfield code="x">Langzeitarchivierung</subfield>
<subfield code="z">kostenfrei</subfield>
<subfield code="3">Volltext</subfield>
</datafield>
```

This could be a problem of Eduweb @acka47

**Comment by acka47** [comment]
+1 Will contact Edoweb re. incorrect catalogued resource. Closing

**Comment by acka47** [comment]
> Will contact Edoweb re. incorrect catalogued resource

Did so, got the following answer:

On 22.03.24 14:09, B.M. wrote:
> der Satz ist so erfasst wie alle Edoweb-Sätze. Der erste Teil (ohne URL) wird bei der Katalogisierung erfasst, der zweite Teil (mit URL) wird automatisch aus edoweb zurückgeschrieben, sobald eine URN erzeugt wurde (also nachträglich). Sie haben uns jetzt darauf aufmerksam gemacht, dass die Informationen teilweise gedoppelt sind. Bisher hat dies nie jemanden gestört, wobei wir uns jetzt fragen, ob wir dies künftig so weiterführen wollen.
> 
> Bereitet dies denn irgendwo Probleme? Denn es sind ja zahlreiche Sätze davon betroffen.

Now I wonder, where the third link in https://lobid.org/resources/99372423567906441 with "--" is coming from. Reopening this to understand this better.

**Comment by TobiasNx** [comment]
@maipet  is handling the missing link in another ticket:
https://github.com/hbz/lobid-resources/issues/1883

**Comment by TobiasNx** [comment]
> > Will contact Edoweb re. incorrect catalogued resource
> 
> Did so, got the following answer:
> 
> On 22.03.24 14:09, B.M. wrote:
> 
> > der Satz ist so erfasst wie alle Edoweb-Sätze. Der erste Teil (ohne URL) wird bei der Katalogisierung erfasst, der zweite Teil (mit URL) wird automatisch aus edoweb zurückgeschrieben, sobald eine URN erzeugt wurde (also nachträglich). Sie haben uns jetzt darauf aufmerksam gemacht, dass die Informationen teilweise gedoppelt sind. Bisher hat dies nie jemanden gestört, wobei wir uns jetzt fragen, ob wir dies künftig so weiterführen wollen.
> > Bereitet dies denn irgendwo Probleme? Denn es sind ja zahlreiche Sätze davon betroffen.
> 
> Now I wonder, where the third link in [lobid.org/resources/99372423567906441](https://lobid.org/resources/99372423567906441) with "--" is coming from. Reopening this to understand this better.

I think this workflow of eduweb is ignoring the "[Geschäftsgangsregelung Elektronische Ressourcen](https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=1000472600)" of hbz. This workflow separates the infos about the link from the link.

**Comment by acka47** [comment]
> I think this workflow of eduweb is ignoring the "[Geschäftsgangsregelung Elektronische Ressourcen](https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=1000472600)" of hbz. This workflow separates the infos about the link from the link.

Yes, it does not look right to me too to do it like this. However, I assume this already was discussed between LBZ and hbz in the past and they have settled on this practice. Regarding the concrete open question where the third link in [lobid.org/resources/99372423567906441](https://lobid.org/resources/99372423567906441) with "--" is coming from: B.M. let me know that this is not the source of this problem:

**Comment by TobiasNx** [comment]
This seems resolved. Closing.
