### ISSUE TITLE
Provide separate mapping for MARC `245$$a` without `$$p`

### ISSUE THREAD

**Issue by blackwinter** [hbz/lobid-resources#1764]
In order to create a label for the superordinate work, we need to be able to address MARC `245$$a` separately (e.g., `titleMain`).

Originally reported as DigiBib-Ticket#2023051550334528.

Example: [990083161270206441](https://lobid.org/resources/990083161270206441)

**Comment by blackwinter** [comment]
Alternatively, it might make sense to set `isPartOf.hasSuperordinate.label` to `245$$a`. (Only if `$$p` exists?)

@acka47, @TobiasNx: What do you think?

(@TobiasNx: You can assign me for the actual implementation once the spec is clear.)

**Comment by acka47** [comment]
+1 for the `isPartOf.hasSuperordinate.label` approach.
