### ISSUE TITLE
Add missing zdbIds

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1776]
ZDB Ids were only mapped if they were stated in 035 and have prefix (DE-600). But There are more ZDB IDs in 016 and 035 if Prefix (DE-599).

See: https://github.com/hbz/lobid-resources/pull/1774

**Comment by TobiasNx** [comment]
While identifying more ZDB IDs in 016 I also saw that there are dnbIds for their records. I added these to the mapping.

**Comment by dr0i** [comment]
Is this done? Looks good IMO http://lobid.org/resources/990053976760206441.json.

**Comment by TobiasNx** [comment]
+1 closing
