### ISSUE TITLE
NWBib titles with missing inCollection statement

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1780]
Reported today by U.P. via NWBib mailing list.

Am 01.06.23 um 10:23 schrieb U.P.:
> ... Allerdings habe ich jetzt in der Kategorie 2.3. "die als letztes von der ULB Düsseldorf (DE-61) modifiziert wurden" viele Titel gefunden, die sehr wohl das Feld 960 mit dem Abrufzeichen korrekt enthalten haben. Das konnte ich mir nicht erklären. 

See [this list](https://lobid.org/resources/search?q=subject.source.id%3A%22https%3A%2F%2Fnwbib.de%2Fsubjects%22+OR+_exists_%3Aspatial+AND+NOT+inCollection.id%3A%22http%3A%2F%2Flobid.org%2Fresources%2FHT014176012%23%21%22+AND+describedBy.resultOf.object.modifiedBy.id%3A%22http%3A%2F%2Flobid.org%2Forganisations%2FDE-61%23%21%22). All titles listed contain the following in the MARC source:

```xml
<datafield tag="960" ind1="1" ind2=" ">
  <subfield code="n">NWBib-61</subfield>
</datafield>
```

**Comment by TobiasNx** [comment]
These records are IZ therefore are not mapped to `inCollection=NWBib`. Most have duplicate NZ records that are `inCollection=NWBib`. Two records are not duplicates but IZ and also have `hbzId` (HT-Nummern).

IZ of ULB Düsseldorf	49HBZ_DUE	6443	DE-61
https://lobid.org/resources/990014631590206443 (no duplicate, but has HT-Number HT013463929)
https://lobid.org/resources/9947512689906443 (duplicate of NZ https://lobid.org/resources/99371658744506441)
https://lobid.org/resources/9947454084406443 (Duplicate of NZ https://lobid.org/resources/990220552310206441 -  https://lobid.org/resources/search?q=9783928844680 See also #1818) 
https://lobid.org/resources/9947564189506443 (Duplicate of NZ https://lobid.org/resources/99372477766406441)
https://lobid.org/resources/990012684090206443 (no duplicate, but has HT-Number HT009513815)

IZ of HS Ruhr West	49HBZ_RUW	6453	DE-1393:
https://lobid.org/resources/991004124708806453 (Duplicate of NZ https://lobid.org/resources/99371670144506441)

**Comment by TobiasNx** [comment]
There are 28 records with nwbib-refrence that are not part of nwbib:
https://lobid.org/resources/search?q=subject.source.id%3A%22https%3A%2F%2Fnwbib.de%2Fsubjects%22+OR+spatial.source.id%3A%22https%3A%2F%2Fnwbib.de%2Fspatial%22+AND+NOT+inCollection.id%3A%22http%3A%2F%2Flobid.org%2Fresources%2FHT014176012%23%21%22

**Comment by TobiasNx** [comment]
@acka47 can this be closed?

**Comment by acka47** [comment]
Yes, closing.
