### ISSUE TITLE
Add inCollection statement for "laufend ausgewertete NWBib-Zeitschriften"

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1781]
Prerequisite for https://github.com/hbz/nwbib/issues/611.

The necessary information is in MARC field `960` and can come in three variations:

1. periodicals used by DE-6, e.g. [990055981810206441](https://alma.lobid.org/marcxml/990055981810206441)

```xml
<datafield tag="960" ind1="1" ind2=" ">
  <subfield code="n">NWBib-Zeitschrift-6</subfield>
</datafield>
```
2. periodicals used by DE-61, e.g. [990054345550206441](https://alma.lobid.org/marcxml/990054345550206441)
```xml
<datafield tag="960" ind1="1" ind2=" ">
  <subfield code="n">NWBib-Zeitschrift-61</subfield>
</datafield>
```
Edit: ~~3. other periodicals, e.g. [990109712970206441](https://alma.lobid.org/marcxml/990109712970206441)~~
```xml
<datafield tag="960" ind1="1" ind2=" ">
   <subfield code="n">NWBib-Zeitschrift</subfield>
</datafield>
```

The following `inCollection` statement should be added:

```json
{
   "id":"https://nwbib.de/journals",
   "label":"Laufend ausgewertete NWBib-Zeitschriften",
   "type":[
      "Collection"
   ]
}
```

**Comment by acka47** [comment]
> 3. other periodicals, e.g. [990109712970206441](https://alma.lobid.org/marcxml/990109712970206441)
```xml
<datafield tag="960" ind1="1" ind2=" ">
   <subfield code="n">NWBib-Zeitschrift</subfield>
</datafield>

U.P. just told us via the mailing list to **not** include these but only entries with `NWBib-Zeitschrift-6` or `NWBib-Zeitschrift-61`:

Am 01.06.23 um 16:18 schrieb U.P.:
> einige Zeitschriften, die wir aus Düsseldorf in der Liste der laufend ausgewerteten Zeitschriften noch haben, erscheinen nicht mehr. Bei einigen ist es zweifelhaft und muss noch geprüft werden. Diese Zeitschriften haben wir nicht mit dem erweiterten Abrufreichen "NWBib-Zeitschrift-61" versehen. Das ist also durchaus beabsichtigt. Auch die Bonner Beethoven-Studien sind so ein Fall. Diese Fälle haben wir ja im Blick und würden sie später, wenn sie doch noch weiter erscheinen, mit dem erweiterten Abrufzeichen versehen können, nicht wahr? Sie könnten aus Düsseldorfer Sicht also wirklich nur die in die neue Liste packen, die das erweiterte Abrufzeichen haben.

**Comment by TobiasNx** [comment]
the example for the not matching variant, now matches in the source data:

https://alma.lobid.org/marcxml/990109712970206441



<datafield tag="960" ind1="1" ind2=" ">
<subfield code="n">NWBib-Zeitschrift-61</subfield>
</datafield>


otherwise @acka47 can this be closed?

**Comment by acka47** [comment]
Yes, this looks good. Closing.
