### ISSUE TITLE
Missing subfield `689.z`

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1787]
Am 06.06.23 um 17:23 schrieb I.N.:
> Noch ein Nachtrag zu den mehrteiligen GND-Schlagwörtern:
> 
> Das Unterfeld *z* Region wurde abgeschnitten.
> 
> Beispiel: https://nwbib.de/990218000370206441 

From the [MARC source]():

```xml
<datafield tag="689" ind1="0" ind2="1">
  <subfield code="a">Rhein-Ruhr</subfield>
  <subfield code="z">Region</subfield>
  <subfield code="D">g</subfield>
  <subfield code="0">(DE-588)4119982-0</subfield>
  <subfield code="0">
https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=idn=041199820
  </subfield>
  <subfield code="0">http://viaf.org/viaf/sourceID/DNB|041199820</subfield>
  <subfield code="B">GND-041199820</subfield>
</datafield>
```

Looking at [the old aleph lobid entry](http://aleph.lobid.org/resources/HT019298495,) I guess it should be added comma-space-seperated after the string from subfield `a`: "Rhein-Ruhr, Region"

**Comment by dr0i** [comment]
Will be deployed at Monday.
Reopened so that then customers are going to  be informed.

**Comment by TobiasNx** [comment]
@acka47 you can feedback NWBIB that this is fixed. See the Schlagwort Rhein-Ruhr (Region) here: https://nwbib.de/990218000370206441
