### ISSUE TITLE
dc vs dcterms 

### ISSUE THREAD

**Issue by nichtich** [hbz/lobid-resources#1796]
The [DINI AG KIM Recommendations tell](https://wiki.dnb.de/display/DINIAGKIM/MARC+21-RDF-Mapping) to use `dc:title` (<http://purl.org/dc/elements/1.1/title>) but lobid-resources use `dct:title`(<http://purl.org/dc/terms/title>). Same may apply for other properties but I have not checked.

[Comparing RDF of German library networks](https://github.com/dini-ag-kim/library-data-in-rdf/issues/2) I found mixed results. In theory I understand the intended difference between `dc:` (IRI value) and `dct:` (string value) but in practice it is not applied consistently anyway, so any data integration would required to normalize to one preferred form anyway. 

So change lobid-resources to follow the recommendations, change the recommendations or just keep it as it is?

**Comment by acka47** [comment]
> So change lobid-resources to follow the recommendations, change the recommendations or just keep it as it is?

I am quite sure we did this intentionally to consistently use one of the DC vocabs. As we use several properties from dct, we just also used dct where there is also a dc elements property.

**Comment by nichtich** [comment]
Closed in favour of https://github.com/dini-ag-kim/library-data-in-rdf/issues/4
