### ISSUE TITLE
Pub date 0000

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1799]
Not plausible pub date:
```
http://lobid.org/resources/990119186660206441.json
```
due to:

```
<datafield tag="264" ind1="3" ind2="1">
<subfield code="a">Middletown, CT</subfield>
<subfield code="b">Xerox Education Publications</subfield>
<subfield code="c">0000-</subfield>
</datafield>
```

**Comment by dr0i** [comment]
I wrote to cataloguer N.D. to fix the data.

**Comment by dr0i** [comment]
From @maipet:
> Aber es scheint keine globale Lösung: "Liegt 
kein Erscheinungsdatum in der Ressource vor und kann auch nicht 
ermittelt werden, wird das Feld mit einem Füllzeichen (0000) besetzt". 
[https://zeitschriftendatenbank.de/fileadmin/user_upload/ZDB/pdf/zdbformat/1100.pdf]"

**Comment by dr0i** [comment]
Should be deployed next Monday.
Closing.
