### ISSUE TITLE
Update URIs for NWBib, Edoweb, RPB & add collectedBy links for ZDB

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#180]
We alreay link to http://lobid.org/resources/NWBib and http://lobid.org/resources/Edoweb in the data but they currently don't resolve. The RDF descriptions (in Turtle) are lying in an Etherpad of which I won't post the URL here.

**Comment by dr0i** [comment]
Note for easier analyzing:  the old uris (resource without "s") work:
http://lobid.org/resource/NWBib and http://lobid.org/resource/Edoweb

**Comment by dr0i** [comment]
You are right in your intention to index the data to the new elasticsearch-cluster. A merley proxying to the old working uris won't help us in the long term.

**Comment by acka47** [comment]
Same for RPB, http://lobid.org/resource/RPB

**Comment by acka47** [comment]
As mentione din #364, we could also outsource the process of additional data creation and storage to Wikidata by using Wikidata URIs for collections.

**Comment by acka47** [comment]
We will also add `collectedBystatements for ZDB resources within this issue, see https://github.com/hbz/lobid-resources/issues/364#issuecomment-291503207.

Today we decided to use Wikidata for the `collectedBy` statements and I adjusted the issue title accordingly. However, I just became aware that we already have URIs for the regional bibliographies and edoweb in lobid-resources, stemming from the ZDB. It probably makes more sense to use these. Here are the URIs:

- http://lobid.org/resource/NWBib --> [Wikidata](http://www.wikidata.org/entity/Q1237350); [lobid](http://lobid.org/resources/HT014176012#!)
- http://lobid.org/resource/Edoweb --> [Wikidata](http://www.wikidata.org/entity/Q29111105) ; [lobid](http://lobid.org/resources/HT016925914#!)
- http://lobid.org/resource/RPB --> [Wikidata](); [lobid](http://lobid.org/resources/HT013494180#!)
- Even the ZDB is recorded by itself, see [lobid](http://lobid.org/resources/HT014846970#!) ; [Wikidata](http://www.wikidata.org/entity/Q186844)

I made the issue title more general to leave the decision open.

**Comment by acka47** [comment]
We decided offline to use the lobid URIs.

**Comment by acka47** [comment]
I will also replace `holding:collectedBy` with `lv:inCollection` within this issue.

**Comment by acka47** [comment]
Deployed to test, see http://test.lobid.org/resources/search?q=inCollection.id:*&format=json

**Comment by ChristophEwertowski** [comment]
+1

**Comment by acka47** [comment]
Moving to deploy, we can follow up with FRL later if needed.
