### ISSUE TITLE
Contact Wave 3 libraries concerning mapping for sublibrary code to Isil to keep the sublibraries in the index.

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1802]
#1652 We introduced a mapping list for wave 1 and wave 2 libraries if they provided one to match the none unique sublibrary codes to Isils. We combine them with the main library ALMA id here: https://github.com/hbz/lookup-tables/tree/master/data/almaSublibraryCode2Isil So that we can use it later in the transformation.

This is especially important for Bonn and Köln.

**Comment by dr0i** [comment]
Seems to be solved, having a quick look at the linked `lookup-tables`. Can you confirm @blackwinter ?

**Comment by blackwinter** [comment]
Libraries have been informed via FEx Daten, yes.
