### ISSUE TITLE
Prefer $n ("Exemplarsignatur") instead of $c("Signatur") for callNumber in ITM

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1803]
The callNumber in ITM can creates for DigiBib dubplicate entries
because the callNumber in ITM $c can be the same in different ITM objects,
but $n differs therefore we should use $n before $c if available.

**Comment by blackwinter** [comment]
Shouldn't we await the outcome of the FEx meeting next month?

**Comment by TobiasNx** [comment]
> Shouldn't we await the outcome of the FEx meeting next month?
I already prepared the PR and needed the ticket for documentation.
We can do this! Then I push this back the PR to draft status.

**Comment by TobiasNx** [comment]
Discussed in FEx Daten Group: Prefer $z (Temporary CallNumber) before $n (Item callNumber) before $c (CallNumber).

**Comment by TobiasNx** [comment]
This is already in production.
