### ISSUE TITLE
Implement MARC `264$#3$` (Manufacture)

### ISSUE THREAD

**Issue by blackwinter** [hbz/lobid-resources#1806]
[HT016692738](https://lobid.org/resources/990183958380206441) should include the "Manufacture place and date" ([MARC 264$#3$](https://www.loc.gov/marc/bibliographic/bd264.html)); possibly modelled after `264$#1$` (`publication`).

```xml
<datafield tag="264" ind1=" " ind2="3">
  <subfield code="a">Marsberg</subfield>
  <subfield code="b">Boxberger</subfield>
  <subfield code="c">2010</subfield>
</datafield>
```

Also: Would it make sense to use [008/07-10](https://www.loc.gov/marc/bibliographic/bd008a.html) (Date 1) as fallback for `publication.startDate`?

Originally reported as DigiBib-Ticket#2023062250336954.

**Comment by TobiasNx** [comment]
It seems that there are no fitting properties for `manufacture/production` that correspondent to `publication` 

Perhaps:
http://www.rdaregistry.info/Elements/m/#P30053

But seems to be a note element.

**Comment by TobiasNx** [comment]
> [HT016692738](https://lobid.org/resources/990183958380206441) should include the "Manufacture place and date" ([MARC 264$#3$](https://www.loc.gov/marc/bibliographic/bd264.html)); possibly modelled after `264$#1$` (`publication`).
> 
> ```
> <datafield tag="264" ind1=" " ind2="3">
>   <subfield code="a">Marsberg</subfield>
>   <subfield code="b">Boxberger</subfield>
>   <subfield code="c">2010</subfield>
> </datafield>
> ```
> 
> Also: Would it make sense to use [008/07-10](https://www.loc.gov/marc/bibliographic/bd008a.html) (Date 1) as fallback for `publication.startDate`?
> 
> Originally reported as DigiBib-Ticket#2023062250336954.

btw.:

in the DNB there is also another publisher listed: https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=idn%3D1009900439

**Comment by acka47** [comment]
Re. the data modelling in RDF, there are excisting properties, both in schema.org and RDA unconstrained properties:

schema.org has two bespoke properties that would be used _instead_ of the event-based approach we have for `publication` (originated in https://github.com/lobid/lodmill/issues/730):
- [`sdo:productionDate`](https://schema.org/productionDate)
- [`sdo:productionCompany`](https://schema.org/productionCompany)

What is missing for our needs is `productionLocation`. Also, if we used this, we would have it modeled in a completely different way than `publication`. Thus, this does not fit our use case.

It is similar with RDA:
- [`rdau:P60072](http://rdaregistry.info/Elements/u/P60072) "has date of manufacture"
- [`rdau:P60162`](http://rdaregistry.info/Elements/u/P60162) "has place of manufacture"
- [`rdau:P60443`](http://rdaregistry.info/Elements/u/P60443) "has manufacturer" resp. [`rdau:P60546`](http://rdaregistry.info/Elements/u/P60546) "has name of manufacturer"
- many more, see http://www.rdaregistry.info/Elements/u/ and search for "manufacture"

However, RDA has the same problem that it would be modeled in a completely different way than `publication`. Thus the general approach in #1896 makes sense. I will comment on details in the PR.

**Comment by TobiasNx** [comment]
https://lobid.org/resources/990183958380206441.json

**Comment by TobiasNx** [comment]
This should be added to the GUI too and also the lobid vocab should be updated.

**Comment by dr0i** [comment]
The `manufacture` and `manufacturedBy` properties are missing in the context(<= labels.json).

**Comment by dr0i** [comment]
Is this solved @TobiasNx ?

**Comment by dr0i** [comment]
If I recollect properly we agreed at Friday that this issue can be closed and be opened again if anyone needs it actually. @TobiasNx said this issue is solved at nwbib repo and wanted to link to respectively PR so that we can easily copy the code if need arises.

**Comment by TobiasNx** [comment]
This was the issue in nwbib: https://github.com/hbz/nwbib/issues/627 and this the PR: https://github.com/hbz/nwbib/pull/640

So then we decide to close this.
Until somebody asks for `manufacturer` in the GUI.
