### ISSUE TITLE
Missing title in Alma

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#1808]
Exists in Aleph, but not in Alma: http://aleph.lobid.org/resources/HT021686606

Edit: once fixed, we need to update `almaMmsId2rpbId.tsv`, see https://github.com/hbz/lookup-tables/pull/18

**Comment by TobiasNx** [comment]
@blackwinter 
This is a [DE-107](http://lobid.org/organisations/DE-107#!)-Publication. Are they part of the ALMA-Data?
Or can you check if the record is available as MARC via the publishing?

**Comment by blackwinter** [comment]
> This is a [DE-107](http://lobid.org/organisations/DE-107#!)-Publication. Are they part of the ALMA-Data?

Yes, `49HBZ_BRIDGE_LBZ`.

> Or can you check if the record is available as MARC via the publishing?

I can't find it.

**Comment by TobiasNx** [comment]
@fsteeg could you feedback this to RPB/LBZ?

**Comment by fsteeg** [comment]
> @fsteeg could you feedback this to RPB/LBZ?

Got feedback from LBZ in [RPB-28](https://jira.hbz-nrw.de/browse/RPB-28?focusedId=305457&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-305457), will be checked by Verbundgruppe.

**Comment by TobiasNx** [comment]
http://lobid.org/resources/HT021686606

@fsteeg is now available can the isse be closed?

**Comment by fsteeg** [comment]
Added the missing `almaMmsId` in [1f7e1ef](https://github.com/hbz/lookup-tables/commit/1f7e1ef65f0627523bd67793f68a107dcca7dee8), closing.
