### ISSUE TITLE
Question about records from Alma-IZ

### ISSUE THREAD

**Issue by hagbeck** [hbz/lobid-resources#1817]
Is it possible to select all records from our Alma-IZ in lobid-resources? An example of such a record is 
http://lobid.org/resources/991013591076006445.json
It would be nice to select them.

**Comment by blackwinter** [comment]
This query should do it: [`hasItem.id:http\:\/\/lobid.org\/items\/*6445\:DE\-290\:*`](https://lobid.org/resources/search?q=hasItem.id%3Ahttp%5C%3A%5C%2F%5C%2Flobid.org%5C%2Fitems%5C%2F*6445%5C%3ADE%5C-290%5C%3A*)

Basically every MMS ID that ends in `6445`, i.e. your institution ID; with your ISIL thrown in for proper anchoring. In theory, `...\/*6445#\!` should also work, but it yields fewer hits (@TobiasNx can probably explain why).

**Comment by hagbeck** [comment]
Thanks! That helps.
