### ISSUE TITLE
Missing inCollection despite of NWBib marker

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1818]
Reported by NWbib editors from Düsseldorf (U.P.) via email on 2023-06-20), see [this query](https://lobid.org/resources/search?q=%28subject.source.id%3A%22https%3A%2F%2Fnwbib.de%2Fsubjects%22+OR+_exists_%3Aspatial%29+AND+NOT+inCollection.id%3A%22http%3A%2F%2Flobid.org%2Fresources%2FHT014176012%23%21%22+AND+describedBy.resultOf.object.modifiedBy.id%3A%22http%3A%2F%2Flobid.org%2Forganisations%2FDE-61%23%21%22) from https://github.com/hbz/nwbib/wiki/Titel-ohne-NWBib-Sortierzeichen-aber-mit-NWBib-Notationen.

Example 9947454084406443 ([JSON](https://lobid.org/resources/9947454084406443.json), [MARC](https://alma.lobid.org/marcxml/9947454084406443)).

NWBib marker:

```xml
<datafield tag="960" ind1="1" ind2=" ">
  <subfield code="n">NWBib-61</subfield>
</datafield>
```

...and no `inCollection` in the JSON.

**Comment by TobiasNx** [comment]
I should have seen that earlier. We only include resources that are part of the NZ fka. Verbundkatalog 9947454084406443, seems to be a duplicate: http://lobid.org/resources/search?q=isbn%3A9783928844680

http://lobid.org/resources/990220552310206441 is the NZ title and also part of the NWBib: http://nwbib.de/990220552310206441

9947454084406443 is a local title IZ publication.
