### ISSUE TITLE
Index `serialNumber`

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1819]
Reported by @cpiesche on 19.07.23 10:32 via email:

> ich habe mal eine Frage zur lobid API. Ich nutze diese, um beim Anlegen von
> Digitalisierungsaufträgen zu prüfen, ob das genannte Exemplar im Verbund
> ist. Dazu nutze ich die Abfrage:
> 
> const url = "https://lobid.org/resources/search?q=hasItem.callNumber:" +
> <value> + "&format=json";
> 
> URL:
> https://lobid.org/resources/search?q=hasItem.callNumber:RHSA66-1&format=json
> 
> Allerdings ist mir aufgefallen, dass einige Signaturen der Exemplare auch im
> Feld serialNumer auftauchen. Das sind dann irgendwelche Spezialfälle,
> Bindeeinheiten und frag mich nicht, was noch. Daher wollte ich die gleiche
> Abfrage auch noch auf das zweite Feld machen, also:
> 
> const url = "https://lobid.org/resources/search?q=hasItem.serialNumber:" +
> <value> + "&format=json";
> 
> URL:
> https://lobid.org/resources/search?q=hasItem.serialNumber:RHSA66-1&format=js
> on
> 
> Die erste Abfrage funktioniert, bei der zweiten bekomme ich einen Bad
> Request zurück. Kannst du mir sagen, woran das liegt?

The problem is that the field `serialNumber` currently isnot indexed, see https://github.com/hbz/lobid-resources/blob/7394e33f59dc22cf2073ad9c3a32e6c832f575c9/src/main/resources/alma/index-config.json#L330-L333

**Comment by TobiasNx** [comment]
For some context here:
https://github.com/hbz/lobid-resources/issues/1466

`serialNumber` is the element in ALMA stated as Buchungsnummer/Barcode ITM $b. It is not a traditional Barcode.

But index `serialNumber` should be no problem to change for @dr0i

**Comment by cpiesche** [comment]
Many thanks from my side!

**Comment by TobiasNx** [comment]
@cpiesche this is working now: https://lobid.org/resources/search?q=hasItem.serialNumber:RHSA66-1&format=json
