### ISSUE TITLE
Broken contact link

### ISSUE THREAD

**Issue by Phu2** [hbz/lobid-resources#1820]
Reported via email today:

> Der Kontaktlink auf https://lobid.org/contact in  https://lobid.org/resources/dataset funktioniert nicht.

I think we need to update the contact info in https://github.com/hbz/lobid-resources/blob/master/web/conf/dataset.jsonld#L59

**Comment by acka47** [comment]
Sorry, had not checked my mail prior and created a duplicate at #1821 .

**Comment by Phu2** [comment]
Superseded by https://github.com/hbz/lobid-resources/issues/1821
