### ISSUE TITLE
ISSN with -

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1828]
`-` needs do be deleted  in ISSN: http://lobid.org/resources/99370698912306441

Based on Issue in JIRA bei Fachrepositorium Lebenswissenschaften.

**Comment by TobiasNx** [comment]
@acka47 or @fsteeg is it intentional that the "related" ISSN is presented in the GUI:
![grafik](https://github.com/hbz/lobid-resources/assets/61879957/465ae799-af33-4965-bee1-f70a08864407)

```
  "related": [
    {
      "issn": "2364-4893"
    }
  ]
```

based on: http://lobid.org/resources/99370698912306441.json

**Comment by TobiasNx** [comment]
Ping @fsteeg and @acka47 

I assume this showing the `related.issn` is an error, right.
The GUI is stating the wrong ISSN. But if I am not mistaken, the code in the detail page is not
specific which ISSN it shows:

https://github.com/hbz/lobid-resources/blob/0e134f96cfc1a158b5a377f87042a85a016c3403/web/app/views/tags/result_doc.scala.html#L192-L193

**Comment by fsteeg** [comment]
> I assume this showing the `related.issn` is an error, right.

Yes, same as in NWBib (https://github.com/hbz/nwbib/issues/636), where it's fixed (https://github.com/hbz/nwbib/pull/644).

**Comment by TobiasNx** [comment]
@dr0i GUI is still wrong, isn't it. at least it is showing the `related.issn` but there is also a separate ticket:  #1829

**Comment by dr0i** [comment]
@TobiasNx yep - this is an other issue
