### ISSUE TITLE
Add "beigefügtes Werk" (249)-Info to `otherTitleInformation`

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1836]
Was decided in: https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=19136520

> Beigef., enth. Werk , nicht standardm. NE
	[HT003309369](http://lobid.org/resource/HT003309369)
	beigefügtes Werk in lobid über rdvocab:otherTitleInformation angegeben
(nur String, keine Autorangabe etc. für beigefügtes Werk in VK wie lobid)

Seems to be never be implemented

**Comment by TobiasNx** [comment]
@acka47 while wiki entry says we should use `otherTitleInformation`.

There is a NWBib Ticket that demands adding 249. Would `otherTitleInformation` fit their demand or not?
https://github.com/hbz/nwbib/issues/589

**Comment by TobiasNx** [comment]
For this element we also should add alternateGraphicRepresentation

**Comment by TobiasNx** [comment]
> @acka47 while wiki entry says we should use `otherTitleInformation`.
> 
> There is a NWBib Ticket that demands adding 249. Would `otherTitleInformation` fit their demand or not? [hbz/nwbib#589](https://github.com/hbz/nwbib/issues/589)

Ping @acka47

**Comment by TobiasNx** [comment]
@dr0i is this deployed?

**Comment by dr0i** [comment]
Yep - there was a problem with automatic deployment. Should be fixed now.
Can be reviewed at stage- where alos the RVK is enriched. But we may also wait till nex Monday to have proof that production is fine.

**Comment by TobiasNx** [comment]
> Was decided in: [service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=19136520](https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=19136520)
> 
> > Beigef., enth. Werk , nicht standardm. NE
> > [HT003309369](http://lobid.org/resource/HT003309369)
> > beigefügtes Werk in lobid über rdvocab:otherTitleInformation angegeben
> > (nur String, keine Autorangabe etc. für beigefügtes Werk in VK wie lobid)
> 
> Seems to be never be implemented

[HT003309369](http://lobid.org/resource/HT003309369)
it now looks like this:

```
 "otherTitleInformation": [
    "Mit einer Entgegnung \"Religion und Psychologie\" / von C. G. Jung"
  ],
```
