### ISSUE TITLE
GUI: Missing link to contained resources

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1837]
Was:
![grafik](https://github.com/hbz/lobid-resources/assets/61879957/8e7c1259-a5f7-4b69-89bb-23097c57755b)

http://aleph.lobid.org/resources/HT003031748#!

This is missing now: http://lobid.org/resources/990062687040206441#!

**Comment by dr0i** [comment]
Checked it, it's there now.
Closing.
