### ISSUE TITLE
Separate logs for Starting and Updating of the Application and for failing queries?

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1847]
Logs are overcrowded one cannot identify the running process building and updating the application.

- [x] a) I suggest we create a separate a second log for queries.
- [ ] b) Also the logs mix the errors for different indexes. At least we should make explicit which error is connected to which index, if possible,
this would espacially be useful if switching fails.
- [ ] c) Also our own services should provide a marker that the failing queries are coming from them, at the moment we only get anonymous `application-akka.actor.default-dispatcher`references.

**Comment by dr0i** [comment]
You describe 3 problems here.
a) should be solved in #1930
b) should not be a problem at all: parallel indexing is not possible (look for "ALREADY_RUNNING" in https://github.com/hbz/lobid-resources/blob/master/web/app/controllers/resources/WebhookAlmaFix.java). So, in the logs, just look for for  `using indexName: resources-alma-fix` and you will get the full index name (with the timestamnp as suffix). All consecutive logs are connected to this index.
Re c) : I don't understand what you mean by "marker". We identify the service because the log resides in the respective home directory of the application.

**Comment by TobiasNx** [comment]
> You describe 3 problems here. a) should be solved in #1930 b) should not be a problem at all: parallel indexing is not possible (look for "ALREADY_RUNNING" in https://github.com/hbz/lobid-resources/blob/master/web/app/controllers/resources/WebhookAlmaFix.java). So, in the logs, just look for for `using indexName: resources-alma-fix` and you will get the full index name (with the timestamnp as suffix). All consecutive logs are connected to this index. Re c) : I don't understand what you mean by "marker". We identify the service because the log resides in the respective home directory of the application.

The idea of a marker is just that we can better identify the source of the logged error.
One cannot identify which of our own services is querying lobid resoruces because all errors just state `application-akka.actor.default-dispatcher` if our own services would provide an `user agent` and this would be stated in the logs too, then we could better identify where an error is coming from. Perhaps the user agent statement is good for all query errors too.

**Comment by TobiasNx** [comment]
> > You describe 3 problems here. a) should be solved in #1930 b) should not be a problem at all: parallel indexing is not possible (look for "ALREADY_RUNNING" in https://github.com/hbz/lobid-resources/blob/master/web/app/controllers/resources/WebhookAlmaFix.java). So, in the logs, just look for for `using indexName: resources-alma-fix` and you will get the full index name (with the timestamnp as suffix). All consecutive logs are connected to this index. Re c) : I don't understand what you mean by "marker". We identify the service because the log resides in the respective home directory of the application.
> 
> The idea of a marker is just that we can better identify the source of the logged error. One cannot identify which of our own services is querying lobid resoruces because all errors just state `application-akka.actor.default-dispatcher` if our own services would provide an `user agent` and this would be stated in the logs too, then we could better identify where an error is coming from. Perhaps the user agent statement is good for all query errors too. So one has not to search or guess like in #1846 to identify the source of an error.

**Comment by dr0i** [comment]
IMO you put 3 issues into one. Logs are separated with #1930. The other issues could be discussed elsewhere and we could close this issue here.

**Comment by TobiasNx** [comment]
I am closing this ticket, we could reopen the ticket if we need the better logging again.
