### ISSUE TITLE
Put `web/conf/context.jsonld` on `.gitIgnore`

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1858]
There was a version of this file commited, but since it is created locally by the web app too. The commited version broke the automatic deployment process. Therefore I strongly suggest to put `web/conf/context.jsonld` on the `.gitIgnore`-List

**Comment by dr0i** [comment]
We had such kind of incidence before, see https://github.com/hbz/lobid-resources/issues/1061.
I am investigating why we _do_ commit the context - even if it's generated by the web app.

**Comment by dr0i** [comment]
Here is the corresponding issue: https://github.com/hbz/lobid-resources/issues/1119 .
It proposes to add it to `.gitignore`, but  I like the note before :  
> Also, this would show if there would be an issue with the context , even if context-labels.json would look ok.
If we have to commit it we are forced to make diffs and so will have a look at  it, if it's good.

So my proposal is to leave it as it is, close #1119 and follow #1061 for server scheduled deployment.

**Comment by TobiasNx** [comment]
But isn't it a problem, that the context changes every time you run the tests?

**Comment by dr0i** [comment]
I don't see how running tests could change the context. There is ` src/main/resources/labels/` but no special  ` src/test/resources/labels/`. _If_ the tests build a "new" context then building and commiting this context was forgotten before.

**Comment by TobiasNx** [comment]
The order changes almost every time when I remember correctly.

**Comment by dr0i** [comment]
Closing this as "will not resolved".
