### ISSUE TITLE
Add class for Database

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1864]
https://lobid.org/resources/990186940270206441.json

Is mapped as periodical but not as database.

**Comment by TobiasNx** [comment]
I am not sure if we have a class for `Database` yet.

**Comment by TobiasNx** [comment]
https://lov.linkeddata.es/dataset/lov/terms?q=Database&type=class there seems to be no good Class in lov, except for dbpedia but we do not use dbpedia classes, do we @acka47

**Comment by acka47** [comment]
The example looks like [`bibo:Collection`](http://purl.org/ontology/bibo/Collection) would be a good fit. It is also part of lobid-organisations with this type: http://lobid.org/organisations/ZDB-1-CDC  (See also https://github.com/hbz/lobid-organisations/issues/308 for more information on collections in lobid-organisations.)

**Comment by TobiasNx** [comment]
To be honest I was not thinking about the collection side of a database, but of the search and query side of an database. So that an database can have additional resources as in an ebook package but has not always one. Other examples of this would be nwbib, web of science, but also catalogues. I am not sure how to combine these under one label.

**Comment by TobiasNx** [comment]
I had another encouter with Database: http://lobid.org/resources/search?q=natureOfContent.label%3ADatenbank

These are examples for Database. But we cannot use a GND-term right? @acka47

**Comment by TobiasNx** [comment]
We should add a seeAlso link to DBIS and perhaps a inCollection statement for DBIS:

```
datafield tag="856" ind1="4" ind2=" ">
<subfield code="u">https://dbis.ur.de/frontdoor.php?titel_id=102604</subfield>
<subfield code="x">DBIS</subfield>
</datafield>
```

**Comment by TobiasNx** [comment]
GUI is also not good yet:

![image](https://github.com/user-attachments/assets/70f13f98-d81a-439a-a782-b8ae6efe5243)

**Comment by dr0i** [comment]
To be reviewed next Monday.

**Comment by dr0i** [comment]
As discussed in the meeting we close this issue because it is not important.
