### ISSUE TITLE
Add ALMA IZ to holding entry

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1866]
When analyzing the records, due to the library codes in hasItem it is difficult to sort the records to the right holder. Sometimes not all institutions belonging to one ~mainholder~ALMA IZ have the same ISIL pattern.

~Therefore I suggest adding the main holder or parentOrganization to the holding entry.~

We could add to heldBy a https://schema.org/memberOf - property linking to the IZ and using the lobid-organisation `id` and add the `label` `IZ of [ISIL]`

**Comment by TobiasNx** [comment]
@acka47 made a good suggestion. The IZ is no info about the holding institution but about the item. Therefore we should add an `inCollection`statement to the item.

**Comment by dr0i** [comment]
Can you provide an example which points to the problem? All I see in the PR is a lot of redundany in all test files.

**Comment by TobiasNx** [comment]
Now has the IZ as inCollection Statement:
```
 "hasItem": [
    {
      "label": "lobid Bestandsressource",
      "type": [
        "Item",
        "PhysikalischerTitel"
      ],
      "currentLibrary": "R5001",
      "currentLocation": "UNASSIGNED",
      "heldBy": {
        "isil": "DE-1116",
        "id": "http://lobid.org/organisations/DE-1116#!",
        "label": "Hochschule für Wirtschaft und Gesellschaft Ludwigshafen, Bibliothek"
      },
      "seeAlso": [
        "https://opac.hwg-lu.de/alipac/-/item-local?BASE=B-TIT&VID=HT020579803"
      ],
      "inCollection": [
        {
          "id": "http://lobid.org/organisations/DE-1116#!",
          "label": "Hochschule für Wirtschaft und Gesellschaft Ludwigshafen, Bibliothek"
        }
      ],
      "id": "http://lobid.org/items/990367731740206441:DE-1116:229499030007824#!"
    }
```

Also is searchable: http://lobid.org/resources/search?q=hasItem.inCollection.id%3A%22http%3A%2F%2Flobid.org%2Forganisations%2FDE-1116%23%21%22
