### ISSUE TITLE
Cache lookup table

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1868]
Results from https://github.com/hbz/lobid-resources/issues/1862:
We should not lookup `isil2opac_hbzid.json` but put it into the filesystem and make it hot-loadable (automatically reload this conf if it changes). We should then crontab (or webhook) to update `isil2opac_hbzid.json`.

Details:
`web/conf/resources.conf:isil2opac_hbzid = "https://raw.githubusercontent.com/hbz/link-templates/master/isil2opac_hbzid.json"`

Note: this is used in other projects , e.g. nwbib. Grep githubusercontent. Should be treated accordingly.

**Comment by TobiasNx** [comment]
@dr0i I am not sure if we need to do this, since we are enriching the source data with this information, see: #1888

**Comment by dr0i** [comment]
Ah , good to hear! The old lookup of websites every time was really not good.
Closing.
