### ISSUE TITLE
Fehlende Erscheinungsorte und Erscheinungsjahre in einigen Titeln

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1885]
Reported via email to NWBib mailing list by U.P. on 06.09.23, 13:03:

> bei folgenden Titeln
> 
> https://nwbib.de/99371240914006441 -> https://lobid.org/resources/99371240914006441
> https://nwbib.de/990368530020206441 -> http://lobid.org/resources/990368530020206441
> https://nwbib.de/99371233633606441 -> http://lobid.org/resources/99371233633606441
> https://nwbib.de/990209806710206441 -> http://lobid.org/resources/990209806710206441
> 
> fehlen im NWBib-Portal in der Titelaufnahme der Erscheinungsort und das 
> Erscheinungsjahr. In Alma ist die TA für diese Titel aber korrekt. 
> Würden Sie sich das bitte anschauen? Ein Hinweis noch: Diese 4 besagten 
> Titel haben im Feld 264 den Indikator 3 an zweiter Stelle, die 
> Vergleichstitel, die im NWBib-Portal richtig dargestellt wurden, haben 
> im Feld 264 an zweiter Position den Indikator 1. (1=Jahr der 
> Veröffentlichung, 3=Herstellungsjahr) Es sollte doch eigentlich beides 
> im NWBib-Portal dargestellt werden, nicht wahr.

**Comment by blackwinter** [comment]
> Ein Hinweis noch: Diese 4 besagten Titel haben im Feld 264 den Indikator 3 an zweiter Stelle, [...] (1=Jahr der Veröffentlichung, 3=Herstellungsjahr)

This is related to #1806.

**Comment by TobiasNx** [comment]
At the moment we only map publication related infos but not Manufacture infos.

**Comment by TobiasNx** [comment]
https://lobid.org/resources/99371240914006441.json

=> 

```
 "manufacture": [
    {
      "startDate": "2021",
      "type": [
        "Event"
      ],
      "location": [
        "Rommerskirchen-Nettesheim"
      ],
      "manufacturedBy": [
        "Pegodruck"
      ]
    }
  ]
```

**Comment by TobiasNx** [comment]
We could add this to lobid GUI too.

**Comment by TobiasNx** [comment]
@acka47 i am closing this ticket. The nwbib related todo are listed here: https://github.com/hbz/nwbib/issues/627
