### ISSUE TITLE
Provide links into local catalogues.

### ISSUE THREAD

**Issue by blackwinter** [hbz/lobid-resources#1888]
It would be nice if individual holdings (`hasItem`) could include links into the respective library's catalogue (OPAC). The Lobid web app already [does this](https://github.com/hbz/lobid-resources/blob/f7fc49c6dae16f92b60b12189db81f2b8506387b/web/app/controllers/resources/Lobid.java#L393) based on [Link Templates](https://github.com/hbz/link-templates). If the URLs would be provided via the API, any downstream consumers could reuse them.

It needs to support both hbz IDs and ZDB IDs; possibly also MMS IDs as fallback.

Originally requested by FEx Daten (W1/W2).

**Comment by TobiasNx** [comment]
@blackwinter you mentioned that we should prefer hbzId over zdbId.
Are you sure that local catalogues still have hbzId in their metadata for ZDB records, since they got dropped in the NZ?
But we still add the old hbzId to the pre-migration ZDB record via a mapping.

**Comment by TobiasNx** [comment]
zdbId and hbzId mappings seem to work.

How do we proceed with ISBNs, Alma MMS Ids and ISSNs?
1) There is no map for opac links with ALMA MMS ID.
2) There are multiple ISBN and ISSN possible. Should we somehow join them before adding them?

**Comment by blackwinter** [comment]
> There is no map for opac links with ALMA MMS ID.

Needs to be added in lookup-tables. But you can already reference it even if it doesn't exist yet.

> There are multiple ISBN and ISSN possible. Should we somehow join them before adding them?

Depends on the individual catalogue. Maybe just use the first one for starters?
