### ISSUE TITLE
Create a data documentation

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#189]
json examples:
* book
* journal article
* book in series
* book in multivolume work
* periodical

**Comment by acka47** [comment]
Sounds good to me as relevant examples. Perhaps we should also add a ZDB resource. The last two (book in series and book in multivolume work) can be covered by one example, see https://github.com/lobid/lodmill/issues/497 with examples http://lobid.org/resources/HT002888677 and http://lobid.org/resources/HT017903191.

**Comment by acka47** [comment]
See also https://wiki1.hbz-nrw.de/pages/viewpage.action?pageId=19136520 for examples of different resource types in the catalogue.

**Comment by ChristophEwertowski** [comment]
Noting examples here.
* book: http://lobid.org/resources/HT010912885 (standard fields with isbn and edition)
* article: http://lobid.org/resources/HT014060796 (containedIn, some subjects)
* book in multivolume work and series: http://lobid.org/resources/HT002888677 (volumeIn, series, multple exemplars)
* periodical: http://lobid.org/resources/HT007216566 (frequency)

**Comment by dr0i** [comment]
Don't know for what you need this exactly but if you want to fast-check changes on the `morph` it makes sense to use resources which are already part of the junit-test set so that the resources are transformed when building the project. If no good test-resource exists yet, add it to the test set.

**Comment by ChristophEwertowski** [comment]
Updated list with examples from the test files so you can see faster if some label/uri has changed and update the documentation:
* article: http://lobid.org/resources/HT013577568
* periodical: http://lobid.org/resources/HT013304490
* book: http://lobid.org/resources/HT013480902
* book in MultiVolumeWork and series: http://lobid.org/resources/HT015865114 but above example is better. For example it is in a real series. Will push example data file next week.

**Comment by ChristophEwertowski** [comment]
Ticket is a sub issue of https://github.com/hbz/lobid/issues/288. 
Made the annotations like the [organisations docu](http://lobid.org/organisations/api/de) in structure. Annotated fields have following points:
* descriptive **name**
* **description** which contains what's in the field and, if directly transferred, the corresponding MAB2-field
* **coverage**/**occurence**
* an **example**

I won't open a pull request since it's already [on the page](http://lobid.org/resources/api). 

Feel free to annotate! (And of course to comment here.)

**Comment by acka47** [comment]
Looking through the annotations, I noticed some problems with the chosen example records:

- None of the agents has an altLabel, thus it isn't documented.
- There is no agent of type corporate body in any example record.

**Comment by ChristophEwertowski** [comment]
The resource [Kantaten Ostern, Pfingsten](https://github.com/hbz/lobid-resources/blob/master/src/test/resources/jsonld/HT014525099) of Johann Sebastian Bach seems a good example: It has altLabels, corporateBodies and is a PublishedScore/AudioDocument.

**Comment by ChristophEwertowski** [comment]
The [61. Jahreskongress der Deutschen Gesellschaft für Kleintiermedizin](http://lobid.org/resources/HT018848513?format=json) is an even better example. It contains all fields of the book example except subject (which I would transfer to article), altLabels for the agents, a CorporateBody and ConferenceOrEvent type. It should be added to the json test files though.

**Comment by ChristophEwertowski** [comment]
A few days before launching the API 2.0 we should update the documentation. To remind myself I'm reopening this issue.

**Comment by ChristophEwertowski** [comment]
Just saw ticket #288 which is already open and treats with the same topic. Closing this one again.
