### ISSUE TITLE
Separate lookup-tables for test and prod and use gitsubmodule for prod

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1893]
As already done for DDC.

**Comment by dr0i** [comment]
Separation is done with #1902. 
We don't use anymore cronjob to update th lookupt tables but gitsubmodule (as proposed by @blackwinter ).
It's already deployed.
We shall await some live tests with real data before closing this issue.

**Comment by dr0i** [comment]
Seems to be good as there are no errors in the logs.
Closing.
