### ISSUE TITLE
Add cron job for lobid-organisation labels map

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1903]
`src/main/resources/alma/maps/lobidOrganisationsMapping.tsv`

Should be fetched via cron job.

https://lobid.org/organisations/search?q=_exists_%3Aisil+OR+type%3ACollection&format=csv:id,isil,sigel,name&size=25000

The process should fetch this and replace:
`^"` => empty
`"$` => empty
`","` => Tab
`",,"` => 2x Tab

It seems that the request is forbidden in prod, but it works on test.

The columns are `id`, `isil`, `sigel`, `name`

This was asked by Digibib, since the labels shoud be updated regularly.

**Comment by dr0i** [comment]
> It seems that the request is forbidden in prod, but it works on test.

I've now increased in the webserver config to `timeout=60`.

**Comment by TobiasNx** [comment]
thanks this seems to work now.

**Comment by TobiasNx** [comment]
Can you help with the seed script? For the cron job?

**Comment by TobiasNx** [comment]
https://lobid.org/organisations/search?q=_exists_%3Aisil+OR+type%3ACollection&format=tsv:id,isil,sigel,name&size=25000

**Comment by TobiasNx** [comment]
The new mechanism does not need any post processing. Only the following must be done:

Cron job to create new `src/main/resources/alma/maps/lobidOrganisationsMapping.tsv` file with https://lobid.org/organisations/search?q=_exists_%3Aisil+OR+type%3ACollection&format=tsv:id,isil,sigel,name&size=25000

Move the local file from  `src/main/resources/alma/maps/lobidOrganisationsMapping.tsv` to `src/test/resources/alma/maps`

**Comment by TobiasNx** [comment]
Also adjust the links for the test here:
https://github.com/hbz/lobid-resources/blob/40f2c43de1f88b789c794b7beba21f61b508f501/src/main/java/org/lobid/resources/run/AlmaMarcXmlFix2lobidJsonEs.java#L128-L129
https://github.com/hbz/lobid-resources/blob/40f2c43de1f88b789c794b7beba21f61b508f501/src/test/java/org/lobid/resources/AlmaMarc21XmlToLobidJsonMetafixTest.java#L72-L73

**Comment by dr0i** [comment]
`lobidOrganisationsMapping.tsv` will be downloaded just before the automatical weekly  deployment.
