### ISSUE TITLE
Use nwbib ttl for nwbib spatial und subjects labels

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1905]
Instead of mapping the labels with the `src/main/resources/labels/labels.json` maker, we could use the ttl files from the upcoming submodule for lobid-vocabs. #1902 

Then we could delete them from the labels.json file. As well as the RPB (lbz notationen) labels.

**Comment by TobiasNx** [comment]
@acka47 it seems that the nwbib labels are unnecessary, see https://github.com/hbz/lobid-resources/pull/1912.

Are they always provided via the marc record?

- Would it be better to use the ttl-file from nwbib since the labels are more up to date?
- Should we use it only as fallback?
- Is an additional adding of nwbib-labels unnecessary since the source data from ZDB is always correct and complete (id and label)?

**Comment by acka47** [comment]
> - Would it be better to use the ttl-file from nwbib since the labels are more up to date?

I think so.

> - Should we use it only as fallback?

Do we need a fallback?

> - Is an additional adding of nwbib-labels unnecessary since the source data from ZDB is always correct and complete (id and label)?

We know that the source data isn't always correct for CZ-derived electronical ZDB/EZB resources.

**Comment by TobiasNx** [comment]
Label in http://lobid.org/resources/990110714900206441.json are updated. So it is productive.
