### ISSUE TITLE
Separate context related info from plain label related info in context-labels.json and labels.json

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1907]
The ettiket-maker does two things:
1. add labels were labels are missing
2. creates the context for json-ld

It uses all files in `src/main/resources/labels`:

But only those with "name" are added to the context while those with only "label" are not.
Some of the values in the context are also in `labels.json`.
I suggest to consistently use `context-labels.json` for properties and classes that are added to the context.
While entity labels are only added in labels. Perhaps rename `labels.json` into `entity-labels.json`.

**Comment by dr0i** [comment]
I am pretty sure that this will just gain us more redundancy and pitfalls.
Read https://github.com/hbz/lobid-resources/pull/899#issuecomment-410161134 .
Update https://github.com/hbz/lobid-resources/wiki/How-context.jsonld-is-generated.

**Comment by TobiasNx** [comment]
I created a PR for cleaning up context-labels.json and labels.json without renaming them.
We then have only one file for context related classes and properties.

**Comment by dr0i** [comment]
PR is merged.  Closing.
