### ISSUE TITLE
Use  opac link instead of web app generated link for opac link

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1915]
https://github.com/hbz/lobid-resources/blob/03720ef25a9165a49388d12164f27b7707de1dd3/web/app/controllers/resources/Lobid.java#L389-L410

This function at least by generating the function every time is not needed anymore. It can use the link given in `hasItem.seeAlso` which is given in the submodule `lookup-tables`

**Comment by dr0i** [comment]
Resolved by #1920, closing.

**Comment by TobiasNx** [comment]
@dr0i not deployed yet.

**Comment by dr0i** [comment]
Hm, I double checked that and it is still good, see e.g. http://lobid.org/resources/99371791018506441 -> Bonn lokal anzeigen . Or did I miss something?

**Comment by TobiasNx** [comment]
On friday there was still the old link, today it is correct. Thanks
