### ISSUE TITLE
Don't lowercase exemplar.id field

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#192]
For faceted search, we need case-aware values in the `exemplar.id` field.

Check the aggregation for `exemplar.id` in http://alpha.lobid.org/resources/aggregations?q=glessen

The values are all lowercase. Since ISILs are case-sensistive, this breaks faceted search for some owners, see owner facet at: http://alpha.lobid.org/resources/search?q=glessen

I currently uppercase the values, which works for many cases, but not all. Second sample for instance returns no hits: http://alpha.lobid.org/resources/search?q=glessen&owner=http%3A%2F%2Flobid.org%2Forganisation%2FDE-KN38 (should be http://alpha.lobid.org/resources/search?q=glessen&owner=http%3A%2F%2Flobid.org%2Forganisation%2FDE-Kn38)

**Comment by dr0i** [comment]
Deployed small test set to gaia-aither cluster aliased `resources-smalltest`.

**Comment by fsteeg** [comment]
Needs updates in UI now that lowercasing is removed.

**Comment by fsteeg** [comment]
Updated and deployed, closing.
