### ISSUE TITLE
Enrich with zbsport

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1938]
For example http://lobid.org/resources/990001412590206441.json lacks many subject headings which exist in the zbsport catalog - see corresponding https://aleph.zbsport.de/F/?func=find-word&scan_code=WRD&scan_word=HT000161712&local_base=str01 . Is there a way to enrich our data with the data of zbsport?

Popped up by reviewing https://github.com/hbz/lobid-resources/pull/1937.

**Comment by TobiasNx** [comment]
@dr0i the two examples do not fit

http://lobid.org/resources/990001412590206441.json  -> Handwörterbuch des Volksschulwesens
[aleph.zbsport.de/F/?func=find-word&scan_code=WRD&scan_word=HT000161712&local_base=str01](https://aleph.zbsport.de/F/?func=find-word&scan_code=WRD&scan_word=HT000161712&local_base=str01) -> [Mein Wittlich-Land]

**Comment by acka47** [comment]
Hm, the ZB Sport is already part of the hbz union catalogue and, thus, of lobid-resources, see https://lobid.org/resources/search?q=hasItem.heldBy.isil%3ADE-Kn41. No need for enrichment then, I guess.

**Comment by dr0i** [comment]
Great to hear - closing.
