### ISSUE TITLE
Remove duplicate ISSNs

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1949]
Just noticed this in the context of https://metadaten.community/t/frage-zur-query-syntax-issn-nummern-fuer-juristische-zeitschriften/57/2. There seem to be lots of duplicate ISSNs in ZDB entries. Of the 50 random entries with ISSN gotten via `$ curl "https://lobid.org/resources/search?q=_exists_%3Aissn&size=50" | jq  '[ .member[] | {id: .id,  issn: .issn }]'`, four have a duplicate ISSN, namely:

```json
[
  {
    "id": "http://lobid.org/resources/990054860120206441#!",
    "issn": [
      "04694333",
      "04694333"
    ]
  },
  {
    "id": "http://lobid.org/resources/990054283670206441#!",
    "issn": [
      "09351078",
      "09351078"
    ]
  },
  {
    "id": "http://lobid.org/resources/990054856760206441#!",
    "issn": [
      "25672967",
      "25672967"
    ]
  },
  {
    "id": "http://lobid.org/resources/990054121890206441#!",
    "issn": [
      "01770004",
      "01770004"
    ]
  },
  {
    "id": "http://lobid.org/resources/990056059230206441#!",
    "issn": [
      "0943786X",
      "0943786X"
    ]
  }
]
```

**Comment by dr0i** [comment]
Should be deployed next Monday. Closing.
