### ISSUE TITLE
ISBN of related resources in GUI  

### ISSUE THREAD

**Issue by maipet** [hbz/lobid-resources#1951]
e.g. http://lobid.org/resources/990366384450206441: displayed ISBN from "related" : 

> [ {"note" : [ "Online-Ausgabe" ],"label" : "Pest und Corona", "isbn" : [ "9783451821677", "3451821672" ]
instead of 
> "isbn" : [ "9783451388798", "3451388790" ]

**Comment by TobiasNx** [comment]
@maipet this seems to be a duplicate #1829
