### ISSUE TITLE
Repeated subfield "d" in 100/700

### ISSUE THREAD

**Issue by maipet** [hbz/lobid-resources#1952]
If subfield "d" (Dates associated with a name) in 100/700 is repeated, the fields should be skipped (according to MARC, the field ist NR)
e.g. MMSID 99371463467006441
```
<datafield tag="100" ind1="1" ind2=" ">
<subfield code="a">Sheffield, Alfred Dwight,</subfield>
<subfield code="d">1871-1961.,</subfield>
<subfield code="d">Sheffield, Alfred Dwight,</subfield>
<subfield code="d">1871-1961.,</subfield>
...
```

**Comment by dr0i** [comment]
To be checked next Monday.

**Comment by dr0i** [comment]
ping @maipet and @TobiasNx : you check and if ok close

**Comment by TobiasNx** [comment]
Looks good

https://lobid.org/resources/99371463467006441.json

Closing.
