### ISSUE TITLE
special characters in some places of publication

### ISSUE THREAD

**Issue by UBmakla** [hbz/lobid-resources#1953]
In some cases there are special characters such as the semicolon in places of publication, e.g. http://lobid.org/resources/99370671029106441.json  "location" : [ "Basel ;", "New York :" ], 
That that doesn't look nice in the catalog, is there a possibility to change it? Thanks!

**Comment by dr0i** [comment]
Hi @UBmakla . We could make it pretty. But it seems that the problem resides on th data side for it seems to be catalogued like this. Is there a chance to correct the metadata ?

**Comment by dr0i** [comment]
Hm, as there is no answer I guess it's not so easy to change the crappy data. Also I think I saw this kind of data when working with @maipet who complained about the missing validation when cataloging data. So:
we fix the data ourserlves.
Take over @maipet !

**Comment by UBmakla** [comment]
Sorry for my late reply, we have discussed the problem internally. As you suspect, we haven´t found a way to clean up the data. Thank you very much for taking care of it!

**Comment by acka47** [comment]
Fixed by #1960. Closing
