### ISSUE TITLE
Map markers don't load

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1966]
Same as https://github.com/hbz/nwbib/issues/637

**Comment by acka47** [comment]
I was dm'ed on my Mastodon account about this by a lobid user. As this is a quick fix, we should implement it soon. Assigning @fsteeg .

**Comment by fsteeg** [comment]
Deployed to stage, see http://stage.lobid.org/resources/990182586200206441

**Comment by acka47** [comment]
> Deployed to stage, see http://stage.lobid.org/resources/990182586200206441

Hmm, doesn't look like it.

**Comment by fsteeg** [comment]
Fixed in test deployment: http://test.lobid.org/resources/990182586200206441

(see https://github.com/hbz/lobid-resources/pull/1969 for background)

**Comment by dr0i** [comment]
I could deploy it at Stage but something is strange in Prod:
When I try `sbt` it cannot download sbt 0.13.18:
>  unresolved dependency: org.scala-sbt#main;0.13.18: not found

I updated server like described at https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Linux.html  using `apt` . Before that I did a naiv copy from Stage:
> $stage: for i in $(find ~/.ivy2/  -name "*0.13.18.jar"); do echo $i; scp "$i" $prod:"$i";  done
to no avail.
Reopen this so @fsteeg can have a look.

**Comment by fsteeg** [comment]
It seems like the local `~/.sbt/repositories` config on prod, which contained non-HTTPS urls, was the issue. I moved it to `~/.sbt/repositories-bk` and copied `~/.sbt/repositories` from `q3`.

Seems to work now, tested with `sbt --java-home $JAVA_HOME compile`, but left the current monit status and app process running to avoid interfering with prod updates / setup.

**Comment by dr0i** [comment]
Thx! Did a `monit restart lobid-resources-alma`, all is fine now. Closing.
