### ISSUE TITLE
Hide temporary labels in API response

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#197]
We decided to hide `subjectLabel` in the API response, see https://github.com/hbz/lobid-resources/issues/8#issuecomment-273803625. 

Does anything speak against also hiding , `contributorOrder`,`subjectOrder` and `subjectChain`?

**Comment by acka47** [comment]
I probably should better have opened this at https://github.com/hbz/lobid-resources-web...

**Comment by fsteeg** [comment]
For `subjectLabel`, if I recall correctly, the idea was that we want to be able to use its values for search, but we don't actually need it when processing the response, e.g. for display.

For `subjectChain`: we need that for display in NWBib.

For `subjectOrder` and `contributorOrder`: I don't know, I seem to recall these are specifically for @jschnasse.

**Comment by fsteeg** [comment]
When NWBib, Edoweb, Publisso switch, we can still re-enable them if we don't have working alternatives, will remove `subjectLabel`, `contributorOrder`, `subjectOrder`, and `subjectChain` from responses.

**Comment by fsteeg** [comment]
Just discussed this offline with @acka47: since @hagbeck also needs the altLabels for indexing, we can't remove `subjectLabel` data (but we decided to call it `subjectAltLabel` to make clear there is no redundancy with `subject.label`, will open issue). The other fields will be hidden in responses.

**Comment by fsteeg** [comment]
Deployed to stage: http://stage.lobid.org/resources/TT050409948?format=json

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
+1
