### ISSUE TITLE
Add medium "Print" to non-electronic maps

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1970]
Reported in the NWBib context:

On 29.02.24 14:31, I.N. wrote:
> da die NWBib-Redaktion Münster für die Durchsicht und Titelübernahme aus 
> der DNB-Reihe C  zuständig ist, möchten wir auf die noch fehlende 
> Anzeige des Medientyps bei Karten hinweisen.
> 
> In der NWBib gibt es  z.Z. 7.682 Karten. Bei 3.021 Karten wird als 
> Medientyp das Icon Fragezeichen |?|  angezeigt. Bei der überwiegenden 
> Menge der Titelaufnahmen wird es sich um eine normale Karte auf Papier 
> handeln. Es sollte das Icon Buchstabe |A| für ein Print-Medium angezeigt 
> werden.
> 
> Ursache für die Anzeige des Icon Fragezeichen ist ein fehlender Eintrag 
> im Feld „medium“.
> 
> Hier zum Vergleich der Ausschnitt des Feldes „medium“ aus 
> Beispiel-Titelaufnahmen:
> 
> Stadtplan Ennepetal 27. Aufl. 
> https://lobid.org/resources/990198516130206441.json 
> <https://lobid.org/resources/990198516130206441.json>
> 
> Stadtplan Ennepetal 29. Aufl. 
> https://lobid.org/resources/99373068381606441.json 
> <https://lobid.org/resources/99373068381606441.json>
> 
> Leider haben wir keine Informationen darüber, welche 
> Feld/Unterfeldbelegung den Eintrag „Book“ erzeugt. Mehrere Versuche 
> durch Veränderung des MARC Feldes 007 diesen Eintrag zu erzeugen, waren 
> erfolglos.
> 
> Eventuell kann man das Icon für „Print“ durch das Auslesen eines anderen 
> Feldes erzeugen?
> 
> In RDA-Titelaufnahmen gibt es die MARC-Felder 337 (Medientyp) Code „n“ = 
> „ohne Hilfsmittel zu benutzen“ und Feld 338 (Datenträgertyp) Code „nb“ = 
> Blatt.
> 
> In den alten RAK-Titelaufnahmen existieren diese Felder aber noch nicht. 
> Hilfreich könnte auch das Feld 300 (Physische Beschreibung), Unterfeld c 
> = Maße sein. Wenn das Unterfeld c belegt ist, muss es sich um ein 
> Print-Medium handeln.

**Comment by dr0i** [comment]
Will be deployed with complete reindexing - i.e. next Monday.
We should revisit then and inform customers. Therefore reopened.

**Comment by dr0i** [comment]
Should be good now - the icon is shown e.g. for https://lobid.org/resources/99373068381606441.
Can you inform customers and close this issue afterwards @acka47 ?

**Comment by acka47** [comment]
I informed the NWBib partners. Closing.

**Comment by TobiasNx** [comment]
> Eventuell kann man das Icon für „Print“ durch das Auslesen eines anderen Feldes erzeugen?
> 
> In RDA-Titelaufnahmen gibt es die MARC-Felder 337 (Medientyp) Code „n“ = „ohne Hilfsmittel zu benutzen“ und Feld 338 (Datenträgertyp) Code „nb“ = Blatt.
> 
> In den alten RAK-Titelaufnahmen existieren diese Felder aber noch nicht. Hilfreich könnte auch das Feld 300 (Physische Beschreibung), Unterfeld c = Maße sein. Wenn das Unterfeld c belegt ist, muss es sich um ein Print-Medium handeln.

@acka47 should we have another look at these RDA rules if they can help specify the medium for other resources than maps too?

**Comment by acka47** [comment]
> @acka47 should we have another look at these RDA rules if they can help specify the medium for other resources than maps too?

This has no high priority but it might improve some edge cases. Otherwise, we can also fix it when reports come in.
