### ISSUE TITLE
`related`-Transformation creates duplicates if ISBN is given as variant.

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1975]
While I was away the `related`-transformation was change to tackle some problems with multiple ids /subfield $w:
https://github.com/hbz/lobid-resources/pull/1948
and PR without MR
https://github.com/hbz/lobid-resources/commit/1911e7b4f2a696c5f208c292591f563fb6d469e2

I found that the changes improved the transformation where multiple Id exist for different variants but create duplicates if the ISBN is identical see:
https://github.com/hbz/lobid-resources/commit/e6e935b96edde36fb04483c5fabf2d95e54404d9#r140286285

and here:
https://github.com/hbz/lobid-resources/blob/a308ef97e113562717a5b3522839d3f37704599f/src/test/resources/alma-fix/990367731740206441.json#L60-L67

**Comment by dr0i** [comment]
Deployed next Monday.

**Comment by TobiasNx** [comment]
The duplicate is not provided anymore: http://lobid.org/resources/990367731740206441.json
