### ISSUE TITLE
sameAs to CultureGraph no longer valid

### ISSUE THREAD

**Issue by hagbeck** [hbz/lobid-resources#1983]
Apparently the hbz now supplies Alma MMS IDs instead of hbz IDs to CultureGraph. Consequently, the links in lobid-resources are no longer correct.
Example [1] contains [2] which results in 404. But [3] works.

[1] https://lobid.org/resources/990050000600206441.json
[2] http://hub.culturegraph.org/resource/HBZ-HT006855611
[3] https://hub.culturegraph.org/resource/(DE-605)990050000600206441

**Comment by TobiasNx** [comment]
@hagbeck @acka47 @dr0i http or https url?

**Comment by hagbeck** [comment]
CultureGraph uses https in the RDF data [1] and http redirects to https.

[1] https://hub.culturegraph.org/resource/(DE-605)990000003810206441/rdf

**Comment by TobiasNx** [comment]
Okay I go with https if @acka47 does not disagree. PR is ready.

**Comment by acka47** [comment]
> Okay I go with https if @acka47 does not disagree.

+1

**Comment by dr0i** [comment]
To be checked after deployment next Monday.

**Comment by dr0i** [comment]
Looks good to me. Can you confirm @hagbeck ?

**Comment by TobiasNx** [comment]
Ping @hagbeck

**Comment by hagbeck** [comment]
Looks good. Thanks!
