### ISSUE TITLE
Supplements names are missing subtitles.  We should be combined  $t and $b

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1994]

**Comment by dr0i** [comment]
What am I supposed to do here?

**Comment by TobiasNx** [comment]
You already merged the related PR should be productive on monday:

https://github.com/hbz/lobid-resources/pull/1998

**Comment by dr0i** [comment]
Well, this is good. But why was I assigned ?

**Comment by TobiasNx** [comment]
Done. +1

https://lobid.org/resources/990054089950206441.json
