### ISSUE TITLE
Redirect with HT-Nr deprecatedUri to detail page of one record when there are two hits? Instead redirect to results or delete deprecatedUri from CZ record.

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1996]
Related to: https://github.com/hbz/nwbib/issues/611#issuecomment-2060901315

Due to the fact, that there are duplicate E-Book records of EZB publications because of CZ/Consor and NZ/ZDB we have faulty redirects. Only one record is linked not both matching records because both records have mapped HT-Nr. (`hbzId`) and (`deprecatedUri`). That created the confusion in: https://github.com/hbz/nwbib/issues/611#issuecomment-2060901315

We should 
**a)** either redirect to the result page instead of only redirecting to one detail page 
 OR 
**b)** we should delete the `deprecatedUri` link and do not map the `hbzId` from the CZ/Consors-Record, since the CZ-Consors-Record was never part of the Verbundkatalog and therefore should not have a HT-Nr. Especially because the ZDB publication do not receive any HT Numbers in ALMA anymore and we mapped the old HT-Numbers to be able to resolve the old URIs. So only the old Verbundkatalog/BZ/ZDB records have a redirect, a `deprecatedUri` and a `hbzId`

Writing this I prefer variant **b**. 

----------

e.g.

http://lobid.org/resources/HT015679368 redirects to https://lobid.org/resources/99370698631806441.
But there are two records with `deprecatedUrl: http://lobid.org/resources/HT015679368`
The other one is: https://lobid.org/resources/990171221570206441

CZ/Consors record: https://lobid.org/resources/99370698631806441. In variant b it would lose the `deprecatedUr`and the `hbzId`

```JSON
{
  "@context": "http://lobid.org/resources/context.jsonld",
  "almaMmsId": "99370698631806441",
  "urn": [
    "urn:nbn:de:hbz:6:2-69622"
  ],
  "oclcNumber": [
    "644257601"
  ],
  "dnbId": "990456757",
  "zdbId": "2451605-3",
  "deprecatedUri": "http://lobid.org/resources/HT015679368#!",
  "hbzId": "HT015679368",
  "title": "ABU-Info",
```

NZ/ZDB record: https://lobid.org/resources/990171221570206441

```JSON
{
  "@context": "http://lobid.org/resources/context.jsonld",
  "almaMmsId": "990171221570206441",
  "urn": [
    "urn:nbn:de:hbz:6:2-69622"
  ],
  "oclcNumber": [
    "984935842"
  ],
  "zdbId": "2451605-3",
  "dnbId": "990456757",
  "deprecatedUri": "http://lobid.org/resources/HT015679368#!",
  "hbzId": "HT015679368",
  "title": "ABU-Info",
...
```

**Comment by TobiasNx** [comment]
@acka47 and I decided to drop the mapping for CZ publications with zdbId and only add a hbzId to hbz NZ publication because they were and are part of the Verbundkatalog.

**Comment by dr0i** [comment]
I don't know what I am supposed to do here. As the PR #1999 is linked with the weak `related to` it implies that work is still to do here?

**Comment by TobiasNx** [comment]
Nope. The "weak" related to is just to stop it from automatically closing because we have to check on monday when merged.

**Comment by dr0i** [comment]
Ah. Now for that I've used the `See #...`. For me, `related` implies one-part-in-the-puzzle-but-look-there-are-more . We don't have written this down somewhere, though.

**Comment by dr0i** [comment]
So, if there is nothing to do here
```
>> work is still to do here?
> Nope.
```

I still 
> don't know what I am supposed to do here.
Why was I assigned ?

**Comment by TobiasNx** [comment]
Because it was in review and you see in the project board that you are on it with the review.

 Since there is no work to do anymore for this now we wait for monday.

**Comment by TobiasNx** [comment]
+1 deprecatedUrl and hbzId are not part of the CZ records anymore.

> http://lobid.org/resources/HT015679368 redirects to [lobid.org/resources/99370698631806441](https://lobid.org/resources/99370698631806441).
> But there are two records with `deprecatedUrl: http://lobid.org/resources/HT015679368`
> The other one is: [lobid.org/resources/990171221570206441](https://lobid.org/resources/990171221570206441)

http://lobid.org/resources/HT015679368 now redirects http://lobid.org/resources/990171221570206441

And there is only one hit for the old HT Nr: https://lobid.org/resources/search?q=HT015679368
While for the zdbId there are two: https://lobid.org/resources/search?q=zdbId%3A%222451605-3%22
