### ISSUE TITLE
URIs of hasSupplement lead to error

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#200]
If I follow the URIs with the pattern  "http://lobid.org/resources/AA000000#!" everything is fine ([example](http://lobid.org/resources/HT017048170?format=json)). But for the data in the format "http://lobid.org/resources/ZDB-ID" errors appear ([from the periodical example of the documenation website](http://lobid.org/resources/2074003-7#!)).

**Comment by fsteeg** [comment]
Seems like the `ZDB` part is missing, since this works (redirects): http://lobid.org/resources/ZDB2074003-7

**Comment by fsteeg** [comment]
The example mentioned by @ChristophEwertowski is at http://lobid.org/resources/api#periodikum

**Comment by acka47** [comment]
As @fsteeg says, we could just add "ZDB" in the URI and the link would work – pointing to an external URI. It would be better to have a link to the ZDB resource in lobid, though. We decided to not support ZDB-ID-based URIs like `http://lobid.org/resources/ZDB{ID}` in API 2.0 . In 1.0 we do, see e.g. http://lobid.org/resource/ZDB2074003-7. This would leave as a possibility to look up the corresponding hbz ID of a linked ZDB resource during the transformation and put the lobid URI into the RDF. If this is feasible without too much work, we should do it.

**Comment by dr0i** [comment]
> This would leave as a possibility to look up the corresponding hbz ID of a linked ZDB resource [...]. If this is feasible without too much work, we should do it.

But it is much work! We have to the day explored many ways of how to enrich our data (offline one-time (dbpedia, gutenberg (and yet not included this data!)), using morph `mysql` and `file` lookups, experimenting using `elasticsearch` lookups (geo-infos), not forgetting `hadoop`. None of these were just simple/performant when it comes to many documents (ZDB >1M) .
I find the approach of enriching using elasticsearch directly sounds nice, but we would have to examine that.
So long, as it is not wrong but easy to do, I would want to go with the linking to the original ZDB resources.

**Comment by dr0i** [comment]
Seems that the underlying problem has nothing to do with our `ZDB`-uris:
even in the API 1.0 this is broken , see http://lobid.org/resource/HT013304490 -> `hasSupplement`. The problematic field is `529z1.9`, see http://lobid.org/hbz01/HT013304490 . Interestingly, in our test data the value of this resources' field is a HT-number ("HT013304885", thus correctly linking to http://lobid.org/resources/HT013304885).
It doesn't seem to link always to a ZDB resource, though, see e.g. http://lobid.org/resources/HT005077556?format=json . So this is rather erratical. I tend to say this is "badly catalogued", but then this subfield is defined as `z     = nicht differenzierte Beziehung` and thus: the underlying data model is lacking the granularity one would expect from librarians.
However, at least two ways to go:

1. ask an librarian (also, why did the entry changed for HT013304490, formerly linking to a HBZ-ID and now to an (umarked) ZDB-ID
2. change the transformation, believing in a pattern like "if the value of the field starts with a number change the URL to zdb-service

**Comment by ChristophEwertowski** [comment]
Changed, respectively added two conditions: If the content in field ```529z1.9``` starts with two letters a lobid resource URL is created and if the content starts with two digits a zdb-service URL is set. Here is a query for resources with supplements. Since the test set only contains resources with non-ZDB supplemental URLs ([query for all resources with supplements](http://test.lobid.org/resources/search?q=supplement.id:*)) or the test data which contain only hbzIds the change for ZDB URLs can't be seen. For example [resource (production)](http://lobid.org/resources/HT013304490?format=json) and [resource (test)](http://test.lobid.org/resources/HT013304490?format=json).

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
+1
