### ISSUE TITLE
Set up custom analyzer for ISBN and ISSN

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#201]
Originates from https://github.com/hbz/lobid-resources-web/issues/33

We should set up a custom analyzer [1] with a char filter (probably a pattern replace char filter, [2]) that removes dashes and blanks for the `isbn` and `issn` fields. Since we will keep the preprocessing in Metafacture, it should suffice to switch only the `search_analyzer` to the custom analyzer.

[1] https://www.elastic.co/guide/en/elasticsearch/reference/2.4/analysis-custom-analyzer.html
[2] https://www.elastic.co/guide/en/elasticsearch/reference/2.4/analysis-pattern-replace-charfilter.html

**Comment by dr0i** [comment]
Deployed to smalltest: 
weywot5.hbz-nrw.de:9200/resources-smalltest-20190611-115124/_search?q=isbn:320-90-017-31
weywot5.hbz-nrw.de:9200/resources-smalltest-20190611-115124/_search?q=isbn:3209001731

**Comment by dr0i** [comment]
Deployed to production, see e.g. http://www.lobid.org/resources/search?q=isbn:320-90-017-31 and http://www.lobid.org/resources/search?q=isbn:3209001731.

Closing.
