### ISSUE TITLE
in ALMA 030 CODEN Designation is missing in `shortTitle`

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#2014]
http://lobid.org/resources/990054089950206441.json

is missing this in shortTitle: 

 <datafield tag="030" ind1=" " ind2=" ">
    <subfield code="a">SPILB</subfield>
  </datafield>

**Comment by dr0i** [comment]
Deployed next Monday.

**Comment by TobiasNx** [comment]
> http://lobid.org/resources/990054089950206441.json
> 
> is missing this in shortTitle:
> SPILB

now part of shortTitle
