### ISSUE TITLE
Add information from MARC 502 subdfields c and d to `thesisInformation`

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#2018]
Reported in https://metadaten.community/t/kennzeichnung-von-hochschulschriften/349 by @kaihessling .

The examples named are: 

- https://lobid.org/resources/990125449590206441 (contains `thesisInformation`)
- https://lobid.org/resources/990220203490206441 (does not contain `thesisInformation`)

The difference ein the MARC is that one uses 502.a and the other (RDA) record 502b-d:

From https://lobid.org/marcxml/990125449590206441:

```xml
<datafield tag="502" ind1=" " ind2=" ">
   <subfield code="a">Köln, Univ., Diss., 2001</subfield>
</datafield>
```

From https://lobid.org/marcxml/990220203490206441:

```xml
<datafield tag="502" ind1=" " ind2=" ">
   <subfield code="b">Dissertation</subfield>
   <subfield code="c">Rheinische Friedrich-Wilhelms-Universität Bonn</subfield>
   <subfield code="d">2017</subfield>
</datafield>
```

In the current fix only subfield `a` is taken into account:

https://github.com/hbz/lobid-resources/blob/1fc9edc45336f0356141b729d30ba7498e6c6f81/src/main/resources/alma/fix/otherFields.fix#L142-L147

**Comment by TobiasNx** [comment]
[hbz MAB to MARC Mapping for ALMA](https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=483000321) states:

```
519 # $$p $$a [nur RAK-WB] -> 502 ## $$a  | Hochschulschriftenvermerk unstrukturiert [nur RAK-WB]

519 # $$p wird nicht umgesetzt

520 # $$b $$c $$d $$g $$o -> 502 ## $$b $$c $$d $$g $$o | Hochschulschriftenvermerk strukturiert

e.g.: 520 # $$b Diplomarbeit $$c Karl-Franzens-Universität Graz $$d 2016 -> 502 ## $$b Diplomarbeit $$c Karl-Franzens-Universität Graz $$d 2016
	
```

**Comment by TobiasNx** [comment]
@acka47 can you have a look at the PR: https://github.com/hbz/lobid-resources/pull/2019

**Comment by dr0i** [comment]
To be checked next Monday.

**Comment by TobiasNx** [comment]
now productive:

https://lobid.org/resources/990220203490206441.json

```JSON
  "thesisInformation": [
    "Rheinische Friedrich-Wilhelms-Universität Bonn, Dissertation, 2017"
  ],
```
