### ISSUE TITLE
Include IZ-activated CZ resources in union catalogue

### ISSUE THREAD

**Issue by blackwinter** [hbz/lobid-resources#2021]
As per [decision by FEx Daten](https://service-wiki.hbz-nrw.de/display/ALF/Umfrage+CZ-Titel+im+hbz-Webkatalog+nachweisen), all CZ resources should be included in the union catalogue (essentially reverting #1754/#1755; centrally managed CZ resources are already included).

They should either be covered by the `inCollection` for the [hbz NZ](https://lobid.org/organisations/DE-655) or selectable by some newly introduced filter condition.

Example: [99370694196806441](https://lobid.org/resources/99370694196806441)

**Comment by TobiasNx** [comment]
Since they are no genuine NZ Publications I will add an additional inCollection statement.

**Comment by blackwinter** [comment]
Seems to be working as intended: [99370694196806441](https://lobid.org/resources/99370694196806441) was not included before, is included now; ZDB ID 2669828-6 yielded one hit before ([990192163630206441](https://lobid.org/resources/990192163630206441)), yields two hits now ([990192163630206441](https://lobid.org/resources/990192163630206441) and [99370694196806441](https://lobid.org/resources/99370694196806441)).

:+1:
