### ISSUE TITLE
add additional relations

### ISSUE THREAD

**Issue by hagbeck** [hbz/lobid-resources#2033]
We have a new case of related works in our data. MARC field 505 sometimes contains information about another part of the current title. Subfield g describes what it is (a note) and subfield 6 contains the corresponding HBZ ID if the title exists in the network.
It would be nice if this information also appeared in lobid-resources. Gladly with the matching Alma-MMS-ID ;-)

Part 1: https://lobid.org/marcxml/99374022974006441
Part 2: https://lobid.org/marcxml/99374024871506441

**Comment by TobiasNx** [comment]
I can create a workable link with the deprecated URI based on the hbzId but I cannot create the ALMA-MMS-ID out of nothing.

Will create a draft and you can have a look if this suits your needs.

**Comment by TobiasNx** [comment]
Should be online next week

**Comment by TobiasNx** [comment]
@hagbeck good like this?

https://lobid.org/resources/99374022974006441.json
https://lobid.org/resources/99374024871506441.json

**Comment by hagbeck** [comment]
Looks good. Thanks!
