### ISSUE TITLE
Adjust Regex for URN pattern in field 024

### ISSUE THREAD

**Issue by maipet** [hbz/lobid-resources#2034]
cf. https://lobid.org/resources/990198125850206441
Reported by E.S. via email on 2024-07-23: Currently, the fulltext links from MARC-field 856 with http://**www.mdz**-nbn-resolving.de/ are not displayed / transformed in lobid. 
The reason seems to be processing the field 856 - URN (cf. https://github.com/hbz/lobid-resources/blob/master/src/main/resources/alma/fix/identifiers.fix#L21-L23), the regex pattern doesn't match "www.mdz"

**Comment by TobiasNx** [comment]
This is fixed now.
