### ISSUE TITLE
Missing URL to Website 

### ISSUE THREAD

**Issue by maipet** [hbz/lobid-resources#2036]
Report by E.S. via e-Mail on 25-07-2024: the URLs from MARC-field 856$u are not displayed / transformed in lobid. 

Maybe we do not take into account links that only have the subfield "u"? 
cf. [http://lobid.org/resources/99373333980706441](http://lobid.org/resources/99373333980706441) (HT030597366)
[http://lobid.org/resources/99373073230106441](http://lobid.org/resources/99373073230106441) (HT030369776)

**Comment by TobiasNx** [comment]
It seems that these examples are websites qualified in 655  with links in 865 $u that are otherwise not specified in the 865 object:

https://lobid.org/marcxml/99373333980706441

```XML
<datafield tag="856" ind1="4" ind2=" ">
  <subfield code="u">http://www.jakob-bengel.de/</subfield>
</datafield>
<datafield tag="655" ind1=" " ind2="7">
  <subfield code="a">Website</subfield>
  <subfield code="0">(DE-588)4596172-4</subfield>
  <subfield code="2">gnd-content</subfield>
</datafield>
```

Which property should we map this information @maipet? Did E.S. specify this @blackwinter do you have any prefrence?

**Comment by maipet** [comment]
@TobiasNx maybe same way like  e.g.: http://lobid.org/resources/990204847970206441 (also a website)?

**Comment by TobiasNx** [comment]
It seems that the information is already present in the JSON files:

```JSON
  "webPageArchived" : [ {
    "id" : "http://www.jakob-bengel.de/",
    "label" : "www.jakob-bengel.de"
  } ],
```

but is not represented on the lobid webpage.

In my opinion we do not have to do anything here.

**Comment by blackwinter** [comment]
We're using `webPageArchived` now.

**Comment by TobiasNx** [comment]
Then closing! Thanks.

**Comment by TobiasNx** [comment]
Additionally the examples seem to be buggy, they are missing edoweb infos in 024 and 865. I reported it in edowebs Jira: https://jira.hbz-nrw.de/projects/EDOZWO/issues/EDOZWO-1165
