### ISSUE TITLE
Replace FRBR "Item" class + properties with bibframe

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#204]
FRBR still occurs four times in the JSON-LD context. We have already removed `frbr:Manifestation` (see https://github.com/lobid/lodmill/issues/639) and I suggest to replace the rest with Bibframe:

- http://purl.org/vocab/frbr/core#Item -> http://id.loc.gov/ontologies/bibframe/Item
- http://purl.org/vocab/frbr/core#exemplarOf -> http://id.loc.gov/ontologies/bibframe/itemOf
- http://purl.org/vocab/frbr/core#exemplar -> http://id.loc.gov/ontologies/bibframe/hasItem
- http://purl.org/vocab/frbr/core#owner -> http://id.loc.gov/ontologies/bibframe/heldBy

I guess the mapping above is correct. I had some problems with the definition of `bf:itemOf` and `bf:hasItem`, though, see http://listserv.loc.gov/cgi-bin/wa?A2=ind1702&L=bibframe&T=0&P=1431. We should wait for the response to my mail before we implement this.

**Comment by acka47** [comment]
The response is in and I was correct with my assumption above:

On 09.02.2017 15:42, Denenberg, Ray wrote:
> Adrian - thanks for the suggestion.  We agree that both definitions need
> improvement. We plan to change these as follows:
> 
>  
> 
> */hasItem: /*/Item which is an example of the described Instance./
> 
> */itemOf: /*/Instance for which the described Item is an example./

Moving this to "ready".

**Comment by dr0i** [comment]
Deployed small test set to satging, see e.g. http://test.lobid.org/resources/TT002234459?format=json .

**Comment by dr0i** [comment]
Ready for updating the UI?
From #248:

> The index config needs to be updated for what previously was owner and exemplarOf.

What dou you mean exactly? Should `heldBy` defined as `"index": "not_analyzed"`? Does it not work without that?

**Comment by fsteeg** [comment]
> What dou you mean exactly? Should heldBy defined as "index": "not_analyzed"? Does it not work without that?

Yes, otherwise an aggregation returns every token. We also agreed to set all `id` fields to not_analyzed (it's actually `heldBy.id` that has to be set to not_analyzed).

**Comment by fsteeg** [comment]
Deployed to test:

http://test.lobid.org/resources/search (owner facet)
http://test.lobid.org/resources/HT000269005 (map and item details)

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
+1

**Comment by ChristophEwertowski** [comment]
Sorry, but I don't get what you tested. The aggregation? Because the context still gives me FRBR. Also the facet *Erscheinungsjahr* only gives me the placeholder "Lade Erscheinungsjahre...".

**Comment by dr0i** [comment]
I assume this question goes to @fsteeg . Reassigning.
