### ISSUE TITLE
Transform spatial lat/lon as number data type?

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#2041]
Since some time now we have an option in the encode-json modul of metafacture (https://github.com/metafacture/metafacture-core/blob/73ec6ad6d63ed041a673da19643ec7ec5442aa77/metafacture-json/src/main/java/org/metafacture/json/JsonEncoder.java#L67) that allows to transform json data not just into strings but also into boolean and numbers, should we provide the `lat` and `lon` elements of `spatial` as datatype `number` ? @fsteeg @acka47

**Comment by acka47** [comment]
Related: #1099. This would be an API break and I am not sure what advantages – if any – a change would bring. Most importantly, we have the same data type for all records with `geo` information which we now have. So, I suggest to close this.

**Comment by TobiasNx** [comment]
Okay, for now closing
