### ISSUE TITLE
faulty language ids

### ISSUE THREAD

**Issue by maipet** [hbz/lobid-resources#2062]
The way the language ID is created is error-prone, it allows any value out of the Marc data. Perhaps the values should first be validate against ISO?
e.g. 
http://id.loc.gov/vocabulary/iso639-2/deutsch -> https://lobid.org/resources/990126426530206441.json
http://id.loc.gov/vocabulary/iso639-2/engl. -> https://lobid.org/resources/990173607780206441.json
http://id.loc.gov/vocabulary/iso639-2/ger024 -> https://lobid.org/resources/99373983156706441.json
...

**Comment by TobiasNx** [comment]
The errors seem to result from: https://github.com/hbz/lobid-resources/blob/ddcd72b0c136572f00d9c6f97dddcff7780b932b/src/main/resources/alma/fix/otherFields.fix#L7

There some non standardized language values can sneak in.

**Comment by TobiasNx** [comment]
https://www.alma-dach.org/alma-marc/bibliographic/041/041.html

If indicator 2 of 041 is " " empty, the marc codes should be used. But it seems they are not always as @maipet examples show.

We should introduce an conditional to test if the value has more than 3 letters and therefore meets the pattern. Unfortenatly we do not have a morph like list filter mechanism yet.

**Comment by dr0i** [comment]
Will be deployed next Monday.
