### ISSUE TITLE
Include new RPB/LBZ Vocabs as submodule

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#2063]
RPB, RPB2 and RPB-Spatial moved to:

https://github.com/hbz/lbz-vocabs

@dr0i can you include this as submodule and adjust the paths for the productive java project?

https://github.com/hbz/lobid-resources/blob/6befacbba2a9025b86c2c7a903a9538b32ad9236/src/main/java/org/lobid/resources/run/AlmaMarcXmlFix2lobidJsonEs.java#L131-L133

**Comment by acka47** [comment]
Thanks for opening this issue, @TobiasNx ! I didn't know that/how RPB vocabs from hbz/lobid-vocabs was integrated in lobid-resources.

**Comment by dr0i** [comment]
Assign me when it's ready @TobiasNx .

**Comment by TobiasNx** [comment]
@dr0i as @acka47 said [hbz/lbz-vocabs](https://github.com/hbz/lbz-vocabs) can be used now

**Comment by dr0i** [comment]
To be reviewed tomorrow after data update.

**Comment by dr0i** [comment]
Looks good now (at first it wasn't deployed probably).
See e.g. http://lobid.org/resources/search?q=describedBy.resultOf.object.dateModified:2024-09-06%20AND%20lbz&format=json.
Closing.
