### ISSUE TITLE
Add adjustment for Introx opac links

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#2074]
In Introx only CZ/NZ resources that are not part of NZ/Verbundkatalog have OPAC-Links based on ALMA MMS ID, all others have ZDB or HBZ identifier as base.

**Comment by TobiasNx** [comment]
@blackwinter We reordered the priority of the links to zdb, hbz, almamms, issn BUT with regard to the CZ/NZ publications they are going to be mapped to the zdbId since they have one.

This is not the behaviour you wanted, is it?

**Comment by blackwinter** [comment]
> We reordered the priority of the links to zdb, hbz, almamms, issn

:+1:

**Comment by TobiasNx** [comment]
Ok then closing.
