### ISSUE TITLE
Map genre/form label if GND-ID is available in 655 but no label

### ISSUE THREAD

**Issue by maipet** [hbz/lobid-resources#2082]
Map the label from https://github.com/hbz/lobid-resources/blob/5c4dc57859a49592c1f519fb2057f6c25ea288f9/src/main/resources/alma/maps/formangabe.tsv if GND-ID exists but label $a is empty.
At the moment the subfield $a must exist if a GND-ID is given
E.g. 991030115479706476

**Comment by dr0i** [comment]
Deployed next Monday. To be checked then.

**Comment by TobiasNx** [comment]
@maipet https://lobid.org/resources/991030115479706476.json is that what you expected?

**Comment by maipet** [comment]
looks good. Closing
