### ISSUE TITLE
Fallback does not work correct for publishing date

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#2089]
http://lobid.org/resources/99374153235806441

There exists a correct publishing date in 264 but the transformation uses 008.
@maipet spotted this because it outputs a wrong publishing date in the future 2088 instead of 2008.

**Comment by dr0i** [comment]
To be checked next Monday.

**Comment by TobiasNx** [comment]
@maipet is this what you expacted?

**Comment by maipet** [comment]
Thx, looks good. Closing
