### ISSUE TITLE
Provide scripts for building and ETL minimal test set

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#21]
It should be easy to build and index an easy to enhance the *small test set* (~ 4k resources). This serves as documentation and also provides an easy and fast way to add some more test resources into an index without blowing up the *junit test set* (~ 70 resources).

**Comment by dr0i** [comment]
+1

**Comment by dr0i** [comment]
The `testIds.txt` is not taken into account. Reopen.

**Comment by dr0i** [comment]
Also, there are encoding issues , reported in https://github.com/hbz/lobid-resources/issues/29#event-561754779. See xml/HT017150239.xml vs xml/HT017150239.

**Comment by fsteeg** [comment]
Reassigning, see: https://github.com/hbz/lobid-resources/issues/35

**Comment by dr0i** [comment]
Would be nice to also have an update possibility, as the downloading of all 5k resources takes 10 minutes in VPN, and there is often the case that just one or two resources should be added to the test set.
