### ISSUE TITLE
Puplishers with double angle brackets aren't shown correctly in HTML

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#221]
Similar to https://github.com/hbz/nwbib/issues/104 where @dr0i removed the "crabs" from the data.
Example: http://lobid.org/resources/HT018147158 http://nwbib.de/HT018147158

From the JSON-LD:

```json
"publication":[
   {
      "location":"Köln",
      "publishedBy":"<<Die>> Ehrenfelder, Gemeinnützige Wohnungsgenossenschaft",
      "startDate":"2008",
      "type":[
         "PublicationEvent"
      ]
   }
]
```

**Comment by dr0i** [comment]
Is this a problem of the data or the html frontend?

**Comment by acka47** [comment]
It depends on the perspective. In https://github.com/hbz/nwbib/issues/104#issuecomment-95931936 you argued it should be fixed in the data. For consistency, I suggest to also fix the data in this case.

**Comment by acka47** [comment]
@ChristophEwertowski You can easily see in https://github.com/lobid/lodmill/pull/696/commits/1ebde307432521ebefb34397d7dea384aa89b6a6 how to remove the angle brackets.

**Comment by dr0i** [comment]
Deployed to stage. @fsteeg no UI update is needed, yes?

**Comment by fsteeg** [comment]
Right, looks good: http://stage.lobid.org/resources/HT018147158
