### ISSUE TITLE
Bad publication dates lead to wrong year facet

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#226]
I used the publication year bar to limit the results to seemingly very old resources: http://lobid.org/resources/search?issued=340-477&sort=oldest. Not surprisingly they aren't as old as that but only badly cataloged. If you look at the json files, you can see that they have startDates in the 3000s and 4000s. They should be displayed after the current year. 
Even better would it be to display all resources up to the current year + 5 years and out of the publication year bar (+5 years to show also publications which aren't published yet but cataloged). Then the publication bar could be used to filter in smaller steps. Publishing it first for discussion.

**Comment by acka47** [comment]
Perhaps it is best to send a list of resources with – mostly – wrong publication dates (something like http://lobid.org/resources/search?issued=%3E2023 and http://lobid.org/resources/search?issued=1000-1400&size=100&sort=oldest) to hbz catalogers so that they can correct the dates? Or we install our own Aleph client...

**Comment by ChristophEwertowski** [comment]
An Aleph client for our own would only be worth it if we use it more than once in half a year. I'm in favor of sending it to our people.

**Comment by fsteeg** [comment]
Quite a few of these seem to be transformation issues, where we pick the wrong number from `089-1.a`:

http://lobid.org/hbz01/TT000333189
http://lobid.org/hbz01/TT000353106
http://lobid.org/hbz01/TT001955286

**Comment by ChristophEwertowski** [comment]
Fortunately Jewish and Islamic resources are also cataloged by the Gregorian timescale (unlike in the HeBIS Verbundkatalog where the first date of some jewish resources is roughly the traditional timescale counting the years from the beginning of the creation of the earth, e.g. now [5777](https://de.wikipedia.org/wiki/J%C3%BCdischer_Kalender)). Tested it by looking at and sorting of Hebrew, Yiddish and Arabic resources. For these languages I only found some resources of the "year 0000".

**Comment by ChristophEwertowski** [comment]
Quite a few of wrongly publication years are volume information from 089, 090 (like [most resources of the USB Köln from the year 2020 onwards](http://lobid.org/resources/search?issued=2020-*&owner=http%3A%2F%2Flobid.org%2Forganisations%2FDE-38&sort=newest)).
Others like [9999](http://lobid.org/resources/search?issued=9999) or [0000](http://lobid.org/resources/search?issued=0000) seem to be placeholders. Mrs. Blankenhagen told me that if you fill something into the publication year field in Aleph, it has to be a four digit number.
Rarely you have two publication dates. For example http://lobid.org/hbz01/HT016560934 which has got a Gregorian date 2015 and Jewish timespan 5764-5775.
I also looked briefly if some organisations had a different cataloging practice but couldn't discern one. 

My suggestions:
* Don't show 0000 or 9999 as a year statement in the list. Instead leave a blank like if you search for [resources without a year](http://lobid.org/resources/search?q=_missing_%3Apublication.startDate). 
* Taking fields 089 and 090 only into account if they have two numbers, separated by a point or at least a four digit number a lower than 2100. Normal notation would be volume.year (maybe with a blank in the middle like in [example](http://lobid.org/hbz01/TT001955286)). Or leave them altogether. Either way this point would require a test against a big dataset.

**Comment by ChristophEwertowski** [comment]
In #258 I listed some searches for wrong publication date data.

**Comment by ChristophEwertowski** [comment]
@acka47 What do you think about the suggestions two comments above? (Especially the second point.)

**Comment by acka47** [comment]
This will probably be resolved by #300 . We should keep this in mind and close it when done.
