### ISSUE TITLE
Use bf:supplement for link to supplement

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#230]
...not http://rdaregistry.info/Elements/u/P60281. We have to upadte the morph and the labels.json.

**Comment by ChristophEwertowski** [comment]
Updated morph.xml and labels.json but got ```Failed tests:   testJson(org.lobid.resources.Hbz01MabXml2ElasticsearchLobidTest)``` and a ```WARN [main] (CompareJsonMaps.java:83) - At least this element is missing in actual: [supplement, id]```
Why a key is missing there, I couldn't comprehend. Also the formating of the json is broken again for the output/json/ files. What do you think @dr0i ?

**Comment by dr0i** [comment]
@ChristophEwertowski The pretty printing is enabled in #224 which is yet to be merged into master. The "missing element" may well be a result of a resource which is not transformed from the beginning, in the error log I can see a problem with HT013480902. So this may be also solved with merging #224 first and rebasing that master into this branch.

**Comment by dr0i** [comment]
Deployed to staging. Now update UI.

**Comment by fsteeg** [comment]
It seems `hasSupplement` is not used in the UI, reassigning for functional review.

**Comment by acka47** [comment]
JSON looks ok but the context hasn't been updated yet.

**Comment by dr0i** [comment]
JSON context for staging is deliberately _not_ deployed, see first comment in https://github.com/hbz/lobid-resources/pull/262.

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production index.
