### ISSUE TITLE
Remove link to Aleph OPAC from RDF

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#232]
Basically, just remove https://github.com/hbz/lobid-resources/blob/28100eff6e40f0847084c28c719ebabb3aa811bd/src/main/resources/morph-hbz01-to-lobid.xml#L205-L209. We don't need it in the RDF and probably not in the frontend. If we want to show it in the frontend, we can add it easily as it is based on hbz ID.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to stage. @fsteeg ready for UI update. Removes the "Weitere Informationen	hbz-Verbundkatalog". While it looks already ok (see e.g. http://stage.lobid.org/resources/HT018472857) it would be best to simpify the code by removing the unnecassary code.

**Comment by dr0i** [comment]
I think I closed this unintentionally.
