### ISSUE TITLE
Replace rdau:P60339 with bf:responsibilityStatement

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#233]

**Comment by fsteeg** [comment]
Requires UI update, see https://github.com/hbz/lobid-resources/pull/250#issuecomment-286054640

**Comment by fsteeg** [comment]
Deployed UI update to stage: http://stage.lobid.org/resources/HT002213253

@dr0i: please include this via branch `233-statement` when deploying to production.

**Comment by dr0i** [comment]
Deployed to production, closing.
