### ISSUE TITLE
Update context location

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#237]
We should update the context location:

- [x] in the data: http://lobid.org/resources/context.jsonld
- [x] remove the Apache redirect for `http://lobid.org/download/context.json`
- [x] write the context to `lobid-resources/web/conf/context.jsonld` directly
- [x] update context documentation in README (how to change context)

**Comment by dr0i** [comment]
Deployed to staging, see http://test.lobid.org/resources/context.jsonld.
(sorry to have the PR as a bundle (see above) and not solely PRs. Will change that in future as discussed offline.)

**Comment by dr0i** [comment]
The apache redirect should be removed after having deployed this to production.

**Comment by fsteeg** [comment]
+1

**Comment by dr0i** [comment]
Removed the apache redirect. Note that `http://lobid.org/download/context.json` will nonetheless resolve because of the redirect for the hole `download` directory, which is needed for other things.
Closing this issue.
