### ISSUE TITLE
Regroup publication information

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#239]
Taken from the discussion in https://github.com/hbz/lobid-resources/issues/59#issuecomment-279744128 ff.

**Example [HT002213253](http://lobid.org/resources/HT002213253)**

Current [JSON-LD](http://lobid.org/resources/HT002213253?format=json) (snippet):

```json
"publication":[
   {
      "endDate":"1934",
      "location":"Berlin",
      "publishedBy":"Weidmann",
      "startDate":"1934",
      "type":[
         "PublicationEvent"
      ]
   }
],
"publicationFrequency":[
   {
      "id":"http://marc21rdf.info/terms/continuingfre#i",
      "label":"dreimal wöchentlich"
   }
],
"secondaryPublication":{
   "description":[
      "Mikrofilm-Ausg.",
      "Berlin : Staatsbibliothek zu Berlin, 1999"
   ],
   "location":"Berlin",
   "publishedBy":"Staatsbibliothek zu Berlin",
   "startDate":"1999",
   "type":[
      "PublicationEvent"
   ]
}
```

Desired JSON:

```json
"publication":[
   {
      "endDate":"1934",
      "location":"Berlin",
      "publishedBy":"Weidmann",
      "startDate":"1934",
      "type":[
         "PublicationEvent"
      ],
      "frequency":{
         "id":"http://marc21rdf.info/terms/continuingfre#i",
         "label":"dreimal wöchentlich"
      }
   },
   {
      "description":[
         "Mikrofilm-Ausg.",
         "Berlin : Staatsbibliothek zu Berlin, 1999"
      ],
      "location":"Berlin",
      "publishedBy":"Staatsbibliothek zu Berlin",
      "startDate":"1999",
      "type":[
         "SecondaryPublicationEvent"
      ]
   }
]
```

This basically means to change x things:

- [ ] rename `publicationFrequency` to `frequency` and put the frequency object into the `PublicationEvent` object
- [ ] remove `secondaryPublication` property and add the secondary publication object to the `publication` array
- [ ] type secondary publication as `SecondaryPublicationEvent`

**Comment by acka47** [comment]
I just took another look at this and wondered where the `endDate` information comes from. It doesn't look like this is correct. We should either have no `endDate` at all or use a correct date.

**Comment by acka47** [comment]
I made another issue regarding the startDate/endDate for periodicals at #285.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to stage, see e.g. http://stage.lobid.org/resources/CT003012479?format=json. @fsteeg ready for (possibly needed) UI update.

**Comment by fsteeg** [comment]
Publication info looks good: http://stage.lobid.org/resources/CT003012479

**Comment by acka47** [comment]
> Publication info looks good: http://stage.lobid.org/resources/CT003012479

I disagree. I doesn't show the information from `PublicationEvent` but only from `SecondaryPublicationEvent`.

**Comment by dr0i** [comment]
Reopened while unexpectly closed, yes @fsteeg ?
