### ISSUE TITLE
Update UI for index changes in #253

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#255]
Update UI for index changes in #253.

**Comment by fsteeg** [comment]
Was an issue with index alias config, now using `resources-smalltest`, looks fine:
http://test.lobid.org/resources/search

**Comment by dr0i** [comment]
OK , but `resources-smalltest` is not the latest index (which is to be tested). That ould be `resources-20170219-0600` . Anyway, the multiple alias of `resources-staging` was indeed the problem.
Closing for now.

**Comment by dr0i** [comment]
We decided to demand UI updates directly on the original issue, i.e. #204.
