### ISSUE TITLE
Handle missing resources and items

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#257]
See:

http://beta.lobid.org/resources/123
http://beta.lobid.org/items/123

Should be like:

http://beta.lobid.org/organisations/123

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/resources/123
http://test.lobid.org/items/123

**Comment by ChristophEwertowski** [comment]
Neither the beta nor test links are found.

**Comment by fsteeg** [comment]
> Neither the beta nor test links are found.

I'll take that as a +1 ;-)

Sorry I should have made the issue description a little more detailed. The problem on beta is that missing resources result in an internal server error, with HTTP code 500. The fix on test is that these missing resources are properly handled, with a message, and HTTP code 404.

**Comment by acka47** [comment]
+1

```
$ curl -i http://test.lobid.org/resources/123
HTTP/1.1 404 Not Found
Date: Fri, 24 Feb 2017 10:54:14 GMT
Server: Apache/2.4.10 (Linux/SUSE)
Access-Control-Allow-Origin: *
Content-Type: text/plain; charset=utf-8
Content-Length: 16

"Not found: 123"
```
