### ISSUE TITLE
Badly cataloged MAB data

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#258]
URL | MAB field | Error in jsonld 
---- | --- | ---
~~http://lobid.org/resources/BT000103077~~ | ~~599~~ | ~~http://lobid.org/resources/von is created as an Id for containedIn. Should be http://lobid.org/resources/BT000102973#! -> BT000102973~~
~~http://lobid.org/resources/search?q=publication.startDate%3A%5B2029+TO+*%5D~~ | ~~089, 090, mostly 425, 595~~ | ~~28 hits. Mostly impossible years as publication.startDate. Latest [resource](http://lobid.org/resources/HT015186671) has a publication date of 2029. Multiple of these resources have volume data in field 425-.~~ Corrected where plausible data was available.
~~http://lobid.org/resources/search?issued=0001-1400&size=100&sort=oldest~~ | '' | ~~388 hits. Mostly wrong year statements.~~
http://lobid.org/resources/HT019407711, HT019401543, HT019469434 | " | Year 2013, 1925, 1937. Can't edit.
~~http://lobid.org/resources/search?issued=0000~~ | '' | ~~19363 hits.~~ No results anymore.
~~http://lobid.org/resources/search?issued=9999~~ | '' | ~~25 hits.~~ No results anymore.
http://lobid.org/resources/search?q=title%3Ajournal | - | Lots of titles with only the title "Journal".
http://lobid.org/hbz01/HT016247254 | 425c | 2912 -> according to ZDB year 2012. Can't edit.
http://lobid.org/hbz01/HT009063035, http://lobid.org/hbz01/HT017524266, http://lobid.org/hbz01/HT018535049 | 101c | Should be earlier name but contains fields of activity (isn't referred by lobid-resources). Found multiple more. Search for more resources like this in Aleph.
~~http://lobid.org/hbz01/HT016638916~~ | ~~100a~~ | ~~Role mentioned after name. Should probably be in subfield 4.~~
~~http://lobid.org/hbz01/TT001099235~~ | ~~101p~~ | ~~Role mentioned after name. Should probably be in subfield 4. Aleph ungleich HBZ01~~
~~http://lobid.org/hbz01/HT018242370, http://lobid.org/hbz01/HT017794760~~ | ~~50.a (Druckschrift)~~ | ~~AudioVisualMedia which is also a book. Should be done after https://github.com/hbz/lobid-resources/issues/349~~
~~http://lobid.org/resources/HT012237361~~ | ~~360~~ | ~~Multiple titles of subseries. Should be one title.~~ Concated in morph. 
~~http://lobid.org/resources/search?q=publication.description%3A%22Mikrofiche-Ausg.%3A%22~~ | ~~610~~ | ~~117572 hits. Out of the first 30 hits, 24 are called "Mikrofiche-Ausg.:".~~ Field relates to SecondaryForms.
~~http://lobid.org/resources/HT009578713, http://lobid.org/resources/HT007640033, http://lobid.org/resources/CT003053572, http://lobid.org/resources/BT000141043, http://lobid.org/resources/BT000089522, http://lobid.org/resources/BT000077891~~ | 050..........a (plane 10, Landkarte) | These resources aren't typed as maps. The Pauluskarte is a map (https://www.lwl.org/LWL/Kultur/Aufbruch/popups/kult/kirche/neuorganisation/paulus_karte_1620/index_print_html).
~~http://lobid.org/resources/HT009578713, http://lobid.org/resources/HT007640033~~ | ~~403~~ | ~~Scale of maps is located here in "Ausgabebezeichnung in Vorlageform". Should it be like this?~~
~~http://lobid.org/resources/BT000089522, http://lobid.org/resources/BT000077891~~ | ~~359~~ | ~~Scale is located in "Verfasserangabe".~~
~~http://lobid.org/resources/TT003060418~~ | ~~410~~ | ~~Contains publisher and year in MAB field for place of publisher.~~
http://lobid.org/resources/TT001726537 | 410 | Cologne [i.e. Amsterdam]
http://lobid.org/resources/HT006266886 | 088c | "Medienzentrum" as a signature
~~http://lobid.org/resources/BT000100437~~ | ~~403~~ | ~~Scale is given instead of edition.~~
~~http://lobid.org/resources/HT018957942~~ | ~~400, 403~~ | ~~Edition is given in 403 ("Ausgabebezeichnung in Vorlageform") and not 400 ("Ausgabebezeichnung in normierter Form") although both DNB catalog and publisher state that it is the "1. Auflage" and not "11". Both aren't in MAB data anymore.~~
http://lobid.org/resources/HT015865114 | 451, 455 | Edition ```<vonTei>```. Nothing like this stated in the catalog of the DNB (EAN: 9783766146878). In other cataloges you can find something like "2. Aufl.", "Hauptband" or "Schülerband".
~~http://lobid.org/resources/search?q=isbn:*&t=Series&aggregations=type~~ | ~~052.r, 052.se, 540~~ | ~~(29 hits) Series can't have ISBNs; only the volumes in it.~~ Wrongly data which isn't allowed to be changed.
~~http://lobid.org/hbz01/HT019011249~~ | ~~655e1.3~~ | ~~"Volltext" instead of "Voltext"~~
http://lobid.org/resources/HT006949254 | 542a1.a | Also contains title of the resource. I can't edit it.
~~http://lobid.org/resources/HT003651380~~ | ~~540~~ | ~~Is a series but has ISBNs. Remove ISBNs.~~ According to the [DNB](http://www.dnb.de/DE/Wir/Kooperation/ISSN/angabeISSN.html) there are cases with ISBN and ISSN.
~~http://lobid.org/hbz01/HT019026784~~ | ~~595~~ | ~~`2013-2014` instead of `2013-21014`.~~
~~http://lobid.org/hbz01/HT018894067~~ | ~~200b1.e~~ | ~~`edt` should be in subfield b or 4.~~
http://lobid.org/hbz01/HT019261884 | 200b1.e | `Sonstige`should be removed, already in subfield 3. I can't edit it.
~~http://lobid.org/hbz01/HT017663161~~ | ~~200-1.g~~ | ~~`(DE-588)1012753-7` should be in MAB `200-1.9`.~~
~~http://lobid.org/resources/HT011192248 and http://lobid.org/resources/TT001211556~~ | - | ~~The same. Is already removed.~~
http://lobid.org/resources/TT000402368 | 050....aj but also edition "1 CD" | Combination or error?
http://lobid.org/hbz01/HT015894164 | 078e1.a | Field doesn't contain a right ISIL. Is it necessary here? `ZDB-13-SOC-article`, `-ebook` and `-statistic` together are ~14500 resources.
http://lobid.org/hbz01/BT000110055 | 200b1.a | Should be 200b1.g because "Kall" is a place.
http://lobid.org/resources/HT018243245.json | 611, 613, 619 | Has no shown content for secondary publication.
http://lobid.org/hbz01/HT015041110, http://lobid.org/hbz01/HT019065667 | 425c | Should be 2015, probably 1912.
~~http://lobid.org/resources/search?q=_exists_:zdbId+AND+_exists_:isbn~~ | ~~025z, 540~~ | ~~~1000 hits. Either it is a `Series` or `Periodical` without an `isbn` or it is a volume with an `isbn`.~~ Update: Mrs. Block said there are also some multi volume books in the ZDB.
[query](http://lobid.org/resources/search?q=natureOfContent.label%3A%22http%5C%3A%5C%2F%5C%2Fd-nb.info%5C%2Fgnd%22) | 064a | Missing `natureOfContent.label`: HT019489988 (Kundt, Wolfgang), HT019238116, HT019175332 and HT018555185 (Bloch, Peter). I can't edit them.
[query](http://lobid.org/resources/search?q=subject.componentList.label%3A588+OR+subject.label%3A588) | 900s | ~~130 subjects with id in label~~ 34 with DE-588

notation | label | resource
-- | -- | --
(DE-588)1062481119 || http://lobid.org/resources/HT019690330
(DE-588)108597569X || http://lobid.org/resources/HT019630850
~(DE-588)1087227593~ | ~Wikipedia~ | ~http://lobid.org/resources/HT019628846~
~(DE-588)1124557482~ | ~Wang, Shi~ | ~http://lobid.org/resources/HT019628846~
~(DE-588)118551256~ | ~Hindemith, Paul~ | ~http://lobid.org/resources/HT000420412~
~(DE-588)118566636~ | ~Krenek, Ernst~ | ~http://lobid.org/resources/HT000420412~
~(DE-588)118602985~  | ~Rossini, Gioachino | ~http://lobid.org/resources/HT007259380~, ~HT014353869~
~(DE-588)118852213~ | ~Bloch, Ernest~ | ~http://lobid.org/resources/HT000420412~
~(DE-588)118587943  || http://lobid.org/resources/HT000562011~
~(DE-588)118594117  || http://lobid.org/resources/HT000562011~
~(DE-588)118602985~ | ~Rossini, Gioachino~ | ~http://lobid.org/resources/HT014623418, HT013416306, HT008386173 (freie Verschlagwortung?), HT013882256 (freie Verschlagwortung?), HT012822602 (freie Verschlagwortung?)~
~(DE-588)118605690~ | ~Satie, Erik~ | ~http://lobid.org/resources/HT000420412~
~(DE-588)118610023~ | ~Schönberg, Arnold~ | ~http://lobid.org/resources/HT000420412~
~(DE-588)118630830~ | ~Wellesz, Egon~ | ~http://lobid.org/resources/HT000420412~
~(DE-588)118642545~ | ~Stravinsky, Igor~ | ~http://lobid.org/resources/HT000420412~
~(DE-588)118699792~ | ~Hába, Alois~ | ~http://lobid.org/resources/HT000420412~
~(DE-588)11892091X~  | ~Frank, Bartholomäus G.~ | ~http://lobid.org/resources/TT000806889~
~(DE-588)118920928~ | ~Wannenmacher, Johann~ | ~http://lobid.org/resources/TT000806889~
~(DE-588)118920936~  | ~Alder, Cosmas~ | ~http://lobid.org/resources/TT000806889~
~(DE-588)11894357X~ | ~Tarde, Gabriel de~ | ~http://lobid.org/resources/HT019619606~
~(DE-588)119389533~ | ~Pizzetti, Ildebrando~ | ~http://lobid.org/resources/HT000420412~
~(DE-588)4011882-4~ | ~Deutschland~ | ~http://lobid.org/resources/HT010179341, HT000358817~
~(DE-588)4028966-7~ | ~Jugoslawien~ | ~http://lobid.org/resources/HT019152251.json (within the label chain)~
~(DE-588)4043271-3~ | ~Österreich~ | ~http://lobid.org/resources/HT016577755~
~(DE-588)4044660-8~ | ~Paris~ | ~http://lobid.org/resources/HT008346264, HT008346265, HT008346263, HT008346260, HT008346261, HT008346262, HT013177258, HT013177283, HT013177270, HT013177278, HT008319242~
~(DE-588)42800-0~ | ~Harvard Graduate School of Business Administration~ | ~http://lobid.org/resources/HT019650125~
~(DE-588)4699643-6~ | ~International Financial Reporting Standards~ | ~http://lobid.org/resources/HT019382592~
(DE-601)091346584 || http://lobid.org/resources/HT019630850
(DE-601)091351405 || http://lobid.org/resources/HT019650125
(DE-601)091353777 || http://lobid.org/resources/HT019628846
(DE-601)091355249 || http://lobid.org/resources/HT019619606
(DE-601)091361540 || http://lobid.org/resources/HT019650125
(DE-601)09136311X || http://lobid.org/resources/HT019650125
(DE-601)091366739 || http://lobid.org/resources/HT019628846
(DE-601)091372089 || http://lobid.org/resources/HT019630850
(DE-601)091375762 || http://lobid.org/resources/HT019690330
(DE-601)091379903 || http://lobid.org/resources/HT019630850
(DE-601)091384354 || http://lobid.org/resources/HT019690330
(DE-601)091385261 || http://lobid.org/resources/HT019690330
(DE-601)091396867 || http://lobid.org/resources/HT019690330, HT019650125
(DE-601)091400910 || http://lobid.org/resources/HT019619606
(DE-601)09140097X || http://lobid.org/resources/HT019650125
(DE-601)081902255 || http://lobid.org/resources/HT019690330
(DE-601)100981763 || http://lobid.org/resources/HT019650125
(DE-601)139814183 || http://lobid.org/resources/HT019619606
(DE-601)550010750 || http://lobid.org/resources/HT019630850
(DE-601)632320737 || http://lobid.org/resources/HT019628846
(DE-601)799218103 || http://lobid.org/resources/HT019628846
(DE-601)80679951X || http://lobid.org/resources/HT019690330
(DE-601)849049385 || http://lobid.org/resources/HT019630850
(DE-601)851562426 || http://lobid.org/resources/HT019628846
(DE-601)878743200 || http://lobid.org/resources/HT019628846
(DE-STW)11160-2 | Neue Institutionenökonomik | http://lobid.org/resources/HT019630850
(DE-STW)12064-0 | Privatwirtschaft | http://lobid.org/resources/HT019690330
(DE-STW)13057-6 | Luftfahrtindustrie | http://lobid.org/resources/HT019690330
(DE-STW)13507-1 | Raumfahrt | http://lobid.org/resources/HT019690330
(DE-STW)13992-3 | Unternehmer | http://lobid.org/resources/HT019628846
(DE-STW)15690-2 | Geschichte | http://lobid.org/resources/HT019650125
(DE-STW)16566-5 | Wirtschaftskultur | http://lobid.org/resources/HT019619606
(DE-STW)16745-5 | Ökonomische Ideengeschichte | http://lobid.org/resources/HT019619606
(DE-STW)17565-2 | China | http://lobid.org/resources/HT019628846
(DE-STW)17829-1 | USA | http://lobid.org/resources/HT019690330, HT019650125
(DE-STW)18143-2 | Führungskräfteentwicklung | http://lobid.org/resources/HT019650125
(DE-STW)18747-5 | Immobilienwirtschaft | http://lobid.org/resources/HT019628846
(DE-STW)18872-2 | Betriebswirtschaftsstudium | http://lobid.org/resources/HT019650125
(DE-STW)18880-3 | Wirtschaftshochschule | http://lobid.org/resources/HT019650125
(DE-STW)19040-0 | Kooperation | http://lobid.org/resources/HT019630850
(DE-STW)19488-5 | Gemeingüter | http://lobid.org/resources/HT019630850 
(DE-STW)27743-5 | Web 2.0-Technologien | http://lobid.org/resources/HT019630850
(DE-STW)29902-1 | Bauträger | http://lobid.org/resources/HT019628846

For DE-601, see [query](http://lobid.org/resources/search?q=subject.componentList.label%3A%22DE-601%22+OR+subject.label%3A%22DE-601%22) (120 hits).
For DE-STW, see [query](http://lobid.org/resources/search?q=subject.componentList.label%3A%22DE-STW%22+OR+subject.label%3A%22DE-STW%22) (120 hits).
Probably DE-601 and DE-STW originate from the ZBW.

The following resources aren't displayed in the frontend because they contents are wrongly cataloged. (See #470)

URL | MAB field | Comment
--- | --- | ---
~~http://lobid.org/hbz01/HT019353538~~ | ~~750-1~~ | ~~Contains link to publisher instead of summary-like text. Should be put into `655e1.u` (URL in access over distance).~~ SOLVED
~~http://lobid.org/hbz01/HT018851526~~ | ~~419-1.b~~ | ~~The MAB field should contain a name. The publisher is `Prima la musica!` as can be seen here: http://www.primalamusica.com/contents/en-uk/about.html. The link should also be put in 655.~~ SOLVED
~~http://lobid.org/hbz01/HT012990825~~ | 088 | ~~Link to the journal is already in 655. Error leads from the issue that `088  .b` is an URL and should be added to a note at the item. Not in "Titeldaten". Contact [Bibliothek des Ruhrgebiets](http://www.isb.ruhr-uni-bochum.de/mitarbeiter/index.html.de#bdr)?~~ SOLVED BY https://github.com/hbz/lobid-resources/pull/683
~~http://lobid.org/hbz01/TT001493152~~ | ~~501-1.a~~ | ~~Correct "Http" to "http".~~ SOLVED
~~http://lobid.org/hbz01/HT008068517~~ | ~~335~~ | ~~Remove "http://www.", put E-Mail in MAB `655a1.a` or maybe 411.~~  SOLVED
[query](http://lobid.org/resources/search?q=inCollection.id%3A%22http%3A%2F%2Flobid.org%2Fresources%2FHT014176012%23%21%22+NOT+_exists_%3AhasItem.id) | 088 | Resources in NWBib which don't have an item. ~252.000 hits (of 406.000 entries). ~51.600 hits if you [exclude Articles with journal with id](http://lobid.org/resources/search?q=inCollection.id%3A%22http%3A%2F%2Flobid.org%2Fresources%2FHT014176012%23%21%22+NOT+_exists_%3AhasItem.id+NOT+_exists_%3AcontainedIn.id&from=15)
~~[query](http://lobid.org/resources/search?q=NOT+publication.type%3APublicationEvent+AND+_exists_%3Apublication.endDate)~~ | | ~~2 resources with only an endDate, both Articles~~

I wrote an exception for 425- fields with volume statements in it (pull request #300) although I found out they are not as many as I supposed. Can be removed if files are corrected.

**Comment by acka47** [comment]
This sounds like a good solution for this: Before adding a link to the data, we should check whether the field content has the form of an hbz ID or ZDB ID.

**Comment by ChristophEwertowski** [comment]
Copying some data from API documentation: 

Search | Missing data
------| ------ 
http://lobid.org/resources/search?q=_missing_:extent | Over 6 Mio. without extent
http://lobid.org/resources/search?q=_missing_:language.id | Ca. 8,5 Mio. without language
http://lobid.org/resources/search?q=_missing_:title | Ca. 1950 without title
http://lobid.org/resources/search?q=_missing_:publication.startDate | Ca. 1.480.000 without date

**Comment by ChristophEwertowski** [comment]
Closing this issue as many errors are corrected. A little bit I will forward to cataloging collegues.
