### ISSUE TITLE
Do we want our data be more MARCy (i.e. more separate subproperties) ?

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#26]
Comment from @acka47 at https://github.com/lobid/lodmill/issues/771#issuecomment-183451646:
 
> Thinking about it you are both right to have it in a separate field for API 2.0. The question is whether we should do this for all subfields and, thus, making our data more MARCy...

I.e. we would have separate fields e.g. of birth `dates`, `locations` of events, dates of events (See https://wiki1.hbz-nrw.de/display/VDBE/GND-2+-+Neue+Unterfeldstruktur+in+BIB). I think these are the  most interesting fields, we could then make queries like "give me all conferences in the near of cologne between 1990-2010".
While it's always good to know what we could `theoretically` do , we mustn't forget to follow our *prime directive*, that is: do stuff that is demanded by customers.

**Comment by acka47** [comment]
We won't do this now. There are no use cases, we have little resources and it is no problem to add more information to the data after the API 2.0 launch without breaking the API. Closing.
