### ISSUE TITLE
Improve load time of HTML pages

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#264]
Currently, loading a single resource via its URL in the browser – e.g. http://lobid.org/resources/HT002948556 – takes > 5s, which is even longer than loading search results (which isn't that quick either). At some point we need to improve the performance before the launch. Directly getting the JSON is fine though (e.g. http://lobid.org/resources/HT018138118?format=json).

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/resources/HT002948556
http://test.lobid.org/resources/HT018138118

**Comment by fsteeg** [comment]
Updated samples for current test deployment:

http://test.lobid.org/resources/HT000269005
http://test.lobid.org/resources/HT007843611

**Comment by ChristophEwertowski** [comment]
When I clicked the first example this morning it took approximately 7 seconds but now it's a lot faster. +1

**Comment by acka47** [comment]
+1
