### ISSUE TITLE
Use generic approach for subject information

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#265]
This originates from #187. 

Generally, we have the problem that the catalog provides subject information from different authority files and classifications. We started with GND subjects in lobid and later added DDC, NWBib subjects and RPB subjects. There are still a lot of subjects that don't get into the RDF (e.g. RVK and MeSH). We should use a generic approach for the subject headings that enables us to later add missing subjects. This approach should also cover NWBib and RPB which we created specific properties for in the past. 

A good example is http://lobid.org/resources/HT015305889#! as it has subject information from four different sources: RPB, NWBib, GND and DDC. Currently, this looks like follows (snippets).

[Source](http://lobid.org/hbz01/HT015305889):

```xml
<datafield tag="700" ind1="l" ind2="1">
  <subfield code="a">rpb824020</subfield>
</datafield>
<datafield tag="700" ind1="l" ind2="1">
  <subfield code="a">550</subfield>
</datafield>
<datafield tag="700" ind1="l" ind2="1">
  <subfield code="a">130</subfield>
</datafield>
<datafield tag="700" ind1="b" ind2="1">
  <subfield code="a">780</subfield>
</datafield>
<datafield tag="700" ind1="n" ind2="1">
  <subfield code="a">99</subfield>
  <subfield code="b">Köln</subfield>
</datafield>
<datafield tag="700" ind1="n" ind2="1">
  <subfield code="a">824040</subfield>
</datafield>
<datafield tag="902" ind1="-" ind2="1">
  <subfield code="p">Bares, Peter</subfield>
  <subfield code="d">1936-2014</subfield>
  <subfield code="9">(DE-588)13163514X</subfield>
</datafield>
```

[JSON-LD](http://lobid.org/resources/HT015305889?format=json):

```json
{
  "@context" : "http://lobid.org/download/context.json",
  "id" : "http://lobid.org/resources/HT015305889#!",
  "nwbibSubject" : [ {
    "id" : "http://purl.org/lobid/nwbib#s824040",
    "label" : "Komponisten"
  } ],
  "rpbSubject" : [ {
    "id" : "https://w3id.org/lobid/rpb2#n550",
    "label" : "Musik"
  }, {
    "id" : "http://purl.org/lobid/rpb#n824020",
    "label" : "Instrumentalmusiker"
  }, {
    "id" : "https://w3id.org/lobid/rpb2#n130",
    "label" : "Landeskunde Region Koblenz"
  } ],
  "subject" : [ {
    "dateOfBirth" : "1936",
    "dateOfDeath" : "2014",
    "id" : "http://d-nb.info/gnd/13163514X",
    "label" : "Bares, Peter",
    "type" : [ "Person" ]
  }, {
    "id" : "http://dewey.info/class/780/",
    "label" : "Musik"
  } ]
}
```

Generally, I propose to represent this in JSON-LD as follows (with `source` mapped to [`bf:source`](http://id.loc.gov/ontologies/bibframe/source)):

```json
{
  "@context" : "http://lobid.org/download/context.json",
  "id" : "http://lobid.org/resources/HT015305889#!",
  "subject" : [ {
    "dateOfBirth" : "1936",
    "dateOfDeath" : "2014",
    "id" : "http://d-nb.info/gnd/13163514X",
    "label" : "Bares, Peter",
    "type" : [ "Person" ],
    "source": "http://www.wikidata.org/entity/Q36578"
  }, {
    "id" : "http://dewey.info/class/780/",
    "label" : "Musik",
    "source": "http://www.wikidata.org/entity/Q48460"
  },
  {
    "id" : "https://w3id.org/lobid/rpb2#n550",
    "label" : "Musik",
    "source": "https://w3id.org/lobid/rpb2"
  }, {
    "id" : "http://purl.org/lobid/rpb#n824020",
    "label" : "Instrumentalmusiker",
    "source": "https://w3id.org/lobid/rpb2"
  }, {
    "id" : "https://w3id.org/lobid/rpb2#n130",
    "label" : "Landeskunde Region Koblenz",
    "source": "https://w3id.org/lobid/rpb2"
  },
  {
    "id" : "http://purl.org/lobid/nwbib#s824040",
    "label" : "Komponisten",
    "source": "http://purl.org/lobid/nwbib"
  }
 ]
}
```

For GND subject chains, we should add a `madsrdf:ComplexSubject` like proposed in #187. The last open question would then be what to do with single GND/RSWK subjects like in the example used here. There are two options:

1. Always create a `madsrdf:ComplexSubject` for GND/RSWK subjects, even if there is only one.
2. Make an exemption for single GND/RSWK subjects and add them to the subject array like in the proposed outcome above.

**Comment by acka47** [comment]
I think we should discuss this in person on Weiberfastnacht before drinking Kölsch.

**Comment by dr0i** [comment]
> what to do with single GND/RSWK subjects like in the example used here. There are two options:

I would argue that 

a) the MAB2 definitions say: `9--       SEGMENT RSWK-SCHLAGWORTKETTEN` , so even a complex subject (aka "Schlagwortkette") with only *one** element _is_ a complex subject
b) it's not _totally_ unintuitive to imagine a chain with only one member
c) it's easier to transform everything into a chain (my favourite argument :) )
d) as it's easier to produce (see c)) it may also easier to consume

**Comment by dr0i** [comment]
Re `source`: we already use this field, see context-json. It's mapped to `dcterms:source`. What now? a) discard dcterms , b) intoduce a new field ?

**Comment by ChristophEwertowski** [comment]
Looked in the morph after dc/terms/source and found out that it is mapped on MAB field 021 which isn't found at the MAB test files (greped in the local repo).
Talked to our cataloger expert and she told me that this field describes a relationship from a secondary publication form to a primary publication and it shouldn't be a rare field. So we should introduce a new field and rename the field which is now called source.

**Comment by acka47** [comment]
As `dct:source` is used in exactly the same way as `isFormatOf` (see the [current morph, lines 220-227](https://github.com/hbz/lobid-resources/blob/a403180f75e9e9fc07d13f6046de775a0560a8b7/src/main/resources/morph-hbz01-to-lobid.xml#L220-L227)), I propose to discard `dct:source` altogether.

`021` carries the "IDENTIFIKATIONSNUMMER DER PRIMAERFORM". `isFormatOf` – for two reasons – seems to be the better choice anyway. (As we call the publication information for the secondary form `SecondaryPublicationEvent`, we might think about changing the JSON key of `isFormatOf` to `primaryForm` or so.)

**Comment by acka47** [comment]
Wow, we posted our comments in exactly the same moment.

**Comment by acka47** [comment]
@dr0i With #388 in the making you can go along as planned.

**Comment by dr0i** [comment]
I will sync the IDs for identifying the source according to #180.

**Comment by acka47** [comment]
Here is an overview over the URIs for all controlled vocabularies currently used:

- For GND, I suggest to use its GND entry: http://d-nb.info/gnd/7749153-1 (There is also an [entry in lobid-organisations](http://lobid.org/organisations/DE-588) as it also has an ISIL but for consistence with DDC we should use GND.)
- DDC also has a GND URI: http://d-nb.info/gnd/4149423-4
- RPB: http://purl.org/lobid/rpb
- RPB2: https://w3id.org/lobid/rpb2
- NWBib: http://purl.org/lobid/nwbib
- NWBib-spatial: http://purl.org/lobid/nwbib-spatial

I think, that's it. (Regarding the legacy subjects dealt with in #378, I am thinking about a solution that involves adding some kind of `source` information à la "NWBib legacy subject headings". But that will be dealt with at another time.)
