### ISSUE TITLE
Starred markers disappear after reload

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#270]
Steps to reproduce:

- Search, e.g.  http://lobid.org/resources/search?q=ehrenfeld
- Star a few results
- Reload: no more stars

They are actually starred, see http://lobid.org/resources/stars

**Comment by fsteeg** [comment]
Deployed to stage, see: http://stage.lobid.org/resources/stars

**Comment by ChristophEwertowski** [comment]
+1 (Functional review)
