### ISSUE TITLE
Wrong facets for multi word queries

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#278]
http://lobid.org/resources/search?q=ehrenfeld+nubbel

Facets shown would be correct for just querying 'ehrenfeld'.

**Comment by fsteeg** [comment]
It's actually not the counts that are wrong, but the searches linked from the facets.

**Comment by fsteeg** [comment]
Deployed to stage: http://stage.lobid.org/resources/search?q=ehrenfeld+nubbel

**Comment by ChristophEwertowski** [comment]
Doesn't work for libraries: For example, if you select the facet "Köln USB" after executing the search above you get 298 hits while the facet counts 334 ((staging)[http://stage.lobid.org/resources/search?q=ehrenfeld+nubbel&owner=http%3A%2F%2Flobid.org%2Forganisations%2FDE-38&aggregations=owner] and (productive)[http://lobid.org/resources/search?q=ehrenfeld+nubbel&owner=http%3A%2F%2Flobid.org%2Forganisations%2FDE-38&aggregations=owner]). 
For the rest: +1

**Comment by acka47** [comment]
> Doesn't work for libraries: For example, if you select the facet "Köln USB" after executing the search above you get 298 hits while the facet counts 334 

I think we already had this in the past. Isn't the underlying mechanism that the facet gives the number of _items_ while the query result lists the FRBR manifestations (or in bibframe-speak: instances)? This would mean there are 36 dublicate items...

**Comment by acka47** [comment]
@fsteeg I don't know how this count is implemented? Could you just count distinct entries in the `itemOf` field of the items in question?

**Comment by ChristophEwertowski** [comment]
Shouldn't we have the discussion why it doesn't work in https://github.com/hbz/lobid-resources/issues/207 ?

**Comment by fsteeg** [comment]
I'll look into the owner issue, but since it is unrelated to this issue (which affects all facets, and much more severly) I second @ChristophEwertowski's suggestion to discuss this in #207. Will reopen that.

**Comment by acka47** [comment]
+1
