### ISSUE TITLE
Add beta note to API documentation

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#279]
Since we decided to launch the resources and organisations APIs as beta, we should add a visible note to the API documentation pages.

**Comment by fsteeg** [comment]
Deployed to staging:

http://stage.lobid.org/resources/api
http://stage.lobid.org/organisations/api

**Comment by acka47** [comment]
I suggest to emphasize the fact that we are looking for feedback by whoever is reading this note. Maybe something like:

> Offene Beta: Details des Anfrage- und Antwortformats können sich vor ihrer endgültigen Veröffentlichung noch ändern. Wir bitten um Rückmeldungen und Hinweise auf letzte Verbesserungen der API.

**Comment by ChristophEwertowski** [comment]
What acka47 said.

**Comment by fsteeg** [comment]
Deployed to staging (shortened the suggestion a bit):

http://stage.lobid.org/resources/api
http://stage.lobid.org/organisations/api/de
http://stage.lobid.org/organisations/api/en

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
+1
