### ISSUE TITLE
Values of 'type' field should be simple values aliased to URLs

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#28]
As in the samples in #10, the values of the 'type' field should be simple values aliased to URLs.

So e.g. for http://gaia.hbz-nrw.de:9200/resources/resource/BT000168595/_source

```
"type": [ "BibliographicResource", "Book" ]
```

**Comment by acka47** [comment]
This is redundant to https://github.com/hbz/lobid-rdf-to-json/issues/26. @dr0i: it probably is best if you decide in which repo the issue fits best and close the issue in the other repo.

**Comment by dr0i** [comment]
Now I am totally confused: in #27 it's said to use `@type` with URIs as string - the same is said in https://github.com/hbz/lobid-rdf-to-json/issues/26. 

1. Why is this redundant to `"type": [ "BibliographicResource", "Book" ]` ?
2. We need to decide what to do, shouldn't we?

Can you help me out of this confusion?

**Comment by acka47** [comment]
#27 is about having an array of strings instead of objects. This is about shortening `@type` URIs via the `@context`.

**Comment by acka47** [comment]
Closing as this is a duplicate of https://github.com/hbz/lobid-rdf-to-json/issues/26.
