### ISSUE TITLE
Unify UI for resources and organisations

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#281]
Common styling for header and footer, page width, etc.

**Comment by fsteeg** [comment]
Basic idea: nav bar like in organisations, but with more readable text, page width like resources, hbz font.

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://stage.lobid.org/resources
http://stage.lobid.org/organisations

**Comment by ChristophEwertowski** [comment]
+1

**Comment by acka47** [comment]
Looks very good. There are two minor adjustment left, though: use "∞" instead the feed icon before "blog" and Capitalize "Imprint".

**Comment by fsteeg** [comment]
Redeployed, as discussed offline with pencil icon:

http://stage.lobid.org/resources
http://stage.lobid.org/organisations

**Comment by acka47** [comment]
+1
