### ISSUE TITLE
Mysterious disappearing of publication year facet

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#283]
As I opened the URLs in https://github.com/hbz/lobid-resources/issues/278#event-981705687 for testing, I got a blank publication year facet. It happened in the production and staging system. If I copy the URL and open the page in a new tab I get the right result. If I open some facets in a new tab they also have no publication year facet. Since I can't reproduce it reliably I'm trying to find out how. Thus for the moment assigning it to myself.

It's reproduceable every second time or so by opening http://lobid.org/resources/search?q=ehrenfeld+nubbel or http://stage.lobid.org/resources/search?q=ehrenfeld+nubbel in a new tab.

![erscheinungsjahrmissing](https://cloud.githubusercontent.com/assets/24875432/23462620/d77bd03e-fe8e-11e6-84d9-bde9993dc009.png)

**Comment by acka47** [comment]
Can not reporduce. Closing.
