### ISSUE TITLE
Transform 425 b/c for periodicals

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#285]
This came up at https://github.com/hbz/lobid-resources/issues/239#issuecomment-283661661.

From the MAB docu:

```
425       ERSCHEINUNGSJAHR(E)

          Indikator:
          blank = Erscheinungsjahr(e) in Vorlageform
          a     = Erscheinungsjahr(e) in Ansetzungsform
          b     = Erscheinungsjahr des ersten Bandes in Ansetzungsform
          c     = Erscheinungsjahr des letzten Bandes in Ansetzungsform
          p     = Publikationsdatum bei Tontraegern (P-Datum)

```

From the MAB source of the example:

```xml
<datafield tag="425" ind1="b" ind2="1">
  <subfield code="a">1859</subfield>
</datafield>
<datafield tag="425" ind1="c" ind2="1">
  <subfield code="a">1934</subfield>
</datafield>
```

Expected outcome:

```json
"publication":[
   {
      "endDate":"1934",
      "location":"Berlin",
      "publishedBy":"Weidmann",
      "startDate":"1859",
      "type":[
         "PublicationEvent"
      ],
      "frequency":{
         "id":"http://marc21rdf.info/terms/continuingfre#i",
         "label":"dreimal wöchentlich"
      }
   }  ]
```

**Comment by acka47** [comment]
+1 (Note to self: Take a look at http://lobid.org/resources/TT001966831 after this is deployed to production.)

**Comment by dr0i** [comment]
@acka47 reminding you at your last comment as this was closed by merging the PR.

**Comment by acka47** [comment]
Hmm, http://lobid.org/resources/TT001966831 doesn't look satisfying as the wrong value for `startDate` is taken from `089` ("2977" instead of "1999"):

```xml
<datafield tag="089" ind1="-" ind2="1">
  <subfield code="a">59,2. 1999 = 2952/2977</subfield>
</datafield>
```

**Comment by ChristophEwertowski** [comment]
Didn't thought it were that many. It's the last field in which is looked for a publication date. Opened the new issue https://github.com/hbz/lobid-resources/issues/321 in which I will tackle this. Because the rest is OK, I'm closing this issue.

**Comment by dr0i** [comment]
>  that many

The relation is 1 to 100.000.
That's not many.
As I know the cataloguers fantasy is unlimited so must be our regex to come along. If you just succeed a completeness of 99.99999% don't be too sad .
