### ISSUE TITLE
No item information available

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#287]
Examples:
http://lobid.org/items/HT000929790:DE-290:T%207141#!
http://lobid.org/items/HT019113913:DE-38:2016%2F715#!
http://lobid.org/items/HT019082336:DE-467:88XDN1402(3)#!

**Comment by fsteeg** [comment]
Deployed to stage:

http://stage.lobid.org/items/HT000929790:DE-290:T%207141
http://stage.lobid.org/items/HT019113913:DE-38:2016%2F715
http://stage.lobid.org/items/HT019082336:DE-467:88XDN1402(3)

**Comment by ChristophEwertowski** [comment]
+1

**Comment by acka47** [comment]
+1
