### ISSUE TITLE
Add information on the package an e-ressource is part of

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#288]
This information is contained in 078e, see e.g. [TT050001472](http://lobid.org/hbz01/TT050001472):

```xml
<datafield tag="078" ind1="e" ind2="1">
  <subfield code="a">ZDB-2-SWI</subfield>
  <subfield code="a">Springer</subfield>
</datafield>
``` 

Subfield `a` contains the ISIL of the e-ressource package. For this it might make sense to re-include packages in lobid-organisations which were removed in https://github.com/hbz/lobid-organisations/issues/207.

**Comment by acka47** [comment]
Requested by @hagbeck.

**Comment by acka47** [comment]
This was errorneously closed. Reopening.

**Comment by acka47** [comment]
I propose to use `inCollection` for this. At best, we look up the labels via lobid-organisations (provided that #308 is done) and add the following to the JSON:

```json
{
   "id":"http://lobid.org/resources/TT050001472#!",
   "inCollection":[
      {
         "id":"http://lobid.org/organisations/ZDB-2-SWI#!",
         "label":"Springer ebook collection / Wirtschaftswissenschaften"
      }
   ]
}
```

**Comment by ChristophEwertowski** [comment]
Didn't find a map for the ebook collections. Even though they aren't in lobid-organisations anymore, is there a list "isil-ebookName"?

**Comment by acka47** [comment]
I don't get why you would need such a list. As I wrote above:

> Subfield `a` contains the ISIL of the e-ressource package

You just have to create the URI from it, e.g.: "ZDB-2-SWI" -> http://lobid.org/organisations/ZDB-2-SWI#!

**Comment by ChristophEwertowski** [comment]
That's not the question. Should we take the label of MAB `078`, in this case "Springer" or the name from the Sigelverzeichnis "Springer ebook collection / Wirtschaftswissenschaften"?

**Comment by acka47** [comment]
For the start, we should use the value from subfield `a`.

**Comment by ChristophEwertowski** [comment]
Asked a collegue about it which looked it up in the *Feldhilfe*. According to it for each indicator (except "u") only one subfield should exist. Therefore the example with "Springer" shouldn't exist. So we agreed upon only taking only the ISILs of the packages and adding a dummy label.  
Since we can't test if it's a valid ISIL I took everything which contains a string which begins with "ZDB". For example [HT015894164 (production)](http://lobid.org/resources/HT015894164.json) / ([HT015894164 (test)](http://test.lobid.org/resources/HT015894164.json) where only `http://lobid.org/organisations/ZDB-13-SOC` contains the right ISIL.

**Comment by ChristophEwertowski** [comment]
I forgot: Please open a ticket in the lobid-organisations repository for adding the package information again.

**Comment by acka47** [comment]
> Please open a ticket in the lobid-organisations repository for adding the package information again.

See https://github.com/hbz/lobid-organisations/issues/308

**Comment by acka47** [comment]
I am not feeling good about the wrong entry in http://test.lobid.org/resources/HT015894164.json:

```json
"inCollection": [
  {
    "id": "http://lobid.org/organisations/ZDB-13-SOC-ebook#!",
    "label": "lobid Organisation"
  }
```
We should run some statistics on `078`. Questions:

- How many records have this field?
- How many have one occurence of subfield `a`? How often it occurs twice? Does it even occur more often sometimes?
- Is the (correct) ISIL always in the first occuring subfield `a`?

**Comment by hagbeck** [comment]
I'm feeling bad about the type 'lobid Organisation' for this package labels, because their are labelling collections of datasets. I would prefer a type like schema:Dataset.

Btw.: you can find a list with all labels at http://sigel.staatsbibliothek-berlin.de/vergabe/isil-fuer-produkte/ and http://sigel.staatsbibliothek-berlin.de/vergabe/neue-produktsigel/

**Comment by ChristophEwertowski** [comment]
I ran the statistics over the data. Apparently it only counts the first hit of a subfield. About 3% or 829.000 have some sort of content in "078e1.a". If you substract "NLZ", "ldd" and "Springer" there are ~177.000 resources or a bit than 1% left. 
A proposal which I'm not satisfied with can be found at http://test.lobid.org/resources/HT010726584.json. There I added the ISILs and the description page of the *Sigelverzeichnis*.

**Comment by acka47** [comment]
As already discussed offline, with https://github.com/hbz/lobid-organisations/issues/308 deployed we can now sue the lobid-organisations URIs for eResource packages, e.g.:
```json
"inCollection": [
    {
      "id": "http://lobid.org/organisations/ZDB-1-AIP#!"
    }
  ]
```

I don't know if this is realistic but a lobid-organisations lookup for the label would be nice, à la:

```json
"inCollection": [
    {
      "id": "http://lobid.org/organisations/ZDB-1-AIP#!",
      "label": "AIP Digital Archive [Archiv] [Nationallizenz]"
    }
  ]
```

@dr0i, is a lookup during transformation feasible without increasing the transformation time too much?

**Comment by dr0i** [comment]
Yes, no problem.

**Comment by ChristophEwertowski** [comment]
E-packages now have the type `Collection` and are labelled `e-ressource package` as long as we don't look up the title from lobid organisations. See [HT010726584 (test, json)](http://test.lobid.org/resources/HT010726584.json). The type `Collection` is also added to all other `inCollection` entries, see examples for edoweb and RPB ([HT014997977](http://test.lobid.org/resources/HT014997977.json)), NWBib ([HT013077595](http://test.lobid.org/resources/HT013077595.json)) and publisso ([HT016987148 (json)](http://test.lobid.org/resources/HT016987148.json)). Example for multiple packages and ZDB collection: [HT010726584](http://test.lobid.org/resources/HT010726584.json). Entries in `078e1.a` like `Springer`, `NLZ` or `ZDB-13-SOC-ebook` ([HT015894164 (MAB)](http://test.lobid.org/hbz01/HT015894164) / [HT015894164 (json)](http://test.lobid.org/resources/HT015894164.json)) aren't included.

**Comment by acka47** [comment]
+1 Just one minor thing: "resource" is written with one "s" in English. A better label thus would be "eResource package".
