### ISSUE TITLE
Add missing subfield information to subjectChain field

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#29]
The corrections from https://github.com/lobid/lodmill/issues/769, https://github.com/lobid/lodmill/issues/770 and https://github.com/lobid/lodmill/issues/771 haven't been taken into account for the `subjectChain` field. As the field is needed for the NWBib "Themensuche" the subfield information also has to be corrected there. 

To do:

- [x] Add subfield `x` for geographica
- [x] Add subfield `b` for corporate bodies
- [x] Add subfield `d` (birth/death date) for persons as subjects

**Comment by dr0i** [comment]
Deployed test set to staging. For geographica see http://gaia.hbz-nrw.de:9200/resources-staging/resource/HT017309948 ; for multiple corporate body names "b" see http://gaia.hbz-nrw.de:9200/resources-staging/resource/HT017150239 ;  for birth/death dates, see http://gaia.hbz-nrw.de:9200/resources-staging/resource/HT016671946.

**Comment by acka47** [comment]
+1 for the content. -1 for encoding of special characters, see e.g. http://gaia.hbz-nrw.de:9200/resources-staging/resource/HT016671946

**Comment by dr0i** [comment]
Encoding issues are a result of #21.

**Comment by fsteeg** [comment]
Fixed encoding issue, deployed to staging:

http://gaia.hbz-nrw.de:9200/resources-staging/resource/HT017309948
http://gaia.hbz-nrw.de:9200/resources-staging/resource/HT017150239
http://gaia.hbz-nrw.de:9200/resources-staging/resource/HT016671946

**Comment by acka47** [comment]
+1 for the encoding – on staging and "production".

**Comment by dr0i** [comment]
Deployed to production, closing.

**Comment by acka47** [comment]
Sorry, I didn't pay attention here. We _also_ need the subfields added to the production API as the "Themensuche" queries API 1.0.

**Comment by fsteeg** [comment]
Looks good on staging:

- http://test.nwbib.de/search?q=%22Heinrich-Heine-Institut%2C+Rheinisches+Literaturarchiv+|+Archivp%C3%A4dagogik+|+Jugend+|+Projekt+|+Geschichte+2009-2011%22
- http://test.nwbib.de/search?q=%22LWL-Archivamt+f%C3%BCr+Westfalen%2C+Westf%C3%A4lisches+Literaturarchiv+|+Geschichte+2001-2011%22

Issue has no process label. Are you still `working` on this, @dr0i? Or is this `review` for @acka47?

**Comment by dr0i** [comment]
Your +1 is enough. Deployed to production, closing.
