### ISSUE TITLE
Replace icons for Aleph-XML and JSON-LD

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#293]
I am repeatedly confusing the icons.

For the JSON-LD, we should use the same as in lobid-organisations: http://lobid.org/organisations/public/images/json-ld.png

For the Aleph-XML, I am not sure what to use, we may just stick with the current one. There is no MAB icon or similar. We might use an icon that indicates this is the upstream data. However, I couldn't find a fitting icon.

**Comment by fsteeg** [comment]
Deployed to staging: http://stage.lobid.org/resources/HT007000722

**Comment by acka47** [comment]
Maybe it would look better with the angle brackets in bold. But I guess you already played around with it a bit. Then +1

**Comment by ChristophEwertowski** [comment]
When I saw the MAB icon I thought about Markdown although it has a different icon; probably because of the &gt and &lt signs (which aren't even used in markdown). But since it's likely just me: +1
