### ISSUE TITLE
Describe lobid-resources dataset

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#294]
Like for lobid-organisations, see https://github.com/hbz/lobid-organisations/issues/255.

**Comment by fsteeg** [comment]
Deployed to staging:

http://stage.lobid.org/resources/dataset
http://stage.lobid.org/resources/dataset.jsonld

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
A tiny change should be done: In the jsonld, at the last sentence the "a" should be removed or behind CC0 "license" should be added. Otherwise +1
