### ISSUE TITLE
Replace rdact:1020 & rdact:1010 with rdamt:1002 & rdamt:1003

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#298]
RDA vocabularies s*ck. http://rdaregistry.info/termList/RDACarrierType/1020 & http://rdaregistry.info/termList/RDACarrierType/1010 are now depracated and should be replaced.

 http://rdaregistry.info/termList/RDACarrierType/1020 -> http://rdaregistry.info/termList/RDAMediaType/1002
http://rdaregistry.info/termList/RDACarrierType/1010 -> http://rdaregistry.info/termList/RDAMediaType/1003

**Comment by acka47** [comment]
+1 I suggest removing the medium information http://rdaregistry.info/termList/RDAMediaType/1003 from all resources that have the medium http://rdaregistry.info/termList/RDACarrierType/1018 (Online Ressource). This will be an improvement of faceting options. Will make another issue for that.

**Comment by fsteeg** [comment]
Needs UI updates, changes are deployed to stage, see https://github.com/hbz/lobid-resources/pull/305#issuecomment-286052127

**Comment by dr0i** [comment]
Hello @fsteeg , since I cannot see any changes you made and don't comprehend why you are said to have closed this issue via  5492594 I reopen this issue to be on the safe side.

**Comment by fsteeg** [comment]
Deployed to staging, see medium facet: http://stage.lobid.org/resources/search

**Comment by ChristophEwertowski** [comment]
+1
