### ISSUE TITLE
Fix internal_id to be hbz01 001, not ZDB*

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#30]
We want to http-get IDs directly, like:

http://gaia.hbz-nrw.de:9200/resources/resource/HT001387709

The resource exists, but has a wrong elasticsearch internal_id, taken form a `sameAs` entry. See http://gaia.hbz-nrw.de:9200/resources/resource/_search?q=HT001387709.

**Comment by fsteeg** [comment]
I've deployed usage of the new index in nwbib to staging.

Here's the test case: http://test.lobid.org/nwbib/HT001387709

**Comment by dr0i** [comment]
Deployed this one test resource into the full index at gaia, see  http://test.lobid.org/nwbib/HT001387709.

**Comment by fsteeg** [comment]
+1

Opened new issue https://github.com/hbz/nwbib/issues/253 (blocks https://github.com/hbz/nwbib/pull/252)

**Comment by fsteeg** [comment]
https://github.com/hbz/lobid-resources/pull/32 is merged and deployed, closing.

See http://test.lobid.org/nwbib/HT001387709 (base feature is not on production yet).
