### ISSUE TITLE
Remove medium "computer carrier" from online resources

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#307]
From https://github.com/hbz/lobid-resources/issues/298#issuecomment-285624228:

> I suggest removing the medium information http://rdaregistry.info/termList/RDAMediaType/1003 from all resources that have the medium http://rdaregistry.info/termList/RDACarrierType/1018 (Online Resource). This will be an improvement of faceting options.

**Comment by ChristophEwertowski** [comment]
Deployed to test set. There is no resource with the type computer carrier which is also an online resource: http://test.lobid.org/resources/search?medium=http%3A%2F%2Frdaregistry.info%2FtermList%2FRDAMediaType%2F1003&aggregations=medium.id.

**Comment by acka47** [comment]
+1
