### ISSUE TITLE
Correct role labels to actual roles

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#308]
The labeling of the role is not consistent. For example: http://id.loc.gov/vocabulary/relators/act is correctly labeled "Schauspieler/in". But we have other roles like http://id.loc.gov/vocabulary/relators/ctg or http://id.loc.gov/vocabulary/relators/drt which are labeled "Kartographie" and "Regie" instead of "Kartograph/in" or "Regisseur/in".
Also the label for http://id.loc.gov/vocabulary/relators/ant "Basiert auf das Werk von" should be corrected.

**Comment by acka47** [comment]
When choosing labels we tried to avoid constructions with `/`. I think we should stick to this. +1 for changing "Basiert auf das Werk von".

**Comment by ChristophEwertowski** [comment]
Because I also changed "Komponist" to "Komposition" I deployed the changed to the test system. [Example resource (test)](http://test.lobid.org/resources/CT003012479?format=json) / [example resource (production)](http://lobid.org/resources/CT003012479?format=json).

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
Taking a look at the "basiert" phrasing, I think we should rather use "Basiert auf einem Werk von" as this referes to a particular work and not the whole Oeuvre.

**Comment by ChristophEwertowski** [comment]
You are right. Look at the [commit](https://github.com/hbz/lobid-resources/pull/311/commits/75e481619db478565d64b6564153ac26cf5e98d4#diff-1f487c543d206a4373e59cc12044ac90L243).

**Comment by acka47** [comment]
+1
