### ISSUE TITLE
Put context data in separate labels file

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#310]

**Comment by ChristophEwertowski** [comment]
Do I understand it right that the context should be generated from the context-labels.json? And the labels.json is for outsourcing the labels and shortening the file from which the context is generated, right? If that's the case: +1

**Comment by acka47** [comment]
This is basically a prerequisite to work on a solution to https://github.com/hbz/lobid-rdf-to-json/issues/59.
