### ISSUE TITLE
Add endDate to publications with secondaryPublicationType

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#315]
http://lobid.org/hbz01/HT008733617 is transformed into two startDates of the same publication because there is no endDate for secondary publications. There are two ways to handle this:
* only include the first number of the 619 field
* also add an endDate for secondary publications

**Comment by ChristophEwertowski** [comment]
Already implemented this in commit 546c039. But since it wasn't deployed, I'm commiting the part of the which concerns this issue again (the other part is already better implemented). @acka47: Talked a while ago with @fsteeg about it and he meant, it would be better if the endDate is handled the same for primary and secondary publications. I think, it isn't bad to have the data in the json because it won't be too much affected files and it can be interesting (what's the biggest digitalisation project?). In any case, I did one commit for startDate and endDate each so it can be reversed.

**Comment by ChristophEwertowski** [comment]
Ah, I forgot to link to the example: http://test.lobid.org/resources/HT008733617?format=json / http://lobid.org/resources/HT008733617?format=json

**Comment by acka47** [comment]
+1
