### ISSUE TITLE
Display start and end dates

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#316]
Originated from https://github.com/hbz/lobid-resources/pull/300#issuecomment-286435853

**Comment by fsteeg** [comment]
Deployed to test and stage, but not visible because it seems like all start and end dates are identical:

http://test.lobid.org/resources/search?q=publication.endDate:*&format=json
http://stage.lobid.org/resources/search?q=publication.endDate:*&format=json

According to @acka47  in https://github.com/hbz/lobid-resources/pull/300#issuecomment-286435853 this one should have different dates:

http://test.lobid.org/resources/HT002619538
http://stage.lobid.org/resources/HT002619538

As discussed offline, assigning @ChristophEwertowski to look into the issue.

**Comment by dr0i** [comment]
> According to @acka47 in #300 (comment) this one should have different dates:
  http://test.lobid.org/resources/HT002619538
http://stage.lobid.org/resources/HT002619538

Yes - and they have! What do I not see?

**Comment by acka47** [comment]
> Yes - and they have! What do I not see?

It's because @ChristophEwertowski fixed the issue in the meantime, see commits fro  yesterday at https://github.com/hbz/lobid-resources/pull/317.

**Comment by dr0i** [comment]
No - these commits are not deployed yet. The `stage` and now even production is based on the data created with the commits of #300.

**Comment by dr0i** [comment]
(On production http://lobid.org/resources/HT002619538 can't be seen yet because of caching).
