### ISSUE TITLE
Display both primary and secondary publication

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#318]
Currently the first one is used, see:

http://lobid.org/resources/HT008733617
http://lobid.org/resources/HT008733617?format=json

Should include fix for #347, see:

http://lobid.org/resources/HT016805170

Should handle open ranges as reported in #423, see:

http://lobid.org/resources/HT013878511
http://lobid.org/resources/HT012712077

Should display frequency labels as reported in #362, see:

http://lobid.org/resources/HT012712077
http://lobid.org/resources/HT016805170

**Comment by fsteeg** [comment]
Deployed to stage:

http://stage.lobid.org/resources/HT008733617
http://stage.lobid.org/resources/HT016805170
http://stage.lobid.org/resources/HT013878511
http://stage.lobid.org/resources/HT012712077

**Comment by ChristophEwertowski** [comment]
The secondary publication should be shown under the primary publication. Otherwise it looks fine.

**Comment by fsteeg** [comment]
Redeployed with publications sorted by date:

http://stage.lobid.org/resources/HT008733617
http://stage.lobid.org/resources/HT016805170
