### ISSUE TITLE
Only take right publication years from volume field

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#321]
@acka47 said in #285 [comment](https://github.com/hbz/lobid-resources/issues/285#issuecomment-287305353):
> Hmm, http://lobid.org/resources/TT001966831 doesn't look satisfying as the wrong value for startDate is taken from 089 ("2977" instead of "1999"):
>```<datafield` tag="089" ind1="-" ind2="1">
  <subfield code="a">59,2. 1999 = 2952/2977</subfield>
</datafield>```
>There are approximately 100 other resources where the wrong number is taken: http://lobid.org/resources/search?size=100&sort=newest

**Comment by ChristophEwertowski** [comment]
Problem is solved with a partly reasonable effort. It is looked for "volume. year", the rest of the MAB fields 089 is ignored. See [example (production)](http://lobid.org/resources/TT001966831) / [example (test)](http://test.lobid.org/resources/TT001966831).

**Comment by acka47** [comment]
+1
