### ISSUE TITLE
Rename subjectLabel to subjectAltLabel

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#325]
See https://github.com/hbz/lobid-resources/issues/197#issuecomment-287703813

**Comment by ChristophEwertowski** [comment]
SubjectLabels changed to SubjectAltLabels, see for example: http://lobid.org/resources/HT013577568?format=json / http://test.lobid.org/resources/HT013577568?format=json

**Comment by acka47** [comment]
+1
