### ISSUE TITLE
Show publication date of primary publication

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#333]
Show publication date of publication type "PublicationEvent" and not "SecondaryPublicationEvent". For the example http://test.lobid.org/resources/HT008733617 this would be "1624" and not "1990-1994". Depends on https://github.com/hbz/lobid-resources/issues/315 (which gets the right startDate and endDate for secondaryPublications).

**Comment by fsteeg** [comment]
Resolved with https://github.com/hbz/lobid-resources/issues/318, closing.
