### ISSUE TITLE
Take into account MARC relators "art" and "cmp"

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#336]
`art` ("Künstler/in", example http://lobid.org/resources/HT018782520) and `cmp` ("Komposition", example http://lobid.org/resources/HT018782520) aren't taken into account in the transformation yet. (Originated at https://github.com/hbz/lobid-resources/issues/72#issuecomment-288680688.)

**Comment by ChristophEwertowski** [comment]
The problem should be solved. I can't look it up for "Komposition" because it's the same resource. For the role artist see: http://lobid.org/resources/HT018782520 / http://test.lobid.org/resources/HT018782520

**Comment by acka47** [comment]
https://lobid.org/resources/HT018781534 is the resource with `cmp` but it obviously is not part of the test set. +1

**Comment by ChristophEwertowski** [comment]
Added it to the test set: https://test.lobid.org/resources/HT018781534 / https://lobid.org/resources/HT018781534

**Comment by acka47** [comment]
+1
