### ISSUE TITLE
Some confusing labels in owner facet

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#340]
Some display names are strange in the owner facet. Looking at http://lobid.org/resources/search?q=, I found the following:

- "DE-646" I don't get it why the name is not shown, see http://lobid.org/organisations/DE-464
- [ZDB-1-ECC](http://ld.zdb-services.de/resource/organisations/ZDB-1-ECC) and [ZDB-1-EEB](http://ld.zdb-services.de/resource/organisations/ZDB-1-EEB): these are eBook packages we currently don't have in lobid-organisations  and they obviously are somehow catalogued as owners. (A first fix might be the addition of packages to lobid-organisations as proposed in https://github.com/hbz/lobid-organisations/issues/308
- DE-386-02, DE-61-51, DE-386-48: These are "Untersigel" not present in lobid-organisations, see also https://github.com/hbz/nwbib/issues/77.
- "WH" for http://lobid.org/organisations/DE-1010: obviously the wrong alternate name is taken for display and not the "standard abbreviation". In the Sigeldata "standard abbreviation" and other alternate names are differentiated by a code in subfield `4` of Pica+ field `029`: `c` for standard abbreviation and `a` for other alternate name, see [documentation](http://sigel.staatsbibliothek-berlin.de/vergabe/adressenformat/410/). Possible fix: Make an analogous differentiation in lobid-organisations RDF.

**Comment by fsteeg** [comment]
Deployed to stage, see owner facet for these searches:

http://stage.lobid.org/resources/search?q=Duisburg-Essen
http://stage.lobid.org/resources/search?q=ZDB
http://stage.lobid.org/resources/search?q=Kaiserslautern
http://stage.lobid.org/resources/search?q=Gelsenkirchen

These changes help to avoid confusion when looking at the owner facet and thus fix this issue. Some of the changes are workarounds, so we should leave the issues mentioned in the original comment open.

**Comment by ChristophEwertowski** [comment]
For now the facets are good. +1
