### ISSUE TITLE
Replace RDA video carrier and add label for microform resources

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#344]
[RDACarrierType/1050 (Video carrier)](http://www.rdaregistry.info/termList/RDACarrierType/#1050) is deprecated. Instead there are more granular carrier types for different sorts of microfilm, video et cetera (1024-1027, 1032-1037, 1051-1053, 1056, 1060, 1069). Bibo only has http://purl.org/ontology/bibo/AudioVisualDocument. Schema.org also doesn't seem to have a property which covers all videos/films. 
http://id.loc.gov/ontologies/bibframe/MovingImage is probably the best alternative.

**Comment by acka47** [comment]
There's also http://rdaregistry.info/termList/RDAMediaType/1008.

**Comment by ChristophEwertowski** [comment]
Replaced the [video carrier](http://www.rdaregistry.info/termList/RDACarrierType/#1050) with [RDAMediaType/1008](http://rdaregistry.info/termList/RDAMediaType/1008) because it also covers movies of still images. Because the label was missing, I added it for video and microform. 
* [Example video (production)](http://lobid.org/resources/HT006266886?format=json) / [example video (test)](http://test.lobid.org/resources/HT006266886?format=json)
* [Example microform (production)](http://lobid.org/resources/HT008733617?format=json) / [example microform (test)](http://test.lobid.org/resources/HT008733617?format=json)

**Comment by acka47** [comment]
+1
