### ISSUE TITLE
No proper title for "Unterreihen"

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#346]
See e.g. http://lobid.org/resources/HT012996101 and volumes. It is actually der "Uni-Spiegel" but we don't have this anywhere in the RDF, let alone in the display.

**Comment by ChristophEwertowski** [comment]
Now the title of a subseries can be found in the data, see: http://test.lobid.org/resources/HT012996101?format=json (titleOfSubSeries). If the label is right, I would at it to the vocabulary.

Of course it isn't shown in the frontend. Two possiblities: 
* The short version: Title / title of subseries.
* Like the ZDB: Titel. Extra field "Unterreihe".

**Comment by acka47** [comment]
There certainly is a fitting RDA unconstrained property. Searching for "subseries" at http://www.rdaregistry.info/Elements/u/ gives 10 results. http://rdaregistry.info/Elements/u/P60517 should do it. 

For the start that shoulld do it. We might add repetitions of `360` later as an array with http://rdaregistry.info/Elements/u/P60495...

**Comment by ChristophEwertowski** [comment]
URL is swapped. It won't be visible on test page but you can see it in the hbz.es.nt (line 5025) or the labels.json / context file.

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
(We should leave this issue open until the subseries title is shown in the UI.)

**Comment by acka47** [comment]
> Of course it isn't shown in the frontend. Two possiblities: 
> * The short version: Title / title of subseries.
> * Like the ZDB: Titel. Extra field "Unterreihe".

I think we have to go with the second option. By now I also think, we should concatenate repetitions of 360 in the literal with seperator `;` or `.`.

**Comment by ChristophEwertowski** [comment]
Changed on the data side, see [example (test)](http://test.lobid.org/resources/HT012237361?format=json) / [example (production)](http://lobid.org/resources/HT012237361?format=json). As you can see, I took the point as a seperator.

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
Like stated in the above comments ([1](https://github.com/hbz/lobid-resources/issues/346#issuecomment-290093776)/[2](https://github.com/hbz/lobid-resources/issues/346#issuecomment-290358301)) of acka47 titles of subseries should be shown in an extra field "Unterreihe". See [example from above](http://lobid.org/resources/HT012237361?format=json).

**Comment by fsteeg** [comment]
Deployed to stage:

http://stage.lobid.org/resources/HT012237361
http://stage.lobid.org/resources/HT012996101

**Comment by ChristophEwertowski** [comment]
+1 As the last change only refers to the frontend and the rest is approved, assigning it to fsteeg for deployment.
