### ISSUE TITLE
describedby should be describedBy

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#358]
For consistency (general camelCasing, specifically collectedBy), `describedby` should be `describedBy`.

**Comment by ChristophEwertowski** [comment]
Will be set for functional review if other functional reviews were went through.

**Comment by ChristophEwertowski** [comment]
[Example (production)](http://lobid.org/resources/HT017028573?format=json) / [example (test)](http://test.lobid.org/resources/HT017028573?format=json).

**Comment by fsteeg** [comment]
Looks good, +1

I'm a bit confused about the property in general though, `describedBy`, it contains creation and modification dates, and links to itself via `id`? Is this correct @acka47?

**Comment by acka47** [comment]
Yes, it is. `http://lobid.org/resources/{hbzId}#!` identifies the bibliographic resource (the instance/manifestation of a book, the journal etc.) and `http://lobid.org/resources/{hbzId}` identifies the page/file served by lobid describing the bibliographic resource (the "record") . This gives us the possibility to separate statements about the different things. E.g. the creation dates of both necessarily differs from each other.

**Comment by acka47** [comment]
+1
