### ISSUE TITLE
Replace shortcuts

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#363]
Replace or delete shortcuts ```s.l.``` (sine loco, without a place) ([example](http://lobid.org/resources/TT003060418)), ```s.a.``` (sine anno, without a year), ```s.n.``` (sine nomine, without a name) ([example](http://lobid.org/resources/HT017028573)). 
Otherwise it won't be shown if you search for missing resources. Additionally in many cases non-librarians won't know the abbreviation. 

Found more shortcuts which probably aren't used: ```S.a.e.l.``` (sine anno et loco) and ```S.l.e.a.``` (sine loco et anno).

**Comment by ChristophEwertowski** [comment]
* ```S.a.``` was already covered. 
* [Example (production)](http://lobid.org/resources/HT010726584?format=json) / [example (test)](http://test.lobid.org/resources/HT010726584?format=json) for ```s.l.```
* [Example (production)](http://lobid.org/resources/HT017028573?format=json) / [example (test)](http://test.lobid.org/resources/HT017028573?format=json) for ```s.n.```.

The last two shortcuts are also covered.

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
S.l. isn't covered see above [example](http://lobid.org/resources/HT010726584) but also in [new example](http://lobid.org/resources/HT016608165).

**Comment by ChristophEwertowski** [comment]
Removed S.l. (sine locum, without a place). See [example (production)](http://lobid.org/resources/HT016608165) / [example (test)](http://test.lobid.org/resources/HT016608165). Since it was already approved in functional review by @acka47, I'm assigning the pull request to dr0i.
