### ISSUE TITLE
FH Münster (MARC) data missing

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#365]
Today at the introduction of the DigiBib I got to know that the FH Münster uses the WorldShare Management System of OCLC. Because the data is stored in MARC probably it isn't in our data.

**Comment by ChristophEwertowski** [comment]
At the introduction of the Verbundgruppe I got to know that they have a converter from MARC21 to MAB. We could probably use it too.

**Comment by acka47** [comment]
As just discussed during the standup, my understanding is that FH Münster data generated in WMS is not fed into the Aleph catalog but is only transformed from MARC to be indexed in the search engine for Fernleihe and DigiBib. A converter from the Aleph catalogue to MARC exists.

**Comment by fsteeg** [comment]
So we don't have the FH Münster data in lobid-resources, correct?

**Comment by acka47** [comment]
At least the changes/additions they made in WMS since the switch.

**Comment by TobiasNx** [comment]
@acka47 can we close this ticket. It seems that FH Münster is included in lobid:

http://lobid.org/resources/search?owner=http%3A%2F%2Flobid.org%2Forganisations%2FDE-836%23!&aggregations=hasItem.heldBy.id

**Comment by acka47** [comment]
Yes, they also went to Alma. Closing.
