### ISSUE TITLE
Include subfield e of subject heading in transformation to RDF

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#37]
Reported by D.B. via email on 2016-02-26:

> Beispiel: Recherche appeltaatefest https://nwbib.de/search?location=&q=appeltaatefest
> 
> In der Einzelanzeige der Titel wird jeweils nur UF d und UF c aus dem Schlagwortsatz angezeigt, es fehlt immer das UF e "Appeltaatefest". Bei der Schlagwortfolge wird jeweils nur UF c angezeigt.
> 
> Einen ähnlichen Fall finden Sie unter https://nwbib.de/search?location=&q=impulse+theater+festival

**Comment by acka47** [comment]
From the source of example [HT014681992](http://beta.lobid.org/hbz01/HT014681992) (snippet):

```xml
<datafield tag="902" ind1="-" ind2="1">
  <subfield code="e">Appeltaatefest</subfield>
  <subfield code="d">2005</subfield>
  <subfield code="c">Neuss</subfield>
  <subfield code="9">(DE-588)6509781-6</subfield>
</datafield>
```

The expected JSON part looks like this:

```javascript
"subject":[
   {
      "@id":"http://d-nb.info/gnd/6509781-6",
      "preferredName": "Appeltaatefest, 2005, Neuss"
   }
]
```

**Comment by fsteeg** [comment]
Added `bug` label. 

e.g. http://nwbib.de/HT014681992: subject is `2005, Neuss`, should be `Appeltaatefest 2005, Neuss`

**Comment by dr0i** [comment]
Deployed small test set , see e.g. http://lobid.org/resources-staging/HT014681992.
@fsteeg should not http://test.nwbib.de/HT014681992 take the staging index into account?

**Comment by fsteeg** [comment]
nwbib-staging wasn't using the data 2.0 staging index yet, now it is: http://test.nwbib.de/HT014681992

**Comment by acka47** [comment]
Also a +1 for NWBib
