### ISSUE TITLE
Some objects missing in `ComplexSubject`

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#378]
This issue is spawned by #187:

Only one literal appears in the `ComplexSubject` where multiple literal(-objects) are in fact in the data ( field `902` and `907` have two subfields `a`), see e.g. BT000040377 ([source](http://lobid.org/hbz01/BT000040377), [JSON-LD](http://stage.lobid.org/resources/BT000040377?format=json)).

**Comment by acka47** [comment]
I will talk to a subject cataloging colleague tomorrow to learn some more about this divergent practice of subject cataloging.

**Comment by acka47** [comment]
This is what we are talking about, from he [source of BT000040377](http://lobid.org/hbz01/BT000040377): 

```xml
<datafield tag="902" ind1="-" ind2="1">
  <subfield code="a">Rheine</subfield>
  <subfield code="a">Vogelschutz</subfield>
</datafield>
<datafield tag="907" ind1="-" ind2="1">
  <subfield code="a">Vogelschutz</subfield>
  <subfield code="a">Rheine</subfield>
</datafield>
```

I talked to A. Blankenhagen and she made clear that these are kind of subject chains from the print NWBib that weren't converted to RSWK/GND subject chains. To not lose the information they were kept in this – incorrect – way in the data. She made clear that the repetition of subfield `a` won't be corrected in the source data.

Looking at the API 1.0 data, we only have this information in the field `subjectChain`, see http://lobid.org/resource/BT000040377/about. I suggest we proceed as follows: Remove the labels from `subject` altogether and leave them in `subjectChain` for now. We will have to decide what to do in the NWBib display when switching to API 2.0. (One option would be: If there is no `subject` field show information from `subjectChain` if available.)

**Comment by acka47** [comment]
I thought about finding out about the actual number of resources with this problematic cataloging style. This query gives a good result: http://gaia.hbz-nrw.de:9200/resources/_search?q=subjectChain:*+AND+collectedBy.label:Nordrhein+AND+_missing_:subject.componentList.id

Less than 37978 NWBib resources have values in `subjectChain` but no subjects with `id` (=GND subject headings). This is approximately 10% of NWBib, thus not unsignificant.

**Comment by fsteeg** [comment]
For reference, public version of that query: http://lobid.org/resources/search?q=subjectChain:*+AND+collectedBy.label:Nordrhein+AND+_missing_:subject.componentList.id&format=json

**Comment by dr0i** [comment]
For clarification:
the mother ticket #187 says at https://github.com/hbz/lobid-resources/issues/187#issuecomment-284766705 : 

> only use the ComplexSubject approach for RSWK subjects.

while in this ticket it is said:

> weren't converted to RSWK/GND 

But I am gonna treat them all as `ComplexSubject`, despite of what was said.
