### ISSUE TITLE
Add corporateBodyForTitle to title in HTML display

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#383]
~320,000 resources have the field `corporateBodyForTitle`, see [http://lobid.org/resources/search?q=corporateBodyForTitle:*](http://lobid.org/resources/search?q=corporateBodyForTitle:*). For example http://lobid.org/resources/HT016132955.

The information from `corporateBodyForTitle` should somehow be added to the title _display_. Note: no changes in the data needed! 

My suggestion is to concatenate both with delimiter `. ` Thus, in the HTML of the example it would read: "Tagungsband. Dortmunder Forum Technisches Management 2009, 18. und 19. Juni 2009"

What do you think, @ChristophEwertowski ?

**Comment by ChristophEwertowski** [comment]
I agree. A title should be expressive so that an user gets a clue what the resource is about. "Tagungsband" isn't enough for that. Because of that adding the corporateBodyForTitle makes sense.
