### ISSUE TITLE
Add label to SeriesRelation

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#384]
Requested by @hagbeck via email. It would be nice if resources that are published within a series would have the series title somewhere in the data.

Example:  HT010610849 ([JSON](http://lobid.org/resources/HT010610849?format=json), [source](http://lobid.org/hbz01/HT010610849)) The resource is part of http://lobid.org/resources/HT002091695#! (title "Suhrkamp-Taschenbuch Wissenschaft") but the series title is not part of the description. In the source, the title can only be found in field 451 which also contains the volume number:

```xml
<datafield tag="451" ind1="-" ind2="1">
  <subfield code="a">Suhrkamp-Taschenbuch Wissenschaft ; 1415</subfield>
</datafield>
```

The information from 451 basically is a label for the specific `SeriesRelation` so that I suggest to add it accordingly:

```json
{
   "id":"http://lobid.org/resources/HT010610849#!",
   "inSeries":[
      {
         "label":"Suhrkamp-Taschenbuch Wissenschaft ; 1415",
         "numbering":"1415",
         "series":[
            {
               "id":"http://lobid.org/resources/HT002091695#!",
               "label":"lobid Ressource"
            }
         ],
         "type":[
            "SeriesRelation"
         ]
      }
   ]
}
```

**Comment by ChristophEwertowski** [comment]
Will be deployed to the test instance after 382 is reviewed by @acka47 .

**Comment by ChristophEwertowski** [comment]
Deployed to test instance, see http://test.lobid.org/resources/search?q=inSeries.label:* Only the real title is taken into account, without the numbering as we have it already in ```numbering``` and it can be filtered out easily ([example](http://test.lobid.org/resources/HT007849834)).

**Comment by acka47** [comment]
As the current label is for the relation it should also contain the numbering. However, thinking about this it would be better understandable for users to put the information in the label for the series itself. (This would also lead to replacing the "lobid resource" placeholder there.) For the current example this means:

```json
"inSeries" : [ {
    "numbering" : "Bd 7",
    "series" : [ {
      "id" : "http://lobid.org/resources/HT008493154#!",
      "label" : "Sportfischer-Bücherei"
    } ],
    "type" : [ "SeriesRelation" ]
  } ]
```

**Comment by acka47** [comment]
I guess this is assigned to me so that I review this. (Usually, there is a link to a resource or similar to review.) This isn't deployed to test yet. The diffs look good, though.

**Comment by acka47** [comment]
Looking at the diffs a bit mire, I see lots of problems with special characters, e.g. https://github.com/hbz/lobid-resources/pull/430/commits/69bf4fa18bd9b709234b2285a57aa92b5f267215#diff-9bf16ee3396e33cb8bc306e9645e05cc

**Comment by ChristophEwertowski** [comment]
Sorry, forgot to deploy it to test. The problems with special characters originate from wrongly transformed test files. So the wrong characters aren't morphed in the wrong way but the files are flawed. Opened an [issue](https://github.com/hbz/lobid-resources/issues/431) for it.
[Example with numbering](http://test.lobid.org/resources/HT015440386?format=json) / [example without a numbering](http://test.lobid.org/resources/HT015183529?format=json). 

As you can see the labels aren't shown in the frontend yet: Either only the hbz id is shown ([example 1](http://test.lobid.org/resources/HT015440386)/[example 2](http://test.lobid.org/resources/HT015183529)) or [part of the MAB fields 451-491](http://test.lobid.org/resources/HT015183529)). So if you are fine with it, hand it to @fsteeg .

**Comment by acka47** [comment]
+1

I think the labels aren't shown in the front end as most superordinate resources are not part of the test set. (See this resource where the series is part of the test set: http://test.lobid.org/resources/HT008355626) So there's no need for @fsteeg to adjust the frontend. (I am not sure whether we should take the information from `inSeries.series.label` for the display as it might differ from the title we show at the respective resource. See for example http://test.lobid.org/resources/HT007849599: "Mémoires : Coll. in 8-o / Acad. Royale de Belgique. Cl. des sciences : Sér. 2" vs. "Mémoire de la Classe des Sciences / Collection in-8 ̊".)

**Comment by ChristophEwertowski** [comment]
Ah, I see. 
By the way: We should stick to showing the title of the superordinate resource from it's file. In the example case there isn't just the title of the series it's in but also numbering and editing institution.
