### ISSUE TITLE
Remove dct:source, rename key for dct:isFormatOf

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#388]
As discussed with @ChristophEwertowski offline today we will proceed as mentioned in https://github.com/hbz/lobid-resources/issues/265#issuecomment-293499700:

> As `dct:source` is used in exactly the same way as `isFormatOf` (see the [current morph, lines 220-227](https://github.com/hbz/lobid-resources/blob/a403180f75e9e9fc07d13f6046de775a0560a8b7/src/main/resources/morph-hbz01-to-lobid.xml#L220-L227)), I propose to discard `dct:source` altogether.
>
> `021` carries the "IDENTIFIKATIONSNUMMER DER PRIMAERFORM". `isFormatOf` – for two reasons – seems to be the better choice anyway. (As we call the publication information for the secondary form `SecondaryPublicationEvent`, we might think about changing the JSON key of `isFormatOf` to `primaryForm` or so.)

**Comment by ChristophEwertowski** [comment]
Done. The JSON key ```primaryForm``` is more expressive so I changed it for ```isFormatOf``` like you suggested. See [example (production)](http://lobid.org/resources/CT003012479?format=json) / [example (test)](http://test.lobid.org/resources/CT003012479?format=json)

**Comment by acka47** [comment]
+1
