### ISSUE TITLE
Weird "In: von" field

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#392]
Weird "In: von" field: http://lobid.org/resources/BT000103077

**Comment by acka47** [comment]
This is a cataloging error. The entry in `599` in the source data is incorrect. 

```xml
<datafield tag="599" ind1="-" ind2="1">
   <subfield code="a">von Jürgen Reulecke</subfield>
</datafield>
```

It should contain a hbz ID (like for example [HT000801438](http://lobid.org/resources/HT000801438)) but contains a name string. Assigning @ablankenhagen. ;-)

**Comment by dr0i** [comment]
+1 for assigning @ablankenhagen

**Comment by ChristophEwertowski** [comment]
Changed the resource in Aleph.

**Comment by ChristophEwertowski** [comment]
@fsteeg : "In: von" is removed from frontend and JSON. Because it's a minor bug and you are not available I'm closing this issue without your approval.
