### ISSUE TITLE
Subject facet missing

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#393]
http://lobid.org/resources/search

**Comment by fsteeg** [comment]
@dr0i: As a prerequisite to updating the subject facet for the new subject structure, the `subject.componentList.id` field needs to be set to not_analyzed (like `subject.id`).

@acka47: I've hit this issue when updating the API docs too. With the new structure we always have to check two fields (resp. 4, if we include labels) when doing subject queries (`subject.id|label` and `subject.componentList.id|label`). That may be a price we're willing to pay for modeling complex subjects, I just wanted to mention it.

**Comment by acka47** [comment]
Re. subject queries: I am aware of the multiple fields to query. There also is the – probably most important – field `subjectAltLabel`.

**Comment by acka47** [comment]
For the subject facet, we should only query `subject.componentList.label`, though, as this is the field that is used most over the whole dataset.

**Comment by ChristophEwertowski** [comment]
@dr0i : Also the componentList gets lost if one generates the files new. And other changes aren't in the master files (the changed context, output and reverseTest files).

**Comment by dr0i** [comment]
re. "componentList gets lost": @ChristophEwertowski I couldn't reproduce your observation. Rebuilding the master anew after removing all output test files shows the creation of `componentList` just fine. Doing this I discovered that some test files reside in the directory *although* they *don't exist in the hbz01XmlClobs.tar.bz2 archive*. These should be in sync. Filed #402. Maybe you looked in some of these files containing old data (i.e. without `componentList`)?

**Comment by fsteeg** [comment]
@dr0i Opened pull request #403 with field update for facet, and deployed to test:

http://test.lobid.org/resources/search?q=k%C3%B6ln

When the `not_analyzed` setup is deployed to the test index, this should work.

**Comment by ChristophEwertowski** [comment]
@dr0i : Yes, it is true that all these changed files aren't in the XmlClobs but in the json/output folder files.

**Comment by fsteeg** [comment]
Deployed to test: http://test.lobid.org/resources/search

**Comment by ChristophEwertowski** [comment]
+1

**Comment by acka47** [comment]
+1
