### ISSUE TITLE
ToC link also added to seeAlso

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#394]
See the example book from the API documentation at http://stage.lobid.org/resources/api#buch or http://lobid.org/resources/HT019025795#! JSON:

```json
{
   "id":"http://lobid.org/resources/HT019025795#!",
   "seeAlso":[
      {
         "id":"http://digitool.hbz-nrw.de:1801/webclient/DeliveryManager?pid=7132111&custom_att_2=simple_viewer",
         "label":"Digitool"
      },
      {
         "id":"http://digitool.hbz-nrw.de:1801/webclient/DeliveryManager?pid=7132112&custom_att_2=simple_viewer",
         "label":"Digitool"
      }
   ],
   "tableOfContents":[
      {
         "id":"http://digitool.hbz-nrw.de:1801/webclient/DeliveryManager?pid=7132111&custom_att_2=simple_viewer",
         "label":"Digitool"
      }
   ]
}
```

`http://digitool.hbz-nrw.de:1801/webclient/DeliveryManager?pid=7132111&custom_att_2=simple_viewer` is content both of `seeAlso` and `tableOfContents`. The morph obviously tries to limit it to `tableOfContents` (see [lines 1802-1828 of current moprh](https://github.com/hbz/lobid-resources/blob/477c6c8b147006cf826065b705dd40210b306727/src/main/resources/morph-hbz01-to-lobid.xml#L1802-L1828))  but this obviously doesn't work as expected.

**Comment by ChristophEwertowski** [comment]
The problem is the first paragraph: 
```
<combine name="http://www.w3.org/2000/01/rdf-schema#seeAlso" value="${seeAlsoUri}">
	<data source="655[-eu][ -1].[x3]">
		<regexp match="^[Z][u][s]"/>
	</data>
	<data source="@linkUri" name="seeAlsoUri"/>
</combine>
```
If anywhere in the resource file the regex matches, add linkUri -> effectively MAB 655[-e][ -1].u. Since this field appears also for tableOfContents and other links, a wrong uri is taken. Thinking about it tomorrow.

**Comment by ChristophEwertowski** [comment]
Found no way for tackling this problem. Is there a way for counting within the morph, @dr0i ?

**Comment by ChristophEwertowski** [comment]
It was easier than I thought. @fsteeg pointed out to me that it could be simple as setting the setting for sameEntities. And this lead to success. Thanks!
[Example (production)](http://lobid.org/resources/HT016382441?format=json) / [example (test)](http://test.lobid.org/resources/HT016382441?format=json)

**Comment by acka47** [comment]
+1
