### ISSUE TITLE
Fetch OPAC URL templates from source file

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#397]
Currently, we replicate the file https://github.com/hbz/link-templates/blob/master/isil2opac_hbzid.json both in this repo and in the NWBib repo. As this file needs to be updated quite often, this is impractical. In the future, OPAC URL templates should directly be fetched from GitHub at https://raw.githubusercontent.com/hbz/link-templates/master/isil2opac_hbzid.json.

**Comment by dr0i** [comment]
With #1893 we use gitsubmodules so lookup table is updated automatically.
Closing.
