### ISSUE TITLE
Differ between contributing persons and corporate bodies

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#40]
Mimicking the distinction between the 1-- and the 2-- fields in MAB, we decided to differ between personal  and corporate body contributors in the JSON. This will enable easy implementation of  person search vs. Körperschaftssuche e.g. in NWBib.

Adjusting the example from https://github.com/hbz/lobid-resources/issues/4#issuecomment-189275621, the result will look like this:

```json
{
   "@context":{
      "id":"@id",
      "type":"@type",
      "subject":{
         "@id":"http://purl.org/dc/terms/subject",
         "@type":"@id",
         "@container":"@list"
      },
      "contributor":{
         "@type":"@id",
         "@id":"http://purl.org/dc/terms/contributor",
         "@container":"@list"
      },
      "corporateBody":{
         "@type":"@id",
         "@id":"http://purl.org/lobid/lv#corporateBody",
         "@container":"@list"
      },
      "label":"http://www.w3.org/2000/01/rdf-schema#label",
      "altLabel":"http://www.w3.org/2004/02/skos/core#altLabel",
      "BibliographicResource":"http://purl.org/dc/terms/BibliographicResource",
      "Book":"http://purl.org/ontology/bibo/Book",
      "CorporateBody":"http://d-nb.info/standards/elementset/gnd#CorporateBody",
      "DifferentiatedPerson":"http://d-nb.info/standards/elementset/gnd#DifferentiatedPerson"
   },
   "@id":"http://lobid.org/resources/HT018454638#!",
   "contributor":[
      {
         "id":"http://d-nb.info/gnd/172845785",
         "type":"DifferentiatedPerson",
         "label":"Clemens-Schierbaum, Ursula",
         "altLabel":[
            "Clemens, Ursula",
            "Schierbaum, Ursula C.-",
            "Schierbaum, Ursula Clemens-"
         ]
      }
   ],
   "corporateBody":[
      {
         "@id":"http://d-nb.info/gnd/1060772442",
         "type":"CorporateBody",
         "label":"Pfarrei St. Joseph und St. Antonius Bergisch Gladbach",
         "altLabel":[
            "Katholische Kirchengemeinde St. Joseph und St. Antonius Bergisch Gladbach",
            "Pfarrei Sankt Joseph und Sankt Antonius Bergisch Gladbach"
         ]
      },
      {
         "@id":"http://d-nb.info/gnd/2175350-7",
         "type":"CorporateBody",
         "label":"Pfarrei Sankt Antonius Abbas Herkenrath",
         "altLabel":[
            "Pfarrei St. Antonius Abbas Herkenrath",
            "Pfarrei Sankt Antonius Abbas Bergisch Gladbach- Herkenrath",
            "Pfarrgemeinderat Sankt Antonius Abbas Herkenrath",
            "Katholische Kirchengemeinde Sankt Joseph und Sankt Antonius Bergisch Gladbach",
            "Pfarrei Sankt Antonius Abbas Herkenrath. Pfarrgemeinderat",
            "Pfarrgemeinderat. Pfarrei Sankt Antonius Abbas Herkenrath"
         ]
      }
   ],
   "type":[
      "BibliographicResource",
      "Book"
   ]
}
```

**Comment by jschnasse** [comment]
LOL

**Comment by acka47** [comment]
Keep in mind: There only exist two roles for corporate bodies: "creator" (Geistiger Schöpfer") and other not specified roles (where no role information should be given).

**Comment by acka47** [comment]
By now, I don't think that this distinction makes sense with regard to the fact that we now have RDA as cataloging rules. In RAK WB we had the distinction between "Verfasser" and "Urheber":

>§ 16 Als Verfasser werden die Personen bezeichnet, die - allein oder gemeinschaftlich - ein
Werk oder Teile eines Werkes erarbeitet haben, auch wenn sie in dem Werk und seinen
Ausgaben nicht oder nicht ausdrücklich als Verfasser genannt sind.

> § 18 Als Urheber werden die Korperschaften bezeichnet, die - allein oder gemeinschaftlich -
ein anonymes Werk oder Teile eines solchen Werkes erarbeitet oder veranlaßt _und_ herausgegeben
haben.

In RDA you don't have this distinction but both corporate bodies and persons can be [creators](http://access.rdatoolkit.org/rdachp19_rda19-394.html) or ["Other Persons, Families, and Corporate Bodies Associated with a Work"](http://access.rdatoolkit.org/rdachp19_rda19-2460.html). Thus, we should also differ as planned between these two but use `contributor` as simpler term (though not 100% accurate) for "Other Persons, Families, and Corporate Bodies Associated with a Work". Thus, whether something is a corporate body will only be clear through the `type` and we won't be able to use simple `q` queries for corporate body search.

**Comment by acka47** [comment]
Closing.
