### ISSUE TITLE
Different data in Verbundkatalog and lobid hbz01

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#406]
While working on a ticket for Mr. Dirx from the LBZ RLP I became aware of different data in a resource. http://lobid.org/hbz01/HT015660188 has 902 and 907 subject chains. The same resource in the Verbundkatalog only has the first five 902 fields (Langsur, Topografie, Geschichte 1843-1998, Karte, CD-ROM) under "Feldnummern". How is this possible? The resource wasn't changed since 2008.

**Comment by acka47** [comment]
The 907 fields and some 902er are added during the export from Aleph from the superordinated resource HT014159452 ([source](http://lobid.org/hbz01/HT014159452)). You can see this from `ind2="2"` in http://lobid.org/hbz01/HT015660188 (snippet):

```xml
<datafield tag="902" ind1="-" ind2="1">
  <subfield code="s">Topografie</subfield>
  <subfield code="9">(DE-588)4133697-5</subfield>
</datafield>
<datafield tag="902" ind1="-" ind2="1">
  <subfield code="z">Geschichte 1843-1998</subfield>
</datafield>
<datafield tag="902" ind1="-" ind2="1">
  <subfield code="f">Karte</subfield>
</datafield>
<datafield tag="902" ind1="-" ind2="1">
  <subfield code="f">CD-ROM</subfield>
</datafield>
<datafield tag="902" ind1="-" ind2="2">
  <subfield code="g">Rheinland-Pfalz</subfield>
  <subfield code="9">(DE-588)4049795-1</subfield>
</datafield>
<datafield tag="902" ind1="-" ind2="2">
  <subfield code="s">Topografie</subfield>
  <subfield code="9">(DE-588)4133697-5</subfield>
</datafield>
<datafield tag="902" ind1="-" ind2="2">
  <subfield code="z">Geschichte 1800-2008</subfield>
</datafield>
<datafield tag="902" ind1="-" ind2="2">
<subfield code="f">Karte</subfield>
</datafield>
<datafield tag="902" ind1="-" ind2="2">
<subfield code="f">CD-ROM</subfield>
</datafield>
<datafield tag="907" ind1="-" ind2="2">
  <subfield code="g">Rheinland</subfield>
  <subfield code="9">(DE-588)4049788-4</subfield>
</datafield>
<datafield tag="907" ind1="-" ind2="2">
  <subfield code="s">Topografie</subfield>
  <subfield code="9">(DE-588)4133697-5</subfield>
</datafield>
<datafield tag="907" ind1="-" ind2="2">
  <subfield code="z">Geschichte 1800-2008</subfield>
</datafield>
<datafield tag="907" ind1="-" ind2="2">
  <subfield code="f">Karte</subfield>
</datafield>
<datafield tag="907" ind1="-" ind2="2">
  <subfield code="f">CD-ROM</subfield>
</datafield>
```

We have been taken this kind of enrichment from the super-ordinated resource into account for a long time now. Do you see a problem with this? If not, please close the issue.

**Comment by ChristophEwertowski** [comment]
At the moment I don't see a problem with it. If the lobid 2.0 is used for edoweb it could become a problem because all subjects from a datafield tag number are put together in a componentList regardless if they are from, for example, MAB 902 of the resource or the superordinated resource. But this issue can be reopened, if needed. Until then I'm closing this issue.
