### ISSUE TITLE
Superordinate resource doesn't appear in subordinate resource

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#408]
http://lobid.org/resources/HT015090208 has a title for the superordinate resource (MAB field 451) which isn't included in ```isPartOf``` or ```inSeries```. No id exists for the superordinate resource (would be in 453).

**Comment by fsteeg** [comment]
This is actually a UI issue (see http://lobid.org/resources/HT015090208.json) covered by #837, closing.
