### ISSUE TITLE
Resource in lobid-resources isn't viewable

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#409]
Resource: http://lobid.org/resources/HT015183529
Example error id: 73nipmc5l

**Comment by fsteeg** [comment]
Deployed to stage: http://stage.lobid.org/resources/HT015183529

Was caused by an unhandled missing `numbering` in the `series` field.

**Comment by ChristophEwertowski** [comment]
Looked in the morph. For ```inVolume``` numbering is found in MAB ```090``` and ```089```. For ```inSeries```, which here is the case, numbering should be found in ```451``` but only the title can be found in the field of the example resource. So the numbering remains empty and the entity isn't complete.

**Comment by ChristophEwertowski** [comment]
Searched for multiVolumeWorks which don't have a numbering and found none ([query](http://lobid.org/resources/search?q=_missing_:volumeIn.numbering+AND+volumeIn.multiVolumeWork.id:*)). Closing this issue.

**Comment by fsteeg** [comment]
Reopening since this is not deployed to production yet.
