### ISSUE TITLE
Trigger daily updates earlier

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#411]
@hagbeck asks if we could provide the daily updates at an earlier point in time.
Should be save to do. Just needs reconfig of crontab.

**Comment by dr0i** [comment]
The complete data update workflow starts now 3 hours earlier then before. Thus the API 2.0 index will be updated beginning 04:00 am and will be finished at a max of 04:30 am.
Ticket to be reviewed.

**Comment by dr0i** [comment]
Data was ETLed ok. 
@hagbeck are you fine with the data updated at 04:30 am?

**Comment by hagbeck** [comment]
That's fine. Thanks!
