### ISSUE TITLE
Put ZDB-links from isPartOf into inSeries/containedIn

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#412]
As the ZDB contains journals and series the links can be put into ```containedIn``` or ```inSeries```, depending on whether it is an article or part of a series (e.g. monography or multiVolumeWork). Then ```isPartOf``` should be obsolete.
Update: Of course articles don't contain zdb-links. Journals aren't contained in other journals. Only multiVolumeWorks remain.

**Comment by ChristophEwertowski** [comment]
To add multiVolumeWorks to ```inSeries``` is not that difficult. But I found out that the multiVolumeWorks are books *and* journals so we can't put all zdbIds into ```inSeries``` since I found some volumes of journals in the test resources. We don't have a property for linking volumes of journals to the journal itself.
Definitions of series and periodicals for further reference from standard work ("Hacker" a.k.a. "Bibliothekarisches Grundwissen"; 2. ed.; Verlag Dokumentation Saur: Pullach, 1973):

> Als Series oder Reihe [...] bezeichnet man eine unbegrenzte Folge von in unregelmäßigen Abständen erscheinenden Bänden oder Heften, wobei die einzelnen <<Stücke>> jeweils in sich absgeschlossen sind, eigene <<Stücktitel>> haben und in der Regel von verschiedenen Verfassern stammen, jedoch durch einen gemeinsamen übergeordneten Serientitel zusammengehalten werden.

> Sie [Serien bzw. Zeitschriften und Zeitungen] unterscheiden sich aber dadurch, daß die Stücke einer Serie in unregelmäßigen Abständen publiziert werden, während Zeitschriften und Zeitungen im allgemeinen in regelmäßigen Abständen, also periodisch, erscheinen. [...] Gewisse Übergangsformen zwischen Zeitschrift und Serie bezeichnet man als zeitschriftenartige Reihen. Dazu gehören in regelmäßigen Abständen publizierte Serienbände mit Jahrgangszählung [...], aber auch Serien ohne periodische Erscheinungsweise, die in einem Stück mehrere Aufsätze nach Art von Zeitschriftenaufsätzen bringen. 

I would put "Zeitschriftenartige Reihen" into series.

**Comment by ChristophEwertowski** [comment]
I put zdb-links with an ISBN ([example](http://test.lobid.org/resources/HT004944075)) or a frequency of one year and above ([example](http://test.lobid.org/resources/HT016604323)) into ```inSeries```. The same where a resource has a zdb-id exists and is not a journal or newspaper ([example](http://test.lobid.org/resources/HT003654516)). But still there are some resources with zdb-links in ```isPartOf```, e.g. issues of journals (see #418). They don't have a frequency.

My hope was that ```isPartOf``` would be obsolete with this issue but there are other cases, see #418, #419 and #420.

**Comment by ChristophEwertowski** [comment]
Switched the test index which lead to errors at the changed resources, see for example [HT004944075 ](http://test.lobid.org/resources/HT004944075). fsteeg told me that the frontend uses ```isPartOf``` which is probably the reason for the errors. Assigning it to fsteeg.

**Comment by fsteeg** [comment]
The error was actually caused by a different issue that was fixed in master in the meantime, but not deployed to test, it now looks good:

http://test.lobid.org/resources/HT004944075

**Comment by acka47** [comment]
Something went wrong here. As far as I can see all the added information is incorrect or redundant.

- [HT004944075](http://test.lobid.org/resources/HT004944075) links to the same resource twice – once with `volumeIn` using the hbz URI of the resource and with `inSeries` using the ZDB URI of the same resource. To make this clear, I add the sameAs link for the hbz entity to the data:

~~~json
{
   "id":"http://lobid.org/resources/HT004944075#!",
   "inSeries":[
      {
         "series":[
            {
               "id":"http://ld.zdb-services.de/resource/1257-9",
               "label":"http://ld.zdb-services.de/resource"
            }
         ],
         "type":[
            "SeriesRelation"
         ]
      }
   ],
   "volumeIn":[
      {
         "multiVolumeWork":[
            {
               "id":"http://lobid.org/resources/HT002619538#!",
               "label":"lobid Ressource",
               "sameAs":[
                  {
                     "id":"http://ld.zdb-services.de/resource/1257-9",
                     "label":"http://ld.zdb-services.de/resource"
                  }
               ],
               "numbering":"43",
               "type":[
                  "MultiVolumeWorkRelation"
               ]
            }
         ]
      }
   ]
}
~~~
- Same for [HT003654516](http://test.lobid.org/resources/HT003654516?format=json)
- [HT016604323](http://test.lobid.org/resources/HT016604323) is part of itself:
~~~json
{
   "id":"http://lobid.org/resources/HT016604323#!",
   "inSeries":[
      {
         "series":[
            {
               "id":"http://ld.zdb-services.de/resource/2581964-1",
               "label":"http://ld.zdb-services.de/resource"
            }
         ],
         "type":[
            "SeriesRelation"
         ]
      }
   ],
   "sameAs":[
      {
         "id":"http://hub.culturegraph.org/resource/HBZ-HT016604323",
         "label":"Culturegraph Ressource"
      },
      {
         "id":"http://ld.zdb-services.de/resource/2581964-1",
         "label":"http://ld.zdb-services.de/resource"
      }
   ],
   "zdbId":"2581964-1"
}
~~~

**Comment by ChristophEwertowski** [comment]
I replaced the information, so it was there before.
[HT003654516 (series, e.g. "zeitschriftenähnliche Reihe")](http://test.lobid.org/resources/HT003654516?format=json), [HT004944075 (the same)](http://test.lobid.org/resources/HT004944075?format=json), [HT012996101 (journal)](http://test.lobid.org/resources/HT012996101?format=json), [HT015082724 (the same)](http://test.lobid.org/resources/HT015082724?format=json), [TT001966831 (newspaper)](http://test.lobid.org/resources/TT001966831?format=json): ```inSeries``` and ```volumeIn.multiVolumeWork``` are different information. It could be ```volumeIn.series``` or ```volumeIn.periodical```.
[HT016604323](http://test.lobid.org/resources/HT016604323?format=json), [HT018147158](http://test.lobid.org/resources/HT018147158): Integrated wrong indicator.

**Comment by ChristophEwertowski** [comment]
The information which was transferred from ```isPartOf``` to ```inSeries``` was derived from other fields than MAB 052. As we discussed we concentrate on MAB 052 level 0. If it is not cataloged there we won't enrich the data. Closing this issue.
