### ISSUE TITLE
Move links of articles to a more speaking property 

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#418]
Links of articles to superordinated resources are stated in ```isPartOf```. Since it's no expressive property it would be nice to transfer them to a newly property like ```isArticleIn``` or even better ```inPeriodical``` / ```inCollectiveEdition```. The last two properties would be only possible by looking into the superordinated resource which dr0i wants to work on later this year. What do you think, @acka47 ?
([Example journal article](http://lobid.org/resources/BT000041593)) / ([example collective editions](http://lobid.org/resources/HT018726005))
The second approach could put issues of journals away from ```isPartOf``` ([example](http://lobid.org/resources/HT005944358)).

**Comment by acka47** [comment]
This is what we use `lv:containedIn` for. From the vocab:

~~~
lv:containedIn
   rdf:type owl:ObjectProperty ;
   rdfs:label "Contained in"@en ; 
   rdfs:label "Enthalten in"@de ;
   rdfs:isDefinedBy <http://purl.org/lobid/lv> ;
   rdfs:comment "This property is used to link an article to a journal or an edited volume it is contained in."@en ;
   rdfs:comment "Diese Property verlinkt einen Artikel mit einer Zeitschrift oder einer Aufsatzsammlung, in der er enthalten ist."@de;
   rdfs:subPropertyOf dct:isPartOf;
   rdfs:domain bibo:Article ;
   rdfs:range dct:BibliographicResource .
~~~

**Comment by ChristophEwertowski** [comment]
We discussed today that putting information of superordinated resources under one property would be better, see #427. What publication type the higher level resource is has to be looked up there and will not be transported in the name of a property. 
But like one can see in the examples from above ([example journal article](http://lobid.org/resources/BT000041593) and [example article from collective editions](http://lobid.org/resources/HT018726005)) the links to the superordinated resources are contained in ```isPartOf``` and ```containedIn```. Therefore renaming this ticket.
