### ISSUE TITLE
Getting updates of tab_sigel

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#422]
The hbz-aleph-dumping uses a file `tab_sigel` for mapping aleph internal sigel/isil IDs to official ISILs, as @jprante noted in an email. This file will from now on be outdated as it is no more updated - it resides in emphytos.hbz-nrw.de/alephxml/tab_sigel .
So the task is to ask the verbundgruppe to supply the updates of tab_sigel.

**Comment by dr0i** [comment]
Meanwhile I scheduled a weekly download of `tab_sigel` from `index.hbz-nrw.de/alephxml/tab_sigel` on emphytos. The file is loaded with `curl -fail` which will fail silently if the server returns an erro. The `tab_sigel` is overwritten, some manually copied backups reside in the directory.

**Comment by dr0i** [comment]
There is no weekly download (anymore). Wouldn't make sense anyway, since the timestamp of the file at the `index`-server dates to end august 2017.

**Comment by ChristophEwertowski** [comment]
I asked a collegue which said that Mrs. B. or Mrs. S. are likely to create this updates. Both are occupied in a meeting today. Because it is not logical to ask again and again who started a process when we have forgotten it, I made a wiki page where we can insert people who give data to us: https://wiki.hbz-nrw.de/pages/viewpage.action?pageId=766935114. 
@dr0i : Please look in your mails who created the process of giving tab_sigel files.

**Comment by dr0i** [comment]
@ChristophEwertowski you got this mail also: Subject "Fwd: Antw: AlephXmlClobs Abzugs Problem: permission denied tab_sigel" from "5/11/17, 1:42 PM"

**Comment by ChristophEwertowski** [comment]
I already sent you the mail with the current tab_sigel file. Please talk to B.S. for updates as he wants to know where the file can be put and how often this should be.

**Comment by dr0i** [comment]
B.S. provides a daily updated tab_sigel at 1:11 PM. Updated the `daily-hbz-aleph.sh`:

> cp /home/mab/tab_sigel org/xbib/analyzer/mab/DE-605/tab_sigel
jar uvf  hbz-toolbox-index-1.27_onlyTar-standalone.jar org/xbib/analyzer/mab/DE-605/tab_sigel

Comitted this in the internal git repo.

**Comment by dr0i** [comment]
To be on the save side, I think the tab_sigel is indeed not loaded via filesystem but using a http-lookup. I remember to have changed the location to our server which. The tab_sigel now will be also copied to this seerver's location - see crontab. Added also this thoughts to the above mentioned script. This should be save.

**Comment by dr0i** [comment]
Note: `mab@weywot1:~$ ls -lc tab_sigel` to check if the file, scp'ed by verbundgruppe, was really transferred even when the file's creation is month old.
