### ISSUE TITLE
Give sign for publication period

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#423]
It would be nice to indicate publication year spans for series and periodicals. If there is only a ```startDate``` or only a ```endDate``` it should be shown like ```YYYY - ``` ([example](http://lobid.org/resources/HT013878511)) or ```- YYYY``` ([example](http://lobid.org/resources/HT012712077)), respectively.

**Comment by fsteeg** [comment]
Will handle in #318, closing.
