### ISSUE TITLE
Add hyphen to date in HTML presentation of current periodicals & series

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#425]
The example periodical http://lobid.org/resources/HT016604323 has start date "2005" and no end date. In the HTML it looks as if it would have been published once in 2005.

![example-periodical](https://cloud.githubusercontent.com/assets/160292/25900454/d592e578-3593-11e7-967e-2e28bf3be7e9.png)

Same for series. 

This means for the implementation: If something is of type "Periodical" or "Series" and doesn't have an `endDate` field, a hyphen should nonetheless be added after the date.

**Comment by ChristophEwertowski** [comment]
Same as #423

**Comment by acka47** [comment]
Duplicate. Closing.
