### ISSUE TITLE
Use one property for relations to superordinated resources 

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#427]
As discussed today ```volumeIn.multiVolume``` contains similar information like ```inSeries``` (numbering, the id of the superordinated resource and a relation type). So they should be put together. 
[Example for volumeIn and inSeries](http://lobid.org/resources/HT002888677?format=json):

```
"volumeIn" : [ {
    "multiVolumeWork" : [ {
      "id" : "http://lobid.org/resources/HT002888668#!",
      "label" : "lobid Ressource"
    } ],
    "numbering" : "2",
    "type" : [ "MultiVolumeWorkRelation" ]
  } ]
```
and 
```
"inSeries" : [ {
    "numbering" : "73",
    "series" : [ {
      "id" : "http://lobid.org/resources/HT001236717#!",
      "label" : "lobid Ressource"
    } ],
    "type" : [ "SeriesRelation" ]
  } ],
```
should be something like:
```
"isPartOf" : [ {
    "numbering" : "2",
    "type" : "isPartOfRelation",
    "superordinated" : {
      "id" : "http://lobid.org/resources/HT002888668#!",
      "label" : "lobid Ressource"
    }
}, {
    "numbering" : "73",
    "type" : "isPartOfRelation",
    "superordinated" : {
      "id" : "http://lobid.org/resources/HT001236717#!",
      "label" : "lobid Ressource"
    }
} ]
```
If someone can think of a better term than ```isPartOf``` then we take that. Also there are cases where a journal volume is part of a periodical which at the moment can't be covered ([example](http://lobid.org/resources/HT015296862)).
There are also resources which don't have an id for their superordinated resource, see [example](http://lobid.org/resources/HT015894164?format=json).

**Comment by fsteeg** [comment]
If we have that `type` field, we might want to use different types here to get the convenience of having that information without accessing the superordination, to display different labels, as we currently do, i.e. something like:

```
"isPartOf" : [ {
    "numbering" : "2",
    "type" : "inMultiVolumeWork",
    "superordinated" : {
      "id" : "http://lobid.org/resources/HT002888668#!",
      "label" : "lobid Ressource"
    }
}, {
    "numbering" : "73",
    "type" : "inSeries",
    "superordinated" : {
      "id" : "http://lobid.org/resources/HT001236717#!",
      "label" : "lobid Ressource"
    }
} ]

```

**Comment by acka47** [comment]
See also my comments (in German) in the KIM Wiki:https://wiki.dnb.de/pages/viewpage.action?pageId=125410060&focusedCommentId=125416192#comment-125416192 f

**Comment by acka47** [comment]
I am not sure whether we should keep the different typing. I found several cataloging errors where we would have better results when looking at the actual type of the superordinate resource.

**Comment by ChristophEwertowski** [comment]
I'm mostly with @acka47. If we found multiple errors just by browsing we shouldn't keep the current definitions of `multiVolumeWorks` and `inSeries` in our data. My proposal: Start with giving everything an ```isPartOfRelation```-type and if we can access the publication type of the superordinate resource swap them with `inSeries` or `inMultiVolumeWork`. First correct data then enrichment.

**Comment by ChristophEwertowski** [comment]
Deployed to test.
* [Example with (former) `volumeIn`, `isPartOf` and added zdb-label (production)](http://lobid.org/resources/TT001966831?format=json) / [the same resource on test](http://test.lobid.org/resources/TT001966831?format=json).
* [Example with (former) `inSeries` (production)](http://lobid.org/resources/HT019011249?format=json) / [the same on test](http://test.lobid.org/resources/HT019011249?format=json).

If everything is correct, assign it to fsteeg because front-end changes are necessary.

**Comment by acka47** [comment]
This looks already really good. We need to do two minor adjustments before working on the UI adjustments. Basically, we will implement this as shown in the [DINI KIM wiki](https://wiki.dnb.de/pages/viewpage.action?pageId=125410060&focusedCommentId=125416193#comment-125416193)

1. use `lv:isPartOf` instead of DC Terms
2. name the property `lv:superordinate` instead of `lv:superordinated`

**Comment by acka47** [comment]
@hagbeck these changes will be relevant for your mapping. Take a look at the German explanation at https://wiki.dnb.de/pages/viewpage.action?pageId=125410060&focusedCommentId=125416192#comment-125416192 to find out what will change.

**Comment by ChristophEwertowski** [comment]
Corrected the property name and deleted superflous properties, see [diff of the context-labels.json file](https://github.com/hbz/lobid-resources/pull/433/files#diff-1645de37c03451cf051ab14b99ee7d6b). Because there aren't much changes to see in the front-end I won't update the test index. 
Depends on https://github.com/hbz/lobid-vocabs/issues/65 and after that Fabians changes.

**Comment by acka47** [comment]
Looks good. +1

**Comment by acka47** [comment]
Now the frontend can be adjusted.

**Comment by ChristophEwertowski** [comment]
We just had the *Geistesblitz* to just call it `volumeIn` instead of `isPartOf`. In a series only volumes exist and a part of a multiVolumeWork is also a volume.

**Comment by fsteeg** [comment]
Deployed to test, these work:

http://test.lobid.org/resources/TT001966831 (subordinate)
http://test.lobid.org/resources/HT006987933 (superordinate)

http://test.lobid.org/resources/HT019011249 (subordinate)
http://test.lobid.org/resources/HT018839495 (superordinate)

Issues (some might be unrelated, collecting here for now):

http://test.lobid.org/resources/HT013304490
(missing subordinate TT002777190, s. http://lobid.org/resources/HT013304490)

http://test.lobid.org/resources/HT008359564
(missing subordinate HT008880969, s. http://lobid.org/resources/HT008359564)

http://test.lobid.org/resources/HT012989088
(missing ISSN, s. http://lobid.org/resources/HT012989088)

Keeping self-assigned for now, will investigate further.

We should test this with a sample that contains multiple types of superordinate resources, like http://lobid.org/resources/HT009821451. See also the issue that led to the different properties in the first place: https://github.com/hbz/nwbib/issues/126.

**Comment by fsteeg** [comment]
I think we will need some way to distinguish the different types of subordination *in the subordination*.

Consider this case with three kinds of subordination:

http://lobid.org/resources/HT009821451

This currently looks like this with the new data:

http://test.lobid.org/resources/HT009821451

Ignore the numbers, that's just due to the test set. The problem is that the 1 *Band* and the 1 *Serienband* can't be distinguished, both are listed under *2 Bände*. Because the way this works is that to show the information in the superordinate resource, we issue queries for subordinate resources linking to this superordinate resource with the different fields (`inSeries`/`volumeIn`). The superordinate resource is the same in both cases, so that does not help. These are the two subordinate resources:

http://lobid.org/resources/HT015217050?format=json
http://lobid.org/resources/HT018596489?format=json

And on test:

http://test.lobid.org/resources/HT015217050?format=json
http://test.lobid.org/resources/HT018596489?format=json

Having a type in the subordinate would also help with displaying the correct superordinate, see:

http://test.lobid.org/resources/HT018596489

Which should be:

http://lobid.org/resources/HT018596489

So as sketched in https://github.com/hbz/lobid-resources/issues/427#issuecomment-300789799, I think we need something like this.

For http://test.lobid.org/resources/HT015217050?format=json:

```
"isPartOf": [
    {
        "numbering": "Sonderh.",
        "superordinate": [
            {
                "id": "http://lobid.org/resources/HT009821451#!",
                "label": "lobid Ressource"
            }
        ],
        "type": "inSeries"
    }
]
```

For http://test.lobid.org/resources/HT018596489?format=json:

```
"isPartOf": [
    {
        "numbering": "2014/15",
        "superordinate": [
            {
                "id": "http://lobid.org/resources/HT009821451#!",
                "label": "lobid Ressource"
            }
        ],
        "type": "volumeIn"
    }
]
```

And is it on purpose that we still have a separate `containedIn` property here?

http://test.lobid.org/resources/HT018998123?format=json

Should that not be:

```
"isPartOf": [
    {
        "superordinate": [
            {
                "id": "http://lobid.org/resources/HT009821451#!",
                "label": "lobid Ressource"
            }
        ],
        "type": "containedIn"
    }
]
```

I've used the original properties `containedIn`, `volumeIn`, `inSeries` as types here, but I think they should all follow the same direction, i.e. all `xIn` or all `inX`. Also all samples use `isPartOf` as the top level property, which is still discussed in https://github.com/hbz/lobid-vocabs/issues/65.

**Comment by ChristophEwertowski** [comment]
The main point for not integrating the types of the relation was the impression that there were too many wrongly associated resources. Let's get an roughly empirical basis for this impression:

property (hits) | definitely wrongly associated | sum
------- | ---- | ---
containedIn (587483) | conference works (5361), periodicals (1004), multiVolumeBooks (667), thesis (659), bibliographies (414), article collection (230), series (17), reference work (6), game (1), law (1) | 8360 / 1,4%
inSeries.series (3521788) | articles (6713), periodicals (64), (books with a numbering in title and the keyword journal -> mostly journals ([query 1](http://lobid.org/resources/search?q=title%3A*%2C*&subject=http%3A%2F%2Fd-nb.info%2Fgnd%2F4067488-5&t=book&aggregations=type) / [query 2](http://lobid.org/resources/search?q=title%3A*%2C+*&subject=http%3A%2F%2Fd-nb.info%2Fgnd%2F4067488-5&t=book&aggregations=subject.componentList.id)) (5246+64493) | 6777 / 0,2% (69739 / 2%)
volumeIn.multiVolumeWork | articles (27046), multiVolumeBook (2489), game (100), series (58), periodical (36), archivedWebpage (2) | 29731 / 0,8%

From this standpoint on I say that ~97% correct affiliation for one case is good enough. If one person searches for resources in another resource he or she will get the correct data. The only case in which the wrongly associated relation would have an effect, would be if one, for example, searches for all resources which are in a series or in a volume. For `containedIn` we have a sort of mirroring object as all resources which have this property should be an article. I think we can live with this low rate of errors and add the old properties. 
`containedIn` could be added to `isPartOf`, especially as there is another way to get the data and the low error rate wouldn't hurt that much. 
What do you think, @acka47 ?

**Comment by acka47** [comment]
Getting up to speed with this issue, responding to @fsteeg first.

>  The problem is that the 1 *Band* and the 1 *Serienband* can't be distinguished, both are listed under *2 Bände*. Because the way this works is that to show the information in the superordinate resource, we issue queries for subordinate resources linking to this superordinate resource with the different fields (`inSeries`/`volumeIn`). The superordinate resource is the same in both cases, so that does not help. 

The question is whether the distinction between inSeries/volumeIn is correct, necessary and useful here or whether a more generic approach wouldn't be more user friendly. Even the Aleph OPAC throws all the diffferent subordinate relationshops together, see http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DHT009821451 and click on "Bände in Ergebnisliste öffnen" in the details view. Currently, we basically have regular issues of a periodical (`volumeIn`) separated from special issues ("Sonderhefte") of the same periodical (`inSeries`). I think this distinction isn't clear at all in the UI and thus is rather confusing, so we might rather put them together as is currently the case on the test index.

**Comment by acka47** [comment]
Re. @ChristophEwertowski's numbers on cataloging errors, I have to say I don't understand how you came to the numbers and the conclusions you draw. Let's take a deeper look at this

**containedIn** 

- The [resources that are of type `Proceedings` and are `containedIn` another resource](http://lobid.org/resources/search?q=containedIn.id%3A*&t=proceedings&aggregations=type) look correct to me. Obviously, proceedings are often published as a longer article in a journal issue.
- Re. the periodicals, these are obviously double-typed `Periodical` and `Article` see http://lobid.org/resources/search?q=containedIn.id%3A*&t=periodical and http://lobid.org/resources/search?q=containedIn.id%3A*+AND+type%3AArticle+AND+type%3APeriodical. Looking at some examples, this actually makes sense as there are some periodically published resources in there that are actually published as part of a journal issue. Example: http://lobid.org/resources/HT006763140
- Bottom line: these again are highly specifical cases of periodicals we don't need to touch for now as nobody asked for it.

**inSeries**

Some of the [articles that are part of a series](http://lobid.org/resources/search?q=inSeries.series.id%3A*&t=article) are definitely not correctly catalogued, for some (e.g. small essays published in booklet form) it makes sense, though. Example: http://lobid.org/resources/TT002711511 (but the two different volume numbers are definitely incorrect).

**volumeIn**

- Not all [articles with a `volumeIn` relationship](http://lobid.org/resources/search?q=volumeIn.multiVolumeWork.id%3A*&size=100&t=article) are incorrectly catalogued. Example: http://lobid.org/resources/HT006331436
- From the [Multi-volume Works with a `volumeIn` relation](http://lobid.org/resources/search?q=volumeIn.multiVolumeWork.id%3A*+AND+type%3AMultiVolumeBook&size=100) all examples I looked seemed incorrect to me. THe stated relationship wasn't the problem though but the stated type.
-

**Comment by acka47** [comment]
I checked the actual mails from the NWBib list that were the basis for  https://github.com/hbz/nwbib/issues/126 (see quotes below). I haven't found a requirement to differentiate between "Serienbände" and other "Bände". Actually two NWBib stakeholders very clearly said to treat volumes of Multi-Volume works and volumes of a series the same.  Thus, I don't see any problem now to proceed with the general isPartOf approach.

On 13.07.2015 14:39, Adrian Pohl wrote 

> Ich habe mir HT009821451 (Altenberger Blätter) [2] gerade in der alten
> NWBib angeschau...  Wie soll das in dem konkreten Fall
> gelöst werden, wenn es zum einen Stücktitel und zum anderen Artikel als
> untergeordnete Titel gibt? Vielleicht im Feld "Bände" ein "Enthaltene
> Bände anzeigen"-Link auf die Bandliste und unter "Enthält" einen
> "Enthaltene Beiträge anzeigen"-Link auf die Aritkelliste?


On 14.07.2015 08:30, P., U. wrote:

> Bislang wurde ja kein Unterschied gemacht und auch die zugehörigen Bände bei Schriftenreihen waren unter dem Button "Enthaltene Beiträge anzeigen" aufgeführt. Um das zu trennen, müsste für alle Unterordnungen (Bände, Stücktitel), die entweder im Feld 010 (bei mehrbändigen Werken) oder im Feld 453 (bei Bänden von Schriftenreihen, bei Stücktiteln von Zeitschriften) die IDN der entsprechenden Überordnung enthalten, in der dazugehörigen Überordnung der Verlinkungsbutton "Zugehörige Bände anzeigen" genannt werden.

**Comment by acka47** [comment]
Discussing this offline with @ChristophEwertowski we decided to stick to the original proposal. This means:

- Use the same properties and relationship type for volume-in and in in-series relations.
- Keep the direct linking of articles to the source with `containedIn`. (We thought about also adding an isPartOf relation for this and associating the `bibliographicCitation` text with it. Though this might make things more homogeonous, it unnecessarily adds complexity and brings at least two problems with it: 1. `bibliographicCitation` is to be used on bibliographic resources and not relations. 2. there are [360k entries](http://lobid.org/resources/search?q=_missing_%3AcontainedIn.id+AND+bibliographicCitation%3A*) with  `bibliographicCitation` and without a link to the superordinate resource.
- Rename the property `superordinate` to `hasSuperordinatefor better comprehensibility.

I have to go now and will provide an example on Thursday.

**Comment by ChristophEwertowski** [comment]
An example:
```
containedIn : [
   {
      "id": "http://lobid.org/resources/HT007018915#!",
      "label": "lobid Ressource"
   }
],
...
isPartOf : [
   {
      "numbering" : "2",
      "hasSuperordinate" : {
         "id" : "http://lobid.org/resources/HT002888668#!",
         "label" : "lobid Ressource"
      }
   },
   {
      "numbering" : "73",
      "hasSuperordinate" : {
         "id" : "http://lobid.org/resources/HT001236717#!",
         "label" : "lobid Ressource"
      }
   }
],
```

**Comment by acka47** [comment]
@ChristophEwertowski will you please deploy this to test so that @fsteeg can then adjust the UI?

**Comment by ChristophEwertowski** [comment]
@fsteeg Deployed the change to test. The checks fail. I tried to adjust your files from `superordinate` to `hasSuperordinate` in a [different branch](https://github.com/hbz/lobid-resources/tree/427-onePropertyForInSeriesAndVolumeIn) but that branch still fails so probably that's not the reason for failing.

**Comment by fsteeg** [comment]
Deployed to test: http://test.lobid.org/resources/BT000003404

**Comment by acka47** [comment]
Looks good. Found two problems, though.

1. #459 
2. Two equivalent isPartOf statements with both the superordinates hbz and ZDB ID lead to suboptimal HTML presentation. Example: http://test.lobid.org/resources/HT008355609

Nonetheless, I think we can deploy this for now and deal with the issue in the next step.

**Comment by acka47** [comment]
Ping @hagbeck. The changes are now on production and you probably have to re-configure your transformation. A good example is http://lobid.org/resources/HT002888677?format=json where `inSeries` and `volumeIn` don't exist anymore and are both subsumed under `isPartOf`.
