### ISSUE TITLE
Add labels for frequent URIs (DOI, edoweb ...)

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#438]
Add real labels instead of placeholders for:
* Digital Object Identifier (DOI) ([example](http://lobid.org/resources/HT018700720?format=json))
* edoweb ([example](http://lobid.org/resources/HT019149667?format=json))
* deposit.d-nb.de ([example](http://lobid.org/resources/HT019025795?format=json))
* resolving over DNB resolver, nbn-resolving.de ([example](http://lobid.org/resources/HT018617137?format=json))
* ~~for subject, see [example](http://lobid.org/resources/HT019149667?format=json)~~ (is dealt with in https://github.com/hbz/lobid-vocabs/issues/67)

**Comment by ChristophEwertowski** [comment]
Set to test instance, see 
* [example DOI (production)](http://lobid.org/resources/TT050409948?format=json) / [example (test)](http://test.lobid.org/resources/TT050409948?format=json)
* [example edoweb (production)](http://lobid.org/resources/HT019149667?format=json) / [example edoweb (test)](http://test.lobid.org/resources/HT019149667?format=json)
* [example deposit.d-nb.de (production)](http://lobid.org/resources/HT015455455?format=json) / [example (test)](http://test.lobid.org/resources/HT015455455?format=json)
* [example (nbn-resolver with URN) (production)](http://lobid.org/resources/HT017480009?format=json) / example (test)](http://test.lobid.org/resources/HT017480009?format=json). 

With the same pull request I solved #407, so please review both before assigning the pull request. Also I see, that it should be `Edoweb Rheinland-Pfalz` like in `inCollection` of the second example. Because I expect additional renaming from your side I'll wait for them and do the all renaming in one step.

**Comment by acka47** [comment]
I adjusted some of the labels as discussed offline. +1

**Comment by dr0i** [comment]
Deployed to production, closed.
