### ISSUE TITLE
Missing languages

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#439]
See [example](http://lobid.org/resources/HT013208902?format=json) and [query for all resources with portugese language](http://lobid.org/resources/search?q=language.id%3A%22http%3A%2F%2Fid.loc.gov%2Fvocabulary%2Fiso639-2%2Fpor%22). 
It seems to me that the list of labels for languages in labels.json is a bit short. So it would be good to look after resources with non-covered languages.

**Comment by ChristophEwertowski** [comment]
Currently there are [809147 resources](http://lobid.org/resources/search?q=language.label:%22http://id.loc.gov/vocabulary%22) without a correct language label in our collection. 
I added labels for languages from Europe and some widely spoken languages from other parts of the world like Chinese. Only language labels where added which are used in the data. There are also the "languages" `Kein linguistischer Inhalt`, `Nicht zu entscheiden` and `Mehrere Sprachen`. 
Since in the data are only examples for new labels for the languages Portugese (HT018939763) and Spanish (TT001966831) I didn't set up a new test index. Also adding about 50 resources just for testing if they get the labels would bloat our test set. So just look at the changes and then assign it for deployment.

(Sadly we have no resource with the galactic language Klingon in our data ;) ([LoC detail page for entry in ISO 639-2](http://id.loc.gov/vocabulary/iso639-2/tlh)).)

**Comment by acka47** [comment]
+1 Shouldn't we also add the language to the HTML view?

**Comment by fsteeg** [comment]
Since the UI change here is not straightforward (so many languages, how to display, which to display), I think we should open a separate issue for adding the language to the UI to avoid having the data changes for this in a long running branch (leading to merging issues etc.)

**Comment by acka47** [comment]
I am ok with opening another issue. Although I don't get, why this is compilcated. You just need a field "Sprache" that displays the value(s) of `language.label`, don't you?

**Comment by fsteeg** [comment]
> You just need a field "Sprache" that displays the value(s) of language.label, don't you?

What about languages we don't have a label for? Should these be ignored? Isn't that misleading?

**Comment by dr0i** [comment]
As a default I would show the whole URI, even if this leads in rare cases to a big blob like with http://lobid.org/resources/HT015444576?format=json.

**Comment by ChristophEwertowski** [comment]
I agree. (By the way: That specific case shouldn't be a problem.)

**Comment by dr0i** [comment]
Ah, you are right! You already gave them the proper labels.

**Comment by fsteeg** [comment]
That's the issues I was thinking about. I had opened https://github.com/hbz/lobid-resources/issues/446 after posting https://github.com/hbz/lobid-resources/issues/439#issuecomment-303308493. This is nothing urgent, I won't be working on this today, so I don't think it should be holding up deployment and merge of the data changes.

**Comment by dr0i** [comment]
Also, I propose to introduce language facetting.

**Comment by dr0i** [comment]
Deployed to production, closed.

**Comment by ChristophEwertowski** [comment]
There are still ~250.000 resources with a missing/wrong language label. Because there are so many missing language labels and they will be shown in the UI I will go through the list of languages on a Friday and add the missing labels.
