### ISSUE TITLE
For spatial notations, add 700n subfield b to "coverage"

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#44]
Reported by E.L., 2016-02-19

> In dem Beispiel http://lobid.org/nwbib/HT017203152 müsste das GSW „10 ;  Münsterland <West>“ heißen und nicht „Westfälische Bucht (10)“ - wie in der alten NWBib.

Source data in http://beta.lobid.org/hbz01/HT017203152 has this:

```xml
<datafield tag="700" ind1="n" ind2="1">
  <subfield code="a">10</subfield>
  <subfield code="b">Münsterland <West></subfield>
</datafield>
<datafield tag="700" ind1="n" ind2="1">
  <subfield code="a">97</subfield>
  <subfield code="b">Borken <Borken, Kreis></subfield>
</datafield>
<datafield tag="700" ind1="n" ind2="1">
  <subfield code="a">97</subfield>
  <subfield code="b">Coesfeld <Kreis></subfield>
</datafield>
```

Data 2.0 in http://lobid.org/resources/HT017203152 has this:

```json
"nwbibspatial": [{
    "id": "http://purl.org/lobid/nwbib-spatial#n97"
},{
    "id": "http://purl.org/lobid/nwbib-spatial#n10"
}]
```

Our label for http://purl.org/lobid/nwbib-spatial#n10 is `Westfälische Bucht`.

Sounds like `700 b` should take precedence. Would be fitting with our general side car approach:

```json
{
    "id": "http://purl.org/lobid/nwbib-spatial#n10",
    "label": "Münsterland <West>"
}
```

Assigning @dr0i as potential implementor, ping @acka47 for functional sanity-check.

**Comment by acka47** [comment]
This case is analogous to what I just described in https://github.com/hbz/nwbib/issues/276#issuecomment-191124371: We have a general notation from the NWBib classification which is specified by the value in subfield `b`. Consequently, we should use the same solution for both. In https://github.com/hbz/nwbib/issues/276, we decided to map the value from subfield `a` to "nwbibspatial" and map the value – if available – from subfield `b` to "coverage". We will then only show the value from subfield `b` in the NWBib view.

What needs to be implemented then?

The extended quote from E.L.'s mail reads:
> Das Problem mit den GSW haben wir ebenfalls mit den Raumnotationen  10, 12, 14, 24, 28, 35, 36, 37, 52, 54, 72 und 74. Sie werden wohl nicht dargestellt. In dem Beispiel http://lobid.org/nwbib/HT017203152 müsste das GSW „10 ;  Münsterland <West>“ heißen und nicht „Westfälische Bucht (10)“ - wie in der alten NWBib.

Thus, we will have to extend the rule that adds the value of 700n subfield `b` to "coverage" so that it also covers the notations 10, 12, 14, 24, 28, 35, 36, 37, 52, 54, 72 und 74.

**Comment by fsteeg** [comment]
Just to make sure I understand:

So for http://lobid.org/resources/HT017203152 the `coverage` field will be:

```json
"coverage": [
    "Coesfeld <Kreis>",
    "Borken <Borken, Kreis>",
    "Münsterland <West>"
]
```

And `nwbibspatial` will remain as it is:

```json
"nwbibspatial": [{
    "id": "http://purl.org/lobid/nwbib-spatial#n97"
},{
    "id": "http://purl.org/lobid/nwbib-spatial#n10"
}]
```

But `nwbibspatial` won't be displayed in NWBib because it contains `97` (see https://github.com/hbz/nwbib/issues/276).

**Comment by acka47** [comment]
> But `nwbibspatial` won't be displayed in NWBib because it contains `97` (see https://github.com/hbz/nwbib/issues/276).

At least the label for `http://purl.org/lobid/nwbib-spatial#n97` shouldn't be displayed. I am not sure whether this also applies to `http://purl.org/lobid/nwbib-spatial#n10`.

**Comment by fsteeg** [comment]
E.L. wrote:

> In dem Beispiel http://lobid.org/nwbib/HT017203152 müsste das GSW „10 ; Münsterland &lt;West&gt;“ heißen und nicht „Westfälische Bucht (10)“ 

This sounds like it should not be displayed as well.

Doing this filtering in the (https://github.com/hbz/nwbib/issues/276) is not straightforward. Would it make sense and possible with reasonable effort to filter the `nwbibspatial` values on the data level? So in our sample here, we'd have no `nwbibspatial`.

**Comment by acka47** [comment]
> Would it make sense and be possible with reasonable effort to filter the nwbibspatial values on the data level? So in our sample here, we'd have no nwbibspatial.

I (accidentally, at first) described this in https://github.com/hbz/nwbib/issues/276#issuecomment-191124371...

**Comment by acka47** [comment]
The downside of removing it from the data would be that an entry by spatial classification – here http://nwbib.de/search?nwbibspatial=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib-spatial%23n10 – wouldn't list these entries. I don't know whether this actually is a problem...

**Comment by fsteeg** [comment]
Right, that would effectively break the Raumsystematik search.

But if I select "Westfälische Bucht" in http://nwbib.de/classification?t=Raumsystematik, I expect the results to contain "Westfälische Bucht", so I don't think it would make sense to remove that for display.

So to me a sensible solution seems to be to leave all in the data, and remove `96` and `97` in the UI if `coverage` exists (which is what https://github.com/hbz/nwbib/issues/276 says).

**Comment by fsteeg** [comment]
We just discussed this offline and agreed to make it so.

I'll keep in mind during impl that stakeholders might require removal of other notations than `96` and `97`.

**Comment by acka47** [comment]
Assigned @fsteeg because I think it still needs to be implemented. Should also probably move to "Working"...

**Comment by fsteeg** [comment]
The removal of 96, 97, and the others in the UI is implemented (this is what we discussed in the comments above). For the transformation, I assumed @dr0i would implement that, reassiging.

@dr0i: let me know if you won't be able to implement this before your leave.

**Comment by dr0i** [comment]
@fsteeg have a look if this is done with #48. `coverage` has the `Münsterland <West>` (as you wished it to be, see https://github.com/hbz/lobid-resources/issues/44#issuecomment-191183566). See  http://lobid.org/resources/HT017203152.

**Comment by fsteeg** [comment]
Looks good, even in production: http://nwbib.de/HT017203152

**Comment by fsteeg** [comment]
Assigning @acka47 for final review. Since it's already deployed, you could close if it's OK.

**Comment by acka47** [comment]
+1. Closing.
