### ISSUE TITLE
Clean up definitions of fulltextOnline, hasVersion and seeAlso

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#441]
The resource [HT018468645 (json)](http://lobid.org/resources/HT018468645?format=json) has the same url three times in it's bibliographic file. The url leads to a publisher abstract stored by the DNB. Since there a lots and lots of abstracts of this type in our data we should remove them from `fulltextOnline` and `hasVersion` and let them stored at `description`. As far as I remember I've never seen other things than abstracts under this domain but I could be wrong. In this case, however, it is clear because the url is stated as an "Inhaltstext".

**Comment by ChristophEwertowski** [comment]
While working on the removing of the abstracts which appeared multiple times I saw that there are other links which are duplicate. So I changed the definitions for these properties:
* `seeAlso`: Only contains links for "Zusätzliche Angaben". See HT013798403 which doesn't have it's `seeAlso` anymore ([example (production)](http://lobid.org/resources/HT013798403?format=json) / [example (test)](http://test.lobid.org/resources/HT013798403?format=json)).
* `fulltextOnline`: Also contains links described as "Volltext". ([Example (production)](http://lobid.org/resources/HT018998891?format=json) / [example (test)](http://test.lobid.org/resources/HT018998891?format=json))
* `hasVersion`: Contains everything from 655 which isn't labeled as a fulltext, table of contents or description.

**Comment by acka47** [comment]
Generally, the data in 655 is very messy and we won't get good data from bad source data.

> * `seeAlso`: Only contains links for "Zusätzliche Angaben". See HT013798403 which doesn't have it's `seeAlso` anymore ([example (production)](http://lobid.org/resources/HT013798403?format=json) / [example (test)](http://test.lobid.org/resources/HT013798403?format=json)).

I don't see why we should remove this information. In the lobid documentation [it says](http://lobid.org/resources/api#annotations:pH-MJCTmEee8DY-bgF8ldA) `SameAs` "[e]nthält einen Link zu weiteren nicht näher definierten Informationen über die Ressource (z.B. Inhaltsverzeichnis)." 

> * `fulltextOnline`: It addition to the former urls it also contains links described as "Volltext". ([Example (production)](http://lobid.org/resources/HT018998891?format=json) / [example (test)](http://test.lobid.org/resources/HT018998891?format=json))

Very good. +1

> * `hasVersion`: Contains everything from 655 which isn't labeled as a fulltext, table of contents or description.

We should rather use `seeAlso` for this and maybe remove `hasVersion` altogether.

**Comment by ChristophEwertowski** [comment]
About `seeAlso` and `hasVersion`: Before the changes it contained all but archived resources if it was an online resource. So it also contained `tableOfContents` etc. Since almost all urls of `hasVersion` in the test set lead to fulltexts they are not exactly *about* a resource but a version of it and should stay there. (Of 16 resources with hasVersion there was one Klappentext in it.) So I'm also against removing `hasVersion`.
The removed information should be in `hasVersion`. It misses because the function sanitizeUrl is used on the url and within the function the ftp-link isn't recognised which leads to giving back an empty string. Opened a [ticket](https://github.com/hbz/lobid-resources/issues/458) for adding ftp-links to the function.

**Comment by acka47** [comment]
So, basically, nothing will change but more links will be provided. Sounds good to me.

**Comment by dr0i** [comment]
Deployed to production, closing.
