### ISSUE TITLE
Remove wrong urn-url objects from properties

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#442]
There are URN-resolving links which are assigned to multiple properties, even if it's clear what they are. 
See [CT003012479](http://test.lobid.org/resources/CT003012479?format=json): fulltextOnline (correct)(MAB 655), hasVersion (MAB 655) and similar (MAB 552).
The property with the label `similar` is defined as following: 

> The property umbel:isLike is used to assert an associative link between similar individuals who may or may not be identical, but are believed to be so. This property is not intended as a general expression of similarity, but rather the likely but uncertain same identity of the two resources being related.

I think we should remove it if it's clear that the urn-link leads to a summary of fulltext. `hasVersion` is defined as following:

> A related resource that is a version, edition, or adaptation of the described resource.

While that's true, I think that a fulltext is also some sort of version of a resource. So `hasVersion` could be removed.
Do you agree, @acka47 ?

**Comment by ChristophEwertowski** [comment]
Will be resolved after deployment of #502.

**Comment by dr0i** [comment]
A reminder: #502 is deployed.

**Comment by ChristophEwertowski** [comment]
The superflous `hasVersion` is removed. What is about `similar`. Because of the definition from above I still think we should remove `similar` if it's identical with `fulltextOnline`. What do you think, @acka47 ?

**Comment by acka47** [comment]
I suggest to keep it for now as it is also part of the DINI KIM recommendations. I am not particularly happy with this myself but it doesn't bother to have it there. For my part, we can close this issue.

**Comment by ChristophEwertowski** [comment]
Closing this issue.
