### ISSUE TITLE
Subject chains of resource and superordiante resource should be separated (2.0)

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#450]
A customer for edoweb recognised that in [HT015660188](http://lobid.org/resources/HT015660188) subjects are mingled into one componentList, regardless if they originate from the resource or the superordinate resource. A solution for this problem would be splitting the macro `subjectRswkId` into two macros (ind2="1"/ind2="2"). It concerns lobid 1.0 but it should be fixed in 2.0, too.

**Comment by dr0i** [comment]
And then, how to model that data? Note: it's *not possible* to use the `source` property (example from http://lobid.org/resources/BT000103077.json):

     "subject" : [ {
           "id" : "http://purl.org/lobid/nwbib#s783000",
           "label" : "Schulgeschichte",
           "source" : {
                 "id" : "http://purl.org/lobid/nwbib",
                 "label" : "Sachsystematik der Nordrhein-Westfälischen Bibliographie"
            }
       }]
because that denotes the source of vocabulary, right?

**Comment by acka47** [comment]
I think the idea is to just create two separate `ComponentList` objects.

**Comment by acka47** [comment]
I think the idea is to just create two separate `ComponentList` objects.

**Comment by dr0i** [comment]
@acka47 Ah - got it now - Thx!
