### ISSUE TITLE
Subject chains of resource and superordiante resource should be separated (1.0)

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#451]
Related ticket for API 2.0, see #450.

A customer for edoweb recognised that in HT015660188 subjects are mingled into one componentList, regardless if they originate from the resource or the superordinate resource. A solution for this problem would be splitting the macros `subject-chain-name` and `subject-chain-perm` into two macros each (ind2="1"/ind2="2").
Assigning it @droi because he fought longer with it ;)

**Comment by dr0i** [comment]
This is resolved in lobid 2.0 (see #450) and won't in lobid 1.0.
Closing.
