### ISSUE TITLE
Add provenance data: who edited the resource

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#455]
We need to add some more provenance data to fulfill a desideratum from Nwbib stakeholders:

>    Sortiermerkmale sollten versuchsweise die Felder 070b ,  070_ und 070a in den Titelaufnahmen sein.
>    
>    070b = korrigierende Institution mit den möglichen Sigeln (=Feldinhalten) 0005, 0006, 0061, 5, 6, 61
>    070_ = katalogisierende Institution mit den möglichen Sigeln (=Feldinhalten) 0005, 0006, 0061, 5, 6, 61
>    070a = liefernde Institution mit den möglichen Sigeln (=Feldinhalten) 0005, 0006, 0061, 5, 6, 61
>    
>    Dabei hat bei der Sortierung Feld 070b Vorrang vor 070_ und Feld 070_ hat Vorrang vor 070a, denn die liefernde Institution ist niemals einer unser Landesbibliotheken, sondern meistens die DNB oder ein anderer Verbund. Die korrigierende Institution wird in der Regel die Bibliothek sein, die die NWBib-Notationen vergibt, und ist daher ausschlaggebend. Die katalogisierende Bibliothek ist nicht notwendig diejenige, die auch die NWBib-Bearbeitung vornimmt. Daher diese vorgeschlagene Rangfolge der zu berücksichtigenden Felder.
>    
>    Die Sigel scheinen im Feld 070 für die drei Landesbibliotheken nur in den Formen aufzutauchen, die oben aufgeführt sind, also nicht im ISIL-Standard. Das habe ich stichprobenartig in der von Herrn Christoph gelieferten Liste geprüft. Alle anderen evt. auftauchenden Sigel von anderen Bibliotheken müssten irrelevant für uns sein.
>    
>    Theoretisch kann es natürlich sein, dass keine unserer 6 Sigelformen in den Feldern 070 enthalten ist. Das dürften aber nur sehr wenige Fälle sein, die dann einfach nur entsprechend aufgelistet werden sollten.

**Comment by acka47** [comment]
This might not be so easy to implement. Looking at some examples, there sometimes seems to be content on the 070s that doesn't correspond with a sigel/ISIL. Examples:

[HT012698142](http://lobid.org/hbz01/HT012698142)
```xml
<datafield tag="070" ind1="-" ind2="1">
  <subfield code="a">9001</subfield>
</datafield>
<datafield tag="070" ind1="a" ind2="1">
  <subfield code="a">DNB</subfield>
</datafield>
<datafield tag="070" ind1="b" ind2="1">
  <subfield code="a">9001</subfield>
</datafield>
```

However, if we do this we should add the information to the `describedBy` object maybe adding objects for creation and modification to associate date and agent with it.

**Comment by acka47** [comment]
Here are some properties that might come handy:

- http://schema.org/sourceOrganization for "katalogisierende Institution"
- http://schema.org/provider for "liefernde Institution"
- http://open-services.net/ns/core#modifiedBy for "koorigierende Institution". This property looks like a good fit. From the description
> The URI of a resource describing the entity that most recently modified this resource.  The link target is usually a foaf:Person or foaf:Agent, but could be any type.  This is modeled after dcterms:creator, but Dublin Core currently has no equivalent property.

However, I am not quite sure how 070 is actually filled. The data is hopefully added automatically. As there are some strange cases, we should probably aks the colleagues how it works.

**Comment by acka47** [comment]
Here is another example, http://lobid.org/hbz01/HT018877897:

```xml
<datafield tag="070" ind1="-" ind2="1">
  <subfield code="a">467</subfield>
</datafield>
<datafield tag="070" ind1="a" ind2="1">
  <subfield code="a">DNB</subfield>
</datafield>
<datafield tag="070" ind1="b" ind2="1">
  <subfield code="a">61</subfield>
</datafield>
```
This could look like this in the JSON:

```json
{
   "id":"http://lobid.org/resources/HT018877897#!",
   "describedBy":{
      "dateCreated":"20160205",
      "dateModified":"20160714",
      "id":"http://lobid.org/resources/HT018877897",
      "label":"lobid Ressource",
      "sourceOrganization":"http://lobid.org/organisations/DE-467#!",
      "provider":"http://lobid.org/organisations/DE-101#!",
      "modifiedBy":"http://lobid.org/organisations/DE-61#!"
   }
}
```

**Comment by ChristophEwertowski** [comment]
I don't understand why the lobid organisations-urls which are built of sigels aren't put into `describedBy`. @dr0i : Let's have a look on it at Tuesday. ([Branch 455](https://github.com/hbz/lobid-resources/tree/455-addProvenanceData))

**Comment by ChristophEwertowski** [comment]
Deployed it to test. Example for `070-` (`sourceOrganisation`) and `070b` (`modifiedBy`): [Example HT008353356 (production)](http://lobid.org/resources/HT008353356.json) / [example (test)](http://test.lobid.org/resources/HT008353356?format=json). Example for `070a` (`provider`): [Example TT050421788 (production)](http://lobid.org/resources/TT050421788?format=json) / [example (test)](http://test.lobid.org/resources/TT050421788?format=json). 
Added sigel to mapping table sigel2isilMap.csv: 7, 1241, 1200, 1240, 1972, 1999

**Comment by acka47** [comment]
Looks good. The new properties are missing in the JSON-LD context, though.

**Comment by ChristophEwertowski** [comment]
Note: It wasn't updated on test but is included in the [context-labels.json](https://github.com/hbz/lobid-resources/pull/479/files#diff-1645de37c03451cf051ab14b99ee7d6b) and [context.json](https://github.com/hbz/lobid-resources/pull/479/files#diff-5ab2f2220a8eff3d9932b9648357820c).

**Comment by ChristophEwertowski** [comment]
Talked to dr0i about it and refreshed my memory about it: The changes in the jsonld context are visible after deploying. So look at the [context-labels.json](https://github.com/hbz/lobid-resources/pull/479/files#diff-1645de37c03451cf051ab14b99ee7d6b).

**Comment by acka47** [comment]
+1 Looks very good. Thanks. For example, resources [last modified by ULB Münster](http://test.lobid.org/resources/search?q=describedBy.modifiedBy.id:%22http%3A%2F%2Flobid.org%2Forganisations%2FDE-6%23!%22), [last modified by ULB Düsseldorf](http://test.lobid.org/resources/search?q=describedBy.modifiedBy.id:%22http%3A%2F%2Flobid.org%2Forganisations%2FDE-61%23!%22).
