### ISSUE TITLE
HT019340959 missing

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid-resources#456]
http://lobid.org/resource/HT019340959/about
http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DHT019340959

**Comment by dr0i** [comment]
That's a hickup of lobid/lodmill#798.
Many thanks for reporting!

**Comment by dr0i** [comment]
Indexed missing resources, closing.

**Comment by jschnasse** [comment]
works! thank you.
