### ISSUE TITLE
sanitizeUrl doesn't recognise ftp and www urls

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#458]
**ftp**
Without sanitizeUrl `ftp://ftp.zew.de/pub/zew-docs/dp/dp0349.pdf` from [HT013798403 (MAB field 655)](http://lobid.org/hbz01/HT013798403) is added; with it not. [UrlSanitizer.java](https://github.com/hbz/lobid-resources/blob/master/src/main/java/org/lobid/resources/UrlSanitizer.java) should be expanded for ftp-links.

**www**
If I add
```
<combine name="http://purl.org/dc/terms/hasVersion" value="${a}">
	<if>
		<none>
			<data source="655e1.[x3]"/>
		</none>
	</if>
	<data source="655[-e]1.u" name="a"/>
</combine>
```
the resource [TT002234459](http://lobid.org/hbz01/TT002234459) gets an additional, correct `hasVersion` object.

Actually this should be covered by 
```
<data source="655[-e][ -1].u" name="@linkContent">
	<sanitizeUrl></sanitizeUrl>
</data>
<combine value="${a}" name="@linkUri" flushWith="655[-e][ -1]">
	<data source="@linkContent" name="a"/>
</combine>
<combine name="@linkForDescription" value="${a}" sameEntity="true">
	<data source="655e[ -1].[x3]" name="a">
		<regexp match="[Ii][Nn][Hh][aA][lL][tT][sS][tT]"/>
	</data>
	<data source="655e[ -1].u" name="a"/>
</combine>
<combine name="@linkForTableOfContents" value="${a}" sameEntity="true">
	<data source="655e[ -1].[x3]" name="a">
		<regexp match="[Ii][Nn][Hh][aA][lL][tT][sS][vV]"/>
	</data>
	<data source="655e[ -1].u" name="a"/>
</combine>
...
<combine name="http://purl.org/dc/terms/hasVersion" value="${a}">
	<if>
		<none>
			<data source="655e1.[x3]">
				<regexp match="[vV][oO][lL][lL][tT][eE][xX][tT]"/>
			</data>
			<data source="@linkForDescription"/>
			<data source="@linkForTableOfContents"/>
		</none>
	</if>
	<data source="@linkUri" name="a">
		<sanitizeUrl></sanitizeUrl>
	</data>
</combine>
```
As I can't see any mistake in the second piece of code I suppose that `http://www.rhein-lahn-info.de/jakobsweg/` isn't covered by sanitizeUrl and gives back an empty string. Also: Why has the same URL to be sanitized at linkContent and down at linkUri? [Corresponding branch 441](https://github.com/hbz/lobid-resources/tree/441-removePublisherAbstractsFromFulltextOnlineAndHasVersion)

**Comment by dr0i** [comment]
Hm. This seems to be fixed - at least at the data level.

1. http://lobid.org/resources/HT013798403.json has a field `hasVersion` with the ftp-object. It is not shown via the web app, however: http://lobid.org/resources/HT013798403.

2. http://lobid.org/resources/TT002234459.json also has correctly the `hasVersion` field (a https-URI with a `www` in it).

I don't know if it's so important to show the `hasVersion` in the web-app, so I assign this to @acka47 to decide and move it to backlog.

**Comment by acka47** [comment]
Hmm, there are nearly half a million records with `hasVersion` but no `fulltextOnline` (compared to [370k where both exist](http://lobid.org/resources/search?q=_exists_%3AhasVersion+AND+_exists_%3AfulltextOnline)). As the `hasVersion` link can be really useful to end users who want to access the document, we should add it to the UI.

**Comment by acka47** [comment]
However, as this ticket is about something different which apparently is solved, I am closing this.
