### ISSUE TITLE
Assign resources from publication type miscellaneous to expressive type

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#461]
At the moment we have ~2,2 million resources with the publication type `Miscellaneous`. As @jschnasse pointed out customers would be happy if they don't see that many resources with this type. I will start this ticket with the collection of some reappearing cases and possible solutions.
I went through it by combination of the publication type miscellaneous and the media types.

* resources for which no fitting publication type exists
   * 38791 resources are audio-visual media
   * [Example HT013627719](http://lobid.org/resources/HT013627719) consists of 26 dias. So we need also a publication type image.
* Audio books and audio dramas can't be covered. No shortcut in MAB `051` for it, none other field which precisely points to this sort of publications.
   * ~~[HT014501310](http://lobid.org/hbz01/HT014501310): An audio drama. No fitting publication type (book or musical work?).~~
   * ~~[HT003424885](http://lobid.org/hbz01/HT003424885): An audio drama but with roles speaker.~~
   * ~~[HT017120289](http://lobid.org/resources/HT017120289): Audio book. Publication type book?~~
* musical work if 541 (ISMN) ([6273 resources](http://lobid.org/resources/search?q=ismn:*))
* manuscript: Shouldn't this be a publication type?
* many cassette tapes are lectures. At the moment there is no fitting publication type for it. They have no labels ([example](http://lobid.org/resources/HT006876039?format=json))
* map
   * expand map criteria from line 1646 ("^Karte") in morph to all keywords from 902[-a][-1].f to 947[-a][-1].f
* electronic
   * [HT016687843](http://lobid.org/resources/HT016687843) is part of a dissertation. Proposal: If `thesisInformation` exist type as academic work. [56809 resources](http://lobid.org/resources/search?q=thesisInformation:*)
   * ~~How to handle supplements to journals? [Example](http://lobid.org/hbz01/HT016540853).~~ Can be defined in MAB 051.
* extent (MAB 433)
   * ~~If it contains "Spiel" then it is a game. [Example HT006166055](http://lobid.org/resources/HT006166055)~~ [216 resources](http://lobid.org/resources/search?q=extent:Spiel)
   * ~~If it contains "Partitur" then it is a musical work. [Example HT019300138](http://lobid.org/resources/HT019300138)~~ [212 resources](http://lobid.org/resources/search?q=extent%3APartitur)

The number of resources can't be derived without statistics:
* Formschlagwörter
   * [HT016539049](http://lobid.org/hbz01/HT016539049): Tagged as "Wörterbuch" in 902-1.f. Can be typed as a reference source. 
   * Some resources contain Formschlagwörter in a different form, see [HT007190101](http://lobid.org/hbz01/HT007190101), MAB field 952.
   * At the moment we only take "Karte", "Aufsatzsammlung" and "Festschrift" into account. We should think about if we use other keywords of the [list](http://www.ib.hu-berlin.de/~kumlau/handreichungen/h66/RSWK/rswk_a6.htm). 
   * Other keywords which fit existing publication types: "Atlas" -> Buch, Karte, "Audio-visuelles Material", "Bericht", "Bibliographie", "Biographie", "Enzyklopädie" -> reference work, "Kongress" -> Konferenzschrift, "Musikdruck" -> publishedScore, Schulbuch", Spiel", "Zeitschrift" -> periodical , "Zeitung" ...
* [HT016694895](http://lobid.org/hbz01/HT016694895): Software in general has no publication type. (If 651.a Systemvoraussetzungen and 651.b; 654) http://schema.org/SoftwareApplication can be used.
* maps which are tagged as Atlas (analogue to "^Karte") should be typed as a book
* maps which aren't in an Atlas ([example HT017125401](http://lobid.org/hbz01/HT017125401)). Mostly contain scale in title (1:25000, 1:25 000) or MAB 407.
* MAB 551 (Verlags-, Produktions- und Besellnummer von Musikalien und Tonträgern) -> publishedScore
* if MAB 516d -> publishedScore

Update: I won't proceed if there are too few resources which aren't already typed as the wanted type. (<1000).

**Comment by ChristophEwertowski** [comment]
Mainly @jschnasse : We already added resources with 051.s in lobid 2.0. See for example [HT015780722 (FRL)](https://repository.publisso.de/resource/frl%3A2708134) which hasn't a publication type and [HT015780722 (lobid 2.0)](lobid.org/resources/HT015780722). So there remain 140 of 4895 resources which are in the collection of "Fachrepositorium Lebenswissenschaften" without a publication type ([query](http://lobid.org/resources/search?q=inCollection.label%3AFachrepositorium&t=miscellaneous&aggregations=type)). For Edoweb it's 146 of 3104 (http://lobid.org/resources/search?q=inCollection.label%3AEdoweb&t=miscellaneous&aggregations=type). 

In FRL there are lots of reports without a publication type. Only one has the Formschlagwort "Bericht" which is used to describe the content/form of resource and could be used to set the type to report. The only other clues can be found in the title which can't be used because the word report is also used for resources which in fact aren't reports (like http://lobid.org/resources/HT013799621 (NSFW? ;)). In Aleph the MAB field for stating that something is a report or of a different publication type is 051 and it should be set there by librarians. The videos could be covered by using a new publication type which contains all videos and takes the same criteria as for audio-visual media.
In Edoweb we have some official publications which can be covered by MAB 064 (field for RDA Formschlagwörter) ([example](http://lobid.org/hbz01/HT019213459)) and maps, which need an own publication type if they are not in a book.

**Comment by jschnasse** [comment]
Hi @ChristophEwertowski , thank you for the comprehensive report. It is good to know that most of the issues of the last weeks are already taken into account in the upcoming version. Is there a chance to get type enhancements into lobid 1.0 as well, also good for NWBIB? How is the situation in lobid 1.0?

**Comment by ChristophEwertowski** [comment]
Used the statistic tool to get knowledge about if it is worth to use other fields for assigning publication types.
* ~~`516d1.a` (Angaben ueber die musikalische Notation): ~~ 321 resources
* `551` (Verlags-, Produktions- und Besellnummer von Musikalien und Tonträgern): ~ 60.000 resources
* `651` (Fußnote zur Computerdatei): ~ 44.000 resources
* `654` (Systemvoraussetzungen für die Computerdatei): ~ 10.300 resources
* `902-[-12].f` (Formschlagwort) (not already included "Aufsatzsammlung" or "Karte")
**Audio-visual**: 4956 "DVD-Video", 1988 "Videokassette"
**Bibliography**: 51766 "Bibliographie"
**Biography**: 59098 "Biographie", 13981 "Autobiographie"
**Book**: 59374 "Bildband", 45985 "Lehrbuch", 37267 "Anthologie", 9984 "Atlas", 7335 "Kinderbuch",  5034 "Jugendbuch", 4966 "Bilderbuch", 4960 "Kochbuch", 4258 "Kindersachbuch", 3254 "Lesebuch", 2771 "Auktionskatalog", 1820 "Jugendsachbuch"
**Combination**: 3282 "Medienkombination"
**Map**: 6853 "Altkarte", 2839 "Stadtplan"
**Microform**: 4012 "Mikroform"
**Newspaper**: 2065 "Zeitung"
**Periodical**: 285245 "Zeitschrift"
**Proceedings**: 181925 "Kongress"
**Reference work**: 82585 "Wörterbuch", 4995 "Enzyklopädie", 4029 "Werkverzeichnis", 4013 "Bestimmungsbuch", 3276 "Wörterbuch <mehrsprachig>"
**Report**: 19875 "Erlebnisbericht", 14455 "Bericht", 3265 "Reisebericht", 1803 "Literaturbericht", 1689 "Forschungsbericht"
**School book**: 50649 "Schulbuch"
**Series**: 1661 "Schriftenreihe"
**Standard**: 4625 "Richtlinie", 2293 "Norm"
**Statistics**: 13518 "Statistik"

* `952-1.s` (Sachschlagwort)
   * 680303 "Formschlagwort"
   * 6228 "Formschlagwort, Bildliche Darstellung"
   * 3093 "Formschlagwort, im weiteren Sinn"

**Comment by ChristophEwertowski** [comment]
What do you think @acka47 ? I didn't include example resources for each case because it would have bloated our test set. Simply look at the morph.

**Comment by acka47** [comment]
Overall, this looks very good and will gain us some more information.  I went through the diffs of the morph and added some comments.
