### ISSUE TITLE
Assign resources from medium miscellaneous to expressive medium

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#464]
Refers to #461. As most resources with the publication type "Miscellaneous" also have the medium "Miscellaneous" (2118291 of 2274920) it is good to improve the medium so that I know what to look for while improving the publication type. In the following I will list some ideas:
* edition (MAB 400, 403)
   * If the edition fields contain "Reprint" or "Nachdruck" they are prints ([example reprint](http://lobid.org/hbz01/HT007186907) / [example Nachdruck](http://lobid.org/resources/HT014815029). [5572 resources](http://lobid.org/resources/search?q=edition:Reprint)/[303 resources](http://lobid.org/resources/search?q=edition:Nachdruck)
   * If the edition fields contain "Mikrofiche" or other microforms the resource has got the medium mikroform. [Example](http://lobid.org/resources/HT013064773) [4726 resources](http://lobid.org/resources/search?q=edition:Nachdruck)
   * ~~"Karte" [76 resources](http://lobid.org/resources/search?q=edition%3A%22Karte%22), "Videokassette/Videocassette" [310 resources which start with "Video"](http://lobid.org/resources/search?q=edition%3AVideo*), "Tonkassette/Kompaktkassette/MC" [2 resources](http://lobid.org/resources/search?q=edition%3AKompaktkassette)/[10 resources](http://lobid.org/resources/search?q=edition%3ATonkassette)/[10 resources](http://lobid.org/resources/search?q=edition%3AMC), "Dia" [134 resources](http://lobid.org/resources/search?q=edition:%22Plakat%22), "Plakat" [10 resources](http://lobid.org/resources/search?q=edition:%22Plakat%22), "Schallplatte" [12 resources](http://lobid.org/resources/search?q=edition:%22Schallplatte%22)~~
* extent (MAB 433)
   * If extent contains "Karte" then the resource is a map. [1731 resources](http://lobid.org/resources/search?q=extent:Karte) 
   * Something which starts with "Video" should have the medium audio-visual. [Example](http://lobid.org/resources/HT006383703?format=json) [6898 resources which start with "Video"](http://lobid.org/resources/search?q=extent:Video*). "DVD-Video" also. [2770 resources](http://lobid.org/resources/search?q=extent%3A%22DVD-Video%22)
   * If it contains "Tonkassette/Kompaktkassette/MC" then the resource is an audio resource. [Example](http://lobid.org/resources/HT010747922?format=json) / [example "Kompaktkassette](http://lobid.org/resources/HT003528408) / [example "music cassette"](http://lobid.org/resources/HT008950475) [2247 resources](http://lobid.org/resources/search?q=extent:Tonkassette)/[1360 resources](http://lobid.org/resources/search?q=extent:Kompaktkassette)/[56 resources](http://lobid.org/resources/search?q=extent:MC)
   * ~~If it contains "Dias" then the resource is an image. [Example](http://lobid.org/resources/HT006868075)~~ [93 resources](http://lobid.org/resources/search?q=extent:Dia)
   * ~~If it contains "Plakate" and is no online resource then the resource is printed. [Example](http://lobid.org/resources/HT006371168)~~ Too few resources.
   * If it contains "CD/Compact-Discs" and is a musical work then the resource is of the medium audio and electronic resource (Datenträger). [Example](http://lobid.org/resources/HT010740421). [1392 resources which are no audio](http://lobid.org/resources/search?q=extent:CD&t=publishedscore)/[5527 resources which are no electronic resource](http://lobid.org/resources/search?q=extent:CD&t=publishedscore) If it isn't a musical work it is only an electronic resource ([example](http://lobid.org/resources/HT006740259?format=json))
   * ~~If it contains "Schallplatte" then the resource is of the medium audio. [Example "record"](http://lobid.org/resources/HT003863964)~~ [370 resources](http://lobid.org/resources/search?q=extent%3ASchallplatte)
   * If it contains "DVD-Video" then it is an electronic work. [Example](http://lobid.org/resources/HT019134891) [1147 resources](http://lobid.org/resources/search?q=extent%3A%22DVD-Video%22)
   * ~~If it contains "Audio-CD" then it has the medium audio and electronic resource. [Example](http://lobid.org/resources/HT013036115)~~ ([26 resources](http://lobid.org/resources/search?q=edition:Audio-CD)) [374 resources without audio, 831 without electronic resource](http://lobid.org/resources/search?q=extent%3A%22Audio-CD%22)
   * ~~If it contains "Online" then it has the medium online.~~ [762 resources](http://lobid.org/resources/search?q=extent:Online)
* ~~A videodisc should have the medium audio-visual. [Example](http://lobid.org/hbz01/HT018964330) MAB 062~~ ([13 resources without audiovisual, 2 without electronic resource](http://lobid.org/resources/search?q=extent%3A%22Videodisc%22))
* combinations: [HT019321220](http://lobid.org/resources/HT019321220?format=json) isn't labeled right. Do we register all publication types of combinations?
* If no other medium then set a resource as print?
* ~~Can a "Tonbildreihe" be named as an audio-visual resource? ([Example](http://lobid.org/resources/HT006868075))~~ [119 resources](http://lobid.org/resources/search?q=Tonbildreihe) 
* ~~[HT000382616](http://lobid.org/hbz01/HT000382616): MAB 523 (Heft and Tonkassette) -> Audio and Print~~ Too much variance in this field to handle it. 
* ~~If a role "Darsteller" exists then it is audio-visual. [Example](http://lobid.org/hbz01/HT006316264)~~ It isn't. See multiple posters like [HT016712209](http://lobid.org/resources/HT016712209)
* ~~Electronical periodicals which are in the ZDB *should* be marked as such. So the others would be printed.~~ [26 resources from the ZDB don't have a medium](http://lobid.org/resources/search?q=inCollection.label:%22Zeitschriftendatenbank%20(ZDB)%22)

Number of resources not countable without statistics:
* MAB 062 (Datenträgertyp)
   * 062-1.a (a: Datenträgertyp in Textform): Videodisk, Online-Ressource
   * 062-1.b (b: Datenträgertyp in codierter Form): vd, cr [example](http://lobid.org/hbz01/HT019317079
* MAB 064 (Inhaltstyp- und Datenträgertyp erweitert)
   * 064b1.a (b: Angaben zum Datenträger): Video
   * 064b1.9: 4585125-6
* MAB 334 (Allgemeine Materialbenennung)
   * 334-[12].a: "Elektronische Ressource" ([example](http://lobid.org/hbz01/TT003436638)), "Medienkombination" ([example](http://lobid.org/hbz01/HT019321220)), "Dia", "Plakat", "Schallplatte"
* MAB 437 (Angabe von Begleitmaterialien): Resources which have it are combinations. 
* MAB 652-1.a ("Spezifische Materialbenennung und Dateityp"): Video
* MAB 902-1.f: Karte etc. (see [list of "Formschlagwörter"](http://www.ib.hu-berlin.de/~kumlau/handreichungen/h66/RSWK/rswk_a6.htm))

Update: I list the number of affected resources and strike out the cases which have too few resources (<1000) (hits minus resources which already have the wanted medium).

**Comment by ChristophEwertowski** [comment]
I expanded the definitions if they concern enough resources.

**Comment by ChristophEwertowski** [comment]
Results of the statistics (>1000 results).
* 062-1.a (Datenträgertyp in Textform)
345731 	 "Band",
83254 	 "Online-Ressource",
8496 	 "Blatt",
5262 	 "Audiodisk",
2645 	 "Videodisk",
1725 	 "Computerdisk"
* 062-1.b (Datenträgertyp in codierter Form)
345731 	 "nc" -> Band
83254 	 "cr" -> Online-Ressource
8496 	 "nb"
5262 	 "sd"
2645 	 "vd" -> Videodisk
1725 	 "cd"
* 064b1.a (Inhaltstyp- und Datenträgertyp erweitert)
4458 	 "CD",
2151 	 "DVD-Video"
* 064b1.9 (Inhaltstyp- und Datenträgertyp erweitert)
4456 	 "(DE-588)4522869-3",
2118 	 "(DE-588)4585125-6"
* 334-[-12].a (Allgemeine Materialbenennung)
1083906 	 "Elektronische Ressource" (>120 wrongly written resources)
334333 	 "Musikdruck"
148706 	 "Tonträger"
57215 	 "Medienkombination" (10 "[Medienkombination]")
37948 	 "Bildtonträger" (43 "[Bildtonträger]")
21889 	 "Mikroform",
16180 	 "Bildliche Darstellung"
* 437-1.a (Angabe von Begleitmaterialien)
Multiple versions of CD or Diskette.
* 652-1.a (Spezifische Materialbenennung und Dateityp)
256372 	 "Online-Ressource",
4629 	 "DVD-Video",
1966 	 "CD-ROM"
* 902-1.f (Formschlagwort)
46397 "Online-Publikation"
18844 "CD-ROM"
6724 "CD"
4956 "DVD-Video"
2459 "Hörbuch"
1988 "Videokassette"
1793 "DVD-ROM"
1640 "Tonträger"
1066 "Diskette"
913 	 "Elektronische Publikation"

**Comment by ChristophEwertowski** [comment]
What do you think @acka47 ? I didn't include example resources for each case because it would have bloated our test set. Simply look at the morph.

**Comment by acka47** [comment]
Overalll, this looks very good and will gain us some more information.  I went through the diffs of the morph and added some comments.

**Comment by ChristophEwertowski** [comment]
Please look at my comments. If you agree with them assign the pull request to dr0i.

**Comment by acka47** [comment]
+1
