### ISSUE TITLE
Document instructions for analyzing coverage and content of MAB fields

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#466]
In https://github.com/hbz/lobid-resources/issues/455#issuecomment-305762786 I wrote:

> However, I am not quite sure how 070 is actually filled. The data is hopefully added automatically. As there are some strange cases, we should probably ask the colleagues how it works.

Generally, I think we should run some analytics on the Aleph XML dump before adding or improving the data transformation. This ticket aims at enabling @ChristophEwertowski and myself to do so on the example of field 070 indicators `-`, `a`, and `b`. 

Results should be:

1. information on the coverage of the fields in the hbz01 data (like "`070-`: 100%, `070a`: 77,3% etc.`
2. a list of different values in each field indicating their occurrence

**Comment by ChristophEwertowski** [comment]
Isn't this covered by https://github.com/hbz/lobid-resources/pull/469? The examples are within the statistics morph.

**Comment by dr0i** [comment]
I admit to have been confused now, too, but it isn't it just that #466 is the issue, #469 the Pull Request belonging to issue #466?

**Comment by ChristophEwertowski** [comment]
Yes. I remember that it was shown divided to me in waffle although I now see in the pull request it is mentioned by you that it resolves this issue. So my last comment can be ignored.

**Comment by dr0i** [comment]
Re waffle: ACK. Yesterday I changed in #469 a "see #466" to "resolves #466" to stick them together. However I wouldn't rely 100% on waffle, I've seen separations of issues and PRs even if they shouldn't.
