### ISSUE TITLE
Redundant isPartOf information leads to UI issues

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#467]
From https://github.com/hbz/lobid-resources/issues/427#issuecomment-306442526:

> Two equivalent isPartOf statements with both the superordinates hbz and ZDB ID lead to suboptimal HTML presentation. Example: http://lobid.org/resources/HT008355609

[JSON-LD](http://lobid.org/resources/HT008355609.json) snippet:

~~~json
{
   "isPartOf":[
      {
         "hasSuperordinate":[
            {
               "id":"http://ld.zdb-services.de/resource/127752-2",
               "label":"Zeitschriftendatenbank (ZDB)"
            }
         ],
         "type":[
            "IsPartOfRelation"
         ]
      },
      {
         "hasSuperordinate":[
            {
               "id":"http://lobid.org/resources/HT006896776#!",
               "label":"lobid Ressource"
            }
         ],
         "numbering":"59",
         "type":[
            "IsPartOfRelation"
         ]
      }
   ]
}
~~~

[Source](http://lobid.org/hbz01/HT008355609) snippet:

~~~xml
<datafield tag="010" ind1="-" ind2="1">
  <subfield code="a">HT006896776</subfield>
</datafield>
<datafield tag="020" ind1="a" ind2="2">
  <subfield code="a">127752-2</subfield>
  <subfield code="b">DNB</subfield>
</datafield>
<datafield tag="025" ind1="a" ind2="2">
  <subfield code="a">010724656</subfield>
</datafield>
<datafield tag="025" ind1="z" ind2="2">
  <subfield code="a">127752-2</subfield>
</datafield>
<datafield tag="026" ind1="-" ind2="2">
  <subfield code="a">ZDB127752-2</subfield>
</datafield>
~~~

Maybe a solution is to ignore the ZDB link in 025 if we have a link to a superordinate resource in 010.

**Comment by acka47** [comment]
I can't review this as no resource which has a resource from ZDB as superordinate is indexed on test: http://test.lobid.org/resources/search?q=isPartOf.hasSuperordinate.label%3AZeitschriftendatenbank

**Comment by ChristophEwertowski** [comment]
I looked at the labels in the small test set and in fact there are no labels "Zeitschriftendatenbank" in `isPartOf` anymore. An example of the change: [example HT005944358 (production)](http://lobid.org/resources/HT005944358.json) / [example (test)](http://test.lobid.org/resources/HT005944358?format=json). The ZDB-link is ignored, e.g. isn't added because of the existing MAB `010-1.a`. The frontend view changes accordingly.

**Comment by acka47** [comment]
+1
