### ISSUE TITLE
Search by clicking on DDC subject doesn't work

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#470]
Example http://lobid.org/resources/HT014872891 (click on "Das Buch").

Generally, we should think about adding an extra line ("DDC") for DDC where we show the label ass well as the notation, in this eaxmple something like:  

> DDC: Das Buch (020)

See also #400.

**Comment by fsteeg** [comment]
Deployed to stage, see:

http://stage.lobid.org/resources/search?subject=http%3A%2F%2Fdewey.info%2Fclass%2F002%2F

**Comment by ChristophEwertowski** [comment]
+1
