### ISSUE TITLE
Add timestamp for including resource into lobid-resources

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#477]
@jschnasse would like to have a timestamp for the point of time when the bibliographic resource was included into lobid-resources. That way it would be easier to add missing resources due to a failed update. He told me that he talked to you @dr0i about it so I'm opening a ticket that it doesn't get forgotten.

**Comment by dr0i** [comment]
Discussed a possibly better solution offline with @jschnasse. Two ideas:

1. Increase time frame for updated lobid resources.
In `modified` resp. `created` a timestamp indicates when the resource was updated in aleph and thus, *if* all went well, one day later in lobid. Status quo is to query lobid for resources which changed the last two days, so you get all updated resources. Now, if a lobid update fails the lobid resources will be added to lobid a day (or more...) later the timestamps are outdated and a query won't fetch them. Increasing the time frame to , say, 4 days, *would* get them (as long as the failed updates are re-updated successfully in two days after the failing). 4 days should be safe. This safety belt comes with the disadvantage of getting the last updates multiple times and thus updating ones own resources which is unnecessary. 

2. Compare timestamps of lobid resources and one's own resources:
Get a list of all lobid resources as in 1. , possibly with an even bigger time frame.  Compare the timestamps of these with the timestamps of one's own resources. After this identification of changed lobid resources go on with syncing them to one's own resources. Advantage: no unnecessary updates are triggered in one's own system.

Assigning @jschnasse for implementing and evaluating this.

**Comment by jschnasse** [comment]
I solved it by doing a pairwise comparison of all resources and their respective timestamps. In order to become aware of lobid internal changes (e.g. enhancements in metadata mapping) one could implement a comparison based on hash codes.
