### ISSUE TITLE
Resources with only an isPartOf-label aren't shown

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#478]
Resources which only have a label as `isPartOf` information aren't shown in the frontend. For example http://lobid.org/resources/HT008328655.

**Comment by acka47** [comment]
From the [JSON-LD](http://lobid.org/resources/HT008328655.json):

```json
{
   "id":"http://lobid.org/resources/HT008328655#!",
   "isPartOf":[
      {
         "label":"Power test codes"
      }
   ]
}
```

The use of `isPartOf` differs from other resources where there is a `hasSuperordinate` in between `isPartOf` and `label`. We need to fix this so that it reads:

```json
{
   "id":"http://lobid.org/resources/HT008328655#!",
   "isPartOf":[
      {
         "type":"IsPartOfRelation",
         "hasSuperordinate":{
            "label":"Power test codes"
         }
      }
   ]
}
```

**Comment by ChristophEwertowski** [comment]
Labels added at `hasSuperordinate`. 
Example with multiple superordinates without numbering: [(production)](http://lobid.org/resources/HT009719670?format=json) / [example (test)](http://test.lobid.org/resources/HT009719670?format=json)

**Comment by ChristophEwertowski** [comment]
I tried to integrate MAB `4[56789]5` instead of `4[56789]1` but that didn't work so I fell back to the solution of `4[56789]1`. At least in the test set it would lead to the same results.

**Comment by acka47** [comment]
As HT009719670 looks really broken (wrongly catalogued) to me, I queried for all resources with a superordinate label and without superordinate ID: http://test.lobid.org/resources/search?q=isPartOf.hasSuperordinate.label:*+AND+_missing_:isPartOf.hasSuperordinate.id 

I noticed that the numbering is missing for resources that actually have information in 451 after the semicolon, see e.g.:
- HT007847626 ([source](http://lobid.org/hbz01/HT007847626), [JSON](http://test.lobid.org/resources/HT007847626?format=json))
- HT007849956 ([source](http://test.lobid.org/hbz01/HT007849956), [JSON](http://test.lobid.org/resources/HT007849956?format=json))

**Comment by ChristophEwertowski** [comment]
Solved, see your links. Also removed square brackets from the numbering, see [HT018771475 (production)](http://lobid.org/resources/HT018771475?format=json) / [HT018771475 (test)](http://test.lobid.org/resources/HT018771475?format=json) and [TT001230001 (production)](http://lobid.org/resources/TT001230001?format=json) / [TT001230001 (test)](http://test.lobid.org/resources/TT001230001?format=json) for numbering of superordinate relations with 4[56789]3 ([MAB](http://lobid.org/hbz01/TT001230001)). It seems that a variable in one macro isn't transported to an other macro.

**Comment by acka47** [comment]
+1
