### ISSUE TITLE
Missing resource in v2

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid-resources#480]
http://lobid.org/resources/HT016987148
http://lobid.org/resource/HT016987148
http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DHT016987148

**Comment by dr0i** [comment]
Indexed the resource manually after updating the morph in #481.
This ticket spawned #482 which promises to capture droppings more closely so that a fix of these documents will be done proactively.
Closing this issue.
