### ISSUE TITLE
Documents encountering a MapperParsingException are dropped

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#482]
Wrong data types, sometimes resulting from a seldom appearing of wrong data structures like in #480, result in a silently dropping of that resource. Grepping in the elasticsearch logs on the productive server reveals around 600 documents that are dropped. These must be looked at more closely to gather the underlying problem. Via the morph either the data structure or the values of the fields should be corrected.

After fixing these document issues a report should be generated which gather document IDs of dropped resources.

**Comment by ChristophEwertowski** [comment]
I went through the log file which wasn't that long because of few errors which appeared often.

**Comment by dr0i** [comment]
This seems to be the mother of #675 and #682.
Things left: automatically write an email to inform about dropped resources.

**Comment by dr0i** [comment]
Ah, the creation of the automatic report has an issue of its own (#518). Closing this one then.
