### ISSUE TITLE
Dropped publisso documents

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#483]
Re #482 these are the dropped publisso documents. Data fixing is prioritized. CC @jschnasse :

- [ ] HT019353934 // 599-1.a="HT019353934" => Recursion because doc is referencin g itself. Must be fixed by cataloguers, yes ? 
- [x] HT017824354
- [x] HT018251327
- [x] HT017359543
- [x] HT016573897
- [x] HT017319578
- [x] HT017326336
- [x] HT016987148
- [x] HT018467813

**Comment by jschnasse** [comment]
easy to get a list for edoweb as well?

**Comment by dr0i** [comment]
Yes, but none edoweb resource found.

**Comment by dr0i** [comment]
@jschnasse resolving #480 got all missing docs fixed (s.a.) but HT019353934. Indexed them, too. What do you think about HT019353934 ?

**Comment by jschnasse** [comment]
Hi @ChristophEwertowski , kannst Du mal bei uns im FRL Jira fragen, was damit ist?

**Comment by ChristophEwertowski** [comment]
I just looked it up. The missing resource is available at http://lobid.org/resources/HT019353934.json. If I look up the resource at hbz01 there isn't a MAB field 599. Closing this issue.
