### ISSUE TITLE
Show source of subjects

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#493]
In #470 you acka47 proposed: 

> Generally, we should think about adding an extra line ("DDC") for DDC where we show the label ass well as the notation, in this eaxmple something like:

    DDC: Das Buch (020)

I'm in favour of it if #400 is solved. Of course other sources should be shown too, not only the DDC.

**Comment by acka47** [comment]
We already did this with #265. Closing.
