### ISSUE TITLE
Regular expression for DOI not correct

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#494]
The DOI of HT017702345 is `10.1039/9781849737708` (see [MAB-XML](http://lobid.org/hbz01/HT017702345)). The "10." isn't put into the json (see [json](http://lobid.org/resources/HT017702345.json)).

**Comment by ChristophEwertowski** [comment]
DOI corrected. [HT017702345](http://lobid.org/resources/HT017702345?format=json)[HT017702345 (test)](http://test.lobid.org/resources/HT017702345?format=json).

**Comment by dr0i** [comment]
Good that you catched this!
