### ISSUE TITLE
What to do with ebook packages as owners

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#496]
Originates from #340. What do we do with ebook packages as owners? ([Example ZDB-1-EEB](http://lobid.org/resources/search?owner=ZDB-1-EEB&aggregations=owner). In the [sigel2isilMap.csv](https://github.com/hbz/lobid-resources/blob/master/src/main/resources/sigel2isilMap.csv) there are 325 "Nationallizenzen" and 50 other packages.

**Comment by acka47** [comment]
I think we should re-include them so that their URIs resolve but they should be excluded from search. As this is a duplicate of #308 then, I am closing this issues
