### ISSUE TITLE
HT019248596 ArchivedWebpage MAB 655e missing

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid-resources#499]
Talking about lobid v1, sorry!

Nice looking Example 

    http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DTT002234840 mit
    655e 	|u http://www.jusos-birkenfeld.de/
    https://lobid.org/resource/TT002234840

Example with missing URL

    http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DHT019248596
    655e 	|u http://www.klimaatlas.koblenz.de/ |z Archivierte Online-Ressource |x kostenfrei |z Langzeitarchivierung
    https://lobid.org/resource/HT019248596

**Comment by dr0i** [comment]
> Talking about lobid v1, sorry!

Would be good to open issues at the right place, then.
The lobid 1.0 repo is located at https://github.com/lobid/lodmill.

**Comment by dr0i** [comment]
Besides, this issue also affects lobid 2.0 . So we leave it here, too.
Thx for the report!

**Comment by ChristophEwertowski** [comment]
Solved for lobid 2.0. See [HT019248596 (production)](https://lobid.org/resources/HT019248596?format=json) / [HT019248596 (test)](https://test.lobid.org/resources/HT019248596?format=json).

**Comment by acka47** [comment]
I just looked at it and I think the underlying problem actually is a cataloging error which shouldn't be countered by adjusting the morph. In HT019248596 `655e` is repeated:

```xml
<datafield tag="655" ind1="e" ind2="1">
  <subfield code="u">http://www.klimaatlas.koblenz.de/</subfield>
  <subfield code="z">Archivierte Online-Ressource</subfield>
  <subfield code="x">kostenfrei</subfield>
  <subfield code="z">Langzeitarchivierung</subfield>
</datafield>
<datafield tag="655" ind1="e" ind2="1">
  <subfield code="u">https://www.edoweb-rlp.de/resource/edoweb:88</subfield>
  <subfield code="x">Archivierte Online-Ressource</subfield>
</datafield>
```

The second entry is probably wrong as I don't think `https://www.edoweb-rlp.de/resource/edoweb:88` is archived. Thus, I think the record should be corrected and before adjusting the morph we have to discuss whether 655e actually is intended to be repeated. (I don't think that it make sense.)

**Comment by jschnasse** [comment]
Wow - this is annoying. The second link is generated by the edoweb repository itself and transferred via OAI-PMH to the catalogue together with the URNs. I don't know the reason behind it, it was a direct requirement of the union catalogue.

If possible to solve for API 2, why not solve for API 1?

**Comment by acka47** [comment]
If I understand @jschnasse correctly, we won't get rid of the repeated `655e`. Thus, +1 for the fix.

**Comment by jschnasse** [comment]
Puh. First entry is about the webpage that is archived. Second entry is about the archived webpage.
This seems to be wrong.

**Comment by acka47** [comment]
Just talked to @jschnasse on the phone. We decided to simply ignore all links in `655e` from the domain `edoweb-rlp.de` in the morph so that they don't get into the JSON at all.

The background: edoweb links in 655 basically are redundant as they are actually a resolved form of the URN link. Thus, having both URN and edoweb link in there is rather confusing.

**Comment by ChristophEwertowski** [comment]
The additional edoweb-URLs are removed, see [HT019248596 (test)](https://test.lobid.org/resources/HT019248596?format=json) / [HT019248596 (hbz01, MAB 655)](https://test.lobid.org/hbz01/HT019248596).

**Comment by acka47** [comment]
+1
