### ISSUE TITLE
Set up apache load balancer for seamless play deployment

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#510]
Instead of manually change the apache configs to point to the second play instance we could configure a load balancer as described at https://www.playframework.com/documentation/2.5.x/HTTPServer.

**Comment by dr0i** [comment]
Configured usage of a load balancer. As there is a bug in apache load balancer in conjunction of reverseProxy (adding a slash in Location Header when hitting a directory) it was not possible to also have our api documentation page load balanced. I don't consider this to be crucial, though. 
The api lookup of resources and items are now load balanced in a cluster, automatically switched from production (if unreachable) to stage (if reachable). And vice versa back.

**Comment by dr0i** [comment]
Besides the apache vhost configs ensure the following to enable load-balancer in apache2.4.10 on suse:
`a2enmod BalancerMember lbmethod_byrequests mod_proxy_balancer slotmem_shm`

(not sure  anymore if the slotmen is really needed).
Check if these modules are loaded with `apache2ctl -M ` . Interesting thing here is that the ` lbmethod_byrequest` module doesn't show up (a bug in suse/apache?), so the module must be added manually:

`echo "LoadModule slotmem_shm_module             /usr/lib64/apache2-prefork/mod_slotmem_shm.so" >> /etc/apache2/sysconfig.d/loadmodule.conf`

Then restart apache like `# apache2ctl graceful`.
LoadModule lbmethod_byrequests_module     /usr/lib64/apache2-prefork/mod_lbmethod_byrequests.so

**Comment by dr0i** [comment]
Deployed to production. You may want to test, anyway. Commits are at https://github.com/hbz/lobid-webserver/commits/master.

**Comment by fsteeg** [comment]
+1 and tested for deploying https://github.com/hbz/lobid-organisations/issues/370, closing.
