### ISSUE TITLE
Add ZDB-labels

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#511]
There are 1.8 million hits for a query with the label in `sameAs` (see http://lobid.org/resources/search?q=sameAs.label:%22http://ld.zdb-services.de/resource%22). They should be resolved like in `inCollection`.

**Comment by acka47** [comment]
I suggest using "ZDB-Ressource" instead of the generic link "http://ld.zdb-services.de/resource", analogous to "Culturegraph-Ressource. Or we leave it like it is and close the issue...
