### ISSUE TITLE
HT015462156 isn't displayed

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#512]
See http://lobid.org/resources/HT015462156. [hbz01](http://lobid.org/hbz01/HT015462156) / [json](http://lobid.org/resources/HT015462156.json)

**Comment by fsteeg** [comment]
Deployed to stage:

http://stage.lobid.org/resources/HT015462156 - no `id`, `numbering`
http://stage.lobid.org/resources/HT006117275 - has `id`, `numbering`

**Comment by ChristophEwertowski** [comment]
+1
