### ISSUE TITLE
Make URN and DOI clickable in HTML

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid-resources#515]
**1. URN example**
http://lobid.org/resources/HT019364129
**Is:**
urn:nbn:de:hbz:929:02-edoweb:70102114
**Should:**
https://nbn-resolving.org/urn:nbn:de:hbz:929:02-edoweb:70102114

**2. DOI example**
http://lobid.org/resources/HT018699585
**Is:**
doi is not displayed
**Should:**
https://dx.doi.org/10.6101/AZQ/000238

**Comment by fsteeg** [comment]
Deployed to production (not staged because we're currently working on our staging setup):

http://lobid.org/resources/HT019364129
http://lobid.org/resources/HT018699585

Assigning @jschnasse for review. If this is OK, you can simply close the issue.
