### ISSUE TITLE
Add work title for musical score

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#516]
Requested by @hagbeck via email on 2917-07-11:

> Uns ist aufgefallen, dass bei Notenwerken/Partituren der EST nicht mit
> in den lobid-Daten enthalten ist. Z.B fehlt bei HT004048199[1] der Titel
> "Rondos, Kl Orch KV 386". Dieser ist aber elementar wichtig (laut
> Fachreferenten und Musikexperten).
> 
> Wir stellen uns vor, dass der EST dann auch in einem explizit dafür
> vorgesehenen Feld abgelegt wird. Z.B. könnte das die 'unconstrained'
> Version von 'titleOfWork' (rdaw:P10088) sein: rdau:P60367 titleOfResource.
> 
> Wenn das o.ä nicht geht, hätten wir gerne den EST mindestens in
> 'alternativeTitle'. In Kombination mit 'type=PublishedScore' könnten wir
> dann diesen Fall kontrollieren.
> 
> [1] http://lobid.org/resources/HT004048199.json

For also adding this to `alternativeTitle` we would only have to add indicator `b` of `304`to [line 727 of the current morph](https://github.com/hbz/lobid-resources/blob/43d15180deaa5ddb2d1a09b1c8ad5dbe29ce7c67/src/main/resources/morph-hbz01-to-lobid.xml#L727). However, I don't think we should do it like this but rather implement the work title approach from https://github.com/lobid/lodmill/issues/784 for `304a|b`. This would result in the following JSON for the example:

```json
{
   "id":"http://lobid.org/resources/HT004048199#!",
   "title":"Konzert-Rondo A-Dur, KV 386",
   "exampleOfWork":{
      "type": "Work",
      "title":"Rondos, Kl Orch KV 386"
   }
}
```

Unfortunately, the ID for the corresponding GND work entry (http://d-nb.info/gnd/300110561) is missing in the source data , otherwise we would add it as `id` in the work object like this:

```json
{
   "id":"http://lobid.org/resources/HT004048199#!",
   "title":"Konzert-Rondo A-Dur, KV 386",
   "exampleOfWork":{
      "id": "http://d-nb.info/gnd/300110561",
      "type": "Work",
      "title":"Rondos, Kl Orch KV 386"
   }
}
```

We should probably look out for an example where the GND work ID is included...

**Comment by ChristophEwertowski** [comment]
Added EST for all resources, not just published scores. I took the title from `303.1.t` if there was an id in `303-1.9` but I couldn't prefer `304?1.a` over `303-1.t` (see [HT015509219 (test)](http://test.lobid.org/resources/HT015509219.json)). Multiple entries in MAB 303 are also covered, see: [HT018857620 (test)](http://test.lobid.org/resources/HT018857620.json). Since I don't know how to suppress the label which is generated automatically for each id, I also added labels for MAB 304s instead of titles.

**Comment by ChristophEwertowski** [comment]
Mrs. Blankenhagen told me that there shouldn't be a field 304 if there are 303 fields. The 303s originate from RDA entries. My proposal is to leave the data from crappy resources as long as it's feasible.

**Comment by acka47** [comment]
There is no record in the test set that only has content in `304` so I couldn't check this. However, giving my +1 and will check it afterwards.

I guess, people will also want the information from `303`, subfields `m`, `n` and `r`. We will need a follow-up ticket for this...

**Comment by acka47** [comment]
> Multiple entries in MAB 303 are also covered, see: [HT018857620 (test)](http://test.lobid.org/resources/HT018857620.json).

Wouldn't it make sense to use `hasPart` instead of `exampleOfWork` if there is more than one work title contained like we do in https://github.com/hbz/lobid/issues/287?

**Comment by dr0i** [comment]
Is this an open question? Will this ticket not be resolved by #539 ?

**Comment by acka47** [comment]
By now, we use `containsExampleOfWork`, both here ([example](http://test.lobid.org/resources/HT018857620.json)) and in https://github.com/hbz/lobid/issues/287 (the same example, which could mean the information will be duplicated there).

However, I just noticed that we use `creatorOfContainedWork` (for http://rdaregistry.info/Elements/w/P10065) and `titleOfContainedWork` (with property `http://purl.org/lobid/lv#titleOfContainedWork`) as JSON keys. We should remove the "contained" from both keys (i.e. using "creatorOfWork" and "titleOfWork") as the containment is already indicated with `containsExampleOfWork`.

Furthermore, instead of `lv:titleOfContainedWork` we should use http://rdaregistry.info/Elements/w/P10088

**Comment by ChristophEwertowski** [comment]
Did the changes in the branch of hbz/lobid#287 (see pull request https://github.com/hbz/lobid-resources/pull/550/files). There is only one example which has contents in MAB 303, 304 and 521. See http://test.lobid.org/resources/HT018857620.json.

**Comment by ChristophEwertowski** [comment]
When work title is in lobid jschnasse should be informed and table https://wolke.hbz-nrw.de/index.php/apps/onlyoffice/9522 updated.

**Comment by ChristophEwertowski** [comment]
About the first comment: MAB 304 only has subfield a. So GND-Ids can't be added. They could be added at 303_.

**Comment by dr0i** [comment]
This should be resolved with #567.
As there are other things to do, triggered by this resolving, I assign this issue to @ChristophEwertowski .

**Comment by ChristophEwertowski** [comment]
Deployed to test. `ind1="b"` wasn't covered. See [HT007847893 (MAB)](http://lobid.org/hbz01/HT007847893) / [HT007847893 (production, json)](http://lobid.org/resources/HT007847893.json) / [HT007847893 (test, json)](http://test.lobid.org/resources/HT007847893.json).

**Comment by acka47** [comment]
+1
