### ISSUE TITLE
Add new source for Raumsystematik (rpbr)

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#517]
At the moment URLs from the Raumsystematik of the "Rheinland-Pfälzische Bibliographie" aren't seperated from other entries of the Bibliography. Now the customer wants that the Raumsystematik in edoweb isn't shown. So we should add a new source so that in edoweb the other two sources ("Systematik der Rheinland-Pfälzischen Bibliographie" and the lbz-notation "RPB-Sachgruppen und Zusätze") are used and the Raumsystematik is ignored. According to the customer the notation of the Raumsystematik starts with "rpbr".
(Maybe we will also get the labels.)

**Comment by ChristophEwertowski** [comment]
A small collection of non-covered rpb-notations with example resources:
* http://lobid.org/resources/HT019319045: http://purl.org/lobid/rpb#nr_99_o317000000500_, http://purl.org/lobid/rpb#nr_99_o32000000_, http://purl.org/lobid/rpb#nr_99_o333_, http://purl.org/lobid/rpb#nr_99_o335, http://purl.org/lobid/rpb#nr_99_o336_, http://purl.org/lobid/rpb#nr_99_o340_

**Comment by acka47** [comment]
I propose to not add any IDs for the notation but only add them in the RDF as blank node with `skos:notation` and `source` information, like so:

```json
{
   "id":"http://lobid.org/resources/HT019319045#!",
   "subject":[
     {
         "notation":"nr_99_o317000000500_",
         "source":{
            "label":"RPB-Ortssystematik"
         }
      },
      {
         "notation":"nr_99_o336_",
         "source":{
            "label":"RPB-Ortssystematik"
         }
      },
      {
         "notation":"nr_99_o335_",
         "source":{
            "label":"RPB-Ortssystematik"
         }
      }
   ]
}
```

**Comment by acka47** [comment]
See also https://github.com/hbz/lobid-resources/issues/400 where we decided on a similar approach for DDC.

**Comment by ChristophEwertowski** [comment]
The customer agreed today on the notation approach for the `Raumsystematik`.

**Comment by ChristophEwertowski** [comment]
Now it's correct in the ntriples but elasticSearch doesn't get it.

**Comment by ChristophEwertowski** [comment]
Couldn't index the local branch to test because none of the configured nodes was available. Waiting until they are ready again. The checks are okay.

**Comment by ChristophEwertowski** [comment]
Tried to deploy the changes to test which didn't work as the changed resource [HT019149667](http://test.lobid.org/resources/HT019149667.json) isn't updated. It works within the branch, though. Locally the resource is reliably built in the right way.

**Comment by ChristophEwertowski** [comment]
The resource is deployed to test. See: http://test.lobid.org/resources/HT019149667.json.

**Comment by acka47** [comment]
+1
