### ISSUE TITLE
Missing "created" timestamp for articles

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#52]
We map mab `002a1.a` to `dct:created` describing the resources' metadata. Sometimes this is missing, like e.g.:

http://lobid.org/resource/HT015414894/about

It's of type `article` and has creation information about the superordinated resource, the journal, residing in mab `002b1.a`. Should we take this if `002a1.a` is missing?

**Comment by acka47** [comment]
I am not sure I understand this. 

This is the relevant part of the [source of the article](http://beta.lobid.org/hbz01/HT015414894):

```xml
<datafield tag="002" ind1="b" ind2="1">
  <subfield code="a">20080125</subfield>
</datafield>
```

As this is not `002a.1a` but `002b.1a` it doesn't get into the "created" field, right?

Now you say that in `002b.1a` one finds creation information about the superordinated resource. Wouldn't this mean that the date in `002b.1a` of the article should be identical with the date in `002a.1a` of the superordinated resource? Looking at the [source of the superordinated resource HT013384949](http://beta.lobid.org/hbz01/HT013384949) this is not the case:

```xml
<datafield tag="002" ind1="a" ind2="1">
<subfield code="a">20020701</subfield>
</datafield>
```

Thus, I think that `002b.1a` actually holds creation information of the article. So we _should_ take this for the "created" field.

**Comment by acka47** [comment]
BTW, is there a modification in article records in field 003 or is there a similar problem with that?

**Comment by dr0i** [comment]
> BTW, is there a modification in article records in field 003 or is there a similar problem with that?

Don't know.

**Comment by acka47** [comment]
Out of curiosity, I looked for an article with modification data. It seems that they work exactly like other resources. See [HT003477093](http://beta.lobid.org/hbz01/HT003477093) (snippet):

```xml
<datafield tag="003" ind1="-" ind2="1">
   <subfield code="a">20120308</subfield>
</datafield>
```

Thus, "dateModified" can be found both in API 1.0 and 2.0.

**Comment by acka47** [comment]
I think, there is nothing to review yet. Wondering why I was assigned the pull request. Reassigning both.

**Comment by dr0i** [comment]
Ok, thx for your investigation!
Deployed to staging, see http://lobid.org/resources-staging/HT015414894.

**Comment by acka47** [comment]
+1
