### ISSUE TITLE
Enable matching of multiple "coverage" values to Wikidata

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#520]
From https://github.com/hbz/lobid-resources/issues/130#issuecomment-315068388: 

> we don't take into account multiple values in the `coverage` field yet. See e.g. http://stage.lobid.org/resources/HT006934472.json which contains two values in `coverage`, "Düsseldorf <Nord>" and "Düsseldorf-Wittlaer". Although at least one of them has a separate wikidata entry ([Wittlaer](https://www.wikidata.org/wiki/Q881495)), "Düsseldorf" was added to the spatial field.

> We should take into account that `coverage` can contain multiple values and accordingly use `spatial` with an array. Each value of `coverage` should be mapped individually.

**Comment by dr0i** [comment]
Resolved by #575, closing.
