### ISSUE TITLE
Lesser NWBib resources in API 2.0 than in API 1.x

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#522]
In API 1.0, we currently have 393,856 entries in NWBib, see http://lobid.org/resource?set=NWBib&format=full & https://nwbib.de. In API 2.0 we have about 50 resources less (393,803) see http://lobid.org/resources/search?q=inCollection.id%3A%22http%3A%2F%2Flobid.org%2Fresources%2FHT014176012%23%21%22.

This is strange as the morph of both has the same criteria for including a resource in NWBib. 

From the [1.x morph, lines 1490-1492](https://github.com/lobid/lodmill/blob/master/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L1490-L1492):

```xml
<data source="078n[-1].a" name="http://purl.org/ontology/holding#collectedBy">
	<regexp match=".*" format="$[ns-lobid-resource]NWBib"/>
</data>
```

From the [current 2.0 morph, lines 2344 - 2346](https://github.com/hbz/lobid-resources/blob/43d15180deaa5ddb2d1a09b1c8ad5dbe29ce7c67/src/main/resources/morph-hbz01-to-lobid.xml#L2344-L2346):

```xml
<data source="078n[-1].a" name="http://purl.org/lobid/lv#inCollection">
	<regexp match=".*" format="$[ns-lobid-resource]HT014176012#!"/>
</data>
```

@dr0i told me that though some resources are still dropped when indexing, none of those is an NWBib resource. What then is the reason why there are NWBib resources missing in 2.0?

**Comment by acka47** [comment]
Here are the total numbers of resources:

- 1.x: 20,118,235 (see http://lobid.org/resource?q=*&format=full)
- 2.0 : 20,118,486 (see [http://lobid.org/resources/search?q=*](http://lobid.org/resources/search?q=*))

Here, we have ~250 resources more in 2.0 than in 1.x.

**Comment by dr0i** [comment]
This issue is similar to hbz/mabxml-elasticsearch#44. Also, as we don't sync Api1.0 that much anymore a comparison of Api 1.0 and Api 2.0 is now hard. As some dropped resources are back in API 2.0 with resolving #675 (see also #482) I think it's best to close this one.
Closing.
