### ISSUE TITLE
Subject wrongly typed as "Person"

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#524]
Reported by Mr. Greßhoff. In http://lobid.org/resources/HT007331917.json the subject "Droste-Hülshoff, Annette von: Die Judenbuche" is typed as Work and Person although it is only a Work.

**Comment by acka47** [comment]
Interesting error, because it doesn't seem to be a systematic problem. See http://lobid.org/resources/HT002984741.json that looks quite similar in the source.

Relevant source part for the buggy resource [HT007331917](http://lobid.org/hbz01/HT007331917):

```xml
<datafield tag="902" ind1="-" ind2="1">
  <subfield code="p">Droste-Hülshoff, Annette <<von>></subfield>
  <subfield code="d">1797-1848</subfield>
  <subfield code="t"><<Die>> Judenbuche</subfield>
  <subfield code="9">(DE-588)4113356-0</subfield>
</datafield>
```

Relevant source part for [HT002984741](http://lobid.org/hbz01/HT002984741):

```xml
<datafield tag="902" ind1="-" ind2="1">
<subfield code="p">Goethe, Johann Wolfgang <<von>></subfield>
<subfield code="d">1749-1832</subfield>
<subfield code="t"><<Die>> Leiden des jungen Werthers</subfield>
<subfield code="9">(DE-588)4099202-0</subfield>
</datafield>
```

Even with the same subject "Die Judenbuche" the problem doesn't always occur, see 


However, Greßhoff also pointed out another issue. We shouldn't add `birthDate` and `deathDate` from subfiled `d` when we are dealing with a work.

**Comment by ChristophEwertowski** [comment]
Additionally the Work has got `dateOfBirth` and `dateOfdeath` which only belong to persons.

**Comment by ChristophEwertowski** [comment]
The problem is located here: https://github.com/hbz/lobid-resources/blob/master/src/main/resources/morph-hbz01-to-lobid.xml#L283-L310. Although the comment states "subjects without ID" the definition doesn't include that. Neither do the other lines around it.

**Comment by ChristophEwertowski** [comment]
The difference between HT007331917 and HT009132474 originates in two persons in the same keyword chain in the first resource. Commenting out of [lines 1552-1557](https://github.com/hbz/lobid-resources/blob/master/src/main/resources/morph-hbz01-to-lobid.xml#L1552-1557) leads to the right results in referring to the types in the example resource but to wrong results in other resources.

See code snippet from branch 524:
```
<combine name="@preferredNameP" value="${a}" sameEntity="true">
	<data source="@subjectLinks"/>
	<data source="9[01234][27]-[-12].p" name="a">
		<replace pattern="&gt;&gt;" with=""/>
		<replace pattern="&lt;&lt;" with=""/>
	</data>
</combine>
<combine name="@preferredNameSemicolon" value="${a}: ${b}" sameEntity="true">
	<data source="@preferredNameP" name="a"/>
	<data source="9[01234][27]-[-12].t" name="b">
		<replace pattern="&gt;" with=""/>
		<replace pattern="&lt;" with=""/>
	</data>
</combine>
<combine name="http://www.w3.org/1999/02/22-rdf-syntax-ns#type" value="http://d-nb.info/standards/elementset/gnd#Person">
	<data source="@preferredNameForThePerson"/>
</combine>
<combine name="http://www.w3.org/1999/02/22-rdf-syntax-ns#type" value="http://d-nb.info/standards/elementset/gnd#Person" flushWith="@preferredNameP">
	<if>
		<none>
			<data source="@preferredNameSemicolon"/>
		</none>
	</if>
	<data source="@subjectPerson">
		<regexp match="^[^Familie].*"/>
	</data>
</combine>
```

**Comment by ChristophEwertowski** [comment]
@dr0i : Can you have a look at the morph ([branch](https://github.com/hbz/lobid-resources/tree/524-subjectWronglyTypedPerson) / [comparing site](https://github.com/hbz/lobid-resources/pull/525/files))? For example: Why is the type `Person` missing in HT014215912 if there is no subject field with the subfield `t` ([HT014215912 (hbz01)](http://lobid.org/hbz01/HT014215912))?

**Comment by ChristophEwertowski** [comment]
Person removed, see [HT007331917 (production)](http://lobid.org/resources/HT007331917.json) / [HT007331917 (test)](http://test.lobid.org/resources/HT007331917.json)

**Comment by acka47** [comment]
+1
