### ISSUE TITLE
Add possiblity to add language tags like in lobid authorities

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#527]
For #509 I need the possibility to add language tags like in lobid resources. E.g.:
```
{
   "translatedTitle":[
      {
         "en":"Population by sex, age, voivodship, district, town and commune"
      },
...
```
At the moment I can't do it in the morph. I suppose it can't be done like in lobid authorities so I'm assigning both of you.

**Comment by TobiasNx** [comment]
Relevant for ALMA? @acka47

**Comment by acka47** [comment]
This is a parallel issue to #509 and refers to the metafacture morph. As we don't do any further morph development after having started developing and using fix, I am closing this issue.
