### ISSUE TITLE
Use 100s.d for dateOfBirth and dateOfDeath

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#528]
At the moment we only use vital statistics from the subject fields (MAB 902-947). But these are also found in the fields for persons, see [HT018703339](http://lobid.org/resources/HT018703339?format=json) or [HT007843862](http://lobid.org/resources/HT007843862?format=json). The former resource contains contents in the form of `yyyy-`, the latter in the form of `yyyy-yyyy`.

**Comment by ChristophEwertowski** [comment]
Deployed to test. See [CT003012479 (production)](http://lobid.org/resources/CT003012479?format=json) / [CT003012479 (test)](http://test.lobid.org/resources/CT003012479?format=json). Added for every authorized form of writing (100, 104...)[-abcefmnp][12].9. But I also saw that contributors are also added for `ind2="3"` or `ind2="4"`. Why is it handled like this and should the fields `dateOfBirth` and `dateOfDeath` also be added in this case?

**Comment by acka47** [comment]
I remember that some contributors didn't want their birth dates shown in the lobid interface (although it is part of the GND data and everybody can see it anyway). See https://github.com/hbz/lobid/issues/244#issuecomment-144424771. So we should just add it to the JSON without updating the HTML view.

**Comment by acka47** [comment]
+1
