### ISSUE TITLE
Adding publication types "Statistics" and "Standards"

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#531]
An edoweb customer wants the publication types "Statistics" and "Standards". From the Jira ticket:

> Bitte Aleph 051 mn bzw. sn unter Publikationstyp "Leitlinien / Normschriften" zusammenfassen, 051 ms bzw. ss unter "Statistiken"

I have to think / read about the most precise English term. Of course we should type resources with other "Erscheinungsformen" also as the same type.

**Comment by acka47** [comment]
We already have `Standard` as type, see http://lobid.org/resources/search?q=type:Standard and [lines 615-620 of the current morph](https://github.com/hbz/lobid-resources/blob/70de741d310fa2e61ae558227259fef7fa400782/src/main/resources/morph-hbz01-to-lobid.xml#L615-L620).

**Comment by ChristophEwertowski** [comment]
Deployed to test, see [HT018722247 (json)](http://test.lobid.org/resources/HT018722247.json) (publication type "Statistic") and [HT019072754](http://test.lobid.org/resources/HT019072754.json) (publication type "Standard" which wasn't included in the set of example resources).
If it's deployed to production we should also add facets for `Statistic` and `Standard` (which now has [1412 resources](http://lobid.org/resources/search?t=standard)).

**Comment by ChristophEwertowski** [comment]
Updated to include [HT001039253 (json)](http://lobid.org/resources/HT001039253.json) instead of HT019072754. HT019072754 was a resource by the customer but didn't include `051..s` so I changed it manually.

**Comment by acka47** [comment]
As discussed offline, we will use the plural "Statistics".
