### ISSUE TITLE
Move content from 710 to subject array

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#536]
Currently these free subjects (resprctively subject heading from other authority files) are put into `subjectAltLabel`, see e.g. http://lobid.org/resources/TT002234459. In https://github.com/hbz/lobid-resources/issues/8#issuecomment-214744018 I wrote that it wouldn't make sense to put it into the subject array but that was before we had RSWK subjects seperated in that array with `componentList`. As we have this now we can just add the free text subjects from 710 like this:

```json
{
   "id":"http://lobid.org/resources/TT002234459#!",
   "subject":[
      {
         "id":"http://dewey.info/class/914/",
         "label":"Geografie Europas und Reisen in Europa",
         "source":{
            "id":"http://d-nb.info/gnd/4149423-4",
            "label":"Dewey-Dezimalklassifikation"
         }
      },
      {
         "label":"Wandern, Diez, Lahnstein, Rhein-Lahn-Info, Rhein, Lahn, Wirtschaftsförderung"
      },
      {
         "componentList":[
            {
               "id":"http://d-nb.info/gnd/4049787-2",
               "label":"Rhein-Lahn-Kreis",
               "source":{
                  "id":"http://d-nb.info/gnd/7749153-1",
                  "label":"Gemeinsame Normdatei (GND)"
               },
               "type":[
                  "PlaceOrGeographicName"
               ]
            },
            {
               "id":"http://d-nb.info/gnd/4114067-9",
               "label":"Jakobsweg",
               "source":{
                  "id":"http://d-nb.info/gnd/7749153-1",
                  "label":"Gemeinsame Normdatei (GND)"
               },
               "type":[
                  "PlaceOrGeographicName"
               ]
            },
            {
               "label":"Karte",
               "type":[
                  "SubjectHeading"
               ]
            }
         ],
         "type":[
            "ComplexSubject"
         ]
      }
   ]
}
```

@jschnasse, this would be opk for you like this, right?

Relevant part of the current morph is [lines 1796-1800](https://github.com/hbz/lobid-resources/blob/70de741d310fa2e61ae558227259fef7fa400782/src/main/resources/morph-hbz01-to-lobid.xml#L1796-L1800).

**Comment by ChristophEwertowski** [comment]
Added 710 and 711 to the subject array. See [TT002234042 (test, json)](http://test.lobid.org/resources/TT002234042?format=json) and [HT002824478 (test, json)](http://test.lobid.org/resources/HT002824478?format=json). Removed the splitting at "/" because the fields are called "Schlagwörter and Schlagwortketten" and in a keyword chain the order is important (see [TT002234042 (production)](https://lobid.org/resources/TT002234042.json) in comparison to the first example.
There are over >620.000 keywords which are typed as "MeSH". I wanted to add the source "https://viaf.org/viaf/305937419/" for the MeSH subjects but couldn't add them because of two subfields "a" per MAB field 711.

**Comment by acka47** [comment]
Looks good, except for the MeSH entries in 711. I suggest to only cover field 710 here and remove 711.

**Comment by ChristophEwertowski** [comment]
For changes see [TT002234042 (test, json)](http://test.lobid.org/resources/TT002234042.json). Because I couldn't find anything in our issues about why strings with "/" where splitted and `split` doesn't work in a `combine` as in a `data` element, I asked Mrs. Büning about it. She is okay with adding it this way.

**Comment by acka47** [comment]
The `/`s are probably used to make something like a subject chain. If we can easily replace the `/` by pipes (`|`), we should do it in order to have a consistent presentation of subject chains. 
 Also we should add a source shouldn't we? Maybe something like this?

```json
{
  "id":"http://lobid.org/resources/TT002234459#!",
  "subject":[
    {
      "label":"Wandern, Diez, Lahnstein, Rhein-Lahn-Info, Rhein, Lahn, Wirtschaftsförderung",
      "source":{
        "id":"http://www.wikidata.org/entity/Q18335415",
        "label":"Freie Verschlagwortung /  Tagging"
      }
    }
  ]
}
```

**Comment by ChristophEwertowski** [comment]
For added source and pipe symbol, see [TT002234042 (test, json)](http://test.lobid.org/resources/TT002234042.json).

**Comment by acka47** [comment]
Looks good, but I have to ask you to adjust `source` part:

1.  I just noticed that there is something wrong in Wikidata as the ID refers to a disambiguation page. I can not find a replacement (maybe you can? [Q494291](http://www.wikidata.org/entity/Q494291) does not seem to be a good fit) and suggest we just drop the ID.
2. While we are at it, I suggest to only use "Freie Verschlagwortung" as label without the tagging part.

**Comment by ChristophEwertowski** [comment]
Added a new Wikidata item, see https://www.wikidata.org/wiki/Q47524318. It's easier and leads to shorter code to use id's instead of blank nodes. Also adjusted the label, see [commit diff of TT002234858](https://github.com/hbz/lobid-resources/pull/554/files#diff-afdd18b612f790abe3a7492881e0645c).

**Comment by acka47** [comment]
+1
