### ISSUE TITLE
Get dateOfDeath if no dateOfBirth exists

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#553]
See [CT001004829 (hbz01)](http://lobid.org/hbz01/CT001004829) and [CT001004829 (json)](http://lobid.org/resources/CT001004829.json). For 900s and not merged 100s.

**Comment by ChristophEwertowski** [comment]
Will be resolved in #528. See [CT001004829 (production) (json)](http://lobid.org/resources/CT001004829?format=json) / [CT001004829 (test) (json)](http://test.lobid.org/resources/CT001004829?format=json).

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Resolved by #551, closing.
