### ISSUE TITLE
Add more subfields  to musical work information

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#556]
As written  in https://github.com/hbz/lobid-resources/issues/516#issuecomment-325655843:

> people will also want the information from `303`, subfields `m`, `n` and `r`.

https://github.com/lobid/lodmill/issues/784#issuecomment-184682023 has the cataloging help for 303. Here is the list of the subfields to add and which RDA properties to use:

- `m`: http://rdaregistry.info/Elements/w/P10220
- `n`: http://rdaregistry.info/Elements/w/P10079
- `p`: We might use http://rdaregistry.info/Elements/w/P10065 with this and the name string as content without creating a separate person object.
- `r`: http://rdaregistry.info/Elements/w/P10221
- `u`: Should be attached to the title with separator `,`

I think this should suffice for now.

**Comment by ChristophEwertowski** [comment]
If it's still relevant it should be tackled after https://github.com/lobid/lodmill/issues/784 is solved.

**Comment by ChristophEwertowski** [comment]
Deployed to test. See `hasMediumOfPerformance` in `exampleOfWork` in [HT018853619 (test, json)](http://test.lobid.org/resources/HT018853619.json) or in `containsExampleOfWork` in [HT018857620 (test, json)](http://test.lobid.org/resources/HT018857620.json). For `hasMusicalKey` or `hasNumericDesignationOfMusicalWork` also see [HT018857620 (test, json)](http://test.lobid.org/resources/HT018857620.json).
Subfields `u` und `p` are already covered.

**Comment by ChristophEwertowski** [comment]
Deployed to test, see http://test.lobid.org/resources/HT018857620.json.

**Comment by acka47** [comment]
+1
