### ISSUE TITLE
Add MAB 370 (Alternative Titel / Korrigierte Titel)

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#559]
Requested by customer. Jira-Ticket: https://jira.hbz-nrw.de/browse/FRL-267.

**Comment by ChristophEwertowski** [comment]
Deployed to test. See [HT003651380 (json, production)](http://lobid.org/resources/HT003651380.json) / [HT003651380 (json, test)](http://test.lobid.org/resources/HT003651380.json) / [HT003651380 (MAB)](http://lobid.org/hbz01/HT003651380).

**Comment by acka47** [comment]
+1
