### ISSUE TITLE
Transform 089 blank to RDF

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#56]
Example Hauptband [HT017708809](http://beta.lobid.org/hbz01/HT017708809):

``` xml
<controlfield tag="089">[Hauptband]</controlfield>
```

Example Anlageband [HT017708826](http://beta.lobid.org/hbz01/HT017708826):

``` xml
<controlfield tag="089">Anlagenband</controlfield>
```

**Comment by acka47** [comment]
The question is whether to concat this to "title" or add it as "numbering".

**Comment by ChristophEwertowski** [comment]
Will be solved by https://github.com/hbz/lobid-resources/pull/746/files.

**Comment by ChristophEwertowski** [comment]
Solved, see `numbering` and `title` at [HT003654516 (production, json)](http://lobid.org/resources/HT003654516.json) / [HT003654516 (MAB)](http://lobid.org/hbz01/HT003654516). Closing this issue.
