### ISSUE TITLE
Searching for ranges of years doesn't work as expected

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#562]
* [ ] At the moment we have a range query for publication dates (q=issued:year-year) which doesn't work like it should. For single fields you can search like this: http://lobid.org/resources/search?q=contribution.agent.dateOfDeath:[* TO 200]. This example only compares the first three digits and not the whole number. So resources from the 1900s are also included. 
* [ ] For negative numbers it doesn't work either: `http://test.lobid.org/resources/search?q=contribution.agent.dateOfDeath:[* TO 0000]` doesn't include the example with Pindaros who was born "-0522".

**Comment by fsteeg** [comment]
Pindarus does not actually have a negative dates even though he lived BC: http://lobid.org/resources/HT007847893.json, same in GND: http://lobid.org/gnd/118594427 (also at DNB: http://d-nb.info/gnd/118594427).

**Comment by ChristophEwertowski** [comment]
It's a data quality issue. [Plato (lobid-gnd)](http://lobid.org/gnd/118594893) for example, has the right living dates. Also in resources like [TT001308282 (MAB)](http://lobid.org/hbz01/TT001308282) in MAB field 902: 
```
<datafield tag="902" ind1="-" ind2="1">
   <subfield code="p">Plato</subfield>
   <subfield code="d">v427-v347</subfield>
   <subfield code="9">(DE-588)118594893</subfield>
</datafield>
```

The GND RDF/XML for Plato looks like this:
```
gndo:udkCode "500 - 401 v. Chr. " , "400 - 301 v. Chr. " ;
gndo:dateOfBirth "-0427"^^<http://www.w3.org/2001/XMLSchema#gYear> ;
gndo:dateOfDeath "-0347"^^<http://www.w3.org/2001/XMLSchema#gYear> .
```

For Sophokles it is different:
```
gndo:udkCode "500 - 401 v. Chr. " ;
gndo:dateOfBirth "0497"^^<http://www.w3.org/2001/XMLSchema#gYear> ;
gndo:dateOfDeath "0406"^^<http://www.w3.org/2001/XMLSchema#gYear> .
```

(Whatever `udkCode` is.) I will open a ticket at the DNB JIRA.

**Comment by ChristophEwertowski** [comment]
Assigning @acka47, as it is dependent on the GND JIRA issue.

**Comment by acka47** [comment]
> The GND RDF/XML for Plato looks like this:
```
gndo:udkCode "500 - 401 v. Chr. " , "400 - 301 v. Chr. " ;
gndo:dateOfBirth "-0427"^^<http://www.w3.org/2001/XMLSchema#gYear> ;
gndo:dateOfDeath "-0347"^^<http://www.w3.org/2001/XMLSchema#gYear> .
```

I just noted that, by now, the `dateOfBirth`/`dateOfDeath` statements are missing from Plato's GND entry, see https://d-nb.info/gnd/118594893/about/lds

**Comment by acka47** [comment]
DNB fixed the errors and implemented a quality check whether there are errors with birth data > death date. Removing the "upstream" label.

**Comment by TobiasNx** [comment]
Still relevant @acka47. Frontend issue?

**Comment by acka47** [comment]
Both issues with range queries still exist but the GND data has been improved. As this issue was raised intrnally five years ago and now actual API user has complained, I am closing this as Won't Fix. If anybody comes around with the same problem, we can reopen it.
