### ISSUE TITLE
Representing contained examples of works in RDF

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#567]
These are three tightly related issues that we should seek to implement a consistent solution for:

[Add work title for musical score (#516)](https://github.com/hbz/lobid-resources/issues/516)
[Add content information from field 521 for RDA records (lobid/#287)](https://github.com/hbz/lobid/issues/287)
[Add links to work entities for RDA records (lodmill/#784)](https://github.com/lobid/lodmill/issues/784)

Several inconsistencies keep on occurring regarding the implementation of those issues. To discuss a consistent solution, I create this super-issue. 

## Describing the work of which an example is included

As we don't have very much information about the included instance/manifestation, we decided to describe the included resources at the work level. Thinking about this again and taking another look at https://wiki.dnb.de/display/DINIAGKIM/Modellierung+Werk, I believe the best way to add the basic information is (note that the following is a hypothetical example to show the properties/keys used):

```json
{
  "@context": {
    "creatorOfWork": {
      "type": "@id",
      "@id": "http://rdaregistry.info/Elements/w/P10065"
    },
    "title": "http://purl.org/dc/terms/title",
    "Work": "http://id.loc.gov/ontologies/bibframe/Work",
    "id": "@id",
    "type": "@type"
  },
  "id": "http://d-nb.info/gnd/1081395184",
  "type": [ "Work" ],
  "title": "Don Carlo: 'Io I'ho perduta'",
  "creatorOfWork": "Giuseppe Verdi"
}
```

Note that:

1. We use http://rdaregistry.info/Elements/w/P10065 instead of the usual `contribution` approach. The reason is that we always deal with the "Creator" role here and always only have the name string and no person URI.
2. We use `title` as we use elsewhere. A specific property like `titleOfWork` isn't necessary as the type `Work` is indicated at the resource. (This also is the solution favoured in the DINI KIM context.)
3. We have to consider additional informationf rom subfields `m, n, r, u` for musical works, see #556.

## Linking the work included to the main resource

You should not link a work directly to an instance/manifestation by using `hasPart`. There are different possibilities of solving this.

### 1. Using existing vocabularies and an intermediary `Instance` bnode 

Solving this using existing properties like `dct:hastPart` or `bf:hasPart` would mean creating a bnode for the instance that is an example of the described work like this:

```json
{
  "@context": {
    "hasPart": {
      "type": "@id",
      "@id": "http://id.loc.gov/ontologies/bibframe/hasPart"
    },
    "exampleOfWork": {
      "@type": "@id",
      "@id": "http://schema.org/exampleOfWork"
    },
    "creatorOfWork": {
      "type": "@id",
      "@id": "http://rdaregistry.info/Elements/w/P10065"
    },
    "title": "http://purl.org/dc/terms/title",
    "Work": "http://id.loc.gov/ontologies/bibframe/Work",
    "id": "@id",
    "type": "@type"
  },
  "id" : "http://lobid.org/resources/HT018857620#!",
  "hasPart": [ {
    "type": [ "Instance" ],
    "exampleOfWork": {
      "id": "http://d-nb.info/gnd/1081395184",
      "type": [ "Work" ],
      "title": "Don Carlo: 'Io I'ho perduta'",
      "creatorOfWork": "Giuseppe Verdi"
    }
  } ]
}
```

### 2. Simplification using `containsExampleOfWork`

In our current solution we tried to simplify this by skipping the instance bnode replacing the property chain `hasPart`->`exampleOfWork` by the – newly created – property `containsExampleOfWork`:

```json
{
  "@context": {
    "containsExampleOfWork": {
      "type": "@id",
      "@id": "http://purl.org/lobid/lv#containsExampleOfWork"
    },
    "creatorOfWork": {
      "type": "@id",
      "@id": "http://rdaregistry.info/Elements/w/P10065"
    },
    "title": "http://purl.org/dc/terms/title",
    "Work": "http://id.loc.gov/ontologies/bibframe/Work",
    "id": "@id",
    "type": "@type"
  },
  "id" : "http://lobid.org/resources/HT018857620#!",
  "containsExampleOfWork": [ {
    "id": "http://d-nb.info/gnd/1081395184",
    "type": [ "Work" ],
    "title": "Don Carlo: 'Io I'ho perduta'",
    "creatorOfWork": "Giuseppe Verdi"
  } ]
}
```

I still think is makes sense to simplify the data like this but we might still want to discuss it. If we create and use `containsExampleOfWork` we should also add the following statements to the vocab:

```
[ ] rdfs:subPropertyOf lv:containsExampleOfWork ;
   owl:propertyChainAxiom (
   bf:hasPart
   bf:instanceOf
   ) .

[ ] rdfs:subPropertyOf lv:containsExampleOfWork ;
   owl:propertyChainAxiom (
   schema:hasPart
   schema:exampleOfWork
   ) .

```

**Comment by acka47** [comment]
To be honest, I don't have a clue what actually is the difference between `521` and `303`. Maybe there are cases where you can only use `521` but not `303` and the other way around. However, they will often be redundant and http://lobid.org/hbz01/HT018857620 is a good example as it has redundant information in both fields.

**Comment by ChristophEwertowski** [comment]
Looked at the MAB fields: 304 is only used in RAK, 521 in RDA and 303t in RAK and RDA.
Talked to Mrs. Blankenhagen about the MAB fields. 521 contains the titles which are in the resource and are determined by observation. These are no work titles! 303_ or 304 contain work titles of the resource and 303t contains work titles of the contained works.
