### ISSUE TITLE
Empty objects ({})

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#569]
With ee179af982327a7841539c312b3f98737e939321 it was revealed (by building the project (doing `mvn clean test -DgenerateTestData=true`)) that some resources had been given a superflous empty object for the `subject` field. See e.g. http://lobid.org/resources/HT018295975.json.

**Comment by fsteeg** [comment]
Same issue in `isPartOf` and `publication`, see http://lobid.org/resources/HT019582722.json

(came up in https://github.com/hbz/lobid-resources/issues/718, which I'll close as duplicate)

**Comment by ChristophEwertowski** [comment]
The problem of the empty `publication` and `isPartOf` objects consits of the use of the following entities which leads to multiple blank nodes: 
```
<macro name="createEntityForHasSuperordinateWithoutIdAndNumbering">
	<entity name="$[ns-lobid-vocab]isPartOf">
```
and `<entity name="http://schema.org/publication" flushWith="record">`. `publication` needs the flushing with the whole record and flushing the `isPartOf` entity with the existing MAB field 451 leads to a missing `hasSuperordinate`. As discussed, I'm assigning it dr0i, so it can be handled programatically. If these empty objects are dropped the code is much easier to read than if I'm creating and setting blank node "manually".
