### ISSUE TITLE
Indicate geo reference system

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#576]
Taken from https://github.com/hbz/lobid-resources/issues/130#issuecomment-332825370.

I don't think we should switch to GeoSPARQL but we should indicate the geo reference system otherwise.

We might indicate the reference model adding this to the context: `"Point": "http://www.w3.org/2003/01/geo/wgs84_pos#Point"` and the type information to the data:

```json
{
  "@id" : "http://lobid.org/resource/HT015579730",
  "dct:spatial" : {
    "type": "Location",
    "id": "http://www.wikidata.org/entity/Q365",
    "geo": {
      "type": [ "GeoCoordinates", "Point" ],
      "lat": 50.942222222222,
      "lon": 6.9577777777778
    },
    "label": "Köln"  
    }
}
```

The description of `http://www.w3.org/2003/01/geo/wgs84_pos#Point` isn't unambiguous, though: 
> A point, typically described using a coordinate system relative to Earth, such as WGS84

`http://www.w3.org/2003/01/geo/wgs84_pos#lat` and `http://www.w3.org/2003/01/geo/wgs84_pos#long` are unambiguous, though:

> The WGS84 latitude of a SpatialThing (decimal degrees).
> The WGS84 longitude of a SpatialThing (decimal degrees).

We could also use those (by updating the `@context`) instead of the schema.org stuff.

**Comment by acka47** [comment]
Even Wikidata does not mandate the use of qualifiers for geo coordinates but uses "WGS84" and "Earth" as default, see https://www.wikidata.org/wiki/Help:Data_type#Koordinate. (It is right that the reference system is not enough as you also need to know about which celestial body you are speaking.) By now, I think we should just keep it like it is and ignore the geo informatics' quibbles.

**Comment by TobiasNx** [comment]
Still relevant @acka47

**Comment by acka47** [comment]
> By now, I think we should just keep it like it is and ignore the geo informatics' quibbles.

This has been working fine until now so we can close this.
