### ISSUE TITLE
Show notation without an URL in frontend

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#578]
Requested by LBZ. See Raumnotation at subject (http://lobid.org/resources/HT019270766.json) and frontend (http://lobid.org/resources/HT019270766). @acka47: Should we show it at "Schlagwörter" or at something like "Notation"?

**Comment by acka47** [comment]
I am in favour of "Notation".

**Comment by ChristophEwertowski** [comment]
Assigning the ticket to @fsteeg. Please show the *Raumnotationen* in a new row in the frontend.

**Comment by fsteeg** [comment]
Is this about this single entry?

```
{
    "notation": "rpbr_99_o13708216_",
    "source": {
        "label": "RPB-Raumsystematik"
    }
}
```

**Comment by ChristophEwertowski** [comment]
For this example yes.

**Comment by dr0i** [comment]
As that frontend is not so much used. And  beacuse it will be addressed in context of the new RPB portal, this issue is closed.
