### ISSUE TITLE
List of holding institutions too cluttered

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#584]
People should get an easy overview when looking at a large list of holding institutions. Example http://lobid.org/resources/HT018641648:

![bestandsliste](https://user-images.githubusercontent.com/160292/31267538-c78dd0be-aa78-11e7-85b6-e8085af87c37.png)

Some thoughts on improving this:

- Remove one of the rows "Signatur" and "Verfügbarkeit". I think we don't necessarily need to link to the lobid-item entry. A link to the OPAC is more important.
- Improve the formatting so that it is easier to see where one list entry ends and another begins.
- A suggestion from NWBib customers was to cluster libraries by location. I think it would be enough to start with sorting the list by `alternateName` of the holding institutions (from lobid-organisations). Then also libraries from one locality would be together.

**Comment by dr0i** [comment]
No one uses this feature so much as to complain about it. Closed.
