### ISSUE TITLE
Improve regular expression for containedIn

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#590]
While working on #392 I recognised that `@dctIsPartOfHbzIdArticle`, which is used by `containedIn`, also takes the wrong indicator b into account. According to the "Feldhilfe" this indicator contains "ISSN formal falsch".
```
<data source="599[-b][-1].[a]" name="@dctIsPartOfHbzIdArticle">
	<regexp match="(.*)" format="$[ns-lobid-resource]${1}#!"/>
</data>
```

**Comment by ChristophEwertowski** [comment]
Deployed to test. See [BT000128754 (test, json)](http://test.lobid.org/resources/BT000128754.json). Correctly cataloged resources contain the identification number in MAB 599-, see definition of MAB-Kurzreferenz: `blank = Identifikationsnummer der selbstaendigen Schrift`.

**Comment by acka47** [comment]
+1
