### ISSUE TITLE
Dropped document because of object in subjectAltLabel

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#596]
There is an object embedded in the `subjectAltLabel` in HT019474284 which leads to a MapperParsingException which results in dropping the whole document:
>   **"subjectAltLabel" :** [
    "Osteoporosis", "Sarcopenia", "Congresses",
          {
          "id" : "https://id.nlm.nih.gov/mesh/D016423",
          "label" : "https://id.nlm.nih.gov/mesh"
           },
     "physiology", "Bone Development", "prevention & control", "Dietary Supplements", "diet therapy" ],

**Comment by acka47** [comment]
This would prbably be fixed by implementing #536, wouldn't it @ChristophEwertowski ? We already have a PR for this with some last changes to be made, see https://github.com/hbz/lobid-resources/issues/536#issuecomment-324000902. We should probably prioritize #536 if it really would fix this issue.

**Comment by ChristophEwertowski** [comment]
I didn't have it on my mind for #536 but it could be implemented along the way. Either we ignore the URLs or we give them a `source`. In the statistic file I made there is only one different MeSH-URL but this is because the script probably just takes the first entry of a subfield.

**Comment by dr0i** [comment]
Yup, solution was to put a regex into the morph to ignore htttp-URIS if they are in subfield `a`.
