### ISSUE TITLE
Word wrapping for subjects

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#598]
There is a special dewey label which is a bit too long for the box: Geografie Mitteleuropas und Reisen in Mitteleuropa    Geografie Deutschlands und Reisen in Deutschland. The problem is that it's present at 6.8 million resources ([query](http://lobid.org/resources/search?subject=Geografie+Mitteleuropas+und+Reisen+in+Mitteleuropa%C2%A0%C2%A0%C2%A0%C2%A0Geografie+Deutschlands+und+Reisen+in+Deutschland)) and part of it is sometimes hidden by the map, see http://lobid.org/resources/HT007007830.
[edit dr0i: ]  you should phrase the search:  http://lobid.org/resources/search?subject=%22Geografie+Mitteleuropas+und+Reisen+in+Mitteleuropa%C2%A0%C2%A0%C2%A0%C2%A0Geografie+Deutschlands+und+Reisen+in+Deutschland%22 . This results in ~70k hits.

**Comment by acka47** [comment]
We decided to correct the label in the lookup file we use for adding DDC labels in the transformation process.

**Comment by ChristophEwertowski** [comment]
Already adjusted on quaoar1 in folder "lobid-resources".

**Comment by ChristophEwertowski** [comment]
Forgot to open a pull request and therefore didn't assign it for review. You can see the change now at [HT017451384 (test, json)](http://test.lobid.org/resources/HT017451384.json).

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, see e.g. http://lobid.org/resources/HT007007830.
Closed.
