### ISSUE TITLE
Adjust context and morph to use new namespace for RDA properties

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#60]
Currently, we have seven properties from the namespace `http://rdvocab.info/Elements` in our data. These are deprecated since the new namespace `http://rdaregistry.info/Elements/u/` is used. Also, the property names differ. E.g. http://rdvocab.info/Elements/frequency now is http://rdaregistry.info/Elements/u/P60538. (Obviously, the proponents of non-natural property names have won. :sob: )

We will have to update

- [x] the morph
- [ ] the test files
- [ ] the context(s)

for these seven properties.

**Comment by acka47** [comment]
I looked up the new URIs or the seven properties:

http://rdvocab.info/Elements/otherTitleInformation => http://rdaregistry.info/Elements/u/P60493
http://rdvocab.info/Elements/longitudeAndLatitude => http://rdaregistry.info/Elements/u/P60345
http://rdvocab.info/Elements/placeOfPublication => http://rdaregistry.info/Elements/u/P60163
http://rdvocab.info/Elements/publicationStatement => http://rdaregistry.info/Elements/u/P60333
http://rdvocab.info/Elements/statementOfResponsibility => http://rdaregistry.info/Elements/u/P60339
http://rdvocab.info/Elements/frequency => http://rdaregistry.info/Elements/u/P60538

**Comment by acka47** [comment]
I adjusted the mprph in https://github.com/hbz/lobid-resources/commit/872a13cdc4d76bb63ec79d2631b94e16c725ad5b. Now I wonder where I can find and adjust the context document for lobid-resources 2.0?

**Comment by acka47** [comment]
As the context is generated with etikett, I guess I have to adjust https://github.com/hbz/lobid-rdf-to-json/blob/master/src/main/resources/context.json, right @jschnasse?

**Comment by jschnasse** [comment]
Yes I think, that is the way to go. The context controls the json output of the converter. The converter is very strict and will only add rdf-statements that are configured in the provided context. Intentionally there is no fallback, e.g. to generate json field names or use  blank uris for that.  
To make sure lobid provides proper rdf you have to host the modified context as well:  
http://lobid.org/download/contextTmp.json
http://lobid.org/download/contextTmp-staging.json

**Comment by jschnasse** [comment]
Yes I think, that is the way to go. The context controls the json output of the converter. The converter is very strict and will only add rdf-statements that are configured in the provided context. Intentionally there is no fallback, e.g. to generate json field names or use  blank uris for that.  
To make sure lobid provides proper rdf you have to host the modified context as well:  
http://lobid.org/download/contextTmp.json
http://lobid.org/download/contextTmp-staging.json

**Comment by acka47** [comment]
Things didn't work out as planned when I followed the instructions in the [readme](https://github.com/hbz/lobid-resources/blob/master/README.textile). @fsteeg and me will implement and deploy the changes together next week.

**Comment by fsteeg** [comment]
Will be deployed as part of full index build over the weekend.

**Comment by fsteeg** [comment]
Deployment as part of weekly full indexing failed, see https://github.com/hbz/lobid/issues/304

**Comment by fsteeg** [comment]
New index exists, but since the only external change is the context (see https://github.com/hbz/lobid-resources/pull/71#issuecomment-212441956), deploying this for data 2.0 only means updating the context at http://lobid.org/download/contextTmp.json.

Since he's the only consumer of the context and its resulting triples, will deploy after +1 by @jschnasse.

**Comment by jschnasse** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See: http://lobid.org/download/contextTmp.json
