### ISSUE TITLE
spatial.geo should be type: geo_point

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#601]
To support geo searches from NWBib, the `spatial.geo` field needs to be `type: geo_point`.

See https://www.elastic.co/guide/en/elasticsearch/reference/2.4/geo-point.html

The current data however is not compatible due to its additional `type` field:

```
spatial": [{
        "geo": {
            "lon": 6.36889,
            "type": "GeoCoordinates",
            "lat": 50.9839
        },
        "id": "http://www.wikidata.org/entity/Q1959200",
        "label": "Müntz (Titz)",
        "type": "Location"
}]
```

With `type: geo_point` I get:

`[error] application - Bulk item response failed for index 'resources', ID 'BT000041593', message: MapperParsingException[failed to parse]; nested: ElasticsearchParseException[field must be either [lat], [lon] or [geohash]];`

I see three options.

In API 1.x, we had a simple string field, so this would be most straight-forward to adopt for clients:

```
spatial": [{
        "geo": "50.9839,6.36889",
        "id": "http://www.wikidata.org/entity/Q1959200",
        "label": "Müntz (Titz)",
        "type": "Location"
}]
```

This would be a API change, but the geo stuff has not been on production for long, and has not been officially announced or documented, so I think we could do this change.

Another option is to just remove the type field:

```
spatial": [{
        "geo": {
            "lon": 6.36889,
            "lat": 50.9839
        },
        "id": "http://www.wikidata.org/entity/Q1959200",
        "label": "Müntz (Titz)",
        "type": "Location"
}]
```

And finally, we could add an additional simple field (if we need the `GeoCoordinates` info):

```
spatial": [{
        "geo": {
            "lon": 6.36889,
            "type": "GeoCoordinates",
            "lat": 50.9839
        },
        "point":  "50.9839,6.36889",
        "id": "http://www.wikidata.org/entity/Q1959200",
        "label": "Müntz (Titz)",
        "type": "Location"
}]
```

I like the first option best. @acka47 @dr0i what do you think?

**Comment by dr0i** [comment]
Keep it simple - I support your suggestion.

**Comment by acka47** [comment]
I think we should be consistent across the different services. This emans we should use the second option as in lobid-organisations.

**Comment by fsteeg** [comment]
Consistency is a good point. Plus it's a compatible change. And should be easy to do on the data side (remove `type` field, and update the geo mapping to `"geo" : { "type": "geo_point" }`). On the client side I'd have to change things a bit, but I think it's worth to try.

@dr0i could you get this into the staging index that's built tonight, is that realistic?

**Comment by dr0i** [comment]
Yes, this can be easily done.
