### ISSUE TITLE
Medium disappeared

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#605]
The `medium` labels and facetting option disappeared. See for example: http://lobid.org/resources/HT011128999.

**Comment by fsteeg** [comment]
Deployed to stage:

http://stage.lobid.org/resources/HT011128999
http://stage.lobid.org/resources/search

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
+1
