### ISSUE TITLE
Work has living statistics

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#606]
At [HT015090208](http://lobid.org/resources/HT015090208.json) there is a subject which is a work which also has living statistics attached to it.

**Comment by fsteeg** [comment]
Seems to be fixed in the meantime: http://lobid.org/resources/HT015090208.json

**Comment by ChristophEwertowski** [comment]
Ah, yes, I remember a ticket with Mrs. Droste-Hülshoff where I corrected it. Closing this issue.
