### ISSUE TITLE
Play error for several resources

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#607]
Examples:

- http://lobid.org/resources/HT019478435 ([JSON](http://lobid.org/resources/HT019478435.json))
- http://lobid.org/resources/HT019440462 ([JSON](http://lobid.org/resources/HT019440462.json))
- http://lobid.org/resources/HT019478435 ([JSON](http://lobid.org/resources/HT019478435.json))

I coudn't directly find the reason for this.

**Comment by acka47** [comment]
Here are two more:

http://lobid.org/resources/HT019438890
http://lobid.org/resources/HT019338868

All of them have "Herausgeber/in" but on the other hand there are resources with "Herausgeber/in" that work, e.g. http://lobid.org/resources/HT019339215

**Comment by fsteeg** [comment]
Fixed on stage:

http://stage.lobid.org/resources/HT019478435
http://stage.lobid.org/resources/HT019440462
http://stage.lobid.org/resources/HT019438890
http://stage.lobid.org/resources/HT019338868

The issue was caused by agents without IDs.

**Comment by acka47** [comment]
+1
