### ISSUE TITLE
geo, lat, lon missing in JSON-LD context

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#616]

**Comment by dr0i** [comment]
... whilst we have two "longitudeAndLatitude" entries.

**Comment by acka47** [comment]
> ... whilst we have two "longitudeAndLatitude" entries.

Ok, I will remove one of those. (These are used for the geo coordinates for GND resources I think.)

**Comment by dr0i** [comment]
See  'http://lobid.org/resources/context.jsonld', closed.
