### ISSUE TITLE
Improve SPARQL query for getting administrative areas in NRW

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#622]
Currently, we use something like this for building the geo index, respectively for creating the classification at https://test.nwbib.de/classification?t=Wikidata: http://tinyurl.com/y8rpexfm

- This queries for things that are sub*classes of wd:Q387917 (Verwaltungseinheit in Deutschland) and are locatedIn* NRW.
- It also queries for things that are geographic regions, e.g.  Münsterland, Südwestfalen etc.

We could improve this:
- The geographic regions bit could be removed imo.
- We might rather use a union query for filtering the types using the following:
   - [Q22721](https://www.wikidata.org/wiki/Q22721): Regierungsbezirk
   - [Q106658](https://www.wikidata.org/wiki/Q106658): Landkreis in Deutschland
   - [Q22865](https://www.wikidata.org/wiki/Q22865): kreisfreie Stadt in Deutschland
   - ~[Q515](https://www.wikidata.org/wiki/Q515): Stadt (Maybe we even don't need this.)~
   - [Q262166](https://www.wikidata.org/wiki/Q262166): Gemeinde in Deutschland
   - [Q253019](https://www.wikidata.org/wiki/Q253019): Ortsteil

**Comment by acka47** [comment]
Here is the query as described above: http://tinyurl.com/ya4kzm8l 

@fsteeg Please try this out for creating the classification. Just comment out lines 20-21 for creating the classification. There should be far less entries under "Sonstiges" with this query.

**Comment by acka47** [comment]
for the geocache, we will have to comment out lines 22-23.

**Comment by dr0i** [comment]
@acka47 the SPARQL-query wasn't allowed to have comments in it. With the new PR it does. Also updated the query.

**Comment by dr0i** [comment]
@acka47 resources with new geo-data in production now. Do you have any ID to test this? Geo-cache seems to be all right, at least ~130 entries less.

**Comment by acka47** [comment]
Looks good in general, I updated the numbers in https://github.com/hbz/nwbib/wiki/Wikidata-Matchingverfahren#abdeckung. As soon as you have updated http://stats.lobid.org/scoreCoverageCsv_alleWerte.csv I can create another overview.

However, we have a systematic mismatch problem with Kreis/Landkreis. Generally, the town is taken as match that has the same name as the Kreis (e.g. Euskrichen for "Kreis Euskirchen"). A good example is http://lobid.org/resources/HT013863573.json. This makes sense as both "label" and "locatedIn" match the query string (for example "Kreis Euskirchen"):

```json
{
  "spatial":{
    "type":"Location",
    "id":"http://www.wikidata.org/entity/Q4074",
    "label":"Euskirchen",
    "geo":{
      "lat":50.659722222222,
      "lon":6.7916666666667
    }
  },
  "locatedIn":{
    "language":"de",
    "value":"Kreis Euskirchen"
  }
}
```

How should we handle this? It might make sense to create a manual matching list that is preferred over the result of querying the query index...

**Comment by acka47** [comment]
Clsoing this one as the new SPARQL query works. Made an issue for the "Kreis" problem at #627 .
