### ISSUE TITLE
Fix matchings based on notation 

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#627]
From https://github.com/hbz/lobid-resources/issues/622#issuecomment-345963369:

>[W]e have a systematic mismatch problem with Kreis/Landkreis. Generally, the town is taken as match that has the same name as the Kreis (e.g. Euskrichen for "Kreis Euskirchen"). A good example is http://lobid.org/resources/HT013863573.json. This makes sense as both "label" and "locatedIn" match the query string (for example "Kreis Euskirchen"):

```json
{
  "spatial":{
    "type":"Location",
    "id":"http://www.wikidata.org/entity/Q4074",
    "label":"Euskirchen",
    "geo":{
      "lat":50.659722222222,
      "lon":6.7916666666667
    }
  },
  "locatedIn":{
    "language":"de",
    "value":"Kreis Euskirchen"
  }
}
```

We have to find a way to deal with this.

**Comment by acka47** [comment]
I guess this also holds for Regierungsbezirke, as soon as we will have them back in the geo cache with #631.

**Comment by dr0i** [comment]
#631 is closed, so this issue can be worked on again.

**Comment by dr0i** [comment]
With #643 some of the `Kreis`-issues are resolved, see e.g. [Kreis Euskirchen](http://lobid.org/resources/HT013863573.json). Some remain, e.g. [Kreis Höxter](http://lobid.org/resources/BT000117093.json).

**Comment by acka47** [comment]
I think we could improve the matching results significantly if we matched the strings from each notation separately. Here are the different notations with strings:

- 99: Städte, Kreisfreie Städte, Gemeinden, Ortsteile plus teilweise Stadtbezirke und (leider auch andere wie z.B. Klöster etc.)
- 97: (Land)Kreise
- 96: Regierungsbezirke
- 74: Kleinere weltliche Territorien in Westfalen
- 72: Kleinere geistliche Territorien in Westfalen
- 54: Kleinere weltliche Territorien im Rheinland
- 52: Kleinere geistliche Territorien im Rheinland
- 37: Katholische Kirche. Dekanate
- 36: Katholische Kirche. Diözesen
- 35: Evangelische Kirche. Kirchenkreise
- 28: Eifel
- 24: Niederrhein-Gebiet
- 14: Sauerland
- 12: Weserbergland
- 10: Westfälische Bucht

As this issue makes clear, we already have problems to separate districts and localities in them so it would make sense to spearate their matchings. For this we need two things:

1. A way to separate the different strings in the JSON
2. Create a different Wikidata subset for the different types of strings to match them to

# Proposal

- We – temporarily – add different fields to our JSON-LD like `coverage_99`,`coverage_97` etc. and fill them with the respective strings. We could also do this in a non-production system if possible only for the NWBib subset
- We add the type to the wikidata entites in the geo index, e.g.:
```json
{
  "spatial":{
    "type": ["Location", "https://www.wikidata.org/wiki/Q15632166"],
    "id":"http://www.wikidata.org/entity/Q897382",
    "label":"Ehrenfeld",
    "geo":{
      "lat":50.9464,
      "lon":6.91833
    }
  },
  "aliases":[
    {
      "language":"de",
      "value":"Köln/Ehrenfeld"
    },
    {
      "language":"de",
      "value":"Köln-Ehrenfeld"
    }
  ],
  "locatedIn":{
    "language":"de",
    "value":"Köln-Ehrenfeld"
  }
}
```

**Comment by acka47** [comment]
I would like to start working on this. So we need to sort out how to exactly proceed. Summing up what we need for better lookups and rating the lookup quality:

0. We need to a) expand the Wikidata geo index to also cover non-administrative entities and b) to add the type information to each entity.
1. Geo lookup queries have to be modified so that only wikidata entities of a specific type are queried depending on the 700n notation the GSW (=name string of locations covered by a resource) is from, e.g. 97 against type http://www.wikidata.org/entity/Q106658
2. In the JSON-LD we need information for each GSW on which notation it is associated with so that we can check the quality of the matching. This should best be done by having a temporal key for each notation, e.g. `"coverage_99"`, `"coverage_97"` etc.

One important question re. the implementation is: Will we add temporal keys to our production system or will we set up a separate – NWBib-only – system?

**Comment by acka47** [comment]
We decided on the following process:

1. 
   1. Add all GSW to the coverage field with a marker for the notation it is associated with, e.g. "Köln | 99".
   2. Adjust the Wikidatas SPARQL Query and add type info to geo index.
2. Finalize the matching
3. Update 700n1.b in the union catalogue with  the QIDs and labels retrieved from the matching
4. Adjust NWBib cataloging practice to use notation in subfield ad and QIDs plus label in subfield b.

I will create sub-issues for the different steps.

**Comment by acka47** [comment]
When #764 is deployed we can start with adding the type to the index and improving the mapping.

**Comment by dr0i** [comment]
@acka47 you mean when #805 is deployed, right?

**Comment by acka47** [comment]
Yes, #805

**Comment by dr0i** [comment]
Made a check-list and provided some more steps there.

**Comment by dr0i** [comment]
Deployed to production. Assigning @acka47 to check how/if the last merged PR has done anything good.

**Comment by dr0i** [comment]
@acka47 done

**Comment by acka47** [comment]
*Coverage* is very good, [292,236](http://lobid.org/resources/search?q=inCollection.id%3A%22http%3A%2F%2Flobid.org%2Fresources%2FHT014176012%23%21%22+AND+coverage%3A%2899+OR+97+OR+96+OR+36+OR+35%29+AND+_exists_%3Aspatial) of [293,948 resources with notations 99, 97, 96,36, 35) and a GSW](http://lobid.org/resources/search?q=inCollection.id%3A%22http%3A%2F%2Flobid.org%2Fresources%2FHT014176012%23%21%22+AND+coverage%3A%2899+OR+97+OR+96+OR+36+OR+35%29) now have a link to wikidata which means **99,4%**.

**Quality**

Regarding the original issue of *Landkreise*, the results look very good. Here are some examples:
- ["Kreis Euskirchen"](http://lobid.org/resources/HT013863573.json) ("Kreis Schleiden" will also be matched correctly in future updates as it is only since today covered by the SPARQL query)
- ["Rhein-Kreis Neuss"](http://lobid.org/resources/HT019152628.json)
-  ["Kreis Olpe"](http://lobid.org/resources/HT019363863.json)
- ["Kreis Grevenbroich"])(http://lobid.org/resources/HT017058681.json)

Note: There are lots of Prussian "Kreise" that are not covered (yet) by the SPARQL query. I added them to [the wiki page](https://github.com/hbz/nwbib/wiki/Wikidata-Matchingverfahren#historische-einheit-aus-preu%C3%9Fen).

Regarding "Regierungsbezirke, the matching also looks very good. I will continue the evaluation on Wednesday.

**Comment by acka47** [comment]
Another strange thing is that ["Bielefeld Bethel"](http://lobid.org/resources/search?q=coverage%3A%28bielefeld+AND+bethel%29) is matched with [Q1490832](https://www.wikidata.org/wiki/Q1490832) (Gadderbaum) and not [Q23559794](https://www.wikidata.org/wiki/Q23559794) (Bethel). Why?

**Comment by acka47** [comment]
However, generally the matching is very good. I could only find some incorrect matchings from score 59 downwards but I think we should only make a cut at a score of 20 (which would remove the matching for 34 strings).

**Comment by ChristophEwertowski** [comment]
About Bethel: Gadderbaum contains the alternative label "Bielefeld-Bethel". 

Also there is an error in the Wikidata sets. Bethel is a quarter within the *Stadtbezirk* Gadderbaum (see [map](https://de.wikipedia.org/wiki/Datei:Stadtteil_Bethel_in_Bielefeld.svg)). In Wikidata both are typed as [quarter](https://www.wikidata.org/wiki/Q253019), while Gadderbaum should be a [Stadtbezirk](https://www.wikidata.org/wiki/Q2740635).

**Comment by acka47** [comment]
Thanks for the hint, @ChristophEwertowski . I removed the variant label and changed the type for Gadderbaum.

**Comment by dr0i** [comment]
> As Q4181 is not typed as Q106658 (Kreis) it should not even be considered as a match

The notation query-addendum is of type "should", not "must". We could change this, but if wikidata-resources don't have a type at all it these would be dropped.

"Gummersbach Kreis" is mapped to Q4181 because it has  `"label" : "Gummersbach"` and ` "locatedIn" : { "value" : "Oberbergischer Kreis"`. Thus it got a score of 51.

**Comment by acka47** [comment]
> The notation query-addendum is of type "should", not "must". We could change this, but if wikidata-resources don't have a type at all it these would be dropped.

I think we should change it. All wikidata resources have one of the types as this is how the SPARQL query works.

**Comment by dr0i** [comment]
Note, though, it seems that "Kreis Gummersbach" don't has an entry in wikidata, only a Prussian one: https://www.wikidata.org/wiki/Q1787322. So this is left without a spatial entry when doing next full etl.

**Comment by acka47** [comment]
> Just added the "instanceOf:Q106658 (Kreis) " to Q1787322. Is this the normal doing @acka47 ?

I do this when it actually is a Landkreis in Deutschland. As the Kreis stopped existing in 1932 and Q106658  refers to Kreise in Germany after 1949 it is not correct. Thus, removed the type.

There are more prussian Kreise in the  coverage field, see https://github.com/hbz/nwbib/wiki/Wikidata-Matchingverfahren#historische-einheit-aus-preu%C3%9Fen. We will have decide how to deal with those. It is probably the best to add Q5283531 (Landkreis in Preußen) to the SPARQL query and make sure that all Kreise we need have a P131 link (liegt in der Verwaltungseinheit) to a Regierungsbezirk as the Regierungsbezirke are entities that exist in Prussia and Germany...

**Comment by dr0i** [comment]
After making the type mandatory it seems to work , e.g. http://stage.lobid.org/resources/BT000110465.json now has no spatial entry at all.

**Comment by acka47** [comment]
Yes, please merge. Have you also set a threshold for the matching score?

**Comment by dr0i** [comment]
Re threshold: No I wouldn't know to what I should set it. I only did https://github.com/hbz/lobid-resources/pull/824/files.

**Comment by dr0i** [comment]
@acka if you could close this we can close #585 too.

**Comment by acka47** [comment]
I don't find the time to pick this issue up. There is still an open question I have to work on, see https://github.com/hbz/lobid-resources/issues/627#issuecomment-386552994:

> There are more prussian Kreise in the  coverage field, see https://github.com/hbz/nwbib/wiki/Wikidata-Matchingverfahren#historische-einheit-aus-preu%C3%9Fen. We will have decide how to deal with those. It is probably the best to add Q5283531 (Landkreis in Preußen) to the SPARQL query and make sure that all Kreise we need have a P131 link (liegt in der Verwaltungseinheit) to a Regierungsbezirk as the Regierungsbezirke are entities that exist in Prussia and Germany...

I hope to find the time after Bibtag.

**Comment by acka47** [comment]
See this SPARQL query with "In NRW gelegene Landkreise in Preußen und deren übergeordnete administrative Einheit ": http://tinyurl.com/y9y3sxoz

**Comment by acka47** [comment]
All "Landkreise in Preußen" that are located in NRW have a current Regierungsbezirk as superordinated administrative area (often besides another like "Rheinprovinz" etc.), see http://tinyurl.com/yagzw9q4. So we basically can fetch them and also place them in our hierarchy.

**Comment by acka47** [comment]
Closing this one.
