### ISSUE TITLE
Example for "Serienband" is typed as "article"

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#628]
At http://lobid.org/resources/api the example for "Serienband" isn't typed as one. Either find the error or search for a new example.

**Comment by ChristophEwertowski** [comment]
The error was built in between creating of the help page and November 2017. However, with consulting a collegue we replaced MAB051at (unselbstständig erschienenes Werk, Aufsatz) with MAB051ah (unselbstständig erschienenes Werk, Biographie). According to the *Formschlagwort* and to the tableOfContents it is a `Biography`. So after the next MAB update it should be correct.

**Comment by ChristophEwertowski** [comment]
There is another error in the code: 
```
<data source="051." name="@article">
	<regexp match="^a|^.t|^..t|^...t|^.....t" format="$[ns-bibo]Article"/>
</data>
```
Not every "unselbstständiges Werk" is an `Article` but every work which doesn't have it's own title like in this case a volume of a work in a series.

**Comment by ChristophEwertowski** [comment]
Deployed to test. See [HT005944358 (test, json)](http://test.lobid.org/resources/HT005944358.json). It's an example like on our help / API description page. Every resource with a volume / numbering statement is typed as `Book`. Other examples:

* [BT000003404 (production, json)](http://lobid.org/resources/BT000003404.json) / [BT000003404 (test, json)](http://test.lobid.org/resources/BT000003404.json) (map in a collection of maps). Other examples:
* [HT013577568 (test, json)](http://test.lobid.org/resources/HT013577568.json): Part of a volume. Not exactly an `Article` because it didn't appear in a journal. In German it is called "Beitrag" (for example in the [bibliography of the RUB](https://bibliographie.ub.rub.de/search?q=&core=hb2)) but also could be named chapter.
* [HT013925945 (test, json)](http://test.lobid.org/resources/HT013925945.json): Article which isn't typed as such (missing t in MAB 051).
* [HT016608165 (test, json)](http://test.lobid.org/resources/HT016608165.json): Part of a music CD, should be "Musikalia".

I will open a different tickets for how to get the correct types of the non-dealt-with resources.

**Comment by acka47** [comment]
- HT005944358 is a special and rare case: Titled "Zeitschrift für romanische Philologie, 95", obviously is an issue of a journal. Thus, the ideal type would be `bibo:Issue`. We already have an issue for this at https://github.com/hbz/lobid-resources/issues/123.
- Re. BT000003404, as discussed in #703  the resource would probably look better when we moved `Map` from `medium` to `type`.
- HT013577568: I think it is ok and valuable to type contributions/chapters in an edited volume as "Article". You are right that they are commonly called "chapters" or "contributions" (see e.g. the wikipedia entry ["Edited Volume"](https://en.wikipedia.org/wiki/Edited_volume)), however I easily did find some examples where they are called "Articles", see e.g. [here](http://libguides.gwumc.edu/c.php?g=27779&p=170363) and [here)(http://www.philosophie.phil.uni-erlangen.de/lehrstuehle/lehrstuhlIII/mayr-publications.pdf).
- HT016608165 is actually a music CD that is part of a 3 CD collection ([HT016607985](http://lobid.org/resources/HT016607985#!)). )"Musikalia" are only published scores and no audio-visual media, so this is correct.)

**Comment by ChristophEwertowski** [comment]
1. I added a journal issue and gave it the type http://schema.org/PublicationIssue according to the content of MAB 089/090 (volume / issue statement), namely "Heft" (see [HT009706034 (test, json)](http://test.lobid.org/resources/HT009706034.json)). Since bibo is down and noone reacts in the bibo repository it seems the better choice. The above [HT005944358 (production)](http://lobid.org/resources/HT009706034) seems to be a volume of issues which were bundled together in hardcover but didn't appear originally in this form so I would stick to type `Book`.
2. Handled at https://github.com/hbz/lobid-resources/issues/705.
3. and 4.: I agree / understand.

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
We will need a label and an icon for "PublicationIssue"
