### ISSUE TITLE
Add MAB 524a ("ISSN der Vorlage")

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#637]
edoweb customers want MAB 524a in edoweb. According to them it contains the "ISSN der Vorlage". When lobid is updated inform jschnasse and update the [table in the hbz Wolke](https://wolke.hbz-nrw.de/index.php/apps/onlyoffice/9522).

**Comment by ChristophEwertowski** [comment]
In the "Online-Kurzreferenz" of the DNB MAB 524 is called "Hinweise auf unselbstständige Werke" and no subfield a is mentioned. MAB 542 contains "Internationale Standardnummer für fortlaufende Werke (ISSN)". Will ask the edoweb people if it's simply a mistake.

**Comment by ChristophEwertowski** [comment]
@acka47 : Do we really want contents from MAB `542b` ("ISSN formal falsch") in our ISSN field?

**Comment by ChristophEwertowski** [comment]
The wished for MAB field was in fact MAB 542 which we already have in lobid-resources.

**Comment by acka47** [comment]
So can we close this issue?

**Comment by ChristophEwertowski** [comment]
Yep.
