### ISSUE TITLE
Add MAB 375e ("Früherer Haupttitel")

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#638]
For edoweb customers. Inform jschnasse after integration and update the [table at hbz Wolke](https://wolke.hbz-nrw.de/index.php/apps/onlyoffice/9522).

**Comment by ChristophEwertowski** [comment]
Examples from the test set:
* [HT012996101 (MAB)](http://lobid.org/hbz01/HT012996101)

Wrongly cataloged:
* [HT014555885](http://lobid.org/hbz01/HT014555885) contains no title at all
* [HT005944358 (MAB)](http://lobid.org/hbz01/HT005944358) contains MAB 375 but contains a later additional title not a. Wrongly cataloged.
* [HT018138676 (MAB)](http://lobid.org/hbz01/HT018138676) contains multiple additional titles.

**Comment by ChristophEwertowski** [comment]
From the RDA toolkit: `Ein früherer Haupttitel ist ein Haupttitel, der in einer früheren Ausgabe einer fortlaufenden Ressource erscheint und der von dem Haupttitel in der spätesten Ausgabe geringfügig abweicht.` So I would assign it to `dct:alternative`. 
From the hbz the question was raised for what cause the edoweb customer the fields for periodicals need. Before this question is answered I won't tackle this ticket.

**Comment by ChristophEwertowski** [comment]
Deployed to test. See [HT005944358 (production, json)](http://lobid.org/resources/HT005944358.json) / [HT005944358 (test, json)](http://test.lobid.org/resources/HT005944358.json) or [HT012996101 (production, json)](http://lobid.org/resources/HT012996101.json) / [HT012996101 (test, json)](http://test.lobid.org/resources/HT012996101.json).

**Comment by acka47** [comment]
+1
