### ISSUE TITLE
Some item URIs don't resolve

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#640]
Reported via email today by @Martin-de-la-Iglesia.

For example the resource [HT017412936](http://lobid.org/resources/HT017412936.json). There are several item link that resolve, e.g. http://lobid.org/items/HT017412936:DE-929:Freihand%20530%20=%20T%204533#!. But there is at least one that doesn't resolve: http://lobid.org/items/HT017412936:DE-361:NA088.88-4442721#!

**Comment by dr0i** [comment]
Direct ID-querying works: `curl -XGET 'http://gaia.hbz-nrw.de:9200/resources/item/HT017412936:DE-361:NA088.88-4442721?parent=HT017412936'`.
Assigning @fsteeg.
