### ISSUE TITLE
Fix quality of geo-cache in ES 5.6

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#643]
The index of the geo-cache in our old cluster is good. Since the boosting-algorithms have changed the geo-cache in ES 5.6 is of a different quality. Aim is to fix the quality of the new geo-cache, i.e. bring it in sync with the old one.

Originates from #585.
Completes #621.

**Comment by dr0i** [comment]
E.g. http://lobid.org/resources/HT018122721.json with ` "coverage" : [ "Bonn" ],` and correctly `spatial" : [ {  "label" : "Bonn"` versus http://stage.lobid.org/resources/HT018122721.json with `spatial" : [ {  "label" : "Bonn-Castell"`

**Comment by dr0i** [comment]
Deployed to staging. http://stage.lobid.org/resources/HT018122721.json good now. A more comprehensive check is to be done. Updated the stats, see http://stats.lobid.org/scoreCoverageCsv_alleWerte_Es5.6.csv.
E.g. `Aachen Frankenberg ` was better in the old matching, but why and how to improve this is to be analyzed.

**Comment by dr0i** [comment]
See http://stats.lobid.org/diff2.3Vs5.6.diff for the diff.

**Comment by dr0i** [comment]
Consequences of the `AND` operator:
**Precision** is fine now, see e.g. [Aachen Frankenberg](http://lobid.org/resources/HT017029574.json). Only rare cases are not good , e.g. [Kreis Höxter](http://lobid.org/resources/BT000117093.json) matches on `Höxter`, which was already reported in #627. 
**Recall**:
http://lobid.org/resources/search?q=spatial%3A* => 281.496 hits
http://lobid.org/resources/search?q=coverage%3A* => 288.506 hits
i.e. ~7k (or 2.4%) `coverage` entries don't have any matches. Formerly we had `7290` distinct matches, now only `5972`.
Updated the stats.

**Comment by acka47** [comment]
I think this can be closed and we should do further work on the wikidata matching in #627.
