### ISSUE TITLE
Wrong "dateOfBirth"

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#66]
Something is cut away in http://lobid.org/resources/HT018924091.

JSON snippet:

```json
subject:[
   {
      "id": "http://d-nb.info/gnd/1093886471",
      "dateOfBirth": "20",
      "preferredName": "Ferd",
      "preferredNameForThePerson": "Ferd"
   }
]
```

In the source it reads "ca. 20.-21. Jh." in 902d.

**Comment by dr0i** [comment]
Here cataloging rules are flawed:
The `902.d` notates the birth AND death date in _one_ string, separated by `-`. We extract this to generate _two_ semantic entries (birth and optionally death).  Having these two fields we can make quite some fancy queries, like [Give me all resources of which persons are subjects which were between 14 and 30 year old when 1968 hit](http://lobid.org/resources?q=subject.dateOfBirth:[1938%20TO%201954]). I mean, who ever wanted to make such a query ;)

So now we have these options:
1. use the string as it is and store this in _one_ property (obviously `gndo:dateOfBirthAndDeath`)
2. stay with the two properties and _ignore_ strings which doesn't fit into the pattern `(YYYY)-(YYYY)?`
3. make it complicate and don't ignore case (2) but encode that string like proposed in (1).

My favourite is obviously (2) , not putting too much effort into this issue. I would propose to make (3) if there is really a demand.

**Comment by acka47** [comment]
+1 for going with (2) for now.

**Comment by dr0i** [comment]
Deployed to production, closing.
