### ISSUE TITLE
Missing JSON object in component list of old NWBib subjects

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#669]
The solution for https://github.com/hbz/lobid-resources/issues/639 leads to a wrong special case ([pull request](https://github.com/hbz/lobid-resources/pull/667)): BT000040377 now misses a label in each affected `componentList`. Supposedly this is the case for multiple old NWBib subjects which were put into the catalog. From the example: 
```
<datafield tag="902" ind1="-" ind2="1">
   <subfield code="a">Rheine</subfield>
   <subfield code="a">Vogelschutz</subfield>
</datafield>
<datafield tag="907" ind1="-" ind2="1">
   <subfield code="a">Vogelschutz</subfield>
   <subfield code="a">Rheine</subfield>
</datafield>
``` 
Resources with a single old NWBib subject aren't affected (like [BT000103077 (MAB)](http://lobid.org/hbz01/BT000103077)). Because there are very few resources which are in this situation we prefered to deploy the not perfect solution for #639.

**Comment by fsteeg** [comment]
Is this still true? Both http://lobid.org/resources/BT000040377.json and http://lobid.org/resources/BT000103077.json seem to have labels for all subjects (both componentList and simple subjects).

**Comment by acka47** [comment]
Yes, the problem is still there. In each component list one JSON object is missing.

**Comment by ChristophEwertowski** [comment]
I couldn't solve the problem with the `componentList`. At least I fixed the label which now in the form of subject chains (with `|` as separators), see [BT000040377 (test, json)](http://test.lobid.org/resources/BT000040377.json) for a changed resource / [HT019305260 (production, json)](https://lobid.org/resources/HT019305260.json) for a subject chain. If we want we could show these labels in the frontend, although then an added source would be good.

**Comment by acka47** [comment]
+1
