### ISSUE TITLE
HT012990825 isn't indexed

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#670]
[HT012990825 (MAB)](http://lobid.org/hbz01/HT012990825) can't be found at http://lobid.org/resources/HT012990825.

**Comment by acka47** [comment]
Same for HT000052280, see [MAB source](http://lobid.org/hbz01/HT000052280) and http://lobid.org/resources/HT000052280. Reported by @hagbeck

**Comment by acka47** [comment]
@dr0i you are already on this, aren't you? @hagbeck asked about it...

**Comment by dr0i** [comment]
HT012990825 has a URI in in 088 subfield (where a litral is expected to create `bibframe:note`).
HT000052280 has no `dct:created` (MAB 002 is missing).
Both are fixed with the above mentioned PRs. Will be deployed with next fulldump index at monday morning.
