### ISSUE TITLE
Concat title with subseries field

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#672]
Edoweb customer wants the `title` field MAB 331 combined with MAB 360 `titleOfSubseries` to differentiate resources easier ([jira ticket](https://jira.hbz-nrw.de/browse/EDOZWO-150)). An example: At the moment our `title` field for specific cases is combined from MAB 331 and MAB 085 (frei definierbares Feld). So it looks like this in [HT016138627 (json)](https://lobid.org/resources/HT016138627.json):
```
"title" : "Statistische Berichte Rheinland-Pfalz / A / I / AII, AIII - vj",
"titleOfSubSeries" : "A. I. AII, AIII - vj, Bevölkerungsvorgänge : im ... Vierteljahr ; (Vorläufige Ergebnisse), Elektronische
``` 
Combined it would contain two times the roughly same content "A / I / AII, AIII - vj" or "A. I. AII, AIII - vj", respectively. There are two possiblities: 
* We remove MAB 085 from title and combine it in the frontend.
* We insert a combine which consists of MAB 331 and MAB 360 which will be chosen before the combination of MAB 331 and 085.

I prefer the second option. What do you think, @acka47?

**Comment by ChristophEwertowski** [comment]
`otherTitleInformation` is removed if it is already in `title`. See [diff of HT016138627](https://github.com/hbz/lobid-resources/pull/673/files#diff-69d6a96c9825d1a8b39e9874593be514).

**Comment by acka47** [comment]
+1
