### ISSUE TITLE
Show thesisInformation in same frontend block as publication type

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#679]
The information from `thesisInformation` is shown in the frontend in a separate row than the `publication type`. As it is an information which is inherent of the type is should be shown in a row with the publication type, like all publication information is shown in one block. 

![thesisinformation](https://user-images.githubusercontent.com/24875432/35143606-56e5f12a-fd02-11e7-903a-96daa48a0ccb.png)

**Comment by acka47** [comment]
Closing
