### ISSUE TITLE
Shouldn't sigel2isilMap.csv be in repo lookup-tables?

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#68]
I just stumbled over https://github.com/hbz/lobid-resources/blob/master/src/main/resources/sigel2isilMap.csv and wondered why it is in the lobid-resources repo and not in the [lookup-tables](https://github.com/hbz/lookup-tables) repo.

**Comment by TobiasNx** [comment]
We do not use the sigel2isil map anymore but a new tsv generated from lobid-organisations.
Should we drop it in lookup tables?

**Comment by TobiasNx** [comment]
> We do not use the sigel2isil map anymore but a new tsv generated from lobid-organisations. Should we drop it in lookup tables? @acka47 @dr0i

The mapping now is generated via cronjob #1903.
I am closing this ticket since sigil2isil mapping is not used anymore.
