### ISSUE TITLE
Update hbz BEACON file

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#685]
At https://de.wikipedia.org/wiki/Wikipedia:BEACON#Bibliotheken,_Verb%C3%BCnde,_Archive there is a BEACON file built from a very outdated open data dump from 2012 that only contained a small part of the union catalogue. As those BEACOn files are used in different service by Wikimedia as well as by others (e.g. https://www.deutsche-biographie.de) the effort to make such an offer is worth it.

We should  think about offering frequently updated versions of a hbz BEACON for

1. resources _by_ a person identified with a specific ID (as the current one) and
2. resource _about_ a person identified with a specific GND ID.

As target both files  should use links to lobid and not the Aleph OPAC.

**Comment by acka47** [comment]
See also https://github.com/hbz/nwbib/issues/335

**Comment by dr0i** [comment]
@acka47 will use `jj` to parse the lobid-dump, which now resided in` hduser@weywot1:~/685-beacon`. There are two dumps: the base-dump(7.7G as gz) and the unpacked 1.7G updates. See the README in that directory. `jj` is installed at weywot1. Assigning @acka47 for building the jj-queries.

**Comment by acka47** [comment]
I am currently working with the NWBib subset obtained via the lobid API. As far as I can see, I only get JSON lines using the `bulk` parameter, don't I? JJ only supports JSON, not JSON lines (I asked for JSON lines support in https://github.com/tidwall/gjson/issues/60).

However, for now I will be working with jq as it supports json lines.

**Comment by acka47** [comment]
Talking offline, we decided to create a list of all contributors with GND ID, including corporate bodies. That is easily done as we only need all the GND IDs from the `contribution` array. Here is the way to create a list including the count:

`cat input.lsonl | jq .contribution[].agent.id | sort | uniq -c | sort -n -r > gnd-contributors.txt`

However, for a BEACON file we only need the GND ID, not the URI and the count is appended after a pipe (e.g. `2012232-9|835`). You can probably also do this with jq but it will take some time for me to find out how. Maybe we can check this out together, @dr0i .

Regarding the persons as subjects, this is not so easily done as you have to filter the subjects by `"type": "Person"`. However, people usually aonly create BEACON files for the contributors and I don't know whether our "subject BEACONs" have been used at all in the past. Thus, I suggest to leave this out.

**Comment by dr0i** [comment]
You can split the lines yourself and then use `jj` like this:
  > IFS=$(echo` -en "\n\b")
rm con; for i in $(head  resources-20170726-20180209.jsonl); do echo "$i" | jj contribution.1.agent.id | sed 's#^http://d-nb.info/gnd/#\n|#g' >> con ;  done; cat con | sort | uniq -c | sort -n -r > gnd-contributors.txt

**Comment by dr0i** [comment]
@acka47 your query is fine, and `jq` is fast enough. To add pipes and remove gnd-prefix and to some formatting just add these cmds to your pipeline: `| sed  's# "#|#g'|sed 's#^ *##g'| sed 's#"$##g'| sed 's#http://d-nb.info/gnd/##g' `.

**Comment by acka47** [comment]
Thanks to the maintainer's quick response, the newest version of jj now supports json lines so we can also use it:

```
$ head 20180213_nwbib.jsonl | jj -p ..#.contribution.#.agent.id
[
  ["http://d-nb.info/gnd/16227679-5", "http://d-nb.info/gnd/4248173-9"], 
  ["http://d-nb.info/gnd/12499251X"], 
  ["http://d-nb.info/gnd/16239355-6"], 
  ["http://d-nb.info/gnd/119509407", "http://d-nb.info/gnd/118599801"], 
  ["http://d-nb.info/gnd/121050343"], 
  ["http://d-nb.info/gnd/1027677215"], 
  ["http://d-nb.info/gnd/106385895"], 
  [
    "http://d-nb.info/gnd/118821512", 
    "http://d-nb.info/gnd/1018387250", 
    "http://d-nb.info/gnd/121818004"
  ], 
  ["http://d-nb.info/gnd/1058450166"], 
  ["http://d-nb.info/gnd/101937425X"]
]
```

It is quicker than jq but the output looks different. @dr0i please decide how to proceed.

**Comment by dr0i** [comment]
I found `jq` fast enough and also easier to consume.

**Comment by acka47** [comment]
Ok, then it is `cat input.jsonl | jq .contribution[].agent.id | sort | uniq -c | sort -n -r | sed 's# "#|#g'|sed 's#^ *##g'| sed 's#"$##g'| sed 's#http://d-nb.info/gnd/##g'`

**Comment by acka47** [comment]
BTW,  already updated https://de.wikipedia.org/wiki/Wikipedia:BEACON#Bibliotheken,_Verb%C3%BCnde,_Archive.
