### ISSUE TITLE
Use note field for information about superordinates

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#688]
In MAB 501 there are whole lot of resources which contain information about titles they are contained in. The resources I looked at were from 1999. 

[HT010107570  (MAB)](http://lobid.org/hbz01/HT010107570)
```
<datafield tag="501" ind1="-" ind2="1">
   <subfield code="a">Aus: Stoma. Zs. f. Zahn-, Mund- u. Kieferheilkunde. 19. 1966</subfield>
</datafield>
```
Even if we have no id we should include this information, shouldn't we?

**Comment by acka47** [comment]
Just to clarify.

- Currently content from 501 is written in to `note` without exception.
- This issue proposes to take all data that has a preceding `Aus:` or `In: ` and use it to specify the isPart relation.

**Comment by ChristophEwertowski** [comment]
At least in the test data set there are no examples with `In:`.

**Comment by ChristophEwertowski** [comment]
Deployed to test, see `isPartOf`/`note` at [TT001451033 (test, json)](http://test.lobid.org/resources/TT001451033.json). Only `note` fields are covered which have only one entry of "In:" or "Aus: ". The `note` contents are only included into `isPartOf` if there isn't already better `isPartOf` information. For "In: " better contents come from MAB `4[56789]3[-ab]1.a` which also describes relations between a part and a volume. For "Aus: " the better `isPartOf` data originates from `<data source="599[-s][-1].a"/>` and `<data source="4[56789]1[-ab]1.a"/>`.

**Comment by acka47** [comment]
This is a very similar thing to what we did in https://github.com/hbz/lobid-resources/issues/478. There, @ChristophEwertowski created two macros called "createEntityForHasSuperordinateWithoutIdWithNumbering" and "createEntityForHasSuperordinateWithoutIdAndNumbering". Couldn't we also use them in this context?

**Comment by dr0i** [comment]
Re: macros:
Macros are like "functions" (or: "methods") and make sense when called more than once, i.e. when iterable fields appear (like 100, 104, ..., 148). Here, they are of no much use.
I guess one *could* conflate some regexs, making a quick shot I failed and since we don't even have test files for all the cases and the one test is working well I propose to just use what @ChristophEwertowski did.
