### ISSUE TITLE
Resource HT017411546 not found

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#69]
Originally reported by @acka47 in https://github.com/hbz/nwbib/issues/308:

```
$ curl -i http://lobid.org/resources/HT017411546
HTTP/1.0 404 Not Found
```

**Comment by dr0i** [comment]
The problem is a bad catalogue entry:

        <datafield ind2="1" ind1="e" tag="655">
            <subfield code="u">
              http://nbn-resolving.de/urn:nbn:de:hbz:6-85659520092 &lt;http://nbn-resolving.de/&gt;
            </subfield>

The content of `655_1e.u` should be a URI, but it's not (having the "&lt;http://nbn-resolving.de/&gt" as surplus). Solution: accept the URI string up to the first whitespace, if any.

**Comment by dr0i** [comment]
Deployed to staging, see http://lobid.org/resources-staging/HT017411546.

**Comment by dr0i** [comment]
Deployed to staging, see http://lobid.org/resources-staging/HT017411546.

**Comment by fsteeg** [comment]
+1

**Comment by dr0i** [comment]
Deployed to prodcution, closed.
