### ISSUE TITLE
Incorporate new vocabularies

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#691]
While talking about https://github.com/hbz/lobid-resources/issues/681 @dr0i addressed the topic of subjects in RVK ([comment](https://github.com/hbz/lobid-resources/issues/681#issuecomment-359496125)). 
There are other subjects which originate from different keywording rule sets. See MAB 700:
```
700       NOTATION EINES KLASSIFIKATIONSSYSTEMS

          Indikator:

          blank = Systematik der katalogisierenden Institution
          a     = UDC     (Universal Decimal Classification)
          b     = DDC     (Dewey Decimal Classification)
          c     = LC      (Library of Congress Classification)
          d     = DNB     (Systematik der Deutschen Nationalbibliographie)
          e     = Methode Eppelsheimer
          g     = Regensburger Verbundklassifikation
          h     = Gesamthochschulbibliothekssystematik (GHBS)
          l     = RPB     (Rheinland-Pfaelzische Bibliographie)
          m     = MSC     (Mathematics Subject Classification)
          n     = NWBib   (Nordrhein-Westfaelische Bibliographie)
          o     = ASB     (Allgemeine Systematik fÃ¼r Bibliotheken)
          p     = SSD     (Systematik der Stadtbibliothek Duisburg)
          q     = SfB     (Systematik fÃ¼r Bibliotheken)
          r     = KAB     (Klassifikation fÃ¼r Allgemeinbibliotheken)
          s     = Systematiken der ekz
          t     = Systematik der TUB Muenchen
          u     = DOPAED der UB Erlangen
          v     = IFZ-Systematik
          w     = Systematik der Bayerischen Bibliographie
          z     = ZDB-Systematik
```
There are also some subjects in MAB 711. 
See [HT008357540](http://lobid.org/hbz01/HT008357540):
```
<datafield tag="711" ind1="a" ind2="1">
   <subfield code="a">Borderline Personality Disorder</subfield>
   <subfield code="a">therapy</subfield>
   <subfield code="x">MeSH</subfield>
</datafield>
```
How should we handle which vocabularies?

**Comment by ChristophEwertowski** [comment]
At the moment we use:
* blank and `b` for DDC-links (if no DNB-DDC-like notation)
* `l` for RPB-Sachgruppen and RPB-Sachsystematik and notations of the RPB-Raumsystematik which we don't resolve
* `n` for NWBib Sachsystematik and NWBib Raumsystematik

**Comment by TobiasNx** [comment]
In ALMA-Fix we also introduced: LCSH. Others should be introduced too

https://github.com/hbz/lobid-resources/blob/1ba224dd9a68cc4e9f21e4a645167f0d82964557/src/main/resources/alma/fix/subjects.fix#L50-L57

**Comment by TobiasNx** [comment]
Previous MAB 700 are now listed as different MARC elements (http://www.alma-dach.org/alma-marc/bibliographic/084/084.html):

Notations of specific cataloguing institutions:
 Systematik der katalogisierenden Institution: 700_ $a $2DNB/$2ZDB -> 084 ## $$a $$qDE-101 $$2 sdnb/ 084 ## $$a $$qDE-600 $$2 zdbs (Indikator: blank = Systematik der katalogisierenden Institution)
UDC(Universal Decimal Classification): 700 a $$a -> 080 ## $$a
DDC(Dewey Decimal Classification): 700 b $$a $$c -> 082 0# $$a $$2
LC(Library of Congress Classification): 700 c $$a ($$2) -> 050 #4 $$a
DNB: 700 d $$a ($$2) -> 084 ## $$a $$2 sdnb
Methode Eppelsheimer: 700 e $$a ($$2) -> 084 ## $$a $$2 methepp 
Basisklassifikation: 700 f $$a -> 084 ## $$a $$2 bkl
RVK: 700 g $$a -> 084 ## $$a $$2 rvk
Gesamthochschulbibliothekssystematik (GHBS) : 700 h $$a -> 084 ## $$a $$2 ghbs
NDC (Nippon Decimal Classification) : 700 j $$a -> 084 ## $$a $$2 njb
NDLC (National Diet Library Classification): 700 k $$a ->  084 ## $$a $$2 kktb
RPB (Rheinland-Pfälzische BibliographieHBS): 700 l $$a -> 084 ## $$a $$2 rpb
MSC (Mathematics Subject Classification) : 700 m $$a -> 084 ## $$a $$2 msc
NWBib : 700 n $$a $$b $$0 -> 084 $$a <700n $$a ; 700n $$b> $$0 $$2 nwbib
ASB (Allgemeine Systematik für Bibliotheken): 700 o $$a -> 084 ## $$a $$2 asb
SSD (Systematik der Stadtbibliothek Duisburg) : 700 p $$a -> 084 ## $$a $$2 ssd
SfB (Systematik für Bibliotheken): 700 q $$a -> 084 ## $$a $$2 sfb
KAB (Klassifikation für Allgemeinbibliotheken): 700 r $$a -> 084 ## $$a $$2 kab
Systematiken der ekz : 700 s $$a -> 072 #7 $$a $$2 ekz
Systematik der TUB München: 700 t $$a -> 084 ## $$a $$2 stub
DOPAED der UB Erlangen: 700 u $$a -> 084 ## $$a $$2 dopaed
IFZ-Systematik: 700 v $$a -> 084 ## $$a $$2 ifzs
Systematik der Bayerischen Bibliographie: 700 w $$a -> 084 ## $$a $$2 sbb
ZDB-Systematik: 700 z $$a -> 084 ## $$a $$q DE-600 $$2 zdbs

The inclusion of 084 seems to be pretty easy.
https://gist.github.com/TobiasNx/f27ef5a08b423236c386754daef55dc6

**Comment by TobiasNx** [comment]
I did a draft PR to discuss stuff: https://github.com/hbz/lobid-resources/pull/1461

**Comment by TobiasNx** [comment]
This is added to ALMA-Fix and won't be added to Aleph.
