### ISSUE TITLE
Missing startDate at Periodicals and Series

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#694]
[HT012056279 (json)](http://lobid.org/resources/HT012056279.json) is missing a `startDate` although it's in MAB 425b (see [HT012056279 (MAB)](http://lobid.org/hbz01/HT012056279)).
Query of all resources which have an `endDate` but no `startDate`: http://lobid.org/resources/search?q=_exists_%3Apublication.endDate+NOT+_exists_%3Apublication.startDate. Of course some of them will be wrongly cataloged.

**Comment by ChristophEwertowski** [comment]
@dr0i , @fsteeg : I need a list which application runs on which server. I have switched the index for test but the new results don't show up. Then I used the restart script in the "lobid-resources-test" folder on quaoar1 because it sometimes helps. Is this the right place? If yes: Why doesn't it work? If no: Where is the test application?

**Comment by ChristophEwertowski** [comment]
Now it does show up: [HT017451384 (production, json)](http://lobid.org/resources/HT017451384.json) / [HT017451384 (test, json)](http://test.lobid.org/resources/HT017451384.json). Maybe it's a caching problem.

**Comment by acka47** [comment]
+1
