### ISSUE TITLE
Bibliographic ontology doesn't resolve anymore

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#698]
The links to bibo don't resolve anymore, see for example http://purl.org/ontology/bibo/Article. The vocabulary still exists on Google Code but only as downloadable files.  
Bibo URLs describe publication types, `doi`, `edition`, `isbn`/`issn`, `oclcnum` and `shortTitle`. For most of these properties we should be able to find alternatives.

**Comment by acka47** [comment]
I opened an issue at https://github.com/structureddynamics/Bibliographic-Ontology-BIBO/issues/13. Regarding replacing bibo properties and types, see alsohttps://github.com/hbz/lobid-resources/issues/108.

**Comment by ChristophEwertowski** [comment]
- `doi`:  In the already used vocabularies there is no fitting equivalent. http://id.loc.gov/vocabulary/identifiers/doi.html could be used if we don't create a lobid property.
- `edition`: [bf:edition](http://id.loc.gov/ontologies/bibframe.html#p_edition) or rda:has edition statement](http://rdaregistry.info/Elements/m/P30107) fit. http://schema.org/bookEdition not.
- `isbn`: http://schema.org/isbn fits. http://id.loc.gov/vocabulary/identifiers/isbn would also work but would be an additional vocabulary.
- `issn`: bibframe only has a class, RDA "[has ISSN of series](http://rdaregistry.info/Elements/m/P30166")" or "[has ISSN of subseries](http://rdaregistry.info/Elements/m/P30167)". http://schema.org/issn fits the best because it's about "serials" and not only "series".
- `oclcnum`: There is no fitting equivalent. http://schema.org/identifier or something similar is too generic.

**Comment by ChristophEwertowski** [comment]
- `shortTitle`: [rda:hasVariantTitle](http://rdaregistry.info/Elements/m/P30128) would fit.

**Comment by acka47** [comment]
There are also the classes:

- bibo:Article
- bibo:Book
- bibo:Image
- bibo:MultiVolumeBook
- bibo:Newspaper
- bibo:Periodical
- bibo:Proceedings
- bibo:ReferenceSource
- bibo:Report
- bibo:Series
- bibo:Standard
- bibo:Thesis

We could just add them to lobid vocab and link with `owl:equivalentClass` to the repsective bibo class (in case it comes up again or for people who still use the Bibo URIs). BTW, the bibo vocab as n3 can be obtained from LOV at http://lov.okfn.org/dataset/lov/vocabs/bibo/versions/2009-11-04.n3.

**Comment by ChristophEwertowski** [comment]
We could also use schema.org: Article (description doesn't cover articles from scientific journals), Book, Newspaper, Periodical, Report, Thesis. For the other type classes I didn't found existing replacements.

**Comment by ChristophEwertowski** [comment]
Deployed to test. For one example, see http://test.lobid.org/resources/HT006266886.json.

Bibo replaced with lobid vocabulary: `AudioDocument`, `AudioVisualDocument`, `Image`, `Manuscript`, `MultiVolumeBook`, `oclcNumber` (previously bibo:oclcnum), `Proceedings`, `ReferenceSource`, `shortTitle`, `Standard`
Bibo replaced with bibframe: `edition`
Bibo replaced with schema.org: `Article`, `Book`, `Map`, `Newspaper`, `Periodical`, `Thesis`
Bibo and mo replaced with "Standard Identifier Schemes" of the Library of Congress: `doi`, `isbn`, `issn`, `ismn` (formerly from Music Ontology)

**Comment by acka47** [comment]
We shouldn't rush this as we are currently implementing the DINI AG KIM's "[Empfehlung für die RDF-Repräsentation bibliographischer Daten](https://wiki.dnb.de/pages/viewpage.action?pageId=68060017)" which contain a lot of Bibo. Also, the Bibo URIs still work as identifieres even if they don't resolve. I will send an email to the group's mailing list

**Comment by ChristophEwertowski** [comment]
Until the second version of the recommendation is finished I won't work on this. So I'm moving it into the backlog.

**Comment by acka47** [comment]
The ontology is resolving again and there are efforts to move hosting (and maybe even more) of Bibo to DCMI. Closing.
