### ISSUE TITLE
Add corporateBodyForTitle to title

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#704]
The following query shows many resources with only the `title` "Journal": http://lobid.org/resources/search?q=title%3Ajournal. Many of them have a `corporateBodyForTitle` which in the detail view is added to title ([example HT012356767](http://lobid.org/resources/HT012356767)). It would be good to also concat it in the list view.

**Comment by acka47** [comment]
As no partner/lobid user has requested this and everybody seems ok with the current data, I am closing this.
