### ISSUE TITLE
Exclude "DDC" notations with subfield "2" = DNB from transformation

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#709]
As noted in https://github.com/hbz/nwbib/issues/163#issuecomment-360504924 there are lots of errors in some resources regarding the DDC notation, see e.g. http://lobid.org/resources/HT006955939. All of the erroneous notations have "DNB" in subfield "2". As noted in https://github.com/hbz/lobid-resources/issues/400#issuecomment-334107184, these DNB-Sachgruppen are not always identical with DDC. Thus, we should remove them from the transformation and only keep those without subfield "2" (from Edoweb, see e.g. [HT019248596](http://lobid.org/resources/HT019248596) ([source](http://lobid.org/hbz01/HT019248596))) and with "ZDB" in subfield "2".

**Comment by acka47** [comment]
@ChristophEwertowski Just to be sure, this still has high priority. The changes should be included in the new index on Thursday.

**Comment by ChristophEwertowski** [comment]
Deployed to test. See [HT013304490 (MAB)](http://lobid.org/hbz01/HT013304490) / [HT013304490 (test, json)](http://test.lobid.org/resources/HT013304490.json). Works also for subjects without a classification which, at least for the test set, only exist if no ZDB or DNB subjects exist. See [HT018895767 (MAB)](http://lobid.org/hbz01/HT018895767) / [HT018895767 (test, json)](http://test.lobid.org/resources/HT018895767.json) (added 530 / `Physik` in the MAB testing file to test if it works with more than two subjects).

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closed.
