### ISSUE TITLE
Search from click on RPB subjects is broken

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#714]
Doesn't work for both RPB subject classifications. See for example http://lobid.org/resources/HT019149667, click on ["Realschule plus"](http://lobid.org/resources/search?subject=http%3A%2F%2Fpurl.org%2Flobid%2Frpb%23n784033) and ["Landeskunde Pfalz"](http://lobid.org/resources/search?subject=https%3A%2F%2Fw3id.org%2Flobid%2Frpb2%23n131) and you don't get results.

**Comment by fsteeg** [comment]
Deployed to stage:

http://stage.lobid.org/resources/search?subject=http%3A%2F%2Fpurl.org%2Flobid%2Frpb%23n784033
http://stage.lobid.org/resources/search?subject=https%3A%2F%2Fw3id.org%2Flobid%2Frpb2%23n131

**Comment by ChristophEwertowski** [comment]
+1
