### ISSUE TITLE
Names for some GND entities missing in JSON

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#716]
There's the placeholder "http://d-nb.info/gnd" instead. There are only 19 resources affected:http://lobid.org/resources/search?q=contribution.agent.label%3A%22http%3A%2F%2Fd-nb.info%2Fgnd%22

Somehow the seem to be ranked high as I got three of them in a not-related search...

**Comment by acka47** [comment]
This has low priority, as these won't surface so prominently as soon as #717 is fixed. So we can place this issue deep in the backlog.

**Comment by fsteeg** [comment]
> This has low priority, as these won't surface so prominently as soon as #717 is fixed.

They are surfacing now (there are only 6 left).

**Comment by ChristophEwertowski** [comment]
Two of the six resources are just cataloging errors, the rest are contracts like [TT002815323 (production)](http://lobid.org/resources/TT002815323) / [TT002815323 (test)](http://test.lobid.org/resources/TT002815323).

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
In #850 it's said that this issue is resolved "mostly". Thus I reopen this issue to let you decide if it's really closable or not.

**Comment by ChristophEwertowski** [comment]
Corrected cataloging errors. Looking at this ticket next week.

**Comment by ChristophEwertowski** [comment]
I missed some contracts for indicators "-" and "a". See `author` at [HT013220743 (production)](http://lobid.org/resources/HT013220743) / [HT013220743 (test)](http://test.lobid.org/resources/HT013220743).

**Comment by acka47** [comment]
+1
