### ISSUE TITLE
ERROR adding gnd ids to Work-objects

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#727]
The ETL logs shows 12k ERRORs. 10k are of this kind:

> ~ERROR~ WARN - Problem with adding http://d-nb.info/gnd/300060130 to {label=<<Le>> cadi dupé, type=[Work]}. Maybe its not declared as 'set'?

So these triples are ignored.

Maybe it's really just the wrong definition of `Work` as a not being a set? Or musn't it be a set and the entries are badly catalogued? Or is it a tranformation-problem and these gnd-ids are wrongly be identified as being part of the `Work`-object?

**Comment by ChristophEwertowski** [comment]
It could be that these resources have multiple entries for `exampleOfWork` in MAB 303-/304 although they shouldn't.

**Comment by dr0i** [comment]
In the logs these WARNs are no more present. So, try to analyze if this is still a problem:

https://lobid.org/resources/TT000012024.json shows a working `Work`.

https://lobid.org/resources/HT014592564.json misses the `Work`-object id. That's no wonder because the gnd id (300060130) is missing in the source MabXmlClob.

Closing this because it seems to be fixed.
