### ISSUE TITLE
edoweb resources with missing inCollection

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#728]
Apparently there are some edoweb resources which don't have the associated `inCollection` entry, like [TT002234887 (json)](http://lobid.org/resources/TT002234887.json) / [TT002234887 (MAB)](http://lobid.org/hbz01/TT002234887). We should use MAB 655 for deciding if a resource is part of edoweb and not MAB 078.

**Comment by acka47** [comment]
There are >1000 resources affected, see http://lobid.org/resources/search?q=fulltextOnline.label%3AEdoweb+AND+NOT+_exists_%3AinCollection.

> We should use MAB 655 for deciding if a resource is part of edoweb and not MAB 078.

I am not sure whether this is the best solution. Perhaps it would make more sense if Edoweb cataloguers added `078`. Can you checkask them what they prefer?

**Comment by ChristophEwertowski** [comment]
The missing edoweb resources consist of:
* "929: rlbdok 166" (e.g. TT002234051)
* content in 078r**2**.a (e.g. HT017773698)
* no entries in 078r (e.g. HT017528975)
* "929: rlbweb 911" (e.g. TT002234887) 

After writing to Mr. Dirx I learned that earlier there were two systems: One for PDFs (rlbdok) and one for websites (rlbdok). The numbers refer to Sigel numbers. I was asked if we could add the edoweb entry to 078r for the missing resources. As the responsible collegue is ill, we don't know if it's needed and looking for URLs in MAB 655 is more robust, I'm using the URL-based approach. 
If the wish for new entries in 078r is still there at the next answer I will refer it to the collegues.

**Comment by ChristophEwertowski** [comment]
The changes are deployed to test. See [TT002234042 (production, json)](http://lobid.org/resources/TT002234042.json) / [TT002234042 (test, json)](http://test.lobid.org/resources/TT002234042.json). Some other properties have changed in some cases because I had to update test files in order to contain edoweb-URLs.

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
Now we have 2112 resources which aren't in the collection but do have the sting "edoweb" in it ([query](NOT inCollection.id:"http://lobid.org/resources/HT016925914#!" AND edoweb)). I'm interested in how much we will have after the merge.
