### ISSUE TITLE
How to handle life dates in subject chains

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#729]
At the moment we use our subject label below the `componentList` to show labels of subject chains. Recently I removed life dates from this concat subject label because it didn't show up at the **real subject labels** and doesn't concur with GND labels. Now that I'm going through my EDOZWO tickets I read why the living statistics were added to the label: Edoweb customer wanted it (https://jira.hbz-nrw.de/browse/EDOZWO-750). So, how to proceed with it? Attach it again to the label or don't and have slow queries at the subjects?

(@dr0i : You were right with asking about the missing life dates for Adenauer in an earlier pull request. It didn't came into my mind that the missing life dates could be an additional error which we didn't detect earlier.)

```json
{
    "componentList" : [ {
      "dateOfBirthAndDeath" : "ca. Mitte d. 4. Jh.",
      "id" : "http://d-nb.info/gnd/129877727",
      "label" : "Castor, von Karden",
      "source" : {
        "id" : "http://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "type" : [ "Person" ]
    }, {
      "label" : "Biographie",
      "type" : [ "SubjectHeading" ]
    }, {
      "label" : "Elektronische Publikation",
      "type" : [ "SubjectHeading" ]
    } ],
    "label" : "Castor, von Karden | Biographie | Elektronische Publikation",
    "type" : [ "ComplexSubject" ]
  } ]
}
```

The example should be something like this in the frontend: `Castor, von Karden (ca. Mitte d. 4. Jh.); Biographie; Elektronische Publikation`.

**Comment by acka47** [comment]
Edoweb does not use `componentList.label` but fetches the data from `dateOfBirthAndDeath` for presentation purpose. NWBib uses it for the Themensuche, though. In the current production system based on lobid 1.x we currently have the dates in subject chains but not in individual subjects' labels, see e.g. https://nwbib.de/HT018630847. 

In the new NWBib we show the dates anywhere, see https://test.nwbib.de/HT018630847. As the GND doesn't have the date in the preferred label (see e.g. http://d-nb.info/gnd/118560034), NWBib seems to be on the right track.

**Comment by ChristophEwertowski** [comment]
Closing this issue.
