### ISSUE TITLE
Type resources with 052r as Series

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#732]
Noticed this while reviewing https://github.com/hbz/lobid-resources/issues/559.

http://lobid.org/resources/HT003651380 currently is of type `EditedVolume` which probably derives from the subject heading "Aufsatzsammlung". However, we are actuallly dealing with a series here which is made clear by `<controlfield tag="052">r||||||||||||||</controlfield>`. From the [MAB documentation](http://www.dnb.de/SharedDocs/Downloads/DE/DNB/standardisierung/mab2FormatSatzkennungSegment000Nov2001.txt?__blob=publicationFile):

```
052       VEROEFFENTLICHUNGSSPEZIFISCHE ANGABEN ZU FORTLAUFENDEN
          SAMMELWERKEN

          Indikator:
          blank = nicht definiert

          Datenelemente:
            0  Erscheinungsform
               a = unselbstaendig erschienenes Werk
               f = Fortsetzung
               j = zeitschriftenartige Reihe
               p = Zeitschrift
               r = Schriftenreihe (Serie)
               z = Zeitung
```

Currently, we are obviously only taking into account `052a.r` and not without the indicator, see https://github.com/hbz/lobid-resources/blob/56fba6ccd13ee2bba52d49cbf7e137f1220838dc/src/main/resources/morph-hbz01-to-lobid.xml#L1470-L1472

**Comment by ChristophEwertowski** [comment]
The code snippet only fires if there is no ISBN (see code below) as a series itself doesn't have ISBNs but only a ISSN (see also http://zdb-katalog.de/title.xhtml?idn=017479924). The volumes however can have ISBNs. Besides: It it's a `Series` it should have it's concurring `zdbId`. So it's bad cataloging.

```
<combine name="@collection" value="${a}">
	<if>
		<none>
			<data source="540[-ab][-1].[ab]"/>
		</none>
	</if>
	<data source="052." name="a">
		<regexp match="^r|^.se|^...se|^.....se" format="$[ns-bibo]Series"/>
	</data>
</combine>
 ```

**Comment by acka47** [comment]
Here is the entry in lobid: http://lobid.org/resources/HT012533073. It has "SSPT" only in `otherTitleInformation` not as `alternativeTitle` although it can be found both in 335 and 370:

```xml
<datafield tag="335" ind1="-" ind2="1">
  <subfield code="a">SSPT</subfield>
</datafield>
<datafield tag="370" ind1="a" ind2="1">
  <subfield code="a">SSPT</subfield>
</datafield>
```

**Comment by ChristophEwertowski** [comment]
In the GVK it's stated for two works that the ISBN stands for the whole series. Some entries have also different, correct ISBNs. Asked Mrs. Block if it could be corrected but she said the ISBN itself is correct but the use of it is not. So it's also the error of the publisher because the ISBN organisation should check it an ISBN is already in use. Since we can't improve it, I'm closing this issue.
