### ISSUE TITLE
Improve altLabel definition

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#739]
At the moment some cases of `altLabel` aren't covered right. See http://lobid.org/resources/HT019440025.json:
`"altLabel" : [ "Der Präsident des Landtags Rheinland-Pfalz", "Landtag", "Der Präsident", "Wissenschaftliche Abteilung", "Parlaments- und Wissenschaftlicher Dienst", "Rheinland-Pfalz" ],`
In the source there is additional information, e.g. 
```
<datafield tag="205" ind1="-" ind2="1">
   <subfield code="k"><<Der>> Präsident</subfield>
   <subfield code="h">Rheinland-Pfalz. Landtag</subfield>
</datafield>
```
instead of only `"Der Präsident"`. The same for subfields "k" and "b", see
```
<datafield tag="205" ind1="-" ind2="1">
   <subfield code="k">Rheinland-Pfalz</subfield>
   <subfield code="b">Landtag</subfield>
   <subfield code="b">Referat Öffentlichkeitsarbeit</subfield>
</datafield>
```

**Comment by ChristophEwertowski** [comment]
Could be partly solved by https://github.com/hbz/lobid-resources/issues/855.

**Comment by ChristophEwertowski** [comment]
Deployed to test, see "Präsident" in`altLabel` [HT019440025 (production, json)](http://lobid.org/resources/HT019440025.json) / [HT019440025 (test, json)](http://test.lobid.org/resources/HT019440025.json). Many other resources also have this combination of `altLabel` subfields.

I can't concat the multiple subfields `b` from the second example because there are many MAB 205s with multiple subfields.

**Comment by acka47** [comment]
> I can't concat the multiple subfields b from the second example because there are many MAB 205s with multiple subfields.

That is a pity as important information gets lost. As the alt labels are rather for indexing and search and not display, this doesn't matter though. Thus, +1.
