### ISSUE TITLE
Replace http://rdvocab.info/termList/RDAproductionMethod/1010

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#74]
It doesn't resolve anymore: http://rdvocab.info/termList/RDAproductionMethod/1010

**Comment by ChristophEwertowski** [comment]
Try this: http://www.rdaregistry.info/termList/RDAproductionMethod/#1010

**Comment by dr0i** [comment]
Deployed to production, see e.g. http://lobid.org/resources/HT012237361#!.

**Comment by acka47** [comment]
I just noticed that the actual URI is `http://rdaregistry.info/termList/RDAproductionMethod/1010` as is written in the HTML and in the RDF (`curl -L -H "Accept: text/turtle" http://rdaregistry.info/termList/RDAproductionMethod`).  Sorry, that I only see this now will have to remove the hash. It is probably best to do this within #97. Closing this one anyway.
