### ISSUE TITLE
Same hbzId leads to different works in old Verbundkatalog and lobid

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#748]
In the old Verbundkatalog HT000016031 stands for `Beiträge zur Geschichte des Parlamentarismus und der politischen Parteien`. In lobid it leads to `Mehr Verständnis für Kinder, mehr Verständnis für die Schule` ([link](http://lobid.org/resources/HT000016031)). A search for the former title leads to seven results ([query](http://lobid.org/resources/search?q=%22Beitr%C3%A4ge+zur+Geschichte+des+Parlamentarismus+und+der+politischen+Parteien%22+)). The former title also isn't part of the JSON. What is going on?

**Comment by ChristophEwertowski** [comment]
I searched for "WYN=0000->1000" and only got this hit. Now that I sent the same search again I get 1086 results before the search is canceled. Something's rotten in the state of Denmark. Nevertheless since now I get the right results for the query and for search for HT000016031 I'm closing this issue.

**Comment by ChristophEwertowski** [comment]
It depends on which browser is used. If I use Firefox I get the wrong result. If I'm using Chrome it works.
![unterschiedliche_hbzid_katalog_lobid](https://user-images.githubusercontent.com/24875432/36742631-7b024bbc-1be8-11e8-8fb9-762ba2a18d29.png)

**Comment by acka47** [comment]
This is really strange. I can't reproduce it, though. Clicking on the Aleph link in http://lobid.org/resource/HT000016031/about gives me the right entry also an expert search with `idn=HT000016031`...
