### ISSUE TITLE
Add missing publication years

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#749]
Obviously the current regular expression for `startDate` excludes several of them.
```
<data source="425[ab-p][-1].a|419-1c|595-[-12].a">
	<regexp match="^1\d{3}|^20\d{2}"/>
</data>
```
See MAB 425 at http://lobid.org/hbz01/HT012841230 or http://lobid.org/hbz01/HT012796134. 
The missing publication dates of https://github.com/hbz/lobid-resources/issues/558 should be added together with this missing dates.

**Comment by ChristophEwertowski** [comment]
Half-deployed to test. See [HT012796134 (production, frontend)](http://lobid.org/resources/HT012796134) / [HT012796134 (test, frontend)](http://test.lobid.org/resources/HT012796134) / [HT012796134 (MAB)](http://lobid.org/hbz01/HT012796134) for example with brackets. HT012841230 (example with months before it) should also have the right date but I don't get test updated (restarting also doesn't help). You'll have to look at the diff in the pull request.
I also removed still existing "s.l." (sine locum) from `location`. See [TT003059252 (production, json)](http://lobid.org/resources/TT003059252.json) / [TT003059252 (test, json)](http://test.lobid.org/resources/TT003059252.json).

**Comment by acka47** [comment]
+1
