### ISSUE TITLE
Maintenance of LBZ vocabulary

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#750]
The easy way of updating the LBZ Sachsystematik worked one time. But there are some steps we should do to give it to the LBZ entirely.

1. I propose that after two more successful commits we should show them how to open and maintain their own vocabulary repository. Then we need a way to automatically import / lookup changes in the vocabulary.
2. The LBZ customer asked if we could maintain the Raumsystematik of the LBZ. I said that this would be too much work but we could make something similar to the procedure for the Sachsystematik. We should to this in conjunction with the first step.

Jira-Ticket: https://jira.hbz-nrw.de/browse/EDOZWO-751

**Comment by ChristophEwertowski** [comment]
@acka47 approved it in a conversation.

**Comment by TobiasNx** [comment]
@acka47 is this still relevant?

**Comment by acka47** [comment]
In fact, we recently showed them how to update the turtle files, see https://service-wiki.hbz-nrw.de/display/SEM/Bearbeitung+der+Systematiken+auf+GitHub So, this is resolved. Closing
