### ISSUE TITLE
Expand definition for natureOfContent

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#753]
While working on https://github.com/hbz/lobid-resources/issues/592 I saw in a created file which counts the contents of MAB 064 that a lot of resources don't have `natureOfContent` which probably should.

From the [BVB documentation](https://www.bib-bvb.de/web/kkb-online/rda-mini-mab):
```
Angaben zur Art des Inhalts, erweiterte Datenträgertypen, musikalische Ausgabeform
Indikator:
blank = nicht definiert --- nicht verwenden!
a = Angaben zum Inhalt (gnd-content)
b = Angaben zum Datenträger (gnd-carrier)
c = Musikalische Ausgabeform (gnd-music)
```

Example for *ind1="c"*: http://lobid.org/hbz01/HT015509219
Example for *ind2="2"*: http://lobid.org/hbz01/HT015429988

**Comment by ChristophEwertowski** [comment]
Deployed to test. Now MAB 455, 465 (field **called Bandangabe!**) and so on are preferred for volume statements instead of picking it out of 451 etc. See [HT013798403 (production, json)](http://lobid.org/resources/HT013798403.json) / [HT013798403 (test, json)](http://test.lobid.org/resources/HT013798403.json).

**Comment by ChristophEwertowski** [comment]
Oops! Wrong window. Now `ind1="c"` is used for `natureOfContent` with `ind1` and `ind2`. For non-musical works we can't use ind2 because for example it may contain "Zeitschrift" while the resource is an `Article`. Examples from MAB 064c2: "Partitur", "Stimme, Musikalische Ausgabeform", "Klavierauszug" etc. Since, for example, parts of a score also have the contents of a score this should be correct.
Example for MAB 064c1: [HT018853619 (production, json)](http://lobid.org/resources/HT018853619.json) / [HT018853619 (test, json)](http://test.lobid.org/resources/HT018853619.json) / [HT018853619 (MAB)](http://lobid.org/hbz01/HT018853619)
Example for MAB 064c2: [HT015429988 (production, json)](http://lobid.org/resources/HT015429988.json) / [HT015429988 (test, json)](http://test.lobid.org/resources/HT015429988.json) / [HT015429988 (MAB)](http://lobid.org/hbz01/HT015429988)

**Comment by acka47** [comment]
+1
