### ISSUE TITLE
Missing note field

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#755]
A FRL customer asks for a missing note field in [HT019488785](http://lobid.org/resources/HT019488785). At the moment we use just the first result of a `choose` element but since multiple entries of MAB 501 are allowed we should use all contents of this MAB field.

Related jira issue: https://jira.hbz-nrw.de/browse/FRL-87

**Comment by ChristophEwertowski** [comment]
Deployed to test. See [HT018857620 (production, json)](http://lobid.org/resources/HT018857620.json) / [HT018857620 (test, json)](http://test.lobid.org/resources/HT018857620.json).

**Comment by acka47** [comment]
Is it possible (with little effort) to retain the original order in the array?

**Comment by ChristophEwertowski** [comment]
Not with little effort. I remember that at some place I concatted contents from MAB fields with the same number and then splitted the string but that's too much work for the `note` field.

**Comment by acka47** [comment]
Ok then, +1.
