### ISSUE TITLE
Wrong assignments of nodes for edoweb resource

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#758]
In http://lobid.org/resources/HT016925914.json the setting of the subjects went wrong so that we have two times the `describedBy` property, one time at the right place and the other time in `inCollection`.

**Comment by ChristophEwertowski** [comment]
Deployed to test. See `inCollection` at production and test of [edoweb (production, json)](http://lobid.org/resources/HT016925914.json) / [edoweb (test, json)](http://test.lobid.org/resources/HT016925914.json), [NWBib (production, json)](http://lobid.org/resources/HT014176012.json) / [NWBib (test, json)](http://test.lobid.org/resources/HT014176012.json) and [ZDB (production, json)](http://lobid.org/resources/HT014846970.json) / [ZDB (test, json)](http://test.lobid.org/resources/HT014846970.json).

**Comment by acka47** [comment]
+1
