### ISSUE TITLE
Add all GSW to coverage with notation marker

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#763]
Sub-issue of #627.

Add all GSW to the coverage field with a marker for the notation it is associated with. We will use a pipe as separator for the marker.

#### HT019016355 

From the [Source](http://lobid.org/hbz01/HT019016355):

```xml
<datafield tag="700" ind1="n" ind2="1">
  <subfield code="a">99</subfield>
  <subfield code="b">Köln</subfield>
</datafield>
```

Expected result:

`"coverage": "Köln | 99"`

#### HT019566068

From the [source](http://lobid.org/hbz01/HT019566068):

```xml
datafield tag="700" ind1="n" ind2="1">
  <subfield code="a">36</subfield>
  <subfield code="b">Diözese Köln</subfield>
</datafield>
```

Expected result:

`"coverage": "Diözese Köln | 36"`

**Comment by acka47** [comment]
@ChristophEwertowski See https://github.com/hbz/lobid-resources/commit/4ebac2de98b4e0e1c84652a54a1819ecebf9761e for the notations that have to be added again.

**Comment by ChristophEwertowski** [comment]
Deployed to test. See [BT000041593 (test, json)](http://test.lobid.org/resources/BT000041593.json) / [HT004381366 (test, json)](http://test.lobid.org/resources/HT004381366.json).

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
It is on production now but unfortunately, I can't query for the notations, see e.g. http://lobid.org/resources/search?q=coverage%3A97 and http://lobid.org/resources/search?q=coverage%3A%22%7C+97%22 (while e.g. http://lobid.org/resources/search?q=coverage%3Aeschweiler works...
