### ISSUE TITLE
Presentation problem in sub heading when two otherTitleInformation strings

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#768]
See http://lobid.org/resources/HT018230040

![bug](https://user-images.githubusercontent.com/160292/37200670-be0b62fa-2385-11e8-8569-0620f7a31f25.png)

I propose to only use the first entry in the arrary for the sub heading.

**Comment by fsteeg** [comment]
Deployed to stage: http://stage.lobid.org/resources/HT018230040

**Comment by acka47** [comment]
....and the award for quickest fix of the month goes to @fsteeg: :trophy: 

+1
