### ISSUE TITLE
Add copyright statement

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#773]
A publisso customer needs the copyright statement which can be found in MAB 444. For an example look at [HT019488427 (MAB-XML)](http://lobid.org/hbz01/HT019488427):
```
<datafield tag="444" ind1="a" ind2="1">
   <subfield code="n">Sofern nicht anders angegeben, ist dieses Werk lizenziert unter einer Creative Commons Namensnennung 4.0 Lizenz</subfield>
   <subfield code="u">https://creativecommons.org/licenses/by/4.0/</subfield>
</datafield>
```

I'm going to look how many entries are in our data and what subfields MAB 444 can contain. According to the collegues from the BVB the field is called "Informationen zum Copyright-Status" and is a RDA field.

Original issue: https://jira.hbz-nrw.de/browse/FRL-267

**Comment by ChristophEwertowski** [comment]
From the Feldhilfe of our Aleph:
```
444      COPYRIGHT-INFORMATIONEN (W, FAKULTATIV, ALLE SATZTYPEN)  -  RDA
              Indikator:
              blank  = nicht definiert
              a  = öffentlich
              b  = nicht öffentlich

              Unterfelder:
              a  = Verantwortliche Person (NW, fakultativ)
              b  = Sterbedatum der verantwortlichen Person (NW, fakultativ)
              c  = Verantwortliche Körperschaft (NW, fakultativ)
              d  = Inhaber des Copyrights (W, fakultativ)
              e  = Kontaktinformation zum Inhaber des Copyrights (W, fakultativ)
              f  = Copyright-Angabe laut Vorlage (W, fakultativ)
              g  = Copyright-Datum (NW, fakultativ)
              h  = Aktualisierungsdatum des Copyrights (W, fakultativ)
              i  = Veröffentlichungsdatum (NW, fakultativ)
              j  = Herstellungsdatum (NW, fakultativ)
              k  = Verlag (W, fakultativ)
              l  = Copyright-Status (NW, fakultativ)
              m  = Veröffentlichungsstatus (NW, fakultativ)
              n  = Anmerkung (W, fakultativ)
              o  = Datum der Ermittlung (NW, fakultativ)
              p  = Veröffentlichungs- bzw. Herstellungsland (W, fakultativ)
              q  = Supplying Agency (NW, fakultativ)
              r  = Gerichtsstand für das Copyright (NW, fakultativ)
              s  = Informationsquelle (NW, fakultativ)
              u  = Uniform Resource Identifier (W, fakultativ)
```

**Comment by ChristophEwertowski** [comment]
At the moment (aleph-baseline from 2018-03-09) we have 41 entries in MAB `444a1.u`, all Creative Commons licenses. After the integration of the field in publisso the ZBMed wants to put the rest of its license information from the note field MAB 501 to MAB 444.

**Comment by ChristophEwertowski** [comment]
Deployed to test. See [HT019488427 (test, json)](http://test.lobid.org/resources/HT019488427.json). First I thought about adding copyright information to `publication` but there can be more licenses than publication events. An example from my own experience: Some musicians published works in the past under Creative Commons license. After they got more successful they removed their from music from one website and published it at a different website with a new license. Also we can't be sure that the information in MAB 444 will be sufficient for aligning it to the right publication statement.
Because of this I created a `copyrightInformation` object for which I couldn't find an existing property. RDA only has [`has copyright date`](http://rdaregistry.info/Elements/m/datatype/P30007) and [`has note on copyright date`](http://rdaregistry.info/Elements/m/datatype/P30007). Bibframe only has [`copyrightDate`](http://id.loc.gov/ontologies/bibframe/copyrightDate). Schema.org has [`copyrightYear`](http://schema.org/copyrightYear) and [`copyrightHolder`](http://schema.org/copyrightHolder) which also doesn't cover all possible contents of MAB 444 we could be interested in (some information like publishing date we already have in the data). 
For the `license` property I used http://schema.org/license. RDA and bibframe didn't have something like this. 

In the past there were some RDF legal vocabularies but most of them aren't accessible anymore. An exception is Creative Commons which has a class for licenses: https://creativecommons.org/ns#License.

**Comment by ChristophEwertowski** [comment]
We decided to only include `license`. If somebody wants additional copyright information from MAB 444 we will create/use an additional property.

**Comment by ChristophEwertowski** [comment]
Deployed to test. See `license` at [HT019488427 (test, json)](http://test.lobid.org/resources/HT019488427.json).

**Comment by acka47** [comment]
+1 However, for me, it would suffice to use "Lizenz" as label instead of "Urheberrechtslizenz"...
