### ISSUE TITLE
Add missing hbz-URLs to predecessor and successor

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#775]
The [FAZ (HT002192569, MAB-XML)](https://lobid.org/hbz01/HT002192569) has a predecessor but the hbzId from MAB 780-1.9 isn't used. If I look at the morph I see the same error for successors (MAB 785).

**Comment by ChristophEwertowski** [comment]
Deployed to test, see ¸predecessor` and `successor` at [HT016138627 (production, json)](http://lobid.org/resources/HT016138627.json) and
[HT016138627 (test, json)](http://test.lobid.org/resources/HT016138627.json).

**Comment by acka47** [comment]
The hasbang is missing at the end of the URI, it shoudl read `http://lobid.org/resources/HT015869763#!`. Otherwise +1.
