### ISSUE TITLE
Publication statements at wrong place

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#776]
See `agent` at https://github.com/hbz/lobid-resources/blob/master/src/test/resources/jsonld/HT019578856. At [HT019578856 (production, json)](http://lobid.org/resources/HT019578856.json) it's still correct.

**Comment by ChristophEwertowski** [comment]
Deployed to test. See [HT019578856 (test, json)](http://test.lobid.org/resources/HT019578856.json).

**Comment by acka47** [comment]
+1
