### ISSUE TITLE
Make "Map" and "Image" a type and not a medium

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#786]
See https://github.com/hbz/lobid-resources/issues/703.

**Comment by ChristophEwertowski** [comment]
Deployed to test. See [HT017066705 (test, json)](http://test.lobid.org/resources/HT017066705.json) for type "Image" and [BT000003404 (test, json)](http://test.lobid.org/resources/BT000003404.json) for type "Map". The frontend has to be adjusted too.
As a sidenote: Atlasses and maps aren't consitently catalogued in Aleph. But the bibo definitions of "Book" and "Map" are broad enough to cover both of these cases.

**Comment by acka47** [comment]
+1
