### ISSUE TITLE
Remove subjectOrder and contributorOrder from lobid

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#790]
While working on #782 ("Keep index small") I came across this issue. We don't show `contributorOrder` or `subjectOrder` in the json files but they can be searched. See http://lobid.org/resources/search?q=_exists_:contributorOrder or http://lobid.org/resources/search?q=_exists_:subjectOrder. Theoretically there could be users so if we remove these properties we should announce it with a few weeks in advance.

**Comment by acka47** [comment]
> Theoretically there could be users so if we remove these properties we should announce it with a few weeks in advance.

The only user was @jschnasse, others should not be aware of these hidden fields. Thus, I think we should not announce it because it would rather irritate people.

**Comment by ChristophEwertowski** [comment]
There is nothing to see at test, so please look at the [pull request](https://github.com/hbz/lobid-resources/pull/793/files) for review of the deleted `subjectOrder` and `contributionOrder`.

**Comment by acka47** [comment]
+1
