### ISSUE TITLE
Rename "Kombination"

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#791]
http://rdaregistry.info/termList/RDAMediaType/1008 is labeled "Kombination" although it is a "video" (like stated at the rdaregistry website). However http://iflastandards.info/ns/isbd/terms/mediatype/T1008 is the right property.

**Comment by ChristophEwertowski** [comment]
Deployed to test. See [HT009719670 (test, json)](http://test.lobid.org/resources/HT009719670.json) for a label "Kombination" ([HT009719670 (production, json)](http://lobid.org/resources/HT009719670.json) dosen't have it) and [HT018857620 (json, test)](http://test.lobid.org/resources/HT018857620.json) for a "Video".
The facet links for "Kombination" and "Video" are corrected. For the at production not shown type "Video" I used a similar icon than for "AudioVisualMedia". But we won't need it as at the moment every resource of medium "AudioVisualMedia" also is a "Video". So I will remove it after your comments (if there is a way to recognise silent films it would make sense to differentiate).

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
As discussed yesterday I removed the medium `Video` from the facets.
