### ISSUE TITLE
Websites partly not secure

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#797]
https://lobid.org/resources : "Parts of this website are not secure".

- [x] lobid-resources
- [x] lobid-organisations
- [x] nwbib
- [x] lobid-gnd
- [x] lobid.org webpages

**Comment by dr0i** [comment]
Could made it secure by changing the `ServerName` in the `default-server.conf` from `emphytos` to `lobid.org`. Pushed it to `gaia master`.

**Comment by dr0i** [comment]
Yeah, well, and then the simple http lookups don't work anymore resp. are not correctly redirected to 443. Sigh.
As firefox is satisfied with the solution provided with https://github.com/hbz/lobid-resources/commit/90c3f84104386cea4d7627bfeb9f1a808cef285a I think this is good enough.
Reverted the `default-server.conf`.

**Comment by dr0i** [comment]
You may have a look at it @acka47 . Atm even chromium seems satisfied, maybe that was a cache issue.

**Comment by dr0i** [comment]
Don't know why travis failed on a morph test. I even reset a branch to a commit once build successfully, but now success now. Try travis again later.

**Comment by acka47** [comment]
Looks good in Chrome, Chromium and Firefox. Closing.
