### ISSUE TITLE
Remove obsolete properties

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#8]
We have a workaround `lv:nameOfContributingCorporateBody` (introduced with hbz/lobid#38), where we subsume literals of corporate bodies, be they creators or contributors. I think this property will be made obsolet by the new `lv:contributorOrder` , right?

**Comment by acka47** [comment]
I re-neamed this ticket to a more general task: remove obsolete properties _after_ properly implementing API 2.0.

When we are properly done with API 2.0 the following properties should be obsolete and should be removed before going into production:

- [ ] `contributingCorporateBodyLabel`: with #40 corporate body search will work with `?q=corporateBody
- [ ] `contributorLabel`: person search will work with `?q=contributor`, see also #40
- [ ] `subjectlabel`, as a subject search works with ?q=subject.*:Pferd
- [ ] `subjectChain`, provided that there is a way to search for a subject chain by using the `subject` list

**Comment by acka47** [comment]
The question is whether these properties are really obsolete or whether they still contain information that isn't found elsewhere. For example, I just noticed that `subjectlabel` contains information from fields 710/711 that is not – and should not– moved to the `subjectarray. Example [TT002234459](http://lobid.org/hbz01/TT002234459) (snippet):

```xml
<datafield tag="710" ind1="-" ind2="1">
  <subfield code="a">
Wandern, Diez, Lahnstein, Rhein-Lahn-Info, Rhein, Lahn, Wirtschaftsförderung
  </subfield>
</datafield>
```

We might not want to have it in the subject array as it would be mistaken as some part of an RSWK subject chain. (There is still the possibility, though, that we need a field like `subjectChain` or `subjectOrder` for providing required functionality like "Themensuche" in NWBib).

We will have to take this into accoutn before removing properties. One possibility for 710/711 might be to switch back to dc:subject for this when we don't list the strings together with alternate names of GND subjects...

**Comment by acka47** [comment]
Talking to @jschnasse the other day, it became clear that we should keep "subjectOrder" as we can not group multiple subject chains in a `subject` array.

**Comment by dr0i** [comment]
Look at the status quo of API 2.0 I think we may close this ticket. Only `subjectChain` is still used and will be in the future because at the moment `json-ld` doesn't support lists in lists, yes @acka47 ?

**Comment by acka47** [comment]
In https://github.com/hbz/lobid-resources/issues/8#issuecomment-195413272, I ticked the properties that already have been removed. Is this correct? This means, we will keep `subjectLabel`, `subjectOrder` and `subjectChain` for now. I would be ok with this.

**Comment by acka47** [comment]
I found another property that should be removed: `volume`. Since https://github.com/lobid/lodmill/issues/497 we don't need it anymore and only retained it because edoweb still needed it, see https://github.com/lobid/lodmill/issues/497#issuecomment-132473784 ff.

**Comment by acka47** [comment]
As we will keep `subjectLabel`, `subjectOrder` and `subjectChain` for now (and will hide them in the API response, at least `subjectLabel`), this issue can be closed after #171. Adjusting the PR accordingly.

**Comment by acka47** [comment]
What about `contributorOrder`? I think we on't need this a well, do we? @jschnasse Do you need it?

**Comment by dr0i** [comment]
@acka47 I know that @jschnasse needs it. He has to rewrite mayor logics and no time for this at the moment. Had him promised to not remove `contributorOrder` till at least march.

**Comment by acka47** [comment]
Reopening. These still have to be removed from the context/labels.json:

- [ ] `contributingCorporateBodyLabel` (http://purl.org/lobid/lv#nameOfContributingCorporateBody)
- [ ] `contributorLabel`
- [ ] `creatorName`
- [ ] `eissn`
- [ ] `hasFormat`
- [ ] `hasPart`
- [ ] `inDataset`
- [ ] `issued`
- [ ] `lccn`
- [ ] `placeOfPublication`
- [ ] `prefLabel`
- [ ] `primaryTopic`
- [ ] `publicationStatement`
- [ ] `publisher`
- [ ] `subjectName`
- [ ] `volume`
- [ ] `wikipedia`
