### ISSUE TITLE
Deletions API sample should be consistent with other range search

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#801]
Like the existing example: `publication.startDate:[* TO 1500]`

We should use: `describedBy.deleted:[201803028 TO 20180405]`

I think we should change this before announcing this new API on the list.

**Comment by fsteeg** [comment]
Deployed to stage: http://stage.lobid.org/resources/api

(Moved the sample below the other range sample, above the link to the ES documentation)

**Comment by fsteeg** [comment]
> I am surprised that the query works anyway...

Yes, weird!

Deployed fix to stage: http://stage.lobid.org/resources/api

**Comment by acka47** [comment]
+1
