### ISSUE TITLE
Add provenance information

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#809]
Similar to https://github.com/hbz/lobid-gnd/issues/89. An easy way would be to add add a ~`derivedBy`~ `isBasedOn` triple to the `describedBy` object:

```json
{
  "id":"http://lobid.org/resources/HT019025795#!",
  "describedBy":{
    "dateCreated":"20160706",
    "dateModified":"20170920",
    "id":"http://lobid.org/resources/HT019025795",
    "label":"lobid Ressource",
    "isBasedOn":"http://lobid.org/hbz01/HT019025795"
  }
}
```

A more complex way would also cover information on the software used etc. something like this:

```json
{
  "@context":{
    "id":"@id",
    "describedBy":{
      "@type":"@id",
      "@id":"http://www.w3.org/2007/05/powder-s#describedby"
    },
    "dateCreated":"http://schema.org/dateCreated",
    "dateModified":"http://schema.org/dateModified",
    "wasGeneratedBy":{
      "@id":"http://www.w3.org/ns/prov#wasGeneratedBy",
      "@type":"@id"
    },
    "Activity":"http://www.w3.org/ns/prov#Activity",
    "startedAtTime":{
      "@id":"http://www.w3.org/ns/prov#startedAtTime",
      "@container":"xsd:dateTime"
    },
    "endedAtTime":{
      "@id":"http://www.w3.org/ns/prov#startedAtTime",
      "@container":"xsd:dateTime"
    },
    "used":{
      "@id":"http://www.w3.org/ns/prov#used",
      "@type":"@id"
    }
  },
  "id":"http://lobid.org/resources/HT019025795#!",
  "describedBy":{
    "dateCreated":"20160706",
    "dateModified":"20170920",
    "id":"http://lobid.org/resources/HT019025795",
    "label":"lobid Ressource",
    "wasGeneratedBy":{
      "type":"Activity",
      "startedAtTime":"2018-04-01T01:30:00Z",
      "endedAtTime":"2016-04-01T05:00:00Z",
      "used":[
        {
          "id":"http://lobid.org/hbz01/HT019025795"
        },
        {
          "id":"https://github.com/hbz/lobid-resources"
        }
      ]
    }
  }
}
```

(If we did it all correctly, we'd have to move `dateCreated` and `dateModified` to `<http://lobid.org/hbz01/HT019025795>` resource but that would mean an API break.)

**Comment by dr0i** [comment]
> (If we did it all correctly, we'd have to add dateCreatedanddateModified` to the hbz01 resource 

Is this not already so since #455 ?

**Comment by acka47** [comment]
@dr0i You misunderstood me. I meant that the provenance triples should rather be stated for `<http://lobid.org/hbz01/HT019025795>`. One reason os that the respective lobid resource most of the time didn't even exists at the time of creation...

**Comment by dr0i** [comment]
Ok now I got it: mind the difference `hbz01` vs `resources`.

**Comment by acka47** [comment]
It's definitely good to only link to the lobid-resources repo. I updated the example above. However, I wouldn't like to add something like a `derivedWith` statement as the connection to the source data would not be there, i.e. it would not be the same as saying: "This entry was generated with this software from this data."

So we have to somehow group the software and the source data together. Another way to do it is with schema.org which even provides more information (by differing between object the action is carried out upon and the instrument) than the PROV example:

```json
{
  "@context":{
    "id":"@id",
    "@vocab": "http://schema.org/",
    "describedBy":{
      "@type":"@id",
      "@id":"http://www.w3.org/2007/05/powder-s#describedby"
    },
    "resultOf": { "@reverse": "http://schema.org/result" }
  },
  "id":"http://lobid.org/resources/HT019025795#!",
  "describedBy":{
    "dateCreated":"20160706",
    "dateModified":"20170920",
    "id":"http://lobid.org/resources/HT019025795",
    "label":"lobid Ressource",
    "resultOf":{
      "type":"Action",
      "object": { 
        "id":"http://lobid.org/hbz01/HT019025795"
      },
      "instrument": {
        "id":"https://github.com/hbz/lobid-resources"
      }
    }
  }
}
```

**Comment by fsteeg** [comment]
Can we get this to:

```json
{
  "@context":{
    "id":"@id",
    "@vocab": "http://schema.org/",
    "describedBy":{
      "@type":"@id",
      "@id":"http://www.w3.org/2007/05/powder-s#describedby"
    },
    "resultOf": { "@reverse": "http://schema.org/result" }
  },
  "id":"http://lobid.org/resources/HT019025795#!",
  "describedBy":{
    "dateCreated":"20160706",
    "dateModified":"20170920",
    "id":"http://lobid.org/resources/HT019025795",
    "label":"lobid Ressource",
    "resultOf":{
      "type":"Action",
      "object": "http://lobid.org/hbz01/HT019025795",
      "instrument":"https://github.com/hbz/lobid-resources"
    }
  }
}
```

**Comment by acka47** [comment]
Yes, of course. But I kept the `id` statement as we might add a label for both because we usually add labels to nodes with an IRI...

**Comment by ChristophEwertowski** [comment]
As your suggestions seem quite good I'm starting with this ticket. To add labels is good because then we can say that a lobid resource originates from the ZDB or the Verbundkatalog.
To fulfill the requirements of DSG NRW also the date of the processing should be added. This could be added by adding the start of lobid-resources 2.0/calculating it after it. Or we could simply add a note which states that newly created resources are added the next day and changes at already created resources are put into it after the weekend.

**Comment by ChristophEwertowski** [comment]
Added processing information to test, see [BT000002852 (test, json)](http://test.lobid.org/resources/BT000002852.json) / [HT000009600 (test, json)](http://test.lobid.org/resources/HT000009600.json). I changed the labels so that is clear what the origin of the `object` is.

**Comment by ChristophEwertowski** [comment]
Also added `note` to give a statement about processing date (probably there are better alternatives for the labels). See [HT019357035 (test, json)](http://test.lobid.org/resources/HT019357035.json) for a non-modified resource after start of lobid 2.0 and [HT014215912 (test, json)](http://test.lobid.org/resources/HT014215912.json) for resource before start of lobid 2.0. For modified resources see [HT017529028 (test, json)](http://test.lobid.org/resources/HT017529028.json) (after start of lobid 2.0) and [HT003651380 (test, json)](http://test.lobid.org/resources/HT003651380.json) (before).

**Comment by ChristophEwertowski** [comment]
@acka47 mentioned in a call that the statement that a resource is processed after a specific `dateModified` or `dateCreated` isn't always true. If the morph changes, new fields could be added to the json without changing the date.
@dr0i: Can a date be added if the MAB-XML file is morphed? It should look like this:

```
"resultOf" : {
   "endDate" : "20180427",
   "instrument" : {
      "id" : "https://github.com/hbz/lobid-resources",
      "label" : "Software lobid-resources"
   },
   "object" : {
      "id" : "http://lobid.org/hbz01/BT000002852",
      "label" : "Ressource aus dem hbz-Verbundkatalog"
   },
   "type" : "Action"
},
```

**Comment by dr0i** [comment]
> Can a date be added if the MAB-XML file is morphed?

Yes, like this:

		<data source="@id" name="http://id.loc.gov/ontologies/bibframe/note">
			<timestamp format="yyyyMMdd" timezone="Europe/Berlin"/>
		</data>

**Comment by acka47** [comment]
Nice, in my opinion the timestamp can be a more specific down to the exact minute..

**Comment by dr0i** [comment]
That would be `yyyy-MM-dd'T'HH:mmZ`. You can modifiy that pattern to your will (e.g. to only use digits).

**Comment by acka47** [comment]
It is ok for `endDate` but thinking about this, we should use http://schema.org/endTime on `Action` anyway.

**Comment by ChristophEwertowski** [comment]
http://schema.org/endTime doesn't quite seem to fit to me. From the description: `For actions that span a period of time, when the action was performed. e.g. John wrote a book from January to December.` But we only want when it was finished (theoretically when it was started as after this the resource could have been changed).
*xsd:dateTime* seems to be the right date format (see [W3.org recommendation](https://www.w3.org/TR/xmlschema-2/#dateTime)) (like the one dr0i used in this example).

**Comment by ChristophEwertowski** [comment]
`endTime` is now added, for example see [HT008355456 (test, json)](http://test.lobid.org/resources/HT008355456.json). In XML schema format dateTime. It won't be indexed as I can't think of a case where somebody wants to search for it (besides one of us for debugging).

**Comment by acka47** [comment]
Looks good. We have to also update the context, though. Also, as I didn't find any use of schema.org for provenance information, before we merge this I want to reassure myself somehow that this makes sense and should be preferred over PROV ontology. Will do this next week.

**Comment by ChristophEwertowski** [comment]
Hint: I already updated the context in the branch, see https://github.com/hbz/lobid-resources/pull/813/files#diff-5ab2f2220a8eff3d9932b9648357820c.

**Comment by acka47** [comment]
Richard gave some good tips over at https://github.com/schemaorg/schemaorg/issues/1905#issuecomment-385372517. We should definitely use a more specific Action type (probably `UpdateAction`) and add type `SoftwareApplication` to the software. If possible, we should also use a unique name as label fr the hb01 resource and add types to the other entities as well as a link to the lobid-resources data set. Here is a quick example:

```json
{
  "@context":{
    "id":"@id",
    "@vocab":"http://schema.org/",
    "describedBy":{
      "@type":"@id",
      "@id":"http://www.w3.org/2007/05/powder-s#describedby"
    },
"BibliographicDescription": "http://purl.org/lobid/lv#BibliographicDescription",
    "resultOf":{
      "@reverse":"http://schema.org/result"
    }
  },
  "id":"http://lobid.org/resources/HT019025795#!",
  "describedBy":{
    "dateCreated":"20160706",
    "dateModified":"20170920",
    "id":"http://lobid.org/resources/HT019025795",
    "type":"BibliographicDescription",
    "isPartOf":"http://lobid.org/resources/dataset#!",
    "label":"Exportierter Eintrag \"Das Kapital \" aus dem hbz-Verbunkatalog",
    "resultOf":{
      "type":"UpdateAction",
      "object":{
        "id":"http://lobid.org/hbz01/HT019025795",
        "type":"DataFeedItem",
        "isPartOf":"https://datahub.io/dataset/hbz_unioncatalog"
      },
      "instrument":{
        "id":"https://github.com/hbz/lobid-resources",
        "label":"Software lobid-resources",
        "type":"SoftwareApplication"
      }
    }
  }
}
```

I just noticed that https://datahub.io/dataset/hbz_unioncatalog redirects to an old datahub verison and lobid is not part of the new one. we will have to look into this but I don't have the time to open an issue now...

**Comment by ChristophEwertowski** [comment]
`lv:isPartOf` doesn't work as it links a resource to an isPartOf relation but not a description. `bf:part`, RDA dct and DC elements also only relate to resources. Seems like we have to create a new property.

**Comment by ChristophEwertowski** [comment]
Current state deployed to test. See [HT008355456 (test, json)](http://test.lobid.org/resources/HT008355456.json). I couldn't get myself to use http://rdfs.org/ns/void#inDataset as the namespace isn't available since 2015 (see comment in http://rdfs.org/ns/void#inDataset)! So if the Open Knowledge Foundation isn't able to host the namespace the vocabulary isn't ready for the future.

For `resultOf` I used the type `CreateAction` instead of `UpdateAction` as the description fits better. Also the resources are created from the start up if the morph runs through.

Finally the type `BibliographicDescription` doesn't fit. This would lead to the case that the bibliographic file contains the following: Something which has the type `BibliographicResource` is `describedBy` something with the type `BibliographicDescription`.

**Comment by ChristophEwertowski** [comment]
Type `BibliographicDescription` is added see every resource on test or [HT008355456 (test, json)](http://test.lobid.org/resources/HT008355456.json).

**Comment by ChristophEwertowski** [comment]
"Webseite zur hbz-Ressource XY" seems fine. See [HT008355367 (test, json)](http://test.lobid.org/resources/HT008355367.json) for changes in the labels of `describedBy` and `object`. In the latter label I added "MAB2-XML" so that people could theoretically inform themselves about the format and understand the data.
