### ISSUE TITLE
Daily updates lagging one day behind

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#81]
See logs in `hduser@gaia:~/git/lobid-resources/log`, e.g. `20160519-064001-master.log.startHbz01ToLobidResources.sh` uses `/files/open_data/open/DE-605/mabxml/DE-605-aleph-update-marcxchange-20160517-20160518.tar.gz`

API 1.x and hbz01-sources are picking up the current ones.

**Comment by dr0i** [comment]
The file containing the list of the to-be-indexed filename is updated at 6:40. The script which reads the file to get the to-be-indexed filename is also set to 6:40. Now this may result in a "race condition": the list may be read before it was updated. Changed the crontab entry to : 

    # API 2.0 @ gaia, start: 00 07 (Attention! Depends on getting the file at 40 06!)
    00 07 * * * ... 

@fsteeg please check tomorrow if this fixes the problem.

**Comment by fsteeg** [comment]
Looks good, according to `hduser@gaia:~/git/lobid-resources/log/20160520-070001-master.log.startHbz01ToLobidResources.sh`, today `/files/open_data/open/DE-605/mabxml/DE-605-aleph-update-marcxchange-20160519-20160520.tar.gz` was used. Closing.
