### ISSUE TITLE
Deweys not searchable

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#815]
Due to the missing `subject.notation` in the `index-config` we can't make a query like http://lobid.org/resources/search?q=subject.notation%3A%22220%22.

**Comment by ChristophEwertowski** [comment]
Why do you need it? `gndIdentifier` also aren't searchable. We should decide if we search by `notation` or `id`. Searching by `notation` seems more intuitive to me. What do you think @acka47 ?

**Comment by ChristophEwertowski** [comment]
Addition: For some dewey or RPB area codes no `id` exist.

**Comment by dr0i** [comment]
> gndIdentifier also aren't searchable.
You could do http://lobid.org/resources/search?subject=http%3A%2F%2Fd-nb.info%2Fgnd%2F4131808-0

I know, nobody asked for it, so we also could skip this. Low priority in any case.
I myself would like to be able to search for a dewey id, it's easier than to search for a label. Also, in particular we have many different languages describing ddc so if I know the ddc for chemistry one could just look this up instead of trying to get the "right" label. Also don't forget, labels are changing! Who knows what label is the actually correct one?

These points mentioned above are nothing compared to the following killer query:
"dewey.notation:231*" . As you know DDC is a hierarchical system so this query would also get you all of the more specific resources. This is what Dewey had in mind.

Again, nobody asked about it, but then sometimes that's just because it was not possible to do in the past and people stick to what they know. History would be at its end, finally.

**Comment by dr0i** [comment]
Ah, uh , people do search for ddc, that's the whole purpose of deweysearch , see e.g.  https://deweysearchde.pansoft.de/webdeweysearch/executeSearch.html?lastScheduleRecord=664.929&lastTableRecord=&query=664.92&_showShortNotations=on&catalogs=DNB&_catalogs=on&catalogs=GBV&_catalogs=on&catalogs=HeBIS&_catalogs=on&catalogs=SUB&_catalogs=on&catalogs=SWB&_catalogs=on&catalogs=FUB&_catalogs=on

Interestingly, 7 german library catalogs are already queryable. But not the hbz one.

**Comment by dr0i** [comment]
I choosed the example because it shows very well the difference between an id (as a ddc is) and a mere label (as in "Zusatzstoffe, Tests, Analysen, Qualitätskontrollen, Nebenprodukte, Verpackung"):
With the label you are not able to differentiate between resources about the different kinds of meat (chicken, mammals, fish etc.). They all have the same label:

> 664.929 Zusatzstoffe, Tests, Analysen, Qualitätskontrollen, Nebenprodukte, Verpackung
664.939 Zusatzstoffe, Tests, Analysen, Qualitätskontrollen, Nebenprodukte, Verpackung
664.949 Zusatzstoffe, Tests, Analysen, Qualitätskontrollen, Nebenprodukte, Verpackung

while denoting in fact 3 different things.
Again I know that this only interesting for very few specialists. But then - isn't it all about that?

**Comment by ChristophEwertowski** [comment]
I see the horses ran wild. ;)

I meant the field `gndIdentifier` which isn't `id`. See for [example](http://lobid.org/resources/TT001173825.json):
```
"gndIdentifier": "119093170", 
"id": "http://d-nb.info/gnd/119093170",
```
Also I checked the morph and it reminded me that there aren't id's for Dewey labels which makes your point clear.

> History would be at its end, finally.
You did use the hammer there, didn't you? ;) I'm with you in this point. To minimise the complexity of the index I'm still in favor of indexing `notation` and `gndIdentifier` fields instead of clunky `id`s. For this https://github.com/hbz/lobid-resources/issues/818 should be solved first.

> Interestingly, 7 german library catalogs are already queryable. But not the hbz one.
The hbz cataloges after "Regeln für die Schlagwortkatalogisierung" (RSWK) so this probably didn't have priority either. But this could be a possiblity to futher expand our lobid imperium.

**Comment by dr0i** [comment]
+1 for enrichment even more deweys. I said "even" because I consider [>13% (2.8M) of our resources having a dewey ID](http://lobid.org/resources/search?q=subject.source.id%3A%22http%3A%2F%2Fd-nb.info%2Fgnd%2F4149423-4%22)  already a broad enough coverage to be quite useful.
