### ISSUE TITLE
Missing dateCreated

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#817]
We have 752 resources which have a `dateModified` but no `dateCreated` ([query](http://lobid.org/resources/search?q=_exists_%3AdescribedBy.dateModified+NOT+_exists_%3AdescribedBy.dateCreated)).

Case 1: MAB field 002 isn't filled, see http://lobid.org/hbz01/HT000052280. Old resource of the previous system which maybe didn't have this field or the transformation was forgotten. In this case we should use `dateModified` for `dateCreated`.
Case 2: MAB field 002 is filled but not with the right content, see http://lobid.org/hbz01/HT000925978 (filled with just "2002").

Argh!!! `dateCreated` (MAB 002) can be edited in any format (see `11.11.2009` in [HT000210058](http://lobid.org/hbz01/HT000210058) or [HT017320303](http://lobid.org/hbz01/HT017320303) where it doesn't even have a subfield) and saved. There is no restriction or even statement in the *Feldhilfe* how to enter data in this fields. I will talk to the collegues of the Verbundgruppe about it. The id can be edited but not saved.

**Comment by ChristophEwertowski** [comment]
I talked to our leader of the Verbundgruppe. Since the new library management system is coming no new plausibility statements are introduced. But she was in favour of using `dateModified` if `dateCreated` doesn't exist. Using the exact same date would be right.

**Comment by ChristophEwertowski** [comment]
Deployed to test. See `dateCreated` at [HT000052280 (test, json)](http://test.lobid.org/resources/HT000052280.json) / [HT000052280 (production, json)](http://lobid.org/resources/HT000052280.json).

**Comment by acka47** [comment]
+1 for the entries where `dateCreated` was missing. What did you do with those entries that have a value in the filed that diverges from the common `yyyymmdd` schema? Do you leave them as is?

**Comment by ChristophEwertowski** [comment]
`dateCreated` is filled with everything from MAB 002 if there are eight digits. So "20180633" would also be possible but "2018" not. If there is only "2018" in MAB 002 (the `dateCreated` field) but "20180612" in MAB 003 (the `dateModified`) the latter would be taken.

**Comment by acka47** [comment]
Great. +1
