### ISSUE TITLE
Missing gndIdentifier

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#818]
[HT019025795 (production, json)](http://lobid.org/resources/HT019025795.json) is missing `gndIdentifier` at `contribution` (unlike for example [TT001173825 (production, json)](http://lobid.org/resources/TT001173825.json)).

**Comment by ChristophEwertowski** [comment]
While adding `gndIdentifier` I used a variable which only covers 900s. I expanded the regular expression and deployed it to test. See [HT000268969 (production, json)](http://lobid.org/resources/HT000268969.json) / [HT000268969 (test, json)](http://test.lobid.org/resources/HT000268969.json)

**Comment by acka47** [comment]
+1
