### ISSUE TITLE
Show smooth numbering statements 

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#828]
[HT019633960](http://lobid.org/resources/HT019633960) shows "Band Volume 87".

[HT004538416](http://lobid.org/resources/HT004538416) shows "Erster Theil, erster" although it should be "Erster Theil, erster Band". Instead of replacing generally "Band" it should be only trimmed only if the string starts with "Band"/"Volume".

**Comment by fsteeg** [comment]
Deployed to stage:

http://stage.lobid.org/resources/HT019633960
http://stage.lobid.org/resources/HT004538416

**Comment by ChristophEwertowski** [comment]
+1
