### ISSUE TITLE
Wrong @context URL in query JSON

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#830]
Reported by @literarymachine. See e.g. http://lobid.org/resources/search?q=_exists_:subject&format=json where the `@context` URL is http://quaoar1.hbz-nrw.de:7500/resources/context.jsonld.

It is ok for single resources, though, see e.g. http://lobid.org/resources/HT017846318.json.

**Comment by fsteeg** [comment]
Same issue in organisations (http://lobid.org/organisations/search?q=*&format=json) and GND (http://lobid.org/gnd/search?q=*&format=json).

**Comment by fsteeg** [comment]
Deployed to test:

http://test.lobid.org/resources/search?q=*&format=json
http://test.lobid.org/organisations/search?q=*&format=json
http://test.lobid.org/gnd/search?q=*&format=json

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

https://lobid.org/resources/search?q=*&format=json
https://lobid.org/organisations/search?q=*&format=json
https://lobid.org/gnd/search?q=*&format=json
