### ISSUE TITLE
Improve ranking by boosting title field

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#832]
[Searching for "elisabeth lange weiße rose"](http://lobid.org/resources/search?q=elisabeth+lange+wei%C3%9Fe+rose&size=100) in lobid-resources, the resource with the title ["Elisabeth Lange | eine Frau aus Detmold im Umfeld der "Weißen Rose""](http://lobid.org/resources/BT000154609) comes not only not as first but is not even part of the first 50 hits. This probably has to do because of the boosting of the preferred name of contributors. This might be solved by boosting the title field with the same factor.

**Comment by fsteeg** [comment]
Deployed to stage: http://stage.lobid.org/resources/search?q=elisabeth+lange+wei%C3%9Fe+rose

**Comment by acka47** [comment]
Looks good. +1
