### ISSUE TITLE
Add label for medium BrailleBook

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#835]
The medium `BrailleBook` doesn't have a label ([query for BrailleBook](http://lobid.org/resources/search?medium=http%3A%2F%2Fpurl.org%2Flibrary%2FBrailleBook&aggregations=medium.id)).

**Comment by ChristophEwertowski** [comment]
Deployed to test. See `http://purl.org/library/BrailleBook` at [TT001210514 (test, json)](http://test.lobid.org/resources/TT001210514.json) / [TT001210514 (production, json)](http://lobid.org/resources/TT001210514.json).

**Comment by acka47** [comment]
+1
