### ISSUE TITLE
Only one of multiple superordinated resources is shown

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#837]
See http://lobid.org/resources/HT015582095 where only one `isPartOf` element is shown. It's quite unfortunate that there is no label for the second superordinate resource but so be it.

**Comment by fsteeg** [comment]
Deployed to stage:

http://stage.lobid.org/resources/HT015582095
http://stage.lobid.org/resources/HT015090208

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
+1
