### ISSUE TITLE
Add new label for alternativeTitle

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#838]
An edoweb customer wants the label of MAB 370 for `alternativeTitle` which is called "Titelzusatz" in lobid. Following MAB fields are contained in it:
1. 340/341, 344/345 [-ab][-1].[ab] (1./2. Parallelsachtitel in Ansetzungsform/in Vorlage- oder Mischform)
2. 342/343, 346/347 [-ab][-1].[ab] (zu ergänzende Urheber zum 1./2. Parallelsachtitel, Zusätze zum 1./2. Parallelsachtitel)
3. 370[abc]1.a (Weitere Sachtitel)
4. 375e[-12].a (Erste/Frühere Titel von fortlaufenden Ressourcen, frühester Titel). Only `ind1="e"` (weitere frühere Titel) is used here, not `ind1="-"` (frühester Titel).
5. 504-1.a (Angabe von Paralleltiteln)

The definition in a RDA learning file of the AG RDA makes clear that none of these MAB fields contain a "Titelzusatz": 
> Ein Titelzusatz ist eine Information, die mit dem Haupttitel in Verbindung steht, und den Charakter, die Inhalte, die Ziele oder die Motivation der Ressource oder den Anlass der Entstehung, Veröffentlichung usw. der Ressource angibt. Zum Titelzusatz gehören beispielsweise Untertitel, Erläuterungen und Ergänzungen zum Haupttitel.

**Goals**
- [ ] If the second group exists we should combine the first and second group, maybe like "342: 340; 343".
   - [ ] For this a new example has to be created as no example fits.
   - [ ] Then we and the customer can call it something like "Alternativtitel". 
- [ ] also use `ind1="-"` of MAB 375 (frühester Titel)

Original ticket: https://jira.hbz-nrw.de/browse/EDOZWO-263
(A FRL customer wants the label "Alternativer Titel" instead of "Titelzusatz". See https://jira.hbz-nrw.de/browse/FRL-278)

**Comment by ChristophEwertowski** [comment]
Combination of fields doesn't work as often only one field exists. Additions to parallel titles (MAB 343, 347, 351, 355) should be added to the parallel titles (MAB 340, 341, 344...).

Reminder to myself: Ask cataloging collegues next week if it is possible that a "zu ergaenzender Urheber zum X. Paralellsachtitel" (MAB 342, 346, 350, 354) could be different from persons and organisations from the MAB 100s and 200s. If not it then it is reasonable to add them to `contribution` entities if no other exists.

**Comment by ChristophEwertowski** [comment]
Deployed to test. "Titelzusätze" are now added to "Paralleltitel in Ansetzungsform" or "Paralleltitel in Vorlageform" if the former doesn't exist. See `alternativeTitle` in [HT015425967 (production)](http://lobid.org/resources/HT015425967.json) / [HT015425967 (test)](http://test.lobid.org/resources/HT015425967.json). Secondly the [context-labels.json (diff)](https://github.com/hbz/lobid-resources/pull/857/files#diff-1645de37c03451cf051ab14b99ee7d6b) has a new label.

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
@dr0i : The change isn't deployed, see `contribution` at [HT007015768 (test)](http://test.lobid.org/resources/HT007015768.json) / [HT007015768 (production)](http://lobid.org/resources/HT007015768.json).
