### ISSUE TITLE
Notation wrongly taken as Dewey notation

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#841]
From a [comment of #814](https://github.com/hbz/lobid-resources/issues/814#issuecomment-396138200). 
In the resource [HT008815963](http://lobid.org/resources/HT008815963) MAB 700 is filled like this:
```
<datafield tag="700" ind1="-" ind2="1">
   <subfield code="a">406120</subfield>
</datafield>
```
`ind1="-"` is defined as: "Systematik der katalogisierenden Institution". As the ZDB uses this indicator for DDC notations we use it for Dewey notations. Because the ZDB uses a subfield for defining it's usage it can be used to exclude non-Dewey notations. Of course the right notation should also be shown.

**Comment by ChristophEwertowski** [comment]
Deployed to test, see [HT008815963 (json)](http://test.lobid.org/resources/HT008815963.json). Since we don't know what the "Systematik der katalogisierenden Institution" is, I linked to [classification schema at Wikidata](https://www.wikidata.org/wiki/Q5962346) and wrote an according label. The frontend has to be adjusted as there is no label for the notation.

**Comment by ChristophEwertowski** [comment]
As discussed, I removed the labels which originate from MAB 700- (not-known classification) and aren't ZDB-DDC labels.

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
I discussed with a collegue who is responsible for the transformation from MAB to our MAB-XML. At the moment he is also working at the 700s as a condition for the development of the MAB-MARC-converter. We didn't see a requirement for librarians how to handle the source of MAB 700- so probably there isn't one. It's likely that this issue will come up in the further development of the converter.
