### ISSUE TITLE
Add license to JSON data, classes of describedBy

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#845]
At the frontend we state: "Katalog- und Bestandsdaten von lobid.org unter CC0". We should also make it clear in our JSON data. Also we give the type `BibliographicDescription` which isn't defined in our vocabulary. Then we should add the type `InventoryData`. E.g.:
```
describedBy: {
   license : {
      id: http://creativecommons.org/publicdomain/zero/1.0
      label: "Creative Commons-Lizenz CC0 1.0 Universal"
   },
   type: [
      "BibliographicDescription",
      "LibraryInventoryData"  
```

**Comment by ChristophEwertowski** [comment]
Deployed to test. See any resources at test. I put the type `LibraryInventoryData` in the `describedBy` block as I wanted to express that the json file is also about library inventory data.

**Comment by acka47** [comment]
As discussed last week, I think that this would rather fit in the item description. But items currently don't have a `describedBy` object where we could add the type. 

One could argue that we should also add `describedBy` triples to items but I don't think it is very important. So my suggestion is to leave this for now. AFAIK, nobody asked for this anyway or did they?

**Comment by ChristophEwertowski** [comment]
As discussed the type `LibraryInventoryData` is removed now. Assining the pull request directly to dr0i.
