### ISSUE TITLE
Set up experimental index with LoC Bibframe data?

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#851]
From an [email to the Bibframe listserv](https://listserv.loc.gov/cgi-bin/wa?A2=BIBFRAME;3141fdaf.1806):

> The Library of Congress has had a second BIBFARME Pilot underway for a year, with 60 catalogers keying descriptions directly into a BIBFRAME editor as the initial step in cataloging a resource.   To support that pilot we converted the entire Library catalog to a BIBFRAME RDF structured file so that the Library’s Pilot catalogers would have the “usual” catalog against which to make cataloging decisions.  There have been numerous requests for access to that file from outside LC and we are working on that.  But in the meantime we are making available a bulk download of that file for systems that can load it and want to experiment.  The converted file is still continually being improved in the Pilot so this is just a snapshot as of May 24 and May 30. 

> The file can be accessed from the download pages of id.lov.gov:  go to http://www.loc.gov/bibframe/implementation/ and follow the link [BIBFRAME Works and Instances dataset](http://www.loc.gov/bibframe/implementation/pdf/bibframe-bulk-download.pdf) which will give you a “ReadMe” for these files, and the link to the ID bulk download page.  

I think we might be able to set up with modest resources an experimental index à la lobid-resources with this data for the community to play around with. What do you think?

**Comment by ChristophEwertowski** [comment]
The benefit would be to be able to see Bibframe in practice (and not only in some example cases). But since the example files are in ntriples format which isn't exactly human readable, I don't know how big the benefit would be without converting it to a different format. 
Also I don't know if it is easy to merge the "BIBFRAME instances" and "BIBFRAME work" files to a single index. They are 20 GB and 18 GB big (http://id.loc.gov/download/). 

(Of course it would be a good publicity move.)

**Comment by literarymachine** [comment]
Are there any stats as to how many triples are in the dump?

**Comment by dr0i** [comment]
@literarymachine unziped the 20 GB file => 216 GB. Counting the lines  `wc -l` => 1.896.985.227.
As expected the file seemed to be build as `[record,record,record]` so with just a little effort a stream-based importer into our ES-cluster should be feasible.

**Comment by dr0i** [comment]
First try results in https://gist.github.com/dr0i/38a920613cba41f29fb37ae409dec4a3 . Discuss.

**Comment by acka47** [comment]
I think, starting with the work data set makes more sense. There is probably more information of interest to the broader community in the work data (e.g. subject headings) while we are not interested in item information from the LoC.

**Comment by dr0i** [comment]
As discussed offline with @acka47 this work example don't reveal interesting things. I couldn't find an entry with an controlled vocabulary for contributors, not even in the `marcXml`, see e.g. https://lccn.loc.gov/2016478507/marcxml . Are these loc entries all so grottig or can you @acka47 or @ChristophEwertowski find something more useful?

**Comment by ChristophEwertowski** [comment]
I neither couldn't find a resource with a `contribution.agent.id`, not even at [Harry Potter and the Order of the Phoenix (MARC-XML](https://lccn.loc.gov/2014495444/marcxml) which was sold in millions and therefore should have a very good entry.

**Comment by acka47** [comment]
Obviously one would have to lookup LoC Name Authorities to get a URI for the contributor, see e.g. http://id.loc.gov/search/?q=j.+k.+rowling&q=cs%3Ahttp%3A%2F%2Fid.loc.gov%2Fauthorities%2Fnames. I am surprised that they didn't do it for the Bibframe data set. Obviously, there is still a lot of work to be done by LoC et al.

**Comment by acka47** [comment]
So, this obviously isn't decent linked data. However, if we set up an ES index with the data, we could provide at least the following facets: `type`, `contribution.agent.label`, `language.id` and maybe also subject headings but I am not sure as there isn't one in the example file at https://gist.github.com/dr0i/9d05c509198c83a1759ecadb0a8726e6.

Furthermore, we could provide some visualizations over `creationDate` and probably also `modificationDate` (that is not in the example file but maybe in others).

**Comment by acka47** [comment]
@dr0i Can you please create a larger example set with a few hundred records?

**Comment by fsteeg** [comment]
As discussed offline, here's a link to the implementation of RDF to JSON-LD conversion in lobid-gnd:

https://github.com/hbz/lobid-gnd/blob/master/app/apps/Convert.java#L111

**Comment by dr0i** [comment]
@acka47 etl'ed ~ 66k to index with name `loc`.

**Comment by dr0i** [comment]
@acka47 works-index also ready. So you can now query two indices, one named `loc_instances` , the other `loc_works`. I don't see any identifier in *works* so I don't think it's useful, while *instances* has at least _some_ ids (e.g. isbn and those to the works of course).
