### ISSUE TITLE
Add altLabels of conferences 

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#855]
Many `altLabel`s of conferences are missing. Some examples:
MAB 201-1.e: http://lobid.org/hbz01/HT012225757
MAB 201-1.e, b and h; MAB 201-1.e and c: http://lobid.org/hbz01/HT006926058 
MAB 201-1.k and b: http://lobid.org/hbz01/HT013094532

There may be additional missing `altLabel`s.

**Comment by ChristophEwertowski** [comment]
Deployed to test.
Subfield `e`: [HT019093814 (MAB-XML)](http://lobid.org/hbz01/HT019093814) / [HT019093814 (production)](http://lobid.org/resources/HT019093814.json) / [HT019093814 (test)](http://test.lobid.org/resources/HT019093814.json). Search for `"Ruhr-Triennale"`.
Subfields `k` and `b`: [BT000168595 (MAB-XML)](http://lobid.org/hbz01/BT000168595) / [BT000168595 (production)](http://lobid.org/resources/BT000168595.json) / [BT000168595 (test)](http://test.lobid.org/resources/BT000168595.json). Search for `"Westfalen-Lippe. Bündnis 90, Die Grünen"`.
Subfields `e` and `c` / `e`, `d` and `c` / `e`, `b` and `h`: [HT006926058 (MAB-XML)](http://lobid.org/hbz01/HT006926058) / [HT006926058 (production)](http://test.lobid.org/resources/HT006926058.json) / [HT006926058 (test)](http://test.lobid.org/resources/HT006926058.json).

As you can see in [HT014681992 (production)](http://lobid.org/resources/HT014681992.json) / [HT014681992 (test)](http://test.lobid.org/resources/HT014681992.json) I also adjusted some labels to RDA form.

**Comment by ChristophEwertowski** [comment]
As mentioned partly in https://github.com/hbz/lobid-resources/issues/859#issuecomment-401013309 the changes should also be done for the `label`s.

**Comment by ChristophEwertowski** [comment]
Deployed to test. See `label` at [HT007015768 (test, json)](http://test.lobid.org/resources/HT007015768.json).

**Comment by acka47** [comment]
+1
