### ISSUE TITLE
Add corporateBody from MAB 342, 346, 350, 354

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#859]
While working on https://github.com/hbz/lobid-resources/issues/838 our cataloging expert for organisations expressed the wish to be able to search in the MAB fields 342, 346, 350 and 354 ("Zu ergänzende Urheber zum 1./2./3./4. Parallelsachtitel"). These fields can contain the title of the organisation in a different language which isn't in the authorized form. An example from [HT007015768 (MAB-XML)](http://lobid.org/hbz01/HT007015768):
```
<datafield tag="200" ind1="-" ind2="1">
   <subfield code="k">Europäische Kommission</subfield>
   <subfield code="b">Zentraldienst Archiv-Dokumentation</subfield>
   <subfield code="9">(DE-588)1020273-0</subfield></datafield>
<datafield tag="201" ind1="-" ind2="1">
   <subfield code="k">Zentraldienst Archiv und Dokumentation</subfield>
   <subfield code="h">Brüssel</subfield>
</datafield>
<datafield tag="201" ind1="-" ind2="1">
   <subfield code="k">Europäische Gemeinschaften</subfield>
   <subfield code="b">Servizio Centrale Automatizzato di Documentazione</subfield>
</datafield>
[...]
<datafield tag="342" ind1="-" ind2="1">
   <subfield code="a">Commission des Communautés Européennes, Service Central Archives-Documentation (SCAD), Division IX/C/3</subfield>
</datafield>
<datafield tag="346" ind1="-" ind2="1">
   <subfield code="a">Commissione delle Comunità Europee, Servizio Centrale Archivi-Documentazione, Divisone IX/C/3</subfield>
</datafield>
```
According to our collegue many librarians want to be able to search for the contents in the named MAB fields because they don't know the right authorized form. E.g. they don't know or can't guess the German name of the top-level corporate body, which in this case would be relatively easy. Additionally the information of all sub-sets of an organisation could be quite useful, too (in this case `Division IX/C/3`). In the catalogue it's not possible to search for it.
Theoretically there could be resources with multiple corporate bodies in these fields but since the number should be relatively small, I propose to simply add the whole string. (If there should be different corporate bodies they would be seperated by ` ; ` but there could be also multiple sections of the same organisation which would be combined like this: "Hogwarts. Hagrids Hütte und Der Finstere Wald." But these problems can be handled by splitting when they occur.)

In RDA files these fields aren't used anymore.

**Comment by ChristophEwertowski** [comment]
Deployed to test. The contents from MAB 342, 346, 350 and 354 are now put into `agent`. See [HT007015768 (MAB-XML)](http://lobid.org/hbz01/HT007015768) / [HT007015768 (production)](http://lobid.org/resources/HT007015768.json) / [HT007015768 (test, json)](http://test.lobid.org/resources/HT007015768.json). As a role I give automatically "author" because these organisations are the ones which created these publications. But "contributor" would be fine too.

**Comment by ChristophEwertowski** [comment]
We decided to put these different forms together with `corporateBodyForTitle` into a `contribution` object. 
```
contribution: [
   {
      agent: {
         altLabel: "Commission des Communautés Européennes, Service Central Archives-Documentation (SCAD), Division IX/C/3", "Commissione delle Comunità Europee, Servizio Centrale Archivi-Documentazione, Divisone IX/C/3"
         label: "Kommission der Europäischen Gemeinschaften, Zentraldienst Archiv, Dokumentation, Abteilung IX/C/3",
         type: [
            "CorporateBody"
         ]
      },
      role: {
         id: "http://id.loc.gov/vocabulary/relators/cre",
         label: "Autor/in"
      },
      type: [
         "Contribution"
      ]
   }
]
```
The `corporateBodyForTitle` exists additionaly as we can't break the API.

**Comment by ChristophEwertowski** [comment]
Deployed to test. See `contribution` at [HT007015768 (test)](http://test.lobid.org/resources/HT007015768.json). [HT006926058 (test)](http://test.lobid.org/resources/HT006926058.json) is an example without MAB 342 etc. Is this OK or shouldn't we show `corporateBodyForTitle` in `contribution` if there isn't a MAB field for the corporate bodies of the parallel titles?

**Comment by acka47** [comment]
As just discussed offline, please also concatenate the subfield `b` for preferred names of corporate bodies from the 200s, e.g. in http://test.lobid.org/resources/HT007015768.json `contribution.agent.label` should read "Europäische Kommission. Zentraldienst Archiv-Dokumentation" instead of only "Europäische Kommission". From the source:

```xml
<datafield tag="200" ind1="-" ind2="1">
  <subfield code="k">Europäische Kommission</subfield>
  <subfield code="b">Zentraldienst Archiv-Dokumentation</subfield>
  <subfield code="9">(DE-588)1020273-0</subfield>
</datafield>
```

**Comment by acka47** [comment]
We also discussed to only add to the contribution array if there is not only 331/333 but also 341/342 or more parallel titles.

**Comment by ChristophEwertowski** [comment]
The decision mentioned in your last commit is now deployed to test. See [example without MAB 342 etc.](http://test.lobid.org/resources/HT006926058.json) / [original example](http://test.lobid.org/resources/HT007015768.json).
The problem with subfields `k` and `b` from the comment above will be handled in https://github.com/hbz/lobid-resources/issues/855 as I already solved it there for `altLabel`.

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
I informed the cataloging expert who wished for this feature that it now works and asked her to spread the word.
