### ISSUE TITLE
Alias `jsonl` format param for bulk downloads

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#861]
See https://github.com/hbz/lobid-gnd/issues/91#issuecomment-399025937

**Comment by fsteeg** [comment]
Deployed to stage, see:

http://stage.lobid.org/resources/search?q=ehrenfeld&format=jsonl
http://stage.lobid.org/resources/search?q=ehrenfeld&format=bulk

**Comment by acka47** [comment]
+1
