### ISSUE TITLE
Clean up definition of labels

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#864]
While I solved the problem of some wrong labels in https://github.com/hbz/lobid-resources/issues/855 it occurred to me that the label definition isn't well defined. There are multiple definitions for `@preferredName` which contains labels for contributing entities as well as subjects. Also the blocks with `@agentId100` etc. could be probably be cleaned up.

**Comment by TobiasNx** [comment]
Still a problem in ALMA-Fix?

**Comment by TobiasNx** [comment]
This was an issue of the old morph transformation. Not relevant anymore. Closing.
