### ISSUE TITLE
Configure fields of "deletions" index for kibana

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#870]
Result of hbz/lobid-gnd#66.

To create nice stats the more index fields be typed as `number` (or even more accurate: `date`) the better.
See [ES-docs for possible types](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/mapping-types.html). There is no need to change the format of the values e.g. of the field `describedBy.deleted` -  it seems to be sufficient to just configure the index to:

> "type": "date", 
> "format": "yyyyMMdd"

(https://www.elastic.co/guide/en/elasticsearch/reference/5.6/date.html)

**Comment by dr0i** [comment]
Changed the type to `date` and reindexed the `deletion`-index with the new index-config-settings.
Added upon that index a new visualizing "lobid-resouces: Tägliche Löschungen seit 2018-03".

**Comment by acka47** [comment]
+1. Closing.
