### ISSUE TITLE
Switch type to "date" for "publication.startDate"

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#873]
Follows #869.

Like #871 switch the type from "text" to "date".

**Comment by dr0i** [comment]
Added two kibana views "lobid-resources: Einstellungsjahr von Publikationen" and "lobid-resources: Ersterscheinungsjahr von Publikationen".

**Comment by ChristophEwertowski** [comment]
Made a ticket for discussing / looking after unusual data in Kibana: https://github.com/hbz/lobid-resources/issues/898. Therefore I'm closing this issue.
