### ISSUE TITLE
Add role edt for string "editor"

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#877]
See e.g. http://lobid.org/resources/TT050425530

**Comment by acka47** [comment]
Also "author", e.g. http://lobid.org/resources/TT050437294

**Comment by ChristophEwertowski** [comment]
And "contributor", "founder" and "attributed name" (whatever that means), e.g. http://lobid.org/resources/HT017915083 and probably other resources. As discussed these roles should appear in subfield b and not in subfield a. I guess that it is/was a systematic problem from some publishers, at least Springer and NEBIS. Therefore I'm now running our statistic creation tool on MAB 100-132 and 200-212 to find all resources who have `\[.*\]` in the subfields for labels. Searching with the query language didn't work. If I have the data I will speak to our Verbund collegues.

**Comment by ChristophEwertowski** [comment]
Forwarded to Mrs. Block. Maybe it will be dealt with before the migration to a new library system. By the way: http://lobid.org/resources/HT017953814 is a nice example.

**Comment by TobiasNx** [comment]
We should check if there are authors/creators without role and how to fix this in ALMA-Fix.

**Comment by TobiasNx** [comment]
```
<datafield tag="700" ind1="1" ind2=" ">
<subfield code="a">Tang, Jie</subfield>
<subfield code="4">oth</subfield>
<subfield code="e">editor</subfield>
</datafield>
<datafield tag="700" ind1="1" ind2=" ">
<subfield code="a">Du, Jianfeng</subfield>
<subfield code="4">oth</subfield>
<subfield code="e">editor</subfield>
</datafield>
<datafield tag="700" ind1="1" ind2=" ">
<subfield code="a">Pan, Jeff Z.</subfield>
<subfield code="4">oth</subfield>
<subfield code="e">editor</subfield>
</datafield>
<datafield tag="700" ind1="1" ind2=" ">
<subfield code="a">Yu, Yong</subfield>
<subfield code="4">oth</subfield>
<subfield code="e">editor</subfield>
</datafield>
```

At the moment we only transform marcRel $4. The initial example shows that $4 and $e do not always fit together.

In my opinion this perhaps could be done with a more systematic and check string provided in $e.

**Comment by TobiasNx** [comment]
Introduced in ALMA FIX with https://github.com/hbz/lobid-resources/pull/1853
