### ISSUE TITLE
Support RSS as response format for search requests

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#887]
Inspired by https://www.hughrundle.net/2018/03/25/watching-the-feeds/

> RSS has been around for so long, there's a chance your library catalogue includes it as a feature. This may be more useful than you imagine, because RSS in library catalogues commonly hooks in to searches: effectively it allows you to subscribe to a particular set of search parameters.

**Comment by fsteeg** [comment]
Deployed to stage. Tested in Firefox and Thunderbird.

Auto-discovery via header link is set up, most RSS clients are able to use the normal search URLs: 
http://stage.lobid.org/resources/search?q=hochschulbibliothekszentrum

RSS can be explicitly requested via `Accept` header and `format=rss`: 
http://stage.lobid.org/resources/search?q=hochschulbibliothekszentrum&format=rss

Updated documentation:
http://stage.lobid.org/resources/api#content_types

**Comment by ChristophEwertowski** [comment]
+1
