### ISSUE TITLE
Set dates with in day time statements to yyyyMMdd

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#894]
Yesterday I sent the Verbundgruppe a list of `dateCreated` which were transformed to "00010101" because we don't cover the contents of the field. Today Mrs. Bl. told me that we should also cover the time information up to seconds because they are valid.

**Comment by dr0i** [comment]
Ok. I suggest to use a regex in morph making all dates following the pattern `yyyyMMdd`.

**Comment by dr0i** [comment]
re pattern: we could also expand the "normal" pattern found in resources to `yyyyMMddhhmmss` but I don't think it's worth the effort considering that maybe 0,01% have the anormal date-pattern.

**Comment by ChristophEwertowski** [comment]
The short version is good enough. Also if someone found a date with "hhmmss" in the json they would probably think that the rest of the files are missing something.

**Comment by dr0i** [comment]
All done, closing.
