### ISSUE TITLE
Labels aren't transferred to web/conf/context.jsonld

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#897]
See title. Pascal already tested it by removing a class which didn't have any effect on the web/conf/context.jsonld file.

**Comment by dr0i** [comment]
See #899.

**Comment by ChristophEwertowski** [comment]
Will be dealt with in https://github.com/hbz/lobid-resources/pull/884.

**Comment by dr0i** [comment]
From https://github.com/hbz/lobid-resources/commit/2062ff66c549e0993c3dbfe6b8a4e9c9bde2ebbe : 
> Using "name" instead of "label" makes the labels exported to context.json.

Closing.
