### ISSUE TITLE
Strange data in Kibana views

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#898]
There is some strange data which we should look into:

- University of Bielefeld has the second biggest collection after the University of Cologne and before Münster and Bonn? Maybe the reason for this is base-search.net. Update: We don't know for sure. There are ~580.000 resources with medium `Miscellaneous` compared with ~220.000 in Cologne and ~210.000 in Münster. The UB Bielefeld is quite big but Münster has many small libraries sprinkled at the whole city. So I suppose the guess is still BASE.
- `publication.endDate`
   - Why ended so many resources in 1994? (7065)
   - Look into resources which ended before 1700 as there weren't that many periodicals around back then. Update: Apperantly I was wrong. I stopped at 1650.
- `publication.startDate`
   - No resource before year 1000? See https://github.com/hbz/lobid-resources/issues/558.
   - Why the drop between 2009 and 2010 from about 1/3 to 1/2?
- `describedBy.dateCreated`
   - August 1984, December 1993 and November 1999 are the peaking months. Where there some changes in the library management system besides imports?
   - Why were so many resources created in 1994? (~3,2 million over the second biggest result ~1,8 million)
- `describedBy.dateModified`: Why were so many resources modified in 2007?
- `describedBy.provider.id`: The second most active provider is DE-292 which doesn't appear in lobid-organisations or the "[ISIL-Verzeichnis](http://sigel.staatsbibliothek-berlin.de/suche.html?tx_sbbyaz_pi1[q]=DE-292)". See https://github.com/hbz/lobid-resources/issues/902.

**Comment by ChristophEwertowski** [comment]
I sent an E-Mail to the Verbundgruppe with the request for sending explanations for extreme data which wasn't already covered.

**Comment by acka47** [comment]
Closing
