### ISSUE TITLE
Querying /resource endpoint should not return items

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#9]
Currently it does, e.g. with this query: `?q=TT003059252`

**Comment by fsteeg** [comment]
Do you mean resources are returned where items match (not 'items are returned') in the current lobid-resources (1.x, in the hbz/lobid repo)? Then I'd suspect this is related to the index profile (see https://github.com/hbz/lobid/issues/283), see:

http://test.lobid.org/resource?q=TT003059252&format=full
http://lobid.org/resource?q=TT003059252&format=full

**Comment by acka47** [comment]
Sorry for the confusion. This issue and repo is about lobid API 2.0 and I opened the issue after taking a look at the 2.0 index.  See e.g. http://gaia.hbz-nrw.de:9200/lobid-resources-20160121-145835/_search?q=TT003059252%27.

We can already differ resource and item search by indicating the type, though, e.g.:

http://gaia.hbz-nrw.de:9200/lobid-resources-20160121-145835/json-ld-lobid/_search?q=TT003059252%27

vs.

http://gaia.hbz-nrw.de:9200/lobid-resources-20160121-145835/json-ld-lobid-item/_search?q=TT003059252%27

We will just have to think about how the API will handle this.

**Comment by fsteeg** [comment]
Ah, I see.

I think a natural query would be `q=TT003059252 AND type: Item` (with the current data you linked to it would be `q=TT003059252 AND type.@id: http\:\/\/purl\.org\/vocab\/frbr\/core%23Item`). That would work with JSON like:

```
type: ["Item"]
```

Instead of:

```
type: [{ 
  @id: "http://purl.org/vocab/frbr/core#Item"
}]
```

Could we map things like `Item` to `http://purl.org/vocab/frbr/core#Item` in the context?

Would be also interesting for #10, see `type` and `role` in https://github.com/hbz/lobid-resources/issues/10#issuecomment-174447850.

**Comment by acka47** [comment]
Yes, you can also map classes to shorter strings, see example 14 at https://www.w3.org/TR/json-ld/#specifying-the-type. We indeed should do so in API 2.0. I will open a separate issue at https://github.com/hbz/lobid-rdf-to-json.

**Comment by acka47** [comment]
We decided to implement the two endpoints `lobid.org/resources/` vs. `lobid.org/items/` as we have now in the production system. This will allow for easily doing the default queries for resources without items.

**Comment by dr0i** [comment]
See also lobid#293 and #289.

**Comment by dr0i** [comment]
Using the plural form `items` endpoint, see e.g. http://lobid.org/resources-staging/TT003059252 .

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by dr0i** [comment]
Reopened as this issue is not solved in whole.

**Comment by dr0i** [comment]
With #110 (which incorporates #hbz/lobid-rdf-to-json#26) it's possible to query the `resources` index like this: http://aither.hbz-nrw.de:9200/resources-staging/_search?q=CT002006357%20AND%20type:Item.

**Comment by acka47** [comment]
In API 1.0 items are generally not returned as results. You can only reach them by directly looking ub the item URI. This is what I actually meant with this issue. Perhaps we should first discuss whether this should also be the behaviour of API 2.0.

**Comment by dr0i** [comment]
Yes, and there are other possibilities. I write them down so we can discuss them. You wrote at https://github.com/hbz/lobid-resources/issues/9#issuecomment-188786748:

> We decided to implement the two endpoints lobid.org/resources/ vs. lobid.org/items/ as we have now in the production system. This will allow for easily doing the default queries for resources without items.

Which is possible (did some apache magic rewriting stuff):
http://lobid.org/resources?q=CT002006357
http://lobid.org/items?q=CT002006357

Now this is what you described what you would have liked to expect at some point in the developement of API 2.0. But, considering loosing the endpoint distinction (`resources` vs. `items`) we need another approach, though.

And we have:
http://staging.lobid.org/items/_search?q=CT002006357%20AND%20type:Item (same as http://staging.lobid.org/items/_search?q=CT002006357)
http://staging.lobid.org/resources/_search?q=CT002006357

**Comment by acka47** [comment]
We will discuss this with @fsteeg next week and decide on how API 2.0 should work with regard to manifestations and items.

**Comment by acka47** [comment]
As discussed today the current solution works well. Closing.
