### ISSUE TITLE
MAB 070 doesn't only contain Sigel

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#902]
Until now we believed that only Sigel are in MAB 070 and therefore can be changed to ISILs and lobid-organisation links. Sadly there are ~750.000 resources with "292" as a provider which is the "Bibliotheksnummer" of the DNB ([query](http://lobid.org/resources/search?q=describedBy.provider.id%3A%22http%3A%2F%2Flobid.org%2Forganisations%2FDE-292%23%21%22)). 
I will look at the first twenty results of the Kibana visualisation and test if they are plausible. Since we can guess that most of the entries have Sigel in this field we could maybe adjust the morph. But I will ask our collegues if the field can't be changes to "(DE-)101" if that's the only case.

**Comment by ChristophEwertowski** [comment]
Of all delivering institutions which are shown in the pie chart (down to 0,59%) the only "Bibliotheksnummer" is the mentioned "292". Because of this I talked to Mrs. Bü. about it and suggested to change the number to the right DNB Sigel "101". She approved this and I sent an email to Mrs. Sch. at the end of the corridor that it should be changed for the resource before the change to a new library management system.

**Comment by TobiasNx** [comment]
Is this still an issue in ALMA?

**Comment by acka47** [comment]
> is this still a problem?

Yes, it is. See the [query from the original comment](http://lobid.org/resources/search?q=describedBy.provider.id%3A%22http%3A%2F%2Flobid.org%2Forganisations%2FDE-292%23%21%22) in test.lobid.org:

http://test.lobid.org/resources/search?q=describedBy.provider.id%3A%22http%3A%2F%2Flobid.org%2Forganisations%2FDE-292%23!%22

**Comment by acka47** [comment]
Apparently this was not fixed upstream as promised in 2018, so we should approach this in the fix (replacing DE-292 in `describedBy.provider.id`, with DE-191).

**Comment by TobiasNx** [comment]
@acka47 still a problem:

query results in 0:
http://lobid.org/resources/search?q=describedBy.provider.id%3A%22http%3A%2F%2Flobid.org%2Forganisations%2FDE-292%23!%22

**Comment by acka47** [comment]
This is fixed. It is expected that the query does not have any results. Closing.
