### ISSUE TITLE
Wrong type 'Family' added to subjects

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#904]
Reported by W.G. via email on 2018-08-10.

When one subject has type 'Family', all other subjects get type 'Familiy' in addition to their actual type.

See: http://lobid.org/resources/search?q=subject.componentList.type%3AFamily&format=json

**Comment by dr0i** [comment]
Deployed to staging, see e.g. http://stage.lobid.org/resources/HT006699267.json.

**Comment by acka47** [comment]
+1
