### ISSUE TITLE
Update sigel2isil.csv

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#907]
Requested by Stephani S. today in person and via email:

> Die Konkordanz Sigel - ISIL ist super:
> https://raw.githubusercontent.com/hbz/lobid-resources/master/src/main/resources/sigel2isilMap.csv
> 
> Wir benötigen sie dringend und haben nun die Bitte ob ihr sie zeitnah 
> aktualisieren könnt.
> 
> Aufgefallen ist mir beim Prüfen eines Titeldatensatzes :-)
> 
> a)
> In der Konkordanz fehlen noch einige Sigel - ISILS. Das kommt daher, 
> dass die Sigel-Owner-Konkordanz des Verbundes im letzten Jahr 
> Aktualisierungen erhalten hat.
> Die aktuelle Sigel-Owner-Konkordanz des Verbundes ist hier zu finden:
> 
> https://wiki1.hbz-nrw.de/display/VDBE/Liste+der+Sigel+und+Owner+der+hbz-Verbundbibliotheken
> 
> als 
> <https://wiki1.hbz-nrw.de/download/attachments/146178143/Sigelliste.pdf?version=1&modificationDate=1535608695557> 
> pdf oder rtf, Stand: 30.08.2018
> 
> Beispiel:
> 61/90 DE-61-90
> 61/93 DE-61-93
> 
> 
> b)
> Einige Sigel - ISILS sind nicht in dem Sigelverzeichnis der ZDB zu 
> finden, also gar nicht zugelassen :-)
> Das nur zur Information. Für die Konkordanz sollten natürlich wie gehabt 
> alle vorhanden sein (und alle sollten eigentlich bei der Sigelstelle in 
> Berlin  beantragt sein...).
> 
> Beispiele:
> 61/08 DE-61-08
> 61/22 DE-61-22
> 61/25 DE-61-25
> 61/26 DE-61-26
> 61/27 DE-61-27
> ....
> 
> Mit der Bitte um zeitnahe Aktualisierung Eurer Konkordanz anhand unserer 
> aktuellen Sigelliste...,

**Comment by acka47** [comment]
After transforming it to tsv, we now have a well structured Sigel file from the Verbundgruppe, see https://gist.github.com/acka47/f27425c7ff058dab40739f485d2b2ba7. @dr0i could you please make a list of all Sigels in that file that are missing in https://github.com/hbz/lobid-resources/blob/master/src/main/resources/sigel2isilMap.csv

**Comment by acka47** [comment]
Siehe auch [hier](https://wiki1.hbz-nrw.de/display/VDBE/Liste+der+Sigel+und+Owner+der+hbz-Verbundbibliotheken?focusedCommentId=311590924#comment-311590924).

**Comment by acka47** [comment]
I just noticed that the Sigels don't occur on their own in the file from Verbundgruppe. I tried to separate them semiautomatically. The result is at https://gist.github.com/acka47/3b5d9a15cc0a4a608ea852cbd3f4003c. We now have to find out which values in this list do not occur in https://github.com/hbz/lobid-resources/blob/master/src/main/resources/sigel2isilMap.csv

**Comment by dr0i** [comment]
@acka47 you can inform Stephani S. that the csv is up to date now.
