### ISSUE TITLE
Setup of dumping of aleph MabXml catalog

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#91]
The origin of the data resides in an aleph system. That's an sql oracle db. There's a column storing the data as MabXml clobs.
To get the data a script exists which dumps this column.
This script is now mantained by us alone.

Aim is to get:
- [x] a fulldump, once per week 
- [x] incremental updates, daily 

Todo:
- [x] make backups of programs, store them on other server
- [x] versionizing of the programs using git
- [x] wire crontab
- [x] setup mail notifications about the dump results

See also lobid/lodmill#465, lobid/lodmill#538.

**Comment by fsteeg** [comment]
This seems to be interfering with the current production setup, see: https://github.com/hbz/lobid/issues/312#issuecomment-234886661

**Comment by dr0i** [comment]
Issue was fixed by change order of execution: first copy, then move.
It's reflected in the commit `755a19c3adaff4a7dd7027c0f7295626aaaceb34` at the new internally git-server `git@gaia:/files/open_data/closed/gitServer/hbz-aleph-dumping`.

**Comment by fsteeg** [comment]
Reassigned corresponding pull request https://github.com/hbz/mabxml-elasticsearch/pull/33, same for this.

**Comment by dr0i** [comment]
Since https://github.com/hbz/mabxml-elasticsearch/pull/33 is merged, I take it this is +1 from your side.
Closing.
