### ISSUE TITLE
Update dataset desrciption for consumption by google 

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#913]
See https://www.blog.google/products/search/making-it-easier-discover-datasets/

The test tool finds some errors, see https://search.google.com/structured-data/testing-tool#url=http%3A%2F%2Flobid.org%2Fresources%2Fdataset. Mainly:

- [x] use `schema:name` instead of `rdfs:label`. (I guess we can do this on dataset level although we use rdfs:label as generic label property in the actual data.)
- [x] use `schema:distribution` instead of `dcat:distribution`

The test tool also doesn't like `dcat:Distribution`. schema.org only has [`DataDownload`](https://schema.org/DataDownload) which does not really fit for the API which may be used to get a complete dump but rather offers access to the dataset via subsets.

**Comment by acka47** [comment]
> The test tool also doesn't like `dcat:Distribution`. schema.org only has [`DataDownload`](https://schema.org/DataDownload) which does not really fit for the API which may be used to get a complete dump but rather offers access to the dataset via subsets.

@danbri, can you say something about this? While `dcat:Distribution` comprises APIs (see https://www.w3.org/TR/vocab-dcat/#class-distribution) it isn't clear that `DataDownload` also covers APIs. Maybe it would be best to update the description of https://schema.org/DataDownload.

 (I just now discovered the [mappings](https://www.w3.org/wiki/WebSchemas/Datasets#Mappings) where `dcat:Distribution` is maped to `schema:DataDownload` but most people won't go there.)

**Comment by danbri** [comment]
how about https://schema.org/WebAPI ?

we have an issue open for integrating it with dataset description... so a
bit experimental (Google SDTT may complain) but worth discussion

Dan
