### ISSUE TITLE
Agents without label

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#916]
Reported by @jschnasse via chat that there is an empty agent in https://lobid.org/resources/HT019746251.json:

```json
{
  "contribution":[
    ...
    {
      "agent":{
        "type":[
          "CorporateBody"
        ]
      },
      "role":{
        "id":"http://id.loc.gov/vocabulary/relators/cre",
        "label":"Autor/in"
      },
      "type":[
        "Contribution"
      ]
    }
  ]
}
```

This is not the only case, we have around 2700 `agent` objects in the `contribution` array that only have a `role` and a `type` but neither `id` nor `label`: [http://lobid.org/resources/search?q=*&nested=contribution:_exists_:contribution.agent.type+AND+_exists_:contribution.role+AND+NOT+_exists_:contribution.agent.id+AND+NOT+_exists_:contribution.agent.label](http://lobid.org/resources/search?q=*&nested=contribution:_exists_:contribution.agent.type+AND+_exists_:contribution.role+AND+NOT+_exists_:contribution.agent.id+AND+NOT+_exists_:contribution.agent.label) (Most of them are [of type `CorporateBody`](http://lobid.org/resources/search?q=*&nested=contribution:contribution.agent.type:CorporateBody+AND+_exists_:contribution.role+AND+NOT+_exists_:contribution.agent.id+AND+NOT+_exists_:contribution.agent.label).)

Generally, there are a lot of entries in the `contribution` array that only have a `label` and not `id`, see http://lobid.org/resources/search?q=*&nested=contribution:_exists_:%20contribution.agent.label%20AND+NOT+_exists_:contribution.agent.id.

So what is so speciall about these 2700? I will find out.

**Comment by acka47** [comment]
It looks like `ind1="a"` is the problem, from the example (HT019746251):

```xml
<datafield tag="204" ind1="a" ind2="1">
  <subfield code="a">Myelom- und Lymphomhilfe Österreich</subfield>
</datafield>
```

As far as I can see, `a` should not be used with indicator 1 in 2--, see the [MAB documntation](http://www.dnb.de/SharedDocs/Downloads/DE/DNB/standardisierung/mabTitelBibliographischeDaten2001.txt?__blob=publicationFile):

```
200       NAME DER 1. KOERPERSCHAFT IN ANSETZUNGSFORM

          Indikator:
          blank = Name des 1. Urhebers
                  Haupteintragung
          b     = Name des 1. Urhebers oder der 1. sonstigen
                  beteiligten Koerperschaft
                  einteilige Nebeneintragung
          c     = Name des 1. Urhebers oder der 1. sonstigen
                  beteiligten Koerperschaft
                  ein- und zweiteilige Nebeneintragung
          e     = Name des 1. Interpreten
                  einteilige Nebeneintragung
```

**Comment by acka47** [comment]
@jschnasse Can you please point the colleagues to this and ask them if I am correct and this is really not correctly catalogued?

**Comment by acka47** [comment]
Bei HT019272732 ist es ein anderes Problem als der falsche Indikator.

[JSON](http://lobid.org/resources/HT019272732.json):

```json
{
  "contribution":[
    {
      "agent":{
        "type":[
          "ConferenceOrEvent"
        ]
      },
      "role":{
        "id":"http://id.loc.gov/vocabulary/relators/ctb",
        "label":"Mitwirkende"
      },
      "type":[
        "Contribution"
      ]
    }
  ]
}
```

[MABXML](http://lobid.org/hbz01/HT019272732):

```xml
<datafield tag="200" ind1="-" ind2="1">
  <subfield code="e">Nihongo Kyôiku Shinpojiumu</subfield>
  <subfield code="n">1</subfield>
  <subfield code="d">1996-nen 9-gatsu</subfield>
  <subfield code="c">Leuven</subfield>
</datafield>
<datafield tag="200" ind1="b" ind2="2">
  <subfield code="k">
Association of Japanese Language Teachers in Europe
  </subfield>
  <subfield code="4">isb</subfield>
  <subfield code="3">Herausgebendes Organ</subfield>
  <subfield code="9">(DE-588)1116978326</subfield>
</datafield>
```

Es ist seltsam, dass es hier zwei 200er Einträge gibt mit verschiedenen Körperschaften. Keine davon taucht im JSON auf.

**Comment by acka47** [comment]
Weitere `ind1="a"`-Beispiele:

- TT003863752: [JSON](http://lobid.org/resources/TT003863752.json), [MABXML](http://lobid.org/hbz01/TT003863752)
- TT003561680: [JSON](http://lobid.org/resources/TT003561680.json), [MABXML](http://lobid.org/hbz01/TT003561680)

**Comment by acka47** [comment]
Bei HT018291103 gibt es wieder ein anderes Problem:

[MABXML](http://lobid.org/hbz01/HT018291103):

```xml
<datafield tag="200" ind1="e" ind2="1">
  <subfield code="a">Radio Berlin</subfield>
</datafield>
```

**Comment by acka47** [comment]
TT003251346, [MABXML]():

```xml
<datafield tag="200" ind1="-" ind2="2">
  <subfield code="k">
Evangelische Brüder-Unität Herrnhut und Bad Boll / Direktion
</subfield>
```

**Comment by acka47** [comment]
TT003561680 hat sogar zwei leere `contribution`-Objekte. Aus dem [MABXML](http://lobid.org/hbz01/TT003561680):

```xml
<datafield tag="200" ind1="-" ind2="1">
  <subfield code="a">Commission of the European Communities</subfield>
</datafield>
<datafield tag="204" ind1="a" ind2="1">
  <subfield code="a">Deutschland <Bundesrepublik> / Umweltbundesamt</subfield>
</datafield>
```

**Comment by acka47** [comment]
BTW, the original example https://lobid.org/resources/HT019746251.json from Publisso is now working after it was corrected (and I think even a new GND entry was created).

**Comment by acka47** [comment]
As there are different underlying problems probably most of them cataloging errors and only 2700 resources are affected, I am moving this to the backlog for now.

**Comment by TobiasNx** [comment]
We could check if this is relevant for ALMA-Fix and filter out all without labels.

**Comment by TobiasNx** [comment]
@acka47 This seems to be no problem with ALMA-FIX: https://github.com/hbz/lobid-resources/pull/1437. Should we close this ticket, since we do not fix the ALEPH-Transformation.

**Comment by acka47** [comment]
> Should we close this ticket, since we do not fix the ALEPH-Transformation.

Yes. Closing. Thanks for the pointer!
