### ISSUE TITLE
NWBib errors with resources-staging index

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#92]
https://test.nwbib.de/ uses http://lobid.org/resources-staging/

Some detail pages result in errors, see:

https://test.nwbib.de/HT018833649
https://test.nwbib.de/HT018776640

The logged error sounds like at some point, a string is expected in the JSON, but an array found.

@dr0i Are you aware of any such changes in the current resources 2.0 staging index?

**Comment by dr0i** [comment]
There only exist a small resources-staging (not as alias), see http://quaoar1.hbz-nrw.de:9200/_plugin/head/ . Last updates were made at 13th July. Does this help?

**Comment by fsteeg** [comment]
Hm, if I remember correctly, we had a general redirect that would allow to use the index name in the path, so `http://lobid.org/resources-staging/*` would redirect to an index called (or aliased) 'resources-staging', but I don't see anything like that in `lobid.org.conf`.

Do we have a full staging index for resources 2.0 that we could use in nwbib-staging to test changes?

**Comment by dr0i** [comment]
`Staging == master` as I said there are no active branche , so there a separate staging index makes no sense. You could delete the resources-staging index and add an alias to the resources index.

**Comment by fsteeg** [comment]
There are no notification for edits, it's better to add a comment.

I think we used to have a permanent staging index, so we would not have to change settings when we deploy changes to test them through nwbib. But maybe I'm wrong, and maybe it's not useful. Right now there's nothing to test, so I won't do anything and just configure nwbib-staging to use the normal resources 2.0 index.

I was mainly irritated about the redirect, but since what I thought was in place is not actually there, the issue seems to be very different: the configured index does not exist, nwbib falls back to API 1.x for details, which fails for certain resources. It all makes sense now :-) Will open an issue in nwbib and close this one.

**Comment by dr0i** [comment]
Ah - I wouldn't know about the fallback. Nice ( but then ;) )

**Comment by dr0i** [comment]
> just configure nwbib-staging to use the normal resources 2.0 index

I would rather make user that there is *always* a staging , using an alias on the master if no separate staging exists. I think you remeber right that there should always be one.
Since you don't need the broken old staging-index I delete it and make add an alias to `resources`.

**Comment by dr0i** [comment]
> Since you don't need the broken old staging-index

I mean: for debugging purposes

> There are no notification for edits, it's better to add a comment.

Reminds me to always preview my comments, count to 10, reread, make tea make coffe, comment at least.

**Comment by dr0i** [comment]
Done the alias setting.
Again, you were right in expecting a full staging index. The two aliases on one index in case of no active branch copies the behaviour used for API1.0 , see http://quaoar2.hbz-nrw.de:9200/_plugin/head/.
Will keep an eye on it in the future.
