### ISSUE TITLE
Document update process

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#931]
Requested by @jschnasse / Publisso users. They want to know when hbz01 to lobid updatea start and can be expected to have ended each day. It is probably to create a Wiki site (in German) for this.

**Comment by jschnasse** [comment]
Is 4.30h really the time when everything is ready? Our clients impression is, that it is often more like around 11.00h .

**Comment by dr0i** [comment]
It depends on what was changed. I updated the wiki-page:

> Folgende Änderungen bedingen eine komplette Reindizierung:
> *   Löschungen von Datensätzen
> *  Änderungen in der ETL (Extract-Transformation-Load) Konfiguration (z.B. Zufügen/Löschen eines MAB-Feldes; oder welche Felder durchsuchbar sein sollen)

If you _just add a new document_ it is expected to be etl'ed at 4:30.

**Comment by jschnasse** [comment]
Wann müssen Indexe geswitched werden? Nur bei den Vollabzügen? Erfolgt das manuell?

**Comment by dr0i** [comment]
Genau. Habe die Wikiseite angepasst.

**Comment by dr0i** [comment]
Fragen geklärt, Ticket geschlossen.
