### ISSUE TITLE
Set up elasticsearch 2.3.3 gaia-aither cluster

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#94]
Since the elasticsearch 2.3.3 on quaoar1 makes trouble (couldn't index the third fulldump, got a timeout;  sometimes indexing produces a timeout (see #93); hickups experienced in nwbib may be the result of this) there should be a cluster on gaia and aither.

**Comment by dr0i** [comment]
Installing of ES is straightforward, except for getting rid of:

> [WARN ][bootstrap] Increase RLIMIT_MEMLOCK, soft limit: 65536, hard limit: 65536
> [WARN ][bootstrap] These can be adjusted by modifying /etc/security/limits.conf, for example: # allow user 'elasticsearch' mlockall

Because 1. this was not enough and 2. different things must be done on different os (debian and ubuntu).
.One should update the `elasticsearch.yml` with `bootstrap.mlockall: true`, then
adapt the mentioned ` /etc/security/limits.conf` like:

    elasticsearch   soft    nofile          1048576
    elasticsearch   hard    nofile          1048576
    elasticsearch   soft    memlock         unlimited
    elasticsearch   hard    memlock         unlimited

(and maybe also for user `root`), then add `session required pam_limits.so` into `/etc/pam.d/common-session` and  execute `sysctl -p`, maybe exit and relogin, update also `/etc/default/elasticsearch`. Restart with `service elasticsearch restart` and you should be fine on ubuntu.
On debian however I had to follow the [instructions provided by @markwalkom](https://github.com/elastic/elasticsearch/issues/9357#issuecomment-70590934):

> edit /usr/lib/systemd/system/elasticsearch.service and set  LimitMEMLOCK=infinity
> Then: systemctl daemon-reload ; service elasticsearch restart

**Comment by dr0i** [comment]
Having an fulldump index build this night on aither with clustername `aither` this index must vanished when restarting the ES instance as part of the cluster `gaia-aither`. But by first stop ES, then `cd /var/lib/elasticsearch; mv aither gaia-aither` and restarting ES the index was there in 2 minutes and began to mirror to gaia :)

Indexing the updates of this week no timeout experienced. 

mabxml-elasticsearch

**Comment by fsteeg** [comment]
+1

**Comment by dr0i** [comment]
Deployed and used for production lobid-resources 2.0, closing.
