### ISSUE TITLE
Switch from our own jsonConverter to java-json-ld

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#940]
Now that the [jsonld-java](https://github.com/jsonld-java/jsonld-java) is mature we can switch to it and dumb our own rolled [JsonConverter](https://github.com/hbz/lobid-resources/commit/58e12319c383c7dbd39746125d14ffe9d67d2dc6#diff-74aa8810cbd6cefd40393b40c3e9ecaf).

**Comment by dr0i** [comment]
To be in sync with the data structure we published as our [lobid-resources API 2.0](https://lobid.org/resources/api) the [setting of the type-alias as @container:@set`](https://github.com/jsonld-java/jsonld-java/pull/243) is needed.

**Comment by dr0i** [comment]
Solved the `@container:@set` issue with jsonld-java/jsonld-java#243.
#942 remains to be solved before switch.

**Comment by acka47** [comment]
I just took a look at the [MAB-XML of HT013395076](http://lobid.org/hbz01/HT013395076) to see whether I maybe see the problem. What looks suspicious is the call number in 088.c as it has a weird underscore that is not an underscore. Pasting it here it becomes an underline:

```
<subfield code="c">HIS 39.2 2002/2-18̲3</subfield>
```

Maybe this is the root of the indexing problem?

**Comment by dr0i** [comment]
@acka47 no, well, it's more complicated than that, what I meant with
> While the latter doc can be etl'ed in principal

is "this file itself is not the cause of the problem".
I am on it - by learning how to identify MapperParserExceptions.

**Comment by acka47** [comment]
Ah, ok. Just to understand the problem correctly: Just the "l" (load = indexing) of the ETL is the problem here, isn't it?

**Comment by dr0i** [comment]
The "t" is the troublemaker for MapperParsingExceptions when doing "l" - but your are right, it's not "e".  Concerning the mere _existence_ of a resource (here: HT013395076) also the "e" could be the source of trouble - so it's better to to check the whole workflow (aka "etl").

**Comment by dr0i** [comment]
@acka47 you're genius! By you insisting to know at which processing-stage the problem could appear you made me think a bit more of the "l" (load) process. We just left the *deletions* out of our musing! And voila - comparing the old index (build 20181226 thus with deletions only up to that date):
http://www.lobid.org/resources/deletions/search?q=describedBy.deleted%3A[20181226+TO+20190107]
=> 491 deleted.
(The difference of the amount of docs of the two indices is exactly "484" (http://lobid.org/resources/search?q=* - http://stage.lobid.org/resources/search?q=*)).

*Conclusion*:
484 were missing. As 491are deleted => in the new index are 7 docs *more* than in the old one!
So, the MapperParsingException(MPE) must (after all) prevent the indexing of only _one_ of the resources, not the _whole_ bulk request (this conforms also with my analysis so far re MPE - Elasticsearch in trace-mode shows exactly that).

So, IMO we can merge. @acka47 ?

**Comment by acka47** [comment]
+1
