### ISSUE TITLE
Cover all MARC relators in morph and labels.json

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#941]
From #933:

> Generally, there exist 268 different relator codes, see http://id.loc.gov/vocabulary/relators.html. In the morph, roles are handled separately for persons (see [lines 812 to 990](https://github.com/hbz/lobid-resources/blob/d6395ab8b57f862136f21e36791311591ed87bc7/src/main/resources/morph-hbz01-to-lobid.xml#L812-L990) of the current morph) and corporate bodies (see [lines 1011 to 1061](https://github.com/hbz/lobid-resources/blob/d6395ab8b57f862136f21e36791311591ed87bc7/src/main/resources/morph-hbz01-to-lobid.xml#L1011-L1061)).

> According to https://www.loc.gov/marc/relators/relaterm.html most relators can apply to corporate bodies as well as to persons. The coverage currently is:
- 15 roles for corporate bodies
- 54 roles for persons (as well as an additional two non-MARC roles)

> I know I asked Christoph whether we can not implement a general approach in the moprh for mapping the three-character strings in the data to the MARC relator URI (e.g. `dgs` --> `http://id.loc.gov/vocabulary/relators/dgs`). This only works where the codes are actually existent, i.e. for the records complying to RDA. However there are a lot of additional mappings from earlier used strings to relatores (e.g. `<regexp match="Vorwort|^win$" format="http://id.loc.gov/vocabulary/relators/win"/>
`). Maybe @dr0i can have a look into mapping every code to the URI. 

And:

> As there are German labels in the source data, there obviously already is a translation list. So I did some research.

> I think the terms are based on the "Arbeitshilfe AH-017" that is currrently available in version 1.7 (and of course as PDF) see https://wiki.dnb.de/download/attachments/106042227/AH-017.pdf. 

> There is also a VuFind config file at https://github.com/vufind-org/vufind/blob/master/config/vufind/author-classification.ini#L312-L591 based on an earlier revision (1.5) of AH-017 and with gendered labels.

**Comment by acka47** [comment]
Is this still a problem with MARC21 from Alma, @TobiasNx ? Did you encounter anything like this. If not, please close the issue.

**Comment by TobiasNx** [comment]
I dont think so, also we introduced all marc-relators with: https://github.com/hbz/lobid-resources/pull/1293 and also use this in ALMA-Fix.
