### ISSUE TITLE
Jsonld: problems with componentList

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#942]
Following #940 results in following issue:
```json
 {
    "type" : [ "ComplexSubject" ],
    "http://www.loc.gov/mads/rdf/v1#componentList" : {
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#first" : {
        "type" : [ "SubjectHeading" ],
        "label" : "Umweltschutz"
      },
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest" : {
        "@list" : [ {
          "id" : "_:b4",
          "type" : [ "SubjectHeading", "CorporateBody" ],
          "label" : "Kall"
        } ]
      }
},
```
(see https://github.com/hbz/lobid-resources/blob/523-addLanguageTagSupport/src/test/resources/jsonld/BT000110055)
although the [context](https://github.com/hbz/lobid-resources/blob/523-addLanguageTagSupport/web/conf/context.jsonld#L265) is provided properly (I think).
Prolems are:
- the componenList-URI is not shortcutted
- the  bnodes of the list (...#first and ...#rest) are shown
- '@list' is printed somehow
- '_:b4' : forget about that. This expected behaviour since this bnode is used multiple times in the resource. and thus MUST be shown (ref to specs needed). Solution is to modify name of the bnode so that they only occur once.

**Comment by dr0i** [comment]
@acka47 you may want to have a look. If you are interested in the ntriples from which this json is produced:
'mvn clean install -DgenerateTestData=true; find . -name BT000110055.nt'.

**Comment by acka47** [comment]
I reproduced the same problem using our json-cli fork at https://github.com/hbz/jsonld-cli. i think there is something wrong with the context.

**Comment by acka47** [comment]
Found the problem with the context. It uses `"type"` in five places where it should be `"@type"`. You can not use the alias in the context itself. Fixed it with https://github.com/hbz/lobid-resources/commit/9e00d3a90350437c9508d86d8512d951a46b54da. But this does not resolve the original problem I think.

**Comment by dr0i** [comment]
Aha, interesting. If you use the java-jsonld library there occurs now even _more_ strangeness than before (the datatype given in @type are not aliased anymore) , so I think you just found another bug in java-jsonld.

**Comment by dr0i** [comment]
Merged in https://github.com/hbz/lobid-resources/pull/948. Closing.
