### ISSUE TITLE
051 |z should be typed "Miscellaneous"

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#943]
Requested by FRL customers, via [Jira](https://jira.hbz-nrw.de/browse/FRL-234?focusedCommentId=204987&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-204987):

> wir haben einige Dokumente, welche wir gern bewusst dem Publikationstypen "Sonstige" zuweisen möchten. Dafür möchten wir gern folgenden Standard vorschlagen (MAB-Kategorien):
```xml
<controlfield tag="050">||||||||g|||||</controlfield>
<controlfield tag="051">mz||||||</controlfield>
```
> Das "z" an der zweiten Position im Feld MAB-051 soll bewirken, dass eine Ressource den Publikationstyp "Sonstige" erhält.

> Wir haben bereits eine Ressource dahingehend als Beispiel geändert. Zurzeit wird sie noch als "Buch" angezeigt: http://lobid.org/hbz01/HT019488427

The proposal looks good as `z` is meant for "sonstige Veroeffentlichungsart/-inhalt". From the [MAB documentation](http://www.dnb.de/SharedDocs/Downloads/DE/DNB/standardisierung/mab2FormatSatzkennungSegment000Nov2001.txt?__blob=publicationFile):

```
051     VEROEFFENTLICHUNGSSPEZIFISCHE ANGABEN ZU BEGRENZTEN
        WERKEN
...
          1-3  Veroeffentlichungsart und Inhalt
...
                 z = sonstige Veroeffentlichungsart/-inhalt
```

**Comment by dr0i** [comment]
This is deployed 5 minutes ago. Nonetheless have a look at it ( http://lobid.org/resources/HT019488427) @acka47 and close the issue if +1.

**Comment by acka47** [comment]
+1 Closing.
