### ISSUE TITLE
Move lobid's start page from being a play app to static webfiles

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#947]
Working on https://github.com/lobid/lodmill/issues/802 we discovered that we cannot shutdown the lobid-1.0 API because it is still solely serving lobid's startpage (http://lobid.org/).
So we should move that page to this repo.
It's exepected that after this and some removings in the apache-conf "test.lobid.org" will also work fine, nomore serving 503.

**Comment by fsteeg** [comment]
We discussed two other options on the phone:

- Trim down the lobid repo/play-app to serve only the main page
- Serve the main page as a static page in apache

Moving the main page into one of the 3 services seems arbitrary to me.

In general, this is not particularly urgent, as the main point about shutting down the old API is freeing the Elasticsearch cluster, which we are ready to do after https://github.com/lobid/lodmill/issues/802 is done.

Reassigning @dr0i as I think the static apache option would make most sense.

**Comment by dr0i** [comment]
Done, see https://lobid.org. 
Also, copied the `team's` page to static html sites.

**Comment by dr0i** [comment]
(todo: revision these static files)

**Comment by fsteeg** [comment]
Two issues:

- I don't think https://lobid.org should redirect to https://lobid.org/index-en.html or https://lobid.org/index-de.html
- The clouds nav bar background / CSS is missing (also missing at http://lobid.org/resources and http://lobid.org/organisations)

**Comment by dr0i** [comment]
Re clouds: solved with a symbolic link.

Re language-dependent start-site:
Best I could came up with is:
- hitting the root the language-header is used to determine which site to serve while keeping the root URL ( https://lobid.org)
- the other links, language-header-independently, serve the wanted pages (https://lobid.org/index-en.html or https://lobid.org/index-de.html). These URL are transparent in that you always get what you asked for, regardless of the language-header.
So, best of two worlds :)
(See here my lost struggle to even get the language-header-independent-pages to the root URL https://serverfault.com/questions/947496/rewrite-url-and-setting-accept-language-header.)

**Comment by fsteeg** [comment]
> hitting the root the language-header is used to determine which site to serve while keeping the root URL (https://lobid.org)

Seems to work only for http://lobid.org, not for https://lobid.org

**Comment by dr0i** [comment]
You sure? I test this ok even for https://www.lobid.org. Also, configs look ok. Your cache clean?

**Comment by acka47** [comment]
It works for me as expected in Firefox but I do get a redirect to https://lobid.org/index-de.html in Chromium. Curl looks fine:

```
$ curl -IL -H "Accept-Language: de" https://lobid.org
HTTP/1.1 200 OK
Date: Mon, 07 Jan 2019 09:53:37 GMT
Server: Apache/2.4.10 (Linux/SUSE)
Last-Modified: Thu, 27 Dec 2018 16:34:07 GMT
ETag: "140d-57e0383f21500"
Accept-Ranges: bytes
Content-Length: 5133
Vary: Accept-Encoding
Content-Type: text/html; charset=utf-8
```

This is strange.

**Comment by acka47** [comment]
BTW, looking at the console I get a warning: 

> Mixed Content: The page at 'https://lobid.org/index-de.html' was loaded over HTTPS, but requested an insecure image 'http://lobid.org/assets/images/clouds.jpg'. This content should also be served over HTTPS.

**Comment by fsteeg** [comment]
I had a redirect in Firefox (even in a new private window) before, but now it's fine both in Chromium and Firefox.

**Comment by acka47** [comment]
It works for me in Chrome and in a private Chromium window. So the problem must be because of caching or because of me using a language switcher addon.

**Comment by dr0i** [comment]
We discussed offline to revision lobid's landing page as static webfiles in lobid's repo. Will reopen an issue there.
