### ISSUE TITLE
"owner" parameter not working

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#949]
Reported today by API user:

> Heute musste ich leider feststellen, dass der bulk-Download keine Treffer mehr liefert. Das scheint an dem "Owner"-Parameter zu liegen und kann an dem Beispiel "Einschränkung auf Bestand in Bibliotheken" aus der API-Dokumentation nachvollzogen werden:

> <http://lobid.org/resources/search?q=kunst&owner=DE-290%2CDE-294&format=json>

This is probably due to https://github.com/hbz/lobid-resources/commit/8d5385b03622934bf0ee65f85519157d2c3e1275 and hopefully can easily be fixed.

**Comment by fsteeg** [comment]
Switched `resources` alias to `resources-20181226-0100` index until this is fixed.

**Comment by fsteeg** [comment]
Deployed to stage:

http://stage.lobid.org/resources/search?q=kunst&owner=DE-290%2CDE-294&format=json

**Comment by acka47** [comment]
+1
