### ISSUE TITLE
Switch to metafacture 5

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#954]
Team lobid decided to see if an update to [metafacture](https://github.com/metafacture/metafacture-core) version 5 is achievable in reasonable time. Also we decided to see what plugins or other code we use in our fork may be provided.

**Comment by dr0i** [comment]
The only difference between the `5.0.1-hbz` branch and the metafacture master is the addition of ObjectThreader:
https://github.com/metafacture/metafacture-core/commit/7151b070f78f6796153aeef841c7bdcf437ff651
Going to add a junit test to the Threader and then open a PR against metafacture/metafacture-core.

**Comment by dr0i** [comment]
@fsteeg I deliberately did not yet merge the branch `5.0.1-hbz` into our metafacture-master because of possible sideeffects in other repos using https://github.com/hbz/metafacture-core. Do you use this or is it safe to merge into master?

**Comment by fsteeg** [comment]
> The only difference between the 5.0.1-hbz branch and the metafacture master is the addition of ObjectThreader

Then this should not cause any issues where it's used. However I don't get how this updates to `5.0.1` then.

**Comment by dr0i** [comment]
This updates by declaring the 5.0.1-hbz branch in the pom.xml of lobid-resource.
You are right, it should be safe, but remember it is not an update based of the hbz-metafacture, so _if_ in this fork any programs reside which are not in metafacture-master _and_ used by any repos I don't know of (and thus not be tested) this would be bad.
Since my tests were good I merge it into master and change the pom.xml of the lobid-resource.

**Comment by dr0i** [comment]
Done updating the pom.xml, closed.
