### ISSUE TITLE
Provide metafacture plugin checking structural consistence of a JSON document

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#956]
We encounter several issues of structural inconsistence of json documents, see e.g. #904. As these may break our API it would be nice to check the integrity of that json  _before_ adding it to an index rather than being informed by customers if an error occurs.

This could be done with a metafacture plugin.

**Comment by acka47** [comment]
Looks like a job for JSON schema: https://json-schema.org/

**Comment by dr0i** [comment]
Yes, and this java-implementation of validator should be fine: https://github.com/java-json-tools/json-schema-validator.

**Comment by dr0i** [comment]
@acka47 are you willing to provide a schema for lobid-resources?

**Comment by acka47** [comment]
>  are you willing to provide a schema for lobid-resources?

I opened another issue for this: #1079

**Comment by acka47** [comment]
@fsteeg, please move issue to metafacture-core

**Comment by fsteeg** [comment]
> @fsteeg, please move issue to metafacture-core

Closing, moved to https://github.com/metafacture/metafacture-core/issues/347
