### ISSUE TITLE
Add subfield t to label for subjects

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#960]
Reported by NWBib customer E.L. on 2019-01-28:

> in der SW-Anzeige unserer NWBib-Titelaufnahmen sind zwei Fehler 
> aufgetaucht, die vielleicht ohne großen Aufwand behoben werden können. 
> Es scheint immer ein Anzeigeproblem zu geben, wenn bei Werktiteln (TS 
> Sätze) ein Unterfeld hinzukommt.
> 
> Schlagwörter als Werktitel von Urhebern: Hier wird das Unterfeld 
> fälschlicherweise abgeschnitten https://nwbib.de/HT017749491. Bei diesem 
> Beispiel wird die Körperschaft „Nordrhein-Westfalen“ angezeigt, aber das 
> Unterfeld t „Landeshundegesetz“ fehlt. Weiteres Beispiel: 
> https://nwbib.de/HT019775759

From the JSON of these examples.

[HT017749491](http://lobid.org/resources/HT017749491.json):

```
{
   "type":[
      "ComplexSubject"
   ],
   "componentList":[
      {
         "id":"http://d-nb.info/gnd/4756230-4",
         "type":[
            "CorporateBody",
            "Work"
         ],
         "label":"Nordrhein-Westfalen"
      },
      {
         "type":[
            "SubjectHeading"
         ],
         "label":"Kommentar"
      }
   ],
   "label":"Nordrhein-Westfalen: Landeshundegesetz | Kommentar"
}
```

The correct label would be "Nordrhein-Westfalen: Landeshundegesetz" (as in the label for the whole `ComplexSubject`).

[HT019775759](http://lobid.org/resources/HT019775759.json):

```json
{
   "type":[
      "ComplexSubject"
   ],
   "componentList":[
      {
         "id":"http://d-nb.info/gnd/1163739820",
         "type":[
            "CorporateBody",
            "Work"
         ],
         "gndIdentifier":"1163739820",
         "source":{
            "id":"http://d-nb.info/gnd/7749153-1",
            "label":"Gemeinsame Normdatei (GND)"
         },
         "label":"Nordrhein-Westfalen"
      }
   ],
   "label":"Nordrhein-Westfalen: Alten- und Pflegegesetz Nordrhein-Westfalen"
}
```

Here the label for the complex subject's element should be the same as in the complex subject's label: "Nordrhein-Westfalen: Alten- und Pflegegesetz Nordrhein-Westfalen"

**Comment by acka47** [comment]
@dr0i As the label is already correct in the `subject.label`, here is the commit where Christoph added it: cfd60df53457113c1bf8ab621fd91f1c331b68c6 It probably makes sense to reuse something from this.

**Comment by dr0i** [comment]
Deployed to staging, see e.g. http://stage.lobid.org/resources/HT017749491.json.

**Comment by acka47** [comment]
+1
