### ISSUE TITLE
Reorder subject label for works

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#961]
Reported by NWBib customer E.L. on 2019-01-28:

> Anonyme Werktitel mit Unterfeldern. Hier werden die Unterfelder nicht 
> abgeschnitten sondern umgestellt https://nwbib.de/HT019434345. Statt in 
> der Reihenfolge „Poetica, Zeitschrift, München“ wird das Unterfeld 
> „Zeitschrift, München“ nach vorn gestellt. Weiteres Beispiel 
> https://nwbib.de/HT018284162

Example [HT019434345](http://lobid.org/resources/HT019434345.json) (snippet):

```json
{
   "componentList":[
      {
         "id":"http://d-nb.info/gnd/1139450719",
         "type":[
            "Work"
         ],
         "gndIdentifier":"1139450719",
         "source":{
            "id":"http://d-nb.info/gnd/7749153-1",
            "label":"Gemeinsame Normdatei (GND)"
         },
         "label":"Zeitschrift, München: Poetica"
      }
   ],
   "label":"Ruhr-Universität Bochum, Germanistisches Institut | Zeitschrift, München: Poetica | Gründung | Geschichte 1966-1967  "
}
```

- `subject.componentList.label` should be: "Poetica, Zeitschrift, München"
- `subject.label` should accordingly be: "Ruhr-Universität Bochum, Germanistisches Institut | Poetica, Zeitschrift, München | Gründung | Geschichte 1966-1967  "

**Comment by dr0i** [comment]
Deployed to staging, see e.g. http://stage.lobid.org/resources/HT019434345.json.

**Comment by acka47** [comment]
Hmm, you chose a colon as delimiter: `Poetica: Zeitschrift, München` 

I suggested a comma: `Poetica, Zeitschrift, München`
DNB does this (see [here](http://d-nb.info/gnd/1139450719)): `Poetica (Zeitschrift, München)`

I think we should stick with the comma (`Poetica, Zeitschrift, München`) as E.L. wrote it down like this in the email and this is also what it looks like in the Aleph OPAC. But it is ok to already deploy it on production for now and push the changes on Thursday.

**Comment by dr0i** [comment]
Deployed to staging, see e.g. http://stage.lobid.org/resources/HT019434345.json.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.

**Comment by acka47** [comment]
Reopening as we did not resolve the whole issue. From the original comment:

> `subject.label` should accordingly be: "Ruhr-Universität Bochum, Germanistisches Institut | Poetica, Zeitschrift, München | Gründung | Geschichte 1966-1967"

I did not do a good review job there.

**Comment by TobiasNx** [comment]
This needs to be done in ALMA-FIX too:

```
  <datafield tag="689" ind1="0" ind2="1">
    <subfield code="a">Poetica</subfield>
    <subfield code="g">Zeitschrift, M&#252;nchen</subfield>
    <subfield code="D">u</subfield>
    <subfield code="0">(DE-588)1139450719</subfield>
    <subfield code="0">(uri) https://portal.dnb.de/opac.htm?method=simpleSearch&amp;cqlMode=true&amp;query=idn=1139450719</subfield>
    <subfield code="0">(uri) http://viaf.org/viaf/sourceID/DNB|1139450719</subfield>
  </datafield>
```

**Comment by TobiasNx** [comment]
@acka47 :
I used the way DNB formats these with ALMA-Fix, since I formatted all other SChlagwortfolgen-subjects as DNB did in https://github.com/hbz/lobid-resources/issues/1556:    

```
 {
      "type": [
        "ComplexSubject"
      ],
      "label": "Ruhr-Universität Bochum. Germanistisches Institut | Poetica (Zeitschrift, München) | Gründung | Geschichte 1966-1967",
```

I hope this is okay.

**Comment by acka47** [comment]
Looks good to me. +1
