### ISSUE TITLE
Change order of matching "coverage" to wikidata

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#964]
To match "coverage" with wikidata entities we use an index (geo_nwbib) and a manually created table. Atm the matching algorithmus starts with using the index and, having no success, using the table. It should be the other way round.

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by dr0i** [comment]
Something went wrong with the geo-index.

**Comment by dr0i** [comment]
Deployed to staging, see e.g. http://stage.lobid.org/resources/search?q=Q1457938.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
