### ISSUE TITLE
Some "coverage" are ignored => no spatial enrichment

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#965]
Reported by NWBib customer I.N. "Frielinghausen - fehlende Titel":
E.g. http://lobid.org/resources/HT019394322.json has a coverage but no spatial field.

**Comment by dr0i** [comment]
Updated  https://wiki1.hbz-nrw.de/display/SEM/Datenaktualisierungsrhythmen.

**Comment by dr0i** [comment]
Uh, something went wrong. The index is not whole, and the index-name is missing the date of creation.

**Comment by dr0i** [comment]
had two entries, now it's only one entry setting to "Tue, Sat".

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
