### ISSUE TITLE
Wikidata matching is broken

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#970]
It looks like https://github.com/hbz/lobid-resources/blob/master/src/main/resources/string2wikidata.tsv is currently not used for the matching. See the following examples that have a value from the list in "coverage" but no "spatial" entry:

- http://lobid.org/resources/BT000059523.json
- http://lobid.org/resources/BT000008649.json

**Comment by acka47** [comment]
I updated the title as no matching is done, neither using the list or the ES index. Result: "spatial" fields only in 1049 lobid-resources: http://lobid.org/resources/search?q=_exists_%3Aspatial

**Comment by dr0i** [comment]
Uh - threads #967 ! Making things faster - and also introduces new kinds of error sources. In this case, teh fix will be easy.

**Comment by dr0i** [comment]
Deployed as "hot fix".

**Comment by dr0i** [comment]
Fix in master, closing.
