### ISSUE TITLE
Wrong ID for deleted resources?

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#971]
Taking a look again at the example for deleted resources on the [API page](http://lobid.org/resources/api#query-syntax), I noticed that the ID we use for the resources is probably not correct. From the [example query](http://lobid.org/resources/deletions/search?q=describedBy.deleted%3A%5B20180328+TO+20180405%5D):

```json
{
   "@context":"http://lobid.org/resources/context-deletions.jsonld",
   "describedBy":{
      "deleted":"20180329",
      "alephInternalSysnumber":"021709679",
      "id":"http://lobid.org/resources/TT003577000",
      "label":"hbz01 mabxml resource"
   },
   "id":"http://lobid.org/resources/TT003577000#!"
}
```

As the label reads "hbz01 mabxml resource" and the current URI in "id" does not give anything back, shouldn't it be http://lobid.org/hbz01/TT003577000 ind the "id" field?

**Comment by acka47** [comment]
Furthermore, the behaviour is strange when I go to the "deletions endpoint": http://lobid.org/resources/deletions

**Comment by dr0i** [comment]
The structure seems to be intended, see https://github.com/lobid/lodmill/issues/258#issuecomment-363430346.

**Comment by dr0i** [comment]
Discussed offline:
Instead of `"label":"hbz01 mabxml resource"` use `"label":"lobid resource description"`.
As this
1. doesn't change anything important
2. needs a complete reindexing

the issue is postponed.

**Comment by dr0i** [comment]
As #976 also needs a reindexing these issues should be solved together so one reindexing would suffice.

**Comment by TobiasNx** [comment]
@dr0i ist the deleted ressources API a thing for ALMA?

**Comment by dr0i** [comment]
I don't even know _if_ this information is somehow transported by the Alma dump. Also, maybe custo,mers can use the Alma-Api to get deletions? I don't know. Let's see if some customer demands it.
I would close this, but as @acka47 opened the issue I assign him and ask for closing.

**Comment by acka47** [comment]
Closing
