### ISSUE TITLE
Broken "deletions" indexing

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#976]
Since 2019-02-23 04:00 the documents meant fpr the `deletions` index are not properly build. A rogue-process was running for two days and added most probably too many documents (status quo last week: 80k,  this week: 200k).
What's also smelling:
This brings up 1081 docs: http://lobid.org/resources/deletions/search?q=describedBy.deleted:[20190101%20TO%2020190110]
Adding a month brings up the exact amount:
http://lobid.org/resources/deletions/search?q=describedBy.deleted:[20190101%20TO%2020190210]

**Comment by dr0i** [comment]
Well : 

> Note to self: don't forget to use `-DkeyToGetMainId="id"` for deletions in crontab.

(source  https://github.com/hbz/lobid-resources/pull/948#issuecomment-450356338)

I know I had given it some thought two weeks later but I thought this was obsolete by then. Sigh. Yeah, a test would be fine. So there _is_ a test regarding deletions it doesn't test everything. Cough (which test does?).
However.

I am going to push this as a hot-fix.
Also, keep in mind that atm the `deletion`-index is somewhat broken since early 2019-01, so the index should be completely rebuild. This _is_ possible, because I discovered we kept all the update-files of 2018 up to today.

**Comment by dr0i** [comment]
Deployed, see e.g. http://lobid.org/resources/deletions/search?q=describedBy.deleted%3A[20190201+TO+20190224].

**Comment by dr0i** [comment]
So, since end of February the documents are good again.

Posponed the rebuilding of the index (to fill the gap between January and February).

**Comment by acka47** [comment]
Closing
