### ISSUE TITLE
Wrong staging index

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#977]
Today, there was a index called "resources-staging" (not alias but actual name with a small size but with more documents than smalltest) used for stage.lobid.org. The alias "resources-staging" could only be applied to the new lobid-resources index "resources-20190227-0100" after deleting "resources-staging".

Maybe this is a problem with #968?

**Comment by dr0i** [comment]
Yes I was aware of this (I had forgotten to reset the crontab for developing purpose and so a fullindex was build which I cancelled unfinished). This behaviour will not occur anymore since I fixed the crontab last week.
Closing.
