### ISSUE TITLE
Configure skohub-deck to show subjects inbox

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#992]
As #986 sends lobid resources' subjects to its inbox we may want to configure a [skohub-deck](https://github.com/hbz/skohub-deck) to actually see what's happening.

**Comment by acka47** [comment]
I just started it on my local machine, listening to ["Geschichte"](http://test.lobid.org/gnd/4020517-4
). (See the instructions by @literarymachine at https://github.com/hbz/skohub-pubsub/pull/12#issuecomment-487892404.) As far as I can see, I can only subscribe to one topic for now.

As there were [seven resources with that subject heading added yesterday](http://lobid.org/resources/search?q=subject.componentList.id%3A%22http%3A%2F%2Fd-nb.info%2Fgnd%2F4020517-4%22+AND+describedBy.dateCreated%3A20190502), these should be send to the inbox today, am I right?

**Comment by acka47** [comment]
And it works:

![Bildschirmfoto vom 2019-05-03 11-25-35](https://user-images.githubusercontent.com/160292/57129297-4021f500-6d96-11e9-8c2b-ffe33d24d15f.png)

**Comment by dr0i** [comment]
Great! Remains the question if we would like to setup a skohub-deck for it. I still think that would be nice.

**Comment by dr0i** [comment]
Great! Closing.
